To be specific, following the pattern of the equations (4.50) and (4.51), let us define \(\lambda_{h}(g_{h})\) and \(\lambda_{h}^{0}\) by:

(4.62) \[\left\{\begin{aligned} \lambda_{h}^{0}\in\mathcal{O}_{h}, \quad\quad(\mathbf{grad}\,\lambda_{h}^{0},\mathbf{grad}\,q_{h})=(\mathbf{u}_{h }^{0},\mathbf{grad}\,q_{h})\quad\quad\forall q_{h}\in\mathcal{O}_{h},\\ \lambda_{h}(g_{h})\in\mathcal{O}_{h},\quad\quad(\mathbf{grad}\, \lambda_{h}(g_{h}),\mathbf{grad}\,q_{h})=(\mathbf{u}_{h}(g_{h}),\mathbf{grad} \,q_{h})\quad\quad\forall q_{h}\in\mathcal{O}_{h}.\end{aligned}\right.\]

Then

\[\lambda_{h}=\lambda_{h}^{0}+\lambda_{h}(\rho_{h})\]

and we have an alternate expression for the bilinear form \(a_{h}(\cdot,\,.)\).

**Lemma 4.4**.: _We have:_

(4.63) \[a_{h}(g_{h},l_{h})=(\mathbf{grad}\,\lambda_{h}(g_{h})-\mathbf{u}_{h}(g_{h}), \mathbf{grad}\,l_{h})\quad\quad\forall g_{h},\,l_{h}\in G_{h}.\]

_Likewise, the right-hand side of (4.52) reads:_

(4.64) \[(\mathbf{u}_{h}^{0},\mathbf{grad}\,p_{h}(l_{h}))=\;-(\mathbf{grad}\,\lambda_{ h}^{0}-\,\mathbf{u}_{h}^{0},\mathbf{grad}\,l_{h})\quad\quad\forall l_{h}\in G _{h}.\]

Proof.: By definition and (4.51) we have:

\[a_{h}(g_{h},l_{h}) =\,v(\mathbf{grad}\,\mathbf{u}_{h}(g_{h}),\mathbf{grad}\,\mathbf{ u}_{h}(l_{h}))=\;-(\mathbf{grad}\,p_{h}(l_{h}),\mathbf{u}_{h}(g_{h}))\] \[=\;-(\mathbf{grad}(p_{h}(l_{h})-l_{h}),\mathbf{u}_{h}(g_{h}))-( \mathbf{grad}\,l_{h},\mathbf{u}_{h}(g_{h}))\] \[=\;-(\mathbf{grad}\,\lambda_{h}(g_{h}),\mathbf{grad}(p_{h}(l_{h} )-l_{h}))-(\mathbf{grad}\,l_{h},\mathbf{u}_{h}(g_{h}))\]

by (4.62). Then (4.51) implies that

\[a_{h}(g_{h},l_{h})=(\mathbf{grad}\,\lambda_{h}(g_{h})-\mathbf{u}_{h}(g_{h}), \mathbf{grad}\,l_{h}),\]

thus proving (4.63). The proof of (4.64) is similar. 

Hence the Problem (4.52) takes the more manageable form:

_Find \(\rho_{h}\) in \(G_{h}\) such that_:

(4.65) \[(\mathbf{grad}\,\lambda_{h}(\rho_{h})-\mathbf{u}_{h}(\rho_{h}),\mathbf{grad} \,l_{h})=(\mathbf{grad}\,\lambda_{h}^{0}-\,\mathbf{u}_{h}^{0},\mathbf{grad}\, l_{h})\quad\quad\forall l_{h}\in G_{h}.\]

From the preceding lemma and the definition of the bilinear form \(a_{h}(\cdot,\,.)\) we know that the left-hand side of (4.65) is a bilinear, symmetric and positive definite form on \(G_{h}\times\,G_{h}\). Let us show briefly how (4.65) is solved in practice; the reader will find more details in Glowinski _et al._, Chapter 13 [37].

Assume that the nodes of \(\mathcal{T}_{h}\cap\Gamma\) are numbered from \(1\) to \(N_{h}\) and let \(\left\{\mu\right\}_{1\leq i\leq N_{h}}\) be the set of basis functions of \(Q_{h}\) defined by:

\[\mu_{i}(a_{i}) =1\quad\text{for each node $a_{i}$ of $\mathcal{T}_{h}\cap\Gamma$},\] \[\mu_{i}(b_{k}) =0\quad\text{for all other nodes of $\mathcal{T}_{h}$}.\]

Then (dropping for the moment the condition \(\int_{\Gamma}g_{h}\,ds=0\)) the functions \(g_{h}\) of \(G_{h}\) have the expression:
