(3.27) \[\lim_{h\to 0}\sup_{\lambda\in\,\alpha}\varepsilon_{h}(\lambda)=0\]

_and_

(3.28) \[\lim_{\alpha\to 0}\left\{\sup_{\lambda\in\,\alpha}L_{h}(\lambda;\alpha)\right\}=0 \quad\text{uniformly for all }h\leq h_{0},\]

_where \(h_{0}\) is the parameter of Lemma 3.4, then there exist two real constants \(\alpha>0\) and \(h_{1}>0\) and a function \(u_{h}\!\in\!\mathcal{C}^{0}(\Lambda;X)\) such that for all \(h\leq h_{1}\):_

(3.29) \[\{(\lambda,u_{h}(\lambda));\lambda\!\in\!\Lambda\}\quad\text{is a branch of }\text{ nonsingular solutions of \eqref{eq:h_0}},\]

_for each \(\lambda\!\in\!\Lambda\), \(u_{h}(\lambda)\) is the only solution of (3.12) in the ball \(S(\tilde{u}_{h}(\lambda);\alpha)\) and we have the bound:_

(3.30) \[\|u_{h}(\lambda)-v\|_{X}\leq 4\gamma(\lambda)\,\|\,F_{h}(\lambda,v)\|_{ \mathcal{X}}\quad\quad\forall v\!\in\!S(\tilde{u}_{h}(\lambda);\alpha).\]

Proof.: According to Lemma 3.4, we know that \(\gamma_{h}(\lambda)\) is bounded above for all \(\lambda\) in \(\Lambda\) and for all \(h\leq h_{0}\). Therefore (3.28) implies that we can find an \(\alpha>0\) such that

(3.31) \[\gamma_{h}(\lambda)L_{h}(\lambda;\alpha)<1/2\quad\quad\forall\lambda\!\in \!\Lambda,\quad\forall h\leq h_{0}.\]

Likewise, (3.27) implies that there exists an \(h_{0}^{\prime}>0\) such that

\[2\gamma_{h}(\lambda)L_{h}(\lambda;2\gamma_{h}(\lambda)\varepsilon_{h}(\lambda ))<1\quad\quad\forall\lambda\!\in\!\Lambda,\quad\forall h\leq h_{0}^{\prime}.\]

Take \(h_{1}=\min(h_{0},h_{0}^{\prime})\). Then it follows from Theorem 3.1 that for all \(\lambda\!\in\!\Lambda\) and all \(h\leq h_{1}\), there exists a \(u_{h}(\lambda)\) in \(X\), unique in \(S(\tilde{u}_{h}(\lambda);\alpha)\), such that:

\[F_{h}(\lambda,u_{h}(\lambda))=0\]

and \(D_{u}F_{h}(\lambda,u_{h}(\lambda))\) is an isomorphism of \(X\) onto \(\mathcal{X}\). In addition Lemma 3.4 and (3.21) yield:

(3.32) \[\|[D_{u}F_{h}(\lambda,u_{h}(\lambda))]^{-1}\|_{\mathcal{L}(\mathcal{X}; \boldsymbol{\lambda})}\leq 4\gamma(\lambda).\]

Similarly, (3.23), (3.26) and (3.31) give (3.30).

Finally, the continuity of \(u_{h}\) with respect to \(\lambda\) is an easy consequence of (3.30), the continuity of \(\tilde{u}_{h}\) and the continuity of \(F_{h}\). 

_Remark 3.2_.: An interesting feature of this proof is that the function \(\tilde{u}_{h}\) is arbitrary. The most obvious choice of function in the present case where \(F\) and \(F_{h}\) are defined on the same space \(X\) is of course \(\tilde{u}_{h}(\lambda)=u(\lambda)\), and this will be used below. When \(F_{h}\) is defined on a space \(X_{h}\) different from \(X\), like in Section 3.4, we shall take for \(\tilde{u}_{h}\) an adequate approximation of \(u\).

_Remark 3.3_.: Theorem 3.2 does not use fully the regularity of \(F\) and \(F_{h}\) with respect to \(\lambda\). When \(\lambda\to\tilde{u}_{h}(\lambda)\) is a \(\mathcal{C}^{p}\)-mapping from \(\Lambda\) into \(X\), it is established in Crouzeix [22] that \(u_{h}\) is also in \(\mathcal{C}^{p}(\Lambda;X)\).
