**Lemma 5.1**.: _Assume that \(\Omega\) is a bounded, convex polygon and \(\mathcal{T}_{h}\) a uniformly regular family of triangulations of \(\bar{\Omega}\). Let \(\phi\!\in\!H^{k+1}(\Omega)\cap H^{1}_{0}(\Omega)\) for some integer \(k\) with \(1\leqslant k\leqslant l\). Then we have the estimate:_

(5.26) \[[\phi-\hat{P_{h}}\phi]_{t}\leqslant C_{t}h^{k-1}\left\|\,\phi\,\right\|_{k+1, \Omega}\ \ \ \ \ \forall t\geqslant 2,\]

_with constants \(C_{t}\) independent of \(h\)._

This lemma is an easy consequence of Theorem A.2 and

(5.27) \[[\phi_{h}]_{t}\leqslant C(t)h^{-1}|\phi_{h}|_{1,\Omega}\ \ \ \ \ \forall\phi_{h}\!\in\!\Phi_{h}.\]

These preliminaries permit to derive some fundamental properties of \(\tilde{a}(\,.\,;.\,,\,.\,)\). First \(\tilde{a}(\,.\,;.\,,\,.\,)\) is bounded.

**Lemma 5.2**.: _Let us retain the assumptions of Lemma 5.1. The form \(\tilde{a}(\,.\,;.\,)\) is bounded as follows, for all \(v_{h}\!\in\!V_{h}\) and all \(z_{h}\), \(u_{h}=(\mathbf{u}_{h}=\mathbf{curl}\,\psi_{h},o_{h})\), \(w_{h}=(\mathbf{w}_{h}=\mathbf{curl}\,\chi_{h},e_{h})\!\in\!X_{h}\):_

(5.28) \[|a_{1}(u_{h};v_{h},\mathbf{w}_{h})|+|a_{2}^{z_{h}}(u_{h};v_{h},\mathbf{w}_{h}) |\leqslant C\left\|\,\mathbf{u}_{h}\right\|_{0,\,4,\,\Omega}|v_{h}|\left\|\, \mathbf{w}_{h}\right\|_{0,\,4,\,\Omega}.\]

_Proof_. Let \(v_{h}=(\mathbf{curl}\,\phi_{h},\theta_{h})\) belong to \(V_{h}\). By Holder's inequality, we have:

\[|a_{1}(u_{h};v_{h},\mathbf{w}_{h})|\leqslant C_{1}|\psi_{h}|_{1,\,4,\,\Omega} |\chi_{h}|_{1,\,4,\,\Omega}\!\left(\sum_{\kappa\in\,\mathcal{T}_{h}}|\phi_{h} |_{2,\,\kappa}^{2}\right)^{1/2}.\]

Thus (5.21) gives:

\[|a_{1}(u_{h};v_{h},\mathbf{w}_{h})|\leqslant C_{2}\left\|\,\mathbf{u}_{h} \right\|_{0,\,4,\,\Omega}|v_{h}|\left\|\,\mathbf{w}_{h}\right\|_{0,\,4,\, \Omega}.\]

Next, consider \(a_{2}^{z_{h}}(u_{h};Pv_{h},\mathbf{w}_{h})\) with \(Pv_{h}=(\mathbf{curl}\,\phi,\theta_{h})\). As \(\phi\) belongs to \(H^{2}(\Omega)\), the surface integrals in \(a_{2}(\,.\,;.\,,\,.\,)\) vanish over all interior segments \(\kappa^{\prime}\) of \(\mathcal{T}_{h}\) and since \(u_{h}\) belongs to \(X_{h}\) the factor \(\mathbf{curl}\,\psi_{h}\cdot\mathbf{n}\) vanishes on all boundary segments of \(\mathcal{T}_{h}\). Hence

(5.29) \[a_{2}^{z_{h}}(u_{h};Pv_{h},\mathbf{w}_{h})=0,\]

so that

\[|a_{2}^{z_{h}}(u_{h};v_{h},\mathbf{w}_{h})|=|a_{2}^{z_{h}}(u_{h};v_{h}-Pv_{h}, \mathbf{w}_{h})|.\]

Therefore

\[|a_{2}^{z_{h}}(u_{h};v_{h},\mathbf{w}_{h})| \leqslant C_{3}\!\left(\sum_{\kappa\in\,\mathcal{T}_{h}}\left\| \,\mathbf{curl}\,\psi_{h}\right\|_{0,\,4,\,\partial\kappa}^{4}\right)^{1/4}\] \[\quad\times\left(\sum_{\kappa\in\,\mathcal{T}_{h}}\left\|\, \mathbf{curl}\,\chi_{h}\right\|_{0,\,4,\,\partial\kappa}^{4}\right)^{1/4}\! \left(\sum_{\kappa\in\,\mathcal{T}_{h}}\left\|\,\mathbf{curl}(\phi_{h}-\phi) \right\|_{0,\,\partial\kappa}^{2}\right)^{1/2}.\]

On the one hand a routine application of

\[\left\|\,\theta\,\right\|_{0,\,t,\,\partial\kappa}\leqslant C_{4}(h_{\kappa}^{1 ,t}/\rho_{\kappa})(\left\|\,\theta\,\right\|_{0,\,\kappa}^{2}+\left.h_{\kappa}^ {2}|\theta|_{1,\,\kappa}^{2})^{1/2}\ \ \ \ \ \forall\theta\!\in\!H^{1}(\kappa)\ \ \ \ \ \forall t\geqslant 1,\]
