Suppose \(\Omega\) is partitioned into a finite number of disjoint, Lipschitz-continuous open subsets \(\Omega\), with boundary \(\Gamma_{r}\):

\[\bar{\Omega}=\bigcup_{r=1}^{R}\Omega_{r}.\]

Let \(X_{h}\) and \(M_{h}\) be defined by (1.38) with \(\mathbb{R}\subset Q_{h}\). For \(1\leq r\leq R\) we set:

\[X_{h}(\Omega_{r}) =\{\mathbf{v}\in X_{h};\,\mathbf{v}=\mathbf{0}\text{ in }\Omega- \Omega_{r}\},\] (1.54) \[Q_{h}(\Omega_{r}) =\{q_{|\Omega_{r}};\,q\in Q_{h}\},\] \[M_{h}(\Omega_{r}) =Q_{h}(\Omega_{r})\cap L_{0}^{2}(\Omega_{r}),\] (1.55) \[\overline{M}_{h} =\{q\in L_{0}^{2}(\Omega);\,q_{|\Omega_{r}}\text{ is constant, }1\leq r \leq R\}.\]

Note that the functions of \(X_{h}(\Omega_{r})\) belong to \(H_{0}^{1}(\Omega_{r})^{N}\). We introduce as an assumption the following concept of uniform, local inf-sup condition with respect to this partition:

**Hypothesis H4**.: _There exists a constant \(\lambda^{*}>0,\) independent of \(h\) and \(r,\) such that:_

\[\sup_{\mathbf{v}_{h}\in X_{h}(\Omega_{r})}\left[\frac{\int_{\Omega_{r}}q_{h} \operatorname{div}\mathbf{v}_{h}\,dx}{|\mathbf{v}_{h}|_{1,\Omega_{r}}}\right] \geq\lambda^{*}\|\,q_{h}\|_{0,\Omega_{r}},\quad\quad\forall q_{h}\in M_{h}( \Omega_{r}),\quad\,1\leq r\leq R.\] (1.56)

Let us establish the salient result of this section.

**Theorem 1.12**.: _Let the pair of spaces \((X_{h},M_{h})\) defined by (1.38) satisfy Hypothesis H4. If there exists a subspace \(X_{h}\) of \(X_{h}\) such that the pair \((\overline{X}_{h},\overline{M}_{h})\) satisfies the inf-sup condition (1.12) with a constant \(\overline{\beta}\) independent of \(h,\) then \((X_{h},M_{h})\) also satisfies (1.12) with a constant \(\beta^{*}\) independent of \(h.\)_

Proof.: From the definition (1.54) we derive immediately the _orthogonal_ decomposition of \(Q_{h}(\Omega_{r})\):

\[Q_{h}(\Omega_{r})=M_{h}(\Omega_{r})\oplus\mathbb{R}.\]

Thus each function \(q_{h}\in M_{h}\) can be split as follows:

\[q_{h}=\bar{q}_{h}+\bar{q}_{h},\]

where

\[\bar{q}_{h|\Omega_{r}}=\frac{1}{\operatorname{meas}(\Omega_{r})}\int_{\Omega _{r}}q_{h}\,dx\]

and \(\bar{q}_{r}=\bar{q}_{h|\Omega_{r}}\in M_{h}(\Omega_{r})\). Observe that \(q_{h}\in\overline{M}_{h}\) and that the orthogonality of the decomposition implies:

\[\|q_{h}\|_{0,\Omega}^{2}=\|\,\bar{q}_{h}\|_{0,\Omega}^{2}+\|\,\bar{q}_{h}\|_{0 ,\Omega}^{2}.\] (1.57)

Now, owing to Hypothesis H4 and Remark 1.4 there exists a function \(\tilde{\mathbf{v}}_{r}\in X_{h}(\Omega_{r})\) such that
