The mixed method discussed here and in the next paragraph is derived from these two formulations.

### A Mixed Formulation

Let \(\Omega\) be a bounded domain of \(\mathbb{R}^{2}\) with a Lipschitz-continuous boundary \(\Gamma\) whose components are denoted by \(\Gamma_{i}\,(0\leqslant i\leqslant p)\) like in Figure 2. For \(\mathbf{f}\) given in \(L^{r}(\Omega)^{2}\) with \(r>1\), recall the classical formulation of the Stokes equations in \(\Omega\):

_Find a pair \((\mathbf{u},p)\) in \(H^{1}_{0}(\Omega)^{2}\,\times\,L^{2}_{0}(\Omega)\) such that_

\[\left\{\begin{aligned} & v(\mathbf{grad}\,\mathbf{u},\mathbf{grad}\, \mathbf{v})-(p,\operatorname{div}\mathbf{v})=(\mathbf{f},\mathbf{v})\quad \quad\forall\mathbf{v}\in H^{1}_{0}(\Omega)^{2},\\ &(q,\operatorname{div}\mathbf{u})=0\quad\quad\forall q\in L^{2} _{0}(\Omega).\end{aligned}\right.\] (1)

Since \(\operatorname{div}\mathbf{u}=0\) we have proved in Theorem I.5.5 that

\[(\mathbf{grad}\,\mathbf{u},\mathbf{grad}\,\mathbf{v})=(\operatorname{curl} \,\mathbf{u},\operatorname{curl}\,\mathbf{v})\quad\quad\forall\mathbf{v}\in H ^{1}_{0}(\Omega)^{2}.\] (2)

Thus introducing the vorticity \(\omega\):

\[\omega=\operatorname{curl}\,\mathbf{u},\]

the equations (1) are equivalent to:

_Find a triple \((\mathbf{u},\omega,p)\!\in\!H^{1}_{0}(\Omega)^{2}\,\times\,L^{2}(\Omega)\,\times \,L^{2}_{0}(\Omega)\) solution of_

\[\left\{\begin{aligned} & v(\omega,\operatorname{curl}\,\mathbf{v})-(p, \operatorname{div}\mathbf{v})=(\mathbf{f},\mathbf{v})\quad\quad\forall \mathbf{v}\in H^{1}_{0}(\Omega)^{2},\\ &(\operatorname{curl}\,\mathbf{u}-\omega,\mu)-(q,\operatorname{ div}\mathbf{u})=0\quad\quad\forall\mu\in L^{2}(\Omega),\quad\quad\forall q\in L ^{2}_{0}(\Omega).\end{aligned}\right.\] (3)

Let us put Problem (3) into the framework of Section I.4.1. Set

\[X=H^{1}_{0}(\Omega)^{2}\,\times\,L^{2}(\Omega),\]

equipped with the norm

\[\|(\mathbf{v},\theta)\|_{X}=(|\mathbf{v}|^{2}_{1,\,\Omega}+\,\|\,\theta\|^{2 }_{0,\,\Omega})^{1/2}\quad\quad\forall(\mathbf{v},\theta)\!\in\!X\]

and

\[M=L^{2}(\Omega)\,\times\,L^{2}_{0}(\Omega),\]

normed by:

\[\|(\mu,q)\|_{M}=(\|\,\mu\|^{2}_{0,\,\Omega}+\,\|\,q\|^{2}_{0,\,\Omega})^{1/2} \quad\quad\forall(\mu,q)\!\in\!M.\]

Next, we introduce the bilinear forms:

\[\left\{\begin{aligned} & a((\mathbf{u},\omega),(\mathbf{v}, \theta))=v(\omega,\theta),\\ & b((\mathbf{v},\theta),(\mu,q))=(\operatorname{curl}\,\mathbf{ v}-\theta,\mu)-(q,\operatorname{div}\mathbf{v})\end{aligned}\right.\] (4)

and the right-hand sides \(l\) and \(\chi\) defined by:

\[\langle l,(\mathbf{v},\theta)\rangle=(\mathbf{f},\mathbf{v}),\quad\,\,\,\,\chi =0.\] (5)
