Hence

(3.17) \[\|\,\hat{f}\,\|_{L^{2}(\xi)/P_{0}}\leqslant C_{4}\sigma_{\kappa}^{2}\,|\,\hat{f} \,|_{1,\,\hat{\kappa}}.\]

Next assume that

(3.18) \[\|\,\hat{f}\,\|_{L^{2}(\xi)/P_{j-1}}\leqslant(C_{4}\sigma_{\kappa}^{2})^{j}|\, \hat{f}\,|_{j,\,\hat{\kappa}}.\]

We can write

\[\|\,\hat{f}\,\|_{L^{2}(\xi)/P_{j}} =\inf_{(q,\,\tilde{q})\,\in\,P_{j-1}\times\tilde{P}_{j}}\,\|\, \hat{f}\,+\,q\,+\,\tilde{q}\,\|_{0,\,\hat{\kappa}}\] \[=\inf_{\tilde{q}\,\in\,\tilde{P}_{j}}\inf_{q\,\in\,P_{j-1}}\|( \hat{f}\,+\,\tilde{q})\,+\,q\,\|_{0,\,\hat{\kappa}}\] \[\leqslant(C_{4}\sigma_{\kappa}^{2})^{j}\inf_{\tilde{q}\,\in\, \tilde{P}_{j}}\,|\,\hat{f}\,+\,\tilde{q}\,|_{j,\,\hat{\kappa}}\]

by the induction hypothesis (3.18). Then (3.17) yields:

\[\|\,\hat{f}\,\|_{L^{2}(\xi)/P_{j}}\leqslant(C_{4}\sigma_{\kappa}^{2})^{j+1} \left\{\sum_{|\tilde{a}|=j}|\partial^{\,\tilde{a}}\hat{f}|_{1,\,\hat{\kappa}} ^{2}\right\}^{1/2}.\]

Since the expression in brackets is \(|\,\hat{f}\,|_{j+1,\,\hat{\kappa}}\), this proves (3.18) for all \(j\).

As a consequence, we have:

\[\|\,f-\,\rho_{h}f\,\|_{0,\,\kappa}\leqslant(C_{4}\sigma_{\kappa}^{2})^{k}|\det (B)|^{1/2}\,|\,\hat{f}\,|_{k,\,\hat{\kappa}}\]

and (3.16) follows from (A.7) and the regularity of \(\mathcal{T}_{h}\). 

From Lemma 3.4, (3.15) and Theorem 3.2, we derive the expected estimate for this scheme.

**Theorem 3.3**.: _Let \(\Omega\) be a bounded plane polygon and suppose the solution \((\mathbf{u},p)\) of the Stokes system satisfies:_

\[\mathbf{u}\in[H^{k+1}(\Omega)\cap H_{0}^{1}(\Omega)]^{2},\ \ \ \ \ p\in H^{k}(\Omega)\cap L_{0}^{2}(\Omega)\]

_for some integer \(k\in[1,l]\). If the triangulation \(\mathcal{T}_{h}\) is regular, the solution \((\mathbf{u}_{h},p_{h})\) of (1.39) with the spaces \(X_{h}\) and \(M_{h}\) defined by (3.11) (3.12) has the estimate:_

\[|\mathbf{u}-\mathbf{u}_{h}|_{1,\,\Omega}+\,\|\,p-\,p_{h}\|_{0,\,\Omega} \leqslant C_{1}\,h^{k}\{|\mathbf{u}|_{k+1,\,\Omega}+|p|_{k,\,\Omega}\}.\]

_In addition, if \(\Omega\) is convex we have the \(L^{2}\)-estimate:_

\[\|\,\mathbf{u}-\mathbf{u}_{h}\|_{0,\,\Omega}\leqslant C_{2}\,h^{k+1}(|\mathbf{ u}|_{k+1,\,\Omega}+|p|_{k,\,\Omega}).\]

### An Example of Checkerboard Instability: the \(Q_{1}\) -\(P_{0}\) Element

The most famous example of spaces failing to satisfy the inf-sup condition is that in which the velocity is made of piecewise polynomials of \(Q_{1}^{2}\) and the pressure is piecewise constant on a rectangular grid. This combination is more familiarly
