(3.28) \[\left|\int_{\partial\hat{\kappa}}[\partial(\hat{\phi}-\hat{I}\hat{ \phi})/\partial\hat{x}_{i}]\hat{n}_{j}\hat{\mu}\,ds\right| \leqslant C_{2}[\hat{\phi}]_{l+1,\hat{\kappa}}\|\hat{\mu}\|_{0,\hat{ \kappa}}\] \[\leqslant C_{3}\sigma_{\kappa}^{2}h_{\kappa}^{l-1}|\phi|_{l+1,\kappa}\| \mu_{h}\|_{0,\kappa}.\]

Hence, in order to sharpen this estimate, we must first sum these terms over all elements \(\kappa\) of \(\mathcal{T}_{h}\) and next evaluate their contribution on a given interelement boundary. Thus a better estimate can only be attained if the difference in the factor

\[X_{\kappa}=(1/J_{F})(\partial F_{\kappa}/\partial\hat{x}_{1})(\partial F_{ \kappa}/\partial\hat{x}_{2})\]

arising from two adjacent elements is "small".

To evaluate this difference, let \(\kappa_{1}\) and \(\kappa_{2}\) denote two adjacent elements of \(\mathcal{T}_{h}\). First we remark that, in view of (3.24), it suffices to estimate the difference

\[X_{\kappa_{1}}(a_{1},b_{1})-X_{\kappa_{2}}(a_{2},b_{2})\]

where \((a_{i},b_{i})\) is an arbitrary point of \(\kappa_{i}\). The simplest choice is to pick a convenient point \((a,b)\) on the interface \(\kappa^{\prime}\) between \(\kappa_{1}\) and \(\kappa_{2}\) and to set

\[(a_{1},b_{1})=(a_{2},b_{2})=(a,b).\]



Let \(i\) be the index such that \(\partial F_{\kappa}/\partial\hat{x}_{i}\) is continuous across the interface \(\hat{\kappa}^{\prime}\). Then a straightforward calculation shows that

\[|J_{F_{1}}J_{F_{2}}(X_{\kappa_{1}}-X_{\kappa_{2}})(a,b)|=\|\partial F_{\kappa} (a,b)/\partial\hat{x}_{i}\|^{2}\,\|(\partial F_{\kappa_{1}}/\partial\hat{x}_{ j})\times(\partial F_{\kappa_{2}}/\partial\hat{x}_{j})(a,b)\|\]

where \(j\neq i\). Now, let us choose for \((a,b)\) one of the end points of \(\kappa^{\prime}\) and let \(L_{1}\) and \(L_{2}\) denote the sides of \(\kappa_{1}\) and \(\kappa_{2}\) (other than \(\kappa^{\prime}\)) that meet at \((a,b)\) (cf. Figure 20). It easy to see that

(3.29) \[|J_{F_{1}}J_{F_{2}}(X_{\kappa_{1}}-X_{\kappa_{2}})(a,b)|=\mbox{meas}^{2}( \kappa^{\prime})\mbox{meas}(L_{1})\mbox{meas}(L_{2})|\tau_{1}\cdot\vec{n}_{2}|\]
