_Then_

\[\lim_{h\to 0}\|u-u_{h}\|_{X}=0.\]

**Corollary 1.2**.: _We retain the above hypotheses on \(a(.,.)\) and \(M\) and we assume that \(b(.,.)\) satisfies a uniform inf-sup condition (1.12). If there exists a dense subspace \(\mathcal{X}\) of \(X\) and a mapping \(r_{h}\colon\mathcal{X}\to X_{h}\) satisfying:_

\[\lim_{h\to 0}\|r_{h}v-v\|_{X}=0\ \ \ \ \ \forall v\in\mathcal{X}\]

_then_

\[\lim_{h\to 0}\{\,\|u-u_{h}\|_{X}+\|\lambda-\lambda_{h}\|_{M}\}=0.\]

Now, let us extend the classical duality argument of Aubin [3] and Nitsche [61] to the case of Problems (P) and (P\({}_{h}\)). For this, we introduce a Hilbert space \(H\) with scalar product \((.,.)\) and associated norm \(|.|\) such that

\[X\subset H\text{ with continuous imbedding and }X\text{ is dense in }H.\]

We identify \(H\) with its dual space \(H^{\prime}\) for the scalar product \((.,.)\). Therefore, \(H\) can be identified with a subspace of \(X^{\prime}\):

\[H\subset X^{\prime}\text{ with continuous and dense imbedding.}\]

In order to evaluate \(|u-u_{h}|\), we introduce for each \(g\) in \(H\) the unique solution pair \((\varphi_{g},\xi_{g})\) of the dual problem:

\[\begin{cases}a(v,\varphi_{g})+b(v,\xi_{g})=(g,v)\ \ \ \ \ \forall v\in X\\ b(\varphi_{g},\mu)=0\ \ \ \ \ \forall\mu\in M.\end{cases}\] (1.21)

**Theorem 1.2**.: _Assume that Problem \((\mathrm{P}_{h})\) has a unique solution \(u_{h}\). Then there exists a constant \(C\), depending only upon \(\|a\|\) and \(\|b\|\), such that:_

\[|u-u_{h}| \leq C\left\{\|u-u_{h}\|_{X}+\inf_{\mu_{h}\in M_{h}}\|\lambda-\mu _{h}\|_{M}\right\}\] (1.22) \[\qquad\times\sup_{g\in H}\frac{1}{|g|}\left\{\inf_{\varphi_{h} \in V_{h}}\|\varphi_{g}-\varphi_{h}\|_{X}+\inf_{\xi_{h}\in M_{h}}\|\xi_{g}- \xi_{h}\|_{M}\right\}.\]

Proof.: On the one hand, we have:

\[|u-u_{h}|=\sup_{g\in H}\frac{(g,u-u_{h})}{|g|}.\]

On the other hand by choosing \(v=u-u_{h}\) in (1.21), we get

\[(g,u-u_{h})=a(u-u_{h},\varphi_{g})+b(u-u_{h},\xi_{g}).\] (1.23)

Then taking into account (1.1) and (1.6) we find:

\[a(u-u_{h},\varphi_{h})=-b(\varphi_{h},\lambda)=-b(\varphi_{h},\lambda-\mu_{h} )\ \ \ \ \ \forall\varphi_{h}\in V_{h},\ \ \ \ \ \forall\mu_{h}\in M_{h}.\]
