_This bound is also valid when \(t=2\) and either \(l\geqslant 2\) or \(\psi\) belongs to \(W^{2,\,\infty}(\Omega)\). If \(l=1\) and \(t=2\), the left-hand side of (5.43) is bounded by_

\[C_{2}(\varepsilon)h^{1/2-\varepsilon}\quad\text{for all $\varepsilon>0$}.\]

_In addition, when the mapping \(\lambda\to\psi(\lambda)\) is continuous from \(\Lambda\) into \(H^{m+2}(\Omega)\cap W^{m+3/2,\,\infty}(\Omega)\) for some real \(m\!\in\![1,l-1/2]\) we have:_

(5.44) \[\sup_{\lambda\,\varepsilon\,A}\left\{\left|\psi_{h}(\lambda)-\psi(\lambda) \right|_{1,s,\Omega}+\left\|\,\omega_{h}(\lambda)-\omega(\lambda)\right\|_{0, \Omega}\right\}\leqslant C_{3}h^{m}.\]

Finally, an argument closely resembling that of Section 4.3 permits to refine the error estimate for \(\left|\psi-\psi_{h}\right|_{1,\Omega}\) and obtain the same order of convergence as Theorem 4.5.

**Theorem 5.2**.: _Let \(\Omega\) and \(\mathcal{T}_{h}\) be like in Theorem 5.1 and assume that the branch of nonsingular solutions of the Navier-Stokes Problem (5.7) has the regularity:_

\[\lambda\to\psi(\lambda)\!\in\!\mathcal{C}^{0}(\Lambda;H^{l+1}(\Omega))\quad \text{for $l\geqslant 2$}\quad\text{or}\quad H^{3}(\Omega)\quad\text{for $l=1$}.\]

_Then the approximate solution \(\psi_{h}\) of the upwind scheme (5.18) satisfies the error bound:_

(5.45) \[\left|\psi(\lambda)-\psi_{h}(\lambda)\right|\leqslant\begin{cases}C_{1}h^{l} \quad\text{when $l\geqslant 2$},\\ C_{2}(\varepsilon)h^{1-\varepsilon}\quad\text{when $l=1$}\quad\quad\forall \varepsilon>0,\end{cases}\]

_with constants independent of \(h\) and \(\lambda\)._

Proof.: Let \(\mathbf{g}\) be any function of \(L^{2}(\Omega)^{2}\) and let us introduce the following dual linearized Navier-Stokes problem, analogous to (4.40):

\[\begin{split} z=(\mathbf{z}=\mathbf{curl}\,\chi,v)\!\in\!V\quad \text{such that:}\\ (v,\theta)+\lambda a_{1}(v;u(\lambda),\mathbf{z})-\lambda a_{1}(u( \lambda);z,\mathbf{v})=(\mathbf{g},\mathbf{curl}\,\phi)\\ \forall v=(\mathbf{v}=\mathbf{curl}\,\phi,\theta)\!\in\!V.\end{split}\] (5.46)

We know that on the one hand:

\[a_{1}(u,z,\mathbf{v})=-\,a_{1}(u;v,\mathbf{z})\]

and on the other hand:

\[a_{1}(u;v,\mathbf{z})+a_{1}(v;u,\mathbf{z})=(DG(u)\cdot v,\mathbf{z})\]

for all \(u,v\) and \(z\) in \(V\). Therefore Problem (5.46) is the same as Problem (4.40) and hence its solution enjoys the regularity properties stated in Lemma 4.1.

Now, by reasoning like in Theorem 4.5 we readily obtain:

\[\begin{split}(\mathbf{g},\mathbf{curl}(\psi-\psi_{h}))=& (v-v_{h},\omega-\omega_{h})+\tilde{b}(u-u_{h},v-\theta_{h})+\tilde{b}(z-z_{h}, \omega-\mu_{h})\\ &+\lambda a_{1}(u-u_{h};u,\mathbf{z})-\lambda a_{1}(u;z,\mathbf{ u}-\mathbf{u}_{h})-\lambda a_{1}(u;u,\mathbf{z}_{h})\\ &+\lambda a_{1}(u_{h};u_{h},\mathbf{z}_{h})+\lambda a_{2}^{u_{h} }(u_{h};u_{h},\mathbf{z}_{h})\\ &\forall z_{h}=(\mathbf{z}_{h}=\mathbf{curl}\,\chi_{h},v_{h})\! \in\!V_{h},\quad\forall\mu_{h},\,\theta_{h}\!\in\!\theta_{h}.\end{split}\]
