**Lemma 5.12**.: _Let \(\Omega\) be a bounded polyhedron in \(\mathbb{R}^{3}\). Then for each \(p_{h}\) in \(Q_{h}\) there exists a function \(\mathbf{v}_{h}\) in \(D_{0h}\) and a function \(\mathbf{0}_{h}\) in \(M_{h}\) such that:_

\[\operatorname{div}\mathbf{v}_{h} =p_{h}\quad\text{in }\Omega,\] \[(\mathbf{0}_{h},\mathbf{\mu}_{h}) =(\mathbf{v}_{h},\operatorname{\mathbf{curl}}\mathbf{\mu}_{h}) \quad\forall\mathbf{\mu}_{h}\in M_{h}.\]

_In addition, when \(\mathcal{T}_{h}\) is a regular family of triangulations of \(\bar{\Omega}\), we have:_

(5.56) \[\left\|\mathbf{0}_{h}\right\|_{0,\Omega}+\left\|\mathbf{v}_{h}\right\|_{H( \operatorname{div};\Omega)}\leqslant C\left\|p_{h}\right\|_{0,\Omega},\]

_where the positive constant \(C\) is independent of \(h\) and \(p_{h}\)._

The above lemmas lead to the expected estimate for the error \(p-p_{h}\).

**Theorem 5.6**.: _Let \(\Omega\) be a bounded polyhedron in \(\mathbb{R}^{3}\). Then Problem (5.55) has a unique solution \((\mathbf{u}_{h},\mathbf{\omega}_{h})\) in \(D_{0h}\times M_{h}\) and \(p_{h}\) in \(Q_{h}\) where \((\mathbf{u}_{h}=\operatorname{\mathbf{curl}}\mathbf{\psi}_{h},\mathbf{\omega}_ {h})\) is the solution of Problem (5.15)._

_Moreover, under the hypotheses of Theorem 5.5 and if the exact pressure \(p\) belongs to \(H^{l}(\Omega)\) for \(l\geqslant 1\), the following error estimate holds:_

(5.57) \[\left\|p-p_{h}\right\|_{0,\Omega}\leqslant C(h^{l}|p|_{l,\Omega}+h^{l}\left\| \mathbf{\omega}\right\|_{l+1,\Omega}+h^{l-1}|\mathbf{\psi}|_{l+1,\Omega}),\]

_with a positive constant \(C\) independent of \(h\), \(p\), \(\mathbf{\omega}\) and \(\mathbf{\psi}\)._
