First, as \(\mathbf{v}\) vanishes on the boundary of \(\kappa\), we can write:

\[\int_{\kappa}q\operatorname{div}\mathbf{v}\,dx=-\int_{\kappa}\mathbf{v}\cdot \operatorname{\mathbf{grad}}q\,dx.\]

Then since \(\operatorname{\mathbf{grad}}q\in P^{2}_{t-2}\), we can try:

\[\mathbf{v}=-\lambda_{1}\lambda_{2}\lambda_{3}\operatorname{\mathbf{grad}}q\]

which belongs indeed to \(\mathcal{P}_{t}(\kappa)\) and vanishes on \(\partial\kappa\). With this choice,

(2.24) \[\int_{\kappa}q\operatorname{div}\mathbf{v}\,dx=\int_{\kappa}\lambda_{1} \lambda_{2}\lambda_{3}\sum_{i=1}^{2}\left(\partial q/\partial x_{i}\right)^{2} \,dx.\]

Next, a straightforward calculation shows that all polynomials \(\phi\) of (say) \(P_{t}\) satisfy:

(2.25) \[\int_{\kappa}\lambda_{1}\lambda_{2}\lambda_{3}\phi^{2}\,dx\geqslant C_{1}\| \,\phi\|_{0,\kappa}^{2}\]

with a constant \(C_{1}>0\) independent of \(\kappa\), \(h\) and \(\phi\). Indeed, in terms of the reference triangle \(\hat{\kappa}\) we have:

\[\int_{\kappa}\lambda_{1}\lambda_{2}\lambda_{3}\phi^{2}\,dx=\left[\text{meas} (\kappa)/\text{meas}(\hat{\kappa})\right]\int_{\hat{\kappa}}\hat{\lambda}_{1} \hat{\lambda}_{2}\hat{\lambda}_{3}\hat{\phi}^{2}\,d\hat{x}.\]

But the mapping

\[\hat{\phi}\to\left(\int_{\hat{\kappa}}\hat{\lambda}_{1}\hat{\lambda}_{2}\hat{ \lambda}_{3}\hat{\phi}^{2}\,d\hat{x}\right)^{1/2}\]

is a norm on \(P_{t}\), equivalent to the \(L^{2}(\hat{\kappa})\)-norm. Hence

\[\int_{\hat{\kappa}}\hat{\lambda}_{1}\hat{\lambda}_{2}\hat{\lambda}_{3}\hat{ \phi}^{2}\,d\hat{x}\geqslant\hat{C}\|\,\hat{\phi}\|_{0,\kappa}^{2}=\hat{C}[ \text{meas}(\hat{\kappa})/\text{meas}(\kappa)]\,\|\,\phi\|_{0,\kappa}^{2}.\]

This yields (2.25) with the equivalence constant \(\hat{C}\). Therefore, combining (2.24) and (2.25) we get:

\[\int_{\kappa}q\operatorname{div}\mathbf{v}\,dx\geqslant\hat{C}|q|_{1,\kappa}^ {2}.\]

Finally, using the argument of Lemma A.6 (cf. formula (A.32)) we get:

\[|\mathbf{v}|_{1,\kappa}\leqslant(C_{2}/\rho_{\kappa})\|\,\mathbf{v}\|_{0,\kappa}\]

with a constant \(C_{2}\) independent of \(h\), \(\kappa\) and \(\mathbf{v}\). But

\[\|\mathbf{v}\|_{0,\kappa}=\|\,\lambda_{1}\lambda_{2}\lambda_{3}\operatorname{ \mathbf{grad}}q\|_{0,\kappa}\leqslant|q|_{1,\kappa}.\]

Hence

\[|\mathbf{v}|_{1,\kappa}\leqslant(C_{2}/\rho_{\kappa})|q|_{1,\kappa}\]
