where

\[p^{\prime}=P/(\rho U^{2}),\ \ \ \ \ \mathbf{f}^{\prime}=L\mathbf{f}/U^{2}.\]

Now, if we define the Reynolds number \(Re\) to be the dimensionless number

\[\operatorname{Re}=LU/v,\]

we find that the Navier-Stokes equations may be written in dimensionless variables

\[\begin{cases}\frac{\partial\mathbf{u}}{\partial t}+\sum\limits_{j=1}^{N}u_{j} \frac{\partial\mathbf{u}}{\partial x_{j}}-\frac{1}{\operatorname{Re}}\, \Delta\,\mathbf{u}+\mathbf{grad}\,p=\mathbf{f},\\ \operatorname{div}\,\mathbf{u}=0.\end{cases}\] (5.8)

We obtain again the equations (5.7) with \(v\) replaced by \(1/Re\).

For the time being, we introduce two simplifications in the equations (5.5) or (5.7). We only consider the steady-state (or stationary) case, that is \(\partial\mathbf{u}/\partial t=\mathbf{0}\), and furthermore we assume that the velocity \(\mathbf{u}\) is sufficiently small for ignoring the nonlinear convection terms \(u_{j}(\partial u_{i}/\partial x_{j})\). Thus we are led to the Stokes equations

\[\begin{cases}-2v\sum\limits_{j=1}^{N}\frac{\partial D_{ij}(\mathbf{u})}{ \partial x_{j}}+\frac{\partial p}{\partial x_{i}}=f_{i},\ \ \ \ 1\leqslant i \leqslant N,\\ \operatorname{div}\,\mathbf{u}=0,\end{cases}\] (5.9)

which can be written more conveniently

\[\begin{cases}-\nu\,\Delta\,\mathbf{u}+\mathbf{grad}\,p=\mathbf{f},\\ \operatorname{div}\,\mathbf{u}=0.\end{cases}\] (5.10)

The Stokes equations are linear but nevertheless they deserve special attention because of the incompressibility condition \(\operatorname{div}\,\mathbf{u}=0\). In this paragraph, we shall establish the existence and uniqueness of the solution of the Stokes equations and we shall derive several variational formulations that will be used later on for approximation purposes.

### The Dirichlet Problem in the Velocity-Pressure Formulation

In order to get a well-posed problem for the Stokes equations (5.10), we have to complete them with appropriate boundary conditions. We begin with the Dirichlet boundary conditions.

**Theorem 5.1**.: _Let \(\Omega\) be a bounded and connected open subset of \(\mathbb{R}^{N}\) with a Lipschitz-continuous boundary \(\Gamma\). Given \(\mathbf{f}\!\in\!H^{-1}(\Omega)^{N}\) and \(\mathbf{g}\!\in\!H^{1/2}(\Gamma)^{N}\) such that_

\[\int_{\Gamma}\mathbf{g}\cdot\mathbf{n}\,ds=0,\] (5.11)
