i.e.

(4.67) \[\sigma^{m}=-D^{2}K_{r}\cdot(g^{m},\omega^{m-1})/D^{2}K_{r}\cdot(\omega^{m-1},\omega ^{m-1}).\]

In fact, \(\rho^{m}\) and \(\sigma^{m}\) have a more amenable expression. Recall the classical theorem (that can be found in every text concerned with conjugate-gradient methods):

**Theorem 4.8**.: _We have the following orthogonality relations_:

\[D^{2}K_{r}\cdot(\omega^{i},\omega^{j}) =0\quad\quad i\neq j,\] \[c(g^{i},g^{j}) =0\quad\quad i\neq j,\] \[c(g^{i},\omega^{j}) =0\quad\quad i>j.\]

As a consequence, we can simplify (4.55) and (4.67):

**Corollary 4.5**.: _The parameters \(\rho^{m}\) and \(\sigma^{m}\) verify_:

(4.68) \[\begin{cases}\sigma^{m}=c(g^{m},g^{m})/c(g^{m-1},g^{m-1}),\\ \rho^{m}=c(g^{m},g^{m})/D^{2}K_{r}\cdot(\omega^{m},g^{m}).\end{cases}\]

Proof.: To begin with, recall that

\[c(g^{m},v)=DK_{r}(\lambda^{m})\cdot v\quad\quad\forall v\in M.\]

Next, like in Theorem 4.6 we obtain:

\[DK_{r}(\lambda^{m+1})-DK_{r}(\lambda^{m})=D^{2}K_{r}\cdot(\lambda^{m+1}-\lambda ^{m})=-\rho^{m}D^{2}K_{r}\cdot\omega^{m},\]

i.e.

(4.69) \[c(g^{m+1}-g^{m},v)=-\rho^{m}D^{2}K_{r}\cdot(\omega^{m},v)\quad\quad\forall v \in M.\]

On the other hand since \(D^{2}K_{r}\) is self-adjoint (cf. (4.52)), we have:

\[\sigma^{m} =-[\rho^{m-1}D^{2}K_{r}\cdot(\omega^{m-1},g^{m})]/[\rho^{m-1}D^{2 }K_{r}\cdot(\omega^{m-1},\omega^{m-1})]\] \[=-c(g^{m}-g^{m-1},g^{m})/c(g^{m}-g^{m-1},\omega^{m-1}).\]

Then Theorem 4.8 and (4.66) yield:

\[\sigma^{m} =c(g^{m},g^{m})/c(g^{m-1},\omega^{m-1})\] \[=c(g^{m},g^{m})/c(g^{m-1},g^{m-1}).\]

Finally, we readily derive the desired expression for \(\rho^{m}\) by taking \(v=g^{m}\) in (4.69). 

With this corollary, we can organize more efficiently the general step of the _conjugate-gradient algorithm_:

For \(m\geqslant 0\), knowing\((u^{m},\lambda^{m})\in X\times M\), compute \(g^{m},\omega^{m}\in M,z^{m}\in X,\rho^{m},\sigma^{m}\in\mathbb{R}\) and the pair \((u^{m+1},\lambda^{m+1})\in X\times M\) by:
