(5.50) \[Q_{h}=\{q_{h}\!\in\!{\cal C}^{0}(\bar{\Omega})\cap L_{0}^{2}(\Omega);\,q_{h}|_{ \kappa}\!\in\!P_{k}\quad\forall\kappa\!\in\!{\cal T}_{h}\}\quad\quad k=\min(1,l-1)\]

and we discretize (5.49) by:

\[Find\ p_{h}\!\in\!Q_{h}\ \mbox{satisfying}\] (5.51) \[(\mbox{\bf grad}\ p_{h},\mbox{\bf grad}\ q_{h})=(\mbox{\bf f}-\ v \,\mbox{\bf curl}\,\omega_{h},\mbox{\bf grad}\ q_{h})-\tilde{a}^{u_{h}}(u_{h};u _{h},\mbox{\bf grad}\ q_{h})\] \[\forall q_{h}\!\in\!Q_{h}.\]

Obviously, this problem has a unique solution.

To estimate the error \(p-p_{h}\) we use the same duality argument as in Theorem III.2.7. We introduce the function \(\mbox{\bf v}\!\in\!H^{1}(\Omega)^{2}\) defined by

\[\mbox{div}\,\mbox{\bf v}=p-p_{h},\quad\ |\mbox{\bf v}|_{1,\Omega}\leqslant C_{1} \|\,p-p_{h}\|_{0,\Omega}\]

which we can split into

\[\mbox{\bf v}=\mbox{\bf grad}\ q+\mbox{\bf curl}\,\phi.\]

Since \(\Omega\) is assumed to be a convex polygon, both \(q\) and \(\phi\) belong to \(H^{2}(\Omega)\) with

\[\|\,q\,\|_{2,\Omega}+\|\,\phi\|_{2,\Omega}\leqslant C_{2}|\mbox{\bf v}|_{1, \Omega}\quad(\mbox{cf. Lemma III.2.6}).\]

In addition, if the triangulation \({\cal T}_{h}\) is uniformly regular Lemma III.2.6 shows that

(5.52) \[|\,q-P_{h}q|_{1,s,\Omega}+|\,\phi-I_{h}\phi|_{1,s,\Omega}\leqslant C_{3}h^{2/ s}|\mbox{\bf v}|_{1,\Omega}.\]

Now, like in Theorem III.2.7 we can write:

\[\|\,p-p_{h}\|_{0,\Omega}^{2}=(\mbox{\bf grad}(q_{h}-p),\mbox{\bf grad }(q-P_{h}q))+(\mbox{\bf grad}(p_{h}-p),\mbox{\bf grad}(P_{h}q))\] \[\forall q_{h}\!\in\!Q_{h}.\]

Thus, to estimate \(p-p_{h}\), we must derive a sharp bound for the second term. By subtracting (5.49) from (5.51) we obtain:

\[(\mbox{\bf grad}(p_{h}-p),\mbox{\bf grad}(P_{h}q)) = -v(\mbox{\bf curl}(\omega_{h}-\omega),\mbox{\bf grad}(P_{h}q))+ \ a_{1}(u;u,\mbox{\bf grad}(P_{h}q))\] \[-\tilde{a}^{u_{h}}(u_{h};u_{h},\mbox{\bf grad}(P_{h}q))\] \[= v(\mbox{\bf curl}(\omega-\omega_{h}),\mbox{\bf v}_{h}-\mbox{\bf v })+\ v(\omega-\omega_{h},\mbox{\rm curl}\,\mbox{\bf v})\] \[+\ \tilde{a}^{u_{h}}(u_{h};u-u_{h},\mbox{\bf v}_{h}-\mbox{\bf v })+\ a_{1}(u-u_{h};u,\mbox{\bf v}_{h}-\mbox{\bf v})\] \[+\ a_{1}(u_{h}-u;v,\mbox{\bf u}_{h})+\ a_{1}(u;v,\mbox{\bf u}_{h}- \mbox{\bf u})\]

where

\[\mbox{\bf v}_{h}=\mbox{\bf grad}(P_{h}q)+\mbox{\bf curl}(I_{h}\phi).\]

Therefore (5.52) together with familiar estimates for the forms \(\tilde{a}^{u_{h}}(.;.,.)\) and \(a_{1}(.;.,.)\) give a result analogous to (III.2.38).

**Lemma 5.5**.: _Let \(\Omega\) be a bounded, convex polygon and \({\cal T}_{h}\) a uniformly regular triangulation of \(\Omega\). If \(p\) and \(\omega\) belong to \(W^{1,\iota}(\Omega)\) for some real \(t\!\in\![r,2]\) then the error on \(p\) is:_
