This in turn will be a consequence of the following Hardy inequality:

(2.19) \[\int_{0}^{\infty}|\phi(t)/t|^{2}\,dt\leq 4\int_{0}^{\infty}|\phi^{\prime}(t)|^{2 }\,dt\ \ \ \ \ \forall\phi\in\mathcal{D}(0,\infty),\]

which can be established as follows. By writing

\[\phi(t)=\int_{0}^{t}\phi^{\prime}(s)\,ds\]

and setting \(t=e^{\tau}\), \(s=e^{\sigma}\), we have

\[\int_{0}^{\infty}|\phi(t)/t|^{2}\,dt =\int_{0}^{\infty}(1/t)\!\left[\int_{0}^{t}\phi^{\prime}(s)\,ds \right]^{2}(dt/t)\] \[=\int_{-\infty}^{+\infty}e^{-\tau}\!\left[\int_{-\infty}^{\tau} \phi^{\prime}(e^{\sigma})e^{\sigma}\,d\sigma\right]^{2}\,d\tau\] \[=\int_{-\infty}^{+\infty}\!\left[\int_{-\infty}^{+\infty}H(\tau -\sigma)e^{-(\tau-\sigma)/2}\phi^{\prime}(e^{\sigma})e^{\sigma/2}\,d\sigma \right]^{2}\,d\tau,\]

where \(H\) is the classical Heaviside function. Now, using the standard convolution inequality:

\[\|f\ast g\|_{L^{2}}\leq\|f\|_{L^{1}}\|g\|_{L^{2}},\]

we get

\[\int_{0}^{\infty}|\phi(t)/t|^{2}\,dt \leq\!\left[\int_{-\infty}^{+\infty}H(\tau)e^{-\tau/2}\,d\tau \right]^{2}\int_{-\infty}^{+\infty}\phi^{\prime}(e^{\sigma})^{2}e^{\sigma}\,d\sigma\] \[=4\int_{0}^{\infty}\phi^{\prime}(s)^{2}\,ds\]

which is the desired inequality. 

Proof of Lemma 2.3.: Let the function \(\mathbf{g}\in H^{1/2}(\Gamma)^{N}\) satisfy the conditions (2.14). We already know from Lemma I.2.2 that there exists a function \(\mathbf{w}_{0}\in H^{1}(\Omega)^{N}\) such that

\[\operatorname{div}\mathbf{w}_{0}=0,\ \ \ \ \ \mathbf{w}_{0}|_{\Gamma}=\mathbf{g}.\]

Moreover, it follows from (2.14), Theorem I.3.1 or I.3.4 and Corollary I.3.3, that we can find a stream function \(\psi_{0}\in H^{2}(\Omega)\) if the dimension \(N=2\) or a vector potential \(\psi_{0}\in H^{2}(\Omega)^{3}\) if the dimension \(N=3\), such that

\[\mathbf{w}_{0}=\begin{cases}\operatorname{\mathbf{curl}}\psi_{0},&N=2,\\ \operatorname{\mathbf{curl}}\psi_{0},&N=3.\end{cases}\]

Consider the case \(N=3\), the case \(N=2\) being exactly similar. For all \(\mu>0\), we introduce the function
