**Lemma 2.3**.: _Suppose \(\Omega\) is a Lipschitz-continuous open subset of \(\mathbb{R}^{N}\)\((\)not necessarily bounded\()\). Then the set of functions of \(H(\mathbf{curl};\Omega)\) with compact support is dense in \(H(\mathbf{curl};\Omega)\)._

Proof.: We use a classical truncation process. Let \(\mathbf{u}\!\in\!H(\mathbf{curl};\Omega)\) and let \(\phi\) be a function of \(\mathcal{C}^{\infty}(\mathbb{R}^{N})\) such that \(0\leqslant\phi\leqslant 1\) everywhere in \(\mathbb{R}^{N}\) and

\[\phi(x)=\begin{cases}1&\text{for }\|\,x\,\|\,\leqslant\,1,\\ 0&\text{for }\|\,x\,\|\,\geqslant\,2.\end{cases}\]

Next, for an arbitrary real number \(a>0\), we make the change of variable:

\[\phi_{a}(x)=\phi(x/a).\]

As \(\phi_{a}\) is smooth, \(\phi_{a}\mathbf{u}\!\in\!H(\mathbf{curl};\Omega)\); moreover

\[\lim_{a\to\infty}\phi_{a}\mathbf{u}=\mathbf{u}\quad\text{in }H(\mathbf{curl};\Omega)\]

and the support of \(\phi_{a}\mathbf{u}\) is compact. Hence \(\phi_{a}\mathbf{u}\) is the desired sequence. 

**Lemma 2.4**.: _If a function \(\mathbf{f}\) of \(H(\mathbf{curl};\Omega)\) satisfies:_

(2.21) \[(\mathbf{f},\mathbf{curl}\,\phi)-(\mathbf{curl}\,\mathbf{f},\phi)=0\quad\quad \forall\phi\!\in\!\mathcal{D}(\bar{\Omega})^{N},\]

_then \(\mathbf{f}\!\in\!H_{0}(\mathbf{curl};\Omega)\)._

Proof.: Let \(\mathbf{\tilde{f}}\) denote the extension of \(\mathbf{f}\) by zero outside \(\Omega\). To begin with, observe that (2.21) implies that \(\mathbf{\tilde{f}}\!\in\!H(\mathbf{curl};\mathbb{R}^{N})\). Next, in order to construct a sequence of \(\mathcal{D}(\Omega)^{N}\) that converges to \(\mathbf{f}\) in \(H(\mathbf{curl};\Omega)\), we combine the regularization techniques of Corollary 2.2 and Theorem 2.3.

\(1^{\circ})\) Suppose for the moment that \(\Omega\) is strictly star-shaped. Again, we make the change of variable introduced in Corollary 2.2:

\[\mathbf{\tilde{f}}_{\theta}(x)=\mathbf{\tilde{f}}(x/\theta)\quad\quad\forall x \!\in\!\Omega_{\theta}=\theta\Omega,\]

but this time, we take \(\theta\) in \((0,1)\) in order to obtain a function \(\mathbf{\tilde{f}}_{\theta}\) with compact support in \(\Omega\). Obviously, \(\mathbf{\tilde{f}}_{\theta}\!\in\!H(\mathbf{curl};\mathbb{R}^{N})\) and

\[\lim_{\theta\to 1}\mathbf{\tilde{f}}_{\theta}=\mathbf{\tilde{f}}\quad\text{in }H( \mathbf{curl};\mathbb{R}^{N}).\]

Hence, for \(\varepsilon>0\) sufficiently small, \(\rho_{\varepsilon}\ast\mathbf{\tilde{f}}_{\theta}\) belongs to \(\mathcal{D}(\Omega)^{N}\) and

\[\lim_{\varepsilon\to 0}\lim_{\theta\to 1}\left(\rho_{\varepsilon}\ast \mathbf{\tilde{f}}_{\theta}\right)=\mathbf{\tilde{f}}\quad\text{in }H(\mathbf{curl};\Omega).\]

\(2^{\circ})\) In the general case, \(\Omega\) can be covered by a finite family of open sets:

\[\Omega\subset\bigcup_{1\leqslant i\leqslant q}\mathcal{C}_{i}\]

such that each \(\Omega_{i}=\mathcal{C}_{i}\cap\Omega\) is Lipschitz-continuous, bounded and strictly star-shaped, for \(1\leqslant i\leqslant q\). Let \((x_{i})_{i\geqslant 1}\) be a partition of unity subordinate to the family
