Note that

\[\sup_{u\in M}\mathcal{L}(v,\mu)=\begin{cases}\infty&\text{if }v\notin V(\chi),\\ J(v)&\text{if }v\in V(\chi).\end{cases}\]

Hence, we have

\[\inf_{v\in X\,\mu\in M}\sup_{v\in V(\chi)}J(v).\]

Since \(b(u,\mu)=\langle\chi,\mu\rangle\), the first equality (4.17) becomes

\[J(u)=\underset{v\in V(\chi)}{\text{Min}}J(v).\] (4.20)

Therefore, the solution \(u\) of Problem (P) is characterized as the solution of the constrained optimization problem (4.20).

On the other hand, let us consider the dual problem of (4.20):

\[\underset{\mu\in M}{\text{Max}}\inf_{v\in X}\mathcal{L}(v,\mu).\]

Assume in addition to the hypotheses of Theorem 4.2 that the bilinear form \(a(.,.)\) is \(X\)-elliptic, i.e.

\[a(v,v)\geq\alpha\|v\|_{X}^{2}\ \ \ \ \ \forall v\in X,\ \ \ \ \alpha>0.\] (4.21)

Now, for any \(\mu\in M\), we define \(u(\mu)\in X\) to be the solution of the optimization problem:

\[\mathcal{L}(u(\mu),\mu)=\inf_{v\in X}\mathcal{L}(v,\mu).\]

We have seen in the proof of Theorem 4.2 that this problem is equivalent to the equation:

\[a(u(\mu),v)=\langle l,v\rangle-b(v,\mu)\ \ \ \ \ \forall v\in X.\] (4.22)

By (4.21), problem (4.22) has indeed a unique solution \(u(\mu)\in X\). Since \(u(\lambda)=u\), we note that

\[\mathcal{L}(u(\lambda),\lambda)=\underset{\mu\in M}{\text{Max}}\ \mathcal{L}(u(\mu),\mu).\]

Let us give a simple expression for \(\mathcal{L}(u(\mu),\mu)\). We have

\[\mathcal{L}(u(\mu),\mu)=(1/2)a(u(\mu),u(\mu))-\langle l,u(\mu)\rangle+b(u(\mu) ,\mu)-\langle\chi,\mu\rangle,\]

so that by (4.22)

\[\mathcal{L}(u(\mu),\mu)=-(1/2)a(u(\mu),u(\mu))-\langle\chi,\mu\rangle.\]

Hence, setting

\[K(\mu)=(1/2)a(u(\mu),u(\mu))+\langle\chi,\mu\rangle,\] (4.23)

the dual problem of (4.20) becomes
