**Lemma 3.8**.: _Assume that \(\bar{\Omega}\) can be partitioned into groups \(\mathcal{C}_{x,\,\beta}\) of four macro-elements \(\Omega_{I,\,J}\) like in Figure 16. Then the pair \((\tilde{V}_{h},\bar{M}_{2h})\) satisfies a global uniform inf-sup condition._

Proof.: First, observe that the functions of \(X_{2h}\) belong necessarily to \(\tilde{V}_{h}\) because their divergence reduces to polynomials of \(P_{1}\) in each macro-element \(\Omega_{I,\,J}\) and

\[\int_{\Omega_{I,\,J}}(v_{\mathbf{a}})_{I,\,J}p\,dx=0\,\,\,\,\,\,\,\,\,\,\,\, \forall p\in P_{1}.\]

Therefore let us prove the inf-sup condition for the pair \((X_{2h},\bar{M}_{2h})\).

For this, we exhibit an adequate operator \(\pi_{h}\) very similar to that of Lemma 2.2. Let \(R_{h}\) be the local regularization operator of Section A.3 and let us fix one of the super macro-elements \(\mathcal{C}_{x,\,\beta}\). For \(v\) in \(H^{1}(\mathcal{C}_{x,\,\beta})\) we define \(\pi v\in Q_{1}\) on each \(\Omega_{I,\,J}\subset\mathcal{C}_{x,\,\beta}\) by:

\[\pi v(x_{i,j})=R_{h}v(x_{i,j})\quad\text{at the four corners and center of }\mathcal{C}_{x,\,\beta},\] \[\int_{T}(\pi v-v)\,ds=0\quad\text{on each side $T$ of }\partial\mathcal{C}_{x,\,\beta}.\]

Then, we take \(\pi_{h}v=\pi v\) on each \(\mathcal{C}_{x,\,\beta}\).

By inspection, it easy to verify that \(\pi_{h}\in\mathcal{L}(H^{1}_{0}(\Omega)^{2};X_{2h})\) and

\[\int_{\Omega}\operatorname{div}(\pi_{h}\mathbf{v}-\mathbf{v})q\,dx=0\,\,\,\, \,\,\,\,\,\,\,\forall q\in\bar{M}_{2h}.\]

Furthermore a simple argument shows that

\[\left|\pi_{h}\mathbf{v}\right|_{1,\,\Omega}\leqslant C\left|\mathbf{v} \right|_{1,\,\Omega}\quad\text{with a constant $C>0$ independent of $h$.}\]

This yields the desired inf-sup condition. 

**Lemma 3.9**.: _On each \(\mathcal{C}_{x,\,\beta}\), the pair of spaces \((\tilde{V}_{h},\bar{M}_{h})\) satisfies a local inf-sup condition._

Proof.: Let \(q\) belong to the space:

\[\bar{M}_{h}(\mathcal{C}_{x,\,\beta})=\{q^{1}|_{\mathcal{C}_{x,\,\beta}}\}\cap L ^{2}_{0}(\mathcal{C}_{x,\,\beta}).\]

We must construct \(\mathbf{v}\) in \(\tilde{V}_{h}\) with \(\mathbf{v}|_{\partial\mathcal{C}_{x,\,\beta}}=\mathbf{0}\) such that

(3.35) \[\left(\int_{\mathcal{C}_{x,\,\beta}}q\operatorname{div}\mathbf{v}\,dx\right) \bigg{/}\left|\mathbf{v}\right|_{1,\,\mathcal{C}_{x,\,\beta}}\geqslant C\left\| q\right\|_{0,\,\mathcal{C}_{x,\,\beta}}.\]

Let us fix \(\mathbf{v}=\mathbf{0}\) on the boundary and central nodes of \(\mathcal{C}_{x,\,\beta}\) and also at the central node of each macro-element \(\Omega_{I,\,J}\) contained in \(\mathcal{C}_{x,\,\beta}\). Then, in view of the formula

\[\int_{\mathcal{C}_{x,\,\beta}}q\operatorname{div}\mathbf{v}\,dx=-h^{2}\sum_{i ,j}\{u_{i,j}(P_{1}q)_{i,j}+v_{i,j}(P_{2}q)_{i,j}\}\]
