(4.70) \[\left\{\begin{aligned} Cg^{m}&=\chi-Bu^{m},\\ \sigma^{m}&=c(g^{m},g^{m})/c(g^{m-1},g^{m-1})\\ \omega^{m}&=g^{m}+\sigma^{m}\omega^{m-1}\end{aligned} \right\}\quad\text{only if $m\geqslant 1$,}\] \[\omega^{0}=g^{0}\text{ otherwise,}\] \[A_{r}z^{m} =B^{\prime}\omega^{m},\] \[\rho^{m} =c(g^{m},g^{m})/b(z^{m},g^{m}),\] \[\lambda^{m+1} =\lambda^{m}-\rho^{m}\omega^{m},\] \[u^{m+1} =u^{m}+\rho^{m}z^{m}.\]

Note that the volume of computation per iteration is slightly larger than that of the simple-gradient algorithm; but the bulk of the computation still lies in the inversion of \(A_{r}\).

Finally, it is easy to prove the convergence of this scheme.

**Corollary 4.6**.: _Under the hypotheses of Corollary 4.4, the conjugate-gradient algorithm (4.70) is convergent._

Proof.: Observe that the convergence criterion (4.58) is equivalent to:

(4.71) \[\rho^{m}\geqslant\alpha\|g^{m}\|_{M}/\|\omega^{m}\|_{M}\quad\text{for some constant $\alpha^{\prime}>0$.}\]

Indeed, in view of (4.57) and the expression of \(z^{m}\) we have

\[\rho^{m} =c(g^{m},\omega^{m})/b(z^{m},\omega^{m})\] \[=c(g^{m},\omega^{m})/D^{2}\,K_{r}\cdot(\omega^{m},\omega^{m}).\]

Hence, (4.58) and (4.59) imply (4.71) with \(\alpha^{\prime}=\alpha/\tau_{r}\); conversely (4.71) and (4.59) yield (4.58) with \(\alpha=\alpha^{\prime}\delta_{r}\).

Next, note that

\[D^{2}\,K_{r}\cdot(\omega^{m},g^{m})=D^{2}\,K_{r}\cdot(\omega^{m},\omega^{m})>0 \quad\quad\forall m.\]

Therefore (4.71) is an immediate consequence of (4.68). Hence the scheme is convergent. 

## 5 The Stokes Equations

Let us consider the Navier-Stokes equations describing the \(N\)-dimensional motion of an incompressible viscous fluid:

(5.1) \[\rho\biggl{(}\frac{\partial u_{i}}{\partial t}+\sum_{j=1}^{N}u_{j} \frac{\partial u_{i}}{\partial x_{j}}\biggr{)}-\sum_{j=1}^{N}\frac{\partial \sigma_{ij}}{\partial x_{j}}=\rho f_{i},\quad\ 1\leqslant i\leqslant N,\] (5.2) \[\operatorname{div}\mathbf{u}=\sum_{i=1}^{N}D_{ii}(\mathbf{u})=0 \quad\text{(incompressibility condition),}\]
