which is a \(\mathscr{C}^{0}\)-mapping from \(\mathbb{R}\times V_{h}\) into \(V_{h}\). The following theorem solves Problem (3.33') without involving the differentiability of \(G_{h}\).

**Theorem 3.8**.: _Under the following hypotheses_:__

(i) \[\|\,T_{h}\|_{\mathscr{L}(Y_{h};V_{h})}\leqslant C,\] (3.59) \[\lim_{h\to 0}\|\,T-\,T_{h}\|_{\mathscr{L}(Y;X)}=0.\] (3.60)

(ii) _There exists an operator \(\pi_{h}\!\in\!\mathscr{L}(V;V_{h})\) such that:_

(3.61) \[\lim_{h\to 0}\|\,v-\pi_{h}v\,\|_{X}=0\ \ \ \ \ \forall v\in V\]

_and_

(3.62) \[\lim_{h\to 0}\sup_{\lambda\in\,\Lambda}\|\,G_{h}(\pi_{h}u(\lambda))-\,G(u( \lambda))\|_{h}=0.\]

(iii) _For all \(u_{h}\!\in\!V_{h}\), there exists an operator \(FG_{h}(u_{h})\!\in\!\mathscr{L}(V_{h};\,Y_{h})\) such that_

(3.63) \[\lim_{h\to 0}\sup_{\lambda\in\,\Lambda}\|\,FG_{h}(\pi_{h}u(\lambda))-\,DG(u( \lambda))\|_{\mathscr{L}(V_{h};\,Y_{h})}=0\]

_and_

(3.64) \[\|\,G_{h}(u_{h})-\,G_{h}(u_{h}^{\star})-\,FG_{h}(u_{h}^{0})\!\cdot\!(u_{h}-u_{ h}^{\star})\|_{h}\leqslant L_{h}(\mu;\|\,u_{h}^{0}\|_{X})\|\,u_{h}-u_{h}^{\star} \|_{X}\]

_for all \(u_{h}^{0}\!\in\!V_{h}\), \(u_{h}\) and \(u_{h}^{\star}\!\in\!S(u_{h}^{0};\mu)\cap V_{h}\), where \(L_{h}\!\!:\mathbb{R}_{+}\times\mathbb{R}_{+}\!\to\!\mathbb{R}_{+}\) is a continuous, monotonically increasing function with respect to each variable and with respect to \(h\), which satisfies:_

(3.65) \[\lim_{h\to 0}L_{h}(0;\mu)=0\ \ \ \ \ \forall\mu\!\in\!\mathbb{R}_{+}.\]

_Then there exists a neighborhood \(\mathscr{C}\) of the origin in \(X\) and for \(h\leqslant h_{0}\) small enough, a unique \(\mathscr{C}^{0}\)-function \(u_{h}\!\): \(\Lambda\to V_{h}\) such that_

(3.66) \[F_{h}(\lambda,u_{h}(\lambda))=0,\ \ \ \ u_{h}(\lambda)\!\in\!u(\lambda)+\, \mathscr{C}\ \ \ \ \ \forall\lambda\!\in\!\Lambda.\]

_In addition, the following error estimate holds_:__

(3.67) \[\begin{split}\|\,u_{h}(\lambda)-u(\lambda)\|_{X}\leqslant& \ C\,\{\|\,(I-\pi_{h})u(\lambda)\|_{X}+\,\|\,\lambda(T-\,T_{h})G(u( \lambda))\|_{X}\\ &+\,\|\,G_{h}(\pi_{h}u(\lambda))-\,G(u(\lambda))\|_{h}\}.\end{split}\]

Proof.: Let us apply Theorem 3.7 with \(\tilde{u}_{h}=\tilde{u}_{h}(\lambda)=\pi_{h}u(\lambda)\), \(V_{h}\) playing the role of \(X_{h}\). Since by assumption, \(u\) belongs to \(\mathscr{C}^{0}(\Lambda;V)\) then \(\tilde{u}_{h}\) belongs to \(\mathscr{C}^{0}(\Lambda;V_{h})\). Next, let us prove (3.27'). We have:

\[\varepsilon_{h}(\lambda)=\|\,F_{h}(\lambda,\tilde{u}_{h}(\lambda))-F(\lambda, u(\lambda))\|_{X},\]

i.e.
