yields:

\[\biggl{(}\sum_{\kappa\,\in\,\mathcal{T}_{h}}\|\operatorname{\mathbf{curl}}(\phi_{h }-\phi)\|_{0,\,\delta\kappa}^{2}\biggr{)}^{1/2}\leq C_{5}h^{-1/2}\biggl{(}| \phi_{h}-\phi|_{1,\,\delta}+h\biggl{(}\sum_{\kappa\,\in\,\mathcal{T}_{h}}|\phi_ {h}-\phi|_{2,\,\kappa}^{2}\biggr{)}^{1/2}\biggr{)}.\]

On the other hand

\[\|\operatorname{\mathbf{curl}}\theta_{h}\|_{0,\,4,\,\delta\kappa}\leq C_{6}h^{ -1/4}|\theta_{h}|_{1,\,4,\,\kappa}\quad\forall\kappa\,\in\,\mathcal{T}_{h} \quad\quad\forall\theta_{h}\,\in\,\Theta_{h}.\]

Combining these inequalities with (5.22) for \(t=2\) we obtain:

\[|a_{2}^{z_{h}}(u_{h};v_{h},w_{h})|\leq C_{7}\|\mathbf{u}_{h}\|_{0,\,4,\, \Omega}\|\mathbf{w}_{h}\|_{0,\,4,\,\Omega}[\phi_{h}-\phi]_{2}.\qed\] (5.30)

The next lemma shows that \(a_{2}^{z_{h}}(\cdot;\,\cdot,\,\cdot)\) is "almost Lipschitz-continuous" with respect to \(z_{h}\).

**Lemma 5.3**.: _We keep the notations and assumptions of Lemma 5.2 but we suppose that both \(v_{h}\) and \(w_{h}\) belong to \(V_{h}\). For all pairs \(z_{h}=(\mathbf{z}_{h},\zeta_{h})\) and \(z_{h}^{\star}=(\mathbf{z}_{h}^{\star},\zeta_{h}^{\star})\) in \(X_{h}\), the difference \(a_{2}^{z_{h}}-a_{2}^{z_{h}^{\star}}\) satisfies:_

\[|a_{2}^{z_{h}}(u_{h};v_{h},\mathbf{w}_{h})-a_{2}^{z_{h}^{\star}}(u _{h};v_{h},\mathbf{w}_{h})|\] (5.31) \[\leq Ch^{1/2}|v_{h}|\,|\,|w_{h}|\begin{cases}\|\mathbf{u}_{h}\|_{ 0,\,4,\,\Omega}&\text{if }z_{h}^{\star}\neq u_{h}\\ \|\,\mathbf{z}_{h}-\mathbf{z}_{h}^{\star}\|_{0,\,4,\,\Omega}&\text{if }z_{h}^{ \star}=u_{h},\\ &\quad\forall u_{h},\,z_{h},\,z_{h}^{\star}\in X_{h},\quad\quad\forall v_{h}, \,w_{h}\,\in V_{h}.\end{cases}\]

Proof.: This proof is based on the identity:

\[a_{2}^{z_{h}}(u_{h};v_{h},\mathbf{w}_{h})-a_{2}^{z_{h}^{\star}}(u _{h};v_{h},\mathbf{w}_{h})\] (5.32) \[=\sum_{\kappa\,\in\,\mathcal{T}_{h}}\int_{\partial_{-}\kappa(z_{ h},\,-\,z_{h}^{\star})}\mathbf{u}_{h}\cdot\mathbf{n}(v_{hi}^{\text{ext}}-v_{hi}^{ \text{int}})(w_{hi}^{\text{int}}-w_{hi}^{\text{ext}})\,ds\]

where

\[\partial_{-}\kappa(z,\,-\,z^{\star})=\{x\,\in\,\partial\kappa;\,\mathbf{z} \cdot\mathbf{n}(x)<0\quad\text{and}\quad\mathbf{z}^{\star}\cdot\mathbf{n}(x)>0\}.\]

Thus, in view of (5.29) we can replace not only \(v_{h}\) by \(v_{h}-Pv_{h}\) but also \(w_{h}\) by \(w_{h}-Pw_{h}\). This gives:

\[|a_{2}^{z_{h}}(u_{h};v_{h},\mathbf{w}_{h})-a_{2}^{z_{h}^{\star}}(u _{h};v_{h},\mathbf{w}_{h})| \leq C_{1}\biggl{(}\sum_{\kappa\,\in\,\mathcal{T}_{h}}\|\operatorname {\mathbf{curl}}\psi_{h}\|_{0,\,4,\,\delta\kappa}^{4}\biggr{)}^{1/4}\] \[\times\biggl{(}\sum_{\kappa\,\in\,\mathcal{T}_{h}}\|\operatorname {\mathbf{curl}}(\phi_{h}-\phi)\|_{0,\,4,\,\delta\kappa}^{4}\biggr{)}^{1/4}\] \[\times\biggl{(}\sum_{\kappa\,\in\,\mathcal{T}_{h}}\|\operatorname {\mathbf{curl}}(\chi_{h}-\chi)\|_{0,\,\delta\kappa}^{2}\biggr{)}^{1/2}.\]

Then the techniques of the preceding lemma easily yield:
