\[V_{h}=\{v_{h}\in X_{h};\,b(v_{h},\mu_{h})=0\quad\forall\mu_{h}\in M_{h}\}.\]

Right away we remark that generally \(V_{h}\not\subset V\) and \(V_{h}(\chi)\not\subset V(\chi)\) because \(M_{h}\) is a proper subspace of \(M\).

Now we approximate Problem (Q) by _Problem_ (Q\({}_{h}\)):

_Find a pair (\(u_{h},\dot{\lambda}_{h}\)) in \(X_{h}\times M_{h}\) satisfying_:

\[a(u_{h},v_{h})+b(v_{h},\dot{\lambda}_{h})=\langle l,v_{h}\rangle\qquad\forall v _{h}\in X_{h},\]

\[b(u_{h},\mu_{h})=\langle\chi,\mu_{h}\rangle\qquad\forall\mu_{h}\in M_{h}\]

and we associate with (Q\({}_{h}\)) the following _Problem_ (P\({}_{h}\)):

_Find \(u_{h}\in V_{h}(\chi)\) such that_:

\[a(u_{h},v_{h})=\langle l,v_{h}\rangle\qquad\forall v_{h}\in V_{h}.\]

As \(V_{h}\not\subset V\), Problem (P\({}_{h}\)) may be viewed as an _external approximation_ of Problem (P). Here again, the first component \(u_{h}\) of any solution (\(u_{h},\dot{\lambda}_{h}\)) of Problem (Q\({}_{h}\)) is also a solution of Problem (P\({}_{h}\)). The converse is proved as part of the next theorem.

Theorem 1.1: \(1^{\circ}\)) _Assume that the following conditions hold_:

(i)_\(V_{h}(\chi)\) is not empty_;

(ii) _there exists a constant \(\alpha^{*}>0\) such that_:

\[a(v_{h},v_{h})\geq\alpha^{*}\|v_{h}\|_{X}^{2}\,\,\,\,\,\,\,\,\,\forall v_{h} \in V_{h}.\]

_Then Problem \((\mathrm{P}_{h})\) has a unique solution \(u_{h}\in V_{h}(\chi)\) and there exists a constant \(C_{1}\) depending only upon \(\alpha^{*}\), \(\|a\|\) and \(\|b\|\) such that the \(``\)error bound\("\) holds_:

\[\|u-u_{h}\|_{X}\leq C_{1}\,\biggl{\{}\inf_{v_{h}\in V_{h}(\chi)}\|u-v_{h}\|_{X }+\inf_{\mu_{h}\in M_{h}}\|\lambda-\mu_{h}\|_{M}\biggr{\}}.\]

\(2^{\circ}\)) _Assume that hypothesis_ (ii) _holds and_, _in addition_, _that_:

(iii) _there exists a constant \(\beta^{*}>0\) such that_

\[\sup_{v_{h}\in X_{h}}\frac{b(v_{h},\mu_{h})}{\|v_{h}\|_{X}}\geq\beta^{*}\|\, \mu_{h}\|_{M}\,\,\,\,\,\,\,\,\,\,\,\,\,\forall\mu_{h}\in M_{h}.\]

_Then \(V_{h}(\chi)\not=\phi\) and there exists a unique \(\dot{\lambda}_{h}\) in \(M_{h}\) such that \((u_{h},\dot{\lambda}_{h})\) is the only solution of Problem (Q\({}_{h}\)). Furthermore\(,\) there exists a constant \(C_{2}\) depending only upon \(\alpha^{*}\), \(\beta^{*}\), \(\|a\|\) and \(\|b\|\) such that_:

\[\|u-u_{h}\|_{X}+\|\lambda-\dot{\lambda}_{h}\|_{M}\leq C_{2}\,\biggl{\{}\inf_{v_ {h}\in X_{h}}\|u-v_{h}\|_{X}+\inf_{\mu_{h}\in M_{h}}\|\lambda-\mu_{h}\|_{M} \biggr{\}}.\]

_Proof_. \(1^{\circ}\)) As \(V_{h}(\chi)\) is not empty, we choose a \(u_{h}^{0}\) in \(V_{h}(\chi)\) and we solve the problem:

_Find \(z_{h}\) in \(V_{h}\) such that_

\[a(z_{h},v_{h})=\langle l,v_{h}\rangle-a(u_{h}^{0},v_{h})\,\,\,\,\,\,\,\,\, \forall v_{h}\in V_{h}.\]
