Also, when \(p=2\) there is an alternate definition of \(W^{s,\,2}(\Omega)\) using Fourier transforms which yields algebraically and topologically the same space as Definition 1.2.

**Definition 1.3**.: \(1^{\circ}\)) For real \(s>0\) we set:

(1.11) \[H^{s}(\mathbb{R}^{N})=\{v\in L^{2}(\mathbb{R}^{N});(1\,+\,\|\,\sigma\,\|^{\,2})^ {s/2}\vartheta(\sigma)\in L^{2}(\mathbb{R}^{N}_{\sigma})\}\]

with the norm:

(1.12) \[\|\,v\,\|_{s,\,\mathbb{R}^{N}}=\{\,\|\,v\,\|_{0,\,\mathbb{R}^{N}}^{2}+\,\|(1\,+ \,\|\,\sigma\,\|^{\,2})^{s/2}\vartheta(\sigma)\|_{0,\,\mathbb{R}^{N}_{\sigma} }^{2}\}^{1/2},\]

where \(\vartheta\) denotes the Fourier transform of \(v\).

\(2^{\circ}\)) When \(\Omega\) is an open subset of \(\mathbb{R}^{N}\), we define

(1.13) \[H^{s}(\Omega)=\{v\in L^{2}(\Omega);\,3\bar{v}\in H^{s}(\mathbb{R}^{N})\text{ with }\tilde{v}|_{\Omega}=v\}\]

with the norm:

(1.14) \[\|\,v\,\|_{s,\,\Omega}=\inf_{\tilde{v}\,\in\,H^{s}(\mathbb{R}^{N}),\tilde{v}| _{\Omega}=v}\|\,\tilde{v}\|_{s,\,\mathbb{R}^{N}}.\]

As mentioned above, we have the following relation between \(H^{s}(\Omega)\) and \(W^{s,\,2}(\Omega)\).

**Lemma 1.3**.: _Let \(\Omega\) be a bounded Lipschitz-continuous open subset of \(\mathbb{R}^{N}\). Then algebraically and topologically, we have_

\[W^{s,\,2}(\Omega)=H^{s}(\Omega)\ \ \ \ \ \forall s>0.\]

_In addition, when \(s\) is an integer (1.11) defines the classical Sobolev space \(H^{m}(\Omega)\) with an equivalent norm._

Now, we are in a position to examine the boundary values of functions in \(W^{s,\,p}(\Omega)\). We assume that \(\Omega\) is a bounded open subset of \(\mathbb{R}^{N}\) with a boundary \(\Gamma\) that is at least Lipschitz-continuous. Let us first define what we mean by the space \(W^{s,\,p}(\Gamma)\). According to Definition 1.1, we can view \(\Gamma\) locally as an \(N-1\) dimensional submanifold of \(\mathbb{R}^{N}\) by means of the mapping

\[\Phi(y^{\prime})=(y^{\prime},\phi(y^{\prime}))\]

from \(\mathcal{O}^{\prime}\) onto \(\Gamma\cap\mathcal{O}\). Then we set the following definition.

**Definition 1.4**.: Let \(\Omega\) be a bounded open subset of \(\mathbb{R}^{N}\) with a boundary \(\Gamma\) of class \(\mathcal{C}^{k,\,1}\) for some integer \(k\geqslant 0\). A distribution \(u\) on \(\Gamma\) belongs to \(W^{s,\,p}(\Gamma)\) for \(s\leqslant k+1\) if \(u\circ\Phi\) belongs to \(W^{s,\,p}(\mathcal{O}^{\prime}\cap\Phi^{-1}(\Gamma\cap\mathcal{O}))\) for all possible \(\mathcal{O}\) and \(\phi\) fulfilling the assumptions of Definition 1.1.

Let \((\mathcal{O}_{j},\Phi_{j})_{1\leqslant j\leqslant J}\) be any atlas of \(\Gamma\) such that each pair \((\mathcal{O}_{j},\Phi_{j})\) satisfies the hypotheses of the above definition. Then one possible Banach norm for \(W^{s,\,p}(\Gamma)\)
