(2.15) \[\operatorname{div}\mathbf{u}_{0}=0,\quad\mathbf{u}_{0}|_{\Gamma}= \mathbf{g},\] (2.16) \[|a_{1}(\mathbf{v};\mathbf{u}_{0},\mathbf{v})|\leqslant\varepsilon| \mathbf{v}|_{1,\Omega}^{2}\quad\quad\forall\mathbf{v}\in V.\]

Before proving Lemma 2.3, we check two preliminary lemmas. For any point \(x\in\Omega\), we denote by \(d(x;\Gamma)\) the distance of \(x\) to the boundary \(\Gamma\). Then, we have:

**Lemma 2.4**.: _Let \(\Omega\) be like in Theorem 2.1. For all \(\varepsilon>0\), there exists a function \(\theta_{\varepsilon}\in\mathcal{C}^{2}(\bar{\Omega})\) such that_

(2.17) \[\left\{\begin{aligned} \theta_{\varepsilon}&=1 \quad\text{in a neighborhood of }\Gamma,\\ \theta_{\varepsilon}(x)&=0\quad\text{if }d(x;\Gamma) \geqslant 2\delta(\varepsilon),\quad\delta(\varepsilon)=\exp(-1/\varepsilon), \\ |\partial\theta_{\varepsilon}(x)/\partial x_{i}|& \leqslant\varepsilon/d(x;\Gamma)\quad\text{if }d(x;\Gamma) \leqslant 2\delta(\varepsilon),\quad 1\leqslant i\leqslant N.\end{aligned}\right.\]

Proof.: Let us consider the function \(\mu\to\phi_{\varepsilon}(\mu)\) defined for \(\mu\geqslant 0\) by

\[\phi_{\varepsilon}(\mu)=\left\{\begin{aligned} & 1\quad\quad\quad\quad\quad\quad \text{if }0\leqslant\mu\leqslant\delta(\varepsilon)^{2},\\ &\varepsilon\operatorname{Log}(\delta(\varepsilon)/\mu)\quad \text{if }\delta(\varepsilon)^{2}\leqslant\mu\leqslant\delta(\varepsilon),\\ & 0\quad\quad\quad\quad\quad\quad\quad\text{if }\mu\geqslant\delta( \varepsilon).\end{aligned}\right.\]

Clearly, \(\phi_{\varepsilon}\in W^{1,\,\infty}(\mathbb{R}_{+})\). We set:

\[\chi_{\varepsilon}(x)=\phi_{\varepsilon}(d(x;\Gamma)),\quad\quad x\in\Omega.\]

Since \(\Gamma\) is Lipschitz-continuous, the function \(d\) belongs to \(W^{1,\,\infty}(\Omega)\) and we have

\[|\partial d(x;\Gamma)/\partial x_{i}|\leqslant 1.\]

Hence the function \(\chi_{\varepsilon}\) belongs to \(W^{1,\,\infty}(\Omega)\) and satisfies

\[|\partial\chi_{\varepsilon}(x)/\partial x_{i}|\leqslant\varepsilon/d(x; \Gamma)\quad\text{if }d(x;\Gamma)\leqslant\delta(\varepsilon).\]

By regularizing \(\chi_{\varepsilon}\), we obtain a function \(\theta_{\varepsilon}\in\mathcal{C}^{2}(\bar{\Omega})\) with the properties (2.17). 

**Lemma 2.5**.: _Let \(\Omega\) be like in Theorem 2.1. There exists a constant \(C=C(\Omega)>0\) such that_

(2.18) \[\|\phi/d(.;\Gamma)\|_{0,\Omega}\leqslant C|\phi|_{1,\Omega}\quad\quad\forall \phi\in H^{1}_{0}(\Omega).\]

Proof.: By introducing a partition of unity subordinate to a covering of \(\Gamma\) and systems of local coordinates near \(\Gamma\), we need only to investigate the case where \(\Omega\) is the half-space

\[\mathbb{R}_{+}^{N}=\{x=(x^{\prime},x_{N});\,x_{N}>0\}\]

and \(d(x;\Gamma)=x_{N}\). Hence, for proving (2.18), it is sufficient to check that

\[\int_{\mathbb{R}_{+}^{N}}\left[\phi(x)/x_{N}\right]^{2}dx\leqslant C_{1}\int_ {\mathbb{R}_{+}^{N}}|\partial\phi(x)/\partial x_{N}|^{2}\,dx\quad\quad\forall \phi\in\mathcal{D}(\mathbb{R}_{+}^{N}).\]
