_Problem_ (P):

_Find \(u\) in \(V(\chi)\) such that_

(1.5) \[a(u,v)=\langle l,v\rangle\ \ \ \ \ \forall v\in V,\]

are well posed.

Let us elaborate a weaker formulation of Problem (Q) better suited to the approximation we have in mind. We introduce two reflexive Banach spaces \(\vec{X}\) and \(\vec{M}\) normed respectively by \(\|\,.\,\|_{\vec{X}}\) and \(\|\,.\,\|_{\vec{M}}\) such that:

\[X\underset{d}{\subset}\vec{X},\ \ \ \ \ \vec{M}\underset{d}{\subset}M,\]

where the sign \(\underset{d}{\subset}\) means that the imbedding is dense and continuous.

Next, we consider two continuous bilinear forms:

\[\tilde{a}(.\,,\,.)\colon\vec{X}\,\times\,\vec{X}\to\mathbb{R},\ \ \ \ \ \tilde{b}(.\,,\,.)\colon\vec{X}\,\times\,\vec{M}\to\mathbb{R},\]

with the norms:

\[\|\,\tilde{a}\,\|=\sup_{u,\,v\,\in\,\vec{X}}\frac{\tilde{a}(u,v)}{\|\,u\,\|_{ \vec{X}}\|\,v\,\|_{\vec{X}}},\ \ \ \ \ \ \|\,\tilde{b}\,\|=\sup_{v\,\in\,\vec{X},\,\mu\,\in\,\vec{M}}\frac{\tilde{b}(v ,\mu)}{\|\,v\,\|_{\vec{X}}\|\,\mu\,\|_{\vec{M}}}.\]

These two bilinear forms are extensions of \(a\) and \(b\) in the sense that

(1.6) \[\tilde{a}(u,v)=a(u,v)\ \ \ \ \ \forall u,\,v\in X,\] (1.7) \[\tilde{b}(v,\mu)=b(v,\mu)\ \ \ \ \ \forall v\in X,\ \ \ \ \ \forall\mu\in\vec{M}.\]

In addition, we assume that the right-hand side \(l\) of (1.1) belongs to the dual space \(\vec{X}^{\prime}\) of \(\vec{X}\) and we denote by \(\langle\,.\,,\,.\,\rangle\) the duality pairing between \(\vec{X}\) and \(\vec{X}^{\prime}\). Then we introduce the following _Problem_ (\(\tilde{\mathbb{Q}}\)):

_Find a pair \((\tilde{u},\tilde{\lambda})\!\in\!\vec{X}\,\times\,\vec{M}\) such that_:

(1.8) \[\tilde{a}(\tilde{u},v)+\tilde{b}(v,\tilde{\lambda})=\langle l,v\rangle\ \ \ \ \ \forall v\in\vec{X},\] (1.9) \[\tilde{b}(\tilde{u},\mu)=\langle\,\chi,\mu\rangle\ \ \ \ \ \forall\mu\in\vec{M}.\]

For each \(\chi\!\in\!M^{\prime}\) we define the affine variety:

(1.10) \[\tilde{V}(\chi)=\{v\!\in\!\vec{X};\,\tilde{b}(v,\mu)=\langle\,\chi,\mu\rangle \ \ \ \forall\mu\in\vec{M}\},\]

and the following closed subspace of \(\vec{X}\):

(1.11) \[\tilde{V}=\tilde{V}(0)=\{v\!\in\!\vec{X};\,\tilde{b}(v,\mu)=0\ \ \ \ \forall\mu\in\vec{M}\}.\]

Equality (1.7) implies that:

(1.12) \[V\subset\tilde{V},\ \ \ \ V(\chi)\subset\tilde{V}(\chi).\]

With the Problem (\(\tilde{\mathbb{Q}}\)) we associate the following _Problem_ (\(\tilde{\mathbb{P}}\)):

_Find \(\tilde{u}\) in \(\tilde{V}(\chi)\) such that_

(1.13) \[\tilde{a}(\tilde{u},v)=\langle l,v\rangle\ \ \ \ \ \forall v\in\tilde{V}.\]
