and consequently,

\[\left(\int_{\kappa}q\,\mathrm{div}\,\mathbf{v}\,dx\right)\bigg{/}|\mathbf{v}|_{ {}_{1,\kappa}}\geqslant(\hat{C}/C_{2})\rho_{\kappa}|q|_{{}_{1,\kappa}}.\]

Therefore the theorem is established provided we show that

\[\|q\|_{{}_{0,\kappa}}\leqslant C_{3}h_{\kappa}|q|_{{}_{1,\kappa}}\ \ \ \ \ \forall q\in M_{h}(\kappa)\]

with a constant \(C_{3}>0\) independent of \(\kappa\), \(h\) and \(q\). This will be the object of the next lemma. Assuming this result, we immediately derive that

\[\rho_{\kappa}|q|_{{}_{1,\kappa}}\geqslant(1/C_{3})(\rho_{\kappa}/h_{\kappa})\, \|q\|_{{}_{0,\kappa}}\geqslant[1/(\sigma C_{3})]\,\|q\|_{{}_{0,\kappa}}\]

on account of the regularity of \(\mathcal{T}_{h}\). 

**Lemma 2.5**.: _Let \(\kappa\) be an \(N\)-simplex of \(\mathbb{R}^{N}\). There exists a constant \(C>0\), independent of \(h\) and \(\kappa\) such that the following inequality holds for all functions \(q\) in \(H^{1}(\kappa)\cap L^{2}_{0}(\kappa)\):_

\[\|q\|_{{}_{0,\kappa}}\leqslant Ch_{\kappa}|q|_{{}_{1,\kappa}}.\] (2.26)

Proof.: Recall that

\[\|q\|_{{}_{0,\kappa}}=\inf_{c\,\in\,\mathbb{R}}\|q\,+\,c\|_{{}_{0,\kappa}}\ \ \ \ \ \forall q\in L^{2}_{0}(\kappa).\]

Therefore

\[\|q\|_{{}_{0,\kappa}} =|\det(B_{\kappa})|^{1/2}\inf_{c\,\in\,\mathbb{R}}\|\,\dot{q}\,+\, c\|_{{}_{0,\kappa}}\] \[\leqslant|\det(B_{\kappa})|^{1/2}\,\|\,\dot{q}\,\|_{{}_{H^{1}( \kappa)/\mathbb{R}}}.\]

Then the equivalence Theorem I.1.9 yields:

\[\|q\|_{{}_{0,\kappa}}\leqslant\hat{C}_{1}|\det(B_{\kappa})|^{1/2}|\dot{q}|_{{ }_{1,\kappa}}\leqslant\hat{C}_{2}h_{\kappa}|q|_{{}_{1,\kappa}}\]

in view of (A.7) and (A.2). 

_Remark 2.4_.: We know from Theorem I.1.9 that

\[\|q\|_{{}_{0,\kappa}}\leqslant C(\kappa)|q|_{{}_{1,\kappa}}\ \ \ \ \ \forall q\in H^{1}(\kappa)\cap L^{2}_{0}(\kappa),\]

but the constant \(C(\kappa)\) depends on \(\kappa\) and Lemma 2.5 precises this dependence.

_Remark 2.5_.: Observe that the crucial idea in the proof of Theorem 2.2 is that

\[\left(\prod_{{}_{1\leqslant i\leqslant N+1}}\lambda_{i}\right)\mathbf{grad}\, q\ \ \ \ \text{belongs to }X_{h}(\kappa)\]

whenever \(q\) belongs to \(M_{h}(\kappa)\). We shall see later on that this fundamental property applies as well to elements in three dimensions.
