with constant pressures in \(\kappa\). Formulas (2.1) and (2.2) suggest to take \(\mathbf{w}\) in the space \(\mathcal{P}_{1}(\kappa)\) with:

(2.30) \[\begin{cases}\qquad\qquad\mathcal{P}_{1}(\kappa)=P_{1}^{3}\oplus\operatorname{ span}\{\mathbf{p}_{1},\mathbf{p}_{2},\mathbf{p}_{3},\mathbf{p}_{4}\}\subset P_{3}^{3}\\ \text{where}\\ \mathbf{p}_{1}=\mathbf{n}_{1}\lambda_{2}\lambda_{3}\lambda_{4},\quad\mathbf{ p}_{2}=\mathbf{n}_{2}\lambda_{3}\lambda_{4}\lambda_{1},\quad\mathbf{p}_{3}= \mathbf{n}_{3}\lambda_{4}\lambda_{1}\lambda_{2},\quad\mathbf{p}_{4}=\mathbf{n }_{4}\lambda_{1}\lambda_{2}\lambda_{3}.\end{cases}\]

Note that \(\mathbf{p}_{i}\) vanishes on all faces \(F_{j}\) with \(j\neq i\) and obviously \(\mathbf{p}_{i}\times\mathbf{n}_{i}=\mathbf{0}\) so that

\[\mathbf{p}_{i}\times\mathbf{n}|_{\partial\kappa}=\mathbf{0}\quad\quad 1\leqslant i \leqslant 4.\]

As far as the degrees of freedom of \(\mathbf{w}\) are concerned we can easily take the values of \(\mathbf{w}\) at the vertices \(a_{i}\) of \(\kappa\) and its flux through each face \(F_{i}\). The argument of Lemma 2.1 shows that these \(16\) degrees of freedom are \(\mathcal{P}_{1}(\kappa)\)-unisolvent:

**Lemma 2.7**.: _A polynomial \(\mathbf{p}\) of \(\mathcal{P}_{1}(\kappa)\) is uniquely determined by the \(16\) values:_

(2.31) \[\begin{cases}\qquad\mathbf{p}(a_{i})\quad\quad 1\leqslant i\leqslant 4,\\ \qquad\qquad\int_{F_{i}}\mathbf{p}\cdot\mathbf{n}_{i}\,ds\quad 1\leqslant i \leqslant 4.\end{cases}\]

_In addition, on any face \(F_{i}\) of \(\kappa\), \(\mathbf{p}\) depends only upon the degrees of freedom defined on that face._

The corresponding velocity and pressure spaces are:

(2.32) \[\begin{cases}\qquad W_{h}=\{\mathbf{w}\!\in\!\mathcal{C}^{0}(\bar{\Omega})^{3 };\,\mathbf{w}|_{\kappa}\!\in\!\mathcal{P}_{1}(\kappa)\quad\forall_{K}\!\in \!\mathcal{T}_{h}\},\\ \qquad\qquad\bar{X}_{h}=W_{h}\cap H_{0}^{1}(\Omega)^{3},\end{cases}\] (2.33) \[\begin{cases}\qquad Q_{h}=\{q\!\in\!L^{2}(\Omega);\,q|_{\kappa}\! \in\!P_{0}\quad\forall_{K}\!\in\!\mathcal{T}_{h}\},\\ \qquad\qquad\bar{M}_{h}=Q_{h}\cap L_{0}^{1}(\Omega).\end{cases}\]
