where \(\lambda_{1}\), \(\lambda_{2}\), \(\lambda_{3}\) are the three barycentric coordinates of \(f\). Then (5.31) readily yields that \(\boldsymbol{r}=0\). 

**Lemma 5.8**.: _If the moments of the vector \(\boldsymbol{\mathsf{u}}\) of \(R_{t}\) are all zero on \(\kappa\) then \(\boldsymbol{\mathsf{u}}\) is identically zero._

Proof.: On the one hand, Lemma 5.7 shows that

(5.33) \[\boldsymbol{\mathsf{u}}\times\boldsymbol{\mathsf{n}}=\boldsymbol{0}\quad \text{on }\partial\kappa;\]

on the other hand, we have

(5.34) \[\int_{\kappa}\boldsymbol{\mathsf{u}}\cdot\boldsymbol{\mathsf{q}}\,dx= \boldsymbol{0}\quad\quad\forall\boldsymbol{\mathsf{q}}\in P_{t-3}^{3}(\kappa).\]

Again, since these conditions are preserved by an affine transformation, we can switch to the reference element. Then Green's formula gives:

\[\int_{\hat{\kappa}}\boldsymbol{\mathsf{curl}}\,\hat{\boldsymbol{\mathsf{u}}} \cdot\hat{\boldsymbol{\mathsf{q}}}\,d\hat{x}=0\quad\quad\forall\hat{ \boldsymbol{\mathsf{q}}}\in P_{t-2}^{3}(\hat{\kappa})\]

and it stems from (5.33) that

\[\boldsymbol{\mathsf{curl}}\,\hat{\boldsymbol{\mathsf{u}}}\cdot\hat{ \boldsymbol{\mathsf{n}}}=\boldsymbol{0}\quad\text{on }\partial\hat{\kappa}.\]

Now, _taking advantage of the geometry of \(\hat{\kappa}\)_, it is easy to prove that these conditions (together with the fact that \(\boldsymbol{\mathsf{curl}}\,\hat{\boldsymbol{\mathsf{u}}}\in P_{t-1}^{3}(\hat{ \kappa})\)) imply

\[\boldsymbol{\mathsf{curl}}\,\hat{\boldsymbol{\mathsf{u}}}=\boldsymbol{0}\quad \text{in }\hat{\kappa}.\]

Hence it follows from (5.30) that

\[\boldsymbol{\mathsf{curl}}\,\boldsymbol{\mathsf{u}}=\boldsymbol{0}\quad \text{in }\kappa.\]

Therefore, owing to Lemma 5.3,

\[\boldsymbol{\mathsf{u}}=\boldsymbol{\mathsf{grad}}\,p\]

with \(p\in P_{t}\) and \(p|_{\hat{\kappa}\kappa}=0\) because \(\boldsymbol{\mathsf{u}}\times\boldsymbol{\mathsf{n}}=\boldsymbol{0}\) on \(\partial\kappa\). As a consequence, \(p=\lambda_{1}\lambda_{2}\lambda_{3}\lambda_{4}r\) with \(r\in P_{t-4}(\kappa)\) and (5.34) implies that \(r=0\). 

_Remark 5.5_.: By applying the arguments of Lemmas 5.7 and 5.8 it can also be proved that every vector \(\boldsymbol{\mathsf{u}}\) of \(P_{t}^{3}\) with zero moments in \(\kappa\) satisfies

\[\boldsymbol{\mathsf{curl}}\,\boldsymbol{\mathsf{u}}=\boldsymbol{0}.\]

First, observe that Lemma 5.7 shows that

\[\boldsymbol{\mathsf{curl}}\,\boldsymbol{\mathsf{u}}\cdot\boldsymbol{\mathsf{ n}}=0\quad\text{on the particular face }x_{3}=0.\]

But since this property is preserved by an affine transformation, it holds on each face of \(\kappa\). Then the argument of Lemma 5.8 yields

\[\boldsymbol{\mathsf{curl}}\,\boldsymbol{\mathsf{u}}=\boldsymbol{0}\quad \text{in }\kappa.\]
