_Find a pair \((\psi,\omega)\) in \(\mathcal{G}_{0}\,\times\,H(\operatorname{\mathbf{curl}};\Omega)\) satisfying_:

(5.7) \[\begin{cases}v(\operatorname{\mathbf{curl}}\omega,\operatorname{\mathbf{curl}} \phi)=(\operatorname{\mathbf{f}},\operatorname{\mathbf{curl}}\phi)\quad\quad \forall\phi\in\mathcal{G}_{0},\\ (\operatorname{\mathbf{curl}}\psi,\operatorname{\mathbf{curl}}\mu)=(\omega, \mu)\quad\quad\forall\mu\in H(\operatorname{\mathbf{curl}};\Omega).\end{cases}\]

Next, we introduce:

\[\tilde{X}=\{\operatorname{\mathbf{curl}}\phi;\,\phi\in\mathcal{G}_{0}\,\}\, \times\,L^{2}(\Omega)^{3},\quad\quad\tilde{M}=H(\operatorname{\mathbf{curl}}; \Omega),\]

\[\tilde{a}(u,v)=v(\omega,\theta)\quad\quad\forall u=(\operatorname{\mathbf{ curl}}\psi,\omega),\quad\quad v=(\operatorname{\mathbf{curl}}\phi,\theta)\in \tilde{X},\]

\[\tilde{b}(v,\mu)=(\operatorname{\mathbf{curl}}\phi,\operatorname{\mathbf{curl}} \mu)-(\theta,\mu)\quad\quad\forall v=(\operatorname{\mathbf{curl}}\phi, \theta)\in\tilde{X},\quad\mu\in\tilde{M},\]

\[\langle l,v\rangle= (\operatorname{\mathbf{f}},\operatorname{\mathbf{curl}}\phi) \quad\quad\forall v=(\operatorname{\mathbf{curl}}\phi,\theta)\in\tilde{X}.\]

With this notation, Problem (\(\tilde{Q}\)) takes the more familiar form:

_Find a pair \((u,\lambda)\) in \(\tilde{X}\,\times\,\tilde{M}\) such that_:

(5.8) \[\begin{cases}\tilde{a}(u,v)+\,\tilde{b}(v,\lambda)=\langle l,v\rangle\quad\quad \forall v\in\tilde{X},\\ \tilde{b}(u,\mu)=0\quad\quad\forall\mu\in\tilde{M}.\end{cases}\]

As usual, the space \(\tilde{V}\) is defined by:

\[\tilde{V}=\{v\in\tilde{X};\,\tilde{b}(v,\mu)=0\quad\forall\mu\in\tilde{M}\},\]

i.e.

\[\tilde{V}=\{v=(\operatorname{\mathbf{curl}}\phi,\theta)\in\tilde{X};( \operatorname{\mathbf{curl}}\phi,\operatorname{\mathbf{curl}}\mu)=(\theta, \mu)\quad\quad\forall\mu\in H(\operatorname{\mathbf{curl}};\Omega)\}.\]

Since the mapping \(\phi\to\|\operatorname{\mathbf{curl}}\phi\|_{0,\,\Omega}\) is a norm on \(\mathcal{G}_{0}\) equivalent to the norm of \(H(\operatorname{\mathbf{curl}};\Omega)\) (cf. Lemma I.3.4):

(5.9) \[\|\,\phi\,\|_{0,\,\Omega}\leq C\,\|\operatorname{\mathbf{curl}}\phi\|_{0,\, \Omega}\quad\quad\forall\phi\in\mathcal{G}_{0},\]

it follows that on the one hand we can choose the following norm on \(\tilde{X}\):

\[\|\,v\,\|_{\,\tilde{X}}=(\|\operatorname{\mathbf{curl}}\phi\|_{0,\,\Omega}^{ 2}+\|\,\theta\|_{0,\,\Omega}^{2})^{1/2}\quad\quad\forall v=(\operatorname{ \mathbf{curl}}\phi,\theta)\in\tilde{X};\]

and on the other hand we have:

(5.10) \[\|\operatorname{\mathbf{curl}}\phi\|_{0,\,\Omega}\leq C\,\|\,\theta\|_{0,\, \Omega}\quad\quad\forall v=(\operatorname{\mathbf{curl}}\phi,\theta)\in \tilde{V}.\]

Hence the _mapping \(v=(\operatorname{\mathbf{curl}}\phi,\theta)\to\|\,\theta\|_{0,\,\Omega}\) is a norm on \(\tilde{V}\) equivalent to the norm of \(\tilde{X}\)_:

\[\|\,v\,\|_{\,\tilde{X}}\leq(C^{2}+1)^{1/2}\,\|\,\theta\|_{0,\,\Omega}\]

and we set:

\[|v|=\|\,\theta\|_{0,\,\Omega}.\]

As a consequence, the form \(\tilde{a}(.\,,\,.)\) is \(\tilde{V}\)-elliptic:

\[\tilde{a}(v,v)=v|v|^{2}\geq\tilde{\alpha}\|\,v\,\|_{\,\tilde{X}}^{2}\quad\quad \forall v\in\tilde{V},\]

with \(\tilde{\alpha}=v/(C^{2}+1)\).
