A look at (2.47) and (2.48) suggests to introduce the following bilinear forms:

\[a_{h}(\omega,\mu)=(\omega,\mu)\ \ \ \ \ \ \forall\omega,\ \mu\in L^{2}(\Omega),\] (2.49) \[b_{h}(\theta,\phi)=\sum_{\kappa\in\mathcal{T}_{h}}\int_{\kappa} \lambda\phi\theta\,dx-\int_{\Gamma_{h}}^{\ast}S(\partial\phi/\partial n)\theta \,ds\] (2.50) \[\forall\theta\in H^{1}(\Omega),\ \ \ \ \forall\phi\in H^{1}(\Omega)\ \text{with}\ \phi\in H^{2}(\kappa)\ \text{on all}\ \kappa\ \text{of}\ \mathcal{T}_{h}.\]

(The subscript \(h\) is introduced to emphasize the fact that some of the spaces involved depend upon the triangulation.) With these bilinear forms, Problem (2.48) appears indeed as a _Problem_ (Q\({}_{h}\)):

_Find a pair \((\omega_{h},\psi_{h})\in\Theta_{h}\times\mathcal{G}_{h}\) such that_

\[\begin{cases}a_{h}(\omega_{h},\theta_{h})+\,b_{h}(\theta_{h},\psi_{h})=0\ \ \ \ \ \ \forall\theta_{h}\in\Theta_{h},\\ b_{h}(\omega_{h},\phi_{h})=-\,(1/v)(\mathbf{f},\mathbf{curl}\,\phi_{h})\ \ \ \ \ \forall\phi_{h}\in\Phi_{h}.\end{cases}\] (2.48 \[{}^{\prime}\] )

Obviously,

\[b_{h}(\theta,\phi)=\,-(\mathbf{curl}\,\phi,\mathbf{curl}\,\theta)\] (2.51a) \[\forall\phi\in H^{1}(\Omega)\ \text{with}\ \phi|_{\kappa}\in H^{2}(\kappa),\ \ \ \ \ \forall\theta\in H^{1}(\Omega),\] (2.51b) \[b_{h}(\theta,\phi)=\int_{\Omega}\lambda\phi\theta\,dx\ \ \ \ \ \forall\phi\in H^{2}(\Omega)\ \text{with}\ (\partial\phi/\partial n)|_{\Gamma}=0,\ \ \ \ \ \forall\theta\in H^{1}(\Omega).\]

In addition, observe that \(b_{h}(.,.)\) is well defined if \(\theta\) is only in \(L^{2}(\Omega)\) with \(\theta|_{\Gamma_{h}}\in L^{2}(\Gamma_{h})\). These considerations induce us to associate with these bilinear forms the following mesh-dependent seminorms:

\[\|\theta\|_{0,\,h}=(\|\theta\|_{0,\,\Omega}^{2}+\,h\|\theta\|_{0,\,\Gamma_{h} }^{2})^{1/2}\ \ \ \ \ \forall\theta\in H^{1}(\Omega),\] (2.52) \[\|\phi\|_{2,\,h}=\biggl{(}\sum_{\kappa\in\mathcal{T}_{h}}|\phi|_{2, \,\kappa}^{2}+\,(1/h)\,\|\,S(\partial\phi/\partial n)\|_{0,\,\Gamma_{h}}^{2} \biggr{)}^{1/2}\] (2.53) \[\forall\phi\in H^{1}(\Omega)\ \text{with}\ \phi|_{\kappa}\in H^{2}(\kappa).\]

Clearly,

\[|a_{h}(\omega,\theta)|\leq\|\omega\|_{0,\,\Omega}\|\theta\|_{0,\,\Omega}\ \ \ \ \ \forall\omega,\,\theta\in L^{2}(\Omega),\]

\[|b_{h}(\theta,\phi)|\leq\sqrt{2}\,\|\theta\|_{0,\,h}\|\phi\|_{2,\,h}\ \ \ \ \forall\theta\in H^{1}(\Omega),\ \ \ \ \forall\phi\in H^{1}(\Omega)\ \text{with}\ \phi|_{\kappa}\in H^{2}(\kappa).\]

Nearly all the remainder of this section is devoted to the study of these bilinear forms and seminorms. We are going to see, in particular, that these seminorms are norms on \(\Theta_{h}\) and \(\Phi_{h}\) respectively and that \(b_{h}(.,.)\) satisfies a uniform inf-sup condition with respect to them.

The following lemma shows that \(\|\,.\|_{0,\,h}\) and \(\|\,.\,\|_{0,\,\Omega}\) are _two uniformly equivalent norms_ on \(\Theta_{h}\).

**Lemma 2.7**.: _If \(\mathcal{T}_{h}\) is a uniformly regular family of triangulations of \(\Omega\)_, _there exists a constant \(C>0\)_, _independent of_ \(h\)_, such that:_

\[\|\theta_{h}\|_{0,\,h}\leq C\,\|\theta_{h}\|_{0,\,\Omega}\ \ \ \ \forall\theta_{h}\in\Theta_{h}.\] (2.54)
