it can be easily shown that the matrix \(B_{\kappa}\) is nonsingular and satisfies the following bounds:

\[\|B_{\kappa}\|\leq h_{\kappa}/\rho_{\hat{\kappa}},\ \ \ \ \ \|\,B_{\kappa}^{-1}\| \leq h_{\hat{\kappa}}/\rho_{\kappa},\] (104)

where \(\|\,.\,\|\) stands for both the Euclidean norm of \(\mathbb{R}^{N}\) and its subordinate matrix norm. In addition, owing that

\[|\det(B_{\kappa})|=\mbox{meas}(\kappa)/\mbox{meas}(\hat{\kappa}),\] (105)

there exist two positive constants \(C_{1}(N)\), \(C_{2}(N)\) depending only upon \(N\), such that

\[C_{2}(N)\rho_{\kappa}^{N}\leq|\det(B_{\kappa})|\leq C_{1}(N)h_{\kappa}^{N}.\] (106)

According to convenience, we shall sometimes replace the Euclidean coordinates of the point \(x\) of \(\mathbb{R}^{N}\) by its barycentric coordinates, \(\lambda_{i}=\lambda_{i}(x)\), with respect to the vertices \(a_{i}\), \(1\leq i\leq N\,+\,1\), defined by:

\[\lambda_{i}\!\in\!P_{1},\ \ \ \ \ \lambda_{i}(a_{j})=\delta_{ij}\ \ \ \mbox{for}\ 1\leq i,j\leq N\,+\,1.\] (107)

The barycentric coordinates satisfy the following useful identities in \(\mathbb{R}^{N}\):

\[\sum_{i=1}^{N+1}\lambda_{i}=1,\ \ \ \ p=\sum_{i=1}^{N+1}p(a_{i})\lambda_{i}\ \ \ \ \ \forall p\!\in\!P_{1}.\] (108)

Moreover, it can be easily checked that

\[\kappa=\{x\!\in\!\mathbb{R}^{N};\,0\leq\lambda_{i}(x)\leq 1,\,1\leq i\leq N\,+\,1\}.\]

As mentioned above, the mapping \(x=F_{\kappa}(\hat{x})\) establishes a one-to-one correspondence between \(\hat{\kappa}\) and \(\kappa\). The composition with \(F_{\kappa}\):

\[(v\colon\kappa\to\mathbb{R})\to(\hat{\varrho}=v\circ F_{\kappa};\,\hat{\kappa }\to\mathbb{R})\]

Figure 3: Triangle \(K\) and its reference unit triangle \(\hat{K}\,(N=2)\)
