**Theorem 4.2**.: _Let \(\Omega\) be a bounded, plane polygon and \(\mathcal{T}_{h}\) a triangulation of \(\bar{\Omega}\). Then Problem (4.20) has a unique solution \((\sigma_{h},\psi_{h})\!\in\!\Sigma_{h}\times\Phi_{h}\). Next, assume that the solution \((\mathbf{u}=\mathbf{curl}\,\psi,p)\) of the Stokes Problem (2.1) satisfies (4.17); let \(\sigma=(\partial^{2}\psi/\partial x_{i}\partial x_{j})_{i,j}\)._

\(1^{\circ})\)_If the triangulation \(\mathcal{T}_{h}\) is regular, we have the bound_

(4.40) \[\|\sigma-\sigma_{h}\|_{0,\,\Omega}\leqslant C_{1}h^{k}|\psi|_{k+2,\,\Omega} \quad\forall k\!\in\![1,l],\quad\ l\geqslant 1,\]

_if \(\psi\!\in\!H^{k+2}(\Omega)\). If in addition \(\Omega\) is convex, we have either_

(4.41) \[|\psi-\psi_{h}|_{1,\,\Omega}\leqslant C_{2}h|\psi|_{3,\,\Omega}\quad\text{if }l= 1\quad\text{and}\quad\psi\!\in\!H^{3}(\Omega),\]

_or_

(4.42) \[|\psi-\psi_{h}|_{1,\,\Omega}\leqslant C_{3}h^{k}|\psi|_{k+1,\,\Omega}\quad \quad\forall k\!\in\![2,l]\quad\text{if }l\geqslant 2\quad\text{and}\quad\psi\!\in\!H^{k+1}( \Omega).\]

\(2^{\circ})\)_If \(\mathcal{T}_{h}\) is uniformly regular, we have:_

(4.43) \[\|\sigma-\sigma_{h}\|_{0,\,h}\leqslant C_{4}h^{k}|\psi|_{k+2,\,\Omega}\quad \quad\forall k\!\in\![1,l],\quad\ l\geqslant 1\]

_and if in addition \(\Omega\) is convex, we have:_

(4.44) \[\|\psi-\psi_{h}\|_{2,\,h}\leqslant C_{5}h^{k}|\psi|_{k+2,\,\Omega}\quad \quad\forall k\!\in\![1,l-1],\quad\text{if }l\geqslant 2\]

_and \(\quad\psi\!\in\!H^{k+2}(\Omega)\)._

Proof.: As usual, we have:

(4.45) \[\begin{cases}b_{h}(\sigma-\sigma_{h},\phi_{h})=0&\quad\forall\phi_{h}\!\in \!\Phi_{h},\\ a_{h}(\sigma-\sigma_{h},\tau_{h})+\,b_{h}(\tau_{h},\psi-\psi_{h})=0&\quad \forall\tau_{h}\!\in\!\Sigma_{h}.\end{cases}\]

Owing to Lemma 4.2 and Corollary 4.1, the relations (4.45) yield:

\[b_{h}(\pi_{h}\sigma-\sigma_{h},\phi_{h}) =0\quad\quad\forall\phi_{h}\!\in\!\Phi_{h},\] \[a_{h}(\sigma-\sigma_{h},\pi_{h}\sigma-\sigma_{h}) =0\]

and observe that these equalities hold without constraint on \(\Omega\) and \(\mathcal{T}_{h}\). Now, the last equation implies directly that

(4.46a) \[\|\sigma-\sigma_{h}\|_{0,\,\Omega}\leqslant\|\sigma-\pi_{h}\sigma\|_{0,\, \Omega}.\]

In addition, when \(\mathcal{T}_{h}\) is uniformly regular, the equivalence between the norms \(\|\,.\,\|_{0,\,h}\) and \(\|\,.\,\|_{0,\,\Omega}\) gives

(4.46b) \[\|\sigma-\sigma_{h}\|_{0,\,h}\leqslant C_{1}\|\sigma-\pi_{h}\sigma\|_{0,\,h}.\]

Therefore (4.40) and (4.43) follow from (4.33).

Next, the second equation (4.45) and Corollary 4.1 yield:

(4.47) \[b_{h}(\tau_{h},\overline{I}_{h}\psi-\psi_{h})=a_{h}(\sigma_{h}-\sigma,\tau_{h}) \quad\quad\forall\tau_{h}\!\in\!\Sigma_{h}.\]

Therefore, when \(\Omega\) is convex and \(\mathcal{T}_{h}\) uniformly regular, it stems from Lemma 4.4 that
