We set:

\[V=\operatorname{Ker}(B),\]

and more generally, for each \(\chi\in M^{\prime}\), we define the affine manifold

\[V(\chi)=\{v\in X;\,\,Bv=\chi\}.\]

Equivalently, we have:

\[\begin{cases}V(\chi)=\{v\in X;\,\,b(v,\mu)=\langle\,\chi,\mu\rangle\quad\forall \mu\in M\},\\ \quad V=V(0).\end{cases}\] (4.7)

Moreover, the continuity of the operator \(B\) implies that \(V\) is a closed subspace of \(X\).

Now, with Problem (Q), we associate the following problem, called _Problem_ (P):

_Find \(u\in V(\chi)\) such that_

\[a(u,v)=\langle\,l,v\rangle\quad\quad\forall v\in V.\] (4.8)

Clearly, if \((u,\lambda)\in X\times M\) is a solution of Problem (Q), then \(u\in V(\chi)\) and \(u\) is a solution of (4.8), i.e. \(u\) is a solution of Problem (P). We want to find suitable conditions which ensure that the converse of this statement holds. For this, we define the polar set \(V^{0}\) of \(V\) by

\[V^{0}=\{g\in X^{\prime};\,\langle g,v\rangle=0\quad\forall v\in V\}.\]

**Lemma 4.1**.: _The three following properties are equivalent:_

(i) _there exists a constant \(\beta>0\) such that_

\[\inf_{\mu\in M}\sup_{v\in X}\frac{b(v,\mu)}{\|\,v\,\|_{X}\|\,\mu\,\|_{M}} \geq\beta;\] (4.9)

(ii) _the operator \(B^{\prime}\) is an isomorphism from \(M\) onto \(V^{0}\) and_

\[\|\,B^{\prime}\mu\,\|_{X^{\prime}}\geq\beta\,\|\,\mu\,\|_{M}\quad\quad\forall \mu\in M;\] (4.10)

(iii) _the operator \(B\) is an isomorphism from \(V^{\perp}\) onto \(M^{\prime}\) and_

\[\|\,Bv\,\|_{M^{\prime}}\geq\beta\,\|\,v\,\|_{X}\quad\quad\forall v\in V^{\perp}.\] (4.11)

Proof.: \(1^{\circ}\)) Let us show that the properties (i) and (ii) are equivalent. By (4.5), statement (i) means that

\[\|\,B^{\prime}\mu\,\|_{X^{\prime}}=\sup_{v\in X,\,v\neq\mathbf{0}}\frac{ \langle B^{\prime}\mu,v\rangle}{\|\,v\,\|_{X}}\geq\beta\,\|\,\mu\,\|_{M}\quad \quad\forall\mu\in M,\]

so that (4.9) is equivalent to (4.10). Hence (ii) implies (i). In order to prove that (i) implies (ii), it remains only to show that, under the condition (4.10), \(B^{\prime}\) is an isomorphism from \(M\) onto \(V^{0}\). Clearly, it follows from (4.10) that \(B^{\prime}\) is a one-to
