Let \(\mathcal{F}\tilde{\mathbf{v}}\) denote the Fourier transform of \(\tilde{\mathbf{v}}\), defined as usual by:

\[\mathcal{F}\tilde{\mathbf{v}}(\mu)=\int_{\mathbb{R}^{3}}e^{-2i\pi(x,\mu)}\tilde{ \mathbf{v}}(x)\,dx,\] (2.23)

where

\[(x,\mu)=\sum_{i=1}^{3}\,x_{i}\mu_{i}.\]

Owing to the properties of the Fourier transform, it is well known that \(\mathcal{F}\tilde{\mathbf{v}}\in L^{2}(\mathbb{R}^{3})\),3

Footnote 3: The Fourier transform of \(\tilde{\mathbf{v}}\) is defined as \(\mathcal{F}(\tilde{\mathbf{v}})=\mathcal{F}(\tilde{\mathbf{v}})\).

\[\|\mathcal{F}\tilde{\mathbf{v}}\|_{0,\,\mathbb{R}^{3}}=\|\,\mathbf{v}\|_{0,\, \Omega},\]

\[\mathcal{F}(\mathbf{curl}\,\tilde{\mathbf{v}})=2i\pi(\mu_{2}\mathcal{F}\tilde{ v}_{3}-\mu_{3}\mathcal{F}\tilde{v}_{2},\mu_{3}\mathcal{F}\tilde{v}_{1}-\mu_{1} \mathcal{F}\tilde{v}_{3},\mu_{1}\mathcal{F}\tilde{v}_{2}-\mu_{2}\mathcal{F} \tilde{v}_{1}),\]

\[\mathcal{F}(\mathrm{div}\,\tilde{\mathbf{v}})=2i\pi(\mu_{1}\mathcal{F}\tilde{ v}_{1}+\mu_{2}\mathcal{F}\tilde{v}_{2}+\mu_{3}\mathcal{F}\tilde{v}_{3}).\]

From these two relations, we readily derive that

\[\|\mathcal{F}(\partial\tilde{v}_{i}/\partial x_{j})\|_{0,\,\mathbb{R}^{3}}^{2} \leqslant\|\mathrm{div}\,\mathbf{v}\|_{0,\,\Omega}^{2}+\|\,\mathbf{curl}\, \mathbf{v}\|_{0,\,\Omega}^{2}.\]

Therefore \(\tilde{\mathbf{v}}\in H^{1}(\mathbb{R}^{3})^{3}\). This implies that \(\mathbf{v}\in H^{1}_{0}(\Omega)^{3}\). Furthermore,

\[\|\,\mathbf{v}\|_{1,\,\Omega} =\|\,\tilde{\mathbf{v}}\|_{1,\,\mathbb{R}^{3}}\] \[\leqslant C(\|\,\mathbf{v}\|_{0,\,\Omega}^{2}+\|\,\mathrm{div}\, \mathbf{v}\|_{0,\,\Omega}^{2}+\|\,\mathbf{curl}\,\mathbf{v}\|_{0,\,\Omega}^{ 2})^{1/2},\]

with a constant \(C\) independent of \(\Omega\).

The inverse inclusion and inequality are obvious. 

The next corollary is a simple consequence of Lemma 2.5.

**Corollary 2.10**.: _Let \(\Omega\) be an arbitrary open subset of \(\mathbb{R}^{N}\) and let \(\mathbf{v}\) belong to \(H(\mathrm{div};\Omega)\cap H(\mathbf{curl};\Omega)\). Then \(\mathbf{v}\) belongs to \(H^{1}_{\mathrm{loc}}(\Omega)^{3}\)._

_Remark 2.6_.: It stems from the proof of Lemma 2.5 that, algebraically and topologically:

\[H^{1}(\mathbb{R}^{N})^{N}=H(\mathrm{div};\mathbb{R}^{N})\cap H(\mathbf{curl}; \mathbb{R}^{N}).\]

_Remark 2.7_.: Lemma 2.5 and Theorem 2.1 readily yield that

\[|\mathbf{v}|_{1,\,\Omega}\leqslant C(\|\,\mathrm{div}\,\mathbf{v}\|_{0,\, \Omega}^{2}+\|_{\,\mathbf{curl}\,\mathbf{v}}\|_{0,\,\Omega}^{2})^{1/2}\quad \quad\forall\mathbf{v}\in H_{0}(\mathrm{div};\Omega)\cap H_{0}(\mathbf{curl}; \Omega).\]

## 3 A Decomposition of Vector Fields

In the preceding paragraph, we have derived the following decompositions into orthogonal subspaces:

\[L^{2}(\Omega)^{N}=H\oplus H^{\perp},\quad\,H^{1}_{0}(\Omega)^{N}=V\oplus V^{ \perp},\]
