Furthermore, Lemma III.3.3 gives the best estimate when \(\phi\) belongs to \(H^{t+3/2}(\Omega)\cap W^{t+1,\,\infty}(\Omega)\)

\[\|\pi_{h}v-v\|_{X}\leqslant Ch^{t-1/2}(\|\phi\|_{t+3/2,\,\Omega}+\|\phi\|_{t+1, \,\infty,\,\Omega}).\]

Now we turn to (3.62); we have

\[\langle G_{h}(\pi_{h}u)-G(u),\mathbf{v}_{h}\rangle=\tilde{a}^{\pi_{h}u}(\pi_{h }u;\pi_{h}u,\mathbf{v}_{h})-a_{1}(u;u,\mathbf{v}_{h})\quad\quad\forall\mathbf{ v}_{h}=\mathbf{curl}\,\phi_{h},\,\phi_{h}\!\in\!\Phi_{h}.\]

Using a simple rearrangement of terms we obtain:

\[\langle G_{h}(\pi_{h}u)-G(u),\mathbf{v}_{h}\rangle=\tilde{a}^{\pi_{h}u}(\pi_{h }u;\pi_{h}u-u,\mathbf{v}_{h})+a_{1}(\pi_{h}u-u;u,\mathbf{v}_{h}).\]

Therefore Lemma 5.4 and Lemma 5.2 together with (5.22) yield:

(5.41) \[\|G_{h}(\pi_{h}u)-G(u)\|_{h}\leqslant Ch^{1/2}(|\psi|_{2,\,\Omega}+|\hat{P}_{ h}\psi|_{1,\,4,\Omega})[\hat{P}_{h}\psi-\psi]_{4}.\]

Hence (3.62) follows from Lemma 5.1. Furthermore we infer from this lemma and (5.41) that

(5.42) \[\|G_{h}(\pi_{h}u)-G(u)\|_{h}\leqslant Ch^{k-1/2}|\psi|_{2,\,\Omega}\|\psi\|_{ k+1,\,\Omega}\] \[\forall u=(\mathbf{curl}\,\psi,\omega)\!\in\!V\quad\text{with }\psi\!\in\!H^{k+1}(\Omega),\quad 1 \leqslant k\leqslant l.\]

As far as (3.63) is concerned, we apply Definition 5.1 and (5.37):

\[\langle(\nabla G_{h}(\pi_{h}u)-DG(u))\cdot v_{h},\mathbf{w}_{h}\rangle =\tilde{a}^{\pi_{h}u}(\pi_{h}u;v_{h},\mathbf{w}_{h})+\tilde{a}^{ \pi_{h}u}(v_{h};\pi_{h}u,\mathbf{w}_{h})\] \[\quad-a_{1}(u;Pv_{h},\mathbf{w}_{h})-a_{1}(v_{h};u,\mathbf{w}_{h} )\quad\quad\forall u\!\in\!V\] \[=\tilde{a}^{\pi_{h}u}(\pi_{h}u;v_{h}-Pv_{h},\mathbf{w}_{h})+ \tilde{a}^{\pi_{h}u}(v_{h};\pi_{h}u-u,\mathbf{w}_{h})\] \[\quad+a_{1}(\pi_{h}u-u;Pv_{h},\mathbf{w}_{h})\]

taking into account the regularity of \(u\) and \(Pv_{h}\). Consequently, it stems from Lemma 5.3 and 5.4 that:

\[\|(FG_{h}(\pi_{h}u)-DG(u))\cdot v_{h}\|_{h}\leqslant C\{h^{1/2}(|\check{P}_{h}\psi|_{1,\,4,\,\Omega}[\phi_{h}-\phi]_{4} +|v_{h}|[\hat{P}_{h}\psi-\psi]_{4})\] \[\quad+|v_{h}|[\hat{P}_{h}\psi-\psi|_{1,\,4,\,\Omega}\},\]

with \(Pv_{h}=(\mathbf{curl}\,\phi,\theta_{h})\), \(\forall u=(\mathbf{curl}\,\psi,\omega)\!\in\!V\), \(\forall v_{h}=(\mathbf{curl}\,\phi_{h},\theta_{h})\!\in\!V_{h}\).

Thus Lemma 5.1 gives:

\[\|(FG_{h}(\pi_{h}u)-DG(u))\cdot v_{h}\|_{h}\leqslant Ch^{1/2}(|\psi|_{1,\,4, \,\Omega}+\|\psi\|_{2,\,\Omega})|v_{h}|,\]

which implies (3.63).

Finally, it remains to verify (3.64). Take \(u_{h}\), \(u_{h}^{*}\) and \(u_{h}^{0}\) in \(V_{h}\); by definition we have for all \(\mathbf{w}_{h}=\mathbf{curl}\,\chi_{h}\), \(\chi_{h}\!\in\!\Phi_{h}\):

\[\langle G_{h}(u_{h})-G_{h}(u_{h}^{*})-FG_{h}(u_{h}^{0})\cdot(u_{h}-u_{h}^{*}), \mathbf{w}_{h}\rangle\] \[=\tilde{a}^{\pi_{h}}(u_{h};u_{h},\mathbf{w}_{h})-\tilde{a}^{u_{h} ^{*}}(u_{h}^{*};u_{h}^{*},\mathbf{w}_{h})-\tilde{a}^{u_{h}^{0}}(u_{h}^{0};u_{h }-u_{h}^{*},\mathbf{w}_{h})-\tilde{a}^{u_{h}^{0}}(u_{h}-u_{h}^{*};u_{h}^{0}, \mathbf{w}_{h})\] \[=\tilde{a}^{u_{h}^{0}}(u_{h}-u_{h}^{0};u_{h}-u_{h}^{*},\mathbf{w} _{h})+\tilde{a}^{u_{h}^{0}}(u_{h}-u_{h}^{*};u_{h}^{*}-u_{h}^{0},\mathbf{w}_{h} )+\{\tilde{a}^{u_{h}^{0}}(u_{h};u_{h},\mathbf{w}_{h})\] \[\quad-a_{2}^{u_{h}^{0}}(u_{h};u_{h},\mathbf{w}_{h})-a_{2}^{u_{h}^{ *}}(u_{h}^{*};u_{h}^{*},\mathbf{w}_{h})+a_{2}^{u_{h}^{0}}(u_{h}^{*};u_{h}^{*}, \mathbf{w}_{h})\}.\]
