Recall the _Problem_ (P) associated with Problem (Q):

_Given \(l\) in \(X^{\prime}\) and \(\chi\) in \(M^{\prime}\), find \(u\) in \(V(\chi)\) such that_:

\[a(u,v)=\langle l,v\rangle\quad\quad\forall v\in V.\] (1.3)

We retain the two hypotheses which guarantee that Problems (Q) and (P) are equivalent and have a unique solution (cf. Theorem 1.4.1 and its Corollary):

there exists a constant \(\alpha>0\) such that

\[a(v,v)\geq\alpha\|v\|_{X}^{2}\quad\quad\forall v\in V;\] (1.4)

there exists a constant \(\beta>0\) such that

\[\inf_{\mu\in M}\sup_{v\in X}\frac{b(v,\mu)}{\|v\|_{X}\|\mu\|_{M}}\geq\beta.\] (1.5)

Let \(h\) denote a discretization parameter tending to zero and, for each \(h\), let \(X_{h}\) and \(M_{h}\) be two _finite-dimensional_ spaces such that:

\[X_{h}\subset X,\quad\quad M_{h}\subset M.\]

Let \(X^{\prime}_{h}\) and \(M^{\prime}_{h}\) denote their dual spaces with the dual norms:

\[\|I_{h}\|_{X^{\prime}_{h}}=\sup_{v_{h}\in X_{h}}\frac{\langle l_{h},v_{h} \rangle}{\|v_{h}\|_{X}},\quad\quad\|\chi_{h}\|_{M^{\prime}_{h}}=\sup_{\mu_{h} \in M_{h}}\frac{\langle\chi_{h},\mu_{h}\rangle}{\|\mu_{h}\|_{M}}.\]

Clearly,

\[\|I\|_{X^{\prime}_{h}}\leq\|I\|_{X^{\prime}},\quad\quad\|\chi\|_{M^{\prime}_{h }}\leq\|\chi\|_{M^{\prime}}\quad\quad\forall l\in X^{\prime},\quad\quad\forall \chi\in M^{\prime}.\]

Like in the continuous case, we associate with \(a(.,.)\) and \(b(.,.)\) the operators \(A_{h}\in\mathcal{L}(X;X^{\prime}_{h})\), \(B_{h}\in\mathcal{L}(X;M^{\prime}_{h})\) and \(B^{\prime}_{h}\in\mathcal{L}(M;X^{\prime}_{h})\) defined by:

\[\langle A_{h}u,v_{h}\rangle = a(u,v_{h})\quad\quad\forall v_{h}\in X_{h},\quad\quad\forall u \in X,\] \[\langle B_{h}v,\mu_{h}\rangle = b(v,\mu_{h})\quad\quad\forall\mu_{h}\in M_{h},\quad\quad\forall v \in X,\] \[\langle v_{h},B^{\prime}_{h}\mu\rangle = b(v_{h},\mu)\quad\quad\forall v_{h}\in X_{h},\quad\quad\forall \mu\in M.\]

Strictly speaking, \(B^{\prime}_{h}\) is not the dual operator of \(B_{h}\) but if \(B_{h}\) is restricted to \(X_{h}\) and \(B^{\prime}_{h}\) to \(M_{h}\) then \(B_{h}\) and \(B^{\prime}_{h}\) are indeed dual operators. In addition, we obviously have:

\[\|B_{h}v\|_{M^{\prime}_{h}}\leq\|Bv\|_{M^{\prime}}\quad\quad\forall v\in X\]

with similar inequalities for \(\|A_{h}v\|_{X^{\prime}_{h}}\) and \(\|B^{\prime}_{h}\mu\|_{X^{\prime}_{h}}\).

For each \(\chi\in M^{\prime}\), we define the finite-dimensional analogue of \(V(\chi)\):

\[V_{h}(\chi)=\{v_{h}\in X_{h};\,b(v_{h},\mu_{h})=\langle\chi,\mu_{h}\rangle \quad\forall\mu_{h}\in M_{h}\}\]

and we set

\[V_{h}=V_{h}(0)=\operatorname{Ker}(B_{h})\cap X_{h};\]

i.e.
