Index of Mathematical Symbols

\(a(.;.,.)\), \(a_{0}(.,.,.)\) 285

\(a_{1}(.;.,.,.)\) 284

\(\mathscr{C}^{m}(\Omega)\), \(\mathscr{C}^{m}(\overline{\Omega})\), \(\mathscr{C}^{m,\,1}(\overline{\Omega})\) 3

\(\mathbf{curl}\)\(u\), \(\mathbf{curl}\)\(\mathbf{u}\) 31

\(\mathscr{D}(\Omega)\), \(\mathscr{D}(\overline{\Omega})\), \(\mathscr{D}^{\prime}(\Omega)\) 1

\(D_{i,j}(u)\) 79

\(\mathrm{div}\)\(\mathbf{u}\) 22

\(\mathscr{F}\)\(v\) 36

\(\Phi\) 40

\(\Phi_{h}\) 98, 107

\(\Gamma_{h}\) 214

\(\gamma_{0}\)\(u\) 8

\(\gamma_{1}\)\(u\) 9

\(\gamma_{n}\) 27

\(\gamma_{\tau}\) 34

\(\mathbf{grad}\)\(u\), \(\mathcal{A}\)\(u\) 10

\(H\) 29

\(H(\mathbf{curl};\Omega)\), \(H_{0}(\mathbf{curl};\Omega)\) 32

\(H(\mathrm{div};\Omega)\), \(H_{0}(\mathrm{div};\Omega)\) 26

\(H^{m}(\Omega)\) 2

\(H^{s}(\Omega)\) 7

\(h_{\kappa}\) 95, 105

\(I_{h}\) 99, 108

\(\widetilde{I}_{h}\) 101, 108

\(J_{F}\) 105

\(\kappa\), \(\hat{\kappa}\) 95, 104

\(L_{0}^{2}(\Omega)\) 23

\(M_{n}(\tau)\), \(M_{m}(\tau)\) 238

\(\mathscr{N}\) 287

\(v\) 79

\(P_{h}\), \(\hat{P}_{h}\) 101

\(P_{k}\) 95

\(\mathcal{P}_{1}(\kappa)\) 135, 145, 174

\(\mathcal{P}_{2}(\kappa)\) 147

\(\mathcal{P}_{l}(\kappa)\) 139, 150

\(\mathcal{P}_{1}(\kappa)\) 139, 150

\(\mathcal{Q}_{k}\) 104

\(\mathcal{Q}_{h}\) 98, 107

Re 80

\(\rho_{h}\) 102, 108

\(\rho_{\kappa}\) 95, 105

\(\sigma_{\kappa}\) 95

\(\mathscr{C}_{h}\) 98

\(\mathscr{V}\) 22

\(V^{0}\) 23

\(W^{m,\,p}(\Omega)\), \(W^{m,\,p}_{10c}(\Omega)\) 2

\(W^{m,\,p}_{0}(\Omega)\), \(W^{-m,\,p^{\prime}}(\Omega)\) 3

\(W^{s,\,p}(\Omega)\), \(W^{s,\,p}_{0}(\Omega)\) 6

\(W^{s,\,p}(\Gamma)\) 7

\(\Psi\) 42

\(\Psi\) 214

\([.]_{k,\,p,\Omega}\) 106

\(|.\,|_{m,\,p,\Omega}\) 2

\(\|.\,|_{m,\,p,\Omega}\) 2, 20

\(\|.\,|_{s,\,p,\Omega}\) 6, 8

\(\|.\,|_{s,\,p,\Omega}\) 8

\(\|.\,|_{-m,\,p^{\prime},\Omega}\) 3

\(\|.\,|_{-1/2,\,\Gamma}\) 8

\(\|.\,|_{H^{1}(\Omega)/\mathbb{R}}\) 13

\(\|.\,|_{H(\mathbf{curl};\Omega)}\) 32

\(\|.\,|_{H(\mathrm{div};\Omega)}\) 26

\((.,.)_{m,\Omega}\) 2

\((-\,\mathcal{A})^{-1}\) 23
