Proof.: The proof is much like that of Theorem 2.2 so we shall only dwell on the details inherent to quadrilaterals. We have:

\[\int_{\kappa}q\operatorname{div}\mathbf{v}\,dx =-\int_{\kappa}\mathbf{v}\boldsymbol{\cdot}\,\mathbf{grad}\,q\,dx\] \[=-\int_{\hat{\kappa}}J_{\hat{\kappa}}\hat{\boldsymbol{\cdot}}\left[ \left(\mathbf{grad}\,q\right)\circ F_{\kappa}\right]d\hat{\kappa}.\]

Since \(q\in P_{t-1}\), we have \(\mathbf{grad}\,q\in P_{t-2}^{2}\) and therefore

\[\left(\mathbf{grad}\,q\right)\circ F_{\kappa}\in Q_{t-2}^{2}\quad\text{on } \hat{\kappa}.\]

Let

\[b(\hat{x})=\hat{x}_{1}\hat{x}_{2}\hat{x}_{3}\hat{x}_{4}\]

denote the "bubble" function on \(\hat{\kappa}\) and let us choose

\[\hat{\boldsymbol{\cdot}}=-b(\hat{x})[(\mathbf{grad}\,q)\circ F_{\kappa}].\]

Then \(\mathbf{v}\in X_{h}(\kappa)\) and with this choice

\[\int_{\kappa}q\operatorname{div}\mathbf{v}\,dx=\int_{\hat{\kappa}}J_{\hat{ \kappa}}b(\hat{x})\,\|\left(\mathbf{grad}\,q\right)\circ F_{\kappa}\|^{2}\,d \hat{x}.\]

Of course the mapping

\[\phi\to\int_{\hat{\kappa}}b(\hat{x})|\phi|\,d\hat{x}\]

is a norm on any finite-dimensional space; thus

\[\int_{\kappa}q\operatorname{div}\mathbf{v}\,dx \geq C_{1}\int_{\hat{\kappa}}J_{\hat{\kappa}}\|\left(\mathbf{grad }\,q\right)\circ F_{\kappa}\|^{2}\,d\hat{x}\] \[\geq C_{1}|q|_{1,\kappa}^{2}.\]

Besides that

\[\|\mathbf{v}\|_{0,\kappa}\leq|q|_{1,\kappa}\]

and

\[|\mathbf{v}|_{1,\kappa}\leq C_{2}(\sigma_{\kappa}^{2}/\rho_{\kappa})\,\| \mathbf{v}\|_{0,\kappa}\]

by applying to quadrilaterals the easy argument of Lemma A.6. Hence

\[\int_{\kappa}q\operatorname{div}\mathbf{v}\,dx\geq C_{3}(\rho_{\kappa}/\sigma _{\kappa}^{2})|q|_{1,\kappa}.\]

Therefore the result follows from the next lemma and the regularity of \(\mathcal{T}_{h}\).
