for a _fixed_\(s\geqslant 4\) and \(1/r+1/s=1\). For \(\mathbf{f}\!\in\!L^{\prime}(\Omega)^{2}\), we know that the Stokes operator can be expressed by:

\[\left\{\begin{aligned} T\mathbf{f}&=u=(\sigma,\psi) \!\in\!\widetilde{\mathcal{L}}\times\,\tilde{\mathcal{U}},\\ b_{h}(\sigma,\phi)&=-(\mathbf{f},\mathbf{curl}\, \phi)\quad\,\,\,\,\forall\phi\!\in\!\tilde{\mathcal{U}},\\ a_{h}(\sigma,\tau)+b_{h}(\tau,\psi)&=0\quad\,\, \,\forall\tau\!\in\!\widetilde{\mathcal{L}}.\end{aligned}\right.\]

Setting

\[Y=L^{\prime}(\Omega)^{2},\] \[X=\{\sigma=(\sigma_{ij})\!\in\!L^{2}(\Omega)^{4};\,\sigma_{1\,2}= \sigma_{2\,1}\}\times\,\Phi_{s},\]

we have

\[T\!\in\!\mathcal{L}(Y;X)\]

and since the Stokes problem is regular we also have

\[T\!\in\!\mathcal{L}(Y;\,W^{1,\,r}(\Omega)^{4}\times\,W^{3,\,r}(\Omega)).\]

In view of (4.31) we introduce the nonlinear convection term by:

\[G(\lambda,u)=-\lambda(\operatorname{tr}(\sigma)\operatorname{grad}\psi\,+ \,\mathbf{f})\]

which is a \(\mathcal{C}^{\infty}\)-mapping from \(\Lambda\times X\) into \(L^{\prime}(\Omega)^{2}\). With these notations, the Navier-Stokes equations take the standard form:

(4.48) \[u(\lambda)\!\in\!X,\quad\,\,F(\lambda,u(\lambda))\equiv u(\lambda)+\,TG( \lambda,u(\lambda))=0\quad\,\,\,\forall\lambda\!\in\!\Lambda.\]

As far as the approximation is concerned, we take

\[X_{h}=\mathcal{L}_{h}\times\,\Phi_{h}\subset X,\]

where

\[\mathcal{L}_{h} =\{\tau\!\in\!\widetilde{\mathcal{L}};\,\tau|_{\kappa}\!\in\!P_{ l-1}^{4}\quad\forall\kappa\!\in\!\mathcal{T}_{h}\},\] \[\Phi_{h} =\{\phi\!\in\!\Phi;\,\phi|_{\kappa}\!\in\!P_{l}\quad\forall\kappa \!\in\!\mathcal{T}_{h}\}\]

for some integer \(l\geqslant 1\). The Stokes operator is discretized by

\[T_{h}\mathbf{f}=u_{h}=(\sigma_{h},\psi_{h})\!\in\!X_{h},\] \[b_{h}(\sigma_{h},\phi_{h})=-(\mathbf{f},\mathbf{curl}\,\phi_{h} )\bigg{\}}\quad\forall v_{h}=(\tau_{h},\phi_{h})\!\in\!X_{h};\] \[a_{h}(\sigma_{h},\tau_{h})+\,b_{h}(\tau_{h},\psi_{h})=0\bigg{\}} \quad\forall v_{h}=(\tau_{h},\phi_{h})\!\in\!X_{h};\]

and the Navier-Stokes equations are approximated by:

(4.49) \[u_{h}(\lambda)\!\in\!X_{h},\quad\,\,F_{h}(\lambda,u_{h}(\lambda))\equiv u_{h} (\lambda)+\,T_{h}G(\lambda,u_{h}(\lambda))=0\quad\,\,\,\forall\lambda\!\in\!\Lambda.\]

The results of Section III.4.3 give the following estimate for \(T-T_{h}\):

\[\|(T-T_{h})\mathbf{f}\|_{X} \equiv\|\sigma-\sigma_{h}\|_{0,\Omega}+|\psi-\psi_{h}|_{1,\,s,\Omega}\] \[\leqslant Ch^{2(1-1/r)}|\psi|_{3,\,r,\Omega}.\]
