\[\sup_{\nu\,\in\,X_{h}}\biggl{[}\biggl{(}\int_{\Omega}q\,\mathrm{div}\,\nu\,dx \biggr{)}\biggl{/}|\nu|_{1,\Omega}\biggr{]}\leq\sqrt{3}\,h\,\|\,q\,\|_{0,\,\Omega}.\]

Together with Lemma 3.5, this means that the constant \(\beta^{\star}\) is really \(O(h)\).

In fact, it can be proved that this undesirable factor \(h\) arises exclusively from the local alternating component \(v_{4}\) in the functions of \(\mathcal{M}_{h}\). Again let us write \(q\in\mathcal{M}_{h}\) in terms of the basis functions \(v_{k}\):

\[q=\sum_{k=1}^{4}\,q^{k},\]

where

\[q^{k}=\sum_{I,J}\,(x_{k}v_{k})_{I,J},\quad\,(\alpha_{k})_{I,J}\in\mathbb{R}, \quad\,\sum_{I,J}\,(\alpha_{1})_{I,J}=\sum_{I,J}\,(\alpha_{4})_{I,J}=0.\]

Following Boland & Nicolaides [12] we split \(\mathcal{M}_{h}\) as follows:

\[\mathcal{M}_{h}=\,A_{h}+\widetilde{M}_{h},\]

where

(3.32) \[\biggl{\{}\begin{aligned} A_{h}&=\{q\in \mathcal{M}_{h};\,q|_{\Omega_{I,J}}=(\alpha_{4}v_{4})_{I,J}\},\\ \widetilde{M}_{h}&=\,A_{h}^{\perp}=\{q\in \mathcal{M}_{h};\,q|_{\Omega_{I,J}}=(\alpha_{1}v_{1}+\alpha_{2}v_{2}+\alpha_{ 3}v_{3})_{I,J}\}\end{aligned}\]

and we associate with these spaces the following subspace of \(X_{h}\):

(3.33) \[\widetilde{V}_{h}=\{\nu_{h}\in X_{h};\,(q_{h},\mathrm{div}\,\nu_{h})=0\quad \forall q_{h}\in A_{h}\}.\]

We propose to establish that the pair \((\widetilde{V}_{h},\widetilde{M}_{h})\) satisfies a uniform inf-sup condition.

To this end, let us start with a local condition.

**Lemma 3.7**.: _With the above notations and hypotheses of Lemma 3.5, the pair \((\widetilde{V}_{h},\widetilde{M}_{h})\) satisfies uniformly a local inf-sup condition with respect to the partition \(\{\Omega_{I,J}\}\) of \(\widetilde{\Omega}\)._

Proof.: Let

\[X_{h}(\Omega_{I,J})=\{\nu\in\widetilde{V}_{h};\,\nu|_{\partial \Omega_{I,J}}=\mathbf{0}\},\] \[M_{h}(\Omega_{I,J})=\{q|_{\partial_{I,J}};\,q\in\widetilde{M}_{ h}\}\cap L_{0}^{2}(\Omega_{I,J}).\]

We must show that all \(q\in M_{h}(\Omega_{I,J})\) satisfy:

(3.34) \[\sup_{\nu\,\in\,X_{h}(\Omega_{I,J})}\biggl{[}\biggl{(}\int_{\Omega_{I,J}}q\, \mathrm{div}\,\nu\,dx\biggr{)}\biggl{/}|\nu|_{1,\Omega_{I,J}}\biggr{]}\geq C \,\|\,q\,\|_{0,\,\Omega_{I,J}}.\]

First, observe that

\[X_{h}(\Omega_{I,J})=\{\nu=\nu_{I,J}\phi_{I,J};\,\forall\nu_{I,J}=(u_{I,J},v_{ I,J})\in\mathbb{R}^{2}\},\]

where \(\phi_{I,J}\) denotes the basis function of \(X_{h}\) that takes the value \(1\) at the node \((I,J)\) and \(0\) at all other nodes of \(\mathcal{T}_{h}\). Similarly, we have
