**Corollary 2.2**.: _If \(\mathcal{T}_{h}\) is uniformly regular\(,\) there exists a constant \(C>0,\) independent of \(h,\) such that_

\[\|\phi\|_{2,\,h}\geqslant C\left\{\|\phi\|_{1,\,\Omega}^{2}+\sum_{\kappa\in \mathcal{T}_{h}}|\phi|_{2,\,\kappa}^{2}\right\}^{1/2},\] (2.58)

_for all \(\phi\in\vec{\mathcal{V}}.\)_

Proof.: By virtue of Lemma I.3.1 (a generalized Poincare inequality), it suffices to show that:

\[\|\phi\|_{2,\,h}\geqslant C_{1}|\phi|_{1,\,\Omega}.\]

But it follows from (2.47) and (2.50) that

\[|\phi|_{1,\,\Omega}^{2}=-\,b_{h}(\phi,\phi)\leqslant\sqrt{2}\,\|\phi\|_{2,\,h }\|\phi\|_{0,\,h}\]

and (2.57) combined with Lemma I.3.1 yields (2.58). 

Corollary 2.2 means that the space \(\vec{\mathcal{V}}\) is a Hilbert space for the norm \(\|\,.\,\|_{2,\,h}.\)

The next two lemmas derive approximation properties of the space \(\mathcal{O}_{h}.\)

**Lemma 2.10**.: _Let \(\mathcal{T}_{h}\) be a regular triangulation of \(\bar{\Omega}.\) For each real \(k\in[1,l+1]\) there exists a constant \(C>0,\) independent of \(h,\) such that:_

\[\inf_{\theta_{h}\in\mathcal{O}_{h}}\|v-\theta_{h}\|_{0,\,h}\leqslant Ch^{k}|v |_{k,\,\Omega}\ \ \ \ \ \forall v\in H^{k}(\Omega).\] (2.59)

Proof.: If \(k\geqslant 2\) we take \(\theta_{h}=I_{h}v,\) the interpolation defined by (A.20); otherwise, we take \(\theta_{h}=R_{h}v,\) the local regularization defined by (A.53), (A.54). Then either (A.21a) or (A.55) gives:

\[\|v-\theta_{h}\|_{0,\,\Omega}\leqslant C_{1}h^{k}|v|_{k,\,\Omega}\ \ \ \ \ \forall v\in H^{k}(\Omega).\]

Thus it remains to evaluate \(\|v-\theta_{h}\|_{0,\,\Gamma_{h}}.\)

Like in Lemma 2.9, we have

\[\|v-\theta_{h}\|_{0,\,\kappa^{\prime}}^{2}\leqslant C_{1}h_{\kappa}\|\,\phi- \hat{\theta}_{h}\|_{1,\,\kappa}^{2}.\]

Then if \(\theta_{h}=I_{h}v,\) this gives

\[\|v-I_{h}v\|_{0,\,\kappa^{\prime}}^{2}\leqslant C_{2}h_{\kappa}|\,\phi|_{k, \,\kappa}^{2};\]

hence we infer from (A.7), (A.2) and (A.4) that:

\[\|v-I_{h}v\|_{0,\,\kappa^{\prime}}^{2}\leqslant C_{3}\sigma^{2}h^{2k-1}|v|_{k ,\,\kappa}^{2}.\]

This proves (2.59).

When \(\theta_{h}=R_{h}v,\) we use the inequality arising in the proof of Lemma 2.9:

\[\|v-\theta_{h}\|_{0,\,\kappa^{\prime}}^{2}\leqslant C_{4}\sigma_{\kappa}[(1/ \rho_{\kappa})\|v-\theta_{h}\|_{0,\,\kappa}^{2}+\sigma_{\kappa}h_{\kappa}|v- \theta_{h}|_{1,\,\kappa}^{2}].\]

Then, applying the local error estimate (A.55) of \(R_{h}\):
