_Find a pair \((\mathbf{u},p)\!\in\!H^{1}_{0}(\Omega)^{N}\times L^{2}_{0}(\Omega)\) such that_

(37) \[\begin{cases}a(\mathbf{u},\mathbf{v})-(p,\operatorname{div}\mathbf{v})=\langle \mathbf{f},\mathbf{v}\rangle\qquad\forall\mathbf{v}\!\in\!H^{1}_{0}(\Omega)^{N} ,\\ (q,\operatorname{div}\mathbf{u})=0\qquad\forall q\!\in\!L^{2}_{0}(\Omega).\end{cases}\]

With the following substitutions:

\[X=H^{1}_{0}(\Omega)^{N},\quad\ M=L^{2}_{0}(\Omega),\quad\ \|\,.\,\|_{X}=|\,.\,|_{1, \Omega},\quad\ \|\,.\,\|_{M}=\|\,.\,\|_{0,\Omega},\]

\[b(\mathbf{v},q)=\,-(q,\operatorname{div}\mathbf{v}),\]

\[\chi=0,\quad\ \mathbf{l}=\mathbf{f},\]

this is exactly the problem studied in Section I.5.1.

Now, for each \(h\) let \(W_{h}\) and \(Q_{h}\) be two finite-dimensional spaces such that

\[W_{h}\subset H^{1}(\Omega)^{N},\quad\ Q_{h}\subset L^{2}(\Omega)\]

and throughout this section we assume that \(Q_{h}\)_contains the constant functions._ We set:

(38) \[\begin{cases}X_{h}=\,W_{h}\cap H^{1}_{0}(\Omega)^{N}=\{\mathbf{v}_{h}\!\in\!W_ {h};\,\mathbf{v}_{h|_{r}}=\,\mathbf{0}\,\},\\ M_{h}=Q_{h}\cap L^{2}_{0}(\Omega)=\left\{q_{h}\!\in\!Q_{h};\,\int_{\Omega}q_{h} \,dx=0\right\}.\end{cases}\]

With these spaces, Problem (37) is approximated by:

_Find a pair \((\mathbf{u}_{h},p_{h})\!\in\!X_{h}\times M_{h}\) such that_:

(39) \[\begin{cases}a(\mathbf{u}_{h},\mathbf{v}_{h})-(p_{h},\operatorname{div} \mathbf{v}_{h})=\langle\mathbf{f},\mathbf{v}_{h}\rangle\qquad\forall\mathbf{ v}_{h}\!\in\!X_{h},\\ (q_{h},\operatorname{div}\mathbf{u}_{h})=0\qquad\forall q_{h}\!\in\!M_{h}. \end{cases}\]

As \(\operatorname{div}\mathbf{u}_{h}\!\in\!L^{2}_{0}(\Omega)\), observe that the second equation in (39) is equivalent to

\[(q_{h},\operatorname{div}\mathbf{u}_{h})=0\qquad\forall q_{h}\!\in\!Q_{h}.\]

In view of this remark, the corresponding space \(V_{h}\) is given by:

\[V_{h}=\{\mathbf{v}_{h}\!\in\!X_{h};\,(q_{h},\operatorname{div}\mathbf{v}_{h}) =0\quad\forall q_{h}\!\in\!Q_{h}\}.\]

Hence the _Problem_ (P\({}_{h}\)) associated with (39) is:

_Find \(\mathbf{u}_{h}\!\in\!V_{h}\) satisfying_

(40) \[a(\mathbf{u}_{h},\mathbf{v}_{h})=\langle\mathbf{f},\mathbf{v}_{h}\rangle \qquad\forall\mathbf{v}_{h}\!\in\!V_{h}.\]

_Remark 1.7_.: As mentioned in the preceding section, \(V_{h}\) is generally not included in \(V\!\cdot\{\mathbf{v}\!\in\!H^{1}_{0}(\Omega)^{N};\operatorname{div}\mathbf{v} =0\}\); this will be the case in all the examples of this chapter. Thus the functions of \(V_{h}\) are not divergence-free but satisfy only

\[\rho_{h}(\operatorname{div}\mathbf{v}_{h})=0,\]

where \(\rho_{h}\) is the orthogonal projection of \(L^{2}(\Omega)\) onto \(Q_{h}\). As a consequence, the
