\[|\phi_{h}|_{1,\Omega}^{2}\leq\|\,\theta_{h}\|_{0,\Omega}\|\,\phi_{h}\|_{0,\Omega} \leq C\,\|\,\theta_{h}\|_{0,\Omega}|\,\phi_{h}|_{1,\Omega},\]

thus proving (2.26). 

When \(s=2\), it follows from this lemma that there exists \(\alpha^{*}>0\):

(2.27) \[v\,\|\,\theta_{h}\|_{0,\Omega}^{2}\geq\alpha^{*}\,\|\,v_{h}\|_{\bar{X}}^{2} \hskip 14.226378pt\forall v_{h}=(\mbox{\bf curl}\,\phi_{h},\theta_{h})\,\in V _{h},\]

provided \(\Phi_{h}\subset M_{h}\). In other words, the _seminorm \(|\,.|\) defined by (2.15) and \(\|\,.\,\|_{\bar{X}}\) are two uniformly equivalent norms on \(V_{h}\)_. When \(s>2\), we take it as an assumption which will be verified in the forthcoming examples.

**Hypothesis H1**. _For \(s>2\), \(|\,.|\) and \(\|\,.\,\|_{\bar{X}}\) are two uniformly equivalent norms_ (_with respect to \(h\)_) _on \(V_{h}\)._

**Lemma 2.4**.: \(1^{\circ}\) _Suppose that_

(2.28) \[\Phi_{h}\subset M_{h}\subset\Theta_{h}\]

_and when \(s>2\) assume that Hypothesis H1 holds. Then Problem (2.24) has exactly one solution \(u_{h}=(\mbox{\bf curl}\,\psi_{h},\omega_{h})\,\in X_{h}\) and \(\lambda_{h}\,\in M_{h}\)._

\(2^{\circ}\)_) If in addition \(M_{h}=\Theta_{h}\) then \(\lambda_{h}=v\omega_{h}\)._

Proof.: \(1^{\circ}\)) Part 1 follows directly from Lemmas 2.2 and 2.3, Hypothesis H1 and Theorem 1.2.

\(2^{\circ}\)) Let \(M_{h}=\Theta_{h}\) and let us show that \((u_{h},v\omega_{h})\) satisfies (2.24), i.e. that

\[v(\mbox{\bf curl}\,\omega_{h},\mbox{\bf curl}\,\phi_{h})=(\mbox{\bf f},\mbox{ \bf curl}\,\phi_{h})\hskip 14.226378pt\forall\phi_{h}\,\in\Phi_{h}.\]

If \((\mbox{\bf curl}\,\phi_{h},\theta_{h})\) belongs to \(V_{h}\), (2.24) becomes:

\[v(\omega_{h},\theta_{h})=(\mbox{\bf f},\mbox{\bf curl}\,\phi_{h}).\]

But since \(M_{h}\equiv\Theta_{h}\) the functions \(\phi_{h}\) and \(\theta_{h}\) satisfy in particular:

\[(\mbox{\bf curl}\,\phi_{h},\mbox{\bf curl}\,\omega_{h})=(\theta_{h},\omega_{ h}).\]

Hence

\[v(\mbox{\bf curl}\,\phi_{h},\mbox{\bf curl}\,\omega_{h})=(\mbox{\bf f},\mbox{ \bf curl}\,\phi_{h})\hskip 14.226378pt\forall(\mbox{\bf curl}\,\phi_{h}, \theta_{h})\,\in V_{h}.\]

This is the desired result because when \(M_{h}=\Theta_{h}\), each function \(\phi_{h}\) in \(\Phi_{h}\) has (exactly) one function \(\theta_{h}\) in \(\Theta_{h}\) such that the pair \((\mbox{\bf curl}\,\phi_{h},\theta_{h})\) belongs to \(V_{h}\). 

Note that the above proof does not require that \(\Phi_{h}\subset M_{h}\) when \(s>2\); but this inclusion always holds in practice.

Lemma 2.4 has the following vital consequence.

**Theorem 2.5**.: _Under the assumptions of Lemma 2.4, Problem (2.24) is equivalent to:_

\[Find\,\psi_{h}\,\in\,\Phi_{h}\,\,and\,\,\omega_{h}\,\in\,\Theta_{h}\,\,such\]
