By combining Lemmas 5.7 and 5.8, we derive the result announced at the beginning of this section.

**Theorem 5.3**.: _A vector field \(\mathbf{u}\) of \(R_{l}\) is entirely determined in a tetrahedron \(\kappa\) by its three sets of moments: \(M_{e}(\mathbf{u})\), \(M_{f}(\mathbf{u})\), \(M_{\kappa}(\mathbf{u})\). Moreover the tangential components of \(\mathbf{u}\) on a given face \(f\) of \(\kappa\) depend only upon the moments \(M_{f}(\mathbf{u})\) and \(M_{e}(\mathbf{u})\) defined on that face._

This theorem induces a natural interpolation operator in \(\kappa\).

**Definition 5.2**.: Let \(\kappa\) be an arbitrary tetrahedron of \(\mathbb{R}^{3}\) and \(\mathbf{u}\in W^{1,s}(\kappa)^{3}\) for some \(s>2\). Its interpolant \(r_{\kappa}\mathbf{u}\) is the unique polynomial of \(R_{l}\) that has the same moments as \(\mathbf{u}\) on \(\kappa\).

In other words, \(r_{\kappa}\mathbf{u}\) is determined by:

\[M_{\kappa}(r_{\kappa}\mathbf{u}-\mathbf{u})=\{0\},\ \ \ \ \ M_{f}(r_{\kappa} \mathbf{u}-\mathbf{u})=\{0\},\ \ \ \ \ M_{e}(r_{\kappa}\mathbf{u}-\mathbf{u})=\{0\}.\]

Clearly, it follows from the invariance Lemmas 5.5 and 5.6 that

(5.35) \[\widehat{r_{\kappa}\mathbf{u}} =r_{\kappa}\mathbf{u},\] \[B_{\kappa}^{T}[(r_{\kappa}\mathbf{u})\circ F_{\kappa}] =r_{\kappa}[B_{\kappa}^{T}(\mathbf{u}\circ F_{\kappa})].\]

_Remark 5.6_.: When \(\mathbf{u}\in W^{1,s}(\kappa)^{3}\) satisfies \(\mathbf{curl}\,\mathbf{u}=\mathbf{0}\), the argument of Lemma 5.8 shows that \(\mathbf{curl}(r_{\kappa}\mathbf{u})=\mathbf{0}\) in \(\kappa\).

Likewise, when \(\mathbf{u}\in P_{l}^{3}\), Remark 5.5 establishes that

\[\mathbf{curl}(\mathbf{u}-r_{\kappa}\mathbf{u})=\mathbf{0}\ \ \ \text{in $\kappa$}.\]

Now we are in a position to define the finite element spaces \(M_{h}\) and \(\Phi_{h}\). As a matter of convenience, we assume that \(\Omega\) is a _bounded polychuron_. Let \(\mathcal{T}_{h}\) be a triangulation of \(\bar{\Omega}\) consisting of polyhedra \(\kappa\) with diameters bounded by \(h\). For each integer \(l\geq 1\), we set:

(5.36a) \[M_{h}=\{\mathbf{\mu}_{h}\in H(\mathbf{curl};\Omega);\,\mathbf{ \mu}_{h}|_{\kappa}\in R_{l}\ \ \ \forall\kappa\in\mathcal{T}_{h}\},\] (5.36b) \[\Phi_{h}=M_{h}\cap H_{0}(\mathbf{curl};\Omega)\]

and we define the interpolation operator \(r_{h}\) on \(M_{h}\) by:

(5.37) \[r_{h}\mathbf{u}|_{\kappa}=r_{\kappa}\mathbf{u}\ \ \ \ \text{on $\kappa$}\ \ \ \ \forall\kappa\in\mathcal{T}_{h}\]

for all \(\mathbf{u}\in W^{1,s}(\Omega)^{3}\) for some \(s>2\). The next lemma asserts that \(M_{h}\) (resp. \(\Phi_{h}\)) is a conforming approximation of \(H(\mathbf{curl};\Omega)\) (resp. \(H_{0}(\mathbf{curl};\Omega)\)).

**Lemma 5.9**.: _If \(\mathbf{u}\in W^{1,s}(\Omega)^{3},\) then \(r_{h}\mathbf{u}\in M_{h}\). Similarly, when \(\mathbf{u}\in W^{1,s}(\Omega)^{3}\) with \(\mathbf{u}\times\mathbf{n}|_{\Gamma}=\mathbf{0}\) then \(r_{h}\mathbf{u}\in\Phi_{h}\)._

We skip the proof as it is a straightforward consequence of Lemma 5.7.
