* 85Numerical Analysis of Upwind Schemes * 85.1Upwinding in the Stream Function-Vorticity Scheme * 85.2Error Analysis of the Upwind Scheme * 85.3Approximating the Pressure with the Upwind Scheme
* 86Numerical Algorithms * 86.1General Methods of Descent and Application to Gradient Methods * 86.2Least-Squares and Gradient Methods to Solve the Navier-Stokes Equations * 86.3Newton's Method and the Continuation Method
* 87
