sion \(l(l+2)\), with \(l\geqslant 1\):

\[\hat{D}=P_{l-1}^{2}\oplus\{p(\hat{x})\hat{x};\,p\in\tilde{P}_{l-1}\},\]

where \(\tilde{P}_{k}\) denotes the space of homogeneous polynomials of degree \(k\). If \(\hat{\kappa}\) is the unit square, we simply take the space of dimension \(2l(l+1)\):

\[\hat{D}=Q_{l,\,l-1}\,\times\,Q_{l-1,\,l},\]

where exceptionally \(Q_{r,\,s}\) denotes the space of all polynomials of degree at most \(r\) in \(x_{1}\) and \(s\) in \(x_{2}\). Then, it is easy to check that:

\[\operatorname{div}(\hat{D})=P_{l-1},\quad\text{ Ker}(\operatorname{div})=\text{\bf curl}(P_{l})\quad\text{if $\hat{\kappa}$ is the unit triangle,}\]

\[\operatorname{div}(\hat{D})=Q_{l-1},\quad\text{ Ker}(\operatorname{div})=\text{\bf curl}(Q_{l})\quad\text{if $\hat{\kappa}$ is the unit square.}\]

In addition, owing to the geometry of \(\hat{\kappa}\), \(\hat{\kappa}\cdot\hat{\mathbf{n}}\) reduces to a polynomial of \(P_{l-1}\) on \(\partial\hat{\kappa}\) for \(\hat{\kappa}\) in \(\hat{D}\).

As a consequence, we can choose the following degrees of freedom for the vectors \(\hat{\kappa}\) of \(\hat{D}\):

(i) the boundary moments of order \(l-1\) for \(\hat{\kappa}\cdot\hat{\mathbf{n}}\):

\[\int_{\hat{\kappa}^{\prime}}\hat{\mathbf{v}}\cdot\hat{\mathbf{n}}f\,d\hat{s} \quad\quad\forall\in P_{l-1}\quad\text{on each side $\hat{\kappa}^{\prime}$ of $\hat{\kappa}$;}\]

(4.62) (ii) the interior moments of order \(l-2\) for \(\hat{\kappa}\):

\[\int_{\hat{\kappa}}\hat{\kappa}\cdot\hat{\mathbf{f}}\,d\hat{x}\quad\quad \forall\hat{\mathbf{f}}\in\begin{cases}P_{l-2}^{2}&\text{if $\hat{\kappa}$ is a triangle,}\\ Q_{l-2,\,l-1}\,\times\,Q_{l-1,\,l-2}&\text{if $\hat{\kappa}$ is a square.}\end{cases}\]

It is a matter of routine to check that (4.62) defines a unique vector \(\hat{\kappa}\) of \(\hat{D}\) and that the restriction of \(\hat{\kappa}\cdot\hat{\mathbf{n}}\) on each side \(\hat{\kappa}^{\prime}\) depends only upon the \(l\) values prescribed on this side.

To switch from \(\hat{\kappa}\) to an arbitrary element \(\kappa\), we introduce the following contravariant transformation between the vector function \(\mathbf{v}=(v_{1},v_{2})\) defined on \(\kappa\) and \(\hat{\kappa}=(\hat{v}_{1},\hat{v}_{2})\) defined on \(\hat{\kappa}\):

\[\mathbf{v}=\mathcal{F}_{\kappa}\hat{\mathbf{v}}\quad\text{where}\quad\mathbf{ v}\circ F_{\kappa}=(1/J_{F})DF_{\kappa}\cdot\hat{\mathbf{v}}.\]

The choice of \(\mathcal{F}_{\kappa}\) is justified by the fact that, roughly speaking, it preserves the divergence, **curl** and normal component:

\[(\operatorname{div}\mathbf{v})\circ F_{\kappa} =(1/J_{F})\operatorname{div}(\mathcal{F}_{\kappa}^{-1}\mathbf{v}),\] \[\mathcal{F}_{\kappa}^{-1}(\text{\bf curl}\,\psi) =\text{\bf curl}(\psi\circ F_{\kappa}),\] \[\int_{\partial\kappa}\phi\mathbf{v}\cdot\mathbf{n}\,ds =\int_{\partial\hat{\kappa}}(\phi\circ F_{\kappa})(\mathcal{F}_{ \kappa}^{-1}\mathbf{v})\cdot\hat{\mathbf{n}}\,d\hat{s}.\]

Then we _fix \(l\) distinct points_ on each segment \(\kappa^{\prime}\) of \(\Gamma_{h}\) and we set:

\[D_{0h}=\{\mathbf{v}_{h}\!\in\!L^{2}(\Omega)^{2};\,\mathbf{v}_{h}|_{\kappa}= \mathcal{F}_{\kappa}\hat{\mathbf{v}},\hat{\mathbf{v}}\!\in\!\hat{D}\quad\forall \kappa\!\in\!\mathcal{T}_{h}\quad\mathbf{v}_{h}\!\cdot\!\mathbf{n}\text{ is continuous}\] (4.64) (resp. \[0\] ) at the \(l\) points of each interior (resp. boundary) segment \(\kappa^{\prime}\) of \(\Gamma_{h}\)
