From (1.10), this problem has a unique solution \(z_{h}\) and therefore

\[u_{h}=z_{h}+u_{h}^{0}\]

is the only solution of Problem (P\({}_{h}\)).

Now let \(w_{h}\) be an arbitrary element of \(V_{h}(\chi)\); then \(v_{h}=u_{h}-w_{h}\in V_{h}\) and

\[a(v_{h},v_{h})=\langle l,v_{h}\rangle-a(w_{h},v_{h}).\] (1.14)

Since \(v_{h}\in X_{h}\), we can take \(v=v_{h}\) in (1.1) and substitute in (1.14). This yields:

\[a(v_{h},v_{h})=a(u-w_{h},v_{h})+b(v_{h},\lambda).\]

Moreover, since \(v_{h}\in V_{h}\), we have \(b(v_{h},\mu_{h})=0\)\(\forall\mu_{h}\in M_{h}\). Hence

\[a(v_{h},v_{h})=a(u-w_{h},v_{h})+b(v_{h},\lambda-\mu_{h})\quad\quad\forall\mu_{ h}\in M_{h}.\] (1.15)

The \(V_{h}\)-ellipticity of \(a\) and the continuity of \(a\) and \(b\) yield:

\[\|v_{h}\|_{X}\leqslant(\|a\|\,\|u-w_{h}\|_{X}+\|b\|\,\|\lambda-\mu_{h}\|_{M})/ \alpha^{\star}.\]

Therefore

\[\|u-u_{h}\|_{X}\leqslant \left(1+\frac{\|a\|}{\alpha^{\star}}\right)\|u-w_{h}\|_{X}+\frac{ \|b\|}{\alpha^{\star}}\|\,\lambda-\mu_{h}\|_{M}\] \[\forall w_{h}\in V_{h}(\chi)\quad\quad\forall\mu_{h}\in M_{h}.\]

This yields (1.11) with \(C_{1}=\max\left(1+\frac{\|a\|}{\alpha^{\star}},\frac{\|b\|}{\alpha^{\star}}\right)\).

\(2^{\circ})\) Let us apply Lemma I.4.1 to the particular case of \(X_{h}\) and \(M_{h}\). Hypothesis (iii) implies that \(B_{h}\) is an isomorphism from \(V_{h}^{\perp}\) (taken in \(X_{h}\)) onto \(M_{h}^{\prime}\). Therefore \(V_{h}(\chi)\) is not empty and according to \(\mathrm{n}^{\circ}\) 1 Problem (P\({}_{h}\)) has a unique solution \(u_{h}\). Furthermore, it follows from Corollary I.4.1 that there exists a unique \(\lambda_{h}\) in \(M_{h}\) such that the pair \((u_{h},\lambda_{h})\) is the only solution of Problem (Q\({}_{h}\)).

To derive the error bound (1.13) we shall first prove that

\[\inf_{w_{h}\in V_{h}(\chi)}\|u-w_{h}\|_{X}\leqslant \left(1+\frac{\|b\|}{\beta^{\star}}\right)\inf_{v_{h}\in X_{h}}\|u-v _{h}\|_{X}.\] (1.16)

Let \(v_{h}\) be an arbitrary element of \(X_{h}\); like above, there exists a unique \(z_{h}\) in \(V_{h}^{\perp}\) such that

\[B_{h}z_{h}=B_{h}(u-v_{h})\]

and

\[\|z_{h}\|_{X}\leqslant\frac{1}{\beta^{\star}}\,\|\,B_{h}(u-v_{h})\|_{M_{h}} \leqslant\frac{1}{\beta^{\star}}\,\|\,b\,\|\,\|u-v_{h}\|_{X}.\]

Thus, if we set \(w_{h}=z_{h}+v_{h}\), then

\[b(w_{h},\mu_{h})=b(u-v_{h},\mu_{h})+b(v_{h},\mu_{h})=\langle\chi,\mu_{h} \rangle\quad\quad\forall\mu_{h}\in M_{h}\]
