\(q\in H^{1}(\Omega_{r})\cap L^{2}_{0}(\Omega_{r})\) by \(\overline{q}\) where

\[\hat{\overline{q}}=\hat{q}\dashv(1/\mathrm{meas}(\hat{\Omega}))\int_{\Omega} \hat{q}\,d\hat{x}.\]

Then \(q\) and \(\overline{q}\) differ by a constant and we have:

\[\|\,q\|_{0,\,\Omega_{r}}=\inf_{c\,\in\,\mathbb{R}}\|\,q\,+\,c\,\|_{0,\,\Omega_{ r}}\leqslant\|\,\overline{q}\,\|_{0,\,\Omega_{r}}.\]

But

\[\|\,\bar{q}\,\|_{0,\,\Omega_{r}}^{2} =\sum_{i=1}^{J}\mathrm{meas}(\kappa_{i})\|\,\hat{\overline{q}}\, \|_{0,\,\hat{x}_{i}}^{2}\] \[\leqslant\hat{\mathcal{C}}_{7}\sup_{1\,\leqslant\,i\,\leqslant\, J}(h_{\kappa_{i}}^{2})|\,\hat{\overline{q}}\,|_{1,\,\hat{\Omega}}^{2}\quad \mathrm{since}\,\,\,\widehat{q}\in H^{1}(\hat{\Omega})\cap L^{2}_{0}(\hat{ \Omega}).\] \[\leqslant\hat{\mathcal{C}}_{8}\left\{\sup_{1\,\leqslant\,i\, \leqslant\,J}(h_{\kappa_{i}}^{2})\bigg{/}\inf_{1\,\leqslant\,i\,\leqslant\,J }(\rho_{\kappa_{i}}^{2})\right\}\sum_{i=1}^{J}\mathrm{meas}(\kappa_{i})|\, \hat{q}|_{1,\,\kappa_{i}}^{2}.\]

Hence

(4.25) \[\left\{\sum_{i=1}^{J}\mathrm{meas}(\kappa_{i})|\,\hat{q}|_{1,\,\hat{\kappa}_{ i}}^{2}\right\}^{1/2}\geqslant(\hat{\mathcal{C}}_{9}/\sigma_{r})\,\|\,q\,\|_{0,\, \Omega_{r}},\]

where

\[\sigma_{r}=\sup_{1\,\leqslant\,i\,\leqslant\,J}(h_{\kappa_{i}})\bigg{/}\inf_{ 1\,\leqslant\,i\,\leqslant\,J}(\rho_{\kappa_{i}}).\]

This finishes the proof because the regularity of \(\mathcal{T}_{h}\) implies that (cf. Bernardi [9]):

(4.26) \[\sigma_{r}\leqslant\hat{\mathcal{C}}\sigma.\qed\]

Owing to Theorem 1.12, the local inf-sup condition (4.19) yields readily the required global condition.

**Corollary 4.1**.: _Under the assumptions of Theorem 4.2 the pair of spaces \((X_{h},M_{h})\) defined by (4.15) (4.4) satisfies the inf-sup condition (4.9) with a constant \(\beta^{*}>0\) independent of \(h\)._

Proof.: Let \(X_{h}\) be the finite element space defined by (2.3) and let

\[\overline{M}_{h}=\{q\in L^{2}_{0}(\Omega);\,q|_{\Omega_{r}}\,\,\mathrm{is\,\, constant}\,\,\forall r\}.\]

Then on the one hand, \(\bar{X}_{h}\subset X_{h}\) because the functions of \(\bar{X}_{h}\) are piecewise incomplete polynomials of \(P^{2}_{2}\). On the other hand, it follows from Lemma 2.2 that the pair \((\bar{X}_{h},\bar{M}_{h})\) satisfies a uniform inf-sup condition since the functions of \(\bar{M}_{h}\) are a particular case of piecewise constants. Hence the result follows from Theorems 1.12 and 4.2.
