### Super Convergence Using Quadrilateral Finite Elements of Degree \(l\)

In this section, we propose to study again the expression

\[\inf_{\phi_{h}\in\mathcal{O}_{h}}\sup_{\mu_{h}\in\mathcal{O}_{h}}\frac{|(\mbox{ \bf curl}(\phi-\phi_{h}),\mbox{\bf curl}\,\mu_{h})|}{\|\mu_{h}\|_{0,0}}\]

and show that it is of the order of \(h^{l}\), for \(\phi\) in \(H^{l+2}(\Omega)\), provided that the triangulation \(\mathcal{T}_{h}\) has a favorable configuration. Essentially, this will be achieved by choosing the function \(\phi_{h}\) as a suitable interpolate of \(\phi\).

To begin with, we assume that \(\mathcal{T}_{h}\) is composed exclusively of convex quadrilaterals and we refer to Section A.2 for the notations and approximation results pertaining to quadrilaterals. Let us \(fix\) an integer \(l\geqslant 1\) and let

\[0=\alpha_{0}<\alpha_{1}<\cdots<\alpha_{l-1}<\alpha_{l}=1\]

be \(l+1\) distinct points of the interval \([0,1]\). Here, we denote by \(\hat{I}\in\mathcal{L}(\mathcal{C}^{0}(\kappa);Q_{l})\) the standard interpolation operator at the \((l+1)^{2}\) points

\[\{(\alpha_{i},\alpha_{j});\,0\leqslant i,j\leqslant l\}\]

of the reference unit square \(\hat{\kappa}\). The following technical result gives a first approximation of the difference \(\hat{\phi}-\hat{I}\hat{\phi}\).

**Lemma 3.5**.: _Let \(R\in\mathcal{L}(H^{l+1}(\kappa);P_{l+1})\) be defined by:_

\[R(\hat{\phi})=\left[1/(l+1)!\right]\sum_{i=1}^{2}\left(\int_{\hat{\kappa}} \left(\partial^{l+1}\hat{\phi}/\partial\hat{x}_{i}^{l+1}\right)d\hat{\kappa} \right)\prod_{k=0}^{l}\left(\hat{x}_{i}-\alpha_{k}\right)\!.\]

_Then, for each integer \(m\) with \(0\leqslant m\leqslant l+2\), there exists a positive constant \(\hat{C}\) depending only upon \(\hat{\kappa}\), \(\hat{I}\), \(R\), \(m\) and \(l\), such that_

(3.20) \[\|\hat{\phi}-\hat{I}\hat{\phi}-R(\hat{\phi})\|_{m,\hat{\kappa}}\leqslant\hat{C }|\hat{\phi}|_{l+2,\hat{\kappa}}\ \ \ \ \forall\hat{\phi}\!\in\!H^{l+2}(\hat{\kappa}).\]

_Proof_. Suppose first that \(\hat{\phi}\!\in\!\mathcal{C}^{l+1}(\hat{\kappa})\). Recall that the interpolation operator \(\hat{I}\) has the expression

\[\hat{I}\hat{\phi}(\hat{x}_{1},\hat{x}_{2})=\sum_{k=0}^{l}L_{k}(\hat{x}_{1}) \sum_{j=0}^{l}L_{j}(\hat{x}_{2})\hat{\phi}(\alpha_{k},\alpha_{j})\]

where \(L_{k}\!\in\!P_{l}\) is the polynomial of one variable such that:

\[L_{i}(\alpha_{j})=\delta_{ij},\ \ \ \ 0\leqslant i,j\leqslant l.\]

The well-known remainder formula for the interpolation error gives on the one hand:

\[\hat{\phi}(\alpha_{k},\hat{x}_{2})=\sum_{j=0}^{l}L_{j}(\hat{x}_{2})\hat{\phi} (\alpha_{k},\alpha_{j})+\left[1/(l+1)!\right]\left[\partial^{l+1}\hat{\phi}( \alpha_{k},\mu_{k})/\partial\hat{x}_{2}^{l+1}\right]\prod_{p=0}^{l}\left(\hat{ x}_{2}-\alpha_{p}\right)\!,\]

and on the other hand,

\[\hat{\phi}(\hat{x}_{1},\hat{x}_{2})=\sum_{k=0}^{l}L_{k}(\hat{x}_{1})\hat{\phi} (\alpha_{k},\hat{x}_{2})+\left[1/(l+1)!\right]\left[\partial^{l+1}\hat{\phi}( v,\hat{x}_{2})/\partial\hat{x}_{1}^{l+1}\right]\prod_{p=0}^{l}\left(\hat{x}_{1}- \alpha_{p}\right)\]
