\[\Phi_{h}(v)-\,\tilde{u}_{h} = [D_{u}F_{h}(\lambda;\tilde{u}_{h})]^{-1}[D_{u}F_{h}(\lambda;\tilde{u} _{h})\cdot(v-\tilde{u}_{h})-(F_{h}(\lambda,v)-F_{h}(\lambda,\tilde{u}_{h}))\] \[-F_{h}(\lambda,\tilde{u}_{h})].\]

But

\[F_{h}(\lambda,v)-F_{h}(\lambda,\tilde{u}_{h})=\int_{0}^{1}D_{u}F_{h}(\lambda, \tilde{u}_{h}+\,\theta(v-\tilde{u}_{h}))\cdot(v-\tilde{u}_{h})\,d\theta.\]

Thus

\[\|D_{u}F_{h}(\lambda,\tilde{u}_{h})\cdot(v-\tilde{u}_{h})-(F_{h}( \lambda,v)-F_{h}(\lambda,\tilde{u}_{h}))\|\] \[=\bigg{\|}\int_{0}^{1}\{D_{u}F_{h}(\lambda,\tilde{u}_{h})-D_{u}F_{ h}(\lambda,\tilde{u}_{h}+\,\theta(v-\tilde{u}_{h}))\}\cdot(v-\tilde{u}_{h})\,d\theta\, \bigg{\|}\] \[\leq L_{h}(\lambda;2\gamma_{h}(\lambda)\varepsilon_{h}(\lambda) )2\gamma_{h}(\lambda)\varepsilon_{h}(\lambda)\]

because \(v\in S\) (cf. (3.17)). Hence:

\[\|\,\Phi_{h}(v)-\tilde{u}_{h}\|_{\,X}\leq\gamma_{h}(\lambda)\varepsilon_{h}( \lambda)\{L_{h}(\lambda;2\gamma_{h}(\lambda)\varepsilon_{h}(\lambda))2\gamma_{ h}(\lambda)+\,1\}<2\gamma_{h}(\lambda)\varepsilon_{h}(\lambda),\]

by virtue of (3.19). Therefore \(\Phi_{h}(v)\) belongs to \(S\).

\(2^{\circ})\) Let \(v\) and \(w\) belong to \(S\). Like above, we can write:

\[\Phi_{h}(v)-\Phi_{h}(w) = [D_{u}F_{h}(\lambda,\tilde{u}_{h})]^{-1}[D_{u}F_{h}(\lambda, \tilde{u}_{h})\cdot(v-w)-(F_{h}(\lambda,v)-F_{h}(\lambda,w))]\] \[= [D_{u}F_{h}(\lambda,\tilde{u}_{h})]^{-1}\int_{0}^{1}\{D_{u}F_{h}( \lambda,\tilde{u}_{h})\] \[-D_{u}F_{h}(\lambda,w+\theta(v-w))\}\cdot(v-w)\,d\theta.\]

Again (3.17) and (3.19) yield:

\[\|\,\Phi_{h}(v)-\Phi_{h}(w)\|_{\,X}\leq\gamma_{h}(\lambda)L_{h}(\lambda;2 \gamma_{h}(\lambda)\varepsilon_{h}(\lambda))\,\|\,v-w\|_{\,X}<(1/2)\,\|\,v-w\| _{\,X}.\]

Hence the mapping \(\Phi_{h}\) is a strict contraction of \(S\) into itself. As a consequence, \(\Phi_{h}\) has a unique fixed point in \(S\).

Let \(u_{h}=u_{h}(\lambda)\) denote the fixed point of \(\Phi_{h}\) in \(S\). It follows from the above considerations that the pair \((\lambda,u_{h})\) is the (unique) solution of (3.12) in \(S\). In addition, observe that

\[\|D_{u}F_{h}(\lambda,u_{h})-D_{u}F_{h}(\lambda,\tilde{u}_{h})\|_ {\,\mathcal{L}(X;\,\mathcal{X})} \leq L_{h}(\lambda;2\gamma_{h}(\lambda)\varepsilon_{h}(\lambda))\] \[< 1/(2\gamma_{h}(\lambda))\quad\text{owing to (\ref{eq:2.1}).}\]

Thus the assumption (3.18) and Lemma 3.3 imply that \(D_{u}F_{h}(\lambda,u_{h})\) is also an isomorphism of \(X\) onto \(\mathcal{X}\) and (3.21) follows from (3.16).

Next, let us prove that \(\Phi_{h}\) has no other fixed point than \(u_{h}\) in the larger ball \(S(\tilde{u}_{h};\alpha)\) with \(\alpha\) prescribed by (3.22). Indeed, let \(v\) be another fixed point of \(\Phi_{h}\) in \(S(\tilde{u}_{h};\alpha)\). The argument of part \(2^{\circ})\) gives:

\[\|v-u_{h}\|_{\,X}=\|\,\Phi_{h}(v)-\Phi_{h}(u_{h})\|_{\,X}\leq\gamma_{h}(\lambda)L _{h}(\lambda;\alpha)\,\|\,v-u_{h}\|_{\,X}.\]

Thus \(v=u_{h}\) when \(\alpha\) satisfies (3.22).
