\[\begin{cases}a(\mathbf{w},\mathbf{v})+b(\mathbf{v},p)=\langle\mathbf{l},\mathbf{v} \rangle\qquad\forall\mathbf{v}\in H^{1}_{0}(\Omega)^{N},\\ b(\mathbf{w},q)=0\qquad\forall q\in L^{2}_{0}(\Omega).\end{cases}\]

Equivalently \((\mathbf{u}=\mathbf{u}_{0}+\mathbf{w},p)\in[\mathbf{u}_{0}+H^{1}_{0}(\Omega)^ {N}]\times L^{2}_{0}(\Omega)\) is the solution of the equations

\[\begin{cases}v(\mathbf{grad}\,\mathbf{u},\mathbf{grad}\,\mathbf{v})-(p,\operatorname {div}\mathbf{v})=\langle\mathbf{f},\mathbf{v}\rangle\qquad\forall\mathbf{v} \in H^{1}_{0}(\Omega)^{N},\\ (q,\operatorname{div}\mathbf{u})=0\qquad\forall q\in L^{2}_{0}(\Omega).\end{cases}\]

Applying again Corollary 2.4, this last equation is equivalent to \(\operatorname{div}\mathbf{u}=0\). Moreover, \(\mathbf{u}\in\mathbf{u}_{0}+H^{1}_{0}(\Omega)^{N}\) if and only if

\[\mathbf{u}\in H^{1}(\Omega)^{N},\quad\mathbf{u}|_{\Gamma}=\mathbf{g}.\]

Hence, there exists a unique pair \((\mathbf{u},p)\in H^{1}(\Omega)^{N}\times L^{2}_{0}(\Omega)\) such that

\[\begin{cases}v(\mathbf{grad}\,\mathbf{u},\mathbf{grad}\,\mathbf{v})-(p, \operatorname{div}\mathbf{v})=\langle\mathbf{f},\mathbf{v}\rangle\qquad \forall\mathbf{v}\in H^{1}_{0}(\Omega)^{N},\\ \operatorname{div}\mathbf{u}=0,\\ \mathbf{u}|_{\Gamma}=\mathbf{g}.\end{cases}\]

Now, using classical arguments, it is easy to show that this last problem is equivalent to Problem (5.12). 

_Remark 5.1_.: The choice \(M=L^{2}_{0}(\Omega)\) in (5.13) is only a matter of convenience and we can just as well take \(M=L^{2}(\Omega)/\mathbb{R}\). On the other hand, we can also choose in the above proof

\[a(\mathbf{u},\mathbf{v})=2v\sum_{i,\,j=1}^{N}\int_{\Omega}D_{ij}(\mathbf{u})D _{ij}(\mathbf{v})\,dx.\]

This is a consequence of the following identity:

(5.15) \[\sum_{i,\,j=1}^{N}\int_{\Omega}D_{ij}(\mathbf{u})D_{ij}(\mathbf{v})\,dx=\frac {1}{2}\sum_{i,\,j=1}^{N}\int_{\Omega}\frac{\partial u_{i}}{\partial x_{j}} \frac{\partial v_{i}}{\partial x_{j}}\,dx\]

which holds _for all \(\mathbf{u}\in H^{1}(\Omega)^{N}\) with \(\operatorname{div}\mathbf{u}=0\) and all \(\mathbf{v}\in H^{1}_{0}(\Omega)^{N}\)_. In fact, using the symmetry of the operator \(D_{ij}\) with respect to \(i\) and \(j\), we have

\[\sum_{i,\,j=1}^{N}\int_{\Omega}D_{ij}(\mathbf{u})D_{ij}(\mathbf{v})\,dx=\sum_ {i,\,j=1}^{N}\int_{\Omega}D_{ij}(\mathbf{u})\frac{\partial v_{i}}{\partial x_ {j}}\,dx.\]

Moreover, we get

\[\sum_{i,\,j=1}^{N}\int_{\Omega}\frac{\partial u_{j}}{\partial x_{i}}\,\frac{ \partial v_{i}}{\partial x_{j}}\,dx=-\sum_{i=1}^{N}\left\langle\frac{\partial \operatorname{div}\mathbf{u}}{\partial x_{i}},v_{i}\right\rangle=0,\]

from which (5.15) follows.

_Remark 5.2_.: Problem (5.12) has the following variational formulations of (Q) and (P) types respectively:
