_there exists a unique pair \((\mathbf{u},p)\in H^{1}(\Omega)^{N}\,\times\,L^{2}_{0}(\Omega)\) solution of the equations_

\[\left\{\begin{aligned} -v\Delta\mathbf{u}\,+\,\mathbf{grad}\,p& =\mathbf{f}\quad\text{in }\Omega,\\ \operatorname{div}\mathbf{u}&=0\quad\text{in }\Omega,\\ \mathbf{u}&=\mathbf{g}\quad\text{on }\Gamma.\end{aligned}\right.\] (5.12)

_Proof_. By virtue of (5.11) and Lemma 2.2, there exists a function \(\mathbf{u}_{0}\in H^{1}(\Omega)^{N}\) such that

\[\operatorname{div}\mathbf{u}_{0}=0\quad\text{in }\Omega,\quad\mathbf{u}_{0}= \mathbf{g}\quad\text{on }\Gamma.\]

Now, let us put Problem (5.12) into the framework of Paragraph 4. We set:

\[X=H^{1}_{0}(\Omega)^{N},\quad\,M=L^{2}_{0}(\Omega)\] \[\text{with norms }\|\,.\,\|_{X}=|\,.\,|_{1,\Omega},\quad\,\|\,.\, \|_{M}=\|\,.\,\|_{0,\Omega},\] (5.13) \[a(\mathbf{u},\mathbf{v})=v\sum\limits_{i,j=1}^{N}\left(\frac{ \partial u_{i}}{\partial x_{j}},\frac{\partial v_{i}}{\partial x_{j}}\right)= v(\mathbf{grad}\,\mathbf{u},\mathbf{grad}\,\mathbf{v}),\] \[b(\mathbf{v},q)=-(q,\operatorname{div}\mathbf{v}),\] \[\langle\mathbf{l},\mathbf{v}\rangle=\langle\mathbf{f},\mathbf{v} \rangle-a(\mathbf{u}_{0},\mathbf{v}),\quad\,\chi=0.\]

Then

\[V=\{\mathbf{v}\in H^{1}_{0}(\Omega)^{N};\,\operatorname{div}\mathbf{v}=0\}.\]

We must check that the form \(a(\,.\,,\,)\) is \(V\)-elliptic and the form \(b(\,.\,,\,)\) satisfies the inf-sup condition (4.9). On the one hand, the ellipticity property is obvious since

\[a(\mathbf{v},\mathbf{v})=v|\mathbf{v}|_{1,\Omega}^{2}.\]

On the other hand, the inf-sup condition says that

\[\sup_{\mathbf{v}\in H\setminus(\Omega)_{N}}\frac{(q,\operatorname{div} \mathbf{v})}{|\mathbf{v}|_{1,\Omega}}\geqslant\beta\|q\|_{0,\Omega}\quad\, \forall q\in L^{2}_{0}(\Omega).\] (5.14)

Let \(q\in L^{2}_{0}(\Omega)\); by virtue of Corollary 2.4, there exists a unique function \(\mathbf{v}\in V^{\perp}\) such that

\[\operatorname{div}\mathbf{v}=q,\quad\,|\mathbf{v}|_{1,\Omega}\leqslant C\,\| \,q\|_{0,\Omega}.\]

Hence

\[\frac{(q,\operatorname{div}\mathbf{v})}{|\mathbf{v}|_{1,\Omega}}=\frac{\|q\|_ {0,\Omega}^{2}}{|\mathbf{v}|_{1,\Omega}}\geqslant(1/C)\,\|\,q\|_{0,\Omega}\]

from which (5.14) follows with \(\beta=1/C\).

We are now in a position to apply Corollary 4.1: there exists a unique pair of functions \((\mathbf{w},p)\in H^{1}_{0}(\Omega)^{N}\,\times\,L^{2}_{0}(\Omega)\) such that
