operator \(R_{h}\) enjoys basically the same interpolation properties as \(I_{h}\) and \(\tilde{I}_{h}\), with the advantage that it works on rough functions. The major local interpolation result is:

**Theorem A.4**.: _Let \(\mathcal{T}_{h}\) be a regular triangulation of \(\Omega,\kappa\) an arbitrary triangle of \(\mathcal{T}_{h}\), \(l\) and \(m\) two positive integers with \(0\leqslant l\leqslant k+1\) and \(p\) and \(q\) two real numbers in \([1,\infty]\) such that:_

\[W^{l,\,p}(\kappa)\subsetneq W^{m,\,q}(\kappa).\]

_Let \(\Delta\) denote the union of all macro-elements \(\Delta_{i}\) containing \(\kappa\). Then for all functions \(v\in W^{l,\,p}(\Delta)\) we have the estimate:_

\[\|v-R_{h}v\|_{m,\,q,\,\kappa}\leqslant Ch_{\kappa}^{l-m+2\,(1/q-1/p)}\|v\|_{l, \,p,\,\Delta},\] (A.55)

_with a constant \(C\) independent of \(\kappa\), \(h\) and \(v\)._
