Therefore, (2.1) follows immediately from (2.6), thus proving the first conclusion.

Likewise, since \(\Omega\) is connected, \(\mathbb{R}=\operatorname{Ker}(\mathbf{grad})\) and (2.5) proves (2.7).

Finally, let \(G=L^{2}(o)\) and \(M\colon L^{2}(\Omega)\to L^{2}(\omega)\) be the identity mapping. Because \(\omega\) has positive measure, \(Mc\neq 0\) for all constants \(c\neq 0\), and (2.4) implies (2.8).



The second Corollary gives an important result of regularity.

**Corollary 2.2**.: _Let \(\Omega\) be connected and satisfy the assumptions of Theorem 2.2. If_

\[p\in L^{2}_{\operatorname{loc}}(\Omega)\quad\text{and}\quad\mathbf{grad}\;p \in H^{-1}(\Omega)^{N},\]

_then \(p\in L^{2}(\Omega)\)._

Proof.: We set

\[X=\{p\in L^{2}_{\operatorname{loc}}(\Omega);\;\mathbf{grad}\;p\in H^{-1}( \Omega)^{N}\}\]

and

\[\llbracket p\rrbracket_{\omega}=\lVert p\rVert_{0,\;\omega}+\lVert\mathbf{ grad}\;p\rVert_{-1,\;\Omega},\]

where \(\omega\subset\subset\Omega\) has positive measure. Then \(\llbracket.\rrbracket_{\omega}\) is a norm on \(X\) and we infer from (2.8) that \(\llbracket.\rrbracket_{\omega}\) and \(\lVert.\rVert_{0,\;\Omega}\) are two equivalent norms on \(L^{2}(\Omega)\). Thus \(L^{2}(\Omega)\) is a Banach space for the norm \(\llbracket.\rrbracket_{\omega}\) and hence it suffices to prove that \(L^{2}(\Omega)\) is dense in \(X\) for \(\llbracket.\rrbracket_{\omega}\).

\(1^{\circ})\) Assume for the moment that \(\Omega\) is strictly star-shaped with respect to one of its points, say \(y\). This amounts to say that, by taking \(y\) as origin,

\[\theta\bar{\Omega}\subset\Omega\quad\quad\forall\theta\in\llbracket 0,1 \rangle\quad\text{and}\quad\bar{\Omega}\subset\theta\Omega\quad\quad\forall \theta>1.\]

Here, we take \(\theta>1\) and we set \(\Omega_{\theta}=\theta\Omega\). For a continuous function \(\phi\) on \(\Omega\) we make the change of variable \(\phi\to\phi_{\theta}\) defined on \(\Omega_{\theta}\) by:

\[\phi_{\theta}(x)=\phi(x/\theta)\quad\quad\forall x\in\Omega_{\theta}\]

which we extend to distributions, \(u\in\mathcal{D}(\Omega)\to u_{\theta}\in\mathcal{D}^{\prime}(\Omega_{\theta})\) by:

\[\langle u_{\theta},\phi\rangle=\theta^{N}\langle u,\phi_{1/\theta}\rangle \quad\quad\forall\phi\in\mathcal{D}(\Omega_{\theta}).\]

Then it is easy to check that

\[\mathbf{grad}(u_{\theta})=(1/\theta)(\mathbf{grad}\;u)_{\theta} \quad\quad\forall u\in\mathcal{D}^{\prime}(\Omega),\] \[\lim_{\theta\to 1}\lVert u_{\theta}-u\rVert_{0,\;\Omega}=0 \quad\quad\forall u\in L^{2}(\Omega),\] \[\lim_{\theta\to 1}\lVert u_{\theta}-u\rVert_{-1,\;\Omega}=0 \quad\quad\forall u\in H^{-1}(\Omega).\]

Hence, if \(p\in X\) then \(p_{\theta}\in L^{2}(\Omega)\) for all \(\theta>1\) and in view of the above remarks, we readily derive that
