### Additional Results for the Hellan-Herrmann-Johnson Scheme

In this short section, we propose to extend part of the preceding results to the case where the right-hand side \(\mathbf{f}\) belongs to \(L^{r}(\Omega)^{2}\) with \(1<r<2\). Since the spaces of Problem (4.20) are finite-dimensional, and in particular \(\Phi_{h}\) is included in \(W^{1,\,\infty}(\Omega)\), it is clear that Problem (4.20) still has a unique solution when the right-hand side \(\mathbf{f}\) is only in \(L^{r}(\Omega)^{2}\), for \(1<r<2\). Thus, we must focus our attention on the equations (4.13) of the continuous problem and see how to adapt them to such a right-hand side. This is achieved much like in Section 2.1: the regularity of the tensor-valued functions \(\tau\) is decreased while that of the test stream functions \(\phi\) is increased.

If the solution \((\mathbf{u}=\mathbf{curl}\,\psi,p)\) of the Stokes Problem (2.1) is such that \(\psi\in W^{3,\tau}(\Omega)\), then \(\sigma\) belongs to \(W^{1,\tau}(\Omega)^{4}\) and therefore, according to Sobolev's Imbedding Theorem I.1.3 and the trace Theorem I.1.5 we have:

\[\sigma\in L^{2}(\Omega)^{4},\ \ \ \ \ M_{n}(\sigma)\in L^{r/(2-r)}(\Gamma_{h}).\]

Hence we replace the space of tensors \(\Sigma\) by:

\[\begin{split}\widetilde{\Sigma}&=\{\tau\in L^{2}( \Omega)^{4};\,\tau|_{\kappa}\in W^{1,\tau}(\kappa)^{4},\,\tau_{12}=\tau_{21}, \,M_{n}(\tau)\text{ is continuous}\\ &\text{ on each segment of }\Gamma_{h}\}.\end{split}\]

Likewise, since \(\mathbf{f}\) is only in \(L^{r}(\Omega)^{2}\), we replace the space \(\tilde{\mathcal{V}}\) by

\[\tilde{\mathcal{V}}\cap W^{1,s}(\Omega),\ \ \ \ 1/s+1/r=1.\]

Then, it is a matter of routine to verify that the pair \((\psi,\sigma=(\partial^{2}\psi/\partial x_{i}\partial x_{j}))\) is the unique solution of:

\[\begin{split}\begin{cases} b_{h}(\sigma,\phi)=-(1/v)\int_{ \Omega}\mathbf{f}\cdot\mathbf{curl}\,\phi\,dx&\forall\phi\in\tilde{ \mathcal{V}}\cap W^{1,s}(\Omega),\\ a_{h}(\sigma,\tau)+b_{h}(\tau,\psi)=0&\forall\tau\in\widetilde{ \Sigma}.\end{cases}\end{split}\] (4.55)

Now, a glance at Theorem 4.2 and its corollary shows that, in order to derive adequate error estimates in this case, we must verify that (4.46a), (4.48) and (4.54) are still valid here. To begin with, (4.46a) is a consequence of (4.45) together with the equations:

\[\begin{split} b_{h}(\sigma-\pi_{h}\sigma,\phi_{h})& =0&\forall\phi_{h}\in\Phi_{h},\\ b_{h}(\tau_{h},\psi-\widetilde{I}_{h}\psi)&=0& \forall\tau_{h}\in\Sigma_{h}.\end{split}\]

But for \(\psi\) in \(W^{3,\tau}(\Omega)\) and \(\sigma\) in \(W^{1,\tau}(\Omega)^{4}\), both \(\widetilde{I}_{h}\psi\) and \(\pi_{h}\sigma\) are well-defined and satisfy the above equations. And of course the equations (4.45) hold here. Therefore (4.46a) is verified. Likewise, (4.48) and (4.54) stem from (4.47) and the inf-sup conditions of Lemma 4.4 and Remark 4.2. Since the finite element spaces are unchanged, the inf-sup conditions carry over without modification; and the above considerations show that (4.47) is still valid here. The next lemma summarizes these results.
