and

(3.25) \[\int_{\Omega_{I,J}}(v_{k})_{I,\,J}(v_{l})_{I,\,J}\,dx=0\quad\text{if }k\neq l.\]

Taking into account (3.24), it is easy to see that (3.19) defines \(M_{h}\) as follows:

\[M_{h}=\biggl{\{}q=\sum_{I,\,J}\sum_{k=1}^{4}\,(\alpha_{k})_{I,\,J}(v_{k})_{I,\, J};\quad\sum_{I,\,J}(\alpha_{1})_{I,\,J}=0\biggr{\}}.\]

Furthermore since the spurious function \(\mu\) can only arise from the "local alternating" function \(v_{4}\), we have in view of (3.25):

\[[\operatorname{Ker}(B_{h}^{\prime})]^{\perp}=\biggl{\{}q=\sum_{I,\,J}\sum_{k=1 }^{4}\,(\alpha_{k})_{I,\,J}(v_{k})_{I,\,J};\quad\sum_{I,\,J}(\alpha_{1})_{I,\, J}=\sum_{I,\,J}(\alpha_{4})_{I,\,J}=0\biggr{\}}.\]

To simplify we use the notation:

(3.26) \[\mathcal{M}_{h}=[\operatorname{Ker}(B_{h}^{\prime})]^{\perp}.\]

Since we are working with finite dimensional spaces the pair \((X_{h},\mathcal{M}_{h})\) satisfies the inf-sup condition (1.12). Unfortunately this is not the end of trouble for, as we are going to see below, the condition is _not uniformly satisfied with respect to \(h\)_,

**Lemma 3.5**.: _Let \(\Omega\) be like above and let the spaces \(X_{h}\) and \(\mathcal{M}_{h}\) be defined by (3.19) and (3.26) respectively. There exists a constant \(C>0,\) independent of \(h,\) such that:_

(3.27) \[\sup_{\mathbf{v}\,\in\,X_{h}}\biggl{[}\biggl{(}\int_{\Omega}q\operatorname{ div}\mathbf{v}\,dx\biggr{)}\biggl{/}|\mathbf{v}|_{1,\,\Omega}\biggr{]}\geqslant\, Ch\,\|\,q\|_{0,\,\Omega}\quad\quad\forall q\in\mathcal{M}_{h}.\]

Proof.: Let \(q\) be an arbitrary function of \(\mathcal{M}_{h}\); we introduce the discrete seminorm:

(3.28) \[|q|_{1,\,h}=\biggl{(}\sum_{i,\,j}h^{2}\,\{(\mathcal{V}_{1}q)_{i,\,j}^{2}+( \mathcal{V}_{2}q)_{i,\,j}^{2}\}\biggr{)}^{1/2},\]

where the summation runs over all interior nodes \((i,j)\) of \(\mathcal{T}_{h}.\) In view of (3.20), we define the function \(\mathbf{v}=(u,v)\) of \(X_{h}\) by:

\[u_{i,\,j}=\,-(\mathcal{V}_{1}\,q)_{i,\,j},\quad\,v_{i,\,j}=\,-(\mathcal{V}_{2 }\,q)_{i,\,j}\]

Figure 15:
