Apart from the boundary value operator \(\gamma_{0}\), we shall also require the trace of the normal derivative \(\gamma_{1}u\) defined for \(u\) in \(\mathcal{D}(\Omega)\) by

\[\gamma_{1}u=\partial u/\partial n=\sum_{i=1}^{N}\gamma_{0}(\partial u/\partial x _{i})n_{i},\] (18)

where \(\mathfrak{n}=(n_{1},\ldots,n_{N})\) denotes the _unit outward normal_ to \(\Gamma\). Then we can complete as follows the statement of Theorem 1.5.

**Theorem 1.6**.: _We keep the assumptions of Theorem 1.5 with \(l\geq 1\). The mapping_:__

\[u\to\{\gamma_{0}u,\gamma_{1}u\}\]

_defined on \(\mathcal{D}(\Omega)\) has a unique linear continuous extension as an operator from_

\[W^{s.p}(\Omega)\quad\text{onto }W^{s-1/p.p}(\Gamma)\times W^{s-1/p,p}(\Gamma).\]

_Moreover, in \(W^{2,p}(\Omega)\) we have the following characterization_:__

\[\operatorname{Ker}\gamma_{0}\cap\operatorname{Ker}\gamma_{1}=W_{0}^{2,p}( \Omega).\]

_Remark 1.1_.: If the boundary of \(\Omega\) has corners, its normal vector has jumps and it is obvious that \(\partial u/\partial n\) is rough no matter how smooth \(u\) can be. Nevertheless, it is possible to extend slightly the statement of Theorem 1.6. Assume that \(\Omega\) is a bounded two-dimensional polygon; let \(\Gamma_{j}\) denote the sides of \(\Gamma\) and \(\mathfrak{n}_{j}\) the corresponding exterior unit normal, \(1\leq j\leq J\). Then the mapping:

\[u\to(\partial u/\partial n_{j};\,1\leq j\leq J)\]

is linear, continuous and _surjective_ from \(W^{k+2,p}(\Omega)\) onto

\[\prod_{j=1}^{J}W^{k+1-1/p,p}(\Gamma_{j}),\]

for each integer \(k\geq 0\) and real \(p\in(1,\infty)\). Note that there is no matching condition for \(\partial u/\partial n\) at the vertices of \(\Gamma\).

The situation of the boundary values of \(u\) is a bit more complicated because there is usually a matching condition at the vertices of \(\Gamma\). For the sake of simplicity, we shall just take \(u\) in \(W^{2,p}(\Omega)\). Denote the vertices of \(\Gamma\) by \(S_{j}\) with the convention that \(S_{J+1}=S_{1}\). The mapping:

\[u\to(h_{j}=u|_{\Gamma_{j}};\,1\leq j\leq J)\]

is linear, continuous and _surjective_ from \(W^{2,p}(\Omega)\) onto the subspace of

\[\prod_{j=1}^{J}W^{2-1/p,p}(\Gamma_{j})\]

defined by the compatibility conditions

\[h_{j}(S_{j+1})=h_{j+1}(S_{j+1}),\quad\,1\leq j\leq J.\]
