**Lemma 3.1**.: _If \(M_{h}\subset\Theta_{h}\), we have for all \(v=(\operatorname{\mathbf{curl}}\phi,\theta)\in V\):_

\[\inf_{w_{h}\in V_{h}}|v-w_{h}|\leqslant\inf_{v_{h}=(\operatorname{ \mathbf{curl}}\phi_{h},\theta_{h})\in X_{h}}\left[2|v-v_{h}|+\sup_{\mu_{h}\in M_ {h}}\frac{|(\operatorname{\mathbf{curl}}(\phi-\phi_{h}),\operatorname{ \mathbf{curl}}\mu_{h})|}{\|\mu_{h}\|_{0,\Omega}}\right].\] (3.1)

_The same bound is valid for \(\inf_{w_{h}\in V_{h}}\|v-w_{h}\|_{\widetilde{X}}\) with the norm \(|.|\) in the right-hand side of (3.1) replaced by \(\|.\|_{\widetilde{X}}\)._

Proof.: Let \(v_{h}=(\operatorname{\mathbf{curl}}\phi_{h},\theta_{h})\) be an arbitrary element of \(X_{h}\) and let \(\tau_{h}\in M_{h}\) be defined by:

\[(\tau_{h},\mu_{h})=(\theta-\theta_{h},\mu_{h})-(\operatorname{ \mathbf{curl}}(\phi-\phi_{h}),\operatorname{\mathbf{curl}}\mu_{h})\quad\quad \forall\mu_{h}\in M_{h}.\]

Then

\[\|\tau_{h}\|_{0,\Omega}\leqslant\|\theta-\theta_{h}\|_{0,\Omega}+\sup_{\mu_{h} \in M_{h}}\frac{|(\operatorname{\mathbf{curl}}(\phi-\phi_{h}),\operatorname{ \mathbf{curl}}\mu_{h})|}{\|\mu_{h}\|_{0,\Omega}}.\] (3.2)

Furthermore, since \(M_{h}\subset\Theta_{h}\) the pair \(z_{h}=(\mathbf{0},\tau_{h})\) belongs to \(X_{h}\). Let us set

\[w_{h}=v_{h}+z_{h}\]

and note that \(w_{h}\in V_{h}\) because \(v\in\widetilde{V}\). Thus, we have

\[|v-w_{h}|\leqslant|v-v_{h}|+\|\tau_{h}\|_{0,\Omega},\] \[\|v-w_{h}\|_{\widetilde{X}}\leqslant\|v-v_{h}\|_{\widetilde{X}}+ \|\tau_{h}\|_{0,\Omega}\]

and the bound (3.1) follows from (3.2) and the fact that \(v_{h}\) is arbitrary. 

By inspecting (3.1), we see that the difficulties lie in evaluating properly the term

\[\sup_{\mu_{h}\in M_{h}}\frac{|(\operatorname{\mathbf{curl}}(\phi-\phi_{h}), \operatorname{\mathbf{curl}}\mu_{h})|}{\|\mu_{h}\|_{0,\Omega}},\]

because the numerator involves the first derivatives of \(\mu_{h}\) while the denominator does not. Of course, here we cannot resort to the simple trick of SS 2 which consists in writing that

\[|\mu_{h}|_{1,\Omega}\leqslant(C/h)\|\mu_{h}\|_{0,\Omega}\quad\quad\forall\mu_ {h}\in M_{h},\]

for this process is too crude. Instead, we propose to use a clever argument due to Scholz [72]. Roughly speaking, this author remarks that by choosing

\[\phi_{h}=\check{P}_{h}\phi,\]

the projection of \(\phi\) onto \(\Phi_{h}\) then the expression \((\operatorname{\mathbf{curl}}(\phi-\phi_{h}),\operatorname{\mathbf{curl}}\mu _{h})\) reduces to a sum of integrals taken only on boundary elements. Since these elements are few compared to the total number of elements in \(\Omega\), a much sharper bound can be derived for this expression. The details are given in the next lemma.
