"reference" set \(\hat{\kappa}\)--not necessarily the unit square--that is related to \(\kappa\) by an _affine mapping_\(F\). More precisely, let us split \(\kappa\) into the two subtriangles (cf. Figure 11):

\[\kappa=S_{1}\cup S_{3},\]

let \(\hat{S}_{1}\) be the _reference unit triangle_, \(F\) the _affine mapping_ such that

\[S_{1}=F(\hat{S}_{1}),\hskip 14.226378ptF(\hat{x})=B\hat{x}+b\]

and set

\[\hat{S}_{3}=F^{-1}(S_{3}).\]

In other words,

\[\hat{\kappa}=\hat{S}_{1}\cup\hat{S}_{3},\hskip 14.226378pt\kappa=F(\hat{\kappa}).\]

_As \(F\)_ is affine and \(\kappa\) is convex, the reference set \(\hat{\kappa}\) is also a _convex quadrilateral_. In addition, we readily derive that on the one hand

\[\text{meas}(\hat{S}_{i})=(1/2)\,[\text{meas}(S_{i})/\text{meas}(S_{1})], \hskip 14.226378pt1\leqslant i\leqslant 4\]

where \(\hat{S}_{i}\) (resp. \(S_{i}\)) denotes any of the four subtriangles of \(\hat{\kappa}\) (resp. \(\kappa\)). On the other hand any two vertices of \(\hat{\kappa}\) satisfy:

\[\hat{a}_{i}-\hat{a}_{j}=B^{-1}(a_{i}-a_{j}).\]

Furthermore formulas (A.2) and (A.3) give here

\[\|B\|\leqslant(3/2)h_{s_{1}},\hskip 14.226378pt\|\,B^{-1}\|\leqslant\sqrt{2}/ \rho_{s_{1}},\hskip 14.226378pt|\det(B)|=2\,\text{meas}(S_{1}).\]

Now, let \(f\!\in\!H^{k}(\kappa)\) with \(0\leqslant k\leqslant l\). The \(L^{2}\)-projection \(\rho_{h}\) on \(P_{l-1}\) is invariant under affine transformations. Thus

\[\|f-\rho_{h}f\|_{0,\kappa}=|\det(B)|^{1/2}\,\|\,\hat{f}-\hat{\rho}\hat{f}\|_{ 0,\hat{\kappa}}.\]

But

\[\|\,\hat{f}-\hat{\rho}\hat{f}\|_{0,\hat{\kappa}}\leqslant\inf_{q\in P_{j}}\| \,\hat{f}+q\,\|_{0,\hat{\kappa}}=\|\,\hat{f}\,\|_{L^{2}(\hat{\kappa})/P_{j}} \hskip 14.226378pt0\leqslant j\leqslant l-1.\]

Since \(\hat{\kappa}\)_is a variable quadrilateral_, we must explicit the constant \(C(\hat{\kappa})\) such that

\[\|\,\hat{f}\,\|_{L^{2}(\hat{\kappa})/P_{j}}\leqslant C(\hat{\kappa})|\,\hat{ f}\,|_{j+1,\hat{\kappa}}.\]

This is done by induction on the degree \(j\). When \(j=0\), which is the only case where we can use Theorem A.3, we get

\[\|\,\hat{f}\,\|_{L^{2}(\hat{\kappa})/P_{0}}\leqslant C_{1}h_{\hat{\kappa}} \left[\frac{\text{Max}_{i}\text{meas}(\hat{S}_{i})}{\text{Min}_{i}\text{meas}( \hat{S}_{i})}\right]^{1/2}|\,\hat{f}|_{1,\hat{\kappa}},\]

with a constant \(C_{1}\) independent of \(h\), \(\hat{\kappa}\) and \(\hat{f}\). The above remarks concerning the geometry of \(\hat{\kappa}\) imply that:

\[\left[\frac{\text{Max}_{i}\text{meas}(\hat{S}_{i})}{\text{Min}_{i}\text{meas }(\hat{S}_{i})}\right]^{1/2}\leqslant C_{2}\,\sigma_{\kappa},\hskip 14.226378pth_{ \hat{\kappa}}\leqslant C_{3}\,\sigma_{\kappa}.\]
