Collecting these equalities we get:

\[\|p-p_{h}\|_{0,\Omega}^{2} = (\mathbf{grad}(q_{h}-p),\mathbf{grad}(q-P_{h}q))-v(o_{h}-\omega, \operatorname{curl}\mathbf{v})\] \[-v(\mathbf{curl}(o_{h}-\theta_{h}),\mathbf{v}_{h}-\mathbf{v})-v( \mathbf{curl}(\theta_{h}-\omega),\mathbf{v}_{h}-\mathbf{v})\] \[\forall q_{h}\!\in\!Q_{h},\quad\theta_{h}\!\in\!\Theta_{h},\quad \phi_{h}\!\in\!\Phi_{h}.\]

Then (2.37) implies (2.38). 

We end this section with a specific example of spaces \(\Phi_{h}\), \(\Theta_{h}\), \(M_{h}\) and \(Q_{h}\). To simplify the discussion, we assume that \(\Omega\) is a _polygonal domain_ of \(\mathbb{R}^{2}\). Let \(\mathcal{T}_{h}\) be a family of triangulations of \(\Omega\) consisting of triangles and/or convex quadrilaterals whose diameters are bounded by \(h\). We suppose that the family \(\mathcal{T}_{h}\) is _uniformly regular_ as \(h\) tends to zero (cf. Definition 2):

\[\tau h\leqslant h_{\kappa}\leqslant\sigma\rho_{\kappa}\quad\quad\forall\kappa \!\in\!\mathcal{T}_{h},\quad\tau>0,\quad\sigma>0.\] (2.16)

For the sake of conciseness, the proofs are derived for a triangulation which is made exclusively of triangles but they can be extended, with very few modifications, to the case where \(\mathcal{T}_{h}\) also includes quadrilaterals.

For a given integer \(l\geqslant 1\), we choose the following standard finite element spaces:

\[\begin{cases}\Theta_{h}=M_{h}=\{\theta_{h}\!\in\!\mathcal{C}^{0}(\Omega);\, \theta_{h}|_{\kappa}\!\in\!P_{l}\quad\forall\kappa\!\in\!\mathcal{T}_{h}\} \subset W^{1,\,\infty}(\Omega),\\ \Phi_{h}=\Theta_{h}\!\cap\Phi=\{\phi_{h}\!\in\!\Theta_{h};\,\phi_{h}|_{\Gamma_{ 0}}=0,\,\phi_{h}|_{\Gamma_{i}}=\text{an arbitrary constant $c_{i}$}\\ \quad\quad 1\leqslant i\leqslant p\},\\ Q_{h}=\{q_{h}\!\in\!\mathcal{C}^{0}(\Omega)\cap L_{0}^{2}(\Omega);\,q_{h}|_ {\kappa}\!\in\!P_{k}\quad\forall\kappa\!\in\!\mathcal{T}_{h}\},\quad k=\min(1, l-1).\end{cases}\] (2.39)

The reason for taking polynomials of degree \(l-1\) for the pressure appears in the bound (2.38). Indeed, the order of convergence of \(p-p_{h}\) cannot be higher than that of \(\omega-\omega_{h}\), whatever the degree of \(p_{h}\).

Here, we have \(\Phi_{h}\!\subset\!\Theta_{h}\!=M_{h}\). Now the approximation properties of the operator \(P_{h}\) are stated in Theorem 2 and the constants \(K(h)\) are estimated by Corollary 3 (both results require the uniformity of \(\mathcal{T}_{h}\)):

\[\|\theta_{h}\|_{1,r,\Omega}\leqslant C(r)(1/h)\,\|\theta_{h}\|_{0,\Omega} \quad\quad\forall\theta_{h}\!\in\!\Theta_{h},\quad\forall r\leqslant 2,\] (2.40)

where the constant \(C(r)\) depends upon \(r\) and \(\Omega\). As a consequence, we have the following estimate for the approximation error in \(V_{h}\):

\[\inf_{v_{h}\!\in\!V_{h}}\|v-v_{h}\|_{\widetilde{\boldsymbol{x}}} \leqslant Ch^{k-1}(|\phi|_{k+1,s,\Omega}+\|\theta\|_{k,\Omega})\quad\quad 0 \leqslant k\leqslant l,\] (2.41) \[\forall v=(\mathbf{curl}\,\phi,\theta)\!\in\!V\cap(W^{k+1,s}( \Omega)\times H^{k}(\Omega)).\]

Thus it remains to check Hypotheses 1 (when \(s>2\)) and 2. This is the object of the next two lemmas. Both include the assumption that \(\Omega\) is a convex polygon because their proofs require extra regularity for the solution of the Dirichlet problem for the Laplace operator.
