Clearly, the tensors \(\tau\) of \(\Sigma_{h}\) are uniquely determined by the data \(M_{n}(\tau)\) on each segment \(\kappa^{\prime}\) of \(\Gamma_{h}\).

At the same time, we can easily define a convenient restriction operator \(\pi_{h}\) from \(\Sigma\) onto \(\Sigma_{h}\) with attractive properties. First, if \(\tau\) is a symmetric tensor of \(L^{1}(\kappa)^{4}\) with \(M_{n}(\tau)\in L^{1}(\delta\kappa)\) we define the symmetric tensor \(\pi_{\kappa}\tau\) of \(P_{t-1}^{4}\) by:

\[\left\{\begin{aligned} &\int_{\kappa^{\prime}}M_{n}(\pi_{ \kappa}\tau-\tau)q\,ds=0\quad\quad\forall q\in P_{t-1}(\kappa^{\prime})\quad \quad\forall\text{sides $\kappa^{\prime}$ of $\kappa$},\\ &\left\{\begin{aligned} &\int_{\kappa}(\pi_{\kappa}\tau- \tau)_{ij}q\,dx=0\quad\quad\forall q\in P_{t-2}(\kappa),\quad\quad 1\leqslant i,j \leqslant 2,\quad\text{if $l\geqslant 2$}.\end{aligned}\right.\end{aligned}\right.\] (4.27)

Then for \(\tau\in\Sigma\), we define \(\pi_{h}\tau\in\Sigma_{h}\) by:

\[\pi_{h}\tau|_{\kappa}=\pi_{\kappa}(\tau|_{\kappa})\quad\quad\forall\kappa\in \mathcal{T}_{h}.\] (4.28)

Clearly, \(\pi_{h}\tau\) is a symmetric tensor and the continuity of \(M_{n}(\tau)\) implies that \(M_{n}(\pi_{h}\tau)\) is continuous across each interelement boundary \(\kappa^{\prime}\). Therefore \(\pi_{h}\tau\) belongs indeed to \(\Sigma_{h}\). In addition, we readily derive from (4.25a) and (4.26) that (4.27) holds iff

\[\left\{\begin{aligned} &\int_{\kappa^{\prime}}M_{\hat{n}}( \widehat{\tau_{\kappa}\tau}-\hat{t})q\,d\hat{s}=0\quad\quad\forall q\in P_{t- 1}(\hat{\kappa}^{\prime})\quad\quad\forall\text{sides $\hat{\kappa}^{\prime}$ of $\hat{\kappa}$},\\ &\left\{\begin{aligned} &\int_{\hat{\kappa}}(\widehat{\tau_{ \kappa}\tau}-\hat{t})_{ij}q\,d\hat{x}=0\quad\quad\forall q\in P_{t-2}(\hat{ \kappa}),\quad\quad 1\leqslant i,j\leqslant 2,\quad\text{if $l\geqslant 2$},\end{aligned}\right. \end{aligned}\right.\] (4.29)

where, as usual, \(\hat{\kappa}\) denotes the unit reference triangle. Hence, applying the definition (4.27) to \(\hat{\kappa}\), we find that \(\pi_{\kappa}\) is preserved by affine transformations:

\[\widehat{\tau_{\kappa}\tau}=\pi_{\hat{\kappa}}\hat{t}\quad\quad\forall\kappa \in\mathcal{T}_{h}.\] (4.30)

The remaining properties of \(\pi_{h}\) are stated in the next lemma.

Lemma 4.2: _Assume that the triangulation \(\mathcal{T}_{h}\) is regular. The operator \(\pi_{h}\) defined by (4.27) and (4.28) is a linear mapping from \(\Sigma\) onto \(\Sigma_{h}\) and satisfies:_

\[b_{h}(\tau-\pi_{h}\tau,\phi_{h})=0\quad\quad\forall\phi_{h}\in \mathcal{O}_{h},\] (4.31) \[\left\|\pi_{h}\tau\right\|_{0,h}\leqslant C_{1}\left\|\tau\right\| _{0,h}\] (4.32)

_Moreover, if \(\tau\in H^{k}(\Omega)^{4}\cap\Sigma\) for some real \(k\in[1,l]\), the following estimate holds:_

\[\left\|\pi_{h}\tau-\tau\right\|_{0,h}\leqslant C_{2}h^{k}|\tau|_{k,\Omega}.\] (4.33)

_Proof_. It is clear from (4.27) that the operator \(\pi_{h}\) is a linear mapping from \(\Sigma\) onto \(\Sigma_{h}\). Besides that, (4.31) follows immediately from (4.27), the expression (4.15) of \(b_{h}(.,.)\) and the definition of \(\Theta_{h}\).

Let us turn to (4.32). To begin with, we observe from (4.27) that

\[\left\|M_{n}(\pi_{h}\tau)\right\|_{0,\Gamma_{h}}\leqslant\left\|M_{n}(\tau) \right\|_{0,\Gamma_{h}}\quad\quad\forall\tau\in\Sigma.\] (4.34)
