computation of \(\rho^{m}\) for Problem (6.21). First, observe that the mapping \(\rho\to J({\bf v}\,-\,\rho{\bf w})\) is a fourth-degree polynomial because \(F\) is a polynomial of degree two. Therefore Taylor's expansion of \(J({\bf u}^{m}-\rho{\bf g}^{m})\) reduces to:

\[J({\bf u}^{m}-\rho{\bf g}^{m}) = J({\bf u}^{m})-\rho DJ({\bf u}^{m})\cdot{\bf g}^{m}+(\rho^{2}/2)D ^{2}J({\bf u}^{m})\cdot({\bf g}^{m},{\bf g}^{m})\] \[-(\rho^{3}/6)D^{3}J({\bf u}^{m})\cdot({\bf g}^{m},{\bf g}^{m},{\bf g }^{m})\] \[+(\rho^{4}/24)D^{4}J({\bf u}^{m})\cdot({\bf g}^{m},{\bf g}^{m},{\bf g }^{m},{\bf g}^{m}),\]

where the third and fourth derivatives of \(J\) have the simple expression:

\[D^{3}J({\bf u}^{m})\cdot({\bf g}^{m},{\bf g}^{m},{\bf g}^{m}) = 3\langle A^{-1}DF({\bf u}^{m})\cdot{\bf g}^{m},D^{2}F({\bf u}^{m}) \cdot({\bf g}^{m},{\bf g}^{m})\rangle,\] \[D^{4}J({\bf u}^{m})\cdot({\bf g}^{m},{\bf g}^{m},{\bf g}^{m},{\bf g }^{m}) = 3\langle A^{-1}D^{2}F({\bf u}^{m})\cdot({\bf g}^{m},{\bf g}^{m}),D^ {2}F({\bf u}^{m})\cdot({\bf g}^{m},{\bf g}^{m})\rangle.\]

Summing up, to solve Problem (6.21), each iteration of the _simple gradient algorithm_ runs as follows:

\(1^{\circ})\) given \({\bf u}^{m}\in H^{1}_{0}(\Omega)^{N}\), compute the solution \({\bf z}^{m}\in H^{1}(\Omega)^{N}\) of

\[-v{\boldsymbol{\lambda}}{\boldsymbol{z}}^{m}+c{\boldsymbol{z}}^{m} = -v{\boldsymbol{\lambda}}{\bf u}^{m}+c{\bf u}^{m}+\sum_{j=1}^{N}u_{ j}^{m}(\partial{\bf u}^{m}/\partial x_{j})-{\bf f}\quad\mbox{in $\Omega$},\] \[{\boldsymbol{z}}^{m} = {\bf 0}\quad\mbox{on $\Gamma$};\]

\(2^{\circ})\) find the solution \({\bf g}^{m}\in H^{1}(\Omega)^{N}\) of

\[v({\bf grad}\,{\bf g}^{m},{\bf grad}\,{\bf v})+c({\bf g}^{m},{\bf v }) = v({\bf grad}\,{\bf z}^{m},{\bf grad}\,{\bf v})\] \[+c({\bf z}^{m},{\bf v})+\sum_{j=1}^{N}\left(u_{j}^{m}\partial{ \bf v}/\partial x_{j}+v_{j}\partial{\bf u}^{m}/\partial x_{j},{\bf z}^{m}\right)\] \[\forall{\bf v}\in H^{1}_{0}(\Omega)^{N},\quad{\bf g}^{m}={\bf 0} \quad\mbox{on $\Gamma$};\]

\(3^{\circ})\) compute

\[J({\bf u}^{m})=(1/2)\{v|{\bf z}^{m}|_{1,\Omega}^{2}+c\,\|\,{\bf z}^{m}\|_{0, \Omega}^{2}\},\] (6.36) \[DJ({\bf u}^{m})\cdot{\bf g}^{m}=(1/2)\{v|{\bf g}^{m}|_{1,\Omega }^{2}+c\,\|\,{\bf g}^{m}\|_{0,\Omega}^{2}\};\]

\(4^{\circ})\) find the solution \({\bf v}^{m}\in H^{1}(\Omega)^{N}\) of

\[-v{\boldsymbol{\lambda}}{\bf v}^{m}+c{\bf v}^{m} = -v{\boldsymbol{\lambda}}{\bf g}^{m}+c\,{\bf g}^{m}+\sum_{j=1}^{N} \left(u_{j}^{m}\partial{\bf g}^{m}/\partial x_{j}+g_{j}^{m}\partial{\bf u}^{m }/\partial x_{j}\right)\quad\mbox{in $\Omega$},\] \[{\bf v}^{m} = {\bf 0}\quad\mbox{on $\Gamma$};\]

\(5^{\circ})\) compute

\[{\bf t}^{m}=D^{2}F({\bf u}^{m})\cdot({\bf g}^{m},{\bf g}^{m})=2\sum_{j=1}^{N}g _{j}^{m}\partial{\bf g}^{m}/\partial x_{j},\] (6.37) \[D^{2}J({\bf u}^{m})\cdot({\bf g}^{m},{\bf g}^{m})=v|{\bf v}^{m}|_ {1,\Omega}^{2}+c\,\|\,{\bf v}^{m}\|_{0,\Omega}^{2}+({\bf z}^{m},{\bf t}^{m}).\] (6.38) \[D^{3}J({\bf u}^{m})\cdot({\bf g}^{m},{\bf g}^{m},{\bf g}^{m})=3({ \bf t}^{m},{\bf v}^{m});\]
