(3.23) \[|\hat{\phi}|_{k,\,\hat{\kappa}}\leqslant C\sigma_{\kappa}h_{\kappa}^{k-1}\biggl{(} \sum_{i=1}^{k}|\phi|_{i,\,\kappa}^{2}\biggr{)}^{1/2}\quad\forall\phi\in H^{k}( \kappa).\]

_Moreover there exists a constant \(C>0,\) independent of \(h\) and \(\kappa,\) such that_:

(3.24) \[\|\partial\bigl{[}(1/J_{F})(\partial F_{\kappa}/\partial\hat{x}_{i})\cdot( \partial F_{\kappa}/\partial\hat{x}_{j})\bigr{]}/\partial\hat{x}_{k}\|_{0,\, \infty,\,\hat{\kappa}}\leqslant C\sigma_{\kappa}^{2}h_{\kappa}(1\,+\,\sigma_{ \kappa}^{2})\\ 1\leqslant i,j,\,k\leqslant 2.\]

As a consequence, if the triangulation \(\mathcal{T}_{h}\) is regular, it follows that (3.24) implies:

\[\bigl{[}(1/J_{F})(\partial F_{\kappa}/\partial\hat{x}_{i})\cdot(\partial F_{ \kappa}/\partial\hat{x}_{j})\bigr{]}(\hat{x}_{1},\hat{x}_{2})=\bigl{[}(1/J_{F} )(\partial F_{\kappa}/\partial\hat{x}_{i})\cdot(\partial F_{\kappa}/\partial \hat{x}_{j})\bigr{]}(1/2,1/2)+\,R_{\kappa}\]

where the remainder \(R_{\kappa}\) is bounded by:

\[|R_{\kappa}|\leqslant Ch.\]

Since we are specifically interested in recovering one power of \(h,\) we can neglect that remainder and it follows from (3.21) and (3.24) that the study of the expression

\[\int_{\kappa}\operatorname{\mathbf{curl}}(\phi-\phi_{h})\cdot\operatorname{ \mathbf{curl}}\mu_{h}\,dx\]

reduces for us to that of the four terms

(3.25) \[\int_{\hat{\kappa}}\bigl{[}\partial(\hat{\phi}-\hat{\phi}_{h})/\partial\hat{ x}_{i}\bigr{]}\bigl{[}\partial\hat{\mu}/\partial\hat{x}_{j}\bigr{]}\,d\hat{x}, \quad 1\leqslant i,j\leqslant 2.\]

Furthermore, if we choose \(\phi_{h}=I_{h}\phi,\) where \(I_{h}\) is the interpolation operator on \(\kappa\) corresponding to \(\hat{I},\) then according to Lemma 3.5, \(\int_{\hat{\kappa}}\bigl{[}\partial(\hat{\phi}-\hat{I}\hat{\phi})/\partial\hat {x}_{i}\bigr{]}\bigl{[}\partial\hat{\mu}/\partial\hat{x}_{j}\bigr{]}\,d\hat{x}\) involves in particular factors of the form

\[\int_{\hat{\kappa}}\partial(\omega_{i})/\partial\hat{x}_{i}\partial\hat{\mu}/ \partial\hat{x}_{j}\,d\hat{x}\]

where

\[\omega_{i}=\prod_{0\leqslant p\leqslant l}(\hat{x}_{i}-\alpha_{p}).\]

Now, if the points \(\alpha_{k}\) coincide with the nodes of a highly precise quadrature formula, this last integral will possibly vanish. This remark induces us to choose for the set \(\{\alpha_{k}\}\) the \(l+1\)_nodes of the Gauss-Lobatto quadrature formula on \([0,1].\)_

Recall that this formula is exact for polynomials of degree \(2l-1.\) Then we have the following lemma.

**Lemma 3.8**.: _Let \(\kappa\) be like in Lemma 3.7 and let \(\{\alpha_{k}\}_{0\leqslant k\leqslant l}\) be the \(l+1\) nodes of the Gauss-Lobatto quadrature formula. Then there exists a constant \(C>0,\) independent of \(h\) and \(\kappa,\) such that:_

(3.26) \[\biggl{|}\int_{\hat{\kappa}}\bigl{[}\partial(\hat{\phi}-\hat{I} \hat{\phi})/\partial\hat{x}_{i}\bigr{]}\bigl{[}\partial\hat{\mu}/\partial\hat {x}_{i}\bigr{]}\,d\hat{x}\biggr{|}\leqslant C\sigma_{\kappa}^{2}h_{k}^{t}\| \phi\|_{l+2,\kappa}\|\,\mu_{h}\|_{0,\,\kappa}\] \[\qquad\qquad\qquad\qquad\qquad\qquad\qquad\qquad\qquad\qquad i=1, 2,\quad\forall\mu_{h}\in\Theta_{h},\quad\forall\phi\in H^{l+2}(\kappa).\]
