_Moreover_, _assuming that \(\Omega\) is convex_, _the solution \(u_{h}=(\mathbf{curl}\,\psi_{h},\omega_{h})\) of Problem (2.29) satisfies the estimate_ (_with another constant \(C>0\)_):

\[\|\,u-u_{h}\|_{\tilde{\boldsymbol{x}}}\leqslant Ch^{t}\,\|\,\psi\,\|_{t+2, \Omega},\] (3.34)

_provided the solution of the Stokes Problem (2.1) has its stream function \(\psi\) in \(H^{t+2}(\Omega)\). When \(\Omega\) is not convex_, _the same order of accuracy is attained if the vorticity \(\omega\) belongs to \(H^{t+1}(\Omega)\)_.

_Finally_, _if the solution \((u=(\mathbf{curl}\,\psi,\omega),p)\) of Problem (2.1) has the regularity_: \(\psi\in H^{t+2}(\Omega)\), \(p\in H^{t}(\Omega)\) and \(\Omega\) is convex_, _we have the estimate for the pressure solution of Problem (2.36):

\[\|\,p-p_{h}\|_{0,\,\Omega}\leqslant Ch^{t}\{|\,p|_{t,\,\Omega}+\,\|\,\psi\,\|_{ t+2,\,\Omega}\}.\] (3.35)

## 4 A "Stream Function-Gradient of Velocity Tensor" Method in Two Dimensions

The method discussed in this paragraph is obtained by taking for dependent variables the stream function \(\psi\) and the gradient of the velocity:

\[\sigma_{ij}=\partial^{2}\psi/\partial x_{i}\partial x_{j},\quad\ 1\leqslant i,j \leqslant 2.\]

In other words it solves for the stream function and all its second derivatives instead of the Laplacian, as was the case of the previous method. The reader will discover that this approach leads to a scheme -- called the Hellan-Herrmann-Johnson scheme--which is economical and optimal. This, and related schemes, are thoroughly analyzed in Brezzi & Raviart [15]. The analysis presented here is a slight variant of this analysis, proposed by Babuska _et al_[5]. It is an elegant application of the use of mesh-dependent norms.

### The Hellan-Herrmann-Johnson Formulation

Let \((\mathbf{u},p)\) denote the solution of Problem (2.1), but instead of the vorticity \(\omega\), let us first introduce the non-symmetric gradient of velocity tensor \(\lambda=(\lambda_{ij})\):

\[\lambda_{ij}=\partial u_{i}/\partial x_{j},\quad\ 1\leqslant i,j\leqslant 2\] (4.1)

as a new dependent variable. Then the equations of Problem (2.1) read:

\[\left\{\begin{array}[]{c}-v\sum\limits_{j=1}^{2}\partial\lambda_{ij}/\partial x _{j}+\partial p/\partial x_{i}=f_{i},\quad\ i=1,2\\ \sum\limits_{j=1}^{2}\lambda_{ij}=0,\end{array}\right\}\quad\text{in }\Omega\] (4.2)

whence a new formulation will be deduced by suitable integrations by parts.
