\(\{(\lambda,u^{\varepsilon}(\lambda)=({\bf u}^{\varepsilon}(\lambda),\lambda p^{ \varepsilon}(\lambda)));\lambda\in\Lambda\}\) of solutions of (3.44) such that_

\[u^{\varepsilon}(\lambda)\in u(\lambda)+\mathcal{O}\ \ \ \ \ \ \forall\lambda\in\Lambda.\]

_Moreover, we get the estimate_

(3.46) \[\sup_{\lambda\in\Lambda}(\|\,{\bf u}^{\varepsilon}(\lambda)-{\bf u}(\lambda) \|_{1,\Omega}+\|\,p^{\varepsilon}(\lambda)-p(\lambda)\|_{0,\Omega})\leqslant Ce,\]

_where the constant \(C\) is independent of \(\varepsilon\)._

_Proof._ If we define the spaces \(X\) and \(Y\) by (3.5) and (3.6) and the mappings \(T\) and \(G\) by (3.7) and (3.8) respectively, we have already seen that Problem (2.1) (2.13) fits into the framework of Section 3.1. Then, in order to apply Theorem 3.3 we take \(Z=Y\) and we define the operator \(T^{\varepsilon}\) of \(\mathcal{L}(Y;X)\) as follows:

_given \(({\bf f}_{\star},{\bf g}_{\star})\in Y\) let \(({\bf u}^{\varepsilon}_{\star},p^{\varepsilon}_{\star})=T^{\varepsilon}({\bf f }_{\star},{\bf g}_{\star})\) denote the solution of the regularized Stokes problem_

\[\left[\begin{array}[]{c}-\Delta{\bf u}^{\varepsilon}_{\star}+{\bf grad}\,p^{ \varepsilon}_{\star}&={\bf f}_{\star}\\ p^{\varepsilon}_{\star}&=\,-(1/\varepsilon)\,{\rm div}\,{\bf u}^{ \varepsilon}_{\star}\end{array}\right]\ \ \ \mbox{in }\Omega,\]

Clearly, \(({\bf u}^{\varepsilon},p^{\varepsilon})\) is a solution of (3.44) if and only if

\[u^{\varepsilon}+\,T^{\varepsilon\nu}G(\lambda,u^{\varepsilon})=0,\]

where \(u^{\varepsilon}=({\bf u}^{\varepsilon},p^{\varepsilon}/v)\). Moreover, Theorem I.5.3 gives for all \(\varepsilon\leqslant\varepsilon_{0}\) sufficiently small:

\[\|\,T^{\varepsilon\nu}-\,T\|_{\mathcal{L}(Y;X)}\leqslant C_{1}\varepsilon\nu \leqslant C_{2}\varepsilon,\]

with a constant \(C_{2}\) independent of \(\lambda\) owing to the compactness of \(\Lambda\).

Now since

\[G(\lambda,v)=\left(\lambda\left(\sum_{j=1}^{N}v_{j}\partial{\bf v}/\partial x_ {j}-{\bf f}\right)\right),\,-\,{\bf g}\right),\]

it follows that \(D^{2}G\) is independent of \(v\):

\[D^{2}G(\lambda,v)\cdot(u,w)=\lambda\sum_{j=1}^{N}\big{(}w_{j}\partial{\bf u}/ \partial x_{j}+u_{j}\partial{\bf w}/\partial x_{j}\big{)}.\]

Thus the mapping \(D^{2}G\) is bounded on all bounded subsets of \(\Lambda\times X\) for \(N\leqslant 4\), by virtue of the Sobolev's Imbedding Theorem I.1.3. (And more generally, \(G\) is \(\mathcal{C}^{\infty}\) and \(D^{p}G\) is zero for all \(p\geqslant 2\)). Therefore the fact that \(\{(\lambda,u(\lambda));\lambda\in\Lambda\}\) is a branch of nonsingular solutions of

\[F(\lambda,u)\equiv u+\,TG(\lambda,u)=0\]

permits to apply Theorem 3.3. In other words, if \(\varepsilon_{0}\) is small enough there exist a real \(a>0\) and a unique branch \(\{(\lambda,u^{\varepsilon}(\lambda)=({\bf u}^{\varepsilon}(\lambda),\lambda p ^{\varepsilon}(\lambda)));\lambda\in\Lambda\}\) of nonsingular
