\[\sigma^{m}=\frac{(g^{m}-g^{m-1},g^{m})_{X}}{\|g^{m-1}\|_{X}^{2}} = \frac{\langle DJ(u^{m})-DJ(u^{m-1}),g^{m}\rangle}{\|g^{m-1}\|_{X}^{ 2}}\] \[= -\rho^{m-1}\,\frac{D^{2}J^{m-1}\cdot(w^{m-1},g^{m})}{\|g^{m-1}\|_{X }^{2}}\] \[= -\frac{D^{2}\,J^{m-1}\cdot(w^{m-1},g^{m})}{D^{2}J^{m-1}\cdot(w^{m- 1},w^{m-1})}\]

in view of (6.18). Therefore (6.2) yields:

\[|\sigma^{m}|\leq(M/\alpha)(\|g^{m}\|_{X}/\|w^{m-1}\|_{X}),\]

whence

\[\|w^{m}\|_{X}=\|g^{m}+\sigma^{m}w^{m-1}\|_{X}\leq(1+M/\alpha)\|g^{m}\|_{X}.\]

Thus

\[(g^{m},w^{m})_{X}=\|g^{m}\|_{X}^{2}\geq\big{[}\|g^{m}\|_{X}\|w^{m}\|_{X}\big{]} /(1+M/\alpha),\]

proving (6.7) with \(\beta=1/(1+M/\alpha)\). 

### Least-Squares and Gradient Methods to Solve the Navier-Stokes Equations

We propose first to decouple the divergence-free constraint and the nonlinearity in the Navier-Stokes equations by means of a heuristic alternating direction method introduced by Glowinski [36]. Then we shall solve the resulting nonlinear equations with the gradient methods of the preceding section.

Following the Peaceman-Rachford _alternating directions algorithm_ we construct a sequence \((\mathbf{u}^{m},p^{m})\) starting from an initial pair \((\mathbf{u}^{0},p^{0})\) by:

\[\left\{\begin{array}[]{rl}-v\Delta\mathbf{u}^{m+1/2}+r^{m}\mathbf{u}^{m+1/2}- \mathbf{grad}\,p^{m+1/2}\\ \\ =\mathbf{f}-\sum\limits_{j=1}^{N}u_{j}^{m}\partial\mathbf{u}^{m}/\partial x_{ j}+r^{m}\mathbf{u}^{m}&\mbox{in }\Omega,\\ \\ \mbox{div}\,\mathbf{u}^{m+1/2}=0&\mbox{in }\Omega,\\ \\ \mathbf{u}^{m+1/2}=\mathbf{0}&\mbox{on }\Gamma;\end{array}\right.\] (6.19)

\[\left\{\begin{array}[]{rl}-v\Delta\mathbf{u}^{m+1}+\sum\limits_{j=1}^{N}u_{j} ^{m+1}\partial\mathbf{u}^{m+1}/\partial x_{j}+r^{m}\mathbf{u}^{m+1}\\ \\ =\mathbf{f}-\mathbf{grad}\,p^{m+1/2}+r^{m}\mathbf{u}^{m+1/2},\\ \\ \mathbf{u}^{m+1}=\mathbf{0}&\mbox{on }\Gamma,\end{array}\right.\] (6.20)

where the parameters \(r^{m}\) are to be chosen as best as possible. Clearly, Problem (6.19) is like the Stokes problem which has been thoroughly studied in the
