\[0=\langle DJ(u^{m}-\rho^{m}w^{m}),w^{m}\rangle=\langle DJ(u^{m}),w^{m}\rangle-\rho^{ m}D^{2}J(u^{m}-t\rho^{m}w^{m})\cdot(w^{m},w^{m})\]

for some \(t\in(0,1)\), i.e.

\[(g^{m},w^{m})_{X}=\rho^{m}D^{2}J(u^{m}-t\rho^{m}w^{m})\cdot(w^{m},w^{m}).\]

Thus it follows from the convexity of \(D\), (6.2) and (6.7) that

\[\beta\|g^{m}\|_{X}\|w^{m}\|_{X}\leq\rho^{m}M\|w^{m}\|_{X}^{2}\]

whence we derive the following lower bound for \(\rho^{m}\):

\[\rho^{m}\geq(\beta/M)(\|g^{m}\|_{X}/\|w^{m}\|_{X}).\]

Next, the sequence \(J(u^{m})\) is by construction monotonically decreasing and so the sequence \((u^{m})\) is contained in \(D^{\prime}\). We have in particular:

\[J(u^{m+1})\leq J(u^{m}-\rho w^{m})\quad\text{for all $\rho$ with $0\leq\rho\leq\rho^{m}$}.\]

Therefore

\[J(u^{m+1})\leq J(u^{m})-\rho(g^{m},w^{m})_{X}+(\rho^{2}/2)D^{2}J(u^{m}-t\rho w ^{m})\cdot(w^{m},w^{m})\]

with \(t\in(0,1)\). Using again (6.7) and (6.2) we obtain:

\[J(u^{m+1})\leq J(u^{m})-\rho\beta\|g^{m}\|_{X}\|w^{m}\|_{X}+M(\rho^{2}/2)\|w^{ m}\|_{X}^{2}.\]

In view of (6.13) we can choose \(\rho=(\beta/M)(\|g^{m}\|_{X}/\|w^{m}\|_{X})\) thus getting

\[J(u^{m+1})-J(u^{m})\leq-(1/2)(\beta^{2}/M)\|g^{m}\|_{X}^{2}.\]

As the sequence \(J(u^{m})\) is monotonically decreasing and bounded below (cf. (6.10)), it converges. In particular, (6.14) implies that

\[\lim_{m\to\infty}\|g^{m}\|_{X}^{2}\leq 2(M/\beta^{2})\lim_{m\to\infty}\big{[}J(u^ {m})-J(u^{m+1})\big{]}=0.\]

Besides that we have

\[DJ(u^{m+p})-DJ(u^{m})=D^{2}J(u^{m}+tu^{m+p})\cdot(u^{m+p}-u^{m})\]

with \(t\in(0,1)\). Thus (6.2) gives

\[\alpha\|u^{m+p}-u^{m}\|_{X}^{2} \leq\langle DJ(u^{m+p})-DJ(u^{m}),u^{m+p}-u^{m}\rangle\] \[\leq(g^{m+p}-g^{m},u^{m+p}-u^{m})_{X},\]

i.e.

\[\|u^{m+p}-u^{m}\|_{X}\leq(1/\alpha)\|g^{m+p}-g^{m}\|_{X}.\]

Since \((g^{m})\) converges in \(X\), this means that \((u^{m})\) is a Cauchy sequence in \(X\), and therefore a converging sequence in \(X\). Thus there exists \(u\) in \(D^{\prime}\) with

\[\lim_{m\to\infty}u^{m}=u\]

and furthermore (6.15) and the continuity of \(DJ\) imply that
