**Lemma 2.12**.: _Assume that \(\Omega\) is a bounded\(,\) convex polygon and that the triangulation \(\mathcal{T}_{h}\) is uniformly regular. There exists a constant \(\beta^{*}>0,\) independent of \(h,\) such that\(:\)_

\[\sup_{\theta_{h}\in\,\Theta_{h}}\frac{\left\{b_{h}(\theta_{h},\phi_{h})\right\} }{\left\|\,\theta_{h}\,\right\|_{0,\,h}}\geq\beta^{*}\|\,\phi_{h}\|_{2,\,h} \hskip 14.226378pt\forall\phi_{h}\!\in\!\Phi_{h}.\] (2.63)

_Proof_. First recall that

\[b_{h}(\theta_{h},\phi_{h})=-(\mbox{\bf curl}\,\phi_{h},\mbox{\bf curl}\,\theta _{h})\hskip 14.226378pt\forall\phi_{h}\!\in\!\Phi_{h},\hskip 14.226378pt \forall\theta_{h}\!\in\!\Theta_{h}.\]

Next for a given \(\phi_{h}\) in \(\Phi_{h}\), define \(\theta_{h}\) in \(\Theta_{h}\) by:

\[(\theta_{h},\mu_{h})=(\mbox{\bf curl}\,\phi_{h},\mbox{\bf curl}\,\mu_{h}) \hskip 14.226378pt\forall\mu_{h}\!\in\!\Theta_{h}\] (2.64)

(note the analogy with the second equation in (2.24)). Hence, by virtue of (2.62) we have found \(\theta_{h}\) in \(\Theta_{h}\) such that

\[-b_{h}(\theta_{h},\phi_{h})\geq\alpha^{*}\|\,\theta_{h}\|_{0,\,h}^{2}.\]

Therefore, in order to derive (2.63), we are going to show that:

\[\|\,\phi_{h}\|_{2,\,h}\leq C\|\,\theta_{h}\|_{0,\,\Omega}.\] (2.65)

Now the proof of (2.65) is very similar to that of (2.41) for \(\phi_{h}\) and \(\theta_{h}\) bear here the same relation. But instead, it is convenient to interpret (2.64) as the discretization in \(\Theta_{h}\) of a homogeneous Neumann's problem. This leads us to introduce the solution \(\phi(h)\) (unique up to an additive constant) of

\[-\Delta\phi(h)=\theta_{h}\hskip 14.226378pt\mbox{in}\,\,\Omega,\hskip 14.226378pt \partial\phi(h)/\partial n=0\hskip 14.226378pt\mbox{on}\,\,\Gamma.\]

Note that by choosing \(\mu_{h}=1\) (\(\in\!\Theta_{h}\)) in (2.64), we find that

\[\int_{\Omega}\theta_{h}\,dx=0,\]

which is precisely the compatibility condition of this Neumann's problem. In addition, the convexity of \(\Omega\) implies that \(\phi(h)\!\in\!H^{2}(\Omega)/\mathbb{R}\) with:

\[|\phi(h)|_{2,\,\Omega}\leq C_{1}\,\|\,\theta_{h}\|_{0,\,\Omega}.\]

Like in Remark 2.5 we derive that

\[|\phi_{h}-\chi_{h}|_{1,\,\Omega}\leq|\,\phi(h)-\chi_{h}|_{1,\,\Omega}\hskip 14.226378pt \forall\chi_{h}\!\in\!\Theta_{h}.\]

Hence in view of (2.55) we obtain

\[\|\phi_{h}-\chi_{h}\|_{2,\,h}\leq C_{2}(1/h)\,|\phi(h)-\chi_{h}|_{1,\,\Omega}.\]

Therefore

\[\|\phi_{h}\|_{2,\,h}\leq\inf_{\chi_{h}\in\,\Theta_{h}}\{C_{2}(1/h)\,|\phi(h)- \chi_{h}|_{1,\,\Omega}+\|\,\chi_{h}-\phi(h)\|_{2,\,h}+\|\,\phi(h)\|_{2,\,h}\}.\]

The choice \(\chi_{h}=I_{h}\phi(h)\) gives
