Finally, the bound (2.13) is still valid for the above space \(Q_{h}\). Therefore, we have established that our scheme is of order one:

**Theorem 3.1**.: _Let \(\Omega\) be a bounded polygon and assume that the solution \((\mathbf{u},p)\) of the Stokes equations satisfies:_

\[\mathbf{u}\in[H^{2}(\Omega)\cap H_{0}^{1}(\Omega)]^{2},\quad\quad p\in H^{1}( \Omega)\cap L_{0}^{2}(\Omega).\]

_Then if the triangulation \(\mathcal{T}_{h}\) is regular, the solution \((\mathbf{u}_{n},p_{h})\) of (1.39) with the spaces \(\bar{X}_{h}\) and \(\bar{M}_{h}\) defined by (3.6) (3.7) satisfies the conclusion of Theorem 2.1._

### Higher-Order Quadrilateral Elements

We propose to discuss and generalize the widely used "\(Q_{2}-P_{1}\)" finite element scheme. In short, this method uses continuous velocities with components that are piecewise \(Q_{2}(\kappa)\) and discontinuous pressures that are piecewise \(P_{1}\) on each element \(\kappa\). Its analysis is pretty straightforward and easily extended to arbitrary order \(l\), so we can start directly with the general case.

Again, let \(\kappa\) be any quadrilateral of \(\mathcal{T}_{h}\) and let us choose:

(3.11) \[\begin{cases}W_{h}=\{\mathbf{w}\in\mathcal{C}^{0}(\bar{\Omega})^{2};\,\mathbf{ w}|_{\kappa}\in Q_{l}(\kappa)^{2}\quad\forall\kappa\in\mathcal{T}_{h}\},\\ \qquad\qquad X_{h}=W_{h}\cap H_{0}^{1}(\Omega)^{2},\end{cases}\] (3.12) \[\begin{cases}Q_{h}=\{q\in L^{2}(\Omega);\,q|_{\kappa}\in P_{t-1} \quad\forall\kappa\in\mathcal{T}_{h}\},\\ \qquad\qquad M_{h}=Q_{h}\cap L_{0}^{2}(\Omega),\end{cases}\]

with \(l\geqslant 2\).

Right away, observe that \(\bar{X}_{h}\subset X_{h}\) so that the inf-sup condition need only be checked locally. As a consequence, we can take the simplest degrees of freedom available such as:

the values of each component of \(\mathbf{w}\) on the principal lattice \(\Sigma_{\kappa}\) of order \(l\);

the moments corresponding to \(P_{t-1}\) for \(q\):

\[\int_{\kappa}qf\,dx\quad\quad\forall\in P_{t-1}.\]

To begin with, let us establish the local inf-sup condition. Here again, we take the triangulation as our partition:

(3.13) \[\begin{cases}X_{h}(\kappa)=\{\mathbf{v}\in Q_{l}(\kappa)^{2};\,\mathbf{v}|_{ \partial\kappa}=\mathbf{0}\},\\ \qquad M_{h}(\kappa)=P_{t-1}\cap L_{0}^{2}(\kappa).\end{cases}\]

**Theorem 3.2**.: _Let the triangulation \(\mathcal{T}_{h}\) be regular. Then the pair of spaces \((X_{h}(\kappa),\)\(M_{h}(\kappa))\) defined by (3.13) satisfies Hypothesis H4._
