Besides (4.31), the bilinear form \(b_{h}(.,.)\) satisfies the following striking property.

Lemma 4.3: For each \(\tau_{h}\) in \(\Sigma_{h}\) the following equivalence holds:

\[\{b_{h}(\tau_{h},\phi_{h})=0\quad\forall\phi_{h}\in\mathcal{O}_{h}\}\quad\text{ iff}\quad\{b_{h}(\tau_{h},\phi)=0\quad\forall\phi\in\tilde{\mathcal{V}}\cap \mathcal{C}^{0}(\Omega)\}.\] (4.37)

Proof: Obviously, it is the "only if" part of (4.37) which must be established. To this end, let us take \(\phi\) in \(\mathcal{C}^{0}(\bar{\Omega})\) with \(\phi|_{\kappa}\in H^{2}(\kappa)\) (in which case \(\phi\in H^{1}(\Omega)\)) and prove that

\[b_{h}(\tau_{h},\phi-\tilde{I}_{h}\phi)=0\quad\quad\forall\tau_{h}\in\Sigma_{h},\] (4.38)

where \(\tilde{I}_{h}\) is the interpolation operator defined by (A.22).

Indeed, two integrations by parts yield:

\[\int_{\kappa}f\partial^{2}\phi/\partial x_{i}\partial x_{j}\,dx=\int_{\kappa} (\partial^{2}f/\partial x_{i}\partial x_{j})\phi\,dx-\int_{\partial\kappa}( \partial f/\partial x_{j})\phi n_{i}\,ds+\int_{\partial\kappa}f(\partial\phi/ \partial x_{i})n_{j}\,ds\]

Thus, when \(f\in P_{l-1}\), the formulas (A.22) give:

\[\int_{\kappa}f\partial^{2}(\phi-\tilde{I}_{h}\phi)/\partial x_{i}\partial x_{ j}\,dx=\int_{\partial\kappa}fn_{j}\partial(\phi-\tilde{I}_{h}\phi)/\partial x _{i}\,ds\quad\quad\forall\phi\in H^{2}(\kappa),\quad\quad\forall f\in P_{l-1}.\]

Substituting into the definition (4.15) of \(b_{h}\), we obtain:

\[b_{h}(\tau_{h},\phi-\tilde{I}_{h}\phi)=-\sum_{\kappa\in\mathcal{T}_{h}}\int_{ \partial\kappa}M_{nt}(\tau_{h})\partial(\phi-\tilde{I}_{h}\phi)/\partial t\,ds.\]

Then integrating by parts on each segment \(\kappa\)' of \(\partial\kappa\) and applying again (A.22) we readily find that \(b_{h}(\tau_{h},\phi-\tilde{I}_{h}\phi)=0\). This proves (4.37). 

From the definition (A.22) it is easy to derive that the statement of Lemma 2.11 holds with \(\theta_{h}=\tilde{I}_{h}v\):

\[\|v-\tilde{I}_{h}v\|_{2,h}\leqslant Ch^{k-2}|v|_{k,\Omega}\quad\quad\forall v \in H^{k}(\Omega),\] (4.39)

provided the triangulation \(\mathcal{T}_{h}\) is regular. Thus, combining (4.38) and (4.39) we have the next result.

Corollary 4.1: The operator \(\tilde{I}_{h}\) defined by (A.22) satisfies:

\[b_{h}(\tau_{h},\phi-\tilde{I}_{h}\phi)=0\quad\quad\forall\phi\in\mathcal{C}^{0 }(\bar{\Omega})\quad\text{with }\phi|_{\kappa}\in H^{2}(\kappa),\quad\quad\forall\tau_{h}\in\Sigma_{h}.\]

In addition, if \(\mathcal{T}_{h}\) is a regular triangulation of \(\bar{\Omega}\), there exists a constant \(C>0\), independent of \(h\) and \(\phi\), such that:

\[\|\phi-\tilde{I}_{h}\phi\|_{2,h}\leqslant Ch^{k-2}|\phi|_{k,\Omega}\quad\quad \forall\phi\in H^{k}(\Omega),\]

provided the real \(k\) belongs to \([2,l+1]\).

Now we turn to the inf-sup condition. Let us first restrict ourselves to the space of tensors \(\Sigma\cap\Theta_{h}^{4}\) and more specifically to tensors of the form
