(1.58) \[\left\{\begin{aligned} \int_{\Omega_{r}}\bar{q}_{r}\,\mathrm{div}\, \bar{\mathbf{v}}_{r}\,dx&=\,\|\,\bar{q}_{r}\|_{0,\Omega_{r}}^{2}, \\ |\bar{\mathbf{v}}_{r}|_{1,\Omega_{r}}&\leqslant\frac{1}{ \lambda*}\,\|\,\bar{q}_{r}\|_{0,\Omega_{r}}.\end{aligned}\right.\]

Similarly, since the pair \((\bar{X}_{n},\bar{M}_{n})\) satisfies (1.12) there exists a function \(\bar{\mathbf{v}}_{n}\!\in\!\dot{X}_{n}\!\) such that

(1.59) \[\left\{\begin{aligned} \int_{\Omega}\bar{q}_{n}\,\mathrm{div}\, \bar{\mathbf{v}}_{n}\,dx&=\,\|\,\bar{q}_{n}\|_{0,\Omega}^{2}, \\ |\bar{\mathbf{v}}_{n}|_{1,\Omega}&\leqslant\frac{1}{ \beta}\,\|\,\bar{q}_{n}\|_{0,\Omega}.\end{aligned}\right.\]

Let \(\bar{\mathbf{v}}_{n}\!\) be the function of \(X_{n}\!\) defined by:

\[\bar{\mathbf{v}}_{n|\Omega_{r}}=\bar{\mathbf{v}}_{r}.\]

We propose to associate with \(q_{n}\) the function \(\mathbf{v}_{n}\!\in\!X_{n}\!\):

\[\mathbf{v}_{n}=\bar{\mathbf{v}}_{n}+\alpha\bar{\mathbf{v}}_{n},\]

for some \(\alpha\!>\!0\) and we hope to adjust the parameter \(\alpha\) so that the pair \((\mathbf{v}_{n},q_{n})\) verifies the inf-sup condition.

Let us evaluate \((q_{n},\mathrm{div}\,\mathbf{v}_{n})\). We have:

\[(q_{n},\mathrm{div}\,\mathbf{v}_{n})=(\bar{q}_{n},\mathrm{div}\,\bar{\mathbf{ v}}_{n})+(\bar{q}_{n},\mathrm{div}\,\bar{\mathbf{v}}_{n})+\alpha(\bar{q}_{n}, \mathrm{div}\,\bar{\mathbf{v}}_{n})+\alpha(\bar{q}_{n},\mathrm{div}\,\bar{ \mathbf{v}}_{n}).\]

Now,

\[(\bar{q}_{n},\mathrm{div}\,\bar{\mathbf{v}}_{n}) =0\quad\text{since $\bar{\mathbf{v}}_{r}$ vanishes on $\Gamma_{r}$},\] \[(\bar{q}_{n},\mathrm{div}\,\bar{\mathbf{v}}_{n}) =\|\,\bar{q}_{n}\|_{0,\Omega}^{2},\] \[(\bar{q}_{n},\mathrm{div}\,\bar{\mathbf{v}}_{n}) =\|\,\bar{q}_{n}\|_{0,\Omega}^{2},\]

by virtue of (1.58) and (1.59) respectively and

\[(\bar{q}_{n},\mathrm{div}\,\bar{\mathbf{v}}_{n})\leqslant\frac{\sqrt{N}}{ \bar{\beta}}\,\|\,\bar{q}_{n}\|_{0,\Omega}\|\,\bar{q}_{n}\|_{0,\Omega}\quad \text{in view of (\ref{eq:1.59}).}\]

Hence, collecting these results we obtain:

\[(q_{n},\mathrm{div}\,\mathbf{v}_{n})\geqslant\|\,\bar{q}_{n}\|_{0,\Omega}^{2} +\alpha\|\,\bar{q}_{n}\|_{0,\Omega}^{2}-\alpha\frac{\sqrt{N}}{\bar{\beta}}\,\| \,\bar{q}_{n}\|_{0,\Omega}\|\,\bar{q}_{n}\|_{0,\Omega}.\]

Then, the inequality:

\[\|\,\bar{q}_{n}\|_{0,\Omega}\|\,\bar{q}_{n}\|_{0,\Omega}\leqslant\varepsilon\, \|\,\bar{q}_{n}\|_{0,\Omega}^{2}+\frac{1}{4\varepsilon}\,\|\,\bar{q}_{n}\|_{0, \Omega}^{2}\]

yields

\[(q_{n},\mathrm{div}\,\mathbf{v}_{n})\geqslant\!\left(1-\frac{\alpha \varepsilon}{\sqrt{N}}{\bar{\beta}}\right)\!\|\,\bar{q}_{n}\|_{0,\Omega}^{2}+ \left(1-\frac{\sqrt{N}}{4\varepsilon\bar{\beta}}\right)\!\|\,\bar{q}_{n}\|_{0, \Omega}^{2}\]
