\[\begin{cases}\mathbf{w}(a_{i})\text{ on the three vertices $a_{i}$ of $\kappa$,}\\ \mathbf{w}(a_{ij})\text{ on the midpoint $a_{ij}$ of the segment $[a_{i},a_{j}]$, $1\leqslant i<j \leqslant 3$,}\end{cases}\] (2.2) \[\mathbf{w}(a_{\kappa}),\]

or

\[\int_{\kappa}\mathbf{w}\,dx.\]

Note that all degrees of freedom (2.19) are defined _separately_ for each component of \(\mathbf{w}\). The next lemma checks their unisolvence.

Lemma 2.3: _A polynomial \(\mathbf{p}\) of \(\mathcal{P}_{l}(\kappa)\) is uniquely determined by the \(l(l+5)\) degrees of freedom (2.19a) (2.19b) or (2.19a) (2.19c). In addition, the restriction of \(\mathbf{p}\) to any side \(f_{i}\) of \(\kappa\) depends only upon the degrees of freedom defined on that side._

Proof: As the dimension of \(\mathcal{P}_{l}(\kappa)\) is \(l(l+5)\) it suffices to show that \(\mathbf{p}=\mathbf{0}\) when all its degrees of freedom vanish.

Let \(p\) be any component of \(\mathbf{p}\). If its degrees of freedom are zero on any side \(f_{i}\) of \(\kappa\), we readily obtain that \(p\) vanishes identically on that side because \(p\) reduces to a polynomial of degree \(l\) on each side of \(\kappa\). Hence, if the degrees of freedom (2.19a) are zero, we have

\[p=\lambda_{1}\lambda_{2}\lambda_{3}q\quad\text{with $q$ in $P_{l-2}$.}\]

Then, if all interior degrees of freedom vanish we find in the case of (2.19c):

\[\int_{\kappa}\lambda_{1}\lambda_{2}\lambda_{3}q^{2}\,dx=0\]

and in the case of (2.19b):

\[\partial^{k}q(a_{\kappa})/\partial x_{1}^{i}\partial x_{2}^{k-i}=0\quad\quad 0 \leqslant i\leqslant k,\quad\ 0\leqslant k\leqslant l-2.\]

Each of these equalities implies that \(q=0\) in \(\kappa\). 

Thus (2.19) yields two interpolation operators:

\(r_{\kappa}\mathbf{v}(\text{resp. $r_{\kappa}^{\prime}\mathbf{v}$})\): the unique polynomial of \(\mathcal{P}_{l}(\kappa)\) that has the same degrees of freedom (2.19a) (2.19c) (resp. (2.19a) (2.19b)) as the function \(\mathbf{v}\) on \(\kappa\). Then we define \(r_{h}\mathbf{v}|_{\kappa}=r_{\kappa}\mathbf{v}\)  \(\forall\kappa\in\mathcal{T}_{h}\)

and similarly for \(r_{h}^{\prime}\). Lemma 2.3 implies that:

\[r_{h}^{\prime}\!\in\!\mathcal{L}(\mathcal{C}^{l-2}(\bar{\bar{\bar{Q}}})^{2}; \,W_{h})\cap\mathcal{L}([\mathcal{C}^{l-2}(\bar{\bar{\bar{Q}}})\cap H_{0}^{1} (\Omega)]^{2};\,X_{h}),\]

\[r_{h}\!\in\!\mathcal{L}(\mathcal{C}^{0}(\bar{\bar{Q}})^{2};\,W_{h})\cap \mathcal{L}([\mathcal{C}^{0}(\bar{\bar{Q}})\cap H_{0}^{1}(\Omega)]^{2};\,X_{h}).\]

Furthermore, it is easy to check that both operators \(r_{\kappa}\) and \(r_{\kappa}^{\prime}\) are _invariant under
