(2.71) \[|\psi-\psi_{h}|_{1,s,\Omega}\leqslant C_{s}h^{k-1+2s}|\psi|_{k+1,\Omega}.\]

This estimate is a routine consequence of (2.69), Lemma A.7 and (A.21a).

The last three results call for a number of comments. The first obvious remark is that the approach of this section provides sharper estimates than the preceding section. Indeed, as long as \(l\geqslant 2\) and the stream function \(\psi\) belongs to \(H^{l+1}(\Omega)\), (2.70) provides an optimal error bound for \(|\psi-\psi_{h}|_{1,\Omega}\). Unfortunately, this section brings no improvement on the error estimate for the vorticity \(\omega\). And furthermore, it fails just as much to establish the convergence when piecewise linear elements are used (i.e. \(l=1\)). In this case, the loss of accuracy arises from the approximation error in the norm \(\|\,.\,\|_{2,\,h}\): clearly, this norm is not adapted to piecewise linear elements.

Finally, it is worth pointing out that, in this section, there is little hope of discarding the convexity hypothesis on \(\Omega\) because Lemma 2.12 requires that \(\phi(h)\) belong necessarily to \(H^{2}(\Omega)\).

_Remark 2.9_.: Owing to the trace terms in \(\|\,.\,\|_{0,\,h}\) and \(\|\,.\,\|_{2,\,h}\), (2.67) yields the additional estimates:

\[\|\omega-\omega_{h}\|_{0,\,\Gamma_{h}}\leqslant Ch^{k-3/2}|\psi|_{k+1,\Omega},\]

\[\|\,S(\partial\psi_{h}/\partial n)\|_{0,\,\Gamma_{h}}\leqslant Ch^{k-1/2}|\psi |_{k+1,\Omega},\]

for \(1\leqslant k\leqslant l\), provided of course that \(\psi\in H^{k+1}(\Omega)\). This last inequality shows that the jump of \(\partial\psi_{h}/\partial n\) across interelement boundaries (as well as \(\partial\psi_{h}/\partial n\) on \(\Gamma\)) tends to zero like \(h^{k-1/2}\).

## 3 Further Topics on the "Stream Function-Vorticity-Pressure" Scheme

This paragraph gives further developments on the "stream function-vorticity-pressure" method for the two-dimensional Stokes problem. In particular it derives better error estimates for \(\psi_{h}\), \(\omega_{h}\) and \(p_{h}\) in the general case. These can also be improved by the use of special meshes.

### Refinement of the Error Analysis

We place ourselves in the situation of Section 2.2 and, unless otherwise specified, we use the same notations and concrete spaces \(\Theta_{h}=M_{h}\), \(\Phi_{h}\) and \(Q_{h}\) defined by (2.39). As mentioned at the section's end, the error bounds given in Theorem 2.8 are quite poor because our estimate for the approximation error in \(V_{h}\) is too coarse. Now, we are going to concentrate on this estimate. The following lemma establishes an analogue of (II.1.16) in abstract situations.
