Therefore an easy manipulation of terms and (5.17) yield:

\[(\mathbf{g},\mathbf{curl}(\psi-\psi_{h}))= (v-v_{h},\omega-\omega_{h})+\tilde{b}(u-u_{h},v-\theta_{h})+\tilde{b }(z-z_{h},\omega-\mu_{h})\] (5.47) \[+\ \dot{\lambda}\{a_{1}(u-u_{h};u,\mathbf{z}-\mathbf{z}_{h})+ \tilde{a}^{u_{h}}(u_{h};u-u_{h},\mathbf{z}-\mathbf{z}_{h})\] \[-a_{1}(u-u_{h};z,\mathbf{u}-\mathbf{u}_{h})\}.\]

But, the delicate step in this proof is an adequate estimate of the \(\tilde{a}(\cdot;\cdot,\ .)\) term in the factor multiplying \(\lambda\). Indeed, if we apply Lemma 5.2, we get:

\[|\tilde{a}^{u_{h}}(u_{h};u-u_{h},\mathbf{z}-\mathbf{z}_{h})|\leqslant Ch^{1/2} |\psi_{h}|_{1,\,4,\,\Omega}[\psi-\psi_{h}]_{2}[\chi-\chi_{h}]_{2}.\]

And when \(l=1\), this upper bound is useless because \(\inf_{x_{h}}[\chi-\chi_{h}]_{2}=O(1)\).

Instead, it is better to take advantage of the fact that \(\chi\in H^{3}(\Omega)\) and replace the previous bound by:

\[|\tilde{a}^{u_{h}}(u_{h};u-u_{h},\mathbf{z}-\mathbf{z}_{h})| \leqslant C_{1}|\psi_{h}|_{1,\,4,\,\Omega}[\psi-\psi_{h}]_{2}\] \[\times\bigg{\{}|\chi-\chi_{h}|_{1,\,4,\,\Omega}+h\bigg{(}\sum \limits_{\kappa\in\mathcal{T}_{h}}|\chi-\chi_{h}|_{2,\,4,\,\kappa}^{4}\bigg{)} ^{1/4}\bigg{\}}.\]

Hence, if we choose \(z_{h}=\pi_{h}z\in V_{h}\) defined by (5.40), the fact that \(\chi_{h}=\hat{P_{h}}\chi\) implies that

\[|\tilde{a}^{u_{h}}(u_{h};u-u_{h},\mathbf{z}-\mathbf{z}_{h})|\leqslant C_{2}h| \psi_{h}|_{1,\,4,\,\Omega}[\psi-\psi_{h}]_{2}\,\|\chi\|_{2,\,4,\,\Omega}.\]

Finally, observe that

\[[\psi-\psi_{h}]_{2} \leqslant[\psi-\hat{P_{h}}\psi]_{2}+[\hat{P_{h}}\psi-\psi_{h}]_{2}\] (5.48) \[\leqslant C_{3}\,h^{1-1}\,\|\psi\|_{l+1,\,\Omega}+C_{4}|\pi_{h}u- u_{h}|\]

by virtue of (5.26), (5.21) and (5.40). This gives an upper bound of the form:

\[|\tilde{a}^{u_{h}}(u_{h};u-u_{h},\mathbf{z}-\mathbf{z}_{h})|\leqslant C_{5}( \|\psi\|_{2,\,\Omega})\,\|\chi\|_{2,\,4,\,\Omega}(h^{1}\|\psi\|_{l+1,\,\Omega} +h|\pi_{h}u-u_{h}|).\]

The other terms in (5.47) are easily estimated and the proof ends exactly like that of Theorem 4.5. 

### Approximating the Pressure with the Upwind Scheme

We have seen in Section 4.3 that the pressure term \(p\) underlying the Navier-Stokes system (5.7) is the solution of the problem:

_Find \(p\in W^{1,\,r}(\Omega)\cap L^{2}_{0}(\Omega)\) such that_:

\[(\mathbf{grad}\,p,\mathbf{grad}\,q)=\bigg{(}\mathbf{f}-v\,\mathbf{curl}\, \omega-\sum\limits_{j=1}^{2}u_{j}\partial\mathbf{u}/\partial x_{j},\mathbf{ grad}\,q\bigg{)}\ \ \ \ \ \forall q\in W^{1,\,s}(\Omega).\] (5.49)

Likewise, to recover the pressure \(p_{h}\) associated with the upwind scheme (5.18), we introduce the space \(Q_{h}\) defined by (4.34):
