where the coordinates \(v\) and \(\mu_{k}\) depend upon \(\hat{\phi}\), \((\hat{x}_{1},\hat{x}_{2})\) and the interpolation points \((\alpha_{i},\alpha_{j})\). Thus we can write:

\[(\hat{\phi}-\hat{I}\hat{\phi})(\hat{x}_{1},\hat{x}_{2}) =\big{[}1/(l+1)!\big{]}\Bigg{[}\Bigg{(}\sum_{k=0}^{l}L_{k}(\hat{x} _{1})\partial^{l+1}\hat{\phi}(\alpha_{k},\mu_{k})/\partial\hat{x}_{2}^{l+1} \Bigg{)}\prod_{p=0}^{l}(\hat{x}_{2}-\alpha_{p})\] \[\quad+\,\partial^{l+1}\hat{\phi}(v,\hat{x}_{2})/\partial\hat{x}_{ 1}^{l+1}\prod_{p=0}^{l}(\hat{x}_{1}-\alpha_{p})\Bigg{]}.\]

By comparing the right-hand side of this expression with \(R(\hat{\phi})\), and using the fact that

\[\sum_{k=0}^{l}L_{k}(\hat{x})\equiv 1\quad\text{on }[0,1],\]

we readily derive that the mapping \(\hat{\phi}\to\hat{\phi}-\hat{I}\hat{\phi}-R(\hat{\phi})\) vanishes on \(P_{l+1}\). Since this mapping belongs to \(\mathcal{L}(H^{l+2}(\kappa);H^{l+2}(\kappa))\), (3.20) follows from Corollary A.1. 

The next result is obtained by a simple rearrangement of terms.

**Lemma 3.6**.: _The following identity holds for all \(\phi\) and \(\mu\in H^{1}(\kappa)\):_

\[\begin{split}\int_{\kappa}\operatorname{\mathbf{grad}}\phi\cdot \operatorname{\mathbf{grad}}\mu\,dx&=\int_{\kappa}(1/J_{F}) \big{[}\|\partial F_{\kappa}/\partial\hat{x}_{2}\|^{2}(\partial\hat{\phi}/ \partial\hat{x}_{1})(\partial\hat{\mu}/\partial\hat{x}_{1})\\ &\quad+\,\|\partial F_{\kappa}/\partial\hat{x}_{1}\|^{2}( \partial\hat{\phi}/\partial\hat{x}_{2})(\partial\hat{\mu}/\partial\hat{x}_{2}) \big{]}\,d\hat{x}\\ &\quad-\int_{\hat{\kappa}}(1/J_{F})(\partial F_{\kappa}/\partial \hat{x}_{1})\cdot(\partial F_{\kappa}/\partial\hat{x}_{2})\big{[}(\partial\hat {\phi}/\partial\hat{x}_{1})(\partial\hat{\mu}/\partial\hat{x}_{2})\\ &\quad+(\partial\hat{\phi}/\partial\hat{x}_{2})(\partial\hat{\mu} /\partial\hat{x}_{1})\big{]}\,d\hat{x},\end{split}\] (3.21)

_where \(\|\,.\|\) denotes the Euclidean norm of \(\mathbb{R}^{2}\) and \(J_{F}\) the Jacobian of the bilinear mapping \(F_{\kappa}\)._

In order to evaluate properly the right-hand side of (3.21), it is convenient to shift out of the integrals the factors involving \(J_{F}\) and \(\partial F_{\kappa}/\partial\hat{x}_{i}\). As these two quantities are not constant, we must therefore assume that their derivatives are "small". To be specific, we make the following hypothesis:

_there exists a constant \(C>0\)_, _independent of \(h\) and \(\kappa\)_, _such that_

\[\|\partial^{2}F_{\kappa}/\partial\hat{x}_{1}\partial\hat{x}_{2}\|\leqslant Ch _{\kappa}^{2}\quad\quad\forall\kappa\in\mathcal{T}_{h}.\] (3.22)

Note that \(\partial^{2}F_{\kappa}/\partial\hat{x}_{1}\partial\hat{x}_{2}=0\) when \(\kappa\) is a parallelogram; in fact, (3.22) holds only if \(\kappa\) is almost a parallelogram. It easy to prove that when (3.22) holds, the full seminorm \(|\,.|_{k,\,\hat{\kappa}}\) and \([\,.\,]_{k,\,\hat{\kappa}}\) (cf. formula (A.41)) have upper bounds of the same order. More precisely, we have:

**Lemma 3.7**.: _Let \(\kappa\) be a convex quadrilateral that satisfies (3.22). Then for each integer \(k\geqslant 1\) there exists a constant \(C>0\)_, _independent of \(h\) and \(\kappa,\) such that:_
