_Stokes problem (2.1) satisfy_

\[\mathbf{f}\in L^{2}(\Omega)^{2},\ \ \ \ \ \ \psi\in H^{k+1}(\Omega),\ \ \ \ \ \ \ \Delta\psi\in H^{k}(\Omega)\]

_for some real \(k\in[1,l],\) then the solution \((\omega_{h},\psi_{h})\) of Problem (2.48) satisfies the error estimate_:

\[\|\omega-\omega_{h}\|_{0,h}+\|\psi-\psi_{h}\|_{2,h}\leqslant C(h^{k}|\Delta \psi|_{k,\Omega}+h^{k-1}|\psi|_{k+1,\Omega}).\] (2.67)

_The best estimate is obtained when \(\psi\in H^{l+1}(\Omega)\)_:

\[\|\omega-\omega_{h}\|_{0,h}+\|\psi-\psi_{h}\|_{2,h}\leqslant Ch^{l-1}|\psi|_{l +1,\Omega}.\] (2.68)

Finally, a simple duality argument permits to sharpen the error bound for \(\psi\) in the \(H^{1}\)-norm.

**Theorem 2.10**.: _Under the assumptions of Theorem 2.9 we have_:

\[|\psi-\psi_{h}|_{1,\Omega}\leqslant Ch^{k}|\psi|_{k+1,\Omega}\] (2.69)

_provided the stream function \(\psi\in H^{k+1}(\Omega)\) for a real \(k\in[2,l].\) When \(\psi\in H^{l+1}(\Omega),\) the best error bound is_:

\[|\psi-\psi_{h}|_{1,\Omega}\leqslant Ch^{l}|\psi|_{l+1,\Omega},\ \ \ \ \ l\geqslant 2.\] (2.70)

_Proof_. For \(\mathbf{g}\in L^{2}(\Omega)^{2},\) consider the auxiliary Stokes problem:

\[a_{h}(\lambda_{g},\mu)+b_{h}(\mu,\phi_{g}) =0\ \ \ \ \ \ \forall\mu\in H^{1}(\Omega),\] \[b_{h}(\lambda_{g},\chi) =-(\mathbf{g},\mathbf{curl}\,\chi)\ \ \ \ \ \ \forall\chi\in\widetilde{\mathcal{P}}.\]

Because of the convexity of \(\Omega,\) the unique solution \((\lambda_{g},\phi_{g})\) of this problem belongs to \(H^{1}(\Omega)\times H^{3}(\Omega)\) and (cf. Remark I.5.6):

\[\|\phi_{g}\|_{3,\Omega}+\|\lambda_{g}\|_{1,\Omega}\leqslant C_{1}\|\mathbf{g }\|_{0,\Omega}.\]

From this and Problem (2.48), we easily derive the following equalities:

\[(\mathbf{g},\mathbf{curl}(\psi-\psi_{h})) =-b_{h}(\lambda_{g}-\lambda_{h},\psi-\psi_{h})+a_{h}(\omega- \omega_{h},\lambda_{h})\] \[=b_{h}(\lambda_{h}-\lambda_{g},\psi-\psi_{h})+a_{h}(\omega- \omega_{h},\lambda_{h}-\lambda_{g})\] \[\quad-b_{h}(\omega-\omega_{h},\phi_{g}-\phi_{h})\ \ \ \ \ \forall\lambda_{h}\in\Theta_{h},\ \ \ \ \ \forall\phi_{h}\in\Phi_{h}.\]

Then (2.69) follows from Theorem 2.9 and Lemmas 2.10 and 2.11. 

As an interesting consequence, we have the following estimate for \(\psi\) in the \(W^{1,s}\)-norm.

**Corollary 2.3**.: _Suppose the hypotheses of Theorem 2.9 hold. If the stream function \(\psi\) belongs to \(H^{k+1}(\Omega)\) for a real \(k\in[2,l],\) then for each real \(s\geqslant 2\) there exists a constant \(C_{s},\) independent of \(h,\) such that:_
