of nonsingular solutions of (6.40). As \(F\) is a \(\mathscr{C}^{p}\)-mapping \((p\geqslant 2)\), so is the mapping \(u(\lambda)\) and we can differentiate both sides of (6.40):

(6.54) \[D_{u}F(\lambda,u(\lambda))\cdot(du(\lambda)/d\lambda)+D_{\lambda}F(\lambda,u( \lambda))=0\ \ \ \ \ \forall\lambda\in\Lambda,\]

i.e. we find a first order differential equation of the form

(6.55) \[du(\lambda)/d\lambda=-\phi(\lambda)\]

where

\[\phi(\lambda)=[D_{u}F(\lambda,u(\lambda))]^{-1}D_{\lambda}F(\lambda,u(\lambda )).\]

The simplest way to solve (6.55) is to use the one-step, explicit, Euler's method; this induces us to choose

(6.56) \[u^{0}(\lambda)=u(\lambda-\Delta\lambda)-\phi(\lambda-\Delta\lambda)\cdot \Delta\lambda.\]

In other words \(u^{0}(\lambda)\) is defined by

(6.57) \[D_{u}F(\lambda-\Delta\lambda,u(\lambda-\Delta\lambda))\cdot(u^{0 }(\lambda)-u(\lambda-\Delta\lambda))\] \[=-D_{\lambda}F(\lambda-\Delta\lambda,u(\lambda-\Delta\lambda)) \cdot\Delta\lambda.\]

Let us estimate the error \(u(\lambda)-u^{0}(\lambda)\). From (6.55) we infer that:

\[u(\lambda)=u(\lambda-\Delta\lambda)-\int_{\lambda-\Delta\lambda}^{\lambda}\phi (\mu)\,d\mu;\]

subtracting (6.56) we obtain

\[u(\lambda)-u^{0}(\lambda) =-\!\!\left[\int_{\lambda-\Delta\lambda}^{\lambda}\phi(\mu)\,d\mu -\phi(\lambda-\Delta\lambda)\cdot\Delta\lambda\right]\] \[=-\!\!\int_{\lambda-\Delta\lambda}^{\lambda}\phi^{\prime}(\theta_ {\mu})\cdot(\mu-\lambda+\Delta\lambda)\,d\mu.\]

Hence

\[\|u(\lambda)-u^{0}(\lambda)\|_{X}\leqslant[(\Delta\lambda)^{2}/2]\mathop{ \mathrm{Max}}_{\theta\in(\lambda-\Delta\lambda,\,\lambda)}\|\phi^{\prime}( \theta)\|_{X}.\]

Thus \(\|u(\lambda)-u^{0}(\lambda)\|_{X}\) is \(O((\Delta\lambda)^{2})\) and if \(\Delta\lambda\) is small enough, \(u^{0}(\lambda)\) defined by (6.56) is an adequate starting value for Newton's algorithm.

As an example, let us explicit formula (6.57) for the Navier-Stokes equation (6.51). To simplify, we set

\[\delta u(\lambda)=u^{0}(\lambda)-u(\lambda-\Delta\lambda).\]

Then (6.57) amounts to

\[\delta u(\lambda)=-T[D_{u}G(\lambda-\Delta\lambda,u(\lambda-\Delta\lambda)) \cdot\delta u(\lambda)+D_{\lambda}G(\lambda-\Delta\lambda,u(\lambda-\Delta \lambda))\cdot\Delta\lambda],\]

or equivalently
