(2.20) \[\left\{\begin{aligned} \rho_{\varepsilon}*\tilde{\mathbf{u}}\in \mathcal{D}(\mathbb{R}^{N})^{N},\\ \lim_{\varepsilon\to 0}(\rho_{\varepsilon}*\tilde{\mathbf{u}})= \tilde{\mathbf{u}}\quad\text{in }L^{2}(\mathbb{R}^{N})^{N},\\ \mathbf{curl}(\rho_{\varepsilon}*\tilde{\mathbf{u}})=\rho_{ \varepsilon}*\mathbf{curl}\,\tilde{\mathbf{u}}.\end{aligned}\right.\]

But if \(\varepsilon\) is sufficiently small,

\[\bigcup_{x\in\Omega_{m}}B(x;\varepsilon)\subset\Omega,\]

where \(B(x;\varepsilon)\) denotes the ball with center \(x\) and radius \(\varepsilon\). Therefore

\[\mathbf{curl}(\rho_{\varepsilon}*\tilde{\mathbf{u}})=\mathbf{0}\quad\text{ in }\Omega_{m}.\]

Hence, it follows from Stokes' Theorem that there exists a smooth function \(p_{\varepsilon}\) (in \(H^{1}(\Omega_{m})\) at least) such.that

\[\rho_{\varepsilon}*\tilde{\mathbf{u}}=\mathbf{grad}\,p_{\varepsilon}\quad \text{in }\Omega_{m}.\]

Moreover, (2.20) implies that there exists \(p_{m}\in H^{1}(\Omega_{m})\) such that

\[\lim_{\varepsilon\to 0}p_{\varepsilon}=p_{m}\quad\text{in }H^{1}(\Omega_{m})/ \mathbb{R}\]

and

\[\mathbf{u}=\mathbf{grad}\,p_{m}\quad\text{in }\Omega_{m}.\]

The proof then ends like that of Theorem 2.3. 

With Theorem 2.7, this gives us another characterization of \(H^{\perp}\):

**Corollary 2.9**.: _If \(\Omega\) is like in Theorem 2.9, the following identity holds in \(L^{2}(\Omega)^{N}\):_

\[H^{\perp}=\operatorname{Ker}(\mathbf{curl})=\{\mathbf{v}\in L^{2}(\Omega)^{N} ;\,\mathbf{curl}\,\mathbf{v}=\mathbf{0}\}.\]

_Remark 2.2_.: As a consequence of Corollary 2.9, if \(\mathbf{u}\in H\) and \(\mathbf{curl}\,\mathbf{u}=\mathbf{0}\) then \(\mathbf{u}=\mathbf{0}\), provided of course that \(\Omega\) is bounded and simply-connected.

Just like we defined the space \(H(\operatorname{div};\Omega)\), we introduce the space \(H(\mathbf{curl};\Omega)\):

\[H(\mathbf{curl};\Omega)=\{\mathbf{v}\in L^{2}(\Omega)^{N};\,\mathbf{curl}\, \mathbf{v}\in L^{2}(\Omega)^{N}\},\]

a Hilbert space for the norm

\[\|\,\mathbf{v}\|_{H(\mathbf{curl};\Omega)}=\{\,\|\,\mathbf{v}\|_{0,\Omega}^{ 2}+\,\|\,\mathbf{curl}\,\mathbf{v}\|_{0,\Omega}^{2}\}^{1/2};\]

and we set

\[H_{0}(\mathbf{curl};\Omega)=\overline{\mathcal{D}(\Omega)^{N}\,H(\mathbf{curl };\Omega)}.\]

For these spaces, we propose to establish the analogues of Theorems 2.4, 2.5 and 2.6. We begin with two preliminary lemmas.
