\[\|u-u_{h}\|_{\bar{x}}+\|\,\dot{\lambda}-\dot{\lambda}_{h}\|_{M}\leqslant C\,\biggl{\{} (1+K(h))\inf_{v_{h}\in X_{h}}\|u-v_{h}\|_{\bar{x}}+\inf_{\mu_{h}\in M_{h}}\|\, \dot{\lambda}-\mu_{h}\|_{\bar{x}}\biggr{\}}.\]

Proof.: Clearly (1.27) is an immediate consequence of (1.26) and Theorem 1.2.

Next, the proof of (1.26) follows very closely the lines of Theorem II.1.1. Indeed, in view of (1.25) the inf-sup condition (1.21) becomes:

\[\sup_{v_{h}\in X_{h}}\frac{\tilde{b}(v_{h},\mu_{h})}{\|v_{h}\|_{\bar{x}}} \geqslant(\beta*/K(h))\,\|\,\mu_{h}\|_{\bar{\alpha}}\ \ \ \ \ \forall\mu_{h}\in M_{h}.\] (1.28)

Therefore, applying the argument of Theorem II.1.1 with the constant \(\beta*/K(h)\) instead of \(\beta*\), we obtain directly (1.26). 

We shall see in the examples of the next paragraph that \(K(h)\) usually becomes infinite when the dimension of \(M_{h}\) tends to infinity. But again the techniques developed in SS 3 will show in some cases how to estimate sharply the approximation error in \(V_{h}(\chi)\) without introducing the factor \(K(h)\).

## SS 2 The "Stream Function-Vorticity-Pressure" Method for the Stokes Problem in Two Dimensions

The widespread "stream function-vorticity-pressure" formulation of the two-dimensional Stokes system of equations is based on the two identities:

\[\operatorname{\mathbf{curl}}(\operatorname{curl}\mathbf{u})=-\,\Delta\, \mathbf{u}+\operatorname{\mathbf{grad}}(\operatorname{div}\mathbf{u}),\ \ \ \ \operatorname{curl}(\operatorname{\mathbf{curl}}\phi)=-\,\Delta\phi.\]

Thus the Stokes problem

\[\left.\begin{array}[]{r}-\,v\,\Delta\,\mathbf{u}+\operatorname{\mathbf{grad}} \,p=\mathbf{f}\\ \operatorname{div}\mathbf{v}=0\end{array}\right\}\ \ \mathbf{in}\ \Omega,\]

\[\left.\begin{array}[]{r}\mathbf{u}\right|_{\Gamma}=\mathbf{0}\end{array}\]

can be expressed either as:

\[\left.\begin{array}[]{r}\operatorname{curl}\mathbf{u}=\omega,\ \ \ \ \operatorname{div}\mathbf{u}=0\\ \,v\,\operatorname{\mathbf{curl}}\omega+\operatorname{\mathbf{grad}}\,p= \mathbf{f}\end{array}\right\}\ \ \mathbf{in}\ \Omega,\]

\[\left.\begin{array}[]{r}\mathbf{u}=\operatorname{\mathbf{curl}}\phi,\ \ \ \ \omega=-\,\Delta\phi\\ \,v\,\operatorname{\mathbf{curl}}\omega+\operatorname{\mathbf{grad}}\,p= \mathbf{f}\end{array}\right\}\ \ \mathbf{in}\ \Omega,\]

\[\left.\begin{array}[]{r}\mathbf{curl}\,\phi\right|_{\Gamma}=\mathbf{0}.\]
