_where_

\[\tilde{\alpha}_{r}=\inf_{v\in X}[a_{r}(v,v)/\|\,Bv\,\|_{M^{\prime}}^{2}.].\]

_Proof_. We set:

\[e^{m}=u^{m}-u,\ \ \ \ \ v^{m}=\lambda^{m}-\lambda.\]

Then (4.1), (4.2) and (4.56) yield:

\[a_{r}(e^{m},v)+b(v,v^{m})=0\ \ \ \ \ \forall v\in X,\]

\[-c(v^{m+1}-v^{m},\mu)+\rho^{m}b(e^{m},\mu)=0\ \ \ \ \ \forall\mu\in M.\]

By taking \(v=e^{m}\) and \(\mu=v^{m+1}\) in the above equations, we get

\[c(v^{m+1}-v^{m},v^{m+1})=\rho^{m}b(e^{m},v^{m+1})=\rho^{m}\{b(e^{m},v^{m+1}-v^ {m})-a_{r}(e^{m},e^{m})\}.\]

As the bilinear form \(c(.,.)\) is symmetric, we may write

\[2c(v^{m+1}-v^{m},v^{m+1})=c(v^{m+1})-c(v^{m})+c(v^{m+1}-v^{m}),\]

where \(c(\mu)\) stands for \(c(\mu,\mu)\). Therefore, using (4.25), we obtain:

\[c(v^{m+1})-c(v^{m})+\gamma\|\,v^{m+1}-v^{m}\|_{M}^{2}+2\rho^{m}a_{r}(e^{m},e^{ m})\]

\[\leq 2\rho^{m}\|\,Be^{m}\|_{M^{\prime}}\|\,v^{m+1}-v^{m}\|_{M}.\]

By virtue of the inequality \(2ab\leq\gamma a^{2}+(1/\gamma)b^{2}\) and (4.46') we find

\[2\rho^{m}\|\,Be^{m}\|_{M^{\prime}}\|\,v^{m+1}-v^{m}\|_{M}\leq\gamma\|\,v^{m+1} -v^{m}\|_{M}^{2}+(\rho^{m})^{2}a_{r}(e^{m},e^{m})/(\tilde{\alpha}_{r}\gamma).\]

Hence, applying (4.46), this yields:

\[c(v^{m+1})-c(v^{m})+\rho^{m}\{2-\rho^{m}/(\tilde{\alpha}_{r}\gamma)\}\alpha_{ r}\|\,e^{m}\|_{X}^{2}\leq 0.\]

Since \(\rho^{m}\) satisfies (4.63), there exists a constant \(\delta>0\), independent of \(m\), such that

\[2\tilde{\alpha}_{r}-\rho^{m}/\gamma\geq\delta.\]

Thus, we obtain:

\[c(v^{m+1})-c(v^{m})+\rho^{m}\delta(\alpha_{r}/\tilde{\alpha}_{r})\|\,e^{m}\|_ {X}^{2}\leq 0.\]

On the other hand, the inf-sup condition (4.9) gives:

\[\|\,v^{m}\|_{M}\leq(1/\beta)\sup_{v\in X}\frac{b(v,v^{m})}{\|\,v\|_{X}}=(1/ \beta)\sup_{v\in X}\frac{a_{r}(e^{m},v)}{\|\,v\|_{X}}\leq(\|\,a_{r}\|/\beta)\, \|\,e^{m}\|_{X},\]

where \(\|\,a_{r}\|\) denotes the norm of the form \(a_{r}(.,.)\). Therefore,

\[\|\,e^{m}\|_{X}^{2}\geq\beta^{2}c(v^{m})/(\|\,c\|\,\|\,a_{r}\|^{2})\]

and (4.64) implies:

\[c(v^{m+1})\leq c(v^{m})\{1-(\alpha_{r}/\tilde{\alpha}_{r})(\rho^{m}\delta \beta^{2})/(\|\,c\|\,\|\,a_{r}\|^{2})\}.\]
