Now, we are looking for a velocity vector \(\mathbf{w}\) that is compatible with a constant pressure in \(\kappa\). Keeping in mind the material of Section 2.1 it is likely that \(\mathbf{w}\) will belong to a space larger than \(Q_{1}(\kappa)\), but that its tangential components on each side of \(\kappa\) will be affine. (The pair \((Q_{1}(\kappa),P_{0})\) will in fact be the object of Section 3.3). As an example, the polynomial

\[\hat{q}_{1}=\hat{x}_{2}\hat{x}_{3}\hat{x}_{4}\]

vanishes on the sides \(\hat{f}_{2},\hat{f}_{3}\) and \(\hat{f}_{4}\) of the reference square \(\hat{\kappa}\). Therefore the function

\[\mathbf{p}_{1}=\mathbf{n}_{1}(\hat{q}_{1}\circ F_{\kappa}^{-1})\]

has zero tangential components on the sides of \(\kappa\). Generalizing this remark, we set

\[\hat{q}_{2}=\hat{x}_{3}\hat{x}_{4}\hat{x}_{1},\hskip 14.226378pt\hat{q}_{3}= \hat{x}_{4}\hat{x}_{1}\hat{x}_{2},\hskip 14.226378pt\hat{q}_{4}=\hat{x}_{1} \hat{x}_{2}\hat{x}_{3},\] (3.1) \[\mathbf{p}_{i}=\mathbf{n}_{i}(\hat{q}_{i}\circ F_{\kappa}^{-1})\]

and we take the velocities \(\mathbf{w}\) in the space (of dimension 12):

\[\mathcal{Q}_{1}(\kappa)=Q_{1}(\kappa)^{2}\oplus\operatorname{span}\{\mathbf{ p}_{1},\mathbf{p}_{2},\mathbf{p}_{3},\mathbf{p}_{4}\}\subset Q_{2}(\kappa)^{2}.\] (3.2)

As will be seen in the next lemma, the degrees of freedom naturally attached to this space are the values of \(\mathbf{w}\) at the vertices \(a_{i}\) and the flux of \(\mathbf{w}\) through each side \(f_{i}\) of \(\kappa\).

**Lemma 3.1**.: _A polynomial \(\mathbf{p}\) of \(\mathcal{Q}_{1}(\kappa)\) is uniquely determined by the \(12\) quantities:_

\[\left\{\begin{aligned} \mathbf{p}(a_{i})& 1\leqslant i \leqslant 4,\\ \int_{f_{i}}\mathbf{p}\mathbin{\boldsymbol{\cdot}}\mathbf{n}_{i} \,ds& 1\leqslant i\leqslant 4.\end{aligned}\right.\] (3.3)

_Furthermore the restriction of \(\mathbf{p}\) to any side \(f_{i}\) of \(\kappa\) depends only upon the degrees of freedom defined on that side._

Figure 10:
