Hence, choosing \(\mu=(1/\alpha)\,\|\,\pi l\|_{V^{\prime}}\), we get for all \(v\in V_{m}\) with \(\|\,v\,\|_{X}=\mu\)

\[(\Phi_{m}(v),v)\geqslant 0.\]

Moreover, \(\Phi_{m}\) is continuous in \(V_{m}\) by virtue of the hypothesis (1.10). The space \(V_{m}\) being finite-dimensional, we may apply Corollary 1.1:

there exists at least one solution \(u_{m}\in V_{m}\) of Problem (P\({}_{m}\)). Furthermore, we have for all solution \(u_{m}\)

\[0=(\Phi_{m}(u_{m}),u_{m})\geqslant(\alpha\,\|\,u_{m}\|_{X}-\|\,\pi l\|_{V^{ \prime}})\,\|\,u_{m}\|_{X}\]

so that

\[\|\,u_{m}\|_{X}\leqslant(1/\alpha)\,\|\,\pi l\|_{V^{\prime}}.\]

\(2^{\circ})\) Next, we construct a sequence \((u_{m})\) in \(V\) by taking, for each \(m\), one arbitrary solution of Problem (P\({}_{m}\)). We want to establish that we can extract a subsequence which converges towards a solution of Problem (P). It follows from (1.12) that the sequence \((u_{m})\) is bounded in \(V\). Therefore, we can extract a subsequence \((u_{m_{p}})\) such that

\[u_{m_{p}}\to u^{\star}\quad\text{weakly in $V$ as $p\to+\infty$}.\]

Then, the hypothesis (1.10) implies that

\[\lim_{p\to\infty}a(u_{m_{p}};u_{m_{p}},v)=a(u^{\star};u^{\star},v)\quad\quad \forall v\in V.\]

Taking in (1.11) \(v=w_{i}\) and \(m=m_{p}\geqslant i\), this yields:

\[a(u^{\star};u^{\star},w_{i})=\langle l,w_{i}\rangle,\quad\quad i\geqslant 1.\]

Since the finite linear combinations of the \(w_{i}\) are dense in \(V\), we get

\[a(u^{\star};u^{\star},v)=\langle l,v\rangle\quad\quad\forall v\in V,\]

so that \(u^{\star}\) is a solution of Problem (P). 

_Remark 1.1_.: Clearly, Theorem 1.2 is valid in a more general context: \(V\) is a separable Hilbert space; \((u,v)\to a(u,v)\) is a mapping from \(V\times V\) into \(\mathbb{R}\) such that

(i) \(a(v,v)\geqslant\alpha\,\|\,v\,\|_{Y}^{2}\quad\forall v\in V,\,\alpha>0\);

(ii) for each \(u\in V,\,v\to a(u,v)\) is a linear continuous form on \(V\);

(iii) for each \(v\in V,\,u\to a(u,v)\) is sequentially weakly continuous on \(V\).

Then, given \(l\in V^{\prime}\), there exists at least one element \(u\in V\) such that

\[a(u,v)=\langle l,v\rangle\quad\quad\forall v\in V.\]

Now, we turn to the uniqueness of the solution of Problem (P). This requires stronger hypotheses than (1.9) and (1.10). Namely, we assume that

(i) the bilinear form \(a(w;\,.\,,\,.\,)\) is uniformly \(V\)-elliptic with respect to \(w\), i.e., there exists a constant \(\alpha>0\) such that

\[a(w;v,v)\geqslant\alpha\,\|\,v\,\|_{X}^{2}\quad\quad\forall v,\,w\in V;\]
