By virtue of (1.24), the operator \(C_{h}\) is non-singular and therefore \(\lambda_{h}^{\varepsilon}\) can be eliminated from the above equations. Thus Problem (\(Q_{h}^{\varepsilon}\)) is equivalent to the following _Problem_ (\(P_{h}^{\varepsilon}\)):

\(Find\ u_{h}^{\varepsilon}\in X_{h}\) _satisfying:_

\[a(u_{h}^{\varepsilon},v_{h})+\frac{1}{\varepsilon}\langle C_{h}\,^{1}B_{h}u_{ h}^{\varepsilon},B_{h}v_{h}\rangle=\langle l,v_{h}\rangle+\frac{1}{\varepsilon} \langle C_{h}^{-1}\chi,B_{h}v_{h}\rangle\ \ \ \ \ \forall v_{h}\in X_{h},\] (1.26)

where \(C_{h}^{-1}\in\mathcal{L}(M_{h}^{\prime};M_{h})\) denotes the inverse of \(C_{h}\).

Clearly, the situation here is exactly that of Section I.4.3, with the operators \(B\) and \(C\) replaced by \(B_{h}\) and \(C_{h}\). Hence the statement of Theorem I.4.3 is valid for Problems (\(P_{h}^{\varepsilon}\)) and (\(Q_{h}^{\varepsilon}\)):

**Theorem 1.3**.: _In addition to (1.12) and (1.24), assume that there exists a constant \(\alpha^{\ast}>0\) such that_:__

\[a(v_{h},v_{h})+\langle C_{h}^{-1}B_{h}v_{h},B_{h}v_{h}\rangle\geqslant\alpha^ {\ast}\|v_{h}\|_{X}^{2}\ \ \ \ \ \forall v_{h}\in X_{h}.\] (1.27)

_Then Problems (\(Q_{h}\)) and (\(Q_{h}^{\varepsilon}\)) for \(\varepsilon\leqslant 1\) have both a unique solution \((u_{h},\lambda_{h})\) and \((u_{h}^{\varepsilon},\lambda_{h}^{\varepsilon})\) in \(X_{h}\times M_{h}\). Moreover, for all \(\varepsilon\leqslant\varepsilon_{0}\) small enough we have the following error bound:_

\[\|u_{h}^{\varepsilon}-u_{h}\|_{X}+\|\lambda_{h}^{\varepsilon}-\lambda_{h}\|_{ M}\leqslant K^{\ast}\varepsilon(\|l\|_{X^{\prime}}+\|\chi\|_{M^{\prime}}),\] (1.28)

_where the constant \(K^{\ast}\) depends only upon \(\alpha^{\ast}\), \(\beta^{\ast}\), \(\|\,a\,\|\), \(\|\,b\,\|\) and \(\|\,c\,\|\)._

Likewise, we can refine (1.28) and obtain an asymptotic expansion for \((u_{h}^{\varepsilon},\lambda_{h}^{\varepsilon})\) in powers of \(\varepsilon\). Again, we introduce the sequence of solutions \((u_{h}^{\ast},\lambda_{h}^{\ast})\in X_{h}\times M_{h}\) of the problems:

\[\left\{\begin{aligned} a(u_{h}^{\ast},v_{h})+b(v_{h},\lambda_{h}^{ \ast})=0\ \ \ \ \ \forall v_{h}\in X_{h},\\ b(u_{h}^{\ast},\mu_{h})=c(\lambda_{h}^{\ast-1},\mu_{h})\ \ \ \ \ \forall\mu_{h}\in M_{h},\end{aligned}\right.\] (1.29)

starting with \(\lambda_{h}^{0}=\lambda_{h}\). We have the analogue of Theorem I.4.4:

**Theorem 1.4**.: _Under the hypotheses of Theorem 1.3, we have for all integers \(N\geqslant 1\) and for \(\varepsilon\leqslant\varepsilon_{0}\) small enough:_

\[\left\|\,u_{h}^{\varepsilon}-u_{h}-\sum_{n=1}^{N}\varepsilon^{n}u_{h}^{n}\, \right\|_{X}+\left\|\,\lambda_{h}^{\varepsilon}-\lambda_{h}-\sum_{n=1}^{N} \varepsilon^{n}\,\lambda_{h}^{n}\,\right\|_{M}\] (1.30) \[\leqslant K_{N}^{\ast}\varepsilon^{N+1}(\|l\|_{X^{\prime}}+\|\chi\| _{M^{\prime}}),\]

_where the constant \(K_{N}^{\ast}\) depends only upon \(N\), \(\alpha^{\ast}\), \(\beta^{\ast}\), \(\|\,a\,\|\), \(\|\,b\,\|\) and \(\|\,c\,\|\)._

Now, we turn to the gradient algorithms of Section I.4.4. With the above notations, we set for each real parameter \(r\geqslant 0\):

\[a_{r}^{h}(u,v)=a(u,v)+r\langle C_{h}^{-1}B_{h}u,B_{h}v\rangle\ \ \ \ \ \forall u,v\in X.\] (1.31)
