The remainder of this section is devoted to the proof of the inf-sup condition. We propose to establish it first locally and then extend it by Theorem 1.12. The reader can also refer to Verfurth [83] for a direct global proof.

Here, the difficulty in a local argument lies in the choice of an adequate partition of \(\Omega\). We propose to group together all the elements which share a common vertex like in Figure 18. More precisely, we make the following assumption on the triangulation \(\mathcal{T}_{h}\):

\[\left\{\begin{aligned} \mathcal{T}_{h}\text{ has a set of interior nodes }\{a_{r}\}_{r=1}^{R}\text{ such that }\{\Omega_{r}\}_{r=1}^{R}\text{ with }\\ \Omega_{r}=\overbrace{\underset{\kappa\text{ has vertex }a_{r}}{\overset{ \circ}{\bigcup}\kappa}}^{\circ}\\ \text{ is a partition of }\bar{\Omega}.\end{aligned}\right.\] (4.17)



If this assumption holds, each element \(\kappa\) of \(\mathcal{T}_{h}\) belongs to exactly one macro-element \(\Omega_{r}\). In addition, the fact that all the nodes \(a_{r}\) are _inside_\(\Omega\) implies that each element \(\kappa\) has _exactly one side_ on the boundary of its macro-element \(\Omega\), and at _most one side_ on the boundary \(\Gamma\) of \(\Omega\).

In practice, it is not difficult to construct a triangulation that satisfies (4.17). The usual procedure is to start with a coarse grid and then progressively refine it by adding interior nodes.

Recall the spaces defined by (1.54):

Figure 18:
