Hence we have on the one hand

\[\langle A^{-1}f,f\rangle\leqslant(1/\!\gamma)\,\|\,f\,\|_{\star}^{2}.\]

On the other hand, we set

\[K=\|\,A\,\|_{\mathscr{L}(X;X)}.\]

Therefore

\[\|\,f\,\|_{\star}\leqslant K\,\|\,A^{-1}f\,\|_{X}\]

and thus

\[\langle A^{-1}f,f\rangle\geqslant(\gamma/K^{2})\,\|\,f\,\|_{\star}^{2}.\]

Summing up, we get

\[(\gamma/K^{2})\,\|\,f\,\|_{\star}^{2}\leqslant\langle A^{-1}f,f\rangle \leqslant(1/\!\gamma)\,\|\,f\,\|_{\star}^{2}.\qed\] (6.26)

**Theorem 6.3**.: _Let \(u\) be a nonsingular solution of Problem (6.24). Then the functional \(J\) defined by_

\[J(v)=(1/2)\,\langle A^{-1}(F(v)),F(v)\rangle\] (6.27)

_is strictly convex in a neighborhood of \(u\)._

Proof.: Taking into account the symmetry of \(A^{-1}\), the first two derivatives of \(J\) have the expression:

\[DJ(v)\cdot w =\langle A^{-1}(DF(v)\cdot w),F(v)\rangle\] (6.28) \[=\langle A^{-1}(F(v)),DF(v)\cdot w\rangle,\] (6.29) \[D^{2}J(v)\cdot(w,z)=\langle A^{-1}(DF(v)\cdot z),DF(v)\cdot w \rangle\,+\,\langle A^{-1}(F(v)),D^{2}F(v)\cdot(w,z)\rangle.\]

Now, recall that \(u\) is a nonsingular solution of Problem (6.24) if

\[F(u)=0\quad\text{and}\quad DF(u)\quad\text{is an {isomorphism} from $X$ onto $X^{\prime}$.}\]

Hence (6.29) yields:

\[D^{2}J(u)\cdot(w,w)=\langle A^{-1}(DF(u)\cdot w),DF(u)\cdot w\rangle.\] (6.30)

Thus (6.26) implies that

\[D^{2}J(u)\cdot(w,w) \geqslant(\gamma/K^{2})\,\|\,DF(u)\cdot w\,\|_{\star}^{2}\] \[\geqslant\delta\,\|\,w\,\|_{X}^{2}\quad\quad\delta>0,\]

since \(DF(u)\) is an isomorphism of \(X\) onto \(X^{\prime}\). But the mapping \(D^{2}J\) is continuous in \(X\) (because \(F\) is a \(\mathscr{C}^{p}\)-mapping); therefore there exists \(\rho>0\) such that

\[\|\,D^{2}J(u)-D^{2}J(v)\|\leqslant\delta/2\]

for all \(v\!\in\!S(u;\rho)=\{v\!\in\!X;\|\,v-u\,\|_{X}\leqslant\rho\}\). Hence
