(3.21) \[(\mathcal{F}_{1}q)_{i,\,j}=[1/(2h)](q_{i+1/2,\,j+1/2}\,+\,q_{i+1/2,\,j-1/2}\,-\,q_ {i-1/2,\,j+1/2}-\,q_{i-1/2,\,j-1/2}),\] \[(\mathcal{F}_{2}q)_{i,\,j}=[1/(2h)](q_{i+1/2,\,j+1/2}\,+\,q_{i-1/2,\, j+1/2}\,-\,q_{i-1/2,\,j+1/2}-\,q_{i-1/2,\,j-1/2})\]

and the summation runs over all interior nodes \((i,j)\) of \(\mathcal{T}_{h}\) (since \(\mathbf{v}\) vanishes on \(\Gamma\)). Therefore, if \(q\) belongs to \(\operatorname{Ker}(B_{h}^{\prime})\), i.e. if \(q\in M_{h}\) and

\[\int_{\Omega}q\operatorname{div}\mathbf{v}\,dx=0\quad\quad\forall\mathbf{v}\in X _{h},\]

we must have

\[q_{i+1/2,\,j+1/2}=q_{i-1/2,\,j-1/2},\quad\quad q_{i-1/2,\,j+1/2}=q_{i+1/2,\,j- 1/2}.\]



These equalities do not necessarily imply that \(q\) is a constant in \(\Omega\). Rather, the values of \(q\) can alternate between two constants on adjacent elements like in Figure 13. That these constants should be opposite numbers follows from the fact that \(\int_{\Omega}q\,dx=0\).

Let us characterize more precisely \(\operatorname{Ker}(B_{h}^{\prime})\). To simplify the discussion, it is convenient to suppose that \(\Omega\) is the _square_\((-1,1)\times(-1,1)\) and that \(\mathcal{T}_{h}\) is the even square grid with mesh size

\[h=1/(2n)\]

and nodes

\[x_{i,\,j}=(ih,jh)\quad\text{with}\,-\,2n\leq i,j\leq 2n\]

(cf. Figure 14). Let \(\mu\in M_{h}\) be defined by

(3.22) \[\mu|_{\kappa_{i,\,j}}=(-1)^{i+j}\quad\quad\forall\kappa_{i,\,j}\subset \mathcal{T}_{h}.\]
