values at the principal lattice of order \(k\) of \(\hat{\kappa}\) (cf. Figure 4):

\[\Sigma_{\hat{\kappa}}=\{(i/k,j/k);\,0\leqslant i,j\leqslant k\},\]

i.e. for each \(\hat{\theta}\in\mathcal{C}^{0}(\hat{\kappa})\), we set

(A.48) \[\hat{I}\hat{\theta}\in Q_{k},\quad\quad\hat{I}\hat{\theta}(\hat{x})=\hat{ \theta}(\hat{x})\quad\quad\forall\hat{x}\in\Sigma_{\hat{\kappa}}.\]

Then, if \(\mathcal{T}_{h}\) is regular the interpolation operator \(I_{h}\) defined on each \(\kappa\) of \(\mathcal{T}_{h}\) by

\[I_{h}v=\hat{I}\hat{v}\quad\quad\forall v\in\mathcal{C}^{0}(\bar{\partial})\]

satisfies the conclusions of Lemma A.2, namely:

(A.49) \[\begin{array}[]{l}|v-I_{h}v|_{m,\,p,\,Q}\leqslant Ch^{s+1-m}|v|_{s+1,\,p,\,Q }\quad\quad\forall v\in W^{s+1,\,p}(\Omega),\\ \quad\quad\forall m\in\mathbb{N},\quad\quad\forall s,\,p\in\mathbb{R}\quad \text{with }p>1,\quad\quad 0\leqslant m\leqslant s+1,\quad\quad 1\leqslant s \leqslant k;\end{array}\]

and

(A.50) \[|v-I_{h}v|_{m,\,q,\,\Omega}\leqslant Ch^{1-m}|v|_{1,\,q,\,\Omega}\quad\quad \forall v\in W^{1,\,q}(\Omega),\quad\,q>2,\quad\,m=0,\,1.\]

Similarly, we define the interpolation operator \(\tilde{I}_{\hat{\kappa}}\) on \(W^{2,\,p}(\hat{\kappa})\) for \(p>1\) by:

\[\tilde{I}_{\hat{\kappa}}\hat{\theta}\in Q_{k},\] \[\tilde{I}_{\hat{\kappa}}\hat{\theta}(\hat{a}_{i})=\hat{\theta}( \hat{a}_{i})\quad\quad 1\leqslant i\leqslant 4,\] \[\text{if }k\geqslant 2\quad\quad\begin{cases}\int_{\hat{\kappa}} \left(\tilde{I}_{\hat{\kappa}}\hat{\theta}-\hat{\theta}\right)f\,d\hat{s}=0 \quad\quad\forall\in P_{k-2}(\hat{\kappa}^{\prime}),\quad\quad\forall\text{ sides }\hat{\kappa}^{\prime}\text{ of }\hat{\kappa},\\ \quad\quad\quad\quad\int_{\hat{\kappa}}\left(\tilde{I}_{\hat{\kappa}}\hat{ \theta}-\hat{\theta}\right)f\,d\hat{x}=0\quad\quad\forall f\in Q_{k-2}(\hat{ \kappa}).\end{cases}\]

Following the lines of Lemma A.3, it can be easily proved that this system of linear equations defines \(\tilde{I}_{\hat{\kappa}}\) uniquely. Then, if \(\mathcal{T}_{h}\) is regular, the operator \(\tilde{I}_{h}\) defined in each \(\kappa\) of \(\mathcal{T}_{h}\) by

\[\widehat{\tilde{I}_{h}v}=\tilde{I}_{\hat{\kappa}}\hat{\theta}\quad\quad\forall v \in W^{2,\,p}(\Omega)\quad\text{with }p>1\]

satisfies the statement of Lemma A.4.

Likewise, the projections \(P_{h}\) and \(\hat{P}_{h}\) can be extended to the case of quadrilaterals and it can be shown that they have the same properties as in the triangular case. Similarly, the \(L^{2}\) projection \(\rho_{h}\) defined by:

(A.51) \[\begin{cases}\hat{\rho}\hat{\theta}\in Q_{k}&\\ \int_{\hat{\kappa}}\left(\hat{\rho}\hat{\theta}-\hat{\theta}\right)f\,d\hat{x} =0\quad\quad\forall f\in Q_{k}\end{cases}\quad\text{on }\hat{\kappa}\]

satisfies the statement of Lemma A.5_provided the triangulation is regular_.

Finally, Lemma A.6 and Corollary A.3 remain valid in the case of quadrilat
