\[Du_{r}=Du_{r}(\mu)\in\mathcal{L}(M;X)\]

is independent of \(\mu\). More precisely, (4.47) yields:

\[Du_{r}=-A_{r}^{-1}B^{\prime}\]

where \(A_{r}\in\mathcal{L}(X;X^{\prime})\) denotes the operator associated with the bilinear form \(a_{r}(.,.)\):

\[\langle A_{r}u,v\rangle=a_{r}(u,v)\ \ \ \ \ \forall u,\,v\in X.\]

Hence, differentiating (4.49), we find:

\[DK_{r}(\mu)\cdot v=\langle A,Du_{r}\cdot v,u_{r}(\mu)\rangle+\langle\chi,v \rangle=\langle\chi-Bu_{r}(\mu),v\rangle.\]

Therefore

\[DK_{r}(\mu)=\chi-Bu_{r}(\mu)\in M^{\prime}\] (4.51)

and

\[D^{2}K_{r}(\mu)=D^{2}K_{r}=-BDu_{r}=BA_{r}^{-1}B^{\prime}\in\mathcal{L}(M;M^{ \prime}).\] (4.52)

Next, let us equip the Hilbert space \(M\) with a scalar product. As the bilinear form \(c(.,.)\) is symmetric and \(M\)-elliptic we can choose it for scalar product. With respect to \(c\), the gradient \(g_{r}(\mu)\) of \(K_{r}\) at the point \(\mu\) of \(M\) is defined by:

\[c(g_{r}(\mu),v)=DK_{r}(\mu)\cdot v.\]

In other words,

\[g_{r}(\mu)=C^{-1}(\chi-Bu_{r}(\mu)).\] (4.53)

Now, let \((\omega^{m})\) be an arbitrary sequence of elements of \(M\) and consider the following method of descent:

starting with an initial guess \(\dot{\iota}^{0}\in M\), construct the sequence \((\dot{\iota}^{m})\subset M\) by:

\[\dot{\iota}^{m+1}=\dot{\iota}^{m}-\rho^{m}\omega^{m}\ \ \ \ \ m\geqslant 0,\] (4.54)

where the parameter \(\rho^{m}\) is chosen so that

\[K_{r}(\dot{\iota}^{m}-\rho^{m}\omega^{m})=\inf_{\rho\,\in\,\mathbb{R}}K_{r}( \dot{\iota}^{m}-\rho\omega^{m}).\]

This optimal \(\rho^{m}\) is given by:

\[\rho^{m}=DK_{r}(\dot{\iota}^{m})\cdot\omega^{m}/D^{2}K_{r}\cdot(\omega^{m}, \omega^{m})\] (4.55)

and of course \(u^{m}\) is related to \(\dot{\iota}^{m}\) by (cf. (4.47)):

\[u^{m}=A_{r}^{-1}(l+rB^{\prime}C^{-1}\chi-B^{\prime}\dot{\iota}^{m})=u^{m}( \dot{\iota}^{m}).\] (4.56)

Note that this iterative method decouples the computation of \(u^{m}\) and \(\dot{\iota}^{m}\). The sequence \((\omega^{m})\) is not specified for the moment. We shall see further on that proper choices of \((\omega^{m})\) lead to attractive gradient methods.

From a practical point of view, the algorithm (4.54), (4.55), (4.56) can be
