estimate can be expected for the whole of \(p_{h}\). However, we are going to see that \(p_{h}^{4}\), the supplementary component of \(p_{h}\) in \(A_{h}\) is bounded. Indeed, it stems from (3.36) that

\[(p_{h}^{4},\operatorname{div}\mathbf{v}_{h})=v(\mathbf{grad}(\mathbf{u}_{h}- \mathbf{u}),\mathbf{grad}\,\mathbf{v}_{h})+(p-\tilde{p}_{h},\operatorname{div} \mathbf{v}_{h})\quad\quad\forall\mathbf{v}_{h}\in X_{h}.\]

Therefore,

\[\sup_{\mathbf{v}_{h}\in X_{h}}\left[\frac{(p_{h}^{4},\operatorname{div} \mathbf{v}_{h})}{|\mathbf{v}_{h}|_{1,\Omega}}\right]\leqslant C_{4}h\{| \mathbf{u}|_{2,\Omega}+|p|_{1,\Omega}\}.\]

It may happen, in the best of cases, that the left-hand side of this inequality is bounded below by \(C_{5}\|p_{h}^{4}\|_{0,\Omega}\) with a constant \(C_{5}\) that does not depend upon \(h\) and thus \(\|p_{h}^{4}\|_{0,\Omega}\) is \(O(h)\). However, in the general case, all we can do is apply Lemma 3.5; it yields the next result.

**Corollary 3.1**.: _Under the hypotheses of Theorem 3.5, the component \(p_{h}^{4}\) of \(p_{h}\) in \(A_{h}\) is bounded as follows:_

\[\|p_{h}^{4}\|_{0,\Omega}\leqslant C\{|\mathbf{u}|_{2,\Omega}+|p|_{1,\Omega}\}.\] (3.42)

Finally, we can also apply Theorem 1.2 with the pair of spaces \((\tilde{V}_{h},\tilde{M}_{h})\) and derive an optimal error estimate for \(\|\mathbf{u}-\mathbf{u}_{h}\|_{0,\Omega}\).

**Corollary 3.2**.: _Under the hypotheses of Theorem 3.5, we have:_

\[\|\mathbf{u}-\mathbf{u}_{h}\|_{0,\Omega}\leqslant Ch^{2}\{|\mathbf{u}|_{2, \Omega}+|p|_{1,\Omega}\}.\] (3.43)

Figure 17:
