Proof.: This is a consequence of a general optimization result: the Lagrangean functional \(\mathcal{L}\) has a saddle-point \((u,\lambda)\) iff

\[\operatorname*{Min}_{v\in X}\left(\sup_{\mu\in M}\mathcal{L}(v,\mu)\right)= \operatorname*{Max}_{\mu\in M}\left(\inf_{v\in X}\mathcal{L}(v,\mu)\right)\] (4.17)

and this quantity is equal to \(\mathcal{L}(u,\lambda)\).

Let us recall the proof for the reader's convenience. Setting

\[\phi(v)=\sup_{\mu\in M}\mathcal{L}(v,\mu),\ \ \ \ \phi^{\star}(\mu)=\inf_{v\in X} \mathcal{L}(v,\mu),\]

we first notice that

\[\sup_{\mu\in M}\phi^{\star}(\mu)\leqslant\inf_{v\in X}\phi(v).\] (4.18)

In fact, since

\[\mathcal{L}(v,\mu)\leqslant\phi(v)\ \ \ \ \ \forall v\in X,\ \ \ \ \ \forall\mu\in M,\]

we get

\[\phi^{\star}(\mu)\leqslant\inf_{v\in X}\phi(v)\ \ \ \ \ \ \forall\mu\in M,\]

so that (4.18) follows.

Now let \((u,\lambda)\) be a saddle-point of \(\mathcal{L}\). This means that

\[\phi(u)=\mathcal{L}(u,\lambda)=\phi^{\star}(\lambda).\]

Hence

\[\inf_{v\in X}\phi(v)\leqslant\phi(u)=\phi^{\star}(\lambda)\leqslant\sup_{\mu \in M}\phi^{\star}(\mu).\] (4.19)

With (4.18) this implies that

\[\inf_{v\in X}\phi(v)=\phi(u)=\mathcal{L}(u,\lambda)=\phi^{\star}(\lambda)= \sup_{\mu\in M}\phi^{\star}(\mu),\]

which in particular implies (4.17).

Conversely, let (4.17') hold and let \(u\) realize the minimum of \(\phi\) and \(\lambda\) the maximum of \(\phi^{\star}\). Then (4.17') says that

\[\phi(u)=\phi^{\star}(\lambda).\]

In addition, the definition of \(\phi\) and \(\phi^{\star}\) implies that

\[\phi^{\star}(\lambda)\leqslant\mathcal{L}(u,\lambda)\leqslant\phi(u);\]

thus

\[\phi(u)=\mathcal{L}(u,\lambda)=\phi^{\star}(\lambda),\]

meaning that \((u,\lambda)\) is a saddle-point of \(\mathcal{L}\).

Finally, this optimization result and the uniqueness of the solution of (Q) yield the characterization (4.17).
