\((\mathcal{O}_{i})_{i\geq 1}\) (cf. Yosida [84]), i.e.

\[\alpha_{i}\!\in\!\mathcal{D}(\mathcal{O}_{i}),\quad\ 0\leq\alpha_{i}(x)\leq 1\quad \text{and}\quad\sum_{i=1}^{q}\alpha_{i}(x)\equiv 1\quad\text{in }\Omega.\]

Thus

\[\mathbf{\tilde{t}}=\sum_{i=1}^{q}\alpha_{i}\mathbf{\tilde{t}}\quad\text{in } \mathbb{R}^{N}.\]

Clearly, \(\alpha_{i}\mathbf{\tilde{f}}\!\in\!H(\mathbf{curl};\Omega)\) and \(\operatorname{supp}(\alpha_{i}\mathbf{\tilde{f}})\!\subset\!\bar{\Omega}_{i}\). Therefore, we can finish the proof by applying the result of \(1^{\circ}\)) to each \(\alpha_{i}\mathbf{\tilde{f}}\). 

**Theorem 2.10**.: _Let \(\Omega\) be like in Lemma 2.3. Then \(\mathcal{D}(\bar{\Omega})^{N}\) is dense in \(H(\mathbf{curl};\Omega)\)._

The proof, which is an easy variant of Theorem 2.4, is left as an exercise.

Now, we are in a position to define the tangential trace on \(\Gamma\) of functions of \(H(\mathbf{curl};\Omega)\). In the case \(N=2\), we denote by \(\tau\) the unit tangent to \(\Gamma\) like in Figure 1--i.e. \(\tau=(-n_{2},n_{1})\).



**Theorem 2.11**.: _The mapping \(\gamma_{\tau}\!:\mathbf{v}\to\mathbf{v}\!\cdot\!\tau\!\restriction_{\Gamma}\) for \(N=2\) or \(\gamma_{\tau}\!:\mathbf{v}\to\mathbf{v}\times\mathbf{n}|_{\Gamma}\) for \(N=3\) defined on \(\mathcal{D}(\Omega)^{N}\) can be extended by continuity to a linear and continuous mapping, still denoted by \(\gamma_{\tau}\), from \(H(\mathbf{curl};\Omega)\) into \(H^{-1/2}(\Gamma)\) if \(N=2\) or \(H^{\cdot 1/2}(\Gamma)^{3}\) if \(N=3\). Moreover, the following Green's formula holds:_

(2.22) \[\begin{split}&(\mathbf{curl}\,\mathbf{v},\phi)-(\mathbf{v}, \mathbf{curl}\,\phi)=\langle\gamma_{\tau}\mathbf{v},\phi\rangle_{\Gamma}\quad \quad\forall\mathbf{v}\!\in\!H(\mathbf{curl};\Omega),\\ &\forall\mathbf{\phi}\!\in\!H^{1}(\Omega)^{3}\quad\text{if }\,N=3\quad \text{or}\quad\phi\!\in\!H^{1}(\Omega)\quad\text{if }\,N=2.\end{split}\]

We skip the proof as it is entirely similar to that of Theorem 2.5.

To avoid a multiplicity of notations, we denote \(\gamma_{\tau}\mathbf{v}\) by \(\mathbf{v}\!\cdot\!\tau\!\restriction_{\Gamma}\) or \(\mathbf{v}\times\mathbf{n}|_{\Gamma}\) according that \(N=2\) or \(N=3\).

Now we turn to \(\operatorname{Ker}(\gamma_{\tau})\) in \(H(\mathbf{curl};\Omega)\).
