(ii) the mapping \(w\to\pi A(w)\) is locally Lipschitz-continuous in \(V\), i.e., there exists a continuous and monotonically increasing function \(L\colon\mathbb{R}_{+}\to\mathbb{R}_{+}\) such that for all \(\mu>0\)

(1.14) \[\begin{split}&|a(w_{1};u,v)-a(w_{2};u,v)|\leqslant L(\mu)\,\|u\, \|_{X}\|v\,\|_{X}\|w_{1}-w_{2}\|_{X}\\ &\quad\forall u,v\in V,\quad\forall w_{1},\,w_{2}\in S_{\mu}=\{w \in V;\,\|w\|_{X}\leqslant\mu\}.\end{split}\]

**Theorem 1.3**.: _Assume that the hypotheses (1.13) and (1.14) hold. Then, under the condition_

(1.15) \[\big{[}\|\pi l\|_{V^{\prime}}/(\alpha^{2})\big{]}L(\|\pi l\|_{V^{\prime}}/ \alpha)<1,\]

_Problem (P) has a unique solution \(u\in V\)._

_Proof_. According to the hypothesis (1.13) and the Lax SS Milgram's Theorem I.1.7, the operator \(\pi A(w)\in\mathcal{L}(V;V^{\prime})\) is invertible for each \(w\in V\). Moreover, \(T(w)=(\pi A(w))^{-1}\) belongs to \(\mathcal{L}(V^{\prime};V)\) and satisfies

(1.16) \[\|\,T(w)\|_{\mathcal{L}(V^{\prime};V)}\leqslant 1/\alpha.\]

With these notations, Problem (P) becomes

\[u=T(u)\pi l\quad\text{in $V$}.\]

Let us show that \(v\to T(v)\pi l\) maps \(V\) into \(S_{\mu}\) and is a strict contraction mapping in \(S_{\mu}\), where \(\mu=(1/\alpha)\,\|\,\pi l\|_{V^{\prime}}\). For all \(v\in V\), we have

\[\|\,T(v)\pi l\|_{X}\leqslant\|\,T(v)\|_{\mathcal{L}(V^{\prime};V)}\,\|\pi l\| _{V^{\prime}}\leqslant(1/\alpha)\,\|\,\pi l\|_{V^{\prime}}=\mu,\]

so that \(T(v)\pi l\) belongs to \(S_{\mu}\). Next, we evaluate \(T(u)-T(v)\) for \(u,v\in S_{\mu}\). By virtue of the identity

\[T(u)-T(v)=T(u)\big{[}\pi A(v)-\pi A(u)\big{]}T(v)\]

and (1.16), we find

\[\|\,T(u)-T(v)\|_{\mathcal{L}(V^{\prime};V)}\leqslant(1/\alpha^{2})\,\|\,\pi A (v)-\pi A(u)\|_{\mathcal{L}(V;V)}.\]

Therefore, (1.14) yields

\[\|(T(u)-T(v))\pi l\|_{X}\leqslant(1/\alpha^{2})\,\|\,\pi l\|_{V^{\prime}}L( \mu)\,\|\,u-v\|_{X}.\]

Hence, by (1.15), the mapping \(v\to T(v)\pi l\) is a strict contraction in \(S_{\mu}\) and has a unique fixed point \(u\in V\) which is the unique solution of Problem (P). 

_Remark 1.2_.: Since \(v\to T(v)\pi l\) is a strict contraction mapping in \(S_{\mu}\), its fixed point \(u\) can be computed by the method of successive approximations. More precisely, starting from any \(u_{0}\in S_{\mu}\), we construct the sequence \((u_{m})\) defined by

\[u_{m+1}=T(u_{m})\pi l,\]

or equivalently by

(1.17) \[a(u_{m};u_{m+1},v)=\langle l,v\rangle\quad\quad\forall v\in V.\]
