for arbitrary \(\varepsilon>0\). With the choice

\[\varepsilon=\frac{1}{2}\,\frac{\overline{\beta}}{\alpha\sqrt{N}}\,,\]

this becomes:

\[(q_{h},\operatorname{div}\mathbf{v}_{h})\geqslant\frac{1}{2}\,\|\,\tilde{q}_{h} \|_{0,\,\mathcal{O}}^{2}+\,\alpha\!\left(1-\frac{\alpha N}{2\overline{\beta}^ {\,2}}\right)\|\,\overline{q}_{h}\|_{0,\,\mathcal{O}}^{2}.\]

Let us choose for example

\[\alpha=\frac{\overline{\beta}^{\,2}}{N}\,.\]

Then (1.57) implies:

(1.60) \[(q_{h},\operatorname{div}\mathbf{v}_{h})\geqslant\min\!\left(\frac{1}{2}, \frac{\alpha}{2}\right)\|\,q_{h}\|_{0,\,\mathcal{O}}^{2}.\]

Finally, we have:

\[|\mathbf{v}_{h}|_{1,\,\mathcal{O}} \leqslant|\mathbf{\tilde{v}}_{h}|_{1,\,\mathcal{O}}+\alpha|\mathbf{ \tilde{v}}_{h}|_{1,\,\mathcal{O}}\] \[\leqslant\frac{1}{\lambda^{\star}}\,\|\,\tilde{q}_{h}\|_{0,\, \mathcal{O}}+\frac{\alpha}{\overline{\beta}}\,\|\,\overline{q}_{h}\|_{0,\, \mathcal{O}}\] \[\leqslant\left[\left\{\frac{1}{\lambda^{\star}}\right\}^{2}+\, \left\{\frac{\alpha}{\overline{\beta}}\right\}^{2}\right]^{1/2}\|\,q_{h}\|_{0, \,\mathcal{O}}\]

by virtue of (1.57), (1.58) and (1.59). Combined with (1.60), this last inequality gives the expected inf-sup condition:

\[\frac{(q_{h},\operatorname{div}\mathbf{v}_{h})}{|\mathbf{v}_{h}|_{1,\, \mathcal{O}}}\geqslant\beta^{\star}\,\|\,q_{h}\|_{0,\,\mathcal{O}}\]

with a constant \(\beta^{\star}\) that depends solely upon \(N\), \(\overline{\beta}\) and \(\lambda^{\star}\). 

The reader can also refer to Stenberg [75] for a related approach.

## 2 Simplicial Finite Element Methods Using Discontinuous Pressures

The methods discussed in this paragraph are essentially the oldest finite element methods developed to solve the Stokes and Navier-Stokes problem. Since their first publication by Fortin [29] and by Crouzeix & Raviart [23], they have been substantially simplified and generalized by a number of authors. We shall
