on all interior nodes \((i,j)\) of \(\mathcal{T}_{h}\). With this choice we have:

\[\int_{\Omega}q\operatorname{div}\mathbf{v}\,dx=|q|_{1,\,h}^{2}\]

and by virtue of Lemma A.6, an easy calculation gives:

\[|\mathbf{v}|_{1,\,\Omega}\leqslant(C_{1}/h)\,\|\mathbf{v}\|_{0,\,\Omega} \leqslant(C_{2}/h)|q|_{1,\,h}.\]

Therefore

\[\biggl{(}\int_{\Omega}q\operatorname{div}\mathbf{v}\,dx\biggr{)}\biggl{/}| \mathbf{v}|_{1,\,\Omega}\geqslant(h/C_{2})|q|_{1,\,h}\]

and (3.27) will be established if we show the following analogue of Theorem I.1.9:

\[\|q\|_{0,\,\Omega}\leqslant C_{3}|q|_{1,\,h}\quad\forall q\in\mathcal{M}_{h}.\] (3.29)

Let us prove (3.29). First a straightforward, constructive argument shows that (3.29) holds for every function \(q\) of \(Q_{h}\) that vanishes on two elements \(\kappa_{i,\,j}\): one with \(i+j\) even and one with \(i+j\) odd. And of course the constant \(C_{3}\) is independent of \(h\) and \(q\). Next, if \(q\) belongs to \(\mathcal{M}_{h}\) it is easy to find \(\overline{q}\in\operatorname{Ker}(B_{h}^{\prime})\oplus\mathbb{R}\) such that \(q-\,\overline{q}\) is like above. Then the orthogonality of \(q\) and \(\overline{q}\) implies that

\[\|q\|_{0,\,\Omega}^{2}=\|q-\overline{q}\|_{0,\,\Omega}^{2}-\|\,\overline{q}\| _{0,\,\Omega}^{2}\leqslant C_{3}^{2}|q-\overline{q}|_{1,\,h}^{2}=C_{3}^{2}|q| _{1,\,h}^{2}.\qed\]

For a long time it was conjectured that (3.27) could not be improved; but it is only recently that Boland & Nicolaides [12] established it with the following counter-example. Roughly speaking, the idea is to find a function \(q\) in \(\mathcal{M}_{h}\) such that

\[\biggl{(}\int_{\Omega}q\operatorname{div}\mathbf{v}\,dx\biggr{)}\biggl{/}| \mathbf{v}|_{1,\,\Omega}\]

is small while \(\|q\|_{0,\,\Omega}\) is large.

More precisely let

\[q=\sum_{I,\,J}\,\{I(v_{\boldsymbol{a}})_{I,\,J}\}.\] (3.30)

On the one hand, \(q\) is indeed in \(\mathcal{M}_{h}\) because \(I\) runs over integers of opposite signs. On the other hand, a simple calculation shows that:

\[\|q\|_{0,\,\Omega}^{2}=4h^{2}(2n)\sum_{I}I^{2}=4h(2n/3)(4n^{2}-1).\]

Thus

\[\|q\|_{0,\,\Omega}=[2/(\sqrt{3}\,h)](1-h^{2})^{1/2}.\] (3.31)

Next, let us evaluate \(\int_{\Omega}q\operatorname{div}\mathbf{v}\,dx\). According to (3.21) we have:

\[(P_{1}q)_{i,\,j}=0\quad\quad\forall i,j,\quad\quad(P_{2}\,q)_{i,\,j}=\begin{cases} 0\quad\text{if $i$ is odd,}\\ (-1)^{j}(2/h)\quad\text{if $i$ is even.}\end{cases}\]
