and therefore \(w_{h}\!\in V_{h}(\chi)\). Furthermore

\[\|u-w_{h}\|_{X}\leq\|u-v_{h}\|_{X}+\|z_{h}\|_{X}\leq\!\left(1+\frac{\|b\,\|}{ \beta^{*}}\right)\|u-v_{h}\|_{X}.\]

As \(v_{h}\) is arbitrary, this implies (1.16).

It remains to evaluate \(\|\lambda-\lambda_{h}\|_{M}\). From (1.1) and (1.7) we derive that:

\[b(v_{h},\lambda_{h}-\mu_{h})=a(u-u_{h},v_{h})+b(v_{h},\lambda-\mu_{h})\ \ \ \ \ \forall v_{h}\!\in X_{h},\ \ \ \ \forall\mu_{h}\!\in M_{h}.\]

Therefore hypothesis (1.12) yields:

\[\|\lambda_{h}-\mu_{h}\|_{M} \leq\frac{1}{\beta^{*}}\sup_{v_{h}\in X_{h}}\frac{1}{\|v_{h}\|_{X }}\{a(u-u_{h},v_{h})+b(v_{h},\lambda-\mu_{h})\}\] \[\leq\!\frac{1}{\beta^{*}}\{\,\|a\|\,\|u-u_{h}\|_{X}+\|b\,\|\,\| \lambda-\mu_{h}\|_{M}\}.\]

Hence

\[\|\lambda-\lambda_{h}\|_{M}\leq\frac{1}{\beta^{*}}\biggl{\{}\|a\|\,\|u-u_{h}\| _{X}+(\beta^{*}+\|b\,\|)\inf_{\mu_{h}\in M_{h}}\|\lambda-\mu_{h}\|_{M}\biggr{\}}.\] (1.17)

Then the bound (1.13) follows immediately from (1.11), (1.16) and (1.17). 

_Remark 1.1_.: The bound (1.11) can be slightly improved without making use of the inf-sup condition (1.12). Indeed, by applying (1.10) to (1.15) we obtain:

\[\|v_{h}\|_{X}\leq\!\frac{1}{\alpha^{*}}\biggl{(}\|a\|\,\|u-w_{h}\|_{X}+\sup_{ v_{h}\in V_{h}}\frac{b(v_{h},\lambda-\mu_{h})}{\|v_{h}\|_{X}}\biggr{)}.\]

Therefore

\[\|u-u_{h}\|_{X}\leq\!\left(1+\frac{\|a\|}{\alpha^{*}}\right)\!\!\!\inf_{w_{h} \in V_{h}(x)}\|u-w_{h}\|_{X}+\frac{1}{\alpha^{*}}\inf_{\mu_{h}\in M_{h}}\sup_{ v_{h}\in V_{h}}\frac{b(v_{h},\lambda-\mu_{h})}{\|v_{h}\|_{X}}.\] (1.18)

Note that the expression

\[\inf_{\mu_{h}\in M_{h}}\sup_{v_{h}\in V_{h}}\frac{b(v_{h},\lambda-\mu_{h})}{\| v_{h}\|_{X}}\]

takes into account the fact that \(V_{h}\notin V\): it vanishes when \(V_{h}\subset V\).

_Remark 1.2_.: If besides Hypotheses (1.10) and (1.12) we assume that the bilinear form \(a(.,.)\) is symmetric and semi-positive definite on \(X_{h}\), then we can relate Problems (\(P_{h}\)) and (\(Q_{h}\)) to optimization problems. As in the continuous case, and with the same notations, it can be shown that the solution \(u_{h}\) of (\(P_{h}\)) is characterized by:

\[J(u_{h})=\inf_{v_{h}\in V_{h}(x)}J(v_{h}),\]
