\[M_{h}(\Omega_{I,J})=\{q=\alpha_{2}(v_{2})_{I,J}+\alpha_{3}(v_{3})_{I,J};\,\forall \alpha_{2},\,\alpha_{3}\in\mathbb{R}\}.\]

Then formula (3.20) yields for all \(\mathbf{v}\in X_{h}(\Omega_{I,J})\) and \(q\in M_{h}(\Omega_{I,J})\):

\[\int_{\Omega_{I,J}}q\,\mathrm{div}\,\mathbf{v}\,dx=\,-2h(\alpha_{2}u_{I,J}+ \alpha_{3}v_{I,J}),\]

where

\[\|\,q\,\|_{0,\,\partial_{I,J}}=2h(\alpha_{2}^{2}+\alpha_{3}^{2})^{1/2}.\]

By choosing

\[u_{I,J}=\,-2h\alpha_{2},\quad\,\,\,v_{I,J}=\,-2h\alpha_{3}\]

we immediately obtain (3.34) with \(C=(3/8)^{1/2}\). 

Thus setting,

\[\overline{M}_{h}=\{q\in L_{0}^{2}(\Omega);\,q|_{\Omega_{I,J}}\in\mathbb{R}\quad \forall I,\,J\}=\{q\in\mathcal{M}_{h};\,q|_{\Omega_{I,J}}=(\alpha_{1}v_{1})_{ I,J}\}\]

it follows from Theorem 1.12 that \((\widetilde{V}_{h},\widetilde{M}_{h})\) satisfies a uniform inf-sup condition provided the same is true for the pair \((\widetilde{V}_{h},\widetilde{M}_{h})\). This last property is less obvious. In order to prove it, it is convenient to group the macro-elements \(\Omega_{I,J}\) four by four like in Figure 16; and of course we must assume that these super macro-elements \(\partial_{\alpha,\,\beta}\) form again a partition of \(\overline{\Omega}\). Then we proceed in two steps. First we introduce the subspace of \(\widetilde{M}_{h}\):

\[\overline{M}_{2h}=\{q\in L_{0}^{2}(\Omega);\,q|_{\partial_{\alpha,\,\beta}} \in\mathbb{R}\quad\forall\alpha,\,\beta\}\]

and we prove that the pair \((\widetilde{V}_{h},\widetilde{M}_{2h})\) satisfies a uniform inf-sup condition. Next we show that the pair \((\widetilde{V}_{h},\widetilde{M}_{h})\) satisfies a local inf sup-condition on each set \(\mathcal{O}_{\alpha,\,\beta}\). This is achieved in the next two lemmas.

Figure 16: Super macro-element \(\mathcal{O}_{\alpha,\,\beta}\)
