Observe that in view of Theorem I.5.4, Problem (1.48) is regular as soon as the boundary \(\Gamma\) of \(\Omega\) is of class \(\mathcal{C}^{2}\). When \(\Gamma\) is only Lipschitz-continuous --and subsequently \(\Gamma\) will be a polygonal line--Remark I.5.6 asserts that Problem (1.48) is regular provided \(\Omega\) is a _plane_, _bounded_ and _convex polygon_.

**Theorem 1.9**.: _Assume that Hypotheses_ H1, H2 _and_ H3 _are satisfied and that Problem_ (1.48) _is regular. Then_, _if the solution_ \((\mathbf{u},p)\) _of the Stokes Problem_ (1.35) _belongs to_ \(H^{m+1}(\Omega)^{N}\times H^{m}(\Omega)\cap L^{2}_{0}(\Omega)\) _for some integer_ \(m\) _with_ \(1\leqslant m\leqslant l\)_, we have the following error bound:_

(1.50) \[\|\mathbf{u}-\mathbf{u}_{h}\|_{0,\Omega}\leqslant Ch^{m+1}(\|\mathbf{u}\|_{m+ 1,\Omega}+\|p\|_{m,\Omega}).\]

_Proof_. According to Theorem 1.2 and Remark 1.6, we have:

(1.51) \[\begin{split}\|\mathbf{u}-\mathbf{u}_{h}\|_{0,\Omega}\leqslant C _{1}\{|\mathbf{u}-\mathbf{u}_{h}|_{1,\Omega}+\|p-p_{h}\|_{0,\Omega}\}\\ \times\sup_{\mathbf{g}\in L^{2}(\Omega)^{N}}\frac{1}{\|\mathbf{g} \|_{0,\Omega}}\biggl{\{}\inf_{\varphi_{h}\in X_{h}}|\varphi-\varphi_{h}|_{1, \Omega}+\inf_{\xi_{h}\in M_{h}}\|\xi-\xi_{h}\|_{0,\Omega}\biggr{\}}.\end{split}\]

Since Problem (1.48) is regular, \(\varphi\in H^{2}(\Omega)^{N}\cap V\) and \(\xi\in H^{1}(\Omega)\cap L^{2}_{0}(\Omega)\). Then the extra power of \(h\) in (1.50) follows from Hypotheses H1 and H2 with \(m=1\) and (1.46) substituted into (1.51).

Thus Hypothesis H1 with \(m=1\) and Hypothesis H2 with \(m=1\) yield:

\[\inf_{\varphi_{h}\in Y_{h}}|\varphi-\varphi_{h}|_{1,\Omega}\leqslant C_{3}h| \varphi|_{2,\Omega},\quad\inf_{\xi_{h}\in M_{h}}\|\xi-\xi_{h}\|_{0,\Omega} \leqslant C_{4}h|\xi|_{1,\Omega}.\]

Therefore combining (1.49) and (1.51) we obtain:

\[\|\mathbf{u}-\mathbf{u}_{h}\|_{0,\Omega}\leqslant C_{5}h\biggl{\{}|\mathbf{u }-\mathbf{u}_{h}|_{1,\Omega}+\inf_{q_{h}\in M_{h}}\|p-q_{h}\|_{0,\Omega} \biggr{\}}\]

and (1.50) follows from (1.46) and (1.42). 

As mentioned in the previous section, the verification of Hypothesis H3 is bound to be often quite intricate. In fact, the choice of the spaces \(X_{h}\) and \(M_{h}\) is generally dictated by the fact (conjectured or established) that H3 is satisfied. The reader will find in the next section how to construct such pairs of spaces.

We finish this section with a brief survey of the iterative methods proposed in Section 1.2 to decouple the computation of \(\mathbf{u}_{h}\) from that of \(p_{h}\). We choose the scalar product of \(L^{2}(\Omega)\) for the bilinear form \(c(.\,,.)\):

\[c(p,q)=\int_{\Omega}p(x)q(x)\,dx.\]

Then, the _penalized version_ of Problem (1.40) becomes:

(1.52) \[\begin{cases}\text{Find a function $\mathbf{u}_{h}^{\varepsilon}\in X_{h}$ such that}\\ \hskip 28.452756pta(\mathbf{u}_{h}^{\varepsilon},\mathbf{v}_{h})+\frac{1}{ \varepsilon}(\rho_{h}(\operatorname{div}\mathbf{u}_{h}^{\varepsilon}),\rho_{h} (\operatorname{div}\mathbf{v}_{h}))=\langle\mathbf{f},\mathbf{v}_{h}\rangle \hskip 28.452756pt\forall\mathbf{v}_{h}\in X_{h},\end{cases}\]
