\[a_{r}^{h}(\mathbf{u}_{h}^{0},\mathbf{v}_{h})=(p_{h}^{0},\mathrm{div}\,\mathbf{v}_{h })+\langle\mathbf{f},\mathbf{v}_{h}\rangle\qquad\forall\mathbf{v}_{h}\!\in\!X_{h};\]

\(2^{\circ})\) For \(m\geqslant 0\), knowing \((\mathbf{u}_{h}^{m},p_{h}^{m})\) determine \(\mathbf{z}_{h}^{m}\!\in\!X_{h}\), \(\mu_{h}^{m}\!\in\!\mathbb{R}\) and the pair \((\mathbf{u}_{h}^{m+1},p_{h}^{m+1})\!\in\!X_{h}\times M_{h}\) by:

\[a_{r}^{h}(\mathbf{z}_{h}^{m},\,\mathbf{v}_{h}) = -(\rho_{h}(\mathrm{div}\,\mathbf{u}_{h}^{m}),\rho_{h}(\mathrm{div} \,\mathbf{v}_{h}))\qquad\forall\mathbf{v}_{h}\!\in\!X_{h};\] \[\mu_{h}^{m} = -\frac{\|\,\rho_{h}(\mathrm{div}\,\mathbf{u}_{h}^{m})\|_{0,\, \Omega}^{2}}{(\rho_{h}(\mathrm{div}\,\mathbf{u}_{h}^{m}),\rho_{h}(\mathrm{div }\,\mathbf{z}_{h}^{m}))},\] \[p_{h}^{m+1} = p_{h}^{m}-\mu_{h}^{m}\rho_{h}(\mathrm{div}\,\mathbf{u}_{h}^{m}),\] \[\mathbf{u}_{h}^{m+1} = \mathbf{u}_{h}^{m}+\mu_{h}^{m}\mathbf{z}_{h}^{m}.\]

The _conjugate-gradient algorithm_ initializes \(\mathbf{u}_{h}^{0}\) like above and replaces step \(\mathrm{n}^{\circ}\,2\) by:

\(2^{\circ})\) For \(m\geqslant 0\), knowing \((\mathbf{u}_{h}^{m},p_{h}^{m})\!\in\!X_{h}\times M_{h}\) compute \((\mathbf{z}_{h}^{m},\omega_{h}^{m})\!\in\!X_{h}\times M_{h}\), \((\mu_{h}^{m},\sigma_{h}^{m})\!\in\!\mathbb{R}\,\times\,\mathbb{R}\) and the pair \((\mathbf{u}_{h}^{m+1},p_{h}^{m+1})\!\in\!X_{h}\times M_{h}\) by:

\[\sigma_{h}^{m} = \frac{\|\,\rho_{h}(\mathrm{div}\,\mathbf{u}_{h}^{m})\|_{0,\, \Omega}^{2}}{\|\,\rho_{h}(\mathrm{div}\,\mathbf{u}_{h}^{m-1})\|_{0,\,\Omega}^ {2}}\left\{\begin{array}[]{ll}&\mbox{only if }m\geqslant 1,\\ &\mbox{$\omega_{h}^{0}=\rho_{h}(\mathrm{div}\,\mathbf{u}_{h}^{0})$,}\end{array}\right.\] \[a_{r}^{h}(\mathbf{z}_{h}^{m},\mathbf{v}_{h}) = -(\omega_{h}^{m},\mathrm{div}\,\mathbf{v}_{h})\qquad\forall \mathbf{v}_{h}\!\in\!X_{h},\] \[\mu_{h}^{m} = -\frac{\|\,\rho_{h}(\mathrm{div}\,\mathbf{u}_{h}^{m})\|_{0,\, \Omega}^{2}}{(\rho_{h}(\mathrm{div}\,\mathbf{u}_{h}^{m}),\rho_{h}(\mathrm{div }\,\mathbf{z}_{h}^{m}))},\] \[p_{h}^{m+1} = p_{h}^{m}-\mu_{h}^{m}\omega_{h}^{m},\] \[\mathbf{u}_{h}^{m+1} = \mathbf{u}_{h}^{m}+\mu_{h}^{m}\mathbf{z}_{h}^{m}.\]

It follows from Theorems 1.5 and 1.7 that both gradient algorithms are _convergent_ provided the Hypothesis H3 holds. Furthermore, the simple-gradient algorithm converges for any choice of the parameters \(\mu_{h}^{m}\) such that:

\[0<\inf_{m}\mu_{h}^{m}\leqslant\sup_{m}\mu_{h}^{m}<2\biggl{(}\frac{v}{N}+r \biggr{)}.\]

### Checking the inf-sup Condition

This short section is dedicated to the construction of pairs of spaces \((X_{h},M_{h})\) that satisfy uniformly the inf-sup condition (1.12). The underlying idea due to Boland & Nicolaiides [11], is that if (1.12) holds uniformly for a pair of spaces \((X_{h},\overline{M}_{h})\) then one can generate a whole family of pairs of spaces that also satisfy (1.12) uniformly provided they satisfy a _local_ inf-sup condition. In other words, the global condition (1.12) can be reduced to a local condition, which is of course much easier to check.
