\[D^{2}K_{r}\cdot(\mu,\mu)=\langle A_{r}^{-1}B^{\prime}\mu,B^{\prime}\mu\rangle.\]

Hence the inf-sup condition (4.9) implies that

\[\delta_{r}\|\,\mu\|_{M}^{2}\leq D^{2}K_{r}\cdot(\mu,\mu)\leq\tau_{r}\|\,\mu\|_{ M}^{2}\quad\quad\forall\mu\in M,\quad\delta_{r},\,\tau_{r}>0.\] (4.59)

As a consequence, (4.57) defines a unique \(\rho^{m}\) (provided of course \(\omega^{m}\neq 0\)).

Now we turn to the convergence of the algorithm. First, we have by construction:

\[DK_{r}(\lambda^{m+1})\cdot\omega^{m}=0.\]

Since \(K_{r}\) is quadratic this implies that:

\[K_{r}(\lambda^{m})-K_{r}(\lambda^{m+1})=(1/2)D^{2}K_{r}\cdot(\lambda^{m}- \lambda^{m+1},\lambda^{m}-\lambda^{m+1}).\]

Therefore, in view of (4.59) we get:

\[K_{r}(\lambda^{m})-K_{r}(\lambda^{m+1})\geq(1/2)\delta_{r}\|\,\lambda^{m}- \lambda^{m+1}\|_{M}^{2}.\]

But by construction, the sequence \(K_{r}(\lambda^{m})\) is monotone decreasing and bounded below by \(K_{r}(\lambda)\). Hence it is convergent and therefore

\[\lim_{m\to\infty}\|\,\lambda^{m}-\lambda^{m+1}\|_{M}=0.\]

According to (4.54), this means that

\[\lim_{m\to\infty}\rho^{m}\|\,\omega^{m}\|_{M}=0.\]

But (4.59) and the hypothesis (4.58) imply that \((\rho^{m})\) is bounded below by:

\[\rho^{m}\geq(\alpha/\tau_{r})(\|\,g^{m}\|_{M}/\|\omega^{m}\|_{M}).\]

As a consequence,

\[\rho^{m}\|\,\omega^{m}\|_{M}\geq(\alpha/\tau_{r})\,\|\,g^{m}\|_{M}\]

and thus

\[\lim_{m\to\infty}g^{m}=0,\]

i.e.

\[\lim_{m\to\infty}DK_{r}(\lambda^{m})=0\quad\text{in $M^{\prime}$}.\] (4.60)

Besides that, since \(DK_{r}(\lambda)=0\) we can write:

\[DK_{r}(\lambda^{m})=DK_{r}(\lambda^{m})-DK_{r}(\lambda)=D^{2}K_{r}\cdot( \lambda^{m}-\lambda),\]

\[D^{2}K_{r}\cdot(\lambda^{m}-\lambda,\lambda^{m}-\lambda)=DK_{r}(\lambda^{m}) \cdot(\lambda^{m}-\lambda).\]

By virtue of (4.59) this gives:

\[\delta_{r}\|\,\lambda^{m}-\lambda\|_{M}\leq\|\,DK_{r}(\lambda^{m})\|_{M^{ \prime}}.\]
