**Lemma 2.5**.: _In addition to the above assumptions, suppose that \(\Omega\) is a convex polygon. Then for each real \(s>2\) there exists a positive constant \(C_{s}\), independent of \(h\), such that:_

\[|\phi_{h}|_{1,s,\Omega}\leqslant C_{s}\|\,\theta_{h}\|_{0,\Omega}\quad\quad \forall v_{h}=(\operatorname{\mathbf{curl}}\phi_{h},\theta_{h})\in V_{h}.\] (2.41)

Proof.: First observe that because \(\Omega\) is convex, its boundary \(\Gamma\) has only one component (i.e. \(\Gamma=\Gamma_{0}\)) and \(\Phi_{h}\subset W_{0}^{1,s}(\Omega)\).

Next, in view of (2.16) and Sobolev's Theorem I.1.3, every function \(v=(\operatorname{\mathbf{curl}}\phi,\)\(\theta)\) in \(V\) satisfies (2.41). Moreover we have

\[-\Delta\phi=\theta\quad\text{in }\Omega.\] (2.42)

Of course, this equality does not hold for the functions of \(V_{h}\) but nevertheless they satisfy

\[(\operatorname{\mathbf{curl}}\phi_{h},\operatorname{\mathbf{curl}}\mu_{h})=( \theta_{h},\mu_{h})\quad\quad\forall\mu_{h}\in\Theta_{h}\]

which can be interpreted as a discrete version of (2.42). This suggests to compare \(\phi_{h}\) with the auxiliary function \(\phi(h)\), solution of the homogeneous Dirichlet problem:

\[\begin{cases}-\Delta\phi(h)=\theta_{h}&\text{in }\Omega,\\ \quad\quad\phi(h)=0&\text{on }\Gamma.\end{cases}\]

Since \(\Omega\) is convex, Theorem I.1.8 claims that \(\phi(h)\in H^{2}(\Omega)\) with

\[\|\phi(h)\|_{2,\Omega}\leqslant C_{1}\,\|\,\theta_{h}\|_{0,\Omega}.\] (2.43)

Moreover, we can readily see that \(\phi_{h}=\mathring{P_{h}}\phi(h)\), the \(H^{1}\)-projection of \(\phi(h)\) onto \(\Phi_{h}\) (cf. (A.24)). Therefore Theorem A.2 yields:

\[|\phi(h)-\phi_{h}|_{1,s,\Omega}\leqslant C_{2}\,\|\,\phi(h)\|_{1,s,\Omega}.\]

Hence applying (2.43) and Sobolev's Theorem I.1.3, we get:

\[|\phi_{h}|_{1,s,\Omega}\leqslant(1+C_{2})\,\|\,\phi(h)\|_{1,s,\Omega} \leqslant C_{3}\,\|\,\theta_{h}\|_{0,\Omega}.\qed\]

_Remark 2.5_.: Lemma 2.5 has a more elementary proof that does not call for Theorem A.2 (which is a difficult result). On the one hand, the fact that \(\phi_{h}=\mathring{P_{h}}\phi(h)\) implies that

\[|\phi_{h}-\chi_{h}|_{1,\Omega}\leqslant|\phi(h)-\chi_{h}|_{1,\Omega}\quad \quad\forall\chi_{h}\in\Phi_{h},\]

and Lemma A.7 gives for all \(s>2\):

\[|\phi_{h}-\chi_{h}|_{1,s,\Omega}\leqslant C(s)h^{2/s-1}|\phi_{h}-\chi_{h}|_{1, \Omega}.\]

On the other hand, we can write:

\[|\phi_{h}|_{1,s,\Omega}\leqslant|\phi_{h}-\chi_{h}|_{1,s,\Omega}+|\chi_{h}|_{1 ,s,\Omega}\quad\quad\forall\chi_{h}\in\Phi_{h}.\]

Collecting these three inequalities, we get:
