solutions of the problem

\[F^{\epsilon}(\lambda,u^{\epsilon})\equiv u^{\epsilon}+\,T^{\epsilon v}G(\lambda,u^ {\epsilon})=0\quad\quad v=1/\lambda\]

such that

\[\|u^{\epsilon}(\lambda)-u(\lambda)\|_{X}\leqslant a.\]

Moreover we have

\[\|u^{\epsilon}(\lambda)-u(\lambda)\|_{X} =\|\operatorname{\mathbf{u}}^{\epsilon}(\lambda)-\operatorname{ \mathbf{u}}(\lambda)\|_{1,\Omega}+\lambda\|\,p^{\epsilon}(\lambda)-p(\lambda) \|_{0,\Omega}\] \[\leqslant C_{3}\,\|(T^{\epsilon v}-\,T)G(\lambda,u(\lambda))\|_{X}\] \[\leqslant C_{2}\,C_{3}\,\varepsilon\,\|\,G(\lambda,u(\lambda))\|_ {X}\leqslant C_{4}\,\varepsilon.\]

In addition Remark 3.6 implies that the mapping \(\lambda\to u^{\epsilon}(\lambda)\) is \(\mathcal{C}^{\infty}\) from \(\Lambda\) into \(X\). 

Let \(H\) be a Banach space such that

\[X\subsetneq H\]

where as usual the sign \(\subsetneq\) means that the imbedding is continuous. Now, we want to derive a sharper estimate for \(\|u_{h}(\lambda)-u(\lambda)\|_{H}\). To this end, we assume that there exists another Banach space \(W\) with

\[W\subsetneq X\]

such that the following property holds:

(3.47) \[\begin{cases}\text{for all }v\in W,\text{ the operator }D_{u}G(\lambda,v)\text{ may be extended as a linear operator of }\mathcal{L}(H;Y),\text{ the mapping }v\to D_{u}G(\lambda,v)\text{ being continuous from }W\text{ into }\mathcal{L}(H;Y).\end{cases}\]

Hence, for \(v\in W\), both \(D_{u}F(\lambda,v)\) and \(D_{u}F_{h}(\lambda,v)\) may be extended as operators of \(\mathcal{L}(H;H)\). Next, we suppose that:

(3.48) \[\lim_{h\to 0}\|\,T_{h}-\,T\|_{\mathcal{L}(Y;H)}=0.\]

_Remark 3.7_.: Note that (3.48) is again a consequence of (3.37) when the imbedding of \(X\) into \(H\) is compact.

Then we can prove the following result.

**Theorem 3.5**.: _We retain the hypotheses of Theorem 3.3 together with (3.47) and (3.48). Assume in addition that:_

(3.49) \[\text{for each }\lambda\in\Lambda,\,u(\lambda)\in W\text{ and the function }\lambda\to u(\lambda)\in\mathcal{C}^{0}(\Lambda;W);\] (3.50) \[\text{for each }\lambda\in\Lambda,\,D_{u}F(\lambda,u(\lambda)) \text{ is an isomorphism of }\,H.\]
