The corresponding function \(\mathbf{u}_{0}(\varepsilon)=\mathbf{u}_{0\mu}\) satisfies the requirements (2.15) and (2.16). 

Now, a variational form of Problem (2.1), (2.13) consists in finding a pair \((\mathbf{u},p)\in H^{1}(\Omega)^{N}\times L^{2}_{0}(\Omega)\) solution of the equations

\[\left\{\begin{aligned} a(\mathbf{u};\mathbf{u},\mathbf{v})-(p, \operatorname{div}\mathbf{v})&=\langle\mathbf{f},\mathbf{v} \rangle\quad\quad\forall\mathbf{v}\in H^{1}_{0}(\Omega)^{N},\\ \operatorname{div}\mathbf{u}&=0\quad\text{in }\Omega,\\ \mathbf{u}&=\mathbf{g}\quad\text{on }\Gamma.\end{aligned}\right.\] (2.20)

**Theorem 2.3**.: _Let \(N\leqslant 3\) and let \(\Omega\) be a bounded domain of \(\mathbb{R}^{N}\) with a Lipschitz-continuous boundary \(\Gamma\). Given \(\mathbf{f}\in H^{-1}(\Omega)^{N}\) and \(\mathbf{g}\in H^{1/2}(\Gamma)^{N}\) satisfying the conditions (2.14), there exists at least one pair \((\mathbf{u},p)\in H^{1}(\Omega)^{N}\times L^{2}_{0}(\Omega)\) solution of (2.20) or equivalently solution of Problem (2.1) (2.13)._

Proof.: Let \(\mathbf{u}_{0}\) be a function of \(H^{1}(\Omega)^{N}\) such that

\[\operatorname{div}\mathbf{u}_{0}=0,\quad\ \mathbf{u}_{0}\,|_{\Gamma}=\mathbf{g}.\]

We set \(\mathbf{u}=\mathbf{u}_{0}+\mathbf{w}\). Since

\[a(\mathbf{u}_{0}+\mathbf{w};\mathbf{u}_{0}+\mathbf{w},\mathbf{v})=a(\mathbf{w };\mathbf{w},\mathbf{v})+a_{1}(\mathbf{u}_{0};\mathbf{w},\mathbf{v})+a_{1}( \mathbf{w};\mathbf{u}_{0},\mathbf{v})+a(\mathbf{u}_{0};\mathbf{u}_{0},\mathbf{ v}),\]

Problem (2.20) may be equivalently stated as follows:

_Find a pair \((\mathbf{w},p)\in V\times L^{2}_{0}(\Omega)\) such that_

\[\tilde{a}(\mathbf{w};\mathbf{w},\mathbf{v})-(p,\operatorname{div}\mathbf{v}) =\langle\mathbf{f},\mathbf{v}\rangle-a(\mathbf{u}_{0};\mathbf{u}_{0},\mathbf{ v})\quad\quad\forall\mathbf{v}\in H^{1}_{0}(\Omega)^{N},\] (2.21)

where

\[\tilde{a}(\mathbf{w};\mathbf{u},\mathbf{v})=a(\mathbf{w};\mathbf{u},\mathbf{ v})+a_{1}(\mathbf{u}_{0};\mathbf{u},\mathbf{v})+a_{1}(\mathbf{u};\mathbf{u}_{0}, \mathbf{v}).\]

Observe that Problem (2.21) fits into the framework of Paragraph 1 if we take

\[X=H^{1}_{0}(\Omega)^{N},\quad\ M=L^{2}_{0}(\Omega),\] \[a(.\,;.\,,.\,,.\,)\text{ replaced by }\tilde{a}(.\,;.\,,.\,,. ),\quad b(\mathbf{v},q)=-(q,\operatorname{div}\mathbf{v}),\] \[\langle l,\mathbf{v}\rangle=\langle\mathbf{f},\mathbf{v}\rangle-a (\mathbf{u}_{0};\mathbf{u}_{0},\mathbf{v}).\]

Again, we have to check the hypotheses of Theorems 1.2 and 1.4. First, using (2.5), we have for all \(\mathbf{v}\), \(\mathbf{w}\in V\)

\[\tilde{a}(\mathbf{w};\mathbf{v},\mathbf{v})=v|\mathbf{v}|^{2}_{1,\,\Omega}+a_ {1}(\mathbf{v};\mathbf{u}_{0},\mathbf{v}).\]

It follows from Lemma 2.3 that we may choose the function \(\mathbf{u}_{0}\) so that

\[|a_{1}(\mathbf{v};\mathbf{u}_{0},\mathbf{v})|\leqslant\varepsilon|\mathbf{v}| ^{2}_{1,\,\Omega}\quad\quad\forall\mathbf{v}\in V,\quad\ \varepsilon<\mathbf{v}\]

and therefore

\[\tilde{a}(\mathbf{w};\mathbf{v},\mathbf{v})\geqslant(v-\varepsilon)|\mathbf{v} |^{2}_{1,\,\Omega}\quad\quad\forall\mathbf{v},\mathbf{w}\in V.\]
