**Lemma 2.2**.: _Let \({\bf u},\,{\bf v}\in H^{1}(\Omega)^{N}\) and let \({\bf w}\in H^{1}(\Omega)^{N}\) with \(\,{\rm div}\,{\bf w}=0\) and \({\bf w}\cdot{\bf n}|_{\Gamma}=0\). Then, we have:_

(2.4) \[a_{1}({\bf w};{\bf u},{\bf v})+a_{1}({\bf w};{\bf v},{\bf u})=0,\] (2.5) \[a_{1}({\bf w};{\bf v},{\bf v})=0.\]

Proof.: Clearly, the properties (2.4) and (2.5) are equivalent and it suffices to check (2.5). Let \({\bf v}\in{\cal D}(\bar{\Omega})^{N}\) and \({\bf w}\in H^{1}(\Omega)^{N}\); we may write:

\[a_{1}({\bf w};{\bf v},{\bf v})=(1/2)\sum_{i,j=1}^{N}\int_{\Omega}w_{j}\partial (v_{i}^{2})/\partial x_{j}\,dx\]

and by Green's formula (I.2.17):

\[a_{1}({\bf w};{\bf v},{\bf v})=-(1/2)\sum_{i,j=1}^{N}\left\{\int_{\Omega}{\rm div }\,{\bf w}v_{i}\,dx+\int_{\Gamma}{\bf w}\cdot{\bf w}v_{i}\,ds\right\}.\]

When \({\bf w}\) satisfies \({\rm div}\,{\bf w}=0\) and \({\bf w}\cdot{\bf n}|_{\Gamma}=0\), this implies

\[a_{1}({\bf w};{\bf v},{\bf v})=0.\]

Then the lemma follows by using the density of \({\cal D}(\bar{\Omega})\) into \(H^{1}(\Omega)\) (cf. Theorem I.1.2). 

Now, recall the following spaces:

\[{\cal V} = \{{\bf v}\in{\cal D}(\Omega)^{N};\,{\rm div}\,{\bf v}=0\},\] \[V = \{{\bf v}\in H^{1}_{0}(\Omega)^{N};\,{\rm div}\,{\bf v}=0\}.\]

We set

(2.6) \[a_{0}({\bf u},{\bf v}) = v({\bf grad}\,{\bf u},{\bf grad}\,{\bf v})\] \[= 2v\sum_{i,j=1}^{N}\left(D_{ij}({\bf u}),D_{ij}({\bf v})\right) \quad\mbox{ if either ${\bf u}$ or ${\bf v}\in{\bf V}$},\]

and

(2.7) \[a({\bf w};{\bf u},{\bf v})=a_{0}({\bf u},{\bf v})+a_{1}({\bf w};{\bf u},{\bf v}).\]

Then Problem (2.1) (2.2) has the equivalent form:

_Find a pair \(({\bf u},p)\in V\times L^{2}_{0}(\Omega)\) such that_:

(2.8) \[a({\bf u};{\bf u},{\bf v})-(p,{\rm div}\,{\bf v})=\langle{\bf f},{\bf v} \rangle\quad\quad\forall{\bf v}\in H^{1}_{0}(\Omega)^{N}.\]

**Theorem 2.1**.: _Let \(N\leq 4\) and let \(\Omega\) be a bounded domain of \({\mathbb{R}}^{N}\) with a Lipschitz-continuous boundary \(\Gamma\). Given \({\bf f}\in H^{-1}(\Omega)^{N},\) there exists at least one pair \(({\bf u},p)\in V\times L^{2}_{0}(\Omega)\) which satisfies (2.8) or equivalently (2.1) (2.2)._
