_Find a pair \((\mathbf{u},p)\in H^{1}(\Omega)^{N}\times L_{0}^{2}(\Omega)\) such that_

(5.16) \[\left\{\begin{aligned} a(\mathbf{u},\mathbf{v})-(p,\operatorname{div} \mathbf{v})&=\langle\mathbf{f},\mathbf{v}\rangle\quad\quad \forall\mathbf{v}\in H_{0}^{1}(\Omega)^{N},\\ (q,\operatorname{div}\mathbf{u})&=0\quad\quad\forall q \in L_{0}^{2}(\Omega),\\ \mathbf{u}=&\mathbf{g}\quad on\ \Gamma,\end{aligned}\right.\]

_and_

\(Find\)__\(\mathbf{u}\in H^{1}(\Omega)^{N}\) _such that_

(5.17) \[\left\{\begin{aligned} a(\mathbf{u},\mathbf{v})& =\langle\mathbf{f},\mathbf{v}\rangle\quad\quad\forall\mathbf{v}\in V,\\ \operatorname{div}\mathbf{u}&=0\quad\text{in }\Omega,\\ \mathbf{u}&=\mathbf{g}\quad on\ \Gamma,\end{aligned}\right.\]

_where_

\[a(\mathbf{u},\mathbf{v})=\left\{\begin{aligned} a(\mathbf{u}, \mathbf{v})&=\left\{\begin{aligned} v(\mathbf{grad}\, \mathbf{u},\mathbf{grad}\,\mathbf{v}),\\ 2v\sum\limits_{i,j=1}^{N}\big{(}D_{ij}(\mathbf{u}),D_{ij}( \mathbf{v})\big{)}.\end{aligned}\right.\end{aligned}\right.\]

_Remark 5.3_.: Corollary 4.1 yields the bound:

\[\left\|\mathbf{u}\right\|_{1,\Omega}+\left\|p\right\|_{0,\Omega}\leqslant C( \left\|\mathbf{f}\right\|_{-1,\Omega}+\left\|\mathbf{g}\right\|_{1/2,\Gamma}).\]

for all functions \(\mathbf{u}_{0}\) in \(H^{1}(\Omega)^{N}\) satisfying \(\operatorname{div}\mathbf{u}_{0}=0\), \(\mathbf{u}_{0}|_{\Gamma}=\mathbf{g}\). By taking the infimum with respect to \(\mathbf{u}_{0}\), this becomes

\[\left\|\mathbf{u}\right\|_{1,\Omega}+\left\|p\right\|_{0,\Omega}\leqslant C( \left\|\mathbf{f}\right\|_{-1,\Omega}+\left\|\mathbf{g}\right\|_{1/2,\Gamma}).\]

Problem (5.12) can also be expressed as a saddle-point problem. With the above notations, we set

(5.18) \[J(\mathbf{v})=(1/2)a(\mathbf{v},\mathbf{v})-\langle\mathbf{f}, \mathbf{v}\rangle,\] (5.19) \[\mathcal{L}(\mathbf{v},q)=J(\mathbf{v})-(q,\operatorname{div} \mathbf{v}).\]

**Theorem 5.2**.: _Under the hypotheses of Theorem 5.1, \(the\) solution \((\mathbf{u},p)\) of (5.12) is characterized by:_

(5.20) \[\left\{\begin{aligned} \mathcal{L}(\mathbf{u},p)&=\underset{ \mathbf{v}\in H^{1}(\Omega)^{N}}{\operatorname{Min}}\sup_{q\in L_{0}^{2}( \Omega)}\mathcal{L}(\mathbf{v},q)\\ &=\underset{q\in L_{0}^{2}(\Omega)}{\operatorname{Max}}\inf_{ \mathbf{v}\in H^{1}(\Omega)^{N}}\mathcal{L}(\mathbf{v},q).\end{aligned}\right.\]

Proof.: We use the notations (5.13). Since the form \(a(.,.)\) is symmetric and \(H_{0}^{1}(\Omega)^{N}\) elliptic and the form \(b(.,.)\) satisfies the inf-sup condition (5.14), we may apply Theorem 4.2. We find that the pair \((\mathbf{u}-\mathbf{u}_{0},p)\) is the unique saddle-point of the Lagrangean functional
