In other words, \(\langle\,.\,,\,.\,\rangle\) is an extension of the scalar product of \(L^{2}(\Omega)\). Now, we can define the derivatives of distributions. Let \(\alpha=(\alpha_{1},\ldots,\alpha_{N})\,{\in}\,\mathbb{N}^{N}\) and set

\[|\alpha|=\sum_{i=1}^{N}\alpha_{i}.\]

For \(u\) in \(\mathcal{D}^{\prime}(\Omega)\), we define \(\partial^{\alpha}u\) in \(\mathcal{D}^{\prime}(\Omega)\) by:

\[\langle\partial^{\alpha}u,\,\phi\rangle=(-1)^{|\alpha|}\langle u,\,\partial^{ \alpha}\phi\rangle\ \ \ \ \ \forall\phi\,{\in}\,\mathcal{D}(\Omega);\]

when \(u\) is \(\alpha\) times differentiable, \(\partial^{\alpha}u\) coincides with the usual notion of derivative:

\[\partial^{\alpha}u=\frac{\partial^{|\alpha|}u}{\partial x_{1}^{\alpha_{1}} \ldots\partial x_{N}^{\alpha_{N}}}.\]

For each integer \(m\geqslant 0\) and real \(p\) with \(1\leqslant p\leqslant\infty,\) we define the Sobolev space:

\[W^{m,\,p}(\Omega)=\{v\,{\in}\,L^{p}(\Omega);\,\partial^{\alpha}v\,{\in}\,L^{p }(\Omega)\ \ \ \forall|\alpha|\leqslant m\},\]

which is a Banach space for the norm:

(1.1) \[\|u\|_{m,\,p,\,\Omega}=\biggl{(}\sum_{|\alpha|\leqslant m}\int_{\Omega}| \partial^{\alpha}u(x)|^{p}\,dx\biggr{)}^{1/p}\ \ \ \ \ p<\infty\]

or

\[\|u\|_{m,\,\infty,\,\Omega}=\max_{|\alpha|\leqslant m}\biggl{(}\operatorname* {ess\,sup}_{x\,\in\,\Omega}|\partial^{\alpha}u(x)|\biggr{)},\ \ \ \ \ p=\infty.\]

The space \(W^{m,\,p}(\Omega)\) is separable for \(1\leqslant p<\infty\) and reflexive for \(1<p<\infty.\) We also provide \(W^{m,\,p}(\Omega)\) with the following seminorm

(1.2) \[|u|_{m,\,p,\,\Omega}=\biggl{(}\sum_{|\alpha|=m}\int_{\Omega}|\partial^{\alpha }u(x)|^{p}\,dx\biggr{)}^{1/p},\ \ \ \text{for}\ p<\infty,\]

and we make the above modification when \(p\equiv\infty.\) If \(u\) belongs to \(W^{m,\,p}(\partial)\) for every measurable, compact proper subset \(\partial\) of \(\Omega\) we say that \(u\) is locally in \(W^{m,\,p}(\Omega)\) and we write

\[u\in W^{m,\,p}_{\text{loc}}(\Omega).\]

When \(p=2,\,W^{m,\,2}(\Omega)\) is usually denoted by \(H^{m}(\Omega)\), and if there is no ambiguity, we drop the subscript \(p=2\) when refering to its norm and seminorm. \(H^{m}(\Omega)\) is a Hilbert space for the scalar product:

(1.3) \[(u,v)_{m,\,\Omega}=\sum_{|\alpha|\leqslant m}\int_{\Omega}\partial^{\alpha}u( x)\partial^{\alpha}v(x)\,dx.\]

In particular, we write the scalar product of \(L^{2}(\Omega)\) with no subscript at all.

Parallel to the Sobolev spaces, we recall the familiar definition of \(\mathcal{C}^{m}\)-functions:

\(\mathcal{C}^{0}(\Omega)\) denotes the space of continuous functions defined in \(\Omega\) and
