more, there exists a continuous and invertible mapping \(F_{d_{i}}\) from \(\hat{\mathcal{A}}_{i}\) onto \(\mathcal{A}_{i}\) such that

\[F_{d_{i}}|_{\hat{\kappa}_{j}}\quad\text{is an {affine} mapping from $\hat{\kappa}_{j}$ onto $\kappa_{j}$}\]

for all \(\hat{\kappa}_{j}\) contained in \(\hat{\mathcal{A}}_{i}\).



Now, we are in a position to define an interpolation operator \(R_{h}\!\in\!\mathcal{L}(L^{1}(\Omega)\); \(\Theta_{h})\) by a local \(L^{2}\) projection. Let \(\mathcal{A}_{i}\) be any macro-element, \(\hat{\mathcal{A}}_{i}\) its reference region and \(\hat{v}\!\in\!L^{1}(\mathcal{A}_{i})\); let \(\hat{R}_{i}\hat{v}\) be the unique polynomial of \(P_{k}(\hat{\mathcal{A}}_{i})\) determined by:

\[\int_{\hat{\mathcal{A}}_{i}}(\hat{R}_{i}\hat{v}-\hat{v})p\,d\hat{x}=0\quad\; \forall p\!\in\!P_{k}(\hat{\mathcal{A}}_{i}).\] (108)

Then, for \(v\!\in\!L^{1}(\Omega)\) we define \(R_{h}v\!\in\!\Theta_{h}\) by

\[R_{h}v=\sum_{i=1}^{N_{h}}\hat{R}_{i}(v\circ F_{d_{i}})(\hat{a}_{i})\theta_{i},\] (109)

where \(\hat{a}_{i}=F_{d_{i}}^{-1}(a_{i})\). It is proved in Clement [21] and Bernardi (loc. cit.) that this

Figure 6: Examples of regions \(\mathcal{A}_{i}\) and their reference regions \(\hat{\mathcal{A}}_{i}\)
