_In addition, if the mapping \(\lambda\to(\mathbf{u}(\lambda),p(\lambda))\) is continuous from \(\Lambda\) into \(H^{m+1}(\Omega)^{N}\times H^{m}(\Omega)\) for some integer \(m\) with \(1\leqslant m\leqslant l\), we have for all \(\lambda\in\Lambda\)_:

\[|\mathbf{u}_{h}(\lambda)-\mathbf{u}(\lambda)|_{1,\,\Omega}+\|p_{h}(\lambda)-p( \lambda)\|_{0,\,\Omega}\leqslant Kh^{m}.\] (4.7)

_Proof_. The idea is to apply Theorem 3.3 with the following choice:

\[X=H^{1}_{0}(\Omega)^{N}\times L^{2}_{0}(\Omega),\ \ \ \ \ Y=H^{-1}(\Omega)^{N}.\]

The operator \(T\in\mathcal{L}(Y;X)\) is the Stokes operator:

for \(\mathbf{f}\) given in \(Y,\ T\mathbf{f}=(\mathbf{v},q)\in X\) is the solution of the Stokes problem:

\[\left\{\begin{aligned} -\,\Delta\mathbf{v}\,+\,\mathbf{grad}\,q& =\mathbf{f}\\ \operatorname{div}\mathbf{v}&=0\\ \mathbf{v}&=\mathbf{0}\end{aligned}\right.\ \text{ in }\Omega,\] (4.8)

For a fixed \(\mathbf{f}\), the \(\mathcal{C}^{\infty}\)-mapping \(G\): \(\mathbb{R}_{+}\times X\to Y\) is defined like in (3.8):

\[G(\lambda,v)=\lambda\biggl{(}\sum_{j=1}^{N}v_{j}\partial\mathbf{v}/\partial x_ {j}-\mathbf{f}\biggr{)},\ \ \ \ v=(\mathbf{v},q)\in X,\]

and

\[D_{u}G(\lambda,v)\cdot w=\lambda\sum_{j=1}^{N}\left(v_{j}\partial\mathbf{w}/ \partial x_{j}+w_{j}\partial\mathbf{v}/\partial x_{j}\right),\ \ \ \ w=(\mathbf{w},r)\in X.\]

Let us determine the space \(Z\). In view of Theorem I.1.3, we know that

\[H^{1}_{0}(\Omega)\subset L^{6}(\Omega)\ \ \ \text{for }N\leqslant 3\]

and the imbedding of \(H^{1}_{0}(\Omega)\) into \(L^{p}(\Omega)\) is compact for \(p<6\). Next, applying Corollary I.1.1 observe that for \(\mathbf{v}\) and \(\mathbf{w}\) in \(H^{1}_{0}(\Omega)^{N}\), we have

\[\sum_{j=1}^{N}\left(v_{j}\partial\mathbf{w}/\partial x_{j}+w_{j}\partial \mathbf{v}/\partial x_{j}\right)\in L^{3/2}(\Omega)^{N}.\]

Finally, applying again Theorem I.1.3 we find that \(L^{q}(\Omega)\) is compactly imbedded in \(H^{-1}(\Omega)\) whenever \(q>6/5\). It stems from these remarks that we can choose

\[Z=L^{3/2}(\Omega)^{N}\subset Y\ \ \ \text{with a compact imbedding}\]

and (3.36) holds.

Now, let \(X_{h}=W_{0h}\times M_{h}\) and let \(T_{h}\in\mathcal{C}(Y;X_{h})\) be the approximate Stokes operator defined by:

\[T_{h}\mathbf{f}=(\mathbf{v}_{h},q_{h})\in X_{h}\ \ \ \text{is the solution of}\] \[\biggl{\{}\begin{aligned} (\mathbf{grad}\,\mathbf{v}_{h}, \mathbf{grad}\,\mathbf{w}_{h})-(q_{h},\operatorname{div}\mathbf{w}_{h})& =\langle\mathbf{f},\mathbf{w}_{h}\rangle\ \ \ \ \ \forall\mathbf{w}_{h}\in W_{0h},\\ (r_{h},\operatorname{div}\mathbf{v}_{h})&=0\ \ \ \ \ \forall r_{h}\in M_{h}.\end{aligned}\]

It follows from Theorem II.1.8 that, owing to the hypotheses H1, H2 and H3
