Now, we are in a position to establish the following existence result for Problem (P).

**Theorem 1.2**.: _Assume that the following hypotheses hold:_

(i) _there exists a constant \(\alpha>0\) such that_

(1.9) \[a(v;v,v)\geqslant\alpha\|\,v\,\|_{X}^{2}\qquad\forall v\in V;\]

(ii) _the space \(V\) is separable and, for all \(v\in V,\) the mapping_

\[u\to a(u;u,v)\]

_is sequentially weakly continuous on \(V,\) i.e.,_

(1.10) \[\text{weak}\lim_{m\to\infty}u_{m}=u\quad\text{in }V\quad\text{implies} \quad\lim_{m\to\infty}a(u_{m};u_{m},v)=a(u;u,v)\qquad\forall v\in V.\]

_Then, Problem (P) has at least one solution \(u\in V.\)_

Proof.: \(1^{\circ})\) We begin by constructing a sequence of approximate solutions by _Galerkin's method._ Since the space \(V\) is separable, there exists a sequence \((w_{m})_{m\geqslant 1}\) in \(V\) such that:

(i) for all \(m\geqslant 1,\) the elements \(w_{1},\,\ldots,\,w_{m}\) are linearly independent;

(ii) the finite linear combinations of the \(w_{i},\,\sum_{i}v_{i}w_{i},\) are dense in \(V.\)

Such a sequence \((w_{m})_{m\geqslant 1}\) is called a "basis" of the separable space \(V.\)

We denote by \(V_{m}\) the subspace of \(V\) spanned by \(w_{1},\,\ldots,\,w_{m}.\) Then, we approximate Problem (P) by the following problem, called _Problem_ (P\({}_{m}\)):

_Find \(u_{m}\in V_{m}\) satisfying_

(1.11) \[a(u_{m};u_{m},v)=\langle l,v\rangle\qquad\forall v\in V_{m}.\]

If we set

\[u_{m}=\sum_{i=1}^{m}v_{i}w_{i},\]

we find that Problem (P\({}_{m}\)) amounts to solve a system of \(m\) nonlinear equations in the \(m\) unknowns \(v_{i}.\)

Let us now show that, for each \(m,\) Problem (P\({}_{m}\)) has at least one solution. We introduce the mapping \(\mathcal{G}_{m}\): \(V_{m}\to V_{m}\) defined by

\[(\mathcal{G}_{m}(v),w_{i})=a(v;v,w_{i})-\langle l,w_{i}\rangle,\quad\ 1\leqslant i \leqslant m,\]

where \((.,.)\) is the scalar product in \(X.\) Hence, \(u_{m}\in V_{m}\) is a solution of Problem (P\({}_{m}\)) if and only if \(\mathcal{G}_{m}(u_{m})=0.\) Since

\[(\mathcal{G}_{m}(v),v)=a(v;v,v)-\langle l,v\rangle\qquad\forall v\in V_{m},\]

it follows from the hypothesis (1.9) that

\[(\mathcal{G}_{m}(v),v)\geqslant(\alpha\|\,v\,\|_{X}-\,\|\pi l\|_{V^{\prime}}) \|\,v\,\|_{X}.\]
