Then

\[\lim_{m\to\infty}\|u_{m}-u\|_{X}=0.\]

Note that \(u_{0}\) need not be picked in \(S_{\mu}\) since, for any \(u_{0}\in V\), \(u_{1}=T(u_{0})\pi l\) is necessarily in \(S_{\mu}\).

We end this paragraph by solving Problem (Q). As mentioned in the beginning, the analysis parallels that of the linear case.

**Theorem 1.4**.: _Assume that the bilinear form \(b(.,.)\) satisfies the inf-sup condition_

(1.18) \[\inf_{\mu\in M}\sup_{v\in X}\frac{b(v,\mu)}{\|v\|_{X}\|\mu\|_{M}}\geqslant\beta>0.\]

_Then, for each solution \(u\) of Problem (P), there exists a unique \(\lambda\in M\) such that the pair \((u,\lambda)\) is a solution of Problem (Q)._

Proof.: Assume that \(u\in V\) is a solution of Problem (P). We must find \(\lambda\in M\) which satisfies the equation (1.3). But \(l-A(u)u\) belongs to the polar set \(V^{0}\) of \(V\). Moreover, the inf-sup condition (1.18) and Lemma I.4.1 imply that \(B^{\prime}\) is an isomorphism from \(M\) onto \(V^{0}\). Thus, there exists a unique \(\lambda\in M\) such that \((u,\lambda)\) is a solution of Problem (Q). 

_Remark 1.3_.: We can now extend the iterative scheme of Remark 1.2 in order to solve Problem (Q). Starting from any \(u_{0}\in V\), we construct the sequence \((u_{m},\lambda_{m})\) in \(X\times M\) by solving

(1.19) \[\left\{\begin{aligned} a(u_{m};u_{m+1},v)+b(v,\lambda_{m+1})& =\langle l,v\rangle\quad\quad\forall v\in X,\\ b(u_{m+1},\mu)&=0\quad\quad\forall\mu\in M.\end{aligned}\right.\]

Let us check that, under the assumptions (1.13), (1.14), (1.15) and (1.18), we have for any \(u_{0}\) in \(V\):

(1.20) \[\lim_{m\to\infty}\left\{\|u_{m}-u\|_{X}+\|\lambda_{m}-\lambda\|_{M}\right\}=0.\]

In fact, \(u_{m}\) belongs to the space \(V\) and satisfies (1.17). Hence by Remark 1.2, we get

\[\lim_{m\to\infty}\|u_{m}-u\|_{X}=0.\]

Moreover, using (1.1) and (1.19), we obtain

\[b(v,\lambda_{m}-\lambda)=a(u;u,v)-a(u_{m-1};u_{m},v)\quad\quad\forall v\in X\]

and by (1.18)

\[\|\lambda_{m}-\lambda\|_{M}\leqslant(1/\beta)\sup_{v\in X}\left\{\frac{a(u;u, v)-a(u_{m-1};u_{m},v)}{\|v\|_{X}}\right\}.\]

The desired result then follows from the convergence of \(u_{m}\) to \(u\) in \(X\) and the continuity properties of \(a(.;.,.)\).
