(4.18) \[\left\{\begin{aligned} X_{h}(\Omega_{r})=\{\mathbf{v}_{h}\!\in\!X_{h} \text{; }\text{supp}(\mathbf{v}_{h})\subset\Omega_{r}\},\\ Q_{h}(\Omega_{r})=\{q\!\mid_{\Omega_{r}};\,q\!\in\!Q_{h}\},\\ M_{h}(\Omega_{r})=Q_{h}(\Omega_{r})\cap L_{0}^{2}(\Omega_{r}). \end{aligned}\right.\]

Let us prove that the pair \((X_{h}(\Omega_{r}),M_{h}(\Omega_{r}))\) satisfies a local inf-sup condition.

**Theorem 4.2**.: _Suppose that \(\mathcal{T}_{h}\) is a regular triangulation of \(\Omega\) and that \(\mathcal{T}_{h}\) satisfies (4.17). Then there exists a constant \(\lambda^{*}>0,\) independent of \(h\) and \(r,\) such that:_

(4.19) \[\sup_{\mathbf{v}\in X_{h}(\Omega_{r})}\!\left[\left(\int_{\Omega_{r}}q\,\mathrm{ div}\,\mathbf{v}\,dx\right)\right]\!\!/\left|\mathbf{v}\right|_{1,\Omega_{r}}\! \right]\!\geqslant\lambda^{*}\!\left\|q\!\right\|_{0,\Omega_{r}},\ \ \ \ \ \forall q\!\in\!M_{h}(\Omega_{r}).\]

Proof.: Let \(J\) be the number of elements \(\kappa\) in \(\Omega_{r}\), and let us number them with an index \(i\) ranging from \(0\) to \(J\) such that \(\kappa_{i}\) is adjacent to \(\kappa_{i-1}\) and \(\kappa_{i+1}\) and \(\kappa_{0}=\kappa_{J}\) (like in Figure 18):

\[\Omega_{r}=\overbrace{\bigcup\limits_{i=1}^{\circ}\kappa_{i}}^{\circ}.\]

We denote by \(\kappa_{i}^{\prime}\) the side shared by \(\kappa_{i}\) and \(\kappa_{i+1}\), by \(\alpha_{i}\) the midpoint of \(\kappa_{i}^{\prime}\) and by \(a\), the vertex common to all the \(\kappa_{i}\) in \(\Omega_{r}\).

Like in Section 0.A.3, we associate with \(\Omega_{r}\) the reference set:

\[\hat{\Omega}=\bigcup\limits_{i=1}^{J}\hat{\kappa}_{i}\ \ \ \text{(cf. Figure 18)}\]

through the continuous, piecewise affine function \(F_{r}\) defined by:

\[F_{r}(\hat{\kappa}_{i})=\kappa_{i},\ \ \ \ F_{r}(\hat{x})=B_{i}\hat{x}+b_{i}\ \ \ \ \ \forall\hat{x}\!\in\!\hat{\kappa}_{i}.\]

Since the triangulation is _regular_, the number \(J\) is bounded above by a fixed constant \(I\) independent of \(r\) and as a consequence there are at most \(I\) different reference sets \(\hat{\Omega}.\) This means that all geometrical constants related to \(\hat{\Omega}\) and \(\hat{\kappa}_{i}\) can be bounded independently of \(h\) and \(r.\)

Now let \(q_{h}\) be an arbitrary element of \(Q_{h}(\Omega_{r})\) and let \(\mathbf{v}_{h}\) be a function in \(X_{h}(\Omega_{r})\) that satisfies \(\mathbf{v}_{h}(a_{r})=\mathbf{0}.\) Since \(\mathbf{v}_{h}\) vanishes on \(\partial\Omega_{r}\) and \(q_{h}\) belongs to \(H^{1}(\Omega_{r})\) we have:

\[\int_{\Omega_{r}}\mathrm{div}\,\mathbf{v}_{h}q_{h}\,dx=-\sum\limits_{i=1}^{J} \int_{\kappa_{i}}\mathbf{v}_{h}\cdot\mathbf{grad}\,q_{h}\,dx.\]

Observe that each component \(v\) of \(\mathbf{v}_{h}\) is a polynomial of \(P_{2}\) on \(\kappa_{i}\) that vanishes at the vertices of \(\kappa_{i}.\) Hence the following quadrature formula holds:

\[\int_{\kappa_{i}}v\,dx=\mathrm{meas}(\kappa_{i})(1/3)\{v(\alpha_{i})+v(\alpha_ {i-1})\}.\]

As \(\mathbf{grad}\,q_{h}\) is constant on each \(\kappa_{i}\) (say \(\mathbf{grad}\,q_{h}|_{\kappa_{i}}=\mathbf{g}_{i}\)), this formula yields:

(4.20) \[\int_{\Omega_{r}}\mathrm{div}\,\mathbf{v}_{h}q_{h}\,dx=-(1/3)\sum\limits_{i=1}^{ J}\mathrm{meas}(\kappa_{i})\{\mathbf{v}(\alpha_{i})+\mathbf{v}(\alpha_{i-1})\} \cdot\mathbf{g}_{i}.\]
