_Then Problems (Q) and (Q\({}^{\varepsilon}\)) for \(\varepsilon\leqslant 1\) both have one and only one solution \((u,\lambda)\) and \((u^{\varepsilon},\lambda^{\varepsilon})\) in \(X\times M\). Moreover, the following error bound holds for \(\varepsilon\leqslant\varepsilon_{0}\) small enough_

\[\|u^{\varepsilon}-u\|_{X}+\|\lambda^{\varepsilon}-\lambda\|_{M}\leqslant K \varepsilon(\|l\|_{X^{\varepsilon}}+\|\chi\|_{M^{\varepsilon}}),\] (4.32)

_where the constant \(K\) depends only upon \(\alpha\), \(\beta\), \(\|\,a\|\), \(\|b\|\) and \(\|\,c\,\|\)._

_Proof_. Hypothesis (4.31) implies that the bilinear form \(a(.,.)\) is \(V\)-elliptic. Hence, by Corollary 4.1, Problem (Q) has a unique solution \((u,\lambda)\in X\,\times\,M\).

Now, it follows from (4.25) and (4.31) that the bilinear form

\[u,\,v\to a(u,v)+(1/\varepsilon)\langle C^{-1}\,Bu,\,Bv\rangle\]

is \(X\)-elliptic when \(\varepsilon\leqslant 1\). Hence Problem (P\({}^{\varepsilon}\)) has exactly one solution \(u^{\varepsilon}\) in \(X\). Therefore, if we define \(\lambda^{\varepsilon}\) by (4.29) then \((u^{\varepsilon},\lambda^{\varepsilon})\) is the only solution of Problem (Q\({}^{\varepsilon}\)).

It remains to establish the bound (4.32). From (4.1) and (4.27), (4.2) and (4.28), we get:

\[\left\{\begin{aligned} a(u^{\varepsilon}-u,v)+b(v,\lambda^{ \varepsilon}-\lambda)&=0&\quad\forall v\in X,\\ -\varepsilon c(\lambda^{\varepsilon},\mu)+b(u^{\varepsilon}-u,\mu)& =0&\quad\forall\mu\in M.\end{aligned}\right.\] (4.33)

The first equation (4.33) together with (4.9) yields:

\[\beta\|\lambda^{\varepsilon}-\lambda\|_{M}\leqslant\sup_{v\in X}\frac{b(v, \lambda^{\varepsilon}-\lambda)}{\|v\|_{X}}\leqslant\|a\|\,\|u^{\varepsilon}- u\|_{X}\]

whence

\[\|\lambda^{\varepsilon}-\lambda\|_{M}\leqslant(\|a\|/\beta)\|u^{\varepsilon} -u\|_{X}.\] (4.34)

Next, by taking \(v=u^{\varepsilon}-u\) and \(\mu=\lambda^{\varepsilon}-\lambda\) in (4.33) we find:

\[a(u^{\varepsilon}-u,u^{\varepsilon}-u)=-\varepsilon c(\lambda,\lambda^{ \varepsilon}-\lambda)-\varepsilon c(\lambda^{\varepsilon}-\lambda,\lambda^{ \varepsilon}-\lambda)\leqslant-\varepsilon c(\lambda,\lambda^{\varepsilon}- \lambda).\]

Then (4.34) gives

\[a(u^{\varepsilon}-u,u^{\varepsilon}-u)\leqslant\varepsilon(\|a\|\,\|c\|/\beta) \|\lambda\|_{M}\|u^{\varepsilon}-u\|_{X}.\]

Besides that, we have by the second equation (4.33):

\[B(u^{\varepsilon}-u)=\varepsilon C\lambda^{\varepsilon}.\]

Therefore, we obtain

\[\langle C^{-1}\,B(u^{\varepsilon}-u),B(u^{\varepsilon}-u)\rangle=\varepsilon ^{2}\langle C\lambda^{\varepsilon},\lambda^{\varepsilon}\rangle=\varepsilon^ {2}c(\lambda^{\varepsilon},\lambda^{\varepsilon})\leqslant\varepsilon^{2}\|c \|\,\|\lambda^{\varepsilon}\|_{M}^{2},\]

and by (4.34)

\[\langle C^{-1}\,B(u^{\varepsilon}-u),B(u^{\varepsilon}-u)\rangle\leqslant \varepsilon^{2}\|c\|\,\{(\|a\|/\beta)\|u^{\varepsilon}-u\|_{X}+\|\lambda\|_{M }\}^{2}.\]

Hence, Hypothesis (4.31) yields an inequality of the form

\[\alpha x^{2}\leqslant\varepsilon^{2}C_{1}(\|\lambda\|_{M}+x)^{2}+\varepsilon C _{2}\|\lambda\|_{M}x,\]
