the simplest alternative is to replace (6.41) by:

(6.42) \[u^{n+1}=u^{n}-[D_{u}F(\lambda,u^{0})]^{-1}\cdot F(\lambda,u^{n})\ \ \ \ \ n\geqslant 0,\]

or equivalently

\[D_{u}F(\lambda,u^{0})\cdot(u^{n+1}-u^{n})=-F(\lambda,u^{n}).\]

We are going to prove that both schemes are convergent.

**Theorem 6.3**.: _Assume that \(D_{u}F(\lambda,v)\) is Lipschitz-continuous with respect to \(v\) in the ball \(S(u;\alpha)\), i.e. there exists a constant \(K>0\) such that_

(6.43) \[\|D_{u}F(\lambda,v)-D_{u}F(\lambda,v^{\star})\|_{\mathcal{L}(X;\mathcal{X})} \leqslant K\,\|v-v^{\star}\|_{X}\ \ \ \ \ \forall v,v^{\star}\in S(u;\alpha).\]

_Then there exists an \(\alpha^{\prime}\) with \(0<\alpha^{\prime}\leqslant\alpha\) such that for each initial guess \(u^{0}\) in \(S(u;\alpha^{\prime})\) the Newton's algorithm (6.41) determines a unique sequence \((u^{n})\subset S(u;\alpha^{\prime})\) that converges to the solution \(u\) of (6.40). Furthermore the convergence is quadratic_:

(6.44) \[\|u^{n+1}-u\|_{X}\leqslant C\,\|u^{n}-u\|_{X}^{2},\ \ \ \ \ C>0.\]

_Likewise_, _there exists an \(\alpha^{\prime\prime}\) with \(0<\alpha^{\prime\prime}\leqslant\alpha\) such that for each initial value \(u^{0}\) in \(S(u;\alpha^{\prime\prime})\) the scheme (6.42) determines a unique sequence \((u^{n})\subset S(u;\alpha^{\prime\prime})\) that converges to \(u\). But the convergence is only linear_:

(6.45) \[\|u^{n+1}-u\|_{X}\leqslant C\,\|u^{n}-u\|_{X},\ \ \ \ \ C<1.\]

Proof.: To begin with, it follows from (6.43) and Lemma 3.3 that there exists an \(\alpha^{\prime}\) with \(0<\alpha^{\prime}\leqslant\alpha\) such that \(D_{u}F(\lambda,v)\) is an isomorphism of \(X\) onto \(\mathcal{X}\) for all \(v\) in \(S(u;\alpha^{\prime})\). Indeed, if we take \(F_{h}=F,\tilde{u}_{h}=v,\gamma=\|[D_{u}F(\lambda,u)]^{-1}\,\|_{\mathcal{L}( \mathcal{L};\mathcal{X})},\mu=\|\,D_{u}F(\lambda,\)\(u)-D_{u}F(\lambda,v)\|_{\mathcal{L}(X;\mathcal{X})}\) then Lemma 3.3 says that \(D_{u}F(\lambda,v)\) is an isomorphism of \(X\) onto \(\mathcal{X}\) provided that \(\gamma\mu<1\). In view of (6.43), this inequality holds if we choose \(\alpha^{\prime}<\operatorname{Min}(\alpha,1/(\gamma K))\). In particular, we can take

(6.46) \[\alpha^{\prime}\leqslant 1/(2\gamma K)\]

and formula (3.16) gives the bound

(6.47) \[\|[D_{u}F(\lambda,v)]^{-1}\,\|_{\mathcal{L}(\mathcal{X};\mathcal{X})}\leqslant 2\gamma.\]

Now let us prove that when \(u^{0}\) belongs to \(S(u;\alpha^{\prime})\) with \(\alpha^{\prime}\) satisfying (6.46) then the scheme (6.41) defines a sequence \((u^{n})\) in \(S(u;\alpha^{\prime})\) that converges to \(u\). We proceed by induction: suppose that \(u^{n}\) belongs to \(S(u;\alpha^{\prime})\); then \([D_{u}F(\lambda,u^{n})]^{-1}\) exists and

\[u^{n+1}-u=u^{n}-u+[D_{u}F(\lambda,u^{n})]^{-1}\cdot(F(\lambda,u)-F(\lambda,u^ {n})).\]

In other words

\[u^{n+1}-u =[D_{u}F(\lambda,u^{n})]^{-1}[F(\lambda,u)-F(\lambda,u^{n})-D_{u} F(\lambda,u^{n})\cdot(u-u^{n})]\] \[=[D_{u}F(\lambda,u^{n})]^{-1}\int_{0}^{1}[D_{u}F(\lambda,u^{n}+t(u -u^{n}))-D_{u}F(\lambda,u^{n})]\cdot(u-u^{n})\,dt.\]
