and we have characterized \(H^{\perp}\) and \(V^{\perp}\). Here, we are going to characterize \(H\) and \(V\) as spaces of **curl** of stream functions. This will show, in particular, that every function of \(L^{2}(\Omega)^{N}\) is the sum of the **curl** of a stream function and a gradient.



We shall make the following assumptions on \(\Omega\): \(\Omega\) is _bounded_, _connected_ but eventually multiply-connected, and its boundary \(\Gamma\) is _Lipschitz-continuous_. We shall denote by \(\Gamma_{0}\) the exterior boundary of \(\Omega\) (cf. Figure 2) and by \(\Gamma_{i}\), \(1\leq i\leq p\), the other components of \(\Gamma\). The duality between \(H^{-1/2}(\Gamma_{i})\) and \(H^{1/2}(\Gamma_{i})\) will be denoted by \(\langle\cdot,\cdot\rangle_{\Gamma_{i}}\). Finally, we shall assume that the dimension \(N\) is either \(2\) or \(3\).

### Decomposition of Two-Dimensional Vector Fields

**Theorem 3.1**.: _A function \(\mathbf{v}\) of \(L^{2}(\Omega)^{2}\) satisfies:_

(3.1) \[\operatorname{div}\mathbf{v}=0,\quad\ \ \langle\mathbf{v}\cdot\mathbf{n},1 \rangle_{\Gamma_{i}}=0\quad\text{for }0\leq i\leq p\]

_iff there exists a stream function \(\phi\) in \(H^{1}(\Omega)\) such that:_

(3.2) \[\mathbf{v}=\operatorname{\mathbf{curl}}\phi.\]

Proof.: \(1^{\circ}\)) Let us show that (3.2) implies (3.1). Let \(\phi\in H^{1}(\Omega)\) and set \(\mathbf{v}=\operatorname{\mathbf{curl}}\phi\). Clearly, \(\operatorname{div}\mathbf{v}=0\). Next, as \(\mathcal{D}(\Omega)\) is dense in \(H^{1}(\Omega)\), it suffices to prove that

\[\int_{\Gamma_{i}}\operatorname{\mathbf{curl}}\phi\cdot\mathbf{n}\,ds=0\quad \ \ \forall\phi\in\mathcal{D}(\Omega),\quad\ 0\leq i\leq p.\]

This is indeed true since

\[\int_{\Gamma_{i}}\operatorname{\mathbf{curl}}\phi\cdot\mathbf{n}\,ds=\int_{ \Gamma_{i}}(\partial\phi/\partial\tau)\,ds=0.\]
