In addition to the ellipticity of \(c(.,.)\), assume that the form \(a_{r}^{h}(.,.)\) is \(X_{h}\)-elliptic: there exists a constant \(\alpha^{*}>0\) such that

\[a_{r}^{h}(v_{h},v_{h})\geq\alpha^{*}\|v_{h}\|_{X}^{2}\ \ \ \ \ \forall v_{h}\in X_{h}.\] (32)

Then the _simple gradient algorithm with optimal parameter_ has the following discrete version:

\(1^{\circ})\) Given an initial guess \(\lambda_{h}^{0}\in M_{h}\), compute the solution \(u_{h}^{0}\in X_{h}\) of the problem

\[a_{r}^{h}(u_{h}^{0},v_{h})=\langle l,v_{h}\rangle+b(v_{h},rC_{h}^{-1}\chi- \lambda_{h}^{0})\ \ \ \ \ \forall v_{h}\in X_{h};\]

\(2^{\circ})\) For \(m\geq 0\), knowing \((u_{h}^{m},\lambda_{h}^{m})\in X_{h}\times M_{h}\), determine \((z_{h}^{m},g_{h}^{m})\in X_{h}\times M_{h}\), \(\rho_{h}^{m}\in\mathbb{R}\) and the pair \((u_{h}^{m+1},\lambda_{h}^{m+1})\in X_{h}\times M_{h}\) by:

\[\left\{\begin{aligned} \text{(a)}&&\left\{c(g_{h}^{m}, \mu_{h})=\langle\chi,\mu_{h}\rangle-b(u_{h}^{m},\mu_{h})\ \ \ \ \ \forall\mu_{h}\in M_{h},\right.\\ &\left.a_{r}^{h}(z_{h}^{m},v_{h})=b(v_{h},g_{h}^{m})\ \ \ \ \ \forall v_{h}\in X_{h},\right.\\ \left.\text{(b)}&&\rho_{h}^{m}=\frac{c(g_{h}^{m},g _{h}^{m})}{b(z_{h}^{m},g_{h}^{m})},\\ \text{(c)}&&\left\{\begin{aligned} \lambda_{h}^{m+1}& =\lambda_{h}^{m}-\rho_{h}^{m}g_{h}^{m},\\ u_{h}^{m+1}&=u_{h}^{m}+\rho_{h}^{m}z_{h}^{m}.\end{aligned} \right.\end{aligned}\right.\] (33)

Needless to say, the above scheme is a gradient algorithm only when the bilinear forms \(a(.,.)\) and \(c(.,.)\) are symmetric. Then the following result is a direct consequence of Corollary I.4.4.

**Theorem 1.5**: _Suppose the bilinear forms \(a_{r}^{h}(.,.)\), \(b(.,.)\) and \(c(.,.)\) satisfy respectively (32), (12) and (24) and assume that \(a(.,.)\) and \(c(.,.)\) are symmetric. Then the simple gradient algorithm (33) is convergent for every choice of the starting value \(\lambda_{h}^{0}\in M_{h}\):_

\[\lim_{m^{-\infty}}\left\{\|u_{h}^{m}-u_{h}\|_{X}+\|\lambda_{h}^{m}-\lambda_{h }\|_{M}\right\}=0.\]

Like in Section I.4.4, observe that the simple gradient algorithm can converge without optimal parameters. In that case, the bilinear form \(a(.,.)\) need not be symmetric and we have the analogue of Theorem I.4.7:

**Theorem 1.6**: _We retain all hypotheses of Theorem 1.5 except the symmetry assumption on \(a(.,.)\). Then the algorithm_ (33a)_(13c) _is convergent for every choice of the initial guess \(\lambda_{h}^{0}\in M_{h}\) and every sequence of numbers \((\rho_{h}^{m})\) in the range:_

\[0<\inf_{m}\rho_{h}^{m}\leq\sup_{m}\rho_{h}^{m}<2\gamma^{*}\tilde{\sigma}_{r}^ {*}\]

_where_

\[\tilde{\sigma}_{r}^{*}=\inf_{v_{h}\in X_{h}}(a_{r}^{h}(v_{h},v_{h})/\|B_{h}v_{ h}\|_{M_{h}}^{2}).\]
