\[\Psi=\left\{\phi\in L^{2}(\Omega)^{3};\,\operatorname{div}\phi\in H^{1}(\Omega), \,\operatorname{\mathbf{curl}}\phi\in H^{1}_{0}(\Omega)^{3},\,\phi\,\times\, \mathbf{n}\mid_{\Gamma}=\mathbf{0},\right.\]

\[\left.\int_{\Gamma_{i}}\phi\cdot\mathbf{n}\,ds=0,\,0\leqslant i\leqslant p\right\}\]

with the norm

\[\|\phi\|=\{\,\|\phi\|_{0,\Omega}^{2}+\|\operatorname{div}\phi\|_{1,\Omega}^{2} +\|\operatorname{\mathbf{curl}}\phi\|_{1,\Omega}^{2}\}^{1/2}.\]

Recall that this norm is equivalent to \(\|\mathcal{A}\phi\|_{0,\Omega}\) (cf. Lemma I.5.2) and for the sake of brevity we denote: \(|\phi|=\|\mathcal{A}\phi\|_{0,\Omega}\).

Since \(\operatorname{div}\mathbf{u}=0\) and \(\Omega\) is simply-connected, \(\mathbf{u}\) has a unique vector potential \(\psi\) in \(\Psi\) that satisfies

\[\mathbf{u}=\operatorname{\mathbf{curl}}\psi,\quad\operatorname{div}\psi=0.\]

Then, taking into account the identity:

(2.30) \[\sum_{i,j=1}^{3}u_{j}(\partial u_{i}/\partial x_{j})v_{i}=(\operatorname{ \mathbf{curl}}\mathbf{u}\times\mathbf{u})\cdot\mathbf{v}+(1/2)\operatorname{ \mathbf{grad}}(\|\mathbf{u}\|^{2})\cdot\mathbf{v},\]

we derive exactly like in Section I.5.3 that this vector \(\psi\) is a solution of the nonlinear biharmonic problem:

_Find \(\psi\) in \(\Psi\) such that_

(2.31) \[v(\mathcal{A}\psi,\mathcal{A}\phi)-\int_{\Omega}(\mathcal{A}\psi\times \operatorname{\mathbf{curl}}\psi)\cdot\operatorname{\mathbf{curl}}\phi\,dx= \langle\mathbf{f},\operatorname{\mathbf{curl}}\phi\rangle\quad\quad\forall \phi\in\Psi.\]

Therefore, it follows from Theorem 2.1 that, for each \(\mathbf{f}\) in \(H^{-1}(\Omega)^{3}\), Problem (2.31) has at least one divergence-free solution \(\psi\) in \(\Psi\).

But conversely, we cannot establish in general that every solution \(\psi\) of (2.31) is a vector potential of a solution \(\mathbf{u}\) of the Navier-Stokes Problem (2.1) (2.3). Indeed, setting

\[\mathbf{w}=\operatorname{\mathbf{curl}}\psi,\]

we infer from (2.31) that \(\mathbf{w}\) satisfies: \(\mathbf{w}\in V,\)

\[v(\operatorname{\mathbf{grad}}\mathbf{w},\operatorname{\mathbf{grad}} \mathbf{v})+\int_{\Omega}\operatorname{\mathbf{curl}}\mathbf{w}\times \mathbf{w}\cdot\mathbf{v}\,dx=\langle\mathbf{f},\mathbf{v}\rangle+\int_{ \Omega}\operatorname{\mathbf{grad}}(\operatorname{div}\psi)\times\mathbf{w} \cdot\mathbf{v}\,dx\]

\[\forall\mathbf{v}\in V.\]

Unless \(\int_{\Omega}\operatorname{\mathbf{grad}}(\operatorname{div}\psi)\times \mathbf{w}\cdot\mathbf{v}\,dx=0\) (and this property does not stem from (2.31)), we see that \(\mathbf{w}\) does not satisfy the Navier-Stokes equations.

The trilinear form naturally attached to Problem (2.31) is

(2.32) \[a_{1}(\phi;\psi,\chi)=-\int_{\Omega}(\mathcal{A}\phi\times\operatorname{ \mathbf{curl}}\psi)\cdot\operatorname{\mathbf{curl}}\chi\,dx.\]

Clearly, this form satisfies (2.4) and (2.5). In addition, like in Lemma 2.1, \(a_{1}(.;.,.)\)
