We finish this section with a number of inverse inequalities satisfied, for arbitrary \(N\), by the functions of \(\Theta_{h}\).

**Lemma A.6**.: _Let \(r\) and \(p\) be reals with \(1\leqslant r\), \(p\leqslant\infty\). Under the assumption that \(\mathcal{T}_{h}\) is regular if \(\ 1/r-1/p\geqslant 1/N\) or \(\mathcal{T}_{h}\) is uniformly regular otherwise, there exists a constant \(C>0\) independent of \(h\) and \(\kappa\) such that:_

(A.31) \[|v|_{{}_{1,\,r,\kappa}}\leqslant Ch^{N(1/r-1/p)-1}\,\|\,v\|_{{}_{0,\,p,\kappa} }\qquad\forall\kappa\in\mathcal{T}_{h}\,\,\,\,\,\,\,\,\,\forall v\in\Theta_{h}.\]

Proof.: Let \(v\in\Theta_{h}\); owing to (A.8), (A.2) and (A.3) we have:

\[|v|_{{}_{1,\,r,\kappa}}\leqslant C_{1}(1/\rho_{\kappa})(\mathrm{meas}(\kappa) )^{1/r}|\hat{v}|_{{}_{1,\,r,\kappa}}.\]

But since \(\hat{v}\) belongs to the finite-dimensional space \(P_{k}\) on \(\hat{\kappa}\), we have

\[|\hat{v}|_{{}_{1,\,r,\hat{\kappa}}}\leqslant C_{2}\,\|\hat{v}\|_{{}_{0,\,p, \hat{\kappa}}}\]

where the constant \(C_{2}\) depends only on \(r\), \(p\), \(k\), \(N\) and the geometry of \(\hat{\kappa}\). Then applying (A.7) and (A.3) we get:

(A.32) \[|v|_{{}_{1,\,r,\kappa}}\leqslant C_{3}(1/\rho_{\kappa})(\mathrm{meas}(\kappa) )^{1/r-1/p}\|\,v\|_{{}_{0,\,p,\kappa}}.\]

In view of (A.4), if \(N(1/r-1/p)\geqslant 1\) the right-hand side of (A.32) involves a positive power of \(h_{\kappa}\) and hence the regularity of \(\mathcal{T}_{h}\) is sufficient to yield (A.31). Otherwise, the uniform regularity of \(\mathcal{T}_{h}\) is necessary to draw the same conclusion. 

**Corollary A.3**.: _Let \(r\) and \(p\) be like in Lemma A.6 and assume \(\mathcal{T}_{h}\) is a uniformly regular triangulation of \(\Omega\). There exists a constant \(C>0\) independent of \(h\) such that_:__

(A.33) \[|v|_{{}_{1,\,r,\Omega}}\leqslant Ch^{-1+\mathrm{Min}(0,\,N/r-N/p)}\|\,v\|_{{}_ {0,\,p,\Omega}}\,\,\,\,\,\,\,\,\,\,\forall v\in\Theta_{h}.\]

Proof.: If \(r\geqslant p\) we derive (A.33) from (A.31) and Jensen's inequality:

(A.34) \[\left(\sum\limits_{i=1}^{I}|a_{i}|^{r}\right)^{1/r}\leqslant\left(\sum\limits_ {i=1}^{I}|a_{i}|^{p}\right)^{1/p}\]

which holds for every finite sum.

If \(r<p\), we use the discrete version of Holder's inequality:

(A.35) \[\left(\sum\limits_{i=1}^{I}|a_{i}|^{r}|b_{i}|^{1-r/p}\right)^{1/r}\leqslant \left(\sum\limits_{i=1}^{I}|a_{i}|^{p}\right)^{1/p}\left(\sum\limits_{i=1}^{I }|b_{i}|\right)^{1/r-1/p},\]

with \(|a_{i}|=\|v\|_{{}_{0,\,p,\kappa}}\), \(b_{i}=\mathrm{meas}(\kappa)\) and the summation runs over all \(\kappa\) of \(\mathcal{T}_{h}\). Thus the uniform regularity of \(\mathcal{T}_{h}\) and (A.32) yield:

\[|v|_{{}_{1,\,r,\Omega}}\leqslant C_{3}[\sigma/(\tau h)](\mathrm{meas}(\Omega ))^{1/r-1/p}\|\,v\|_{{}_{0,\,p,\Omega}}.\qed\]

**Lemma A.7**.: _Let \(r\) and \(p\) be like in Lemma A.6 and let \(m\) be a non-negative integer. If \(r\leqslant p\) or if the triangulation \(\mathcal{T}_{h}\) is uniformly regular and \(r>p\), there exists a
