Now, let \(\mu\) be any element of \(H^{1/2}(\Gamma)\). Then there exists an element \(\phi\) of \(H^{1}(\Omega)\) such that \(\phi=\mu\) on \(\Gamma\). Hence the above inequality implies that

\[\left|\int_{\Gamma}\mu\mathbf{v}\cdot\mathbf{n}\,ds\right|\leq\|\mathbf{v}\,\| _{H(\operatorname{div};\Omega)}\|\mu\|_{1/2,\,\Gamma}\ \ \ \ \ \forall\mu\in H^{1/2}(\Gamma),\ \ \ \ \ \forall\mathbf{v}\in \mathcal{D}(\bar{\Omega})^{N}.\]

Thus

\[\|\mathbf{v}\cdot\mathbf{n}\|_{-1/2,\,\Gamma}\leq\|\mathbf{v}\,\| _{H(\operatorname{div};\Omega)}.\]

Therefore, the linear mapping \(\gamma_{n}\colon\mathbf{v}\to\mathbf{v}\cdot\mathbf{n}\|_{\Gamma}\) defined on \(\mathcal{D}(\bar{\Omega})^{N}\) is continuous for the norm of \(H(\operatorname{div};\Omega)\). Since \(\mathcal{D}(\bar{\Omega})^{N}\) is dense in \(H(\operatorname{div};\Omega)\), \(\gamma_{n}\) can be extended by continuity to a mapping still called \(\gamma_{n}\in\mathcal{D}(H(\operatorname{div};\Omega);H^{-1/2}(\Gamma))\) such that:

(2.16) \[\|\gamma_{n}\|_{\mathcal{D}(H(\operatorname{div};\Omega);H^{-1/2}( \Gamma))}\leq 1.\qed\]

By extension, \(\gamma_{n}\mathbf{v}\) is called the normal component of \(\mathbf{v}\) on \(\Gamma\) and is denoted simply by \(\mathbf{v}\cdot\mathbf{n}\).

From Theorems 2.4 and 2.5, we derive the following Green's formula:

(2.17) \[(\mathbf{v},\mathbf{grad}\,\phi)+(\operatorname{div}\mathbf{v}, \phi)=\langle\mathbf{v}\cdot\mathbf{n},\phi\rangle_{\Gamma}\ \ \ \ \ \forall\mathbf{v}\in H(\operatorname{div};\Omega),\ \ \ \ \ \forall\phi\in H^{1}(\Omega).\]

As a consequence, we can now extend Green's formula for the Laplace operator to a wider range of functions.

**Corollary 2.6**.: _Let \(u\in H^{1}(\Omega)\) and \(\Delta u\in L^{2}(\Omega)\). Then \(\partial u/\partial n\in H^{-1/2}(\Gamma)\) and_

(2.18) \[(\mathbf{grad}\,u,\mathbf{grad}\,v)=-(\Delta u,v)+\langle\partial u/\partial n ,v\rangle_{\Gamma}\ \ \ \ \ \forall v\in H^{1}(\Omega).\]

The proof is left as an exercise.

Another interesting consequence is that now we can interpret properly the variational problem (N\({}^{\prime}\)) of Section 1.4 and show that it is equivalent to the Neumann's problem (N). We skip the proof, as it follows immediately from (2.18).

**Corollary 2.7**.: _Problem (1.37) and Problem (1.31) (1.32) (1.33) are equivalent._

The next two results give further information about \(\gamma_{n}\).

**Corollary 2.8**.: _We have:_

\[\mathcal{R}(\gamma_{n})=H^{-1/2}(\Gamma)\]

_and_

\[\|\gamma_{n}\|_{\mathcal{S}(H(\operatorname{div};\Omega);H\ \ \nu_{2}(\Gamma))}=1.\]

Proof.: Let \(\mu\in H^{-1/2}(\Gamma)\); we want to exhibit an element \(\mathbf{v}\) of \(H(\operatorname{div};\Omega)\) such that

\[\mathbf{v}\cdot\mathbf{n}=\mu\ \ \ \text{on}\ \Gamma\ \ \ \text{and}\ \ \ \ \|\mathbf{v}\cdot\mathbf{n}\|_{-1/2,\,\Gamma}\geq\|\mathbf{v}\|_{H( \operatorname{div};\Omega)}.\]
