\[h_{j}\in H^{3/2}(\Gamma_{j})\quad\quad 1\leqslant j\leqslant J\]

satisfying the matching conditions \(h_{j}(S_{j+1})=h_{j+1}(S_{j+1})\) and \(J\) functions:

\[g_{j}\in H^{1/2}(\Gamma_{j})\quad\quad 1\leqslant j\leqslant J\]

and consider the problem:

\[Find\ u\ \text{such that}\] (B \[{}^{\prime\prime}\] ) \[\left\{\begin{array}[]{l}\eqref{eq:h_j}&\Delta^{2}u=f\quad\text{ in }H^{-2}(\Omega),\\ \eqref{eq:h_j}&u=h_{j}\quad\text{on }\Gamma_{j}\\ \eqref{eq:h_j}&\partial u/\partial n=g_{j}\quad\text{on }\Gamma_{j}\end{array} \right\}\quad 1\leqslant j\leqslant J.\]

By virtue of Remark 1.1, we know that there exists a function \(u_{0}\) in \(H^{2}(\Omega)\) such that

\[u_{0}=h_{j},\quad\partial u_{0}/\partial n=g_{j}\quad\text{on }\Gamma_{j}, \quad\quad 1\leqslant j\leqslant J\]

and

\[\left\|u_{0}\right\|_{2,\Omega}\leqslant C_{3}\left\{\sum\limits_{j=1}^{J} \left(\left\|h_{j}\right\|_{3/2,\Gamma_{j}}^{2}+\left\|g_{j}\right\|_{1/2, \Gamma_{j}}^{2}\right)\right\}^{1/2}.\]

Hence the conclusion of Proposition 1.3 (with the functions \(h_{j}\) and \(g_{j}\) instead of \(g_{1}\) and \(g_{2}\)) applies also to Problem (B\({}^{\prime\prime}\)) in this case.

When the boundary of \(\Omega\) is sufficiently smooth, it is possible to derive more information about the regularity of \(u\).

**Theorem 1.11**.: _Let \(\Omega\) be a bounded open subset of \(\mathbb{R}^{N}\) with a boundary \(\Gamma\) of class \(\mathcal{C}^{k+3,1}\) for an integer \(k\geqslant-2\) and assume that the data \(f,\,g_{1}\) and \(g_{2}\) of the biharmonic Problem (B) satisfy:_

\[f\in H^{k}(\Omega),\quad\quad g_{1}\in H^{k+7/2}(\Gamma),\quad\quad g_{2}\in H ^{k+5/2}(\Gamma).\]

_Then \(u\in H^{k+4}(\Omega)\) and there exists a constant \(C=C(k,\Omega)\) such that_

(1.51) \[\left\|u\right\|_{k+4,\Omega}\leqslant C\left\{\left\|f\right\|_{k,\Omega}+ \left\|g_{1}\right\|_{k+7/2,\Gamma}+\left\|g_{2}\right\|_{k+5/2,\Gamma}\right\}.\]

But even when \(\Gamma\) has corners, the conclusion of Proposition 1.3 can be refined for the biharmonic problem with homogeneous boundary conditions.

**Theorem 1.12**.: _Assume that \(\Omega\) is a two-dimensional bounded polygon with no re-entrant corner. Then the mapping \(u\to\Delta^{2}u\) is an isomorphism from \(H^{3}(\Omega)\cap H^{2}_{0}(\Omega)\) onto \(H^{-1}(\Omega)\)._

This last result is fundamental to establish the regularity of the solution of the Stokes problem in a plane, convex polygon (cf. Grisvard [43]).
