\(Find\)\(\psi_{h}\!\in\!\varTheta_{h}\) and \(\omega_{h}\!\in\!\varTheta_{h}\) satisfying:_

(4.36a) \[\left\{\begin{aligned} & v(\mathbf{curl}\,\omega_{h},\mathbf{ curl}\,\phi_{h})+(\omega_{h}\,\mathbf{grad}\,\psi_{h},\mathbf{curl}\,\phi_{h})=( \mathbf{f},\mathbf{curl}\,\phi_{h})\quad\quad\forall\phi_{h}\!\in\!\varPhi_{h} ,\\ &(\mathbf{curl}\,\psi_{h},\mathbf{curl}\,\mu_{h})=(\omega_{h}, \mu_{h})\quad\quad\forall\mu_{h}\!\in\!\varTheta_{h};\end{aligned}\right.\]

_Find \(p_{h}^{\star}\!\in\!Q_{h}\) such that:_

(4.36b) \[(\mathbf{grad}\,p_{h}^{\star},\mathbf{grad}\,q_{h})=(\mathbf{f}-\omega_{h}\, \mathbf{grad}\,\psi_{h}-v\,\mathbf{curl}\,\omega_{h},\mathbf{grad}\,q_{h}) \quad\quad\forall q_{h}\!\in\!Q_{h}.\]

In other words, this problem can also be written as:

\[F_{h}(\lambda,u_{h})\equiv u_{h}+\,T_{h}G(\lambda,u_{h})=0,\]

with \(\lambda=1/v\), \(u_{h}=(\mathbf{curl}\,\psi_{h},\omega_{h},\lambda p_{h}^{\star})\!\in\!X_{h}\), \(G\) defined by (4.31) and \(T_{h}\) by (4.35).

Now, let us apply Theorem 3.3 with \(Z=Y\). Recall the approximation properties of the operator \(T_{h}\) derived in Section III.3.1 (cf. Theorem III.3.2). When \(\varOmega\) is a convex polygon, the Stokes problem has the regularity (4.18); in other words, if \(\mathbf{f}\) belongs to \(L^{t}(\varOmega)^{2}\) with \(r\leqslant t\leqslant 2\) the solution of the Stokes problem \((\mathbf{curl}\,\psi,o,p)\) belongs to \(W^{2,t}(\varOmega)\times W^{1,t}(\varOmega)\times W^{1,t}(\varOmega)\) and

\[\|\psi\|_{3,t,\varOmega}+\|\omega\|_{1,t,\varOmega}+|p|_{1,t,\varOmega}\leqslant C _{1}\,\|\mathbf{f}\|_{0,t,\varOmega}.\]

Hence, if \(\mathcal{T}_{h}\) is a uniformly regular family of triangulations of \(\varOmega\), we have the following estimates for the solution \((\mathbf{curl}\,\psi_{h},o_{h},p_{h})\) of Problem (4.35):

\[|\psi-\psi_{h}|_{1,s,\varOmega}+\|\omega-o_{h}\|_{0,\varOmega}+\|p-p_{h}\|_{0 ,\varOmega}\leqslant C_{2}h^{\alpha}\|\mathbf{f}\|_{0,t,\varOmega},\]

with \(r\leqslant t<2\), \(1/\!\gamma+1/t=1\), \(\alpha=1/\!\gamma\) when \(l=1\) and \(\alpha=2/\!\gamma\) when \(l\geqslant 2\). This settles (3.37) and (3.38). Therefore the conclusion of Theorem 3.3 holds and combined with Theorem III.3.1, it gives the next result.

**Theorem 4.4**.: \(1^{\circ}\)_Let \(\varOmega\) be a bounded, convex polygon and let \(\mathcal{T}_{h}\) be a uniformly regular family of triangulations of \(\varOmega\). For \(\mathbf{f}\!\in\!L^{t}(\varOmega)^{2}\), \(t\!\in\![r,2]\), let \(\{(\lambda,(\mathbf{curl}\,\psi(\lambda),\,\omega(\lambda),\lambda p^{\star}( \lambda)));\lambda=1/v\!\in\!\varLambda\}\) be a branch of nonsingular solutions of the Navier-Stokes Problem (4.32). Then for \(h\!\leqslant\!h_{0}\) small enough there exists a unique \(\mathcal{C}^{\infty}\) branch \(\{(\lambda,(\mathbf{curl}\,\psi_{h}(\lambda),\omega_{h}(\lambda),\lambda p_{h }^{\star}(\lambda)));\lambda=1/v\!\in\!\varLambda\}\) of solutions of Problem (4.36) that satisfies:_

\[\sup_{\lambda\in\varLambda}\{|\psi_{h}(\lambda)-\psi(\lambda)|_{1,s,\varOmega} +\|\omega_{h}(\lambda)-o(\lambda)\|_{0,\varOmega}+\|p_{h}^{\star}(\lambda)-p^{ \star}(\lambda)\|_{0,\varOmega}\}\] (4.37) \[\leqslant Ch^{\alpha}\quad\text{with }\alpha=\begin{cases}1/\!\gamma&\text{if }l=1\\ 2/\!\gamma&\text{if }l\geqslant 2,\end{cases}\]

\(1/t+1/\!\gamma=1\) _and the constant \(C\) is independent of \(h\) or \(\lambda\). This bound is still valid when \(t=2\) and either \(l\geqslant 2\) or \(\psi\) belongs also to \(W^{2,\,\infty}(\varOmega)\). When \(l=1\) and \(t=2\), the left-hand side of (4.37) is bounded by_

\[C(\varepsilon)h^{1/2-\varepsilon}\quad\text{for all }\varepsilon>0.\]
