**Theorem 2.4**.: _Let \(\Omega\) be a Lipschitz-continuous open subset of \(\mathbb{R}^{N}\) (not necessarily bounded). The space \(\mathcal{D}(\Omega)^{N}\) is dense in \(H(\operatorname{div};\Omega)\)._

Proof.: The proof is also based on property (2.14). Let \(l\) belong to \((H(\operatorname{div};\Omega))^{\prime}\), the dual space of \(H(\operatorname{div};\Omega)\). As this is a Hilbert space, we can associate with \(l\) a function \(\mathbf{l}\) of \(H(\operatorname{div};\Omega)\) such that:

\[\langle l,\mathbf{u}\rangle=\sum_{i=1}^{N}\left(l_{i},u_{i}\right)+\left(l_{N+ 1},\operatorname{div}\mathbf{u}\right)\quad\forall\mathbf{u}\in H( \operatorname{div};\Omega),\]

where

\[l_{N+1}=\operatorname{div}\mathbf{l}.\]

Now, assume that \(l\) vanishes on \(\mathcal{D}(\Omega)^{N}\) and let \(\tilde{l}_{i}\) denote the extension of \(l_{i}\) by zero outside \(\Omega\). The above formula may be rewritten as follows:

\[\int_{\mathbb{R}^{N}}\left\{\sum_{i=1}^{N}\tilde{l}_{i}\phi_{i}+\tilde{l}_{N+ 1}\operatorname{div}\phi\right\}dx=0\quad\forall\phi\in\mathcal{D}(\mathbb{R} ^{N})^{N}.\]

This equality implies that, in the sense of distributions on \(\mathbb{R}^{N}\),

\[\mathbf{\tilde{l}}=\mathbf{grad}\,\tilde{l}_{N+1}.\]

Thus \(\tilde{l}_{N+1}\in H^{1}(\mathbb{R}^{N})\), since \(\mathbf{\tilde{l}}\in L^{2}(\mathbb{R}^{N})^{N}\). Then, it follows from Theorem 1.2\(2^{\circ})\) that \(l_{N+1}\in H^{1}_{0}(\Omega)\). As \(\mathcal{D}(\Omega)\) is dense in \(H^{1}_{0}(\Omega)\), let \((\psi_{\mu})_{\mu\geqslant 1}\) be a sequence of \(\mathcal{D}(\Omega)\) that tends to \(l_{N+1}\) in \(H^{1}(\Omega)\). Then

\[\langle l,\mathbf{u}\rangle=\lim_{\mu\to\infty}\left\{(\mathbf{grad}\,\psi_{ \mu},\mathbf{u})+(\psi_{\mu},\operatorname{div}\mathbf{u})\right\}=0\quad \forall\mathbf{u}\in H(\operatorname{div};\Omega).\]

Therefore, if \(l\) vanishes on \(\mathcal{D}(\Omega)^{N}\) then \(l\) also vanishes on \(H(\operatorname{div};\Omega)\), thus proving the required density. 

The next theorems concern the normal component of boundary values of functions of \(H(\operatorname{div};\Omega)\).

**Theorem 2.5**.: _The mapping \(\gamma_{n}\colon\mathbf{v}\to\mathbf{v}\cdot\mathbf{n}|_{\Gamma}\) defined on \(\mathcal{D}(\Omega)^{N}\) can be extended by continuity to a linear and continuous mapping, still denoted by \(\gamma_{n}\), from \(H(\operatorname{div};\Omega)\) into \(H^{-1/2}(\Gamma)\)._

Proof.: Let \(\phi\in\mathcal{D}(\Omega)\) and \(\mathbf{v}\in\mathcal{D}(\Omega)^{N}\). The following Green's formula holds:

\[(v,\mathbf{grad}\,\phi)+(\operatorname{div}\mathbf{v},\phi)=\int_{\Gamma}\phi \mathbf{v}\cdot\mathbf{n}\,ds.\]

As \(\mathcal{D}(\Omega)\) is dense in \(H^{1}(\Omega)\), this equality is still valid for \(\phi\) in \(H^{1}(\Omega)\) and \(\mathbf{v}\) in \(\mathcal{D}(\Omega)^{N}\). Therefore,

\[\left|\int_{\Gamma}\phi\mathbf{v}\cdot\mathbf{n}\,ds\right|\leqslant\left\| \mathbf{v}\right\|_{H(\operatorname{div};\Omega)}\left\|\phi\right\|_{1, \Omega}\quad\forall\phi\in H^{1}(\Omega),\quad\forall\mathbf{v}\in\mathcal{D}( \Omega)^{N}.\]
