More precisely, let \(\kappa\) be a bounded and open subset of \(\mathbb{R}^{2}\) with a Lipschitz-continuous boundary \(\partial\kappa\), unit exterior normal \(\mathfrak{n}=(n_{1},n_{2})\) and unit tangent vector \(\mathfrak{t}=(-n_{2},n_{1})\). For a vector \(\mathbf{v}\) in \(H^{1}(\kappa)^{2}\) and a tensor \(\tau=(\tau_{ij})\) in \(H^{1}(\kappa)^{4}\) Green's formula gives:

(4.3) \[\int_{\kappa}(\partial v_{i}/\partial x_{j})\tau_{ij}\,dx=-\int_{\kappa}v_{i} \partial\tau_{ij}/\partial x_{j}\,dx+\int_{\partial\kappa}v_{i}n_{j}\tau_{ij} \,ds,\ \ \ \ \ 1\leq i,j\leq 2.\]

Using the fact that \(v_{i}=(\mathbf{v}\cdot\mathbf{n})n_{i}+(\mathbf{v}\cdot\mathbf{t})t_{i}\), \(i=1,\,2\), the boundary integral in (4.3) can also be written as:

\[\int_{\partial\kappa}v_{i}n_{j}\tau_{ij}\,ds=\int_{\partial\kappa}(\mathbf{v} \cdot\mathbf{n})\tau_{ij}n_{j}n_{i}\,ds+\int_{\partial\kappa}(\mathbf{v} \cdot\mathbf{t})\tau_{ij}n_{j}t_{i}\,ds.\]

Thus summing over all \(i\) and \(j\) and defining the quantities:

(4.4) \[\begin{cases}M_{n}(\tau)=\sum\limits_{i,j=1}^{2}\tau_{ij}n_{j}n_{i},\\ M_{n}(\tau)=\sum\limits_{i,j=1}^{2}\tau_{ij}n_{j}t_{i},\end{cases}\]

the identity (4.3) becomes:

\[\int_{\kappa}\sum\limits_{i,j=1}^{2}(\partial v_{i}/\partial x_{j })\tau_{ij}\,dx =-\int_{\kappa}\sum\limits_{i,j=1}^{2}v_{i}(\partial\tau_{ij}/ \partial x_{j})\,dx\] \[\quad+\int_{\partial\kappa}\mathbf{v}\cdot\mathbf{n}M_{n}(\tau) \,ds+\int_{\partial\kappa}\mathbf{v}\cdot\mathbf{t}M_{n}(\tau)\,ds.\]

Or, with the well-known summation convention that a repeated index corresponds to a sum, we have the more compact expression:

(4.5) \[\int_{\kappa}(\partial v_{i}/\partial x_{j})\tau_{ij}\,dx =-\int_{\kappa}v_{i}(\partial\tau_{ij}/\partial x_{j})\,dx+\int_{ \partial\kappa}\mathbf{v}\cdot\mathbf{n}M_{n}(\tau)\,ds\] \[\quad+\int_{\partial\kappa}\mathbf{v}\cdot\mathbf{t}M_{n}(\tau) \,ds,\ \ \ \ \forall\mathbf{v}\in H^{1}(\kappa)^{2},\ \ \ \ \ \forall\tau\in H^{1}(\kappa)^{4}.\]

Together with (4.2), this identity is the foundation of several schemes, including the Hellan-Herrmann-Johnson scheme.

Here again, there are several ways of formulating the present method; we propose a mesh-dependent formulation closely related to that of Section 2.3. So, we assume that \(\Omega\) is a bounded domain of \(\mathbb{R}^{2}\) with a polygonal boundary \(\Gamma\) and we introduce a triangulation \(\mathcal{T}_{h}\) of \(\Omega\) made of triangles and/or convex quadrilaterals with diameters bounded by \(h\).

Like in Section 2.3, assume that the velocity \(\mathbf{u}\) and right-hand side \(\mathbf{f}\) satisfy: \(\mathbf{u}\in H^{2}(\Omega)^{2}\), \(\mathbf{f}\in L^{2}(\Omega)^{2}\). Let us examine the equations (4.2) in the light of (4.1) and (4.5). Observe that if the tensor \(\tau\) belongs globally to \(H^{1}(\Omega)^{4}\) and if the vector field \(\mathbf{v}\) belongs to
