As mentioned above, Theorems 1.12 and 2.2 imply the uniform inf-sup condition (1.12):

**Lemma 2.6**.: _Let \(\mathscr{T}_{h}\) be a regular triangulation of \(\bar{\Omega}\) and let the spaces \(X_{h}\) and \(M_{h}\) be defined by (2.17) (2.18). Then there exists a constant \(\beta^{*}>0\) independent of \(h\) such that:_

\[\sup_{\mathbf{v}_{h}\in X_{h}}\left\{\!\!\left(\left.\int_{\Omega}q_{h}\, \mathrm{div}\,\mathbf{v}_{h}\,dx\right)\!\!\right/\!\left|\mathbf{v}_{h}\right| _{1,\Omega}\right\}\geq\beta^{*}\left\|q_{h}\right\|_{0,\Omega}\ \ \ \ \ \forall q_{h}\in M_{h}.\]

Again, Hypothesis H2 follows immediately from Lemma A.5 for the \(L^{2}\)-projection \(\rho_{h}\) onto \(Q_{h}\):

(2.27) \[\left\|q-\rho_{h}q\right\|_{0,\Omega}\leq Ch^{1}|q|_{1,\Omega}\ \ \ \ \ \forall q\in H^{l}(\Omega).\]

Thus Theorems 1.8 and 1.9 imply the convergence and error estimates for the higher-order schemes.

**Theorem 2.3**.: _Assume that \(\Omega\) is a bounded, plane polygon. Let the solution \((\mathbf{u},p)\) of the Stokes problem satisfy:_

\[\mathbf{u}\in[H^{k+1}(\Omega)\cap H^{1}_{0}(\Omega)]^{2},\ \ \ \ \ p\in H^{k}(\Omega)\cap L^{2}_{0}(\Omega)\]

_for some integer \(k\) with \(1\leq k\leq l\) where the integer \(l\geq 2\); and let the spaces \(X_{h}\) and \(M_{h}\) be defined respectively by (2.17) and (2.18). If \(\mathscr{T}_{h}\) is a regular family of triangulations of \(\bar{\Omega}\) then the solution \((\mathbf{u}_{h},p_{h})\) of (1.39) satisfies:_

(2.28) \[\left|\mathbf{u}-\mathbf{u}_{h}\right|_{1,\Omega}+\left\|p-p_{h}\right\|_{0, \Omega}\leq C_{1}h^{k}(\left|\mathbf{u}\right|_{k+1,\Omega}+\left|p\right|_{k ,\Omega}).\]

_If in addition \(\Omega\) is convex, we have the \(L^{2}\)-estimate:_

(2.29) \[\left\|\mathbf{u}-\mathbf{u}_{h}\right\|_{0,\Omega}\leq C_{2}h^{k+1}(\left| \mathbf{u}\right|_{k+1,\Omega}+\left|p\right|_{k,\Omega}).\]

_Remark 2.6_.: Of course, according to (1.45) the hypotheses of Theorem 2.1 on \(\Omega\) and \(\mathscr{T}_{h}\) guarantee the convergence of \(\mathbf{u}_{h}\) and \(p_{h}\) without regularity assumption on the exact solution \(\mathbf{u}\) and \(p\).

### The Three-Dimensional Case: First and Higher-Order Schemes

In this section we assume that \(\Omega\) is a _bounded polyhedron_ of \(\mathbb{R}^{3}\) and \(\mathscr{T}_{h}\) is a triangulation of \(\bar{\Omega}\) that consists of tetrahedra \(\kappa\) with diameters bounded by \(h\). If \(\kappa\) is a tetrahedron with vertices \(a_{1}\), \(a_{2}\), \(a_{3}\), \(a_{4}\) like in Figure 9 we denote by \(F_{i}\) the face opposite \(a_{i}\), \(\mathbf{n}_{i}\) its outward unit normal and \(e_{ij}\) the edge \([a_{i},a_{j}]\).



We shall develop the first and second-order schemes separately, since they are particular cases. The _first-order scheme_ is a very straightforward extension of the two-dimensional scheme discussed in Section 2.1 and we shall skim through it rapidly. Let \(\kappa\) be an arbitrary tetrahedron; what we want is a velocity vector \(\mathbf{w}\), with affine tangential components on the faces of \(\kappa\), that is compatible
