The expression in brackets can be rearranged as follows:

\[\{a_{2}^{u_{n}}(u_{h}-u_{h}^{*};u_{h},\mathbf{w}_{h})-a_{2}^{u_{0}}(u _{h}-u_{h}^{*};u_{h},\mathbf{w}_{h})\}+\{a_{2}^{u_{h}^{*}}(u_{h}^{*};u_{h}-u_{h}^ {*},\mathbf{w}_{h})\] \[\quad-a_{2}^{u_{0}^{0}}(u_{h}^{*};u_{h}-u_{h}^{*},\mathbf{w}_{h}) \}+\{a_{2}^{u_{h}}(u_{h}^{*};u_{h},\mathbf{w}_{h})-a_{2}^{u_{h}^{*}}(u_{h}^{*};u _{h},\mathbf{w}_{h})\}.\]

Then using repeatedly Lemma 5.3 this expression can be bounded by:

\[C_{1}h^{1/2}\{|u_{h}|\,|\psi_{h}-\psi_{h}^{*}|_{1,\,4,\,\mathcal{ O}}+|\psi_{h}^{*}-\psi_{h}^{0}|_{1,\,4,\,\mathcal{O}}|u_{h}-u_{h}^{*}|\}\,|w_{h}|\] \[\quad\leqslant C_{2}h^{1/2}|u_{h}-u_{h}^{*}|\,\{|u_{h}-u_{h}^{0}| +|u_{h}^{*}-u_{h}^{0}|+|u_{h}^{0}|\}\,|w_{h}|\quad\quad\forall w_{h}\!\in V_{h}.\]

Hence Lemma 5.2 gives the bound

\[\|\,G_{h}(u_{h})-G_{h}(u_{h}^{*})-FG_{h}(u_{h}^{0})\cdot(u_{h}-u_{h }^{*})\|_{h}\] \[\quad\leqslant C_{3}|u_{h}-u_{h}^{*}|\,\{|u_{h}-u_{h}^{0}|+|u_{h} ^{*}-u_{h}^{0}|+h^{1/2}|u_{h}^{0}|\}.\]

This implies (3.64) with the function

\[L_{h}(\mu;v)=C_{4}(\mu+h^{1/2}v).\]

Clearly \(L_{h}\) is continuous, monotonically increasing with respect to each variable and

\[\lim_{h\to 0}L_{h}(0;v)=\lim_{h\to 0}(h^{1/2}v)=0\quad\quad\forall v\!\in \!\mathbb{R}_{+}.\]

Since all the assumptions of Theorem 3.8 are satisfied, we can apply its conclusion to the upwind scheme (5.18), thus deriving the existence, uniqueness and convergence of its branch of solutions. Furthermore, by comparing the two error estimates (3.67) and (3.41) and taking into account (5.42) we readily deduce that the error of the upwind scheme is bounded exactly like the error of the centered scheme. In other words, in this case _the upwinding does not alter the scheme's order_. These results are summed up in the following theorem.

**Theorem 5.1**.: _Let \(\Omega\) be a bounded, convex polygon and \(\mathcal{T}_{h}\) a uniformly regular family of triangulations of \(\Omega\). For \(\mathbf{f}\!\in\!L^{t}(\Omega)^{2},\,t\!\in\![r,2)\) let_

\[\{(\dot{\lambda},(\mathbf{curl}\,\psi(\dot{\lambda}),\omega(\dot{\lambda}))); \,\dot{\lambda}=1/v\!\in\!\Lambda\}\]

_be a branch of nonsingular solutions of the Navier-Stokes Problem (5.7). Then for \(h\leqslant h_{0}\) small enough there exists a unique branch_

\[\{(\dot{\lambda},(\mathbf{curl}\,\psi_{h}(\dot{\lambda}),\omega_{h}(\dot{ \lambda})));\,\dot{\lambda}=1/v\!\in\!\Lambda\}\]

_of \(\mathcal{C}^{0}\)-solutions of the upwind scheme (5.18) satisfying the error estimate_:

(5.43) \[\begin{split}\sup_{\dot{\lambda}\,\in\,\Lambda}\{|\psi_{h}(\dot{ \lambda})-\psi(\dot{\lambda})|_{1,\,s,\,\mathcal{O}}+\|\,\omega_{h}(\dot{ \lambda})-\omega(\dot{\lambda})\|_{0,\,\mathcal{O}}\}\leqslant C_{1}h^{\alpha}, \\ \alpha=\begin{cases}1/\gamma&\text{if }l=1,\\ 2/\gamma&\text{if }l\geqslant 2,\end{cases}\quad\quad 1/t\,+\,1/\gamma=1, \end{split}\]

_with a constant \(C\) independent of \(h\) or \(\dot{\lambda}\)._
