Now, let us show that there exists a constant \(C>0\) independent of \(h\), such that

(4.35) \[\|\pi_{h}\tau\|_{0,\Omega}\leqslant C\,\|\,\tau\|_{0,\,h}\quad\quad\forall\tau \in\mathcal{Z},\]

where, for the sake of simplicity, the norms of tensors and scalars are denoted alike. For each \(\kappa\) of \(\mathcal{T}_{h}\), (4.30) and (4.25a) imply:

\[\|\pi_{\kappa}\tau\|_{0,\Omega}^{2}\leqslant|\det(B_{\kappa})|\,\|B_{\kappa}\| ^{4}\,\|\,\pi_{\kappa}\hat{\tau}\|_{0,\,\hat{\kappa}}^{2}.\]

But it follows easily from (4.29) that

\[\|\pi_{\kappa}\hat{\tau}\|_{0,\,\kappa}^{2}\leqslant C_{1}(\|\,\hat{\tau}\|_{ 0,\,\hat{\kappa}}^{2}+\|\,M_{\hat{\mu}}(\hat{\tau})\|_{0,\,\hat{\infty}}^{2}),\]

where the constant \(C_{1}\) is independent of \(h\). Next, (4.26) implies:

\[\|M_{\hat{\mu}}(\hat{\tau})\|_{0,\,\hat{\kappa}^{\prime}}^{2}\leqslant(C_{2}/ \rho_{\kappa})\,\|\,B_{\kappa}^{-1}\|^{4}\|\,M_{\mathfrak{n}}(\tau)\|_{0,\, \kappa}^{2},\quad\quad\text{\rm{vsides $\kappa^{\prime}$ of $\kappa$.}}\]

Likewise, we derive from (4.25b) that

\[\|\,\hat{\tau}\|_{0,\,\hat{\kappa}}^{2}\leqslant|\det(B_{\kappa})|^{-1}\,\|B_ {\kappa}^{-1}\,\|^{4}\|\,\tau\|_{0,\,\kappa}^{2}.\]

Collecting these four inequalities and applying (A.2) and (A.4) we obtain:

\[\|\pi_{\kappa}\tau\|_{0,\,\kappa}^{2}\leqslant C_{3}\sigma_{\kappa}^{4}(\| \,\tau\|_{0,\,\kappa}^{2}+\sigma_{\kappa}h_{\kappa}\|M_{\mathfrak{n}}(\tau)\| _{0,\,\hat{\infty}}^{2}).\]

Since \(\mathcal{T}_{h}\) is regular, this proves (4.35) and in turn (4.32).

Finally, let us establish (4.33). Like above, we have

\[\|\,\pi_{\kappa}\tau-\tau\|_{0,\,\kappa}^{2}\leqslant|\det(B_{\kappa})|\,\|B _{\kappa}\|^{4}\,\|\pi_{\hat{\kappa}}\hat{\tau}-\hat{\tau}\|_{0,\,\hat{\kappa }}^{2}.\]

As the mapping \(\pi_{\kappa}\) leaves invariant the symmetric tensors with coefficients in \(P_{t-1}\), (A.12) gives:

\[\|\pi_{\hat{\kappa}}\hat{\tau}-\hat{\tau}\|_{0,\,\hat{\kappa}}\leqslant C_{4} |\,\hat{\tau}|_{k,\,\hat{\kappa}}\quad\quad 1\leqslant k\leqslant l.\]

According to (4.25b), we have:

\[|\,\hat{\tau}|_{k,\,\hat{\kappa}}\leqslant\|B_{\kappa}^{-1}\,\|^{2}|\,\tau \circ F_{\kappa}|_{k,\,\hat{\kappa}};\]

and in view of (A.7) this becomes

(4.36) \[|\,\hat{\tau}|_{k,\,\hat{\kappa}}\leqslant C_{5}\,\|B_{\kappa}\|^{k}\,\|B_{ \kappa}^{-1}\,\|^{2}|\det(B_{\kappa})|^{-1/2}|\tau|_{k,\,\kappa}.\]

Since \(\mathcal{T}_{h}\) is regular, the above inequalities yield:

\[\|\,\pi_{h}\tau-\tau\|_{0,\,\Omega}\leqslant C_{6}h^{k}|\tau|_{k,\,\Omega}.\]

Similarly, it stems from (4.26) that:

\[\|\,M_{\mathfrak{n}}(\pi_{\kappa}\tau-\tau)\|_{0,\,\kappa^{\prime}}^{2} \leqslant C_{7}h_{\kappa}\|\,B_{\kappa}\|^{4}\,\|M_{\mathfrak{n}}(\pi_{\kappa }\hat{\tau}-\hat{\tau})\|_{0,\,\hat{\kappa}^{\prime}}^{2},\]

and the trace Theorem I.1.5 implies:

\[\|M_{\mathfrak{n}}(\pi_{\hat{\kappa}}\hat{\tau}-\hat{\tau})\|_{0,\,\hat{\kappa }^{\prime}}^{2}\leqslant C_{8}\,\|\,\pi_{\hat{\kappa}}\hat{\tau}-\hat{\tau}\|_ {1,\,\hat{\kappa}}^{2}\leqslant C_{9}|\hat{\tau}|_{k,\,\hat{\kappa}}^{2}.\]

Therefore, owing to (4.36) and the regularity of \(\mathcal{T}_{h}\), we get:

\[\|M_{\mathfrak{n}}(\pi_{\kappa}\tau-\tau)\|_{0,\,\kappa^{\prime}}^{2} \leqslant C_{1\,0}h^{2k-1}|\tau|_{k,\,\kappa}^{2},\]

thus establishing (4.33).
