\[\vec{X}=\{v=(\mbox{\bf curl}\,\phi,\theta);\,\phi\!\in\!\mathcal{P}_{s},\,\theta\! \in\!L^{2}(\Omega)\},\quad\ \ \vec{M}=W^{1,\tau}(\Omega),\]

equipped with the norms:

\[\|(\mbox{\bf curl}\,\phi,\theta)\|_{\vec{X}}=|\phi|_{1,\,s,\Omega}+\,\|\,\theta \|_{0,\,\Omega},\quad\ \ \|\,\mu\,\|_{\vec{M}}=\|\,\mu\|_{1,\,\tau,\Omega}.\]

The bilinear forms are:

\[\tilde{a}(u,v)=v(\omega,\theta)\quad\ \ \forall u=(\mbox{\bf curl }\,\psi,\omega),\quad\ v=(\mbox{\bf curl}\,\phi,\theta)\!\in\!\vec{X},\] \[\tilde{b}(v,\mu)=(\mbox{\bf curl}\,\phi,\mbox{\bf curl}\,\mu)-( \theta,\mu)\quad\ \ \forall v=(\mbox{\bf curl}\,\phi,\theta)\!\in\!\vec{X},\quad\ \ \forall\mu\!\in\!\vec{M}\]

and the corresponding space \(\vec{V}\) is:

\[\vec{V}=\{v\!\in\!\vec{X};\,\tilde{b}(v,\mu)=0\quad\ \forall\mu\!\in\!\vec{M}\}.\]

In view of the approximation, we introduce three finite-dimensional spaces:

\[\mathcal{P}_{h}\subset\mathcal{P}_{s},\quad\ \ \mathcal{O}_{h}\subset L^{2}( \Omega),\quad\ M_{h}\subset W^{1,\tau}(\Omega)\] (2.23)

and we discretize (2.19) by the following _Problem_ (Q\({}_{h}\)):

\[\mbox{\it Find }(\psi_{h},\omega_{h})\!\in\!\mathcal{P}_{h}\times\,\mathcal{O }_{h}\mbox{\it and }\dot{\lambda}_{h}\!\in\!M_{h}\mbox{\it such that }\] (2.24) \[\left\{\begin{aligned} v(\omega_{h},\theta_{h})& -(\dot{\lambda}_{h},\theta_{h})+(\mbox{\bf curl}\,\phi_{h},\mbox{\bf curl }\,\dot{\lambda}_{h})=(\mbox{\bf f},\mbox{\bf curl}\,\phi_{h})\quad\ \ \forall(\phi_{h},\theta_{h})\!\in\!\mathcal{P}_{h}\times\, \mathcal{O}_{h},\\ &(\mbox{\bf curl}\,\psi_{h},\mbox{\bf curl}\,\mu_{h})=(o_{h}, \mu_{h})\quad\ \ \forall\mu_{h}\!\in\!M_{h}.\end{aligned}\right.\]

Here, the spaces \(X_{h}\) and \(V_{h}\) are:

\[X_{h}=\{v_{h}=(\mbox{\bf curl}\,\phi_{h},\theta_{h});\,\phi_{h}\!\in\! \mathcal{P}_{h},\,\theta_{h}\!\in\!\Theta_{h}\},\] \[V_{h}=\{v_{h}=(\mbox{\bf curl}\,\phi_{h},\theta_{h})\!\in\!X_{h}; (\mbox{\bf curl}\,\phi_{h},\mbox{\bf curl}\,\mu_{h})=(\theta_{h},\mu_{h}) \quad\ \ \forall\mu_{h}\!\in\!M_{h}\}.\]

The next lemma checks the inf-sup condition (1.21).

**Lemma 2.2**.: _If \(M_{h}\subset\mathcal{O}_{h}\) then_

\[\sup_{v_{h}\!\in\!X_{h}}\frac{\tilde{b}(v_{h},\mu_{h})}{\|v_{h}\|_{\vec{X}}} \geqslant\|\,\mu_{h}\|_{0,\,\Omega}\quad\ \ \forall\mu_{h}\!\in\!M_{h}.\] (2.25)

Indeed, (2.25) stems from the choice \(v_{h}=(\mathbf{0},\,-\mu_{h})\).

When \(s=2\), the uniform ellipticity of \(\tilde{a}(.\,,.)\) follows from the next lemma, but when \(s>2\) there seems to be no obvious way of establishing this property and it has to be introduced by means of a hypothesis.

**Lemma 2.3**.: _If \(\mathcal{P}_{h}\subset M_{h}\) there exists a constant \(C>0\) such that_:__

\[|\phi_{h}|_{1,\,\Omega}\leqslant C\,\|\,\theta_{h}\|_{0,\,\Omega}\quad\ \ \forall(\mbox{\bf curl}\,\phi_{h},\theta_{h})\!\in\!V_{h}.\] (2.26)

Proof.: By definition a function \((\mbox{\bf curl}\,\phi_{h},\theta_{h})\) in \(V_{h}\) verifies:

\[(\mbox{\bf curl}\,\phi_{h},\mbox{\bf curl}\,\mu_{h})=(\theta_{h},\mu_{h}) \quad\ \ \forall\mu_{h}\!\in\!M_{h}.\]

As \(\mathcal{P}_{h}\subset M_{h}\) we can take \(\mu_{h}=\phi_{h}\); with Lemma I.3.1 this implies:
