The approximation properties of \(X_{h}\) and \(Q_{h}\) are well known. For instance, if the triangulation \(\mathcal{T}_{h}\) is regular, the interpolation operator \(r_{h}\) defined by:

\[\begin{cases}r_{h}\mathbf{v}(a)=\mathbf{v}(a)\quad\text{on all nodes $a$ of $\mathcal{T}_{h}$,}\\ r_{h}\mathbf{v}(a_{\kappa})=\mathbf{v}(a_{\kappa})\quad\text{on the center $a_{\kappa}$ of $\kappa$,} \quad\forall\kappa\in\mathcal{T}_{h},\\ r_{h}\mathbf{v}\in\mathcal{P}_{1}(\kappa)\quad\text{on each $\kappa$,}\end{cases}\] (4.6)

satisfies

\[r_{h}\in\mathcal{L}([H^{2}(\Omega)\cap H^{1}_{0}(\Omega)]^{2};\,X_{h})\]

and

\[\|\mathbf{v}-r_{h}\mathbf{v}\|_{m,\Omega}\leq Ch^{2-m}|\mathbf{v}|_{2,\Omega} \quad\quad\forall\mathbf{v}\in H^{2}(\Omega)^{2},\quad\quad m=0\text{ or }1.\] (4.7)

Indeed, \(r_{h}\) is preserved by affine transformations on each \(\kappa\) and leaves invariant the polynomials of \(P^{2}_{1}\).

Likewise, the local regularization operator \(R_{h}\) on \(P_{1}\) defined by (A.53), (A.54) satisfies \(R_{h}\in\mathcal{L}(L^{2}(\Omega);Q_{h})\) and

\[\|q-R_{h}q\|_{m,\Omega}\leq Ch^{1-m}|q|_{1,\Omega}\quad\quad\forall q\in H^{1 }(\Omega),\quad\quad m=0\text{ or }1,\] (4.8)

provided of course that \(\mathcal{T}_{h}\) is regular.

Therefore the Hypotheses H1 and H2 are fulfilled and it remains to verify H3, namely the inf-sup condition:

\[\sup_{\mathbf{v}_{h}\in X_{h}}\frac{(q_{h},\operatorname{div}\mathbf{v}_{h})}{ |\mathbf{v}_{h}|_{1,\Omega}}\geqslant\beta^{*}\|q_{h}\|_{0,\Omega}\quad\quad \forall q_{h}\in M_{h}.\] (4.9)

This is achieved by the next lemma.

**Lemma 4.1**.: _If the triangulation \(\mathcal{T}_{h}\) is regular_, _the pair of spaces \((X_{h},M_{h})\) defined by (4.3) (4.4) satisfies (4.9) with a constant \(\beta^{*}>0\) independent of \(h\)._

_Proof_. Let us exhibit the operator \(\pi_{h}\) of Lemma 1.1. Take an arbitrary \(q_{h}\) in \(M_{h}\). Since \(q_{h}\in L^{2}_{0}(\Omega)\) there exists \(\mathbf{v}\) in \(H^{1}_{0}(\Omega)^{2}\) such that

\[\operatorname{div}\mathbf{v}=q_{h},\quad|\mathbf{v}|_{1,\Omega}\leq C_{1}\|q _{h}\|_{0,\Omega}.\] (4.10)

Therefore, since \(M_{h}\subset H^{1}(\Omega)\) we want to construct a function \(\pi_{h}\mathbf{v}\) in \(X_{h}\) that satisfies

\[\sum_{\kappa\in\mathcal{T}_{h}}\int_{\kappa}\pi_{h}\mathbf{v}\cdot\mathbf{grad }\,\mu_{h}\,dx=\sum_{\kappa\in\mathcal{T}_{h}}\int_{\kappa}\mathbf{v}\cdot \mathbf{grad}\,\mu_{h}\,dx\quad\quad\forall\mu_{h}\in M_{h}.\]

As \(\mathbf{grad}\,\mu_{h}\in P^{2}_{0}\) on each \(\kappa\), this equality induces us to define \(\pi_{h}\mathbf{v}\) in \(X_{h}\) such that:

\[\pi_{h}\mathbf{v}(a)=(R_{h}\mathbf{v})(a)\quad\quad\forall\text{node $a$ of $\mathcal{T}_{h}$,}\] (4.11)

and
