## SS2. Theory of the Steady-State Navier-Stokes Equations

As we have seen in Paragraph I.5, the stationary Navier-Stokes equations may be written in the form

(2.1) \[\left\{\begin{aligned} -\nu\mathcal{J}\mathbf{u}&+\sum \limits_{j=1}^{N}u_{j}\partial\mathbf{u}/\partial x_{j}+\mathbf{grad}\,p= \mathbf{f},\\ \operatorname{div}\mathbf{u}&=0,\end{aligned}\right\} \quad\text{in }\Omega\] \[\mathbf{f}\text{ given in }H^{-1}(\Omega)^{N},\]

where again \(\Omega\) is a bounded domain of \(\mathbb{R}^{N}\left(N=2,3\right)\) with a Lipschitz-continuous boundary \(\Gamma\). In this paragraph, we want to derive from the abstract material of SS1 existence and uniqueness results for various formulations of the Navier-Stokes equations.

### The Dirichlet Problem in the Velocity-Pressure Formulation

We first consider the case of the _homogeneous Dirichlet boundary condition_

(2.2) \[\mathbf{u}=\mathbf{0}\quad\text{on }\Gamma.\]

In order to write Problem (2.1), (2.2) in a variational form, we introduce the trilinear form

(2.3) \[a_{1}(\mathbf{w};\mathbf{u},\mathbf{v})=\sum\limits_{i,j=1}^{N}\int_{\Omega}w _{j}(\partial u_{i}/\partial x_{j})v_{i}\,dx.\]

The next two lemmas state useful properties of the trilinear form \(a_{1}(.;.,.)\).

**Lemma 2.1**.: _For \(N\leq 4\), the trilinear form \(a_{1}(.;.,.)\) is continuous on \((H^{1}(\Omega)^{N})^{3}\)._

Proof.: According to the Sobolev Imbedding Theorem I.1.3, the space \(H^{1}(\Omega)\) is continuously imbedded in \(L^{4}(\Omega)\) for \(N\leq 4\). Then by Holder's inequality, we have if \(\mathbf{u}\), \(\mathbf{v}\), \(\mathbf{w}\!\in\!H^{1}(\Omega)^{N}\):

\[w_{j}(\partial u_{i}/\partial x_{j})v_{i}\!\in\!L^{1}(\Omega),\quad\ 1\leq i,j \leq N,\]

with

\[\left|\int_{\Omega}w_{j}(\partial u_{i}/\partial x_{j})v_{i}\,dx\right| \leq\|w_{j}\|_{0,4,\Omega}\|\partial u_{i}/\partial x_{j}\|_{0, \Omega}\|v_{i}\|_{0,4,\Omega}\] \[\leq C_{1}\,\|w_{j}\|_{1,\Omega}|u_{i}|_{1,\Omega}\|v_{i}\|_{1, \Omega}.\]

Thus, the form \(a_{1}(.;.,.)\) is well defined and continuous on \((H^{1}(\Omega)^{N})^{3}\) and

\[|a_{1}(\mathbf{w};\mathbf{u},\mathbf{v})| \leq C_{2}|\mathbf{u}|_{1,\Omega}\|\mathbf{v}\|_{1,\Omega}\| \mathbf{w}\|_{1,\Omega}.\qed\]
