It remains to fulfill the conditions on the function \(L_{h}\) defined by (3.54). In view of (3.59) and (3.64), we have the upper bound:

\[\|\,F_{u}F_{h}(\lambda,\tilde{u}_{h}(\lambda))\cdot(v_{h}-w_{h})-F_ {h}(\lambda,v_{h})+F_{h}(\lambda,w_{h})\|_{X}\] \[\quad\leqslant C|\lambda|L_{h}(\alpha;\|\,\tilde{u}_{h}(\lambda) \|_{X})\,\|\,v_{h}-w_{h}\|_{X}\] \[\forall\lambda\in\Lambda,\quad\forall v_{h},\,w_{h}\in S(\tilde{ u}_{h}(\lambda);\alpha)\cap V_{h}.\]

Let

\[K=\sup_{h\leqslant h_{1}}\sup_{\lambda\in\Lambda}\|\,\tilde{u}_{h}(\lambda) \|_{X}.\]

The monotonicity of \(L_{h}\) implies that

\[L_{h}(\alpha;\|\,\tilde{u}_{h}(\lambda)\|_{X})\leqslant L_{h}(\alpha;K).\]

By assumption, the mapping \(\mu\to L_{h}(\mu;K)\) is monotonically increasing with respect to \(h\) and \(\mu\) and continuous at \(\mu=0\). In addition, by virtue of (3.65), it satisfies the condition (3.57).

As a consequence, we can apply the conclusion of Theorem 3.7. It yields (3.66); then (3.67) stems from (3.30') with \(v_{h}=\tilde{u}_{h}(\lambda)\), (3.68) and (3.59). 

_Remark 3.9_.: The space \(V\), which enters only in the assumption (3.61), plays a minor part in this proof. It is useful when the restriction operator \(\pi_{h}\) requires more regularity than the space \(X\) can provide.

## 4 Numerical Analysis of Centered Finite Element Schemes

In this paragraph, we propose to apply to the homogeneous Navier-Stokes equations most of the finite element methods developed in Chapters II and III to solve the Stokes problem. The reader will find that in nearly every case, the error analysis carries over successfully to Navier-Stokes equations. One of the few exceptions is the three-dimensional mixed method elaborated in Paragraph III.5. This method can be tried to solve the Navier-Stokes system but at the present stage, its numerical analysis is still an open problem.

### Formulation in Primitive Variables: Methods Using Discontinuous Pressures

The situation is that of Section II.1.3. For each value of the parameter \(h>0\), we are given two finite-dimensional spaces:

\[W_{h}\subset H^{1}(\Omega)^{N},\quad\ Q_{h}\subset L^{2}(\Omega)\]

and we assume that \(Q_{h}\) contains the constant functions. Then we define:
