**Theorem 2.7**.: _If \(\Omega\) is connected, we have:_

\[H^{\perp}=\{\mathbf{grad}\,q;\,q\in H^{1}(\Omega)\}.\]

Proof.: For the sake of brevity, we denote the space \(\{\mathbf{grad}\,q;q\in H^{1}(\Omega)\}\) by \(X\). First, observe that in view of Theorem 1.9, \(X\) is a closed subspace of \(L^{2}(\Omega)^{N}\). Hence, if we prove that \(X^{\perp}=H\) this will imply:

\[H^{\perp}=(X^{\perp})^{\perp}=\bar{X}=X,\]

which is the required result.

First, let \(\mathbf{u}\in H\). Formula (2.17) and Theorem 2.6 yield

\[(\mathbf{u},\mathbf{grad}\,q)=0\ \ \ \ \ \forall q\in H^{1}(\Omega).\]

Therefore \(H\subset X^{\perp}\).

Conversely, let \(\mathbf{u}\in L^{2}(\Omega)^{N}\) with

\[(\mathbf{u},\mathbf{grad}\,q)=0\ \ \ \ \ \forall q\in H^{1}(\Omega).\]

By choosing \(q\) in \(\mathcal{D}(\Omega)\), this implies that \(\operatorname{div}\mathbf{u}=0\). Hence \(\mathbf{u}\in H(\operatorname{div};\Omega)\).Therefore we can apply formula (2.17) which gives \(\mathbf{u}\cdot\mathbf{n}=0\). In view of Theorem 2.6, this means that \(\mathbf{u}\in H\). Therefore \(X^{\perp}\subset H\). 

**Theorem 2.8**.: _The space \(\mathcal{V}\) is dense in \(H\)._

Proof.: This is another application of property (2.14). Let \(l\in H^{\prime}\) and let \(\mathbf{l}\in H\) be associated with \(l\) by

\[\langle l,\mathbf{u}\rangle=(\mathbf{l},\mathbf{u})\ \ \ \ \ \forall\mathbf{u}\in H.\]

Then, if \(l\) vanishes on \(\mathcal{V}\), the function \(\mathbf{l}\) satisfies the hypotheses of Theorem 2.3. Hence

\[\mathbf{l}=\mathbf{grad}\,p\]

for some \(p\in L^{2}(\Omega)\). As \(\mathbf{l}\in L^{2}(\Omega)^{N}\), this implies that \(p\in H^{1}(\Omega)\). Thus formula (2.17) yields:

\[\langle l,\mathbf{u}\rangle=-(p,\operatorname{div}\mathbf{u})+\langle \mathbf{u}\cdot\mathbf{n},p\rangle_{\Gamma}=0\ \ \ \ \ \ \forall\mathbf{u}\in H.\qed\]

### Some Properties of Spaces Related to the curl Operator

Unless otherwise specified, we assume in this section that the dimension \(N\) is two or three and that \(\Omega\) is a _bounded_ region of \(\mathbb{R}^{N}\) with a _Lipschitz-continuous_ boundary \(\Gamma\). When \(N=2\), we define the curl operator for distributions \(\phi\) of \(\mathcal{D}^{\prime}(\Omega)\) and \(\mathbf{v}\) of \(\mathcal{D}^{\prime}(\Omega)^{2}\) by
