**Lemma 3.4**.: _Here we assume only that \(\Omega\) is bounded, Lipschitz-continuous, simply-connected and \(\Gamma\) has just one component \((p=0)\). Then the mapping \(\phi\rightarrow\operatorname{\mathbf{curl}}\phi\) is an isomorphism from \(W_{0}\) onto \(H\) and there exist two positive constants \(C_{1}\) and \(C_{2}\) such that:_

(3.35) \[\left\|\phi\right\|_{0,\Omega}\leqslant C_{1}\left\| \operatorname{\mathbf{curl}}\phi\right\|_{0,\Omega}\ \ \ \ \ \forall\phi\in W_{0},\] (3.36) \[\left\|\phi\right\|_{0,\Omega}\leqslant C_{2}\{\left\| \operatorname{\mathbf{curl}}\phi\right\|_{0,\Omega}+\left\|\operatorname{div} \phi\right\|_{0,\Omega}\}\ \ \ \ \ \forall\phi\in W.\]

Proof.: Since \(\Omega\) is simply-connected and \(p=0\), Theorem 3.6 claims that each function \(\mathbf{u}\) in \(H\) has exactly one vector potential \(\phi\) in \(W_{0}\):

\[\mathbf{u}=\operatorname{\mathbf{curl}}\phi.\]

Therefore, the mapping \(\operatorname{\mathbf{curl}}\) is one-to-one, linear and continuous from \(W_{0}\) onto \(H\). As \(W_{0}\) and \(H\) are Banach spaces, it follows that it is an isomorphism. Furthermore, the mapping \(\phi\rightarrow\left\|\mathbf{u}\right\|_{H(\operatorname{div},\Omega)}= \left\|\operatorname{\mathbf{curl}}\phi\right\|_{0,\Omega}\) is a norm on \(W_{0}\) equivalent to the norm of \(W\). This establishes (3.35).

Now, (3.36) is an easy consequence of (3.35) and the decomposition of Lemma 3.3: \(\phi\) in \(W\) can be written as

\[\phi=\psi+\operatorname{\mathbf{grad}}q,\]

where \(\psi\in W_{0}\) and, by virtue of Poincare's Theorem 1.1,

\[\left|q\right|_{1,\Omega}\leqslant C\left\|\operatorname{div}\phi \right\|_{0,\Omega}.\]

Hence

\[\left\|\phi\right\|_{0,\Omega}\leqslant C_{1}\left\|\operatorname{\mathbf{ curl}}\psi\right\|_{0,\Omega}+C\left\|\operatorname{div}\phi\right\|_{0, \Omega},\]

and the result follows since \(\operatorname{\mathbf{curl}}\psi=\operatorname{\mathbf{curl}}\phi\). Note that, although we use here part of the proof of Lemma 3.3, we do not require its hypotheses on \(\Omega\) for we do not ask \(q\) to belong to \(H^{2}(\Omega)\). 

**Theorem 3.7**.: _The space \(W\) is continuously imbedded into \(H^{1}(\Omega)^{3}\)._

Proof.: \(1^{\circ}\)) Assume for the moment that \(\Omega\) is simply-connected and \(p=0\). According to Lemma 3.3, it is equivalent to examine \(W_{0}\). By virtue of Lemma 3.4, the mapping \(\operatorname{\mathbf{curl}}\) is an isomorphism from \(W_{0}\) onto \(H\). But, since the hypotheses of Theorem 3.6, \(3^{\circ}\)) are satisfied, \(\operatorname{\mathbf{curl}}\) is also an isomorphism from \(W_{0}\cap H^{1}(\Omega)^{3}\) onto \(H\). Hence, algebraically and topologically, we have

\[W_{0}=W_{0}\cap H^{1}(\Omega)^{3}\]

and therefore \(W_{0}\) is continuously imbedded into \(H^{1}(\Omega)^{3}\).

\(2^{\circ}\)) When \(\Omega\) is arbitrary, it is no longer convex and thus, by hypothesis, \(\Gamma\) must be \(\mathcal{C}^{1.1}\). Now, we can easily find a finite open covering \(\{\mathcal{O}_{i}\}_{1\leqslant i\leqslant l}\) of \(\Omega\) such that each \(\mathcal{O}_{i}\cap\Omega\) is simply-connected and has a connected boundary. Let \(\{\alpha_{i}\}\) be a partition of unity subordinate to \(\{\mathcal{O}_{i}\}\); then each \(\phi\) in \(W\) can be expressed as
