(3.12) \[\|v-P_{h}v\|_{0,\,\Omega}\leqslant Ch^{2/p}|\ln(h)|^{\beta}|v|_{1,\,q,\,\Omega} \quad\quad\forall v\in W^{1,\,q}(\Omega),\]

_where \(\beta=0\) if \(l\geqslant 2\) and \(\beta=1-2/p\) if \(l=1\)._

Proof.: Let \(R_{h}\in\mathcal{L}(H^{1}(\Omega);\Theta_{h})\) be the local regularization operator defined by (A.53) (A.54) and let us write:

\[\|v-P_{h}v\|_{0,\,\Omega}\leqslant\|v-R_{h}v\|_{0,\,\Omega}+\|R_{h}v-P_{h}v\|_ {0,\,\Omega}.\]

As \(R_{h}v-P_{h}v\in\Theta_{h}\), Lemma A.7 implies:

\[\|R_{h}v-P_{h}v\|_{0,\,\Omega}\leqslant Ch^{1-2/q}\|R_{h}v-P_{h}v\|_{0,\,q, \,\Omega}.\]

Hence

\[\|v-P_{h}v\|_{0,\,\Omega}\leqslant\|v-R_{h}v\|_{0,\,\Omega}+Ch^{1-2/q}(\|v-R_ {h}v\|_{0,\,q,\,\Omega}+\|v-P_{h}v\|_{0,\,q,\,\Omega}).\]

Thus (3.12) is a straightforward consequence of Theorem A.4, Jensen's inequality (A.34) and (A.26) with a logarithmic factor if \(q<2\). 

This lemma enables us to extend Theorem 3.1.

**Theorem 3.2**.: _Let \(\Omega\) and \(\mathcal{T}_{h}\) be like in Theorem 3.1 and assume that the stream function \(\psi\) belongs to \(W^{3,\,\mathfrak{s}}(\Omega)\) and the pressure \(p\) to \(W^{1,\,\mathfrak{s}}(\Omega)\) with \(\mathfrak{s}\in[r,2)\). Let \(\beta\) satisfy \(1/\mathfrak{s}+1/\beta=1\). We have the following estimates:_

(3.13) \[\|u-u_{h}\|_{\tilde{X}}\leqslant C_{1}\begin{cases}h^{2/\beta}|\psi|_{3,\, \mathfrak{s},\Omega}&\text{if }l\geqslant 2,\\ h^{1/\beta}\|\psi\|_{3,\,\mathfrak{s},\Omega}&\text{if }l=1,\end{cases}\]

(3.14) \[\|p-p_{h}\|_{0,\,\Omega}\leqslant C_{2}(\|\psi\|_{3,\,\mathfrak{s},\Omega}+| p|_{1,\,\mathfrak{s},\Omega})\begin{cases}h^{2/\beta}&\text{if }l\geqslant 2,\\ h^{1/\beta}&\text{if }l=1,\end{cases}\]

_with constants \(C_{1}\) and \(C_{2}\) independent of \(h,\psi\) and \(p\)._

Proof.: When \(l\geqslant 2\) we can apply the material of Section 2.3. Indeed, the arguments of Lemmas 2.10 and 2.11 can be readily extended to obtain:

\[\inf_{\theta_{h}\in\Theta_{h}}\|\omega-\theta_{h}\|_{0,\,h} \leqslant C_{1}h^{2/\beta}|\omega|_{1,\,\mathfrak{s},\Omega}\quad\text{for }l\geqslant 1,\] \[\inf_{\theta_{h}\in\Theta_{h}}\|\psi-\phi_{h}\|_{2,\,h} \leqslant C_{2}h^{2/\beta}|\psi|_{3,\,\mathfrak{s},\Omega}\quad\text{for }l\geqslant 2.\]

(Note that \(\psi\) belongs to \(H^{2}(\Omega)\) because \(W^{3,\,\mathfrak{s}}(\Omega)\subset H^{2}(\Omega)\)). When substituted into (2.66) these two bounds yield a somewhat sharper estimate than (3.13), namely:

(3.15) \[\|\omega-\omega_{h}\|_{0,\,h}+\|\psi-\psi_{h}\|_{2,\,h}\leqslant C_{3}h^{2/ \beta}|\psi|_{3,\,\mathfrak{s},\Omega}\quad\text{for }l\geqslant 2.\]

In turn, (2.38) and (3.13) give immediately (3.14).

When \(l=1\), we must resort to (2.30) and (3.6):

(3.16) \[\begin{split}\|u-u_{h}\|_{\tilde{X}}\leqslant& C_{4}\{\,\|\omega-P_{h}\omega\|_{0,\,\Omega}+|\psi-\hat{P}_{h} \psi|_{1,\,s,\Omega}\\ &+\,h^{k-1/2-1/p}\|\psi\|_{k+1,\,p,\,\Omega}\}.\end{split}\]
