Proof.: \(1^{\circ}\)) In view of Theorem 3.4, there exists \(\phi\) in \(H^{1}(\Omega)^{3}\) satisfying (3.23). Therefore, if we can find \(\psi\) in \(H(\mathbf{curl};\Omega)\) such that

(3.26) \[\left\{\begin{aligned} &\mathbf{curl}\,\psi=\mathbf{0}\\ &\operatorname{div}\psi=0\end{aligned}\right\}\text{ in }\Omega,\] \[\psi\!\cdot\!\mathbf{n}=\phi\!\cdot\!\mathbf{n}\quad\text{ on }\Gamma,\]

the difference \(\phi\!-\!\psi\) will be the desired function. Keeping this in mind, let \(\chi\!\in\!H^{1}(\Omega)/\mathbb{R}\) be the solution of the non-homogeneous Neumann's problem:

(3.27) \[\left\{\begin{aligned} &\mathcal{A}\chi=0\quad\text{in }\Gamma,\\ &\partial\chi/\partial n=\phi\!\cdot\!\mathbf{n}\quad\text{on } \Gamma.\end{aligned}\right.\]

Then

\[\psi=\mathbf{grad}\,\chi\]

satisfies precisely (3.26) and of course belongs to \(H(\mathbf{curl};\Omega)\).

When \(\Omega\) is simply-connected, the uniqueness of \(\phi\) is an obvious consequence of Remark 2.2. In addition, it is clear that \(\phi\) satisfies (3.25). Conversely (3.25) has at most one solution, for if (3.25) holds with \(\mathbf{v}=\mathbf{0}\) then, on the one hand \(\mathbf{curl}\,\phi\!\in\!H\) and on the other hand \(\mathbf{curl}\,\phi\!\in\!\operatorname{Ker}(\mathbf{curl})\). Therefore \(\mathbf{curl}\,\phi\!=\!\mathbf{0}\). And since \(\phi\!\in\!H\), Remark 2.2 implies again that \(\phi\!=\!\mathbf{0}\).

\(2^{\circ}\)) If \(\Gamma\) is of class \(\mathscr{C}^{1,\,1}\), then \(\phi\!\cdot\!\mathbf{n}\!\in\!H^{1/2}(\Gamma)\). Therefore, Theorem 1.10 (with \(k=0\)) asserts that \(\chi\!\in\!H^{2}(\Omega)\). Hence \(\mathbf{grad}\,\chi\!\in\!H^{1}(\Omega)^{3}\). 

**Theorem 3.6**.: \(1^{\circ}\)_Each function in \(L^{2}(\Omega)^{3}\) that satisfies (3.1) has at most one divergence-free vector potential \(\phi\!\in\!H(\mathbf{curl};\Omega)\) that satisfies the boundary conditions:_

(3.28) \[\phi\times\mathbf{n}=\mathbf{0}\quad\text{on }\Gamma,\quad\ \ \langle\phi\!\cdot\!\mathbf{n},1\rangle_{\Gamma_{i}}=0,\quad\ 0\leqslant i\leqslant p.\]

\(2^{\circ}\)) _When \(\Omega\) is simply-connected, each \(\mathbf{v}\!\in\!H\) has exactly one divergence-free vector potential \(\phi\) in \(H(\mathbf{curl};\Omega)\) satisfying (3.28). It is characterized as the only solution of the boundary value problem:_

(3.29) \[\left\{\begin{aligned} &-\mathcal{A}\phi=\mathbf{curl}\, \mathbf{v}\quad\text{in }H^{-1}(\Omega)^{3},\\ &\operatorname{div}\phi=0\quad\text{in }\Omega,\\ &\phi\text{ satisfies \eqref{eq:2.2}}.\end{aligned}\right.\]

\(3^{\circ}\)) _In addition to the above hypotheses, if \(\Gamma\) is \(\mathscr{C}^{1,\,1}\) or if \(\Omega\) is a convex polyhedron, then this vector potential \(\phi\) belongs to \(H^{1}(\Omega)^{3}\)._

Proof.: \(1^{\circ}\)) We proceed by contradiction. Assume that \(\phi\!\in\!H(\mathbf{curl};\Omega)\) satisfies:

\[\mathbf{curl}\,\phi\!=\!\mathbf{0}\quad\text{in }\Omega,\quad\ \phi\times \mathbf{n}=\mathbf{0}\quad\text{on }\Gamma,\] \[\operatorname{div}\phi=0\quad\text{in }\Omega,\quad\ \ \langle\phi\!\cdot\!\mathbf{n},1\rangle_{\Gamma_{i}}=0\quad\text{for }0 \leqslant i\leqslant p.\]

Then Remark 3.9 says that \(\phi\!=\!\mathbf{0}\).
