**Theorem 2.12**.: _We have_

\[\operatorname{Ker}(\gamma_{\tau})=H_{0}(\operatorname{\mathbf{curl}};\Omega).\]

Proof.: By taking limits in (2.22), it is clear that \(H_{0}(\operatorname{\mathbf{curl}};\Omega)\subset\operatorname{Ker}(\gamma_{ \tau})\). The converse is an obvious application of Lemma 2.4. 

_Remark 2.3_.: The tangential components on \(\Gamma\) of a vector field \(\mathbf{v}\) are defined formally by:

\[\mathbf{v}_{T}=\mathbf{v}-(\mathbf{v}\boldsymbol{\cdot}\mathbf{n})\mathbf{n}.\]

Clearly, we have \(\mathbf{v}_{T}\times\mathbf{n}=\mathbf{v}\times\mathbf{n}\). As a consequence, each vector field \(\mathbf{v}\) of \(H(\operatorname{\mathbf{curl}};\Omega)\) satisfies \(\mathbf{v}\times\mathbf{n}|_{\Gamma}=\mathbf{0}\) iff its tangential components vanish on \(\Gamma\). Similarly, each function \(q\) of \(H^{1}(\Omega)\) satisfies \((\operatorname{\mathbf{grad}}q)\times\mathbf{n}=\mathbf{0}\) on \(\Gamma\) iff \(q\) is constant on each connected component of \(\Gamma\).

_Remark 2.4_.: When \(N=2\), we observe that the function \(\mathbf{v}=(v_{1},v_{2})\) belongs to \(H(\operatorname{curl};\Omega)\) iff the function \(\mathbf{w}=(-v_{2},v_{1})\) belongs to \(H(\operatorname{div};\Omega)\). Moreover, \(\mathbf{w}\boldsymbol{\cdot}\mathbf{n}=-\mathbf{v}\boldsymbol{\cdot}\mathbf{n}\). Hence all the properties of \(H(\operatorname{div};\Omega)\) stated in Theorems 2.4, 2.5, 2.6 and Corollary 2.8 carry over directly to \(H(\operatorname{curl};\Omega)\).

_Remark 2.5_.: If \(\mathbf{v}\in H_{0}(\operatorname{\mathbf{curl}};\Omega)\), then \(\operatorname{\mathbf{curl}}\mathbf{v}\in H\). Indeed, since \(\operatorname{div}\operatorname{\mathbf{curl}}\mathbf{v}=0\), it suffices to check that \((\operatorname{\mathbf{curl}}\mathbf{v})\boldsymbol{\cdot}\mathbf{n}=0\). For \(\phi\) in \(H^{2}(\Omega)\), Green's formulas (2.17) and (2.22) imply that

\[\langle(\operatorname{\mathbf{curl}}\mathbf{v})\boldsymbol{\cdot}\mathbf{n}, \phi\rangle_{\Gamma}=\int_{\Omega}\operatorname{\mathbf{curl}}\mathbf{v} \boldsymbol{\cdot}\operatorname{\mathbf{grad}}\phi\,dx=\langle\mathbf{v} \times\mathbf{n},\operatorname{\mathbf{grad}}\phi\rangle_{\Gamma}=0.\]

Hence the result follows from the density of \(H^{2}(\Omega)\) in \(H^{1}(\Omega)\).

We end this paragraph by examining the intersection of \(H_{0}(\operatorname{div};\Omega)\) and \(H_{0}(\operatorname{\mathbf{curl}};\Omega)\).

**Lemma 2.5**.: _The following equality holds algebraically and topologically:_

\[H_{0}^{1}(\Omega)^{N}=H_{0}(\operatorname{div};\Omega)\cap H_{0}(\operatorname {\mathbf{curl}};\Omega).\]

Proof.: We establish the lemma for \(N=3\); the proof is similar and simpler when \(N=2\). Let \(\mathbf{v}\in H_{0}(\operatorname{div};\Omega)\cap H_{0}(\operatorname{ \mathbf{curl}};\Omega)\) and let \(\tilde{\mathbf{v}}\) denote the extension of \(\mathbf{v}\) by zero outside \(\Omega\). From Green's formulas (2.17) and (2.22), we easily derive that \(\tilde{\mathbf{v}}\in H(\operatorname{div};\mathbb{R}^{3})\cap H(\operatorname {\mathbf{curl}};\mathbb{R}^{3})\) with

\[\|\operatorname{div}\tilde{\mathbf{v}}\|_{0,\,\mathbb{R}^{3}} = \|\operatorname{div}\mathbf{v}\|_{0,\,\Omega},\] \[\|\operatorname{\mathbf{curl}}\tilde{\mathbf{v}}\|_{0,\,\mathbb{R }^{3}} = \|\operatorname{\mathbf{curl}}\mathbf{v}\|_{0,\,\Omega},\] \[\|\tilde{\mathbf{v}}\|_{0,\,\mathbb{R}^{3}} = \|\mathbf{v}\|_{0,\,\Omega}.\]
