Therefore, Problem (P) may be equivalently stated in the following way:

\(\mathit{Find}\ w=u-u_{0}\in V\) _satisfying_

\[a(w,v)=\langle l,v\rangle-a(u_{0},v)\ \ \ \ \ \forall v\in V\]

or satisfying

\[\pi Aw=\pi(l-Au_{0}).\]

Since \(\pi A\) is an isomorphism from \(V\) onto \(V^{\prime}\), Problem (P) has a unique solution \(u=u_{0}+w\in V(\chi)\) and we have

\[\|\,w\|_{X}\leqslant C_{1}\,\|\,\pi(l-Au_{0})\|_{V^{\prime}}\leqslant C_{1}\, \|\,l-Au_{0}\|_{X},\]

so that

\[\|\,u\|_{X}\leqslant C_{2}(\|\,l\|_{X^{\prime}}+\|\,\chi\|_{M^{\prime}}).\]

Now, \(l-Au\) belongs to \(V^{0}\). Thus, according to Lemma 4.1, there exists a unique \(\lambda\in M\) such that

\[B^{\prime}\lambda=l-Au\]

with

\[\|\,\lambda\|_{M}\leqslant(1/\beta)\,\|\,l-Au\|_{X^{\prime}}\leqslant C_{3}( \|\,l\|_{X^{\prime}}+\|\,\chi\|_{M^{\prime}}).\]

Hence, Problem (Q) has a unique solution \((u,\lambda)\) and the mapping \((l,\chi)\to(u,\lambda)\) is continuous from \(X^{\prime}\times M^{\prime}\) onto \(X\times M\). This means that \(\Phi\) is an isomorphism from \(X^{\prime}\times M^{\prime}\) onto \(X\times M\).

\(2^{\circ})\) The conditions (i) and (ii) are necessary. Assume that \(\Phi\) is an isomorphism from \(X\times M\) onto \(X^{\prime}\times M^{\prime}\). We first show that the inf-sup condition (4.9) holds. Let \(\chi\) be in \(M^{\prime}\) and set \((u,\lambda)=\Phi^{-1}(0,\chi)\). We have \(Bu=\chi\) so that \(\mathcal{R}(B)=M^{\prime}\). Hence \(B\) is a continuous and one-to-one mapping from \(V^{\perp}\) onto \(M^{\prime}\), and therefore an isomorphism from \(V^{\perp}\) onto \(M^{\prime}\). Thus, by virtue of Lemma 4.1, the condition (4.9) holds.

Let us next prove that \(\pi A\) is an isomorphism from \(V\) onto \(V^{\prime}\). We first check that the operator \(\pi A\) is injective on \(V\). Indeed, let \(u\in V\) satisfy \(\pi Au=0\) so that \(Au\in V^{0}\). Since the inf-sup condition holds, it follows from Lemma 4.1 that \(B^{\prime}\) is an isomorphism from \(M\) onto \(V^{0}\). Hence, there exists a unique \(\lambda\in M\) such that \(B^{\prime}\lambda=-Au\). Thus, we have \(\Phi(u,\lambda)=(0,0)\) and therefore, \(u=0\).

Now, we check that \(\pi A\) is surjective. Let \(g\) be in \(V^{\prime}\). By the Hahn-Banach Theorem, there exists at least one element \(l\in X^{\prime}\) such that \(g=\pi l\). We set \((u,\lambda)=\Phi^{-1}(l,0)\). Clearly, \(u\in V\) and

\[Au+B^{\prime}\lambda=l.\]

Since for all \(v\in V\)

\[\langle\pi B^{\prime}\lambda,v\rangle=\langle B^{\prime}\lambda,v\rangle= \langle\lambda,Bv\rangle=0,\]

we have \(\pi B^{\prime}\lambda=0\) so that
