For this, let \(\mathbf{q}\) denote an arbitrary (but fixed) representative of the solution of (3.30) and, just here, let \(\mathcal{A}^{-1}(\mathbf{q})\) denote the corresponding solution of (3.31). For \(\mathbf{c}\in\mathbb{R}^{p+1}\), we set:

\[\chi(\mathbf{c})=\mathcal{A}^{-1}(\mathbf{q})+\mathcal{A}^{-1}(\mathbf{c}),\]

and

\[\mathbf{w}(\mathbf{c})=\mathbf{grad}\,\chi(\mathbf{c})=\mathbf{grad}\, \mathcal{A}^{-1}(\mathbf{q})+\mathbf{grad}\,\mathcal{A}^{-1}(\mathbf{c}).\]

Let us examine more closely the properties of \(\mathbf{grad}\,\mathcal{A}^{-1}(\mathbf{c})\). First, we observe that the set \(E=\{\mathbf{grad}\,\mathcal{A}^{-1}(\mathbf{c});\mathbf{c}\in\mathbb{R}^{p+1}\}\) is a \(p\)-dimensional subspace of

\[F=\{\mathbf{v}\in L^{2}(\Omega)^{N};\,\mathrm{div}\,\mathbf{v}=0,\mathbf{curl} \,\mathbf{v}=\mathbf{0},\mathbf{v}\,\times\,\mathbf{n}|_{\Gamma}=\mathbf{0}\}\]

because \(\mathcal{A}^{-1}\) is an isomorphism and \(\mathrm{Ker}(\mathbf{grad})\) has dimension \(1\). Next, we note that:

\[\langle\mathbf{v}\,\mathbf{\cdot}\,\mathbf{n},1\rangle_{\Gamma_{0}}=-\sum_{i= 1}^{p}\,\langle\mathbf{v}\,\mathbf{\cdot}\,\mathbf{n},1\rangle_{\Gamma_{i}} \quad\text{for all divergence-free }\mathbf{v}.\]

Hence, if we prove that the mapping \(\mathbf{v}\,\mathbf{\cdot}\,(\langle\mathbf{v}\,\mathbf{\cdot}\,\mathbf{n},1 \rangle_{\Gamma_{i}})_{1\leqslant i\leqslant p}\) from \(E\) into \(\mathbb{R}^{p}\) is injective, it will be automatically surjective since \(E\) and \(\mathbb{R}^{p}\) have the same dimension. But it follows immediately from \(1^{\circ}\) that this mapping is indeed injective. Therefore, we can find \(\mathbf{c}\) in \(\mathbb{R}^{p+1}\) such that

\[\langle\mathbf{w}(\mathbf{c})\,\mathbf{\cdot}\,\mathbf{n},1\rangle_{\Gamma_{ i}}=\langle\mathbf{\psi}\,\mathbf{\cdot}\,\mathbf{n},1\rangle_{\Gamma_{i}} \quad\text{for }0\leqslant i\leqslant p,\]

and the function \(\phi=\psi\,-\,\mathbf{w}(\mathbf{c})\) does satisfy (3.23), (3.28) and also (3.29).

Finally, let us prove that (3.29) has at most one solution. When \(\mathbf{v}=\mathbf{0}\), we have \(\mathbf{curl}\,\phi\in\mathrm{Ker}(\mathbf{curl})\) and also \(\mathbf{curl}\,\phi\in H\), owing to Remark 2.5. Hence, Remark 2.2 implies that \(\mathbf{curl}\,\phi=\mathbf{0}\). Therefore, according to Remark 3.9, \(\phi=\mathbf{0}\).

\(3^{\circ}\)) Since the functions \(q_{i}\) belong to \(H^{2}(\Omega_{i})\), it follows from Theorem 1.8 that the solution \(\chi\) of (3.31) belongs to \(H^{2}(\Omega)\) provided either \(\Gamma\) is \(\mathcal{C}^{1,1}\) or \(\Omega\) is a convex polyhedron. Therefore \(\mathbf{w}\in H^{1}(\Omega)^{3}\) and so does \(\phi\). 

_Remark 3.14_.: When \(\Omega\) is a bounded, convex polyhedron and \(\mathbf{v}\,\mathbf{\in}\,H\cap L^{s}(\Omega)^{3}\) for some \(s>2\) we derive from Theorem 3.6 and Remark 3.11 that its unique vector potential \(\phi\) satisfying

\[\mathrm{div}\,\phi=0,\quad\ \phi\,\times\,\mathbf{n}=\mathbf{0}\quad\text{on }\Gamma\]

has the extra regularity: \(\phi\,\mathbf{\in}\,W^{1,p}(\Omega)^{3}\) for some \(p\) with \(2<p\leqslant s\). Indeed the regularity of \(\phi\) is determined, through Problem (3.31), by the regularity of the solution of a Dirichlet problem (for \(-\mathcal{A}\)) with right-hand side in \(L^{s}(\Omega)\) (cf. Theorem 1.8).

Like in the two-dimensional case, we derive from Theorem 3.6 the following decomposition of \(L^{2}(\Omega)^{3}\) and \(H^{1}_{0}(\Omega)^{3}\).

**Corollary 3.4**.: _Every function \(\mathbf{v}\) of \(L^{2}(\Omega)^{3}\) has the orthogonal decomposition_:__

(3.22) \[\mathbf{v}=\mathbf{grad}\,q+\mathbf{curl}\,\phi,\]
