**Theorem 3.3**.: _Assume that \(G\) is a \(\mathscr{C}^{2}\)-mapping from \(\Lambda\times X\) into \(Y\) and the mapping \(D^{2}\,G\) is bounded on all bounded subsets of \(\Lambda\times X\). Assume in addition that the conditions (3.36), (3.37) and (3.38) hold and that \(\{(\lambda,u(\lambda));\lambda\in\Lambda\}\) is a branch of nonsingular solutions of (3.33). Then there exists a neighborhood \(\mathbb{O}\) of the origin in \(X\) and for \(h\leqslant h_{0}\) small enough a unique \(\mathscr{C}^{2}\)-function \(\lambda\in\Lambda\to u_{h}(\lambda)\in X\) such that:_

(3.39) \[\{(\lambda,u_{h}(\lambda));\,\lambda\in\Lambda\}\quad\text{is a branch of nonsingular solutions of \eqref{eq:h_1}},\] (3.40) \[u_{h}(\lambda)-u(\lambda)\in\mathbb{O}\quad\text{for all $\lambda\in \Lambda$}.\]

_Furthermore\(,\) there exists a constant \(K>0\) independent of \(h\) and \(\lambda\) with:_

(3.41) \[\|u_{h}(\lambda)-u(\lambda)\|_{X}\leqslant K\,\|(T_{h}-\,T)G(\lambda,u( \lambda))\|_{X}\quad\quad\forall\lambda\in\Lambda.\]

Proof.: We are going to apply Theorem 3.2 with \(\tilde{u}_{h}(\lambda)=u(\lambda).\) Since by assumption the mapping \((\lambda,u)\to G(\lambda,u)\) is \(\mathscr{C}^{2},\) then \((\lambda,u)\to F(\lambda,u)\) is also \(\mathscr{C}^{2}\) and so is \(\lambda\to u(\lambda).\)

Let us check the condition (3.25). We have

\[\mu_{h}(\lambda)=\|(T-\,T_{h})D_{u}G(\lambda,u(\lambda))\|_{\mathscr{L}(X;X)}.\]

Then (3.36), (3.38) and the continuity of the mapping \(\lambda\to D_{u}G(\lambda,u(\lambda))\) yield (3.25). Next, we turn to (3.27). Since

\[F(\lambda,u(\lambda))=0\]

we can write:

\[\varepsilon_{h}(\lambda) =\|\,F_{h}(\lambda,u(\lambda))-F(\lambda,u(\lambda))\|_{X}\] \[=\|(T_{h}-\,T)G(\lambda,u(\lambda))\|_{X}.\]

Hence the continuity of the mapping \(\lambda\to G(\lambda,u(\lambda))\) and (3.37) imply (3.27). Finally, consider (3.28). Using (3.27) and the uniform-boundedness theorem we obtain

\[\|\,T_{h}\|_{\mathscr{L}(Y;X)}\leqslant C.\]

Therefore,

\[L_{h}(\lambda;\alpha)\leqslant C\sup_{v\,\in\,S(u(\lambda);\alpha)}\|\,D_{u}G (\lambda,u(\lambda))-\,D_{u}G(\lambda,v)\|_{\mathscr{L}(X;Y)}.\]

Thus, by the mean-value theorem:

\[L_{h}(\lambda;\alpha)\leqslant\alpha CL(\alpha)\]

where

\[L(\alpha)=\sup_{\lambda\,\in\,\Lambda,\,v\,\in\,S(u(\lambda);\alpha)}\|\,D_{ uu}^{2}G(\lambda,v)\|_{\mathscr{L}_{2}(X;Y)}.\]

As \(D^{2}\,G\) is bounded on all bounded subsets of \(\Lambda\times X,\) we immediately derive (3.28).

Therefore, the conclusion of Theorem 3.2 holds, (3.41) follows readily from
