and with \(F_{\kappa}^{-1}\):

\[(\hat{\theta}\colon\hat{\kappa}\to\mathbb{R})\to(v=\hat{\epsilon}\circ F_{\kappa} ^{-1}\colon\kappa\to\mathbb{R})\]

are of constant use because they enable us to work exclusively on the reference element \(\hat{\kappa}\). The effects of this change of variable are described in the next lemma.

**Lemma A.1**.: _For each integer \(m\geq 0\) and for all real \(p\) with \(1\leq p\leq\infty,\) the mapping \(v\to\hat{\epsilon}=v\circ F_{\kappa}\) is an isomorphism from \(W^{m,\,p}(\kappa)\) onto \(W^{m,\,p}(\hat{\kappa})\) and the following bounds hold:_

\[|\hat{\epsilon}|_{m,\,p,\,\hat{\kappa}} \leq C_{1}\,\|\,B_{\kappa}\,\|^{m}\|\det(B_{\kappa})|^{-1/p}|v|_{m, \,p,\,\kappa} \forall v\in W^{m,\,p}(\kappa),\] (A.7) \[|v|_{m,\,p,\,\kappa} \leq C_{2}\,\|B_{\kappa}^{-1}\,\|^{m}\|\det(B_{\kappa})|^{1/p}| \hat{\epsilon}|_{m,\,p,\,\hat{\kappa}} \forall\hat{v}\in W^{m,\,p}(\hat{\kappa}).\] (A.8)

Note that the gradient of a function and the unit normal vector have the simple expressions (cf. for instance Babuska & _al_[5]):

\[\mathbf{grad}_{\hat{\kappa}}\,\hat{\epsilon}(\hat{x})=(B_{\kappa}^{T}\, \mathbf{grad}_{\kappa}\,v)\circ F_{\kappa}(\hat{x}),\] (A.9) \[\hat{\mathbf{n}}(\hat{x})=[(B_{\kappa}^{T}\mathbf{n})/\|\,B_{ \kappa}^{T}\mathbf{n}\,\|]\circ F_{\kappa}(\hat{x}),\] (A.10)

where \(\mathbf{n}\) (resp. \(\hat{\mathbf{n}}\)) denotes the unit exterior normal to \(\kappa\) (resp. \(\hat{\kappa}\)).

The following theorem (which is an extension of Theorem I.1.9) and its consequences are fundamental tools of the finite element theory.

**Theorem A.1**.: _For each integer \(k\geq 0\) and real \(p\) with \(1\leq p\leq\infty,\) there exists a constant \(\hat{C}>0,\) depending only on \(k,\)\(p\) and \(\hat{\kappa},\) such that:_

\[\inf_{t\,\in\,P_{k}}\|\,\hat{u}\,+\,t\|_{k+1,\,p,\,\hat{\kappa}} \leq\hat{C}|\hat{u}|_{k+1,\,p,\,\hat{\kappa}} \forall\hat{u}\in W^{k+1,\,p}(\hat{\kappa})/P_{k}.\] (A.11)

**Corollary A.1**.: _Let \(k\geq 0,\)\(m\geq 0\) be integers and \(p\geq 1,\)\(q\geq 1\) be reals such that_

\[W^{k+1,\,p}(\hat{\kappa})\subset W^{m,\,q}(\hat{\kappa}).\]

_Let \(\hat{\pi}\in\mathscr{L}(W^{k+1,\,p}(\hat{\kappa});W^{m,\,q}(\hat{\kappa}))\) satisfy:_

\[\hat{\pi}t=t\quad\quad\forall t\in P_{k}.\]

_Then there exists a constant \(\hat{C}>0\) depending on \(k,\)\(m,\)\(p,\)\(q,\)\(\hat{\kappa}\) and \(\hat{\pi}\) only\(,\) such that_

\[\|\hat{\epsilon}-\hat{\pi}\hat{\epsilon}\|_{m,\,q,\,\hat{\kappa}} \leq\hat{C}|\hat{v}|_{k+1,\,p,\,\hat{\kappa}}\quad\quad\forall\hat{v}\in W^{k +1,\,p}(\hat{\kappa}).\] (A.12)

When combined with Lemma A.1, (A.2) and (A.3), Corollary A.1 yields:

**Corollary A.2**.: _Let \(k,\)\(m,\)\(p,\)\(q\) and \(\hat{\pi}\) be like in Corollary A.1. Let \(\kappa\) be an \(N\)-simplex of \(\,\mathbb{R}^{N}\) and let the operator \(\pi\in\mathscr{L}(W^{k+1,\,p}(\kappa);W^{m,\,q}(\kappa))\) be defined by:_

\[(\pi v)\circ F_{\kappa}=\hat{\pi}(v\circ F_{\kappa})\quad(\text{i.e.}\ \widehat{\pi v}=\hat{\pi}\hat{v}).\] (A.13)

_Then there exists a constant \(C>0,\) depending only on \(k,\)\(m,\)\(p,\)\(q,\)\(\hat{\kappa}\) and \(\hat{\pi}\) such that_

\[\|\hat{\epsilon}-\hat{\pi}\hat{\epsilon}\|_{m,\,q,\,\hat{\kappa}} \leq\hat{C}|\hat{v}|_{k+1,\,p,\,\hat{\kappa}}\quad\quad\forall\hat{v}\in W^{k +1,\,p}(\hat{\kappa}).\] (A.14)

_Then there exists a constant \(C>0,\) depending only on \(k,\)\(m,\)\(p,\)\(q,\)\(\hat{\kappa}\) and \(\hat{\pi}\) such that_

\[\|\hat{\epsilon}-\hat{\pi}\hat{\epsilon}\|_{m,\,q,\,\hat{\kappa}} \leq\hat{C}|\hat{v}|_{k+1,\,p,\,\hat{\kappa}}\quad\quad\forall\hat{v}\in W^{k +1,\,p}(\hat{\kappa}).\] (A.15)

_Then there exists a constant \(C>0,\) depending only on \(k,\)\(m,\)\(p,\)\(q,\)\(\hat{\kappa}\) and \(\hat{\pi}\) such that_

\[\|\hat{\epsilon}-\hat{\pi}\hat{\epsilon}\|_{m,\,q,\,\hat{\kappa}} \leq\hat{C}|\hat{v}|_{k+1,\,p,\,\hat{\kappa}}\quad\quad\forall\hat{v}\in W^{k +1,\,p}(\hat{\kappa}).\] (A.16)

_Then there exists a constant \(C>0,\) depending only on \(k,\)\(m,\)\(p,\)\(q,\)\(\hat{\kappa}\) and \(\hat{\pi}\) such that_

\[\|\hat{\epsilon}-\hat{\pi}\hat{\epsilon}\|_{m,\,q,\,\hat{\kappa}} \leq\hat{C}|\hat{v}|_{k+1,\,p,\,\hat{\kappa}}\quad\quad\forall\hat{v}\in W^{k +1,\,p}(\hat{\kappa}).\] (A.17)

_Then there exists a constant \(C>0,\) depending only on \(k,\)\(m,\)\(p,\)\(q,\)\(\hat{\kappa}\) and \(\hat{\pi}\) such that_

\[\|\hat{\epsilon}-\hat{\pi}\hat{\epsilon}\|_{m,\,q,\,\hat{\kappa}} \leq\hat{C}|\hat{v}|_{k+1,\,p,\,\hat{\kappa}}\quad\quad\forall\hat{v}\in W^{k +1,\,p}(\hat{\kappa}).\] (A.18)

_Then there exists a constant \(C>0,\) depending only on \(k,\)\(m,\)\(p,\)\(q,\)\(\hat{\kappa}\) and \(\hat{\pi}\) such that_

\[\|\hat{\epsilon}-\hat{\pi}\hat{\epsilon}\|_{m,\,q,\,\hat{\kappa}} \leq\hat{C}|\hat{v}|_{k+1,\,p,\,\hat{\kappa}}\quad\quad\forall\hat{v}\in W^{k +1,\,p}(\hat{\kappa}).\] (A.19)

_Then there exists a constant \(C>0,\) depending only on \(k,\)\(m,\)\(p,\)\(q,\)\(\hat{\kappa}\) and \(\hat{\pi}\) such that_

\[\|\hat{\epsilon}-\hat{\pi}\hat{\epsilon}\|_{m,\,q,\,\hat{\kappa}} \leq\hat{C}|\hat{v}|_{k+1,\,p,\,\hat{\kappa}}\quad\quad\forall\hat{v}\in W^{k +1,\,p}(\hat{\kappa}).\] (A.20)

_Then there exists a constant \(C>0,\) depending only on \(k,\)\(m,\)
