We denote by \(S_{i}\) the subtriangle of \(\kappa\) with vertices \(a_{i-1}\), \(a_{i}\) and \(a_{i+1}\) (where of course \(a_{0}\) coincides with \(a_{4}\)). Note that unless \(\kappa\) is a parallelogram, the mapping \(F_{\kappa}\) is not affine, but nevertheless it maps the sides of \(\hat{\kappa}\) onto the corresponding sides of \(\kappa\) and in fact the restriction of \(F_{\kappa}\) to the sides of \(\hat{\kappa}\) is affine.

For each \(\hat{x}\), let \(DF_{\kappa}(\hat{x})=[\partial F_{i}(\hat{x})/\partial\hat{x}_{j}]_{i,j}\in \mathcal{L}(\mathbb{R}^{2};\mathbb{R}^{2})\) denote the derivative of \(F_{\kappa}\) at the point \(\hat{x}\) with the following norm:

\[\|DF_{\kappa}\|_{\infty,\,\kappa}=\sup_{\hat{x}\,\in\,\hat{\kappa}}\|DF_{ \kappa}(\hat{x})\|,\]

where as usual \(\|\cdot_{n}\|\) stands for the subordinate Euclidean norm, and let \(J_{F}\) denote the Jacobian of \(F_{\kappa}\), i.e.

\[J_{F}(\hat{x})=\det(DF_{\kappa}(\hat{x})).\]

Then, if \(F_{\kappa}^{-1}\) denotes the inverse of \(F_{\kappa}\) with Jacobian \(J_{F^{-1}}\), we have:

\[D(F_{\kappa}^{-1})\circ F_{\kappa}=(DF_{\kappa}^{T})^{-1},\quad\ J_{F^{-1}} \circ F_{\kappa}=1/J_{F}.\] (A.37)

Note again that when \(F_{\kappa}\) is affine, \(DF_{\kappa}=B_{\kappa}\), \(D(F_{\kappa}^{-1})=(B_{\kappa}^{T})^{-1}\) and \(J_{F}=\det(B_{\kappa})\). Of course, since \(J_{F}\) is not constant the simple relation (A.3) does not hold here but a plain calculation shows that \(J_{F}\) belongs to \(P_{1}\). Hence, its extrema are attained at the vertices of \(\hat{\kappa}\). Thus it is easy to check that

\[\left\{\begin{aligned} &\operatorname*{Max}_{\hat{x}\,\in\,\hat{\kappa}}J_{F}( \hat{x})=2\operatorname*{Max}_{1\,\leq i\leq 4}\operatorname*{meas}(S_{i}),\\ &\operatorname*{Min}_{\hat{x}\,\in\,\hat{\kappa}}J_{F}(\hat{x})= 2\operatorname*{Min}_{1\,\leq i\leq 4}\operatorname*{meas}(S_{i}),\end{aligned}\right.\] (A.38)

and observe that

\[J_{F}(\hat{x})\geq 0\]

because \(\kappa\) is convex. Furthermore,

\[J_{F}(1/2,1/2)=\operatorname*{meas}(\kappa).\]

Hence, a glance at (A.37) and (A.38) shows that a convenient choice of parameters to describe the geometry of \(\kappa\) is:

\[h_{\kappa}=\text{diameter of }\kappa,\] \[\rho_{\kappa}=2\operatorname*{Min}_{1\,\leq i\leq 4}\{\text{diameter of circle inscribed in }S_{i}\}.\]

This choice leads to the following upper bounds:

\[\left\{\begin{aligned} &\|DF_{\kappa}\|_{\infty,\,\kappa}\leq C_{1}h_{ \kappa},\quad\quad\|J_{F}\|_{\infty,\,\hat{\kappa}}\leq C_{2}h_{\kappa}^{2}\\ &\|DF_{\kappa}^{-1}\|_{\infty,\,\kappa}\leq C_{3}(h_{\kappa}/ \rho_{\kappa}^{2}),\quad\quad\|J_{F^{-1}}\|_{\infty,\,\kappa}\leq C_{4}(1/\rho _{\kappa}^{2}),\end{aligned}\right.\] (A.39)

where all constants involved are independent of the geometry of \(\kappa\).

We use the same concept for the triangulation \(\mathcal{T}_{h}\) except that here it is made of _convex quadrilaterals_ instead of triangles and with the above parameters, we retain _Definition A.2 for a regular and uniformly regular triangulation_. Note that
