\[M_{f}(\mathfrak{u})=\{0\}\Leftrightarrow\int_{f}\mathfrak{u}\cdot\mathfrak{q}\,ds=0 \quad\quad\forall\mathfrak{q}\in P_{t-2}^{3}(\kappa)\quad\text{such that}\quad \mathfrak{q}\cdot\mathfrak{n}=0.\]

Therefore, applying (5.26) and (5.27) we have:

\[M_{f}(\mathfrak{u})=\{0\}\Leftrightarrow \int_{\hat{f}}\hat{\mathfrak{u}}\cdot(B_{\kappa}^{-1})(\mathfrak{ q}\circ F_{\kappa})\,d\hat{s}=0\quad\quad\forall\mathfrak{q}\in P_{t-2}^{3}(\kappa)\] \[\text{such that}\quad(B_{\kappa}^{-1})(\mathfrak{q}\circ F_{ \kappa})\cdot\hat{\mathfrak{u}}=0\] \[\Leftrightarrow M_{\hat{f}}(\hat{\mathfrak{u}})=\{0\}.\]

Likewise, owing to (5.28) we readily derive that

\[M_{e}(\mathfrak{u})=\{0\}\Leftrightarrow M_{\hat{e}}(\hat{\mathfrak{u}})=\{0\}.\qed\]

Now we turn to the unisolvence. Let us start with a boundary result.

**Lemma 5.7**.: _A vector \(\mathfrak{u}\) of \(R_{l}\) has all its moments zero on a given face \(f\) of \(\kappa\) iff the tangential components of \(\mathfrak{u}\) vanish on \(f\)._

Proof.: As all conditions involved are preserved by an affine transformation, we can assume that the face \(f\) lies on the plane \(x_{3}=0\). Then the tangential components \(\mathfrak{u}_{T}\) of \(\mathfrak{u}\) on \(f\) reduce to its first two components:

\[\mathfrak{u}_{T}(x_{1},x_{2})=(u_{1}(x_{1},x_{2},0),u_{2}(x_{1},x_{2},0)).\]

Moreover, the conditions \(M_{f}(\mathfrak{u})=\{0\}\) and \(M_{e}(\mathfrak{u})=\{0\}\) are respectively equivalent to:

(5.31) \[\int_{f}\mathfrak{u}_{T}\cdot\mathfrak{q}\,dx_{1}\,dx_{2}=0\quad\quad\forall \mathfrak{q}\in P_{t-2}^{2}(f),\]

(5.32) \[\int_{e}\mathfrak{u}_{T}\cdot\tau q\,de=0\quad\quad\forall q\in P_{t-1}(e).\]

Hence Green's formula (I.2.22) in two dimensions gives:

\[\int_{f}\operatorname{curl}\mathfrak{u}_{T}q\,dx_{1}\,dx_{2}=0\quad\quad \forall q\in P_{t-1}(f),\]

i.e.

\[\operatorname{curl}\mathfrak{u}_{T}=0\quad\text{on $f$}.\]

Now, it is easy to verify that \(\mathfrak{u}_{T}\) belongs to the two-dimensional analogue of \(R_{l}\). Therefore it follows from Lemma 5.3 and its Remark that

\[\mathfrak{u}_{T}=\operatorname{\mathbf{grad}}p\quad\text{with $p\in P_{l}(f)$}.\]

As a consequence, (5.32) implies that \(p\) is constant on the boundary \(\partial f\) of \(f\); thus we can take

\[p=0\quad\text{on $\partial f$},\]

i.e.

\[p=\lambda_{1}\lambda_{2}\lambda_{3}r\quad\text{with $r\in P_{t-3}(f)$},\]
