In order to analyze conveniently Problems (\(\tilde{\mathrm{P}}\)) and (\(\tilde{Q}\)) we make the following assumption on \(\tilde{a}(.,.)\):

the form \(\tilde{a}(.,.)\) is \(\tilde{V}\)-elliptic, i.e. there exists a constant \(\tilde{a}>0\) such that:

\[\tilde{a}(v,v)\geqslant\tilde{a}\,\|\,v\,\|_{\tilde{X}}^{2}\,\,\,\,\,\,\,\,\, \,\forall v\in\tilde{V}.\] (1.14)

Note that on the one hand (1.14) does not stem from (1.3) because \(\tilde{V}\) is (usually) a larger space than \(V\). On the other hand there is no inf-sup condition on \(\tilde{b}(.,.)\) except the one which follows from (1.4) and (1.7):

\[\sup_{v\in\tilde{X}}\frac{\tilde{b}(v,\mu)}{\|\,v\,\|_{\tilde{X}}}\geqslant(1/ C)\sup_{v\in X}\frac{\tilde{b}(v,\mu)}{\|\,v\,\|_{X}}\geqslant(\beta/C)\,\|\,\mu\|_{M }\,\,\,\,\,\,\,\,\,\,\,\forall\mu\in\tilde{M},\] (1.15)

where \(C\) is the continuity constant of the imbedding \(X\subset\tilde{X}\). Strictly speaking, this is not sufficient to ensure that Problem (\(\tilde{\mathrm{Q}}\)) is well posed. The next theorem tackles this difficulty.

**Theorem 1.1**.: _Let \((u,\dot{\iota})\) be the solution of Problem (\(\mathrm{Q}\)) and let \(\tilde{a}\) satisfy (1.14)._

\(1^{\circ}\)_Problem (\(\tilde{\mathrm{P}}\)) has exactly one solution \(\tilde{u}\) in \(\tilde{V}(\chi)\). Moreover, if \(\tilde{u}\) also belongs to \(V(\chi)\) or if \(V\) is dense in \(\tilde{V}\) then \(\tilde{u}=u\)._

\(2^{\circ}\)_In addition, if \(\dot{\iota}\) belongs to \(\tilde{M}\) then the pair \((u,\dot{\iota})\) is the only solution of Problem (\(\tilde{\mathrm{Q}}\))._

Proof.: To begin with, recall that the theory of Section I.4.1 applies also to reflexive Banach spaces (cf. Remark I.4.2).

\(1^{\circ}\)) The inf-sup condition (1.4) on \(b(.,.)\) implies that \(V(\chi)\) is not empty; hence \(\tilde{V}(\chi)\) is not empty. Then the ellipticity of \(\tilde{a}\) implies that Problem (\(\tilde{\mathrm{P}}\)) has one and only one solution \(\tilde{u}\) in \(\tilde{V}(\chi)\). If \(\tilde{u}\in V(\chi)\), we see from (1.6) that \(\tilde{u}\) is a solution of Problem (\(\mathrm{P}\)); therefore \(\tilde{u}=u\) since (\(\mathrm{P}\)) has exactly one solution. Otherwise, we assume that \(V\) is dense in \(\tilde{V}\); then (1.5) and (1.6) imply that \(u\) is a solution of Problem (\(\tilde{\mathrm{P}}\)). Thus \(u=\tilde{u}\).

\(2^{\circ}\)) In addition, suppose that \(\dot{\iota}\in\tilde{M}\). Then by virtue of (1.6) and (1.7), (1.1) becomes:

\[\tilde{a}(u,v)+\tilde{b}(v,\dot{\iota})=\langle\dot{\iota},v\rangle\,\,\,\,\, \,\,\,\,\,\forall v\in X.\]

As \(X\) is dense in \(\tilde{X}\), this shows that the pair \((u,\dot{\iota})\) is a solution of Problem (\(\tilde{\mathrm{Q}}\)). Finally, we must prove that it is the only solution of (\(\tilde{\mathrm{Q}}\)). Obviously, the first component \(u\) is unique. Then assume that

\[\tilde{b}(v,\dot{\iota})=0\,\,\,\,\,\,\,\,\,\,\forall v\in\tilde{X}.\]

With (1.15) this implies that \(\dot{\iota}=0\). 

_Remark 1.1_.: The assumption \(\dot{\iota}\in\tilde{M}\) is in fact a regularity condition.

In subsequent paragraphs, we shall study applications where the approximation of Problem (\(\tilde{\mathrm{Q}}\)) is simpler than that of Problem (\(\mathrm{Q}\)).
