\[\lim_{\theta\to 1}\left[p_{\theta}-p\right]_{\omega}=0.\]

Therefore \(p\in L^{2}(\Omega)\).

\(2^{\circ})\) In the general case, we use the following property (cf. for example Bernardi [8]):

_A bounded_, _Lipschitz-continuous open set is the union of a finite number of star-shaped_, _Lipschitz-continuous open sets_.

Clearly, it suffices to apply the above argument to each of these sets to derive the desired result on the entire domain. 

### Some Properties of Spaces Related to the Divergence Operator

Unless otherwise specified, we assume in this section that \(\Omega\) is a _bounded_ subset of \(\mathbb{R}^{N}\) with a _Lipschitz-continuous_ boundary \(\Gamma\).

For \(\mathbf{v}=(v_{1},\ldots,v_{N})\), we define the divergence operator by:

\[\operatorname{div}\mathbf{v}=\sum_{i=1}^{N}\left(\partial v_{i}/\partial x_{i }\right)\text{.}\]

Note the identity:

\[\operatorname{div}(\mathbf{grad}\,v)=\Delta v\text{.}\]

Let us introduce the following spaces of divergence-free functions:

\[\mathcal{V}=\{\phi\in\mathcal{D}(\Omega)^{N}\text{;}\operatorname{div}\phi=0\} ,\quad\ V=\{\mathbf{v}\in H^{1}_{0}(\Omega)^{N}\text{;}\operatorname{div} \mathbf{v}=0\}.\]

Here we equip \(H^{1}_{0}(\Omega)^{N}\) with the norm \(|.|_{1,\Omega}\), equivalent to \(\|.|_{1,\Omega}\) by virtue of Poincare's Theorem 1.1. Since \(V\) is a closed subspace of \(H^{1}_{0}(\Omega)^{N}\), we have the decomposition:

\[H^{1}_{0}(\Omega)^{N}=V\oplus V^{\perp},\]

where \(V^{\perp}\) denotes the orthogonal of \(V\) in \(H^{1}_{0}(\Omega)^{N}\) for the scalar product \((\mathbf{grad}\,u\), \(\mathbf{grad}\,v)\) associated with \(|.|_{1,\Omega}\).

The following lemma establishes a first coarse version of De Rham's Theorem (2.0).

**Lemma 2.1**.: _If \(\mathbf{f}\in H^{-1}(\Omega)^{N}\) satisfies_

(2.9) \[\langle\mathbf{f},\mathbf{v}\rangle=0\quad\quad\forall\mathbf{v}\in V\]

_then there exists \(p\in L^{2}(\Omega)\) such that_

\[\mathbf{f}=\mathbf{grad}\,p\text{.}\]

_When \(\Omega\) is connected, \(p\) is unique up to an additive constant._
