* [21] P. Clement. Approximation by finite element functions using local regularization. R.A.I.R.O. Anal. Numer. 9 R2, pp. 77-84. (1975).
* [22] M. Crouzeix. Approximation de problemes faiblement non lineaires. Pub. Univ Rennes. (To appear).
* [23] M. Crouzeix, P.-A. Raviart. Conforming and non conforming finite element methods for solving the stationary Stokes equations. R.A.I.R.O. R3, pp. 33-76. (1973).
* [24] J. Dominguez. Formulation en potentiel vecteur du systeme de Stokes dans un domaine de R\({}^{3}\). Anal. Numer. L.A. 189. Paris. (1983).
* [25] J. Douglas, T. Dupont, L. Wahlbin. Stability in L\({}^{q}\) of the L\({}^{2}\)-projection into finite element function spaces. Numer. Math. 23, pp. 193-197. (1975).
* [26] G. Duvaut, J.-L. Lions. _Les Inequations en Mecanique et en Physique_. Dunod. (1972).
* [27] G. Foias, R. Temam. Remarques sur les equations de Navier-Stokes stationnaires et les phenomenes successifs de bifurcation. Annali Scuola Normale Superiore Pisa, Serie IV vol. V n\({}^{\circ}\) 1, pp. 29-63. (1978).
* [28] M. Fortin. An analysis of the convergence of mixed finite element methods. R.A.I.R.O. Anal. Numer. 11 R3, pp. 341-354. (1977).
* [29] M. Fortin. Calcul numerique des ecoulements des fluides de Bingham et des fluides Newtoniens incompressibles par la methode des elements finis. These Univ. Paris. (1972).
* [30] M. Fortin. Old and new finite elements for incompressible flows. Int. Jour. Numer. Meth. Fluids, 1, pp. 347-364. (1981).
* [31] M. Fortin. Resolution numerique des equations de Navier-Stokes par des methodes d'elements finis de type mixte. Proc. 2nd Int. Symp. Finite Elements in Flow Problems, S. Margherita Ligure, Italy. (1978).
* [32] V. Girault, P.-A. Raviart. _Finite Element Approximation of the Navier-Stokes Equations_. Lect. Notes in Math. vol. 749. Springer-Verlag. (1979).
* [33] V. Girault, P.-A. Raviart. An analysis of a mixed finite element method for the Navier-Stokes equations. Numer. Math. vol. 33, pp. 235-271. (1979).
* [34] V. Girault, P.-A. Raviart. An analysis of upwind schemes for the Navier-Stokes equations. SIAM J. Numer. Anal. vol. 19 n\({}^{\circ}\) 2. pp. 312-333. (1982).
* [35] R. Glowinski. Approximations externes par elements finis de Lagrange d'ordre un et deux, du probleme de Dirichlet pour l'operateur biharmonique. Methodes iteratives de resolution des problemes approches. _Topics in Numerical Analysis_, pp. 123-171. Academic Press. (1973).
* [36] R. Glowinski. _Numerical Methods for Nonlinear Variational Problems_. Springer Series in Comp. Physics. Springer-Verlag. (1984).
* [37] R. Glowinski, O. Pironneau. _Energy Methods in Finite Element Analysis_. (R. Glowinski, E. Rodin, O. Zienkiewicz). Wiley, pp. 243-264. (1979).
* [38] R. Glowinski, O. Pironneau. On a mixed finite element approximation of the Stokes problem I. Convergence of the approximate solution. Numer. Math. 33, pp. 397-424. (1979).
* [39] R. Glowinski, O. Pironneau. Numerical methods for the first biharmonic equation and for the two-dimensional Stokes problem. SIAM Review vol. 21 n\({}^{\circ}\) 2, pp. 167-212. (1979).
* [40] J. Gobert. Sur une inegalite de coercive. J. of Math. Anal. and App. 36, pp. 529-555. (1971).
* [41] C. Goldstein. Variational crimes and L\({}^{\prime\prime}\). error estimates in the finite element method. Math. of Comp. vol. 35 n\({}^{\circ}\) 152, pp. 1131-1157. (1980).
* [42] P. Grisvard. _Boundary Value Problems in Non-Smooth Domains_. Univ. of Maryland, Dept. of Math. Lecture Notes n\({}^{\circ}\) 19. (1980).
* [43] P. Grisvard. Singularites des solutions du probleme de Stokes dans un polygone. Univ. de Nice. (1978).
* [44] P. Hood, C. Taylor. A numerical solution of the Navier-Stokes equations using the finite element technique. Comp. and Fluids 1, pp. 73-100. (1973).
* [45] E. Hopf. On Non-Linear Partial Differential Equations. Lecture Series of the Symp. on Partial Diff. Equations. Berkeley. (1955).
* [46] C. Johnson, J. Pitkaranta. Analysis of some mixed finite element methods related to reduced integration. Math. of Comp. vol. 38, pp. 375-400. (1982).
