\[\lambda_{ij}=\partial u_{i}/\partial x_{j}\quad\text{in each element $\kappa$,}\]

and in turn \(\operatorname{div}\mathbf{u}=0\) in \(\Omega\). Then, supposing that the right-hand side \(\mathbf{f}=\mathbf{0}\) we easily derive that \(\lambda_{ij}=0\) for all \(i,j\). Thus, \(\mathbf{u}\) is constant in each \(\kappa\) and moreover

\[\sum_{\kappa}\int_{\partial\kappa}M_{nt}(\tau)\mathbf{u}\cdot\mathbf{t}\,ds=0\]

\[\forall\tau\in H^{1}(\kappa)^{4}\quad\text{with $M_{nt}(\tau)$ continuous across the segments of $\Gamma_{h}$.}\]

In view of the fact that \(\mathbf{u}\) belongs to \(H_{0}(\operatorname{div};\Omega)\), this last relation readily implies that \(\mathbf{u}=\mathbf{0}\) in \(\Omega\). As a consequence, _Problem (4.8) is an equivalent formulation of the Stokes problem (2.1) whenever the solution of Problem (2.1) has sufficient regularity_.

To eliminate the pressure, Problem (4.8) can also be expressed in terms of stream functions. Indeed, recall that \(\mathbf{v}\in H_{0}(\operatorname{div};\Omega)\) satisfies \(\operatorname{div}\mathbf{v}=0\) iff:

\[\mathbf{v}=\operatorname{\mathbf{curl}}\phi\quad\text{with $\phi\in\Phi=\{\phi \in H^{1}(\Omega);\phi|_{\Gamma_{0}}=0,\phi|_{\Gamma_{i}}$ is constant, $1\leq i\leq p$}}.\]

If in addition \(\mathbf{v}|_{\kappa}\in H^{1}(\kappa)^{2}\) then \(\phi|_{\kappa}\in H^{2}(\kappa)\) and conversely. Then we can rewrite directly Problem (4.8) in terms of stream functions, but the notations are simplified if instead of working with the tensor \(\lambda\) we now introduce the symmetric tensor \(\sigma\):

\[\sigma_{ij}=\partial^{2}\psi/\partial x_{i}\partial x_{j}\quad\text{with $ \operatorname{\mathbf{curl}}\psi=\mathbf{u}$.}\] (4.9)

The correspondence between \(\sigma\) and \(\lambda\) is:

\[\left\{\begin{aligned} \lambda_{11}&=-\lambda_{22} =\sigma_{12},\quad\lambda_{21}&=-\sigma_{11},\quad\lambda_{12} =\sigma_{22},\\ M_{nt}(\lambda)&=-M_{n}(\sigma),\\ M_{n}(\lambda)&=M_{nt}(\sigma).\end{aligned}\right.\] (4.10)

This induces us to define the following space of tensors:

\[\Sigma=\{\tau=(\tau_{ij})\in L^{2}(\Omega)^{4};\,\tau|_{\kappa}\in H^{1}( \kappa)^{4}\quad\forall\kappa\in\mathcal{T}_{h},\,\tau_{12}=\tau_{21},\] (4.11) \[M_{n}(\tau)\text{ is continuous on each segment of $\Gamma_{h}$}\},\]

together with the space \(\tilde{\mathcal{V}}\) of stream functions (already introduced in Section 2.3):

\[\tilde{\mathcal{V}}=\{\phi\in\Phi;\phi|_{\kappa}\in H^{2}(\kappa)\quad\forall \kappa\in\mathcal{T}_{h}\}.\] (4.12)

With these spaces and the above correspondence, the sum of the surface integrals in (4.8) has also the following expression:

\[\sum_{\kappa\in\mathcal{T}_{h}}\int_{\partial\kappa}M_{nt}(\lambda)\mathbf{u} \cdot\mathbf{t}\,ds=\int_{\Gamma_{h}}M_{n}(\sigma)S(\partial\psi/\partial n) \,ds,\]

where \(S(\chi)\) denotes the jump of \(\chi\) over the segments of \(\mathcal{T}_{h}\) (cf. Section 2.3). Therefore, Problem (4.8) has the following equivalent formulation, called the _Hellan-Herrmann-Johnson formulation_:

_Find a pair \((\sigma,\psi)\in\Sigma\times\tilde{\mathcal{V}}\) satisfying_:
