(2.4) \[\begin{cases}Q_{h}=\{q\in L^{2}(\Omega);\,q|_{\kappa}\in P_{0},\quad\forall\kappa \in\mathcal{T}_{h}\},\\ \qquad\qquad\widetilde{M}_{h}=Q_{h}\cap L^{2}_{0}(\Omega).\end{cases}\]

(The bars on top of \(X_{h}\) and \(M_{h}\) are put to match the notation of Section 1.4.)

_Remark 2.1_.: Let \(\mathbf{p}\in\mathcal{P}_{1}(\kappa)\) and let

\[I_{\kappa}\mathbf{p}=\sum\limits_{i=1}^{3}\mathbf{p}(a_{i})\dot{\lambda}_{i}\]

denote its standard interpolant on \(P^{2}_{1}\). Then since \(\mathbf{p}_{i}(a_{j})=\mathbf{0}\) for \(1\leqslant i,j\leqslant 3\), \(\mathbf{p}\) has the form:

\[\mathbf{p}=I_{\kappa}\mathbf{p}+\sum\limits_{i=1}^{3}\alpha_{i}\mathbf{p}_{i} \quad\text{with }\alpha_{i}\in\mathbb{R}.\]

In addition, since \(\mathbf{p}_{i}|_{f_{j}}=\mathbf{0}\) for \(i\neq j\), we immediately derive that

\[\alpha_{i}\mathbf{p}_{i}|_{f_{i}}=(\mathbf{p}-I_{\kappa}\mathbf{p})|_{f_{i}}.\]

This remark suggests to choose the following degrees of freedom for the functions of \(\mathcal{P}_{1}(\kappa)\): the values of \(\mathbf{p}\) at the vertices \(a_{i}\) of \(\kappa\) and the flux of \(\mathbf{p}\) through each side \(f_{i}\) of \(\kappa\). The next lemma checks the \(\mathcal{P}_{1}(\kappa)\)-unisolvence of these degrees of freedom.

**Lemma 2.1**.: _A polynomial \(\mathbf{p}\) of \(\mathcal{P}_{1}(\kappa)\) is uniquely determined by:_

(2.5) \[\begin{cases}\mathbf{p}(a_{i}),\quad 1\leqslant i\leqslant 3\\ \qquad\int_{f_{i}}\mathbf{p}\cdot\mathbf{n}_{i}\,ds,\quad 1\leqslant i \leqslant 3.\end{cases}\]

_Moreover, on any side \(f_{i}=[a_{k},a_{l}]\) of \(\kappa,\mathbf{p}\) depends only upon the degrees of freedom defined on that side, namely: \(\mathbf{p}(a_{k})\), \(\mathbf{p}(a_{l})\) and \(\int_{f_{i}}\mathbf{p}\cdot\mathbf{n}_{i}\,ds\)._

Proof.: First, observe that (2.5) involves nine linear conditions and that \(\mathbf{p}\) has nine coefficients. Thus it suffices to prove that if all the degrees of freedom in (2.5) vanish then \(\mathbf{p}=\mathbf{0}\).

In view of Remark 2.1, we have \(I_{\kappa}\mathbf{p}=\mathbf{0}\). Likewise, \(\int_{f_{i}}\alpha_{i}\mathbf{p}_{i}\cdot\mathbf{n}_{i}\,ds=0\); i.e. \(\int_{f_{i}}\alpha_{i}\dot{\lambda}_{i}\dot{\lambda}_{k}\,ds=0\). Hence \(\alpha_{i}=0\) for \(1\leqslant i\leqslant 3\) and therefore \(\mathbf{p}=\mathbf{0}\).

Similarly, if \(\mathbf{p}(a_{k})=\mathbf{p}(a_{l})=\mathbf{0}\) and \(\int_{f_{i}}\mathbf{p}\cdot\mathbf{n}_{i}\,ds=0\) we readily find that \(\mathbf{p}|_{f_{i}}=\mathbf{0}\). 

Lemma 2.1 leads to the following interpolation operator:

for \(\mathbf{v}\in\mathcal{C}^{0}(\bar{\Omega})^{2}\), let \(r_{\kappa}\mathbf{v}\) be the unique polynomial of \(\mathcal{P}_{1}(\kappa)\) defined by:

(2.6) \[\begin{cases}r_{\kappa}\mathbf{v}(a_{i})=\mathbf{v}(a_{i})\quad 1 \leqslant i\leqslant 3,\\ \qquad\int_{f_{i}}(r_{\kappa}\mathbf{v}-\mathbf{v})\cdot\mathbf{n}_{i}\,ds=0 \quad 1\leqslant i\leqslant 3,\end{cases}\]
