Next, remark that \(\partial q_{h}/\partial\tau\) is continuous at interelements boundaries. This suggests to choose

\[\mathbf{v}(\alpha_{i})=-(\mathbf{g}_{i}\cdot\mathbf{t}_{i})\mathbf{t}_{i}=-( \mathbf{g}_{i+1}\cdot\mathbf{t}_{i})\mathbf{t}_{i}\]

where \(\mathbf{t}_{i}\) is the tangent vector to \(\kappa_{i}^{\prime}\) with length \(\|\kappa_{i}^{\prime}\|\) and (say) pointing outside \(\Omega_{r}\). With this choice we obtain

\[\int_{\Omega_{r}}\operatorname{div}\mathbf{v}_{h}q_{h}\,dx=(1/3)\sum_{i=1}^{J} \operatorname{meas}(\kappa_{i})\{(\mathbf{g}_{i}\cdot\mathbf{t}_{i})^{2}+( \mathbf{g}_{i}\cdot\mathbf{t}_{i-1})^{2}\}.\]

But according to (A.9), \(\mathbf{g}\cdot\mathbf{t}\) is preserved by affine transformations. Thus, with obvious notations we can write:

\[\int_{\Omega_{r}}\operatorname{div}\mathbf{v}_{h}q_{h}\,dx=(1/3)\sum_{i=1}^{J} \operatorname{meas}(\kappa_{i})\{(\hat{\mathbf{g}}_{i}\cdot\hat{\mathbf{t}}_ {i})^{2}+(\hat{\mathbf{g}}_{i}\cdot\hat{\mathbf{t}}_{i-1})^{2}\}.\]

Clearly, each set of vectors \(\{\hat{\mathbf{t}}_{i-1},\hat{\mathbf{t}}_{i}\}\) is a basis on the reference space. Therefore the mapping \(\mathbf{g}\to\{(\mathbf{g}\cdot\hat{\mathbf{t}}_{i-1})^{2}+(\mathbf{g}\cdot \hat{\mathbf{t}}_{i})^{2}\}^{1/2}\) is equivalent to the Euclidean norm on the reference space. Hence, in view of

\[|\hat{q}|_{1,\hat{\kappa}_{i}}^{2}=\operatorname{meas}(\hat{\kappa}_{i})\| \hat{\mathbf{g}}_{i}\|^{2},\]

there exists a constant \(\hat{C}_{1}>0\) such that:

\[\int_{\Omega_{r}}\operatorname{div}\mathbf{v}_{h}q_{h}\,dx\geqslant\hat{C}_{ 1}\sum_{i=1}^{J}\operatorname{meas}(\kappa_{i})|\hat{q}|_{1,\hat{\kappa}_{i}} ^{2}.\] (4.21)

Next, on the one hand the definition of \(\mathbf{v}_{h}\) yields:

\[\|\mathbf{v}_{h}\|_{0,\kappa_{i}}^{2} \leqslant\hat{C}_{2}\operatorname{meas}(\kappa_{i})\{\|\,\mathbf{ v}(q_{i-1})\|^{2}+\|\mathbf{v}(\alpha_{i})\|^{2}\}\] (4.22) \[\leqslant\hat{C}_{3}\operatorname{meas}(\kappa_{i})[h_{\kappa_{i }}|\hat{q}|_{1,\hat{\kappa}_{i}}]^{2}.\]

And on the other hand, the argument of Lemma A.6 gives:

\[|\mathbf{v}_{h}|_{1,\kappa_{i}}^{2} \leqslant\hat{C}_{4}\mathbb{L}[\,\|B_{i}^{-1}\|\,\|\,\|\mathbf{v}_ {h}\|_{0,\kappa_{i}}]^{2}\] (4.23) \[\leqslant\hat{C}_{5}\operatorname{meas}(\kappa_{i})[\sigma_{ \kappa_{i}}|\hat{q}|_{1,\kappa_{i}}]^{2}\]

by virtue of (A.2) and (4.22). Hence it stems from (4.21), (4.23) and the regularity of \(\mathcal{T}_{h}\) that

\[\int_{\Omega_{r}}\operatorname{div}\mathbf{v}_{h}q_{h}\,dx\geqslant\hat{C}_{ 6}(1/\sigma)|\mathbf{v}_{h}|_{1,\Omega_{r}}\left\{\sum_{i=1}^{J} \operatorname{meas}(\kappa_{i})|\hat{q}|_{1,\hat{\kappa}_{i}}^{2}\right\}^{1/2}.\] (4.24)

It remains to show that, on a regular triangulation,

\[\left\{\sum_{i=1}^{J}\operatorname{meas}(\kappa_{i})|\hat{q}|_{1,\hat{\kappa}_ {i}}^{2}\right\}^{1/2}\geqslant\hat{C}\|\,q\|_{0,\Omega_{r}}\quad\quad\forall q \in H^{1}(\Omega_{r})\cap L_{0}^{2}(\Omega_{r}).\]

The corresponding proof is a simple variant of that of Lemma 2.5. To begin with, observe that the composition with \(F_{r}\) maps \(H^{1}(\Omega_{r})\) into \(H^{1}(\hat{\Omega})\) but does not preserve the zero mean value. This small difficulty can be handled by replacing
