Numerical results confirm this theoretical analysis but it appears most often that it is the _entire pressure \(p_{h}\) that converges towards \(p\)_--not the component \(\tilde{p}_{h}\) alone--. This renders the filtering of the pressure component \(p_{h}^{4}\) seldom necessary. There are cases, though, where \(p_{h}^{4}\) does diverge; the reader can refer to Boland & Nicolaides [12] for a specific example. Besides that, the reader will find in Malkus & Olsen [55] other examples of currently used finite element spaces which do not satisfy a uniform inf-sup condition.

From a practical point of view, Problem (3.36) can be solved by the penalty method of Section 1.3 (cf. (1.52)). Numerical results can be found for example in Carey & Krishnan [16]. But it is also possible to decouple directly the velocity from the pressure by using a basis of "divergence-free" velocities, i.e. a basis of \(V_{h}\). Following Stephens _et al_[76] we introduce the vector field \(\vec{v}_{\kappa}\in X_{h}\) that takes the values \((1,-1)\), \((1,1)\), \((-1,1)\), \((-1,-1)\) at the four vertices of \(\kappa\) like in Figure 17 and \((0,0)\) at all other nodes of \(\mathcal{T}_{h}\); then we define the set

\[S=\{\vec{v}_{\kappa};\,\text{for all interior elements $\kappa$ of $\mathcal{T}_{h}$}\}.\]

By inspection, we can easily ascertain that each \(\vec{v}_{\kappa}\in S\) belongs to \(V_{h}\) and that all these functions are linearly independent. In addition, a simple dimension argument yields:

\[\operatorname{card}(S)=\dim(X_{h})-\dim(\mathcal{M}_{h})=\dim(V_{h}).\]

Hence \(S\) is a convenient basis of \(V_{h}\). The reader will find numerical results with this basis in the above reference.

## 4 Continuous Approximation of the Pressure

So far, we have used approximate pressures that were (generally) discontinuous across interelement boundaries. But from the engineering point of view, continuous pressures are more natural because the pressures encountered in practice are usually continuous functions. The fact is that numerical analysts found Stokes solvers with \(\mathcal{C}^{0}\) pressures more difficult to analyze than those with \(L^{2}\) pressures. This difficulty accounts for the relatively meager literature on the theory of important schemes of the "Hood-Taylor" type.

The first rigorous error analysis of the very popular Hood & Taylor [44] scheme is due to Bercovier & Pironneau [7]. Later on this analysis was cleverly simplified by Verfurth [83]; but now the approach of Section 1.4 permits to insert directly the Hood-Taylor method into the framework of SS1.

Apart from the Hood-Taylor and closely related schemes, this paragraph studies an interesting variant introduced by Glowinski & Pironneau [38] which approximates the Stokes problem by a sequence of discrete Dirichlet problems for \(-\Delta\).
