\[|\phi_{h}|_{1,s,\Omega}\leqslant\inf_{\chi_{h}\in\Phi_{h}}\{C(s)h^{2/s-1}|\phi(h)- \chi_{h}|_{1,\Omega}+|\chi_{h}|_{1,s,\Omega}\}.\]

But as \(s>2\), Sobolev's Theorem I.1.3 states that \(W^{1,s}(\Omega)\subset\mathcal{C}^{0}(\bar{\Omega})\) and therefore we can take \(\chi_{h}=I_{h}\phi(h)\), where \(I_{h}\) is the standard finite element interpolation operator defined by Lemma A.2. This lemma gives the estimates:

\[|I_{h}\phi(h)|_{1,s,\Omega} \leqslant C_{1}|\phi(h)|_{1,s,\Omega},\] \[|\phi(h)-I_{h}\phi(h)|_{1,\Omega} \leqslant C_{2}h|\phi(h)|_{2,\Omega}.\]

In view of (2.43) this proves (2.41).

_Remark 2.6_.: When \(s\) is not too large, it can be shown that the convexity hypothesis on \(\Omega\) is not necessary for (2.41). Notice that the alternate proof given above only uses this hypothesis to deduce that \(\phi(h)\in H^{2}(\Omega)\), but in fact it does not require so much regularity. For example, if \(s=4\) (and this is the exponent most often used for Navier-Stokes equations) it suffices that \(\phi(h)\in H^{3/2}(\Omega)\) because \(H^{3/2}(\Omega)\subset W^{1,4}(\Omega)\). But an extension of Theorem I.1.8 (cf. Grisvard [42]) proves that \(\phi(h)\) belongs to \(H^{3/2}(\Omega)\) whenever the angles of \(\Gamma\) are bounded by \(3\pi/2\) and this allows a much wider range of domains. The reader will find more details in Section IV.4.3.

**Lemma 2.6**.: _Hypothesis \(\mathrm{H2}\) is satisfied for all real \(s\geqslant 2\) when \(\Omega\) is a convex polygon and \(\mathcal{T}_{h}\) is uniformly regular._

Proof.: Let \(\mathbf{v}\in H^{1}_{0}(\Omega)^{2}\). We use the orthogonal decomposition of \(\mathbf{v}\) established by Theorem I.3.2:

\[\mathbf{v}=\mathbf{grad}\,q+\mathbf{curl}\,\phi,\]

where \(\phi\in\Phi\) and, in view of Remark I.3.2\(q\in H^{1}(\Omega)\cap L^{2}_{0}(\Omega)\) is the solution of:

\[\begin{cases}\phantom{\phantom{\phantom{\phantom{\phantom{\phantom{\phantom{ \phantom{\phantom{\phantom{\phantom{\phantomphantom{\phantomphantomphantom{{\phantomphantomphantomphantomphantomphantom }}}}}}}}}}}}}} \mathbf{ }\mathbf{\mathbf{\mathbf{\mathbf{{{{{\phantom{\phantom{ \phantom{\phantom{\phantom{\phantom{\phantom{\phantomphantomphantomphantom{\phantomphantomphantomphantomphantom{ }}}}}}}}}}}}}}}dq}q=\mathrm{div}\, \mathbf{v}\quad\mathrm{in}\,\Omega,\\ \partial q/\partial n=0\quad\mathrm{on}\,\,\Gamma.\end{cases}\]

Since \(\Omega\) is convex, Theorem I.1.10 asserts that \(q\in H^{2}(\Omega)\cap L^{2}_{0}(\Omega)\) with:

\[\|q\|_{2,\Omega}\leqslant C_{1}\|\operatorname{div}\mathbf{v}\|_{0,\Omega} \leqslant C_{1}\sqrt{2}|\mathbf{v}|_{1,\Omega}.\]

As a consequence \(\phi\in H^{2}(\Omega)\cap H^{1}_{0}(\Omega)\) and

\[\|\phi\|_{2,\Omega}\leqslant C_{2}\|\mathbf{v}\|_{1,\Omega}\leqslant C_{3}| \mathbf{v}|_{1,\Omega}.\]

By virtue of Sobolev's Theorem I.1.3, we have

\[H^{2}(\Omega)\subset W^{1+2/s,s}(\Omega).\]

Then, since the polynomials of \(Q_{h}\) are at least of degree one, (A.26) implies:

\[|q-P_{h}q|_{1,s,\Omega}\leqslant C_{4}h^{2/s}|\mathbf{v}|_{1,\Omega}.\]
