**Lemma 3.3**.: _Let \(\kappa\) be a plane, convex quadrilateral. There exists a constant \(C>0,\) independent of \(h\) and \(\kappa,\) such that_

(3.14) \[\|q\|_{0,\kappa}\leqslant C\sigma_{\kappa}h_{\kappa}|q|_{1,\kappa}\ \ \ \ \ \forall q\in H^{1}(\kappa)\cap L_{0}^{2}(\kappa).\]

We skip the proof because it is entirely similar to that of Lemma 2.5.

It remains to examine the approximation properties of \(W_{h}\) and \(Q_{h}.\) While the approximation error in \(W_{h}\) is completely standard since it stems directly from (A.49):

(3.15) \[\begin{split}|\mathbf{w}-I_{h}\mathbf{w}|_{m,\Omega}\leqslant Ch ^{k+1-m}|\mathbf{w}|_{k+1,\Omega}\ \ \ \ \ \ \forall\mathbf{w}\in H^{k+1}(\Omega)^{2},\ \ \ \ 1\leqslant k \leqslant l,\\ m=0\text{ or }1,\end{split}\]

the approximation error in \(Q_{h}\) is not so immediate because we are dealing with polynomials of \(P_{l-1}\) on quadrilaterals (instead of triangles). In particular, Theorem A.3 cannot be applied because \(\{p\circ F_{\kappa};p\in P_{l-1}\}\) is a proper subspace of \(Q_{l-1}.\) The following lemma is due to Bernardi (private communication).

**Lemma 3.4**.: _If the triangulation \(\mathcal{T}_{h}\) is regular, the operator \(\rho_{h}\) of orthogonal \(L^{2}\)-projection on \(Q_{h}\) satisfies the bound:_

(3.16) \[\|f-\rho_{h}f\|_{0,\Omega}\leqslant Ch^{k}|f|_{k,\Omega}\ \ \ \ \ \forall f\in H^{k}(\Omega)\ \ \ \text{ for }0\leqslant k\leqslant l.\]

Proof.: Let \(\kappa\) be a quadrilateral of \(\mathcal{T}_{h}.\) Notice that (3.16) would be trivial if the mapping \(F_{\kappa}\) were affine instead of bilinear. So we propose to introduce another

Figure 11:
