(A.26) \[\begin{split}&\|v-P_{h}v\|_{0,\,\rho,\,\Omega}+h|v-P_{h}v|_{1,\, \rho,\,\Omega}\leq Ch^{s+1}\|v\|_{s+1,\,\rho,\,\Omega}\\ &\forall v\in W^{s+1,\,p}(\Omega)\quad\text{(resp. $\forall v\in W^{s+1,\,p}(\Omega)\cap W^{1,\,p}_{0}(\Omega)$)}.\end{split}\]

_When \(k=1\) and \(p\in[1,2)\), the estimate (A.26) holds with the additional factor_

\[|\ln h|^{2/p-1}\]

_in the right-hand side. When \(k=1\) and \(p=\infty,\) the \(L^{\infty}\)-estimate in (A.26) becomes_

(A.27) \[\|v-P_{h}v\|_{0,\,\infty,\,\Omega}\leq C|\ln h|h^{s+1}\,\|v\|_{s+1,\,\infty,\, \Omega},\]

_while the \(W^{1,\,\infty}\)-estimate is unchanged._

The proof of Theorem A.2 relies on the fact that the Laplacian operator is an isomorphism from \(W^{1,\,p}_{0}(\Omega)\cap W^{2,\,p}(\Omega)\) onto \(L^{p}(\Omega)\) for all \(p\in(1,2+\varepsilon)\), for some \(\varepsilon>0\). According to Remark I.1.2, this isomorphism holds on a smooth domain or on a convex polygon. This accounts for the convexity hypothesis in the statement of Theorem A.2. Let us point out that the occurrence of the logarithmic factor is a well-known phenomenon in \(L^{\infty}\)-estimates. Finally, as mentioned above, (A.26) can be established directly when \(p=2\) and for all \(k\geq 1\); if \(s\) is an integer, this yields the familiar estimate for \(P_{h}\) (resp. \(\check{P}_{h}\)):

(A.28) \[\begin{split}&\|v-P_{h}v\|_{0,\,\Omega}+h|v-P_{h}v|_{1,\,\Omega} \leq Ch^{m+1}|v|_{m+1,\,\Omega}\\ &\forall v\in H^{m+1}(\Omega)\quad\text{(resp. $\forall v\in H^{m+1}(\Omega)\cap H^{1}_{0}(\Omega)$)}.\end{split}\]

_Remark A.2_.: When the function \(v\) is not continuous, neither its interpolant \(I_{h}v\) nor \(\check{I}_{h}v\) are defined. If \(\Omega\) is convex and the triangulation uniformly regular, they may be conveniently replaced by the projection \(P_{h}v\) (or \(\check{P}_{h}v\) if \(v\) vanishes on \(\Gamma\)). When \(\Omega\) is not convex or a uniformly regular triangulation is not available, other interpolants obtained by _local regularization_ may be used. They also have the advantage, over the projection, of being defined locally and not globally. The reader will find some information about this technique in Section A.3.

We shall also use subsequently a _local \(L^{2}\) projection._ To be precise, for \(v\in L^{2}(\Omega)\) and each integer \(k\geq 0\), we define:

(A.29) \[\rho_{h}v|_{\kappa}\in P_{k},\quad\ \ \int_{\kappa}(\rho_{h}v-v)f\,dx=0\quad \ \ \forall f\in P_{k},\quad\ \ \forall\kappa\in\mathcal{T}_{h}.\]

Clearly the operator \(\rho_{h}\) satisfies the hypotheses of Corollary A.2 and we have the following result valid in all dimensions \(N\).

**Lemma A.5**.: _Let \(v\in H^{s}(\Omega)\) for some real \(s\in[0,k+1]\). The \(L^{2}\) projection \(\rho_{h}\) satisfies the error estimate:_

(A.30) \[\|v-\rho_{h}v\|_{0,\,\Omega}\leq Ch^{s}|v|_{s,\,\Omega},\]

_with a constant \(C>0\) independent of \(h\) and \(v\)._

Note that this lemma requires no regularity of the triangulation.
