Before studying the trace of functions of \(W^{m,\,p}(\Omega)\), it is convenient to extend the notion of Sobolev spaces to nonintegral values of \(m\). There are several definitions of fractional Sobolev spaces which unfortunately are not equivalent. Here we shall use mostly the following one.

**Definition 1.2**.: Let \(\Omega\) be an open subset of \(\mathbb{R}^{N}\), \(m\geqslant 0\) be an integer and \(s\) and \(p\) be two real numbers with \(1\leqslant p<\infty\) and \(s=m+\sigma\) where \(\sigma\!\in\!\mathbb{R}\) with \(0<\sigma<1\). We denote by \(W^{s,\,p}(\Omega)\) the space of all distributions \(u\) defined in \(\Omega\) such that

\[u\in W^{m,\,p}(\Omega)\]

and

\[\int_{\Omega}\int_{\Omega}\frac{|\partial^{\alpha}u(x)-\partial^{ \alpha}u(y)|^{p}}{\|x-y\|^{N+\sigma p}}dx\,dy<+\infty\quad\quad\forall|\alpha| =m.\]

Likewise, we denote by \(W^{s,\,\infty}(\Omega)\) the subspace of functions \(u\) in \(W^{m,\,\infty}(\Omega)\) such that

\[\max_{|\alpha|=m}\operatorname*{ess\,sup}_{\begin{subarray}{c}x,\,y\in\, \Omega\\ x\neq y\end{subarray}}\frac{|\partial^{\alpha}u(x)-\partial^{\alpha}u(y)|^{p} }{\|x-y\|^{\sigma}}\leqslant+\infty.\]

It can be shown that \(W^{s,\,p}(\Omega)\) is a Banach space for the norm:

(1.9) \[\|u\|_{s,\,p,\,\Omega}=\left\{\|u\|_{m,\,p,\,\Omega}^{p}+\sum_{| \alpha|=m}\int_{\Omega}\int_{\Omega}\frac{|\partial^{\alpha}u(x)-\partial^{ \alpha}u(y)|^{p}}{\|x-y\|^{N+\sigma p}}\,dx\,dy\right\}^{1/p}\]

with the obvious modification when \(p=\infty\). Like in the integral case, we define for \(s>0\):

\[W^{s,\,p}_{0}(\Omega)=\overline{\mathcal{D}(\Omega)}^{\boldsymbol{w}^{s,\,p} (\Omega)}\]

and we denote by \(W^{-s,\,p^{\prime}}(\Omega)\) the dual space of \(W^{s,\,p}_{0}(\Omega)\) with \(p\) and \(p^{\prime}\) related by (1.6). It turns out that several previous results carry over to fractional Sobolev spaces with few modifications. More precisely, the statements of Sobolev's Imbedding Theorem 1.3 and that of its Corollary 1.1 are valid for fractional-order Sobolev spaces. The density part of Theorem 1.2 carries over without modification to \(s>0\), while the extension part is valid for \(s>0\) when \(\Omega\) is bounded. In addition, we have the following outstanding Interpolation Theorem of Lions & Peetre [54] which we shall use over and over.

**Theorem 1.4**.: _Let \(\Omega\) be a bounded Lipschitz-continuous open subset of \(\mathbb{R}^{N}\). Let \(\theta\!\in\![0,1]\) and let \(s_{i}\) and \(t_{i}\) be two pairs of real numbers with \(0\leqslant t_{i}\leqslant s_{i}\) for \(i=1,2\) and let \(\mathcal{L}_{i}\) and \(\mathcal{L}_{\theta}\) denote respectively \(\mathcal{L}(W^{s_{i},\,p}(\Omega);W^{t_{i},\,p}(\Omega))\) and \(\mathcal{L}(W^{(1-\theta)s_{1}+\theta s_{2},\,p}(\Omega);W^{(1-\theta)t_{1}+ \theta t_{2},\,p}(\Omega))\) for some real \(p\) with \(1<p<\infty\). Let \(\pi\) be an operator in \(\mathcal{L}_{1}\cap\mathcal{L}_{2}\); then \(\pi\) also belongs to \(\mathcal{L}_{\theta}\) and there exists a constant \(C\) such that_

(1.10) \[\|\pi\|_{\mathcal{L}_{\theta}}\leqslant C\,\|\pi\|_{\mathcal{L}_{ \theta}}^{1-\theta}\|\pi\|_{\mathcal{L}_{2}}^{\theta}.\]
