**Lemma A.4**.: _Let \(\mathcal{T}_{h}\) be a regular triangulation of \(\bar{\Omega}\). For real \(p>1,\) the interpolation operator \(\widetilde{I}_{h}\!\in\!\mathcal{L}(W^{2,\,p}(\Omega);\Theta_{h})\cap\mathcal{L} (W^{2,\,p}(\Omega)\cap W^{1,\,p}_{0}(\Omega);\Phi_{h})\) defined in each element \(\kappa\) by:_

\[\widetilde{I}_{h}v|_{\kappa}=\widetilde{I}_{\kappa}v\quad\quad\forall\kappa\! \in\!\mathcal{T}_{h},\]

_satisfies the following error estimate for all integers \(m\) and real \(s\) with \(0\leqslant m\leqslant s+1,\)\(1\leqslant s\leqslant k\):_

(A.23) \[|v-\widetilde{I}_{h}v|_{m,\,p,\,\Omega}\leqslant Ch^{s+1-m}|v|_{s+1,\,p,\, \Omega}\quad\quad\forall v\!\in\!W^{s+1,\,p}(\Omega),\]

_where the constant \(C>0\) is independent of \(h\) and \(v\)._

Apart from these two interpolants, the projection operator will play a fundamental part in the subsequent theory. To be specific, for real \(p\geqslant 1\), let

\[\check{P}_{h}\!\in\!\mathcal{L}(W^{1,\,p}_{0}(\Omega);\Phi_{h}),\quad\quad P_ {h}\!\in\!\mathcal{L}(W^{1,\,p}(\Omega);\Theta_{h})\]

be defined respectively by

(A.24) \[(\mathbf{grad}(\check{P}_{h}v-v),\mathbf{grad}\,\phi_{h}) =0\quad\quad\forall\phi_{h}\!\in\!\Phi_{h},\quad\quad\forall v\! \in\!W^{1,\,p}_{0}(\Omega);\] (A.25) \[\begin{cases}(\mathbf{grad}(P_{h}v-v),\mathbf{grad}\,\theta_{h}) =0\quad\quad\forall\theta_{h}\!\in\!\Theta_{h},\quad\quad\forall v\!\in\!W^{1, \,p}(\Omega).\\ (P_{h}v-v,1)=0.\end{cases}\]

Note that \(\check{P}_{h}v\) can also be interpreted as the finite element solution of the homogeneous Dirichlet problem:

\[-\,\mathcal{A}v=f\quad\text{in }\Omega,\quad\quad v=0\quad\text{on }\Gamma;\]

and \(P_{h}v\) as the finite element solution of the non-homogeneous Neumann problem:

\[-\,\mathcal{A}v=f\quad\text{in }\Omega,\quad\quad\partial v/\partial n=g\quad \text{on }\Gamma,\]

with the compatibility condition

\[\int_{\Omega}f\,dx=\langle g,1\rangle_{\Gamma},\]

its uniqueness proceeding from the second condition of (A.25). Now, since \(\check{P}_{h}\) and \(P_{h}\) are projections for the seminorm of \(H^{1}(\Omega)\), it is easy to prove error estimates in the \(L^{2}\) and \(H^{1}\) norms, provided \(v\!\in\!H^{1}(\Omega)\); but it is much more difficult to establish optimal \(L^{p}\) and \(W^{1,\,p}\) estimates. The following theorem is the achievement of many years of work contributed by several mathematicians; cf. for example Douglas, Dupont & Whalbin [25], Nitsche [62], Rannacher & Scott [66] and Scott [73]. Although it is by no means standard, its proof is omitted as it is far beyond the scope of this book.

**Theorem A.2**.: _Assume that \(\Omega\) is a convex polygon. Let \(\mathcal{T}_{h}\) be a uniformly regular triangulation of \(\bar{\Omega}\) and let the reals \(s\) and \(p\) be such that \(0\leqslant s\leqslant k\) and \(1\leqslant p\leqslant\infty.\) For \(k\geqslant 2\) or for \(k=1\) and \(2\leqslant p<\infty,\) there exists a constant \(C>0,\) independent of \(h,\) such that the projection \(P_{h}\) (resp. \(\check{P}_{h}\)) satisfies the error estimate:_
