The following theorem establishes the approximation properties of \(M_{h}\) when the triangulation \(\mathcal{T}_{h}\) is regular as \(h\) tends to zero (cf. Definition A.2):

\[h_{\kappa}/\rho_{\kappa}=\sigma_{\kappa}\leqslant\sigma\ \ \ \ \ \forall\kappa\!\in\! \mathcal{T}_{h},\ \ \ \ \ \sigma>0\ \ \ \text{ independent of $h$.}\]

**Theorem 5.4**.: _Let \(\mathcal{T}_{h}\) be a regular family of triangulations of \(\bar{\Omega}\) and let \(M_{h}\) and \(r_{h}\) be defined by (5.36) and (5.37) for some integer \(l\geqslant 1\). We have the upper bound for all \(\mathbf{u}\!\in\!H^{l+1}(\Omega)^{3}\):_

(5.38) \[\|\mathbf{u}-r_{h}\mathbf{u}\|_{H(\mathbf{curl};\,\Omega)}\leqslant C_{1}h^{l }\{|\mathbf{u}|_{l,\Omega}+|\mathbf{u}|_{l+1,\,\Omega}\}.\]

_Moreover, the operator \(r_{h}\) satisfies the following stability estimate:_

(5.39) \[\|\mathbf{u}-r_{h}\mathbf{u}\|_{0,\Omega}+h\|\mathbf{curl}(\mathbf{u}-r_{h} \mathbf{u})\|_{0,\Omega}\leqslant C_{2}h|\mathbf{u}|_{1,\,s,\Omega}\]

_for all \(\mathbf{u}\!\in\!W^{1,s}(\Omega)^{3}\) with \(s>2\), where the positive constants \(C_{1}\) and \(C_{2}\) are independent of \(h\) and \(\mathbf{u}\)._

Proof.: Let us first prove (5.38). By virtue of (5.26) we have:

\[\|\mathbf{u}-r_{h}\mathbf{u}\|_{0,\kappa}\leqslant|\mathrm{det}(B_{\kappa})|^ {1/2}\,\|\,B_{\kappa}^{-1}\|\,\|\,\|\hat{\mathbf{u}}-r_{\hat{\kappa}}\hat{ \mathbf{u}}\|_{0,\hat{\kappa}}.\]

But since the operator \(r_{\hat{\kappa}}\) preserves the polynomials of \(P_{l-1}^{3}\), Corollary A.1 implies that:

\[\|\hat{\mathbf{u}}-r_{\hat{\kappa}}\hat{\mathbf{u}}\|_{0,\hat{\kappa}} \leqslant C_{1}\begin{cases}|\hat{\mathbf{u}}|_{l,\hat{\kappa}}\ \ \ \text{if}\ l \geqslant 2,\\ |\hat{\mathbf{u}}|_{1,\hat{\kappa}}+|\hat{\mathbf{u}}|_{2,\hat{\kappa}}\ \ \ \text{if}\ l=1.\end{cases}\]

Next, combining formulas (A.7) and (5.26) we derive:

(5.40) \[|\hat{\mathbf{u}}|_{k,\hat{\kappa}}\leqslant C_{2}\,\|\,B_{\kappa}\|^{k+1}| \mathrm{det}(B_{\kappa})|^{-1/2}|\mathbf{u}|_{k,\kappa}.\]

Therefore, these three inequalities yield:

(5.41) \[\begin{cases}\|\mathbf{u}-r_{h}\mathbf{u}\|_{0,\kappa}\leqslant C_{3}\,\|\,B _{\kappa}^{-1}\|\,\|\,B_{\kappa}\|^{l+1}|\mathbf{u}|_{l,\kappa}\ \ \ \text{when}\ l \geqslant 2,\\ \|\mathbf{u}-r_{h}\mathbf{u}\|_{0,\kappa}\leqslant C_{3}\,\|\,B_{\kappa}^{-1 }\|\,\|\,B_{\kappa}\|^{2}(|\mathbf{u}|_{1,\kappa}+\|B_{\kappa}\|\,|\mathbf{u} |_{2,\kappa})\ \ \ \text{when}\ l=1.\end{cases}\]

Next, let us examine \(\mathbf{curl}(\mathbf{u}-r_{h}\mathbf{u})\). According to (5.30), we have:

\[\|\mathbf{curl}(\mathbf{u}-r_{h}\mathbf{u})\|_{0,\kappa}\leqslant C_{4}| \mathrm{det}(B_{\kappa})|^{1/2}\,\|B_{\kappa}^{-1}\|^{2}\,\|\,\mathbf{curl}( \hat{\mathbf{u}}-r_{\kappa}\hat{\mathbf{u}})\|_{0,\hat{\kappa}}.\]

As mentioned in Remark 5.6, the linear mapping \(\hat{\mathbf{u}}\!\to\!\mathbf{curl}(\hat{\mathbf{u}}-r_{\hat{\kappa}}\hat{ \mathbf{u}})\) vanishes on the space \(P_{l}^{3}\). Therefore, a simple application of Theorem A.1 yields:

\[\|\mathbf{curl}(\hat{\mathbf{u}}-r_{\hat{\kappa}}\hat{\mathbf{u}})\|_{0,\hat{ \kappa}}\leqslant C_{5}|\hat{\mathbf{u}}|_{l+1,\hat{\kappa}}.\]

Hence

(5.42) \[\|\mathbf{curl}(\mathbf{u}-r_{h}\mathbf{u})\|_{0,\kappa}\leqslant C_{6}\,\|\,B _{\kappa}^{-1}\|^{2}\,\|\,B_{\kappa}\|^{l+2}|\mathbf{u}|_{l+1,\kappa}.\]

Finally (5.38) stems from (5.41) and (5.42) together with (A.2) and the regularity of \(\mathcal{T}_{h}\).

The proof of the stability estimate (5.39) is a trifle more intricate. Taking into account the facts that \(r_{\hat{\kappa}}\) preserves the constant polynomials and belongs to
