Now, we suppose that \(\Omega\) is a _bounded polyhedron_ and we take a family \(\mathcal{T}_{h}\) of triangulations of \(\bar{\Omega}\). For each integer \(l\geqslant 1\), we define:

\[\begin{cases}D_{h}=\{\mathbf{u}_{h}\!\in\!H(\operatorname{div};\Omega);\,\mathbf{ u}_{h}|_{\kappa}\!\in\!D_{l}&\forall\kappa\!\in\!\mathcal{T}_{h}\},\\ \qquad\qquad D_{0h}=D_{h}\cap H_{0}(\operatorname{div};\Omega),\\ \qquad\qquad Q_{h}=\{p_{h}\!\in\!L_{0}^{2}(\Omega);\,p_{h}|_{\kappa}\!\in\!P_{l -1}&\forall\kappa\!\in\!\mathcal{T}_{h}\},\end{cases}\] (5.53)

together with the interpolation operator \(\omega_{h}\):

\[\omega_{h}\mathbf{u}|_{\kappa}=\omega_{h}\mathbf{u}\quad\text{on }\kappa \quad\quad\forall\kappa\!\in\!\mathcal{T}_{h},\]

and for all \(\mathbf{u}\!\in\!H^{1}(\Omega)^{3}\). Clearly, \(\operatorname{div}\mathbf{u}_{h}\) belongs to \(Q_{h}\) for all \(\mathbf{u}_{h}\) in \(D_{0h}\) and \(\operatorname{\mathbf{curl}}\mathbf{u}_{h}\) belongs to \(D_{0h}\) for all \(\mathbf{u}_{h}\) in \(\Phi_{h}\). Furthermore, we have the analogue of Lemma 5.9:

\[\mathbf{u}\!\in\!H^{1}(\Omega)^{3}\quad\text{implies}\quad\omega_{h}\mathbf{u }\!\in\!D_{h},\]

\[\mathbf{u}\!\in\!H^{1}(\Omega)^{3}\quad\text{with }\mathbf{u}\!\cdot\! \mathbf{n}=0\quad\text{implies}\quad\omega_{h}\mathbf{u}\!\in\!D_{0h}.\]

The following proposition states the approximation properties of \(D_{h}\).

**Proposition 5.3**.: _Let \(\mathcal{T}_{h}\) be a regular family of triangulations of \(\bar{\Omega}\) and let \(D_{h}\) be defined by (5.53) for an integer \(l\geqslant 1\). We have the estimates:_

\[\begin{cases}\qquad\|\mathbf{u}-\omega_{h}\mathbf{u}\|_{0,\Omega}\leqslant C_ {1}h^{l}|\mathbf{u}|_{l,\Omega}&\forall\mathbf{u}\!\in\!H^{l}(\Omega)^{3},\\ \qquad\|\operatorname{div}(\mathbf{u}-\omega_{h}\mathbf{u})\|_{0,\Omega} \leqslant C_{2}h^{l}|\mathbf{u}|_{l+1,\Omega}&\forall\mathbf{u}\!\in\!H^{l+1} (\Omega)^{3}.\end{cases}\] (5.54)

The next lemma establishes the desired relationship between the spaces \(D_{h}\) and \(M_{h}\).

**Lemma 5.11**.: _Let \(\Omega\) be an open, bounded polyhedron in \(\mathbb{R}^{3}\) and let \(\Gamma_{i},\,0\leqslant i\leqslant p,\) denote the connected components of its boundary. A function \(\mathbf{u}_{h}\) of \(D_{h}\) (resp. \(D_{0h}\)) satisfies:_

\[\operatorname{div}\mathbf{u}_{h}=0\quad\text{in }\Omega,\quad\quad\int_{ \Gamma_{i}}\mathbf{u}_{h}\cdot\mathbf{n}\,ds=0\quad\text{for }0\leqslant i\leqslant p\]

_iff there exists a function \(\phi_{h}\) in \(M_{h}\) (resp. \(\Phi_{h}\)) such that:_

\[\mathbf{u}_{h}=\operatorname{\mathbf{curl}}\phi_{h}.\]

Proof.: We already know that \(\operatorname{\mathbf{curl}}\phi_{h}\) belongs to \(D_{h}\)(resp. \(D_{0h}\)) whenever \(\phi_{h}\) belongs to \(M_{h}\)(resp. \(\Phi_{h}\)).

Conversely, Theorem I.3.4 asserts that there exists \(\phi\!\in\!H^{1}(\Omega)^{3}\) such that

\[\mathbf{u}_{h}=\operatorname{\mathbf{curl}}\phi.\]

Furthermore, the fact that \(\mathbf{u}_{h}\) belongs to \(H^{\alpha}(\Omega)^{3}\) for all \(\alpha\) with \(0<\alpha<1/2\) implies that \(\phi\) belongs to \(H^{1+\alpha}(\Omega)^{3}\)(cf. Remark I.3.12). Thus, the interpolate of \(\phi,\,r_{h}\phi,\) is well defined. Let us prove that:
