(2.29) \[\left\{\begin{aligned} v(\mathbf{curl}\,\omega_{h},\mathbf{ curl}\,\phi_{h})&=(\mathbf{f},\mathbf{curl}\,\phi_{h})& \quad\forall\phi_{h}\!\in\!\varTheta_{h},\\ (\mathbf{curl}\,\psi_{h},\mathbf{curl}\,\mu_{h})&=( \omega_{h},\mu_{h})&\quad\forall\mu_{h}\!\in\!\varTheta_{h}.\end{aligned}\right.\]

Problem (2.29) is the formulation that is used as a basis for practical computation. Like in the continuous case, it enjoys the following attractive features:

\(1^{\circ})\) Problem (2.29) is formulated in terms of stream functions (i.e. exactly divergence-free velocities) with \(H^{1}\)-regularity;

\(2^{\circ})\) it consists of two Dirichlet problems for the Laplace operator;

\(3^{\circ})\) the computation of the stream function and vorticity is independent of any future computation of the pressure.

Here again, the two problems in (2.29) are coupled. They can either be solved together or dissociated by a technique very similar to that discussed in Chapter II, Sections 4.3 and 4.4 (cf. Glowinski & Pironneau [39]).

In view of Theorem 1.2, the hypotheses (2.28) and H1 imply the error estimates (1.22) and (1.23) with constants that do not depend on \(h\). Moreover, if \(M_{h}=\varTheta_{h}\), the bound (1.23) can be slightly improved by introducing the projection operator \(P_{h}\) from \(W^{1,r}(\varOmega)\) onto \(\varTheta_{h}\) defined by (A.25):

(A.25) \[\left\{\begin{aligned} (\mathbf{grad}\,(P_{h}\mu-\mu), \mathbf{grad}\,\theta_{h})&=0&\quad\forall\theta_{h }\!\in\!\varTheta_{h},\\ (P_{h}\mu-\mu,1)&=0.\end{aligned}\right.\]

Then the resulting estimates are given by the following theorem.

**Theorem 2.6**.: _Let \(u=(\mathbf{curl}\,\psi,\omega=-\,\varDelta\psi)\) and \(u_{h}=(\mathbf{curl}\,\psi_{h},\omega_{h})\) be the respective solutions of Problems (2.20) and (2.29). Under the assumptions of Theorem 2.3 and Lemma 2.4, we have the error bounds:_

(2.30) \[\|u-u_{h}\|_{\tilde{X}} \leqslant C_{1}\left\{\inf_{v_{h}\in V_{h}}\|u-v_{h}\|_{\tilde{X}} +\|\,\omega-P_{h}\omega\|_{0,\varOmega}\right\}\!,\] \[\|u-u_{h}\|_{\tilde{X}} \leqslant C_{2}\bigg{[}(1+K_{r}(h))\bigg{\{}\inf_{\phi_{h}\in \varTheta_{h}}|\psi-\phi_{h}|_{1,\,s,\varOmega}\] \[\quad+\inf_{\theta_{h}\in\varTheta_{h}}\|\,\omega-\theta_{h}\|_{ 0,\varOmega}\bigg{\}}+\|\,\omega-P_{h}\omega\|_{0,\varOmega}\bigg{]}\!,\]

_where \(P_{h}\) is defined by (A.25) and for \(r\leqslant 2\), \(K_{r}(h)\) is given here by:_

\[K_{r}(h)=\sup_{\theta_{h}\in\varTheta_{h}}(\|\,\theta_{h}\|_{1,\,r,\varOmega} /\|\,\theta_{h}\|_{0,\varOmega}).\]

Proof.: Let us establish (2.30). From (2.20) and (2.29) we infer that:

\[(\mathbf{curl}(\mu_{h}-\omega_{h}),\mathbf{curl}\,\phi_{h})=(\mathbf{curl}(\mu _{h}-\omega),\mathbf{curl}\,\phi_{h})\quad\quad\forall\phi_{h}\!\in\!\varTheta _{h},\quad\quad\forall\mu_{h}\!\in\!\varTheta_{h}.\]

In particular, by choosing \(\mu_{h}=P_{h}\omega\) we obtain:

(2.32) \[(\mathbf{curl}(P_{h}\omega-\omega_{h}),\mathbf{curl}\,\phi_{h})=0\quad\quad \forall\phi_{h}\!\in\!\varTheta_{h}.\]
