Hence applying Theorems 3.3 and III.4.2 and Corollary III.4.2 we obtain the following error bound for \(u-u_{h}\) with \(u\) (resp. \(u_{h}\)) satisfying (4.48) (resp. (4.49)):

\[\|u(\lambda)-u_{h}(\lambda)\|_{X}\leqslant Ch^{k}\]

provided \(\psi(\lambda)\in H^{k+2}(\Omega)\) for some \(k\in[1,l]\).

Finally if \(\psi(\lambda)\in H^{l+1}(\Omega)\) when \(l\geqslant 2\) or \(\psi(\lambda)\in H^{3}(\Omega)\) when \(l=1\), a duality argument similar to that of Theorem 4.5 yields the optimal estimate:

\[|\psi(\lambda)-\psi_{h}(\lambda)|_{1,\Omega}\leqslant Ch^{l}.\]

By applying the material of Section III.4.4, we can derive error bounds of the same order for the pressure.

The proofs are left as exercises.

## 5 Numerical Analysis of Upwind Schemes

When the viscosity \(v\) is small, or equivalently when the Reynolds number \(Re\) is large compared to the other parameters of the fluid, there arises a boundary layer in the neighborhood of \(\Gamma\) where the viscosity predominates while it is negligible in the interior of \(\Omega\). At the same time, the flow becomes turbulent. Thus the solutions of the Navier-Stokes equations are seriously discontinuous at high Reynolds number.

It is not our purpose here to modelize turbulent flows, but all the same, it is worthwhile to examine one possible discretization of discontinuous solutions of the Navier-Stokes equations. Instead of the centered schemes studied so far, we propose upwind schemes which are better adapted to describe discontinuous flows. The forthcoming analysis shows that these schemes are nearly optimal.

The reader can also refer to Johnson & Saranen [47] for an alternate method, the streamline diffusion method, that applies to Euler and Navier-Stokes equations.

### Upwinding in the Stream Function-Vorticity Scheme

The upwind scheme discussed in this section was developed by Fortin [31], inspired by a numerical method advocated in Lesaint & Raviart [51] to solve a neutron transport equation. It stems from the following heuristic remarks. When a smooth vector field \(\mathbf{u}\) is divergence-free, the convection term satisfies (with the usual summation convention that a repeated index represents a sum):

\[u_{j}(\partial u_{i}/\partial x_{j})=\partial(u_{j}u_{i})/\partial x_{j}.\]

Now, suppose \(\Omega\) is the union of two bounded regions \(\Omega_{1}\) and \(\Omega_{2}\) separated by an interface \(S\) like in Figure 21. Denote by \(\Gamma\) the boundary of \(\Omega\) and by \(\mathbf{n}_{i}\) the
