As \(\operatorname{div}\mathbf{u}=0\) we obtain first:

\[v\langle\operatorname{\mathbf{curl}}\operatorname{\mathbf{curl}}\mathbf{u}, \operatorname{\mathbf{curl}}\mathbf{\phi}\rangle=(\mathbf{f},\operatorname{ \mathbf{curl}}\mathbf{\phi})\quad\quad\forall\mathbf{\phi}\in H_{0}(\operatorname{ \mathbf{curl}};\Omega),\]

where \(\langle.,.\rangle\) denotes the duality between \(H_{0}(\operatorname{\mathbf{curl}};\Omega)\) and its dual space. Now, let us set

(5.3) \[\mathbf{\omega}=\operatorname{\mathbf{curl}}\mathbf{u}\]

and _assume that_\(\mathbf{\omega}\in H(\operatorname{\mathbf{curl}};\Omega)\); then we have

\[v(\operatorname{\mathbf{curl}}\mathbf{\omega},\operatorname{\mathbf{curl}} \mathbf{\phi})=(\mathbf{f},\operatorname{\mathbf{curl}}\mathbf{\phi})\quad \quad\forall\mathbf{\phi}\in H_{0}(\operatorname{\mathbf{curl}};\Omega).\]

Finally, since

\[\mathbf{u}=\operatorname{\mathbf{curl}}\mathbf{\psi}\quad\text{with}\quad \operatorname{div}\mathbf{\psi}=0\quad\text{and}\quad\mathbf{\psi}\in \mathbf{\Psi},\]

equation (5.3) can be written equivalently as:

\[(\operatorname{\mathbf{curl}}\operatorname{\mathbf{curl}}\mathbf{\psi}, \mathbf{\mu})=(\mathbf{\omega},\mathbf{\mu})\quad\quad\forall\mathbf{\mu}\in L ^{2}(\Omega)^{3}.\]

And by restricting \(\mathbf{\mu}\) to \(H(\operatorname{\mathbf{curl}};\Omega)\) this becomes:

\[(\operatorname{\mathbf{curl}}\mathbf{\psi},\operatorname{\mathbf{curl}} \mathbf{\mu})=(\mathbf{\omega},\mathbf{\mu})\quad\quad\forall\mathbf{\mu}\in H (\operatorname{\mathbf{curl}};\Omega).\]

Hence, summing up we see that the following _Problem_ (\(\tilde{\mathbb{Q}}\)):

\[Find\text{ a pair }(\mathbf{\psi},\mathbf{\omega})\in H_{0}( \operatorname{\mathbf{curl}};\Omega)\times H(\operatorname{\mathbf{curl}}; \Omega)\text{ such that}:\] (5.4) \[v(\operatorname{\mathbf{curl}}\mathbf{\omega},\operatorname{ \mathbf{curl}}\mathbf{\phi})=(\mathbf{f},\operatorname{\mathbf{curl}} \mathbf{\phi})\quad\quad\forall\mathbf{\phi}\in H_{0}(\operatorname{\mathbf{ curl}};\Omega),\] (5.5) \[(\operatorname{\mathbf{curl}}\mathbf{\psi},\operatorname{\mathbf{ curl}}\mathbf{\mu})=(\mathbf{\omega},\mathbf{\mu})\quad\quad\forall\mathbf{\mu}\in H (\operatorname{\mathbf{curl}};\Omega),\] (5.6) \[\operatorname{div}\mathbf{\psi}=0,\]

has at least one solution \((\mathbf{\psi},\mathbf{\omega}=-\Delta\mathbf{\psi})\) where \(\mathbf{u}=\operatorname{\mathbf{curl}}\mathbf{\psi}\) and \(\mathbf{\psi}\in\mathbf{\Psi}\). Conversely, it is easy to check that this problem has at most one solution. Indeed, if

\[(\operatorname{\mathbf{curl}}\mathbf{\omega},\operatorname{\mathbf{curl}} \mathbf{\phi})=0\quad\quad\forall\mathbf{\phi}\in H_{0}(\operatorname{ \mathbf{curl}};\Omega),\]

then choosing \(\mathbf{\phi}=\mathbf{\psi}\) and \(\mathbf{\mu}=\mathbf{\omega}\) in (5.5) we obtain successively \(\mathbf{\omega}=\mathbf{0}\) and \(\operatorname{\mathbf{curl}}\mathbf{\psi}=\mathbf{0}\). Since \(\operatorname{div}\mathbf{\psi}=0\) and \(\Gamma\) has only one connected component this implies that \(\mathbf{\psi}=\mathbf{0}\) (cf. Remark I.3.9). Therefore, we have proved the following result:

**Theorem 5.1**.: _Assume that the solution \(\mathbf{u}\) of Problem (5.1) satisfies_

\[\operatorname{\mathbf{curl}}\mathbf{u}\in H(\operatorname{\mathbf{curl}}; \Omega).\]

_Then Problem (5.4) (5.5) (5.6) has the unique solution:_

\[(\mathbf{\psi},-\Delta\mathbf{\psi})\quad\text{where }\operatorname{\mathbf{ curl}}\mathbf{\psi}=\mathbf{u}.\]

Now we want to insert Problem (\(\tilde{\mathbb{Q}}\)) into the framework of Section 1.1. We set

\[\Phi_{0}=\{\phi\in H_{0}(\operatorname{\mathbf{curl}};\Omega);\,\operatorname{ div}\mathbf{\phi}=0\}.\]

Clearly, Problem (\(\tilde{\mathbb{Q}}\)) is equivalent to:
