In view of (2.16), this will prove the corollary. To this end, consider the problem:

_Find \(\phi\) in \(H^{1}(\Omega)\) such that_

\[-\,\mathcal{A}\phi\,+\,\phi =0\quad\text{in }\Omega,\] \[\partial\phi/\partial n =\mu\quad\text{on }\Gamma.\]

Unlike the Neumann's problem of Section 1.4, this problem has exactly one solution \(\phi\) in \(H^{1}(\Omega)\). We set \(\mathbf{v}=\mathbf{grad}\,\phi\). Then \(\mathbf{v}\,\in H(\operatorname{div};\Omega)\) and \(\mathbf{v}\,\cdot\,\mathbf{n}=\mu\). Moreover

\[\|\,\phi\,\|_{1,\,\Omega}^{2}=\langle\,\mu,\phi\,\rangle_{\Gamma}\leqslant\| \,\mu\|_{-1/2,\,\Gamma}\|\,\phi\,\|_{1,\,\Omega}.\]

As \(\operatorname{div}\mathbf{v}=\phi\), it follows that

\[\|\,\mathbf{v}\,\|_{H(\operatorname{div};\Omega)}\leqslant\|\,\mu\|_{-1/2, \,\Gamma}=\|\,\mathbf{v}\,\cdot\,\mathbf{n}\,\|_{-1/2,\,\Gamma}.\qed\]

**Theorem 2.6**.: _We have:_

\[H_{0}(\operatorname{div};\Omega)=\operatorname{Ker}(\gamma_{n})=\{\mathbf{u} \,\in H(\operatorname{div};\Omega);\,\mathbf{u}\,\cdot\,\mathbf{n}|_{\,\Gamma }=0\}.\]

Proof.: Let us establish that \(\mathcal{D}(\Omega)^{N}\) is dense in \(\operatorname{Ker}(\gamma_{n})\). Again, the proof makes use of property (2.14). Let \(l\,\in(\operatorname{Ker}(\gamma_{n}))^{\prime}\) and let \(\mathbf{l}\) be the element of \(\operatorname{Ker}(\gamma_{n})\) associated with \(l\) by:

(2.19) \[\langle l,\mathbf{u}\rangle=\sum_{i=1}^{N}\,(l_{i},u_{i})+(l_{N+1}, \operatorname{div}\mathbf{u})\quad\quad\forall\mathbf{u}\,\in\operatorname{ Ker}(\gamma_{n}).\]

Now, suppose that \(l\) vanishes on \(\mathcal{D}(\Omega)^{N}\). This implies that

\[\mathbf{l}=\mathbf{grad}\,l_{N+1}.\]

Hence \(l_{N+1}\in H^{1}(\Omega)\) and we can apply Green's formula (2.17) to (2.19):

\[\langle l,\mathbf{u}\rangle=\langle\,\mathbf{u}\,\cdot\,\mathbf{n},l_{N+1} \,\rangle_{\Gamma}\quad\quad\forall\mathbf{u}\,\in\operatorname{Ker}(\gamma_ {n}).\]

Therefore \(l\) also vanishes on \(\operatorname{Ker}(\gamma_{n})\). Consequently \(\operatorname{Ker}(\gamma_{n})\subset H_{0}(\operatorname{div};\Omega)\).

The inclusion \(H_{0}(\operatorname{div};\Omega)\subset\operatorname{Ker}(\gamma_{n})\) is an immediate consequence of Green's formula (2.17). 

We end this section by examining the subspace of divergence-free functions of \(H_{0}(\operatorname{div};\Omega)\):

\[H=\{\mathbf{u}\,\in H_{0}(\operatorname{div};\Omega);\,\operatorname{div} \mathbf{u}=0\}.\]

Because it is a closed subspace of \(L^{2}(\Omega)^{N}\), we have the decomposition:

\[L^{2}(\Omega)^{N}=H\oplus H^{\perp}\]

where \(H^{\perp}\) denotes the orthogonal of \(H\) in \(L^{2}(\Omega)^{N}\) for the scalar product \((.,.)\). The following theorem characterizes \(H^{\perp}\).
