\[|{\bf v}|_{1,\Omega}\leqslant C_{1}\,\|\,{\rm div}\,{\bf w}\|_{0,\Omega}.\]

Clearly,

\[{\bf u}={\bf w}-{\bf v}\]

is the required function. It remains to check the bound (2.12). First, observe that

\[\|\,{\bf u}\|_{1,\Omega}\leqslant C_{2}\,\|\,{\bf w}\|_{1,\Omega}\]

with a constant \(C_{2}>0\) independent of \({\bf u}\) and \({\bf w}\). Then we derive (2.12) with the same constant \(C_{2}\) by taking the infimum on both sides of this inequality and using the norm (1.16) on \(H^{1/2}(\Gamma)\). 

The following theorem which sharpens the statement of Lemma 2.1 is a fundamental tool in the theory of Stokes equations. It is a simplified version of De Rham's Theorem (2.0) but it is sufficient for our purpose.

**Theorem 2.3**.: _If \({\bf f}\!\in\!H^{-1}(\Omega)^{N}\) satisfies:_

(2.13) \[\langle{\bf f},\phi\rangle=0\ \ \ \ \ \ \forall\phi\!\in\!{\cal N},\]

_then there exists \(p\!\in\!L^{2}(\Omega)\) such that:_

\[{\bf f}={\bf grad}\,p.\]

_If \(\Omega\) is connected, \(p\) is unique up to an additive constant._

Proof.: Assume for the moment that \(\Omega\) is connected. Let us show that \({\bf f}={\bf grad}\,p\) for \(p\) in \(L^{2}_{\rm loc}(\Omega)\); then Corollary 2.2 will give immediately that \(p\) is in \(L^{2}(\Omega)\).

As \(\Omega\) is a bounded and connected Lipschitz-continuous open set, there exists an _increasing_ sequence\((\Omega_{m})_{m\geqslant 1}\) of connected Lipschitz-continuous open sets such that

\[\overline{\Omega}_{m}=\Omega\ \ \ \ {\rm and}\ \ \ \Omega=\bigcup_{m\geqslant 1} \Omega_{m}.\]

Let \({\bf u}_{m}\!\in\!H^{1}_{0}(\Omega)^{N}\) with

\[{\bf u}_{m}={\bf 0}\ \ \ {\rm outside}\ \Omega_{m}\ \ \ {\rm and}\ \ \ {\rm div}\,{\bf u}_{m}=0.\]

In order to apply Lemma 2.1, we want to regularize \({\bf u}_{m}\) in such a way that it stays divergence-free. This is achieved by the classical process of _mollifiers_ (cf. for example Adams [1]):

for \(\varepsilon>0\) let \(\rho_{\varepsilon}\) be a regularizing sequence of \({\cal D}(\mathbb{R}^{N})\) that vanishes for \(\|\,x\|>\varepsilon\) and that satisfies:

\[\rho_{\varepsilon}(x)\geqslant 0,\ \ \ \ \ \ \int_{\mathbb{R}^{N}}\rho_{ \varepsilon}(x)\,dx=1,\ \ \ \ \lim_{\varepsilon\to 0}\rho_{\varepsilon}=\delta\ \ \ \ {\rm in}\ {\cal D}^{\prime}(\mathbb{R}^{N}).\]
