the polynomial space defined by (II.2.2):

\[\mathcal{P}_{1}(\kappa)=P_{1}^{2}\oplus\operatorname{span}\{\mathbf{n}_{i}\lambda _{j}\lambda_{k};\,1\leqslant i,j,\,k\leqslant 3,\,i\neq j\neq k\}.\]

Then, if the triangulation \(\mathcal{T}_{h}\) is regular the finite element scheme (4.2) with the spaces:

\[W_{h} =\{\mathbf{w}\in\mathcal{C}^{0}(\bar{\Omega})^{2};\,\mathbf{w}|_{ \kappa}\in\mathcal{P}_{1}(\kappa)\quad\forall\kappa\in\mathcal{T}_{h}\},\] \[Q_{h} =\{q\in L^{2}(\Omega);\,q|_{\kappa}\in P_{0}\quad\forall\kappa\in \mathcal{T}_{h}\}\]

has a unique branch of solutions \(\{(\lambda,(\mathbf{u}_{h}(\lambda),\lambda p_{h}(\lambda)));\lambda\in\Lambda\}\) that satisfies the error bound:

\[|\mathbf{u}_{h}(\lambda)-\mathbf{u}(\lambda)|_{1,\,\Omega}+\left\|p_{h}( \lambda)-p(\lambda)\right\|_{0,\,\Omega}\leqslant Ch(|\mathbf{u}(\lambda)|_{ 2,\,\Omega}+\left|p(\lambda)\right|_{1,\,\Omega})\quad\quad\forall\lambda\in \Lambda.\]

In addition, when \(\Omega\) is convex we have the \(L^{2}\)-estimate:

\[\left\|\mathbf{u}_{h}(\lambda)-\mathbf{u}(\lambda)\right\|_{0,\,\Omega} \leqslant Ch^{2}(|\mathbf{u}(\lambda)|_{2,\,\Omega}+\left|p(\lambda)\right|_{ 1,\,\Omega})\quad\quad\forall\lambda\in\Lambda.\]

Another interesting example is the scheme derived from the controversial \(Q_{1}-P_{0}\) element discussed in Sections II.3.3 and II.3.4 in the case of the square \((-1,1)\times(-1,1)\). Assume that \(\mathcal{T}_{h}\) is a square grid with mesh-size \(h=1/(4n)\) so that the conclusion of Theorem II.3.4 be valid. Then take

\[W_{0h}=\widetilde{\mathcal{V}}_{h}\quad\text{and}\quad M_{h}=\widetilde{M}_{h}\]

with \(\widetilde{\mathcal{V}}_{h}\) and \(\widetilde{M}_{h}\) defined respectively by (II.3.33) and (II.3.32). It is established in Sections II.3.3 and II.3.4 that this choice of spaces satisfies the three hypotheses H1, H2 and H3 (cf. (II.3.39), (II.3.40) and Theorem II.3.4). Therefore Theorems 4.1 and II.3.5 imply that, under the condition (4.14), the finite element scheme (4.2) has a unique branch of solutions

\[\{(\lambda,(\mathbf{u}_{h}(\lambda),\lambda\tilde{p}_{h}(\lambda)));\,\lambda \in\Lambda\}\]

and

\[|\mathbf{u}_{h}(\lambda)-\mathbf{u}(\lambda)|_{1,\,\Omega}+\left\|\tilde{p}_{ h}(\lambda)-p(\lambda)\right\|_{0,\,\Omega}\leqslant Ch\{|\mathbf{u}(\lambda)|_{ 2,\,\Omega}+\left|p(\lambda)\right|_{1,\,\Omega}\}.\]

Likewise, we derive immediately from Theorem 4.2 and Corollary II.3.2 that:

\[\left\|\mathbf{u}_{h}(\lambda)-\mathbf{u}(\lambda)\right\|_{0,\,\Omega} \leqslant Ch^{2}\{|\mathbf{u}(\lambda)|_{2,\,\Omega}+\left|p(\lambda)\right|_{ 1,\,\Omega}\}.\]

_Remark 4.1_.: To solve the scheme (4.2) with the \(Q_{1}-P_{0}\) element, it is convenient (like in the linear case) to use the basis of \(V_{h}\) described at the end of Section II.3.4.

### Formulation in Primitive Variables: the Case of Continuous Pressures

Going back to Chapter II, we can plainly see that the previous analysis applies readily to the "mini" element discussed in Section II.4.1 as well as the "Hood-Taylor" elements of Section II.4.2. Indeed, all these elements satisfy the hypotheses
