where \(I_{h}\!\in\!{\cal L}([H^{2}(\Omega)\cap H^{1}_{0}(\Omega)]^{2}\); \(X_{h})\) is the standard interpolator at the vertices of each subtriangle \(\tilde{\kappa}\) of \({\cal T}_{h}\).

The proof of the inf-sup condition is almost exactly like above. We take the _same_ partition (4.17) and observe that the space \(X_{h}(\Omega_{r})\) with \(X_{h}\) defined by (4.30) involves exactly the _same degrees of freedom_ as if the space \(X_{h}\) were defined by (4.15). Just the degree of the polynomials varies and this affects only the factor \(1/3\) in the quadrature formula (4.20) and the reference constants \(\hat{C}\) in subsequent formulas. Hence the _statement of Theorem 4.2 carries over here without modification._

To switch from the local inf-sup condition to the global inf-sup condition, we choose the same space \(\overline{M}_{h}\) but we take

\[\overline{X}_{h}=X_{h}.\]

It is easy to prove that the pair of spaces \((X_{h},\overline{M}_{h})\) satisfies a uniform inf-sup condition. This is in fact part of a more general result.

**Lemma 4.2**.: _If the triangulation \({\cal T}_{h}\) is regular, the spaces \(X_{h}\) and_

\[\{q\!\in\!L^{2}_{0}(\Omega);\,q\mbox{ is constant on }\kappa\quad\forall \kappa\!\in\!{\cal T}_{h}\}\]

_satisfy a uniform inf-sup condition._

We skip the proof since it is included in the argument of Lemma 3.8: it suffices to adapt the definition of the restriction operator \(\pi\) to the present case.

Summarizing, we have the analogue of Theorem 4.3.

**Theorem 4.4**.: _Let \(\Omega\) and \({\cal T}_{h}\) satisfy the hypotheses of Theorem 4.3 and suppose the solution \(({\bf u},p)\) of (4.1) belongs to \(H^{2}(\Omega)^{2}\times[H^{1}(\Omega)\cap L^{2}_{0}(\Omega)]\). Then the solution \(({\bf u}_{h},p_{h})\) of Problem (4.5) with \(X_{h}\) and \(M_{h}\) defined by (4.30) (4.4) has the error bound:_

(4.32) \[|{\bf u}-{\bf u}_{h}|_{1,\,\Omega}+\|\,p-p_{h}\|_{0,\,\Omega}\leqslant C_{1}h \{|{\bf u}|_{2,\,\Omega}+|p|_{1,\,\Omega}\}.\]

_Moreover, when \(\Omega\) is convex we have the \(L^{2}\)-estimate:_

(4.33) \[\|{\bf u}-{\bf u}_{h}\|_{0,\,\Omega}\leqslant C_{2}h^{2}\{|{\bf u}|_{2,\, \Omega}+|p|_{1,\,\Omega}\}.\]

Figure 19: Triangle \(K\) divided into four subtriangles
