long time this was believed to be the simplest velocity space to associate with the above pressure space \(Q_{n}\). However, following a further idea of Fortin [30], Bernardi & Raugel [10] recently analyzed an intermediate velocity space which involves less degrees of freedom and lends itself more readily to higher order extensions. We shall study this element in detail.

Let \(\kappa\) be an arbitrary triangle of \(\mathcal{T}_{h}\) with vertices \(a_{1}\), \(a_{2}\), \(a_{3}\) like in Figure 8. We denote by \(f_{i}\) the side opposite \(a_{i}\) and by \(\mathbf{n}_{i}\) and \(\mathbf{t}_{i}\) the unit outward normal and unit tangent to \(f_{i}\). Our aim is a function \(\mathbf{w}\) with quadratic components in \(\kappa\) and affine tangential components on each side \(f_{i}\) of \(\kappa\):

\[\mathbf{w}|_{\kappa}\in P_{2}^{2},\quad\quad\mathbf{w}\cdot\mathbf{t}_{i}|_{f_ {i}}\in P_{1}.\]

This can be achieved by splitting \(\mathbf{w}\):

\[\mathbf{w}=\mathbf{w}_{1}+\mathbf{w}_{2}\]

into \(\mathbf{w}_{1}\in P_{1}^{2}\) and \(\mathbf{w}_{2}\in P_{2}^{2}\) such that \(\mathbf{w}_{2}\cdot\mathbf{t}_{i}|_{f_{i}}=0\).



As an example, observe that the function

\[\mathbf{p}_{1}=\mathbf{n}_{1}\lambda_{2}\lambda_{3}\]

vanishes on the sides \(f_{2}\) and \(f_{3}\) and satisfies \(\mathbf{p}_{1}\cdot\mathbf{t}_{1}|_{f_{1}}=0\). Generalizing this remark, we set:

(2.1) \[\mathbf{p}_{1}=\mathbf{n}_{1}\lambda_{2}\lambda_{3},\quad\quad\mathbf{p}_{2}= \mathbf{n}_{2}\lambda_{3}\lambda_{1},\quad\quad\mathbf{p}_{3}=\mathbf{n}_{3} \lambda_{1}\lambda_{2},\]

and we take the velocities \(\mathbf{w}\) in the polynomial subspace of \(P_{2}^{2}\):

(2.2) \[\mathcal{P}_{1}(\kappa)=P_{1}^{2}\oplus\operatorname{span}\{\mathbf{p}_{1}, \mathbf{p}_{2},\mathbf{p}_{3}\}.\]

Hence, we propose the following pair of spaces:

(2.3) \[\begin{cases}W_{h}=\{\mathbf{w}\in\mathcal{C}^{0}(\bar{\Omega})^{2};\,\mathbf{ w}|_{\kappa}\in\mathcal{P}_{1}(\kappa),\quad\forall\kappa\in\mathcal{T}_{h}\},\\ \bar{X}_{h}=W_{h}\cap H_{0}^{1}(\Omega)^{2},\end{cases}\]
