where \(\rho_{h}\) is the operator of orthogonal projection of \(L^{2}(\Omega)\) onto \(Q_{h}\). Clearly, Problem (1.52) dissociates the computation of \(\mathbf{u}_{h}^{\epsilon}\) from that of \(p_{h}^{\epsilon}\) since here \(p_{h}^{\epsilon}\) is given explicitly by

\[p_{h}^{\epsilon}=-\frac{1}{\varepsilon}\rho_{h}(\operatorname{div}\mathbf{u}_ {h}^{\epsilon}).\]

But, of course, this problem offers a practical interest only if the calculation of \(\rho_{h}(\operatorname{div}\mathbf{v}_{h})\) is simple. This will be precisely the case of nearly all methods discussed in this chapter because the functions of \(M_{h}\) will be piecewise discontinuous and \(\rho_{h}\) will be a local operator.

As far as the convergence of \(\mathbf{u}_{h}^{\epsilon}\) is concerned, a straightforward application of Theorem 1.3 gives the following result.

**Theorem 1.10**.: _Problem (1.52) has a unique solution \(\mathbf{u}_{h}^{\epsilon}\) for all \(\varepsilon>0\). Moreover, under Hypothesis \(\mathrm{H3}\), we have for all \(\varepsilon\leq\varepsilon_{0}\) sufficiently small:_

\[|\mathbf{u}_{h}-\mathbf{u}_{h}^{\epsilon}|_{1,\,\Omega}+\left\|\,p_{h}+\frac{ 1}{\varepsilon}\rho_{h}(\operatorname{div}\mathbf{u}_{h}^{\epsilon})\,\right\| _{0,\,\Omega}\leq C\varepsilon\|\mathbf{f}\|_{-1,\,\Omega}\]

_with a constant \(C>0\) independent of \(h\) and \(\varepsilon\)._

Similarly, \(\mathbf{u}_{h}^{\epsilon}\) and \(p_{h}^{\epsilon}\) can be expanded in powers of \(\varepsilon\). Starting with \(p_{h}^{0}=p_{h}\), we define the sequence \((\mathbf{u}_{h}^{n},p_{h}^{n})\in X_{h}\times\,M_{h}\), solution of

\[\begin{cases}a(\mathbf{u}_{h}^{n},\mathbf{v}_{h})-(\operatorname{div}\mathbf{ v}_{h},p_{h}^{n})=0&\quad\forall\mathbf{v}_{h}\in X_{h},\\ (\operatorname{div}\mathbf{u}_{h}^{n},q_{h})=-(p_{h}^{n-1},q_{h})&\quad\forall q _{h}\in Q_{h}.\end{cases}\] (1.53)

Then Theorem 1.4 yields the following asymptotic expansion:

**Theorem 1.11**.: _Under Hypothesis \(\mathrm{H3}\), we have for all integers \(M\geq 1\) and all \(\varepsilon\leq\varepsilon_{0}\) sufficiently small:_

\[\left|\mathbf{u}_{h}^{\epsilon}-\mathbf{u}_{h}-\sum\limits_{n=1} ^{M}\varepsilon^{n}\mathbf{u}_{h}^{n}\right|_{1,\,\Omega}+\left\|\,\frac{1}{ \varepsilon}\rho_{h}(\operatorname{div}\mathbf{u}_{h}^{\epsilon})+p_{h}+\sum \limits_{n=1}^{M}\varepsilon^{n}p_{h}^{n}\right\|_{0,\,\Omega}\] \[\quad\leq K_{M}\varepsilon^{M+1}\|\mathbf{f}\|_{-1,\,\Omega},\]

_with a constant \(K_{M}\) independent of \(h\) and \(\varepsilon\)._

Now, let us discuss the gradient algorithms. With the above choice of \(c(.,.)\), the bilinear form \(a_{r}^{h}(.,.)\) reads:

\[a_{r}^{h}(\mathbf{u},\mathbf{v})=a(\mathbf{u},\mathbf{v})+r(\rho_{h}( \operatorname{div}\mathbf{u}),\rho_{h}(\operatorname{div}\mathbf{v})).\]

It is \(H_{0}^{1}(\Omega)^{N}\)-elliptic and obviously symmetric. Therefore, the algorithms described by (1.33) and (1.34) are genuine gradient algorithms. The formulas for the _simple gradient algorithm with optimal parameter_ are:

1) Predict the initial value \(p_{h}^{0}\in M_{h}\) and compute the solution \(\mathbf{u}_{h}^{0}\in X_{h}\) of:
