\[\operatorname{div}_{\Gamma}(\psi\times\mathfrak{n}) =\mathbf{g}\boldsymbol{\cdot}\mathfrak{n},\] \[\operatorname{curl}_{\Gamma}(\psi\times\mathfrak{n}) =0,\]

where the subscript \(\Gamma\) indicates that the operators \(\operatorname{div}\) and \(\operatorname{curl}\) are surface operators. We refer to Roux [69] for more details.

## Appendix A Results of Standard Finite Element Approximation

This short chapter gathers most of the properties of the classical finite element approximation that will be required subsequently. The more familiar results are stated without proof; for detailed proofs and further material, the reader can refer to the very complete texts of Ciarlet [19] and Strang & Fix [77]. In addition, we include a brief mention of new or nonstandard material, developed among others by Clement [21], Bernardi [9], Scott [73], Lenoir [50], that will also be very useful later on.

### Triangular Finite Elements

**Definition A.1**.: For each integer \(k\geqslant 0\), we denote by \(P_{k}\) the space of all polynomials defined on \(\mathbb{R}^{N}\), of degree less than or equal to \(k\).

Recall that an \(N\)-simplex of \(\mathbb{R}^{N}\) is the convex hull \(\kappa\) of \(N+1\) points \(a_{j}\), \(1\leqslant j\leqslant N+1\), called the vertices of \(\kappa\), which are not all located in a single hyperplane. For instance, a 2-simplex is a non degenerate triangle and a 3-simplex is a non degenerate tetrahedron. The size and shape of an \(N\)-simplex \(\kappa\) are specified by two quantities:

\[h_{\kappa}=\text{diameter of }\kappa\]

and

\[\rho_{\kappa}=\sup\{\text{diameter of }B;\,B\text{ is a ball contained in }\kappa\}.\]

In addition, the regularity of \(\kappa\) is measured by the ratio

\[\sigma_{\kappa}=h_{\kappa}/\rho_{\kappa}.\]

We denote by \(\hat{\kappa}\) the reference unit simplex in the \((\hat{x}_{1},\ldots,\hat{x}_{N})\) space with vertices \(\hat{a}_{j}=(\delta_{ij})_{1\leqslant i\leqslant N}\), for \(1\leqslant j\leqslant N\), and \(\hat{a}_{N+1}=(0)_{1\leqslant i\leqslant N}\). If \(\kappa\) is an \(N\)-simplex with vertices \(a_{j}\), \(1\leqslant j\leqslant N+1\), there exists exactly one affine mapping

(A.1) \[F_{\kappa}(\hat{x})=B_{\kappa}\hat{x}+b_{\kappa}\]

that maps \(\hat{\kappa}\) onto \(\kappa\) with \(F_{\kappa}(\hat{a}_{i})=a_{i}\) for \(1\leqslant i\leqslant N+1\) (cf. Figure 3). Furthermore,
