## Chapter III Incompressible Mixed Finite Element Methods for Solving the Stokes Problem

### 1 Mixed Approximation of an Abstract Problem

In this paragraph, we concentrate again upon the abstract problem studied in Chapter I SS 4, but we put it into a weaker setting leading to a (generally) different mixed formulation. The mixed approximation derived from this formulation will give rise to the important class of exactly incompressible methods to solve the Stokes and Navier-Stokes equations.

### A Mixed Variational Problem

We put ourselves into the situation of Section I.4.1. Recall that \(X\) and \(M\) are two Hilbert spaces and that \(a(.,.)\) and \(b(.,.)\) are two _continuous bilinear_ forms on \(X\times X\) and \(X\times M\) respectively. Recall that _Problem_ (Q) is:

_For \((l,\chi)\) given in \(X^{\prime}\times M^{\prime}\), find a pair \((u,\lambda)\) in \(X\times M\) with:_

(1.1) \[a(u,v)+b(v,\lambda) =\langle l,v\rangle\quad\quad\forall v\in X,\] (1.2) \[b(u,\mu) =\langle\chi,\mu\rangle\quad\quad\forall\mu\in M.\]

As usual, we set

\[V(\chi)=\{v\in X;\,b(v,\mu)=\langle\chi,\mu\rangle\quad\forall\mu\in M\},\]

\[V=V(0).\]

Again, we assume that \(a(.,.)\) and \(b(.,.)\) satisfy the two hypotheses:

there exists a constant \(\alpha>0\) such that

(1.3) \[a(v,v)\geq\alpha\,\|\,v\,\|_{X}^{2}\quad\quad\forall v\in V;\]

there exists a constant \(\beta>0\) such that

(1.4) \[\sup_{v\in X}\frac{b(v,\mu)}{\|\,v\,\|_{X}}\geq\beta\,\|\,\mu\|_{M}\quad\quad \forall\mu\in M.\]

These two assumptions guarantee that the Problem (Q) and its corresponding
