We shall study further on several boundary conditions that must be added to this equation in order to specify \(\phi\) uniquely.

_Remark 3.9_.: A simple consequence of Theorem 3.4 is that if \(\mathbf{v}\in L^{2}(\Omega)^{3}\) satisfies (3.1) and in addition \(\mathbf{curl}\,\mathbf{v}=\mathbf{0}\) and \(\mathbf{v}\times\mathbf{n}|_{\Gamma}=\mathbf{0}\) then \(\mathbf{v}=\mathbf{0}\).

_Remark 3.10_.: When \(\Gamma\) has only one component (i.e. \(p=0\)) then (3.1) reduces to the sole condition \(\operatorname{div}\mathbf{v}=0\).

The next results give further information on the regularity of the vector potential.

_Remark 3.11_.: When \(\mathbf{v}\in H\cap L^{s}(\Omega)^{3}\) for some \(s>2\), it can be shown that the construction of Theorem 3.4 gives a vector potential \(\phi\) in \(W^{1,s}(\Omega)^{3}\) with \(\operatorname{div}\phi=0\).

**Corollary 3.3**.: _Let \(\mathbf{v}\in H^{1}(\Omega)^{3}\) satisfy (3.1). Then it has a divergence-free vector potential \(\phi\) in \(H^{2}(\Omega)^{3}\):_

\[\mathbf{v}=\mathbf{curl}\,\phi,\quad\operatorname{div}\phi=0.\]

The proof is left as an exercise. (Hint: use Lemma 2.2 to extend \(\mathbf{v}\) to \(\mathbb{R}^{3}\) by matching its boundary values with that of its extension; then construct the vector potential by Fourier transforms.)

_Remark 3.12_.: By interpolating between Theorem 3.4 and Corollary 3.3 we immediately see that if \(\mathbf{v}\in H^{s}(\Omega)^{3}\), with \(s\in[0,1]\), satisfies (3.1) then it has a divergence-free vector potential \(\phi\) in \(H^{s+1}(\Omega)^{3}\).

_Remark 3.13_.: When \(\Gamma\) is of class \(\mathcal{C}^{m,\,1}\) (\(m\geqslant 2\)), it can be shown that each \(\mathbf{v}\) in \(H^{m}(\Omega)^{3}\) satisfying (3.1) has a divergence-free vector potential \(\phi\) in \(H^{m\,+\,1}(\Omega)^{3}\).

Now, we turn to the boundary conditions that characterize \(\phi\).

**Theorem 3.5**.: \(1^{\circ}\)_Let \(\mathbf{v}\in L^{2}(\Omega)^{3}\) satisfy (3.1); among the vector potentials \(\phi\) verifying:_

(3.23) \[\mathbf{curl}\,\phi=\mathbf{v},\quad\operatorname{div}\phi=0,\]

_we can choose \(\phi\) in \(H(\mathbf{curl};\Omega)\) such that:_

(3.24) \[\phi\cdot\mathbf{n}=0.\]

_Moreover, when \(\Omega\) is simply-connected, \(\phi\) is entirely determined by (3.23) and (3.24); it can be characterized as the unique solution of the boundary value problem:_

(3.25) \[\left\{\begin{aligned} &\phi\in H,\\ &-\lambda\phi=\mathbf{curl}\,\mathbf{v}\quad\text{in }H^{-1}(\Omega)^{3}\\ &(\mathbf{curl}\,\phi-\mathbf{v})\cdot\mathbf{n}=0\quad\text{on } \Gamma.\end{aligned}\right.\]

\(2^{\circ}\)_If \(\Gamma\) is smooth (for instance of class \(\mathcal{C}^{1,\,1}\)), then \(\phi\in H^{1}(\Omega)^{3}\)._
