Now we are in a position to define the dual linearized Navier-Stokes system:

\[\begin{split}&\text{\em For }g=\mathbf{g}\in L^{2}(\Omega)^{2}\text{ \em find }z=(\mathbf{curl}\,\chi,\mu)\in V\text{\em such that:}\\ &\tilde{a}((I\,+\,TD^{*})z,v)=(\mathbf{g},\mathbf{curl}\,\phi) \quad\quad\forall v=(\mathbf{curl}\,\phi,\theta)\in V;\\ & z=(I\,+\,TD^{*})^{-1}\,Tg.\end{split}\] (4.40)

**Lemma 4.1**.: _Let \(\Omega\) be a bounded, Lipschitz-continuous domain of \(\,\mathbb{R}^{2}\) and suppose the Stokes problem has the regularity (4.18). Then the solution \(z=(\mathbf{curl}\,\chi,\mu)\) of Problem (4.40) belongs to \(H^{2}(\Omega)\times H^{1}(\Omega)\) with_

(4.41) \[\|\chi\|_{3,\,\Omega}+\,\|\,\mu\|_{1,\,\Omega}\leq C\,\{1\,+\,\lambda(\|\psi( \lambda)\|_{3,\,\Omega}+\,\|\,o(\lambda)\|_{1,\,\Omega})\}\,\|\,\mathbf{g}\|_ {0,\,\Omega}.\]

Proof.: First, it stems from (4.40) that

(4.42) \[\|\,z\|_{X}\leq C_{1}\,\|\,\mathbf{g}\|_{0,\,\Omega}.\]

Next we know from Lemma III.2.1 that all functions \(v=(\mathbf{curl}\,\phi,\theta)\in V\) satisfy:

\[\mathbf{curl}\,\phi\in H^{1}_{0}(\Omega)^{2},\quad\quad\theta=-\,\Delta\phi, \quad\quad\|\,\theta\|_{0,\,\Omega}=|v|\cong\|\,v\|_{X}.\]

Therefore

\[\langle D^{*}z,v\rangle =\lambda(\mathbf{curl}\,\chi,o(\lambda)\,\mathbf{grad}\,\phi- \,\Delta\phi\,\mathbf{grad}\,\psi(\lambda))\quad\quad\forall v\in V\] \[=\lambda(\mathbf{curl}(\mathbf{curl}\,\chi\cdot\mathbf{grad}\, \psi(\lambda))-o(\lambda)\,\mathbf{grad}\,\chi,\mathbf{curl}\,\phi).\]

Thus \(D^{*}z\) can be written in the form

\[\langle D^{*}z,v\rangle=(\mathbf{l},\mathbf{curl}\,\phi)\quad\quad\forall v= (\mathbf{curl}\,\phi,\theta)\in V\]

where, in view of the regularity of \(u(\lambda)\) and Sobolev's Imbedding Theorem I.1.3, \(\mathbf{l}\in L^{2}(\Omega)^{2}\) with

\[\|\mathbf{l}\|_{0,\,\Omega} \leq C_{2}\,\lambda(\|\,o(\lambda)\|_{1,\,\Omega}+\,\|\,\psi( \lambda)\|_{3,\,\Omega})\,\|\chi\|_{2,\,\Omega},\] \[\leq C_{3}\,\lambda(\|\,o(\lambda)\|_{1,\,\Omega}+\,\|\,\psi( \lambda)\|_{3,\,\Omega})\,\|\,\mathbf{g}\|_{0,\,\Omega},\]

since \(z\in V\) and satisfies (4.42). Then (4.41) follows from this last inequality, the regularity assumption (4.18) and the fact that \(z\) can also be expressed as \(z=T(g-D^{*}z)\). 

**Theorem 4.5**.: _Let \(\Omega\) and \(\mathcal{T}_{h}\) be like in Theorem 4.4 and suppose that the Navier-Stokes Problem (4.42) has a branch of nonsingular solutions such that the mapping \(\lambda\to\psi(\lambda)\) is continuous from \(\Lambda\) into \(H^{l+1}(\Omega)\) when \(l\geq 2\) or \(H^{3}(\Omega)\) when \(l=1\). Then we have the following estimate for all \(\lambda\) in \(\Lambda\):_

(4.43) \[|\psi(\lambda)-\psi_{h}(\lambda)|_{1,\,\Omega}\leq\begin{cases}C_{1}h^{1}& \text{if }l\geq 2,\\ C_{2}(\varepsilon)h^{1-\varepsilon}&\text{if }l=1\quad\quad\forall \varepsilon>0,\end{cases}\]

_with constants independent of \(h\) and \(\lambda\)._
