Then, there is a subsequence \((u_{\mu})\) such that \((Bu_{\mu})\) converges in \(E_{3}\). Hence \((u_{\mu})\) is a Cauchy sequence in \(E_{1}\) and therefore

\[\lim_{\mu\to\infty}u_{\mu}=u\]

with

\[Au=0,\quad\quad Mu=0\quad\text{and}\quad\|u\|_{E_{1}}=1.\]

But then, (2.3) implies that \(u=0\); this leads to a contradiction. 

Now, let \(\Omega\) be a bounded subset of \(\mathbb{R}^{N}\) with a Lipschitz-continuous boundary \(\Gamma\). From now on, we shall often deal with vector-valued functions. We shall distinguish vectors by means of bold-face characters and extend naturally all the previous norms to vectors as follows: if \(\mathbf{v}=(v_{1},\ldots,v_{N})\) then

\[\|\mathbf{v}\|_{m,\,p,\,\Omega}=\left(\sum_{i=1}^{N}\|v_{i}\|_{m,\,p,\,\Omega} ^{p}\right)^{1/p}.\]

The next theorem is part of a general result of functional analysis due to Necas [57]. Its proof is long and delicate because it only assumes the Lipschitz-continuity of the boundary. When the boundary is smooth there is an alternate, easier proof that can be found in Duvaut & Lions [26]. Here we omit either proof for they are both outside the scope of this book.

**Theorem 2.2**.: _Let \(\Omega\) be a bounded, Lipschitz-continuous open set. There exists a constant \(C>0,\) depending only on \(\Omega,\) such that_

(2.6) \[\|p\|_{0,\,\Omega}\leqslant C\{\,\|p\|_{-1,\,\Omega}+\,\|\mathbf{ grad}\,p\|_{-1,\,\Omega}\}\quad\quad\forall p\in L^{2}(\Omega).\]

As an immediate consequence, we have:

**Corollary 2.1**.: \(1^{\circ}\) _Under the assumptions of Theorem 2.2, the range of the gradient operator_: \(\mathbf{grad}\in\mathcal{L}(L^{2}(\Omega);H^{-1}(\Omega)^{N})\) is a closed subspace of \(H^{-1}(\Omega)^{N}.\)_

\(2^{\circ})\)_If in addition \(\Omega\) is connected_, _there exists a constant \(C>0,\) depending only on \(\Omega,\) such that_

(2.7) \[\|\,\dot{p}\|_{L^{2}(\Omega)/\mathbb{R}}\leqslant C\,\|\,\mathbf{ grad}\,\dot{p}\|_{-1,\,\Omega}\quad\quad\forall\dot{p}\in L^{2}(\Omega)/ \mathbb{R}.\]

\(3^{\circ})\)_Let \(\omega\) be an open subset of \(\Omega\) with positive measure. There exists a constant \(C_{\omega}>0\) depending only on \(\Omega\) and \(\omega\) such that_

(2.8) \[\|p\|_{0,\,\Omega}\leqslant C_{\omega}\{\,\|p\|_{0,\,\omega}+\|\mathbf{ grad}\,p\|_{-1,\,\Omega}\}\quad\quad\forall p\in L^{2}(\Omega).\]

Proof.: The idea is to apply Theorem 2.1 with \(E_{1}=L^{2}(\Omega),\)\(E_{2}=H^{-1}(\Omega)^{N},\)\(E_{3}=H^{-1}(\Omega),\)\(A=\mathbf{grad}\) and \(B=\) the canonical imbedding of \(L^{2}(\Omega)\) into \(H^{-1}(\Omega)\) which is compact according to Theorem 1.3. Clearly,

\[\|p\|_{-1,\,\Omega}+\|\mathbf{grad}\,p\|_{-1,\,\Omega}\leqslant C_{1}\,\|p\|_{ 0,\,\Omega}\quad\quad\forall p\in L^{2}(\Omega).\]
