As in the linear case we set \(V=\operatorname{Ker}(B)\) and we associate with Problem (Q) the following problem, called _Problem_ (P):

_Find \(u\in V\) such that_

(1.5) \[a(u;u,v)=\langle l,v\rangle\ \ \ \ \ \ \forall v\in V,\]

or equivalently such that

(1.6) \[\pi A(u)u=\pi l\ \ \ \ in\ V^{\prime},\]

where the linear operator \(\pi\in\mathcal{L}(X^{\prime};V^{\prime})\) is again defined by:

\[\langle\pi l,v\rangle=\langle l,v\rangle\ \ \ \ \ \ \forall v\in V.\]

Of course, if \((u,\dot{\lambda})\) is a solution of Problem (Q), then \(u\) is a solution of Problem (P). The converse property may be easily established as in the linear case provided the inf-sup condition holds. Therefore, the real difficulty here lies in solving the _nonlinear_ Problem (P). To begin with, we need to derive a simple consequence of the following classical fixed-point theorem due to Brouwer, which we state without proof.

Theorem 1.1: _Let \(C\) denote a non-void, convex and compact subset of a finite-dimensional space and let \(F\) be a continuous mapping from \(C\) into \(C\). Then, \(F\) has at least one fixed point._

Corollary 1.1: _Let \(H\) be a finite-dimensional Hilbert space whose scalar product is denoted by \((.\,,.)\) and the corresponding norm by \(|.|\). Let \(\Phi\) be a continuous mapping from \(H\) into \(H\) with the following property:_

_there exists \(\mu>0\) such that_

(1.7) \[(\Phi(f),f)\geqslant 0\ \ \ \text{ for all }\ \ \ f\in H\ \ \ \text{with}\ \ \ |f|=\mu.\]

_Then, there exists an element \(f\) in \(H\) such that_

(1.8) \[\Phi(f)=0,\ \ \ \ |f|\leqslant\mu.\]

_Proof_. The proof proceeds by contradiction. Suppose that \(\Phi(f)\neq 0\) in the closed sphere \(S=\{f\in H;|f|\leqslant\mu\}\). Then, the mapping

\[f\to-\mu\Phi(f)/|\Phi(f)|\]

is continuous from \(S\) into \(S\). As the dimension of \(H\) is finite and since the set \(S\) is obviously non-void, convex and compact, we may apply Theorem 1.1:

there exists an \(f\in S\) such that

\[f=-\mu\Phi(f)/|\Phi(f)|.\]

Thus, we have exhibited an \(f\in H\) such that \(|f|=\mu\) and

\[(\Phi(f),f)=-\mu|\Phi(f)|<0.\]

This contradicts (1.7).
