**Lemma 3.2**.: _Suppose that \(\Omega\) is a bounded, convex polygon and \(\mathcal{T}_{h}\) a uniformly regular family of triangulations of \(\bar{\Omega}\). Let \(k\) be an integer and \(p\) a real number such that \(1\leq k\leq l\) and \(2\leq p\leq\infty\). There exists a constant \(C>0\), independent of \(h\), such that for all functions \(\phi\in W^{k+1,\,p}(\Omega)\cap H^{1}_{0}(\Omega)\), we have:_

\[\sup_{\mu_{h}\in\,\Theta_{h}}\frac{|(\operatorname{\mathbf{curl}}(\phi-\check{ P}_{h}\phi),\operatorname{\mathbf{curl}}\mu_{h})|}{\|\mu_{h}\|_{0,\,\Omega}} \leq Ch^{k-1/2-1/p}\|\phi\|_{k+1,\,p,\,\Omega}.\] (3.3)

Proof.: First, note that \(\Phi_{h}\subset H^{1}_{0}(\Omega)\) because \(\Omega\) is convex. Next, let \(\mu_{h}\) be an arbitrary element of \(\Theta_{h}\) and let \(\lambda_{h}\) denote the function of \(\Phi_{h}\) which coincides with \(\mu_{h}\) at all interior finite element nodes. In particular, if \(\Sigma_{h}\) denotes the union of the boundary elements of \(\mathcal{T}_{h}\) then \(\operatorname{supp}(\mu_{h}-\lambda_{h})\subset\Sigma_{h}\). Therefore since

\[(\operatorname{\mathbf{curl}}(\phi-\check{P}_{h}\phi),\operatorname{\mathbf{ curl}}\phi_{h})=0\quad\quad\forall\phi_{h}\in\Phi_{h},\]

this implies:

\[(\operatorname{\mathbf{curl}}(\phi-\check{P}_{h}\phi),\operatorname{\mathbf{ curl}}\mu_{h})=\sum_{\kappa\subset\Sigma_{h}}\int_{\kappa}\operatorname{ \mathbf{curl}}(\phi-\check{P}_{h}\phi)\cdot\operatorname{\mathbf{curl}}(\mu_ {h}-\lambda_{h})\,dx.\]

Hence by Holder's inequality, we have:

\[|(\operatorname{\mathbf{curl}}(\phi-\check{P}_{h}\phi),\operatorname{\mathbf{ curl}}\mu_{h})|\leq|\phi-\check{P}_{h}\phi|_{1,\,p,\,\Sigma_{h}}|\mu_{h}- \lambda_{h}|_{1,\,q,\,\Sigma_{h}},\] (3.4)

where

\[1/p+1/q=1,\quad\text{with }p\geq 2.\]

Now, (A.32) and the argument of Corollary A.3 yield:

\[|\mu_{h}-\lambda_{h}|_{1,\,q,\,\Sigma_{h}}\leq C_{1}h^{-1}(\operatorname{meas }(\Sigma_{h}))^{1/q-1/2}\|\mu_{h}-\lambda_{h}\|_{0,\,\Sigma_{h}}.\]

On the one hand

\[\|\mu_{h}-\lambda_{h}\|_{0,\,\Sigma_{h}}\leq C_{2}\|\mu_{h}\|_{0,\,\Sigma_{h}}\]

because \(\mu_{h}-\lambda_{h}\) vanishes on all interior nodes of \(\mathcal{T}_{h}\) and reduces to \(\mu_{h}\) on all boundary nodes. On the other hand,

\[\operatorname{meas}(\Sigma_{h})\leq C_{3}h\operatorname{meas}(\Gamma).\]

Therefore,

\[|\mu_{h}-\lambda_{h}|_{1,\,q,\,\Sigma_{h}}\leq C_{4}h^{-1/2-1/p}\|\mu_{h}\|_{0 ,\,\Sigma_{h}}.\]

When substituted into (3.4), this inequality gives:

\[|(\operatorname{\mathbf{curl}}(\phi-\check{P}_{h}\phi),\operatorname{\mathbf{ curl}}\mu_{h})|\leq C_{4}h^{-1/2-1/p}|\phi-\check{P}_{h}\phi|_{1,\,p,\, \Omega}\|\mu_{h}\|_{0,\,\Omega}\]

and the desired result follows from the estimate (A.26), whatever the value of \(k\) since \(p\geq 2\). 

_Remark 3.1_.: Let us denote

\[c(\phi,\mu_{h})=(\operatorname{\mathbf{curl}}(\phi-\check{P}_{h}\phi), \operatorname{\mathbf{curl}}\mu_{h})\quad\quad\forall\phi\in W^{1,\,p}( \Omega),\quad\quad\forall\mu_{h}\in\Theta_{h},\]
