Proof.: The proof is based on the Closed Range Theorem of Banach. First, we note that \(-\,\mathbf{grad}\,{\in}\,\mathcal{L}(L^{2}(\Omega);H^{-1}(\Omega)^{N})\) is the dual operator of \(\operatorname{div}\,{\in}\,\mathcal{L}(H^{1}_{0}(\Omega)^{N};\)\(L^{2}(\Omega)).\) Then, since \(\mathcal{R}(\mathbf{grad})\) is a closed subspace of \(H^{-1}(\Omega)^{N}\), we can apply the Closed Range Theorem of Banach (cf. for instance Yosida [84]):

\[\mathcal{R}(\mathbf{grad})=(\operatorname{Ker}(\operatorname{div}))^{0}=V^{0},\]

where \(V^{0}\) denotes the polar set of \(V\):

(2.10) \[V^{0}=\{\mathbf{y}\,{\in}\,H^{-1}(\Omega)^{N};\,\langle\mathbf{y},\phi\rangle =0\quad\forall\phi\,{\in}\,V\}.\]

This is precisely the statement of our lemma. 

The next corollary gives a characterization of \(V^{\perp}\). Previously, we require a definition.

**Definition 2.1**.: Let \((-\,\Delta)^{-1}\,{\in}\,\mathcal{L}(H^{-1}(\Omega)^{N};H^{1}_{0}(\Omega)^{N})\) denote Green's operator related to Dirichlet's homogeneous problem for \(-\,\Delta\) in \(\mathbb{R}^{N}\), i.e. \(\mathbf{u}=(-\,\Delta)^{-1}\,\mathbf{f}\,{\rm iff}\,\mathbf{u}\) is the solution of:

\[-\,\Delta\mathbf{u}=\mathbf{f}\quad\text{in }\Omega,\quad\mathbf{u}=\mathbf{0} \quad\text{on }\Gamma.\]

**Corollary 2.3**.: _We have_

\[V^{\perp}=\{(-\,\Delta)^{-1}\,\mathbf{grad}\,q;\,q\,{\in}\,L^{2}(\Omega)\}.\]

Proof.: First, it is easy to check that \((-\,\Delta^{-1})\,\mathbf{grad}\,q\,{\in}\,V^{\perp}\) for all \(q\) in \(L^{2}(\Omega)\). Conversely, let \(\mathbf{u}\,{\in}\,V^{\perp}\) and consider the linear functional \(l\) defined on \(H^{1}_{0}(\Omega)^{N}\) by \(\langle l,\nu\rangle=(\mathbf{grad}\,\mathbf{u},\mathbf{grad}\,\mathbf{v})\). It belongs to \(H^{-1}(\Omega)^{N}\) and vanishes on \(V.\) Therefore, in view of Lemma 2.1, there exists \(p\,{\in}\,L^{2}(\Omega)\) such that:

\[\langle l,\mathbf{v}\rangle=(\mathbf{grad}\,\mathbf{u},\mathbf{grad}\,\mathbf{ v})=\langle\mathbf{grad}\,p,\mathbf{v}\rangle\quad\quad\forall\mathbf{v}\,{\in}\,H^{1}_{0}( \Omega)^{N}.\]

Hence \(\mathbf{u}\) has indeed the expression: \(\mathbf{u}=(-\,\Delta^{-1})\,\mathbf{grad}\,p.\) 

Now, we observe that Green's formula (1.19) yields:

\[\int_{\Omega}\operatorname{div}\,\mathbf{v}\,dx=0\quad\quad\forall\mathbf{v}\, {\in}\,H^{1}_{0}(\Omega)^{N}.\]

Thus the range space of \(\operatorname{div}\) is contained in a proper, closed subspace of \(L^{2}(\Omega)\) which for the sake of convenience we denote by \(L^{2}_{0}(\Omega)\):

\[L^{2}_{0}(\Omega)=\biggl{\{}p\,{\in}\,L^{2}(\Omega);\,\int_{\Omega}p\,dx=0 \biggr{\}}.\]

The usefulness of \(L^{2}_{0}(\Omega)\) arises in particular from the fact that

(2.11) \[\|\,q\,\|_{\,0,\Omega}=\inf_{\,\subseteq\,\subseteq\,\mathbb{R}}\|\,q\,+\,c\, \|_{\,0,\Omega}=\|\,\hat{q}\|_{L^{2}(\Omega)/\mathbb{R}}\quad\quad\forall q\, {\in}\,L^{2}_{0}(\Omega).\]
