Proof.: First observe that \(D\) is a convex subset of \(X\). Indeed, as \(J\) is convex in \(D\), we have for all \(v_{1}\) and \(v_{2}\) in \(D\):

\[J(\theta v_{1}+(1-\theta)v_{2}) \leq\theta J(v_{1})+(1-\theta)J(v_{2})\quad\quad\forall\theta\in \llbracket 0,1\rrbracket\] \[\leq C_{0}\quad\text{by virtue of \eqref{eq:D}.}\]

Since \(D\) is connected, this means that \(\theta v_{1}+(1-\theta)v_{2}\in D\).

Next, we set

\[D^{\prime}=\{v\in D;J(v)\leq J(u^{0})\}\]

and we assume that the starting value \(u^{0}\) is not the solution of (6.3) (otherwise the algorithm of descent yields the constant value \(u^{m}=u^{0}\)). Again, \(D^{\prime}\) is convex and because \(J\) is continuous, \(D^{\prime}\) is obviously a closed subset of \(X\). Let us establish that \(D^{\prime}\) is bounded. Taylor's formula gives:

\[J(v)=J(u^{0})+\langle DJ(u^{0}),v-u^{0}\rangle+(1/2)D^{2}J(u^{0}+t(v-u^{0})) \cdot(v-u^{0},v-u^{0})\]

for some \(t\in(0,1)\). To simplify, we denote

\[g^{m}=g(u^{m}).\]

Then, for all \(v\) in \(D^{\prime}\), the convexity of \(D^{\prime}\) and (6.2) imply

(6.8) \[J(v)\geq J(u^{0})-\|g^{0}\|_{X}\|v-u^{0}\|_{X}+(\alpha/2)\|v-u^{0}\|_{X}^{2}.\]

But since \(J(v)\leq J(u^{0})\) this yields:

\[J(u^{0})\geq J(u^{0})-\|g^{0}\|_{X}\|v-u^{0}\|_{X}+(\alpha/2)\|v-u^{0}\|_{X}^{ 2};\]

in other words:

(6.9) \[\|v-u^{0}\|_{X}\leq(2/\alpha)\|g^{0}\|_{X}.\]

This proves the boundedness of \(D^{\prime}\).

Observe also that \(J\) is bounded below in \(D^{\prime}\) because (6.8) and (6.9) imply

(6.10) \[J(v)\geq J(u^{0})-(2/\alpha)\|g^{0}\|_{X}^{2}.\]

Now we remark that the equation (6.5) defines a unique \(\rho^{m}\geq 0\) for each pair \(u^{m}\) and \(w^{m}\) satisfying (6.7). Indeed, since by construction \(u^{m}\) belongs to the interior of \(D\), the mapping \(\rho\to J(u^{m}-\rho w^{m})\) is strictly convex for all \(\rho\) such that \(u^{m}-\rho w^{m}\in D\). Hence \(J(u^{m}-\rho w^{m})\) has a unique minimum in \(D\) and this minimum is realized by a unique interior element of \(D\), \(u^{m}-\rho^{m}w^{m}\), with \(\rho^{m}\geq 0\). Therefore \(u^{m}-\rho^{m}w^{m}\) is characterized by:

\[\left[dJ(u^{m}-\rho w^{m})/d\rho\right]_{|_{\rho=m}=}=-\langle DJ(u^{m}-\rho^{ m}w^{m}),w^{m}\rangle=0.\]

With (6.6) this can also be written:

(6.11) \[\langle DJ(u^{m+1}),w^{m}\rangle=(g^{m+1},w^{m})_{X}=0.\]

Note also that (6.11) gives:
