\[\mathcal{L}_{\mathbf{u}_{0}}(\mathbf{v},q)=(1/2)a(\mathbf{v},\mathbf{v})-\langle \mathbf{f},\mathbf{v}\rangle+a(\mathbf{u}_{0},\mathbf{v})-(q,\operatorname{div} \mathbf{v})\]

over the product space \(H^{1}_{0}(\Omega)^{N}\times L^{2}_{0}(\Omega)\). By taking into account that \(\operatorname{div}\mathbf{u}_{0}=\operatorname{div}\mathbf{u}=0\), this exactly means that

\[\mathcal{L}(\mathbf{u},q)=\mathcal{L}(\mathbf{u},p)\leqslant\mathcal{L}( \mathbf{v}+\mathbf{u}_{0},p)\quad\quad\forall\mathbf{v}\in H^{1}_{0}(\Omega)^{ N},\quad\quad\forall q\in L^{2}_{0}(\Omega)\]

and therefore that \((\mathbf{u},p)\) is the unique saddle-point of the functional \(\mathcal{L}\) over \([\mathbf{u}_{0}+H^{1}_{0}(\Omega)^{N}]\times L^{2}_{0}(\Omega)\).

Now, using

\[\mathbf{u}_{0}+H^{1}_{0}(\Omega)^{N}=\{\mathbf{v}\in H^{1}(\Omega)^{N}; \mathbf{v}|_{\Gamma}=\mathbf{g}\}\]

and arguing as in the proof of Corollary 4.2, we obtain the characterization (5.20). 

By adapting the arguments of Paragraph 4.2 to the present situation, we find that \(\mathbf{u}\) is characterized by

(5.21) \[J(\mathbf{u})=\inf_{\begin{subarray}{c}\mathbf{v}\in H^{1}(\Omega)^{N}\\ \operatorname{div}\mathbf{v}=0,\,\mathbf{v}|_{\Gamma}=\mathbf{g}\end{subarray}}J (\mathbf{v}).\]

On the other hand, with any \(q\in L^{2}_{0}(\Omega)\), we associate the solution \(\mathbf{u}(q)\in H^{1}(\Omega)^{N}\) of the boundary value problem

(5.22) \[\begin{cases}-\nu\Delta\mathbf{u}(q)=\mathbf{f}-\mathbf{grad}\,q\quad\text{in } \Omega,\\ \mathbf{u}=\mathbf{g}\quad\text{on }\Gamma.\end{cases}\]

Then setting

(5.23) \[K(q)=(1/2)a(\mathbf{w}(q),\mathbf{w}(q))\]

where \(\mathbf{w}(q)=\mathbf{u}(q)-\mathbf{u}_{0}\) with \(\operatorname{div}\mathbf{u}_{0}=0\), \(\mathbf{u}_{0}|_{\Gamma}=\mathbf{g}\), we find that the function \(p\in L^{2}_{0}(\Omega)\) is characterized by

(5.24) \[K(p)=\operatorname*{Min}_{q\in L^{2}_{0}(\Omega)}K(q).\]

In order to eliminate the pressure, we can use the regularization method or penalty method introduced in Section 4.3. We consider the following problem:

(5.25) \[\begin{cases}-\nu\Delta\mathbf{u}^{\epsilon}+\mathbf{grad}\,p^{\epsilon}= \mathbf{f}\quad\text{in }\Omega,\\ p^{\epsilon}=-(1/\epsilon)\operatorname{div}\mathbf{u}^{\epsilon}\quad\text{in } \Omega,\\ \mathbf{u}^{\epsilon}=\mathbf{g}\quad\text{on }\Gamma.\end{cases}\]

By eliminating \(p^{\epsilon}\), we get an equivalent second order elliptic problem in \(\mathbf{u}^{\epsilon}\):

(5.26) \[\begin{cases}-\nu\Delta\mathbf{u}^{\epsilon}-(1/\epsilon)\mathbf{grad}\, \operatorname{div}\mathbf{u}^{\epsilon}=\mathbf{f}\quad\text{in }\Omega,\\ \mathbf{u}^{\epsilon}=\mathbf{g}\quad\text{on }\Omega.\end{cases}\]
