Hence, the form \(\tilde{a}(.;.,.,.)\) satisfies the property (1.13) (and also (1.9)). Besides that, the property (1.10) is established exactly as in the proof of Theorem 2.1. Since the \(\inf\)-sup condition (1.18) holds, we obtain that Problem (2.21) has at least one solution \((\mathbf{w},p)\!\in\!V\,\times\,L^{2}_{0}(\Omega)\), which proves the theorem. 

Next, we derive a uniqueness result. For any function \(\mathbf{u}_{0}\!\in\!H^{1}(\Omega)^{N}\), we set

\[\rho(\mathbf{u}_{0})=\sup_{\mathbf{v}\,\in\,\boldsymbol{V}}\frac{a_{1}( \mathbf{v};\mathbf{u}_{0},\mathbf{v})}{|\mathbf{v}|_{1,\Omega}^{2}},\] (2.22)

\[\|l(\mathbf{f};\mathbf{u}_{0})\|_{V^{\prime}}=\sup_{\mathbf{v}\,\in\, \boldsymbol{V}}\frac{\langle l,\mathbf{v}\rangle}{|\mathbf{v}|_{1,\Omega}}, \quad\quad\langle l,\mathbf{v}\rangle=\langle\mathbf{f},\mathbf{v}\rangle-a( \mathbf{u}_{0};\mathbf{u}_{0},\mathbf{v}).\] (2.23)

Then, we define \(v_{0}=v_{0}(\Omega;\mathbf{f},\mathbf{g})\) by

\[v_{0}=\inf\{\rho(\mathbf{u}_{0})+(\mathcal{N}\,\|l(\mathbf{f};\mathbf{u}_{0}) \|_{V^{\prime}})^{1/2};\,\mathbf{u}_{0}\!\in\!H^{1}(\Omega)^{N}\text{ satisfies \eqref{eq:11}}\}.\] (2.24)

Given any number \(v>0\), it follows from Lemma 2.3 and the continuity of the mapping \(\mathbf{g}\!\to\!\mathbf{u}_{0}\) (cf. (I.2.12)) that we have \(v_{0}<v\) for \(\|\mathbf{f}\|_{V^{\prime}}\) and \(\|\mathbf{g}\|_{1/2,\,\Gamma}\) small enough.

**Theorem 2.4**.: _Assume the hypotheses of Theorem 2.3. Then, for \(v>v_{0}(\Omega;\mathbf{f},\mathbf{g})\), Problem (2.20) has a unique solution \((\mathbf{u},p)\!\in\!H^{1}(\Omega)^{N}\,\times\,L^{2}_{0}(\Omega)\)._

Proof.: Let us choose a function \(\mathbf{u}_{0}\!\in\!H^{1}(\Omega)^{N}\) which satisfies (2.15) and \(\rho(\mathbf{u}_{0})<v\). We want to apply Theorem 1.3 to Problem (2.21). We have for all \(\mathbf{v},\mathbf{w}\!\in\!V\)

\[\tilde{a}(\mathbf{w};\mathbf{v},\mathbf{v})\geqslant(v-\rho(\mathbf{u}_{0}))| \mathbf{v}|_{1,\Omega}^{2},\]

so that the property (1.13) holds with \(\alpha=v-\rho(\mathbf{u}_{0})\). Hence, it remains only to check (1.14). Let \(\mathbf{u},\,\mathbf{v},\,\mathbf{w}_{1},\,\mathbf{w}_{2}\) be in \(V\); using (2.10), we get

\[|\tilde{a}(\mathbf{w}_{1};\mathbf{u},\mathbf{v})-\tilde{a}( \mathbf{w}_{2};\mathbf{u},\mathbf{v})| =|a_{1}(\mathbf{w}_{1}-\mathbf{w}_{2};\mathbf{u},\mathbf{v})|\] \[\leqslant\mathcal{N}|\mathbf{u}|_{1,\Omega}|\mathbf{v}|_{1, \Omega}|\mathbf{w}_{1}-\mathbf{w}_{2}|_{1,\Omega}.\]

Hence, the form \(\tilde{a}(.;.,.,.)\) satisfies the property (1.14) with \(L(\mu)=.\,\,\hat{.}\,\). Now, the condition (1.15) becomes in our case

\[\frac{\mathcal{N}\,\|l(\mathbf{f};\mathbf{u}_{0})\|_{V^{\prime}}}{(v-\rho( \mathbf{u}_{0}))^{2}}<1\]

or equivalently

\[v>\rho(\mathbf{u}_{0})+(\mathcal{N}\,\|l(\mathbf{f};\mathbf{u}_{0})\|_{V^{ \prime}})^{1/2}.\]

By taking the infimum over all the admissible functions \(\mathbf{u}_{0}\), we obtain that, for \(v>v_{0}\), Problem (2.21) has a unique solution \((\mathbf{w},p)\!\in\!H^{1}_{0}(\Omega)^{N}\,\times\,L^{2}_{0}(\Omega)\) and therefore Problem (2.20) has a unique solution \((\mathbf{u}_{0}\,+\,\mathbf{w},p)\!\in\!H^{1}(\Omega)^{N}\,\times\,L^{2}_{0}(\Omega)\).
