(3.26) \[\left\{\begin{aligned} v(\mathbf{grad}\,\mathbf{u}_{h}, \mathbf{grad}\,\mathbf{v}_{h})-(p_{h},\operatorname{div}\mathbf{v}_{h})& =\langle\mathbf{f},\mathbf{v}_{h}\rangle\qquad\forall\mathbf{v}_{h} \in X_{h},\\ (q_{h},\operatorname{div}\mathbf{u}_{h})&=0\qquad \forall q_{h}\in M_{h},\end{aligned}\right.\]

with \(X_{h}\) and \(M_{h}\) defined by (3.19). We know that \(\mathbf{u}_{h}\) is unique but that each \(p_{h}\) is of the form:

\[p_{h}=\tilde{p}_{h}+p_{h}^{4}+C\mu\]

with \(\mu\) defined by (3.22), \(p_{h}^{4}\) and \(\tilde{p}_{h}\) uniquely determined in \(\tilde{A}_{h}\) and \(\tilde{M}_{h}\) respectively and \(C\) arbitrary. Furthermore, \(\mathbf{u}_{h}\in\tilde{V}_{h}\) with \(\tilde{V}_{h}\) defined by (3.33) and the pair \((\mathbf{u}_{h},\tilde{p}_{h})\in\tilde{V}_{h}\times\tilde{M}_{h}\) is the unique solution of:

(3.37) \[\left\{\begin{aligned} v(\mathbf{grad}\,\mathbf{u}_{h}, \mathbf{grad}\,\tilde{\mathbf{v}}_{h})-(\tilde{p}_{h},\operatorname{div}\tilde {\mathbf{v}}_{h})&=\langle\mathbf{f},\tilde{\mathbf{v}}_{h} \rangle\qquad\forall\tilde{\mathbf{v}}_{h}\in\tilde{V}_{h},\\ (\tilde{q}_{h},\operatorname{div}\mathbf{u}_{h})&=0 \qquad\forall\tilde{q}_{h}\in\tilde{M}_{h}.\end{aligned}\right.\]

Therefore, owing to Theorem 3.4, we can apply straight away Theorem 1.1\(2^{\circ}\)) with \(\tilde{V}_{h}\) and \(\tilde{M}_{h}\) instead of \(X_{h}\) and \(M_{h}\) respectively:

(3.38) \[\left\{\begin{aligned} &|\mathbf{u}-\mathbf{u}_{h}|_{1,\Omega}+ \|p-\tilde{p}_{h}\|_{0,\Omega}\\ &\quad\leqslant C_{1}\left\{\inf_{\tilde{\mathbf{v}}_{h}\in \tilde{V}_{h}}|\mathbf{u}-\tilde{\mathbf{v}}_{h}|_{1,\Omega}+\inf_{\tilde{q}_ {h}\in\tilde{M}_{h}}\|p-\tilde{q}_{h}\|_{0,\Omega}\right\}\end{aligned}\right.\]

with a constant \(C_{1}>0\) independent of \(h\).

Hence it remains to investigate the approximation properties of the spaces \(\tilde{V}_{h}\) and \(\tilde{M}_{h}\). As far as \(\tilde{V}_{h}\) is concerned, recall that (cf. Lemma 3.8):

\[X_{2h}\subset\tilde{V}_{h}.\]

Thus, formula (A.49) yields:

(3.39) \[\inf_{\tilde{\mathbf{v}}_{h}\in\tilde{V}_{h}}|\mathbf{u}-\tilde{\mathbf{v}}_{ h}|_{1,\Omega}\leqslant|\mathbf{u}-I_{2h}\mathbf{u}|_{1,\Omega}\leqslant C_{2}h| \mathbf{u}|_{2,\Omega}\qquad\forall\mathbf{u}\in H^{2}(\Omega)^{2}.\]

Likewise, since \(\tilde{M}_{h}\subset\tilde{M}_{h}\), formula (A.51) gives:

(3.40) \[\inf_{\tilde{q}_{h}\in\tilde{M}_{h}}\|p-\tilde{q}_{h}\|_{0,\Omega}\leqslant\|p -\rho_{2h}p\|_{0,\Omega}\leqslant C_{3}h|p|_{1,\Omega}\qquad\forall p\in H^{1} (\Omega).\]

These three inequalities are combined in the following theorem.

**Theorem 3.5**.: _Assume that \(\Omega\) is like in Theorem 3.4 and suppose the solution \((\mathbf{u},p)\) of the Stokes system satisfies:_

\[\mathbf{u}\in[H^{2}(\Omega)\cap H^{1}_{0}(\Omega)]^{2},\qquad p\in H^{1}( \Omega)\cap L^{2}_{0}(\Omega).\]

_Then the solution \((\mathbf{u}_{h},p_{h})\) of the scheme (3.36) has the error estimate:_

(3.41) \[|\mathbf{u}-\mathbf{u}_{h}|_{1,\Omega}+\|p-\tilde{p}_{h}\|_{0,\Omega}\leqslant Ch \{|\mathbf{u}|_{2,\Omega}+|p|_{1,\Omega}\},\]

_where \(\tilde{p}_{h}\) is the component of \(p_{h}\) in \(\tilde{M}_{h}\)._

Here the component \(\tilde{p}_{h}\)_acts as a filter_ for the pressure \(p_{h}\) since it discards entirely the alternating functions \(v_{\pm}\). It is clear, from Lemma 3.6, that no satisfying
