We propose to extend the above considerations to the case where \(\Omega\) is triangulated, each triangle being considered as a subregion of \(\Omega\). But, beforehand, let us recall the setting of the stream function-vorticity formulation and approximation of the Navier-Stokes system developed in Section 4.3.

Let \(\Omega\) be a bounded domain in \(\mathbb{R}^{2}\) with a polygonal boundary \(\Gamma\), so that it can be entirely triangulated and suppose \(\Omega\) is _convex_ so the regularity condition (4.18) holds. To simplify the discussion we agree to drop the pressure for the moment and consider only the stream function and vorticity. Then we set

\[Y=L^{r}(\Omega)^{2},\quad\ X=\{\operatorname{\mathbf{curl}}\phi;\,\phi\in \Phi_{s}\}\,\times\,L^{2}(\Omega)\]

with \(s\geqslant 4\) and \(1/r+1/s=1\). The Stokes operator \(T\in\mathcal{L}(Y;X)\) is defined by

\[T\mathbf{f}=(\operatorname{\mathbf{curl}}\psi,\omega)\quad\text{where}\] (5.3) \[\begin{cases}(\operatorname{\mathbf{curl}}\omega,\operatorname{ \mathbf{curl}}\phi)=(\mathbf{f},\operatorname{\mathbf{curl}}\phi)\quad\quad \forall\phi\in\Phi_{s},\\ (\operatorname{\mathbf{curl}}\psi,\operatorname{\mathbf{curl}}\mu)=(\omega, \mu)\quad\quad\forall\mu\in W^{1,\,r}(\Omega),\end{cases}\]

where \(\psi\) and \(\omega\) are related to the velocity \(\mathbf{u}\) by

(5.4) \[\mathbf{u}=\operatorname{\mathbf{curl}}\psi\quad\text{and}\quad\omega= \operatorname{\mathbf{curl}}\mathbf{u}.\]

As usual, we introduce the subspace of \(X\)

(5.5) \[V=\{(\operatorname{\mathbf{curl}}\phi,\theta)\in X;\,\phi\in H^{2}_{0}(\Omega) ,\,\theta=-\,\lambda\phi\},\]

(\(\Gamma\) has only one connected component since \(\Omega\) is convex) and we know from Lemma III.2.1 that \(T\in\mathcal{L}(Y;V)\).

The nonlinearity is expressed much like in (4.31):

(5.6) \[G(u)=\omega\operatorname{\mathbf{grad}}\psi-\mathbf{f}\quad\quad u=( \operatorname{\mathbf{curl}}\psi,\omega)\in X.\]

Then the Navier-Stokes problem is stated like in (4.32):

_For \(\mathbf{f}\) in \(L^{r}(\Omega)^{2}\) find \(u=(\operatorname{\mathbf{curl}}\psi,\omega)\in X\) such that_:

(5.7) \[\begin{cases}v(\operatorname{\mathbf{curl}}\omega,\operatorname{\mathbf{ curl}}\phi)+(\omega\operatorname{\mathbf{grad}}\psi,\operatorname{\mathbf{ curl}}\phi)=(\mathbf{f},\operatorname{\mathbf{curl}}\phi)\quad\quad \forall\phi\in\Phi_{s},\\ (\operatorname{\mathbf{curl}}\psi,\operatorname{\mathbf{curl}}\mu)=(\omega, \mu)\quad\quad\forall\mu\in W^{1,\,r}(\Omega),\end{cases}\]

where \(\psi\) and \(\omega\) are related to \(\mathbf{u}\) by (5.4). With \(T\) and \(G\) defined above and \(\lambda=1/v\), this has the compact expression:

(5.8) \[\overset{\cdot}{F}(\lambda,u)\equiv u+\lambda TG(u)=0.\]

For the purpose of the approximation, we introduce the first two finite-dimensional spaces \(\Theta_{h}\) and \(\Phi_{h}\) defined by (4.34):

\[\Theta_{h}=\{\theta_{h}\in\mathcal{C}^{0}(\bar{\Omega});\,\theta_{h}|_{x}\in P _{t}\quad\forall\kappa\in\mathcal{T}_{h}\},\quad\ \Phi_{h}=\Theta_{h}\cap H^{1}_{0}(\Omega),\]

where \(\mathcal{T}_{h}\) is a triangulation of \(\bar{\Omega}\) and the integer \(l\geqslant 1\). Naturally we take

\[X_{h}=\{\operatorname{\mathbf{curl}}\phi_{h};\,\phi_{h}\in\Phi_{h}\}\,\times\, \Theta_{h}\subset X\]
