_Remark 4.1_.: Most technical details in the proof of Theorem 4.2 have already been used by Bercovier & Pironneau [7] in establishing a weak form of the inf-sup condition (4.9). Albeit simple, the above proof is long because it deals with a reference region composed of several reference triangles instead of a single one. The crucial point in the proof is the particular choice of \(\mathbf{v}\) at the midpoint of the interior segments. Apart from that, the major steps are essentially the same as those used in proving Theorem 2.2.

With Theorem 4.2 and its corollary we readily derive the major result of this section.

**Theorem 4.3**.: _Let \(\Omega\) be a bounded, plane polygon and let the solution \((\mathbf{u},p)\) of the Stokes system (4.1) satisfy_

\[\mathbf{u}\in[H^{k+1}(\Omega)\cap H^{1}_{0}(\Omega)]^{2},\quad\ p\in H^{k}( \Omega)\cap L^{2}_{0}(\Omega),\quad\ k=1\ \text{or}\ 2.\]

_If the triangulation \(\mathcal{T}_{h}\) is regular and like in (4.17), the solution \((\mathbf{u}_{h},p_{h})\) of Problem (4.5) with spaces \(X_{h}\) and \(M_{h}\) defined by (4.15) (4.4) satisfies the estimate:_

(4.27) \[|\mathbf{u}-\mathbf{u}_{h}|_{1,\,\Omega}+\|p-p_{h}\|_{0,\,\Omega}\leqslant C_ {1}h^{k}\{|\mathbf{u}|_{k+1,\,\Omega}+|p|_{k,\,\Omega}\},\quad\ k=1\ \text{or}\ 2.\]

_When \(\Omega\) is convex, this can be refined:_

(4.28) \[\|\mathbf{u}-\mathbf{u}_{h}\|_{0,\,\Omega}\leqslant C_{2}h^{k+1}\{|\mathbf{u }|_{k+1,\,\Omega}+|p|_{k,\,\Omega}\}.\]

_Furthermore, if \(\mathcal{T}_{h}\) is uniformly regular (but \(\Omega\) not necessarily convex) we also have:_

(4.29) \[|p-p_{h}|_{1,\,\Omega}\leqslant C_{3}h^{k-1}\{|\mathbf{u}|_{k+1,\,\Omega}+|p| _{k,\,\Omega}\}.\]

_Remark 4.2_.: In order to establish (4.29) we can apply Corollary 4.1 and switch from \(\|p_{h}-q_{h}\|_{0,\,\Omega}\) to \(|p_{h}-q_{h}|_{1,\,\Omega}\) by Corollary A.3 (this is where the uniformity of \(\mathcal{T}_{h}\) steps in).

_Remark 4.3_.: Obviously, Remark 2.6 is also valid here.

We finish this section with a quick study of a popular variant of the Hood-Taylor method. Again, let \(\mathcal{T}_{h}\) be a regular triangulation of \(\Omega\) that satisfies (4.17) and let us divide each of its triangles \(\kappa\) into four equal triangles \(\tilde{\kappa}\) by joining the midpoints of the sides (cf. Figure 19). For the pressure, we retain the spaces \(Q_{h}\) and \(M_{h}\) defined by (4.4) and we replace the velocity space \(X_{h}\) by:

(4.30) \[\begin{split} X_{h}=\{\mathbf{v}\in\mathcal{C}^{0}(\Omega)^{2}; \,\mathbf{v}\in P_{1}^{2}\ \text{on each subtriangle }\tilde{\kappa}\ \text{of}\ \kappa\ \ \ \forall\kappa\in\mathcal{T}_{h},\\ \mathbf{v}|_{\,\Gamma}=\mathbf{0}\}.\end{split}\]

The approximation properties of \(Q_{h}\) and \(M_{h}\) are unchanged while the approximation properties of \(X_{h}\) correspond to polynomials of \(P_{1}\), i.e. we have:

(4.31) \[\|\mathbf{v}-I_{h}\mathbf{v}\|_{m,\,\Omega}\leqslant Ch^{2-m}|\mathbf{v}|_{2, \,\Omega}\ \ \ \ \ \forall v\in H^{2}(\Omega)^{2},\quad\ m=0\ \text{or}\ 1\]
