\[W_{0h}=W_{h}\cap H^{1}_{0}(\Omega)^{N},\ \ \ \ \ M_{h}=Q_{h}\cap L^{2}_{0}(\Omega).\]

As usual, \(\Omega\) is a bounded, connected, open subset of \(\mathbb{R}^{N}\) with a Lipschitz-continuous boundary \(\Gamma\).

With the above spaces, the homogeneous Navier-Stokes Problem:

_Given \(\mathbf{f}\) in \(H^{-1}(\Omega)^{N},\) find \((\mathbf{u},p)\) in \(H^{1}_{0}(\Omega)^{N}\times L^{2}_{0}(\Omega)\) satisfying_:

(4.1) \[\begin{cases}a(\mathbf{u};\mathbf{u},\mathbf{v})-(p,\operatorname{div}\mathbf{ v})=\langle\mathbf{f},\mathbf{v}\rangle\ \ \ \ \ \forall\mathbf{v}\in H^{1}_{0}(\Omega)^{N},\\ \operatorname{div}\mathbf{u}=0\ \ \ \text{ in }\Omega\end{cases}\]

is discretized by the following _Problem_ (Q\({}_{h}\))

_Find \((\mathbf{u}_{h},p_{h})\in W_{0h}\times M_{h}\) solution of_

(4.2) \[\begin{cases}a(\mathbf{u}_{h};\mathbf{u}_{h},\mathbf{v}_{h})-(p_{h}, \operatorname{div}\mathbf{v}_{h})=\langle\mathbf{f},\mathbf{v}_{h}\rangle \ \ \ \ \forall\mathbf{v}_{h}\in W_{0h},\\ (q_{h},\operatorname{div}\mathbf{u}_{h})=0\ \ \ \ \ \forall q_{h}\in M_{h}.\end{cases}\]

Recall the three hypotheses introduced in Section II.1.3 and related to the approximation of the Stokes system:

**Hypothesis H1** (Approximation property of \(W_{0h}\)).: _There exist an operator \(r_{h}\in\mathcal{L}([H^{2}(\Omega)\cap H^{1}_{0}(\Omega)]^{N};W_{0h})\) and an integer \(l\) such that_:

(4.3) \[\|\,\mathbf{v}-r_{h}\mathbf{v}\|_{{}_{1,\Omega}}\leqslant Ch^{m}\|\,\mathbf{ v}\|_{{}_{m+1,\Omega}}\ \ \ \ \ \forall\mathbf{v}\in H^{m+1}(\Omega)^{N},\ \ \ \ 1\leqslant m \leqslant l.\]

**Hypothesis H2** (Approximation property of Q\({}_{h}\)).: _There exists an operator \(s_{h}\in\mathcal{L}(L^{2}(\Omega);Q_{h})\) such that:_

(4.4) \[\|\,q-s_{h}q\|_{{}_{0,\Omega}}\leqslant Ch^{m}\|\,q\|_{{}_{m,\Omega}}\ \ \ \ \ \forall q\in H^{m}(\Omega),\ \ \ \ 0\leqslant m \leqslant l.\]

**Hypothesis H3** (Uniform inf-sup condition).: _For each \(q_{h}\in M_{h}\) there exists a \(\mathbf{v}_{h}\in W_{0h}\) such that:_

(4.5) \[(q_{h},\operatorname{div}\mathbf{v}_{h})=\|\,q_{h}\|^{2}_{0,\Omega},\ \ \ \ \ | \mathbf{v}_{h}|_{{}_{1,\Omega}}\leqslant C\|\,q_{h}\|_{{}_{0,\Omega}},\]

_with a constant \(C>0\) independent of \(h,\,q_{h}\) and \(\mathbf{v}_{h}\)._

In view of these assumptions, let us apply the material of Section 3.3.

**Theorem 4.1**.: _Suppose \(N\leqslant 3\) and assume that the hypotheses H1, H2 and H3 hold. Let \(\{(\lambda,(\mathbf{u}(\lambda),\lambda p(\lambda)));\lambda=1/v\in\Lambda\}\) be a branch of nonsingular solutions of the Navier-Stokes Problem_ (4.1).: _Then there exists a neighborhood \(\mathcal{C}\) of the origin in \(H^{1}_{0}(\Omega)^{N}\times L^{2}_{0}(\Omega)\) and for \(h\leqslant h_{0}\) sufficiently small a unique \(\mathcal{C}^{\infty}\) branch \(\{(\lambda,(\mathbf{u}_{h}(\lambda),\allowbreak\lambda p_{h}(\lambda))); \lambda\in\Lambda\}\) of nonsingular solutions of Problem_ (4.2) _such that:_

\[(\mathbf{u}_{h}(\lambda),\lambda p_{h}(\lambda))\in(\mathbf{u}(\lambda), \lambda p(\lambda))+\mathcal{C}\ \ \ \ \ \forall\lambda\in\Lambda.\]

_Moreover, we have the convergence property_:

(4.6) \[\limsup_{h\to 0}\,\{|\,\mathbf{u}_{h}(\lambda)-\mathbf{u}(\lambda)|_{{}_{1, \Omega}}+\|\,p_{h}(\lambda)-p(\lambda)\|_{{}_{0,\Omega}}\}=0.\]
