Thus \(L^{2}_{0}(\Omega)\) can be identified isometrically with \(L^{2}(\Omega)/\mathbb{R}\). The next corollary states further that the range space of \(\operatorname{div}\) is exactly \(L^{2}_{0}(\Omega)\).

**Corollary 2.4**.: _Let \(\Omega\) be connected. Then_

\(1^{\circ})\) _the operator_ **grad** _is an isomorphism of \(L^{2}_{0}(\Omega)\) onto \(V^{0}\)_;

\(2^{\circ})\) _the operator \(\operatorname{div}\) is an isomorphism of \(V^{\perp}\) onto \(L^{2}_{0}(\Omega)\)._

Proof.: \(1^{\circ})\) We know that \(\textbf{grad}\in\mathcal{L}(L^{2}_{0}(\Omega);V^{0})\); furthermore Lemma 2.1 asserts that this mapping is a bijection. As \(V^{0}\) and \(L^{2}_{0}(\Omega)\) are both Banach spaces, it follows that **grad** is an isomorphism.

\(2^{\circ})\) By virtue of \(1^{\circ})\), and since \(\operatorname{div}\) is the dual operator of \(-\textbf{grad}\), we have that \(\operatorname{div}\) is an isomorphism from \((V^{0})^{\prime}\) onto \((L^{2}_{0}(\Omega))^{\prime}\). Now, it suffices to prove that \(V^{0}\) can be identified with \((V^{\perp})^{\prime}\). Let \(\mathbf{g}\) be any element of \((V^{\perp})^{\prime}\) and let us extend \(\mathbf{g}\) to \(H^{1}_{0}(\Omega)^{N}\) by setting:

\[\langle\mathbf{\tilde{g}},\mathbf{v}\rangle=\langle\mathbf{g},\mathbf{v}^{ \perp}\rangle\ \ \ \ \ \forall\mathbf{v}\in H^{1}_{0}(\Omega)^{N},\]

where \(\mathbf{v}^{\perp}\) denotes the orthogonal projection of \(\mathbf{v}\) on \(V^{\perp}\). Clearly, \(\mathbf{\tilde{g}}\in V^{0}\) and the linear mapping \(\mathbf{g}\to\mathbf{\tilde{g}}\) maps isometrically \((V^{\perp})^{\prime}\) onto \(V^{0}\). This permits to identify \((V^{\perp})^{\prime}\) and \(V^{0}\). 

_Remark 2.1_.: The proof of Corollary 2.4\(2^{\circ})\) is valid in abstract situations (cf. Lemma 4.1).

Again, let \(\mathbf{n}\) denote the unit exterior normal to \(\Gamma\). The following lemma gives a lifting operator of boundary values by means of divergence-free functions.

**Lemma 2.2**.: _Let \(\Omega\) be connected. For each \(\mathbf{g}\in H^{1/2}(\Gamma)^{N}\) satisfying \(\int_{\Gamma}\mathbf{g}\cdot\mathbf{n}\,ds=0\) there exists a function \(\mathbf{u}\in H^{1}(\Omega)^{N}\), unique up to an additive function of \(V\), such that_

\[\operatorname{div}\mathbf{u}=0\ \ \ \text{in}\ \Omega,\ \ \ \ \ \mathbf{u}=\mathbf{g}\ \ \ \text{on}\ \Gamma.\]

_Moreover, we have_

(2.12) \[\inf_{\mathbf{v}\in V}\|\mathbf{u}+\mathbf{v}\|_{1,\Omega}\leq C\|\mathbf{g} \|_{1/2,\Gamma},\]

_where the constant \(C>0\) is independent of \(\mathbf{u}\) and \(\mathbf{g}\)._

Proof.: Obviously such a function \(\mathbf{u}\) must be unique in \([H^{1}(\Omega)^{N}]/V\). Let us check its existence. Let \(\mathbf{w}\) be any function of \(H^{1}(\Omega)^{N}\) that satisfies \(\mathbf{w}=\mathbf{g}\) on \(\Gamma\). Then Green's formula (1.19) gives:

\[\int_{\Omega}\operatorname{div}\mathbf{w}\,dx=\int_{\Gamma}\mathbf{g}\cdot \mathbf{n}\,ds=0.\]

Therefore \(\operatorname{div}\mathbf{w}\in L^{2}_{0}(\Omega)\) and owing to Corollary 2.4\(2^{\circ})\) there exists a unique \(\mathbf{v}\) in \(V^{\perp}\) such that

\[\operatorname{div}\mathbf{v}=\operatorname{div}\mathbf{w},\]
