Now that we know that \(\operatorname{Ker}(A)\) is a finite-dimensional subspace of \(E_{1}\), we can introduce the quotient space:

\[X=E_{1}/\operatorname{Ker}(A)\]

which is a Banach space for the familiar quotient norm:

\[\left\|\dot{u}\right\|_{X}=\inf_{u\in\dot{u}}\left\|u\right\|_{E_{1}}.\]

In addition, because \(\operatorname{Ker}(A)\) is finite-dimensional, the above infimum is attained, i.e. each class \(\dot{u}\) has a representative \(\tilde{u}\) such that

\[\left\|\dot{u}\right\|_{X}=\left\|\tilde{u}\right\|_{E_{1}}\quad\quad\forall \dot{u}\in X.\]

As \(A\) is a linear, continuous and one-to-one mapping from \(X\) onto \(\mathcal{R}(A)\), to establish the announced isomorphism it suffices to prove that \(A\) has a continuous inverse, i.e. there exists a constant \(C>0\) such that:

\[\left\|\dot{u}\right\|_{X}\leqslant C\left\|A\dot{u}\right\|_{E_{2}}\quad\quad \forall\dot{u}\in X.\] (2.5)

This is achieved by contradiction: assume that there exists a sequence \((\dot{u}_{n})\) in \(X\) such that

\[\left\|\dot{u}_{n}\right\|_{X}=1\quad\text{and}\quad\lim_{n\to\infty}A\dot{u} _{n}=0\quad\text{in }E_{2}.\]

Hence

\[\left\|\tilde{u}_{n}\right\|_{E_{1}}=1\quad\text{and}\quad\lim_{n\to\infty} \left\|A\tilde{u}_{n}\right\|_{E_{2}}=0.\]

Therefore, we can extract a subsequence \((\tilde{u}_{n})\) such that \((B\tilde{u}_{n})\) converges in \(E_{3}\). Then (2.1) implies that \((\tilde{u}_{n})\) is a Cauchy sequence in \(E_{1}\). Thus, there exists \(u\) in \(\operatorname{Ker}(A)\) such that \(\lim\tilde{u}_{n}=u\) in \(E_{1}\). This implies that \(\dot{u}_{n}\to 0\) which contradicts our hypothesis.

Finally, since \(A\) is an isomorphism from \(X\) onto \(\mathcal{R}(A)\) and since \(X\) is a Banach space, it follows immediately that \(\mathcal{R}(A)\) is also a Banach space. Therefore \(\mathcal{R}(A)\) is a closed subspace of \(E_{2}\).

\(2^{\circ})\) Since \(L\) vanishes on \(\operatorname{Ker}(A)\), we can write

\[Lu=L\dot{u}=LA^{-1}Au\quad\quad\forall u\in E_{1}.\]

Therefore

\[\left\|Lu\right\|_{F}\leqslant\left\|L\right\|_{\mathcal{L}(E_{1};F)}\left\|A ^{-1}\right\|_{\mathcal{L}(\tilde{\mathcal{R}}(A);X)}\left\|Au\right\|_{E_{2}} \quad\quad\forall u\in E_{1},\]

thus yielding (2.2) with \(C_{0}=\left\|A^{-1}\right\|_{\mathcal{L}(\mathcal{R}(A);X)}\).

\(3^{\circ})\) Finally, let us prove that there exists a constant \(C>0\) such that

\[\left\|Au\right\|_{E_{2}}+\left\|Mu\right\|_{G}\geqslant C\left\|u\right\|_{E _{1}}\quad\quad\forall u\in E_{1}.\]

Again, we proceed by contradiction. Let \((u_{n})\) be a sequence in \(E_{1}\) such that

\[\lim_{n\to\infty}\left(\left\|Au_{n}\right\|_{E_{2}}+\left\|Mu_{n}\right\|_{G} \right)=0\quad\text{and}\quad\left\|u_{n}\right\|_{E_{1}}=1.\]
