\[\langle\operatorname{div}\tilde{\mathbf{v}},\phi\rangle=-\langle\mathbf{v}\cdot \mathbf{n},\phi\rangle_{\Gamma}-\sum_{i=0}^{p}\,\langle\mathbf{v}\cdot\mathbf{n },\phi\rangle_{\Gamma_{i}}.\]

In the above sum, the normal to \(\Gamma_{i}\) is directed outside \(\Omega_{i}\) and therefore inside \(\Omega\); hence each term of this sum cancels a term of \(\langle\mathbf{v}\cdot\mathbf{n},\phi\rangle_{\Gamma}\). Therefore

\[\langle\operatorname{div}\tilde{\mathbf{v}},\phi\rangle=0\quad\quad\forall \phi\in\mathcal{D}(\mathbb{R}^{2}),\]

i.e.

\[\operatorname{div}\tilde{\mathbf{v}}=0.\]

c) As the support of \(\tilde{\mathbf{v}}\) is compact, it follows that its Fourier transform \(\mathcal{F}\tilde{\mathbf{v}}\) defined by (2.23) is a holomorphic function of \(\mu\). In terms of Fourier transforms, the conditions \(\operatorname{div}\tilde{\mathbf{v}}=0\) and \(\tilde{\mathbf{v}}=\operatorname{\mathbf{curl}}\phi\) read:

(3.4) \[\mu_{1}\mathcal{F}\tilde{v}_{1}+\mu_{2}\mathcal{F}\tilde{v}_{2}=0,\] (3.5) \[\mathcal{F}\tilde{v}_{1}=2i\pi\mu_{2}\mathcal{F}\phi,\quad\ \mathcal{F}\tilde{v}_{2}=-2i\pi\mu_{1}\mathcal{F}\phi.\]

If we take \(\mathcal{F}\phi=\mathcal{F}\tilde{v}_{1}/(2i\pi\mu_{2})\) then thanks to (3.4), both equalities of (3.5) are valid, i.e.

\[\mathcal{F}\phi=\mathcal{F}\tilde{v}_{1}/(2i\pi\mu_{2})=-\mathcal{F}\tilde{v} _{2}/(2i\pi\mu_{1}).\]

Therefore the inverse transform of \(\mathcal{F}\phi\) is the required stream function of \(\tilde{\mathbf{v}}\), provided \(\mathcal{F}\phi\in L^{2}(\mathbb{R}^{2})\). But since \(\mathcal{F}\tilde{v}_{j}\in L^{2}(\mathbb{R}^{2})\), it suffices to show that \(\mathcal{F}\phi\) is bounded in a neighborhood of the origin.

According to (3.4), we have \(\mathcal{F}\tilde{v}_{1}(\mu_{1},0)=0\). Hence, using the holomorphy of \(\mathcal{F}\tilde{v}_{1}\), we obtain

\[\mathcal{F}\tilde{v}_{1}(\mu_{1},\mu_{2})=\mu_{2}(\partial\mathcal{F}\tilde{ v}_{1}(\mu_{1},0)/\partial\mu_{2})+O(|\mu_{2}|^{2})\]

so that

\[\mathcal{F}\phi(\mu_{1},\mu_{2})=[1/(2i\pi)](\partial\mathcal{F}\tilde{v}_{1 }(\mu_{1},0)/\partial\mu_{2})+O(|\mu_{2}|).\]

Clearly, this implies that \(\mathcal{F}\phi\) is bounded in a neighborhood of zero. 

An immediate consequence of this theorem is that when \(\mathbf{v}\) belongs to \(L^{s}(\Omega)^{2}\) for some real \(s\geqslant 2\) (resp. \(H^{m}(\Omega)^{2}\) for some integer \(m\geqslant 0\)) and \(\mathbf{v}\) satisfies \(\operatorname{div}\mathbf{v}=0\), \(\langle\mathbf{v}\cdot\mathbf{n},1\rangle_{\Gamma_{i}}=0\) for \(0\leqslant i\leqslant p\), then

\[\mathbf{v}=\operatorname{\mathbf{curl}}\phi\quad\text{with }\phi\in W^{1,s}( \Omega)\quad\text{(resp. }\phi\in H^{m+1}(\Omega)).\]

Note that, since \(\Omega\) is connected, the stream function \(\phi\) of \(\mathbf{v}\) is unique up to an additive constant. In particular, when \(\mathbf{v}\in H\), its stream function \(\phi\) satisfies \((\partial\phi/\partial\tau)|_{\Gamma_{i}}=0\), that is

\[\phi|_{\Gamma_{i}}=\text{a constant }c_{i},\ \ \text{ for }0\leqslant i \leqslant p.\]

Therefore, \(\phi\) is uniquely determined if we fix one of these constants. For example, \(\mathbf{v}\) has one and only one stream function \(\phi\) that _vanishes_ on \(\Gamma_{0}\). This function belongs to the space
