\(b(.,.)\) satisfies the _inf-sup_ condition (4.9) and that the bilinear form \(a(.,.)\) is _symmetric_ and \(X\)_-elliptic_ in the sense of (4.21). Then according to Corollary 4.1, Problem (Q) is well-posed and Theorem 4.2 claims that its unique solution \((u,\lambda)\) is characterized as the unique saddle-point of the Lagrangean functional \(\mathcal{L}(v,\mu)\) defined by (4.14). Furthermore, \(u\) is the unique solution of the _constrained_ optimization problem (4.20) while \(\lambda\) is the unique solution of the _unconstrained_ optimization problem (4.24). It appears clearly that this last problem is the easiest to solve and that methods of descent should be particularly well-adapted to its solution. Here we shall concentrate on a general descent algorithm and apply it to two classes of gradient methods: the _simple gradient_ (also called _Uzawa's Algorithm_) and the _conjugate-gradient_ methods.

Keeping in mind the above considerations, let us first generalize Theorem 4.2 and show that \((u,\lambda)\) can be characterized as the unique saddle-point of a parametrized family of Lagrangean functionals. Following the preceding section, we introduce a continuous, bilinear form \(c(.,.)\colon M\times M\to\mathbb{R}\), _\(M\)-elliptic_ in the sense of (4.25) and _symmetric_. Likewise, we define by (4.26) the corresponding operator \(C\in\mathcal{L}(M;M^{\prime})\). Now, for all \(r\geq 0\) we introduce the _augmented energy functional_\(J_{r}\colon X\to\mathbb{R}\) and the _augmented Lagrangean functional_\(\mathcal{L}_{r}\colon X\times M\to\mathbb{R}\) defined respectively by:

\[J_{r}(v)=J(v)+(r/2)\langle C^{-1}(Bv-\chi),Bv-\chi\rangle,\] (4.41) \[\mathcal{L}_{r}(v,\mu)=J_{r}(v)+b(v,\mu)-\langle\chi,\mu\rangle.\] (4.42)

Since

\[J_{r}(v)=J(v)\ \ \ \ \ \forall v\in V(\chi),\]

\(u\) is still characterized by:

\[J_{r}(u)=\inf_{v\in V(\chi)}J_{r}(v).\] (4.43)

On the other hand, we have the following result.

**Theorem 4.5**.: _Suppose that (4.9), (4.12) and (4.25) hold and in addition assume that the bilinear forms \(a(.,.)\) and \(c(.,.)\) are symmetric with_

\[a(v,v)+r\langle C^{-1}Bv,Bv\rangle\geq 0\ \ \ \ \ \forall v\in X.\] (4.44)

_Then the solution \((u,\lambda)\) of Problem_ (Q) _is the unique saddle-point of the augmented Lagrangean functional \(\mathcal{L}_{r}\), or equivalently is characterized by:_

\[\operatorname*{Min}_{v\in X}\biggl{(}\sup_{\mu\in M}\mathcal{L}_{r}(v,\mu) \biggr{)}=\mathcal{L}_{r}(u,\lambda)=\operatorname*{Max}_{\mu\in M}\biggl{(} \inf_{v\in X}\mathcal{L}_{r}(v,\mu)\biggr{)}.\] (4.45)

_Proof_. Taking into account the symmetry of \(a(.,.)\) and \(c(.,.)\) we get:

\[D_{v}\mathcal{L}_{r}(u,\lambda)\cdot v=a(u,v)-\langle l,v\rangle+r\langle C^ {-1}(Bu-\chi),Bv\rangle+b(v,\lambda),\]

\[D_{v}^{2}\mathcal{L}_{r}(u,\lambda)\cdot(v,v)=a(v,v)+r\langle C^{-1}Bv,Bv\rangle.\]

Then the proof follows the lines of Theorem 4.2 and Corollary 4.2.
