study here contributions by Bernardi & Raugel [10], Fortin [30], Johnson & Pitkaranta [46], Mansfield [56] and Boland & Nicolaides [12].

The situation and notations are those of Section 1.3.

### A First Order Approximation on Triangular Elements

Throughout this section, we assume that \(\Omega\) is a _bounded polygon_ in \(\mathbb{R}^{2}\) so that it can be entirely triangulated. For each \(h>0\), \(\mathcal{T}_{h}\) is a triangulation of \(\Omega\) made of triangles \(\kappa\) with diameters bound by \(h\):

\[\bar{\Omega}=\bigcup_{\kappa\in\mathcal{T}_{h}}\kappa.\]

By now, the reader is well aware that the choice of compatible spaces \(X_{h}\) and \(M_{h}\), whatever their accuracy, is crucial for the success of the approximation. For example, the most straightforward choice of first-order spaces is:

\[W_{h}=\{w\!\in\!\mathcal{C}^{0}(\bar{\Omega})^{2};\,w|_{\kappa}\!\in\!P_{1}^{ 2}\quad\forall\kappa\!\in\!\mathcal{T}_{h}\},\]

\[X_{h}=W_{h}\cap H_{0}^{1}(\Omega)^{2},\]

\[Q_{h}=\{q\!\in\!L^{2}(\Omega);\,q|_{\kappa}\!\in\!P_{0}\quad\forall\kappa\! \in\!\mathcal{T}_{h}\},\]

\[M_{h}=Q_{h}\cap L_{0}^{2}(\Omega).\]

But, more often than not, this choice leads to \(V_{h}=\{0\}\) as can be checked in the simple example of Figure 7. Here, \(X_{h}\) has only two degrees of freedom, while the definition of \(V_{h}\) requires five independent conditions. Hence, \(V_{h}=\{0\}\).



This example illustrates the fact that the space \(W_{h}\) needs more degrees of freedom in order to generate a sufficiently large space \(V_{h}\). Fortin [29] suggested first to take piecewise polynomials of degree two for the functions of \(W_{h}\). For a

Figure 7: Example of incompatible pair of spaces \((X_{h},M_{h})\)
