Now we turn to the _second-order scheme_. As expected we wish to construct a velocity vector \(\mathbf{w}\), with quadratic tangential components on the boundary of \(\kappa\), which is compatible with affine pressures in \(\kappa\). In the light of the corresponding scheme in \(\mathbb{R}^{2}\), one is tempted to take \(\mathbf{w}\) in the space \(\{P_{2}\oplus(\lambda_{1}\lambda_{2}\lambda_{3}\lambda_{4}P_{0})\}^{3}\). Unfortunately, this space's dimension is too small to meet the requirements of the inf-sup condition with affine pressures. Following Fortin [30] and Bernardi & Raugel [10], the best we can do is add to this space the cubics \(\mathbf{p}_{i}\) of (2.30); thus we shall take \(\mathbf{w}\) in the subspace of \(P_{4}^{3}\):

(2.38) \[\mathcal{P}_{2}(\kappa)=\{P_{2}\oplus(\lambda_{1}\lambda_{2}\lambda_{3} \lambda_{4}P_{0})\}^{3}\oplus\operatorname{span}\{\mathbf{p}_{1},\mathbf{p}_{ 2},\mathbf{p}_{3},\mathbf{p}_{4}\}.\]

Right away, observe that \(\mathcal{P}_{1}(\kappa)\subset\mathcal{P}_{2}(\kappa)\); therefore we can try as much as possible to apply the material of Section 1.4 in order to establish the inf-sup condition. This means that the inf-sup condition imposes no constraint on the degrees of freedom of the velocity \(\mathbf{w}\) and thus we can choose the most convenient ones. Now, the degrees of freedom naturally attached to \(P_{2}\) are:

\[w(a_{i})\quad 1\leqslant i\leqslant 4\quad\text{and}\quad w(a_{ij})\quad\text{ where }a_{ij}\text{ is the midpoint of }e_{ij},\quad 1\leqslant i<j\leqslant 4;\]

those corresponding to \(\{\mathbf{p}_{i};1\leqslant i\leqslant 4\}\) are:

\[\int_{F_{i}}\mathbf{w}\cdot\mathbf{n}_{i}\,ds\quad\quad 1\leqslant i\leqslant 4,\]

and the simplest one corresponding to the "bubble function" \(\lambda_{1}\lambda_{2}\lambda_{3}\lambda_{4}\) is

\[w(a_{\kappa})\quad\text{where }a_{\kappa}\text{ is the center of }\kappa.\]

The next lemma shows that this set of moments is \(\mathcal{P}_{2}(\kappa)\)-unisolvent.

**Lemma 2.9**.: _A polynomial \(\mathbf{p}\) of \(\mathcal{P}_{2}(\kappa)\) is uniquely determined by the 37 values:_

(2.39) \[\begin{cases}\mathbf{p}(a_{i})&1\leqslant i\leqslant 4,\quad\mathbf{p}(a_{ij}) \quad 1\leqslant i<j\leqslant 4,\quad\mathbf{p}(a_{\kappa}),\\ &\quad\quad\quad\int_{F_{i}}\mathbf{p}\cdot\mathbf{n}_{i}\,ds\quad\quad 1 \leqslant i\leqslant 4.\end{cases}\]

_Moreover the restriction of \(\mathbf{p}\) to any face \(F_{i}\) of \(\kappa\) depends exclusively upon its degrees of freedom on that face._

Proof.: A polynomial of \(\mathcal{P}_{2}(\kappa)\) has 37 coefficients which is precisely the number of degrees of freedom defined by (2.39). Therefore it suffices to prove that zero moments generate only the zero polynomial. Now, on any edge \(e_{ij}\) a component \(p\) of \(\mathbf{p}\) reduces to a quadratic function of one variable. Therefore \(p(a_{i})=p(a_{j})=p(a_{ij})=0\) imply that \(p|_{e_{ij}}=0\). Thus if the degrees of freedom of \(\mathbf{p}\) vanish on the boundary of any face \(F_{i}\) then necessarily \(\mathbf{p}|_{F_{i}}=c\,\mathbf{p}_{i}\) and if \(\int_{F_{i}}\mathbf{p}\cdot\mathbf{n}_{i}\,ds=0\) then \(c=0\).

Finally, if \(\mathbf{p}|_{\partial\kappa}=\mathbf{0}\) then each component \(p\) of \(\mathbf{p}\) is a "bubble function" and therefore \(p(a_{\kappa})=0\) implies that \(p=0\) on \(\kappa\)
