**Theorem 1.2**.: _Let \(\Omega\) be an open Lipschitz-continuous subset of \(\mathbb{R}^{N}\)._

\(1^{\circ})\) _The space \(\mathcal{D}(\bar{\Omega})\) is dense in \(W^{m,\,p}(\Omega)\) for all integers \(m\geqslant 0\) and real \(p\) with \(1\leqslant p<\infty\)._

\(2^{\circ})\) _Let \(u\!\in\!W^{m,\,p}(\Omega)\) and let \(\tilde{u}\) denote its extension by zero outside \(\Omega\). If \(\tilde{u}\!\in\!W^{m,\,p}(\mathbb{R}^{N})\) then \(u\!\in\!W^{m,\,p}_{0}(\Omega)\)._

\(3^{\circ})\) _If in addition \(\Gamma\) is bounded and \(m\!\geqslant\!1\), there exists a continuous linear extension operator \(P\) from \(W^{m,\,p}(\Omega)\) into \(W^{m,\,p}(\mathbb{R}^{N})\)_:

\[Pu|_{\Omega}=u\ \ \ \ \ \forall u\!\in\!W^{m,\,p}(\Omega).\]

We now come to the fundamental Sobolev Imbedding Theorem which essentially relates different Sobolev spaces and spaces of smooth functions.

**Theorem 1.3**.: _Let \(\Omega\) be an open Lipschitz-continuous subset of \(\mathbb{R}^{N}\) and let \(p\!\in\!\mathbb{R}\) with \(1\!\leqslant\!p<\infty\) and \(m\) and \(n\!\in\!\mathbb{N}\) with \(n\!\leqslant\!m\). The following imbeddings hold algebraically and topologically:_

(1.7) \[W^{m,\,p}(\Omega)\subset\begin{cases}W^{n,\,q}(\Omega)&\text{if }1/q=1/p-(m-n)/N>0,\\ W^{n,\,q}_{\rm loc}(\Omega)&\forall q\!\in\![1,\,\infty)\text{ if }1/p=(m-n)/N,\\ \mathcal{C}^{n}(\Omega)&\text{provided }1/p<(m-n)/N.\end{cases}\]

_Moreover, if \(\Omega\) is bounded, the last inclusion holds in \(\mathcal{C}^{n}(\bar{\Omega})\) and the imbedding of \(W^{m,\,p}(\Omega)\) into \(W^{n,\,q}(\Omega)\) is compact for all real \(q^{\prime}\) that satisfy:_

(1.8) \[\text{or}\ \ \ \ \begin{cases}1\leqslant q^{\prime}<Np/(N-(m-n)p)\ \ \ \text{whenever }N>(m-n)p,\\ 1\leqslant q^{\prime}<\infty\ \ \ \text{ when }N=(m-n)p.\end{cases}\]

_In addition, these compact imbeddings are also valid for negative \(n\) or \(m\)._

This theorem will be used constantly in the sequel. For instance, in the next paragraph we shall use the fact that \(L^{2}(\Omega)\) is compactly imbedded in \(H^{-1}(\Omega)\). As an immediate application, we have the following corollary about multiplication in \(W^{m,\,p}(\Omega)\).

**Corollary 1.1**.: _Assume that \(\Omega\) is a bounded Lipschitz-continuous open subset of \(\mathbb{R}^{N}\). Let \(m_{1},\,m_{2}\) and \(m\) be three non negative integers and \(p_{1},\,p_{2}\) and \(p\) be three real numbers in \([1,\infty)\) such that \(m_{1}\geqslant m,\,m_{2}\geqslant m\) and either_

\[m_{1}+m_{2}-m\geqslant N(1/p_{1}+1/p_{2}-1/p)\geqslant 0,\ \ \ m_{i}-m>N(1/p_{i}-1/p)\ \ \ i=1,2\]

_or_

\[m_{1}+m_{2}-m>N(1/p_{1}+1/p_{2}-1/p)\geqslant 0,\ \ \ m_{i}-m\geqslant N(1/p_{i}-1/p)\ \ \ i=1,2.\]

_Then the mapping \(u,\,v\!\to\!u\!\cdot\!v\) is a continuous bilinear map from \(W^{m_{1},\,p_{1}}(\Omega)\!\times\!W^{m_{2},\,p_{2}}(\Omega)\) into \(W^{m,\,p}(\Omega)\)._
