one operator from \(M\) onto its range \(\mathcal{R}(B^{\prime})\) with a continuous inverse. Hence \(B^{\prime}\) is an isomorphism from \(M\) onto \(\mathcal{R}(B^{\prime})\) so that \(\mathcal{R}(B^{\prime})\) is a closed subspace of \(X^{\prime}\). Thus, we have only to prove that

\[\mathcal{R}(B^{\prime})=V^{0}.\]

For this we apply the Closed Range Theorem of Banach (cf. Yosida [84]) which asserts that

\[\mathcal{R}(B^{\prime})=(\operatorname{Ker}(B))^{0}=V^{0}.\]

This proves part \(1^{\circ}\)).

\(2^{\circ})\) We now show that properties (ii) and (iii) are equivalent. First, we observe that \(V^{0}\) may be isometrically identified with \((V^{\perp})^{\prime}\). Indeed, for \(v\in X\), let \(v^{\perp}\) denote the orthogonal projection of \(v\) onto \(V^{\perp}\). Then, with each \(g\in(V^{\perp})^{\prime}\), we associate the element \(\tilde{g}\in X^{\prime}\) defined by:

\[\langle\tilde{g},v\rangle=\langle g,v^{\perp}\rangle\ \ \ \ \ \forall v\in X.\]

Obviously, \(\tilde{g}\in V^{0}\) and it is easy to check that the correspondence \(g\to\tilde{g}\) is an isometric bijection from \((V^{\perp})^{\prime}\) onto \(V^{0}\). This enables us to identify \((V^{\perp})^{\prime}\) and \(V^{0}\).

As a consequence, we have that \(B\) is an isomorphism from \(V^{\perp}\) onto \(M^{\prime}\) with

\[\|B^{-1}\|_{\mathcal{L}(M^{\prime};V^{\perp})}\leqslant 1/\beta\]

if and only if \(B^{\prime}\) is an isomorphism from \(M\) onto \((V^{\perp})^{\prime}=V^{0}\) with

\[\|(B^{\prime})^{-1}\|_{\mathcal{L}(V^{0};M)}\leqslant 1/\beta.\]

Therefore, properties (ii) and (iii) are equivalent. 

The condition (4.9), usually called an "inf-sup condition", was introduced independently by Babuska [4] and Brezzi [13].

In order to state our main result, we introduce the linear continuous operator \(\pi\in\mathcal{L}(X^{\prime};V^{\prime})\) by:

\[\langle\pi f,v\rangle=\langle f,v\rangle\ \ \ \ \ \forall f\in X^{\prime},\ \ \ \ \ \forall v\in V.\]

Clearly, we have

\[\|\pi f\|_{V^{\prime}}\leqslant\|f\|_{X^{\prime}}.\]

**Theorem 4.1**.: _Problem_ (Q) _is well-posed_ (_i.e. the operator \(\Phi\) is an isomorphism from \(X\times M\) onto \(X^{\prime}\times M^{\prime}\)_) _if and only if the following conditions hold:_

(i) _the operator \(\pi A\) is an isomorphism from \(V\) onto \(V^{\prime}\)_;

(ii) _the bilinear form \(b(.,.)\) satisfies the inf-sup condition (4.9)._

Proof.: \(1^{\circ})\) The conditions (i) and (ii) are sufficient. It follows from (4.9) and Lemma 4.1 that there exists a unique element \(u_{0}\in V^{\perp}\) such that

\[\begin{cases}Bu_{0}=\gamma,\\ \|u_{0}\|_{X}\leqslant(1/\beta)\|\,\chi\|_{M^{\prime}}.\end{cases}\]
