the regularity of the triangulation guarantees that no subtriangle of \(\kappa\) has zero measure, i.e. \(\kappa\) does not degenerate into a triangle.

Next, we turn to the finite element spaces. It stems from the geometry of quadrilateals that the basis functions here are not polynomials of \(P_{k}\) but rather are images of polynomials of \(Q_{k}\). To be specific, for each integer \(k\geqslant 0\), and for each element \(\kappa\) of \(\mathcal{T}_{k}\), we introduce the finite-dimensional space:

\[Q_{k}(\kappa)=\{q=\hat{q}\circ F_{\kappa}^{-1};\,\hat{q}\!\in\!Q_{k}\}\] (A.40)

and observe that \(Q_{k}(\kappa)\subset\mathscr{C}^{\infty}(\kappa)\), but (unless \(\kappa\) is a parallelogram) \(Q_{k}(\kappa)\) is _not_ a space of polynomials. Then, in order to study the approximation error in such a space, we must modify slightly the statements of Theorem A.1 and its corollaries. This is achieved by a change of seminorm: for each integer \(k\geqslant 0\) and real \(p>0\), we set

\[[v]_{k,\,p,\Omega}=(\|\partial^{k}v/\partial x_{1}^{k}\|_{0,\,p,\Omega}^{p}+\| \partial^{k}v/\partial x_{2}^{k}\|_{0,\,p,\Omega}^{p})^{1/p}.\] (A.41)

Clearly, \([.]_{0,\,p,\Omega}=\|\,.\,\|_{0,\,p,\Omega}\) and \([.]_{1,\,p,\Omega}=|\,.\,|_{1.\,p,\Omega}\); in addition, this seminorm has the following important property proved by Aronszajn & Smith (cf. Smith [74]):

Let \(\Omega\) be a bounded domain of \(\mathbb{R}^{2}\) with a Lipschitz-continuous boundary. For each integer \(k\geqslant 0\) and real \(p>0\) there exists a positive constant \(C\) such that

\[\|v\|_{k,\,p,\Omega}\leqslant C\{\|v\|_{0,\,p,\Omega}+[v]_{k,\,p,\Omega}\} \quad\quad\forall v\!\in\!W^{k,\,p}(\Omega).\] (A.42)

Now, Theorem A.1 and its first corollary have the following counterpart:

Let \(k\geqslant 0\), \(m\geqslant 0\) be integers and \(p\geqslant 1\), \(q\geqslant 1\) be reals such that

\[W^{k+1,\,p}(\hat{\kappa})\subset W^{m,\,q}(\hat{\kappa}).\]

Let \(\hat{\pi}\!\in\!\mathscr{L}(W^{k+1,\,p}(\hat{\kappa});W^{m,\,q}(\hat{\kappa}))\) satisfy

\[\hat{\pi}t=t\quad\quad\forall t\!\in\!Q_{k}.\]

Then there exists a positive constant \(\hat{C}\) that depends only on \(k\), \(m\), \(p\), \(q\), \(\hat{\kappa}\) and \(\hat{\pi}\), such that

\[|\hat{\sigma}-\hat{\pi}\hat{\sigma}|_{m,\,q,\hat{\kappa}}\leqslant\hat{C}[\hat {\sigma}]_{k+1,\,p,\hat{\kappa}}\quad\quad\forall\hat{\sigma}\!\in\!W^{k+1,\,p }(\hat{\kappa}).\] (A.43)

Thus, in order to estimate the interpolation error in \(Q_{k}(\kappa)\), we must derive an upper bound for \(|v|_{m,\,q,\kappa}\) in terms of \(\hat{\sigma}\) and for \([\hat{\sigma}]_{k+1,\,p,\hat{\kappa}}\) in terms of \(v\). This is the object of the next lemma (compare with Lemma A.1). The material for the proof can be found in Cartan [17].

Let \(\kappa\) be a convex quadrilateral. For each integer \(m\geqslant 0\) and real \(p\!\in\![1,\infty]\) there exist positive constants \(C_{1}\), \(C_{2}\) and \(C_{3}\) independent of the geometry
