\[\Phi=\sum_{i=1}^{l}\alpha_{i}\Phi\quad\text{in }\Omega\]

and therefore the problem reduces to the regularity of \(\alpha_{i}\Phi\). Note that, since \(\Gamma\) is smooth and \(\alpha_{i}\in\mathcal{D}(\mathcal{C}_{i})\), we can consider that \(\alpha_{i}\Phi\) is defined on a subset of \(\mathcal{C}_{i}\cap\Omega\), say \(\mathcal{C}_{i}^{\prime}\), with a smooth boundary and the same properties as \(\mathcal{C}_{i}\cap\Omega\). In addition, we have:

\[\alpha_{i}(\Phi\times\mathbf{n})=\mathbf{0}\quad\text{on }\partial\mathcal{C}_{i} ^{\prime}\]

as either factor vanishes on each point of \(\partial\mathcal{C}_{i}^{\prime}\). Hence \(\alpha_{i}\Phi\in W\) on \(\mathcal{C}_{i}^{\prime}\) and we infer from \(1^{\circ}\) that \(\alpha_{i}\Phi\in H^{1}(\mathcal{C}_{i})^{3}\) with

\[\left\|\alpha_{i}\Phi\right\|_{1}\leqslant C_{i}\{\left\|\alpha_{i}\Phi \right\|_{0}+\left\|\operatorname{div}(\alpha_{i}\Phi)\right\|_{0}+\left\| \operatorname{\mathbf{curl}}(\alpha_{i}\Phi)\right\|_{0}\},\]

where all norms are taken over \(\mathcal{C}_{i}^{\prime}\). Therefore, with the same notation,

\[\left\|\alpha_{i}\Phi\right\|_{1}\leqslant C_{i}^{\prime}\{\left\|\Phi\right\| _{0}+\left\|\operatorname{div}\Phi\right\|_{0}+\left\|\operatorname{\mathbf{ curl}}\Phi\right\|_{0}\},\]

thus proving the theorem. 

### The Imbedding of \(H_{0}(\operatorname{div};\Omega)\cap H(\operatorname{\mathbf{curl}};\Omega)\) into \(H^{1}(\Omega)^{3}\)

Again we keep the hypotheses of Section 3.4 and we set:

\[U=H_{0}(\operatorname{div};\Omega)\cap H(\operatorname{\mathbf{curl}};\Omega) ,\quad\ U_{0}=\{\mathbf{u}\in U;\,\operatorname{div}\mathbf{u}=0\}.\]

We begin with two results analogous to Lemmas 3.3 and 3.4.

**Lemma 3.5**.: _The space \(U\) is continuously imbedded into \(H^{1}(\Omega)^{3}\) iff \(U_{0}\) is also continuously imbedded into \(H^{1}(\Omega)^{3}\)._

The proof, which follows the lines of Lemma 3.3, is left to the reader.

**Lemma 3.6**.: _Suppose that \(\Omega\) is bounded, Lipschitz-continuous and simply-connected. Then the mapping \(\Phi\to\operatorname{\mathbf{curl}}\Phi\) is an isomorphism from the space \(U_{0}\) onto the space:_

\[T=\{\mathbf{u}\in L^{2}(\Omega)^{3};\,\operatorname{div}\mathbf{u}=0,\zeta \mathbf{u}\cdot\mathbf{n},1\}_{T_{i}}=0,0\leqslant i\leqslant p\};\]

_and there exist two positive constants \(C_{1}\) and \(C_{2}\) such that_

(3.37) \[\left\|\Phi\right\|_{0,\Omega}\leqslant C_{1}\left\| \operatorname{\mathbf{curl}}\Phi\right\|_{0,\Omega}\quad\quad\forall\Phi\in U_{ 0},\] (3.38) \[\left\|\Phi\right\|_{0,\Omega}\leqslant C_{2}\{\left\| \operatorname{\mathbf{curl}}\Phi\right\|_{0,\Omega}+\left\|\operatorname{div} \Phi\right\|_{0,\Omega}\}\quad\quad\forall\Phi\in U.\]

Proof.: Since \(\Omega\) is simply-connected, we infer from Theorem 3.5 and the argument of Lemma 3.4 that the mapping \(\Phi\to\operatorname{\mathbf{curl}}\Phi\) is an isomorphism from \(U_{0}\) onto \(T\) and that (3.37) holds. In turn, (3.38) follows readily from (3.37), the decomposition (3.32) and Theorem 1.9. Note that here again there is no continuity requirement on \(\Gamma\), except of course the Lipschitz-continuity.
