Finally, \(\theta=-\,\mathcal{A}\phi\in H^{t-1/2}(\Omega)\) and it follows from (A.26) (or (A.21a) when \(l\geqslant 3\)) that:

\[\inf_{\theta_{h}\,\in\,\theta_{h}}\|\,\theta-\,\theta_{h}\|_{0,\, \Omega}\leqslant C_{4}\,h^{t-1/2}\,\|\,\theta\,\|_{t-1/2,\,\Omega}\leqslant C_{ 4}\,h^{t-1/2}\,\|\,\phi\|_{t+3/2,\,\Omega}.\]

Hence (3.7) stems from (3.6) and these three inequalities. 

As an immediate consequence, we derive the following corollary by using a simple and classical density argument.

**Corollary 3.1**.: _Under the assumptions of Lemma 3.2, we have for all \(v\in\widetilde{V}\)_:__

\[\lim_{h\to 0}\inf_{w_{h}\,\in\,\mathcal{V}_{h}}\|v-w_{h}\|_{\widetilde{x}}=0.\]

In addition, Lemma 3.3 implies a number of error estimates for the "stream function-vorticity" method. First, let us consider the simplest case where the solution of the Stokes problem has sufficient regularity.

**Theorem 3.1**.: _Let \(\Omega\) be a bounded, convex polygon and let \(\mathcal{T}_{h}\) be a uniformly regular family of triangulations of \(\bar{\Omega}\). Assume that the solution \((\mathbf{u}=\mathbf{curl}\,\psi,p)\) of the Stokes problem (2.1) is such that \(\,\psi\in H^{k+3/2}(\Omega)\cap W^{k+1,\,\infty}(\Omega),\ p\in H^{k-1/2}( \Omega)\cap L^{2}_{0}(\Omega)\) for some real \(k\in[3/2,l]\). Then the solution \((u_{h}=(\mathbf{curl}\,\psi_{h},\omega_{h}),p_{h})\) of Problem (2.29) satisfies the estimate:_

(3.8) \[\|\,u-u_{h}\|_{\widetilde{x}} \leqslant C_{1}\,h^{k-1/2}(\|\,\psi\,\|_{k+3/2,\,\Omega}+\,\|\, \psi\,\|_{k+1,\,\infty,\,\Omega}),\] (3.9) \[\|\,p-p_{h}\|_{0,\,\Omega} \leqslant C_{2}\,h^{k-1/2}(|p|_{k-1/2,\,\Omega}+\,\|\,\psi\,\|_{k +3/2,\,\Omega}+\,\|\,\psi\,\|_{k+1,\,\infty,\,\Omega}).\]

_When \(1\leqslant k\leqslant\min(3/2,l)\) and \(\psi\in W^{k+1,\,\infty}(\Omega)\), \(\mathcal{A}\psi\) and \(\,p\in H^{1}(\Omega)\) we have:_

(3.10) \[\|\,u-u_{h}\|_{\widetilde{x}} \leqslant C_{3}(h|\,\mathcal{A}\psi|_{1,\,\Omega}+\,h^{k-1/2}\, \|\,\psi\,\|_{k+1,\,\infty,\,\Omega}),\] (3.11) \[\|\,p-p_{h}\|_{0,\,\Omega} \leqslant C_{4}(h|\,p|_{1,\,\Omega}+\,h|\,\mathcal{A}\psi|_{1,\, \Omega}+\,h^{k-1/2}\,\|\,\psi\,\|_{k+1,\,\infty,\,\Omega}).\]

Proof.: Owing to (3.6), Remark 2.2 and Theorems 2.6 and 2.7 we get:

\[|u-u_{h}| \leqslant C_{1}\{\,\|\,\omega-p_{h}\omega\|_{0,\,\Omega}+\,h^{k-1/2}\| \,\psi\,\|_{k+1,\,\infty,\,\Omega}\},\] \[\|\,u-u_{h}\|_{\widetilde{x}} \leqslant C_{2}\{\,\|\,\omega-p_{h}\omega\|_{0,\,\Omega}+|\psi-\,\hat{P}_{h} \psi|_{1,\,s,\Omega}+\,h^{k-1/2}\,\|\,\psi\,\|_{k+1,\,\infty,\,\Omega}\},\] \[\|\,p-p_{h}\|_{0,\,\Omega} \leqslant C_{3}\,\biggl{\{}h\inf_{q_{h}\,\in\,Q_{h}}|p-q_{h}|_{1,\, \Omega}+|u-u_{h}|\] \[\quad+\inf_{\theta_{h}\,\in\,\Theta_{h}}(\|\,\omega-\theta_{h}\|_ {0,\,\Omega}+h|\,\omega-\theta_{h}|_{1,\,\Omega})\biggr{\}}.\]

Applying (A.26), this gives (3.8) and (3.9) or (3.10) and (3.11) according to the value of \(k\)
