\[|(\mathbf{g},\mathbf{curl}(\psi-\psi_{h}))| \leqslant|u-u_{h}|(|z-z_{h}|+\lambda|\psi|_{1,\,4,\,\Omega}|\chi-\chi_ {h}|_{1,\,4,\,\Omega}\] (4.47) \[\quad+\lambda|\chi_{h}|_{1,\,4,\,\Omega}|\psi-\psi_{h}|_{1,\,4, \,\Omega}+\|v-P_{h}v\|_{0,\,\Omega})\] \[\quad+\lambda|u|\,|\psi-\psi_{h}|_{1,\,4,\,\Omega}|\chi-\chi_{h}| _{1,\,4,\,\Omega}\] \[\quad+|v-P_{h}v|_{1,\,\,\Omega}|\psi-\phi_{h}|_{1,\,\,\Omega}\] \[\quad+|\chi-\delta_{h}|_{1,\,\,\Omega}|o-P_{h}o|_{1,\,\,\Omega}\] \[\quad+|z-z_{h}|\,|o-P_{h}o|_{0,\,\Omega}\] \[\qquad\qquad\qquad\qquad\qquad\qquad\qquad\qquad\qquad\qquad \qquad\qquad\forall z_{h}\in V_{h}\quad\quad\forall\phi_{h},\,\delta_{h}\in \mathcal{P}_{h}.\]

Finally, recall that (cf. Lemma III.3.3 and Remark III.3.2):

\[\inf_{z_{h}\in V_{h}}\|z-z_{h}\|_{X}\leqslant\begin{cases}C_{1}h\|\chi\|_{3, \,\Omega}\quad\text{if $l\geqslant 2$}\\ C_{2}(\xi)h^{1/2-\varepsilon}\|\chi\|_{3,\,\Omega}\quad\text{if $l=1$}\quad\quad \forall\varepsilon>0;\end{cases}\]

on the other hand,

\[\inf_{\delta_{h}\in\mathcal{P}_{h}}|\chi-\delta_{h}|_{1,\,\,\Omega}\leqslant C _{3}h^{a}|\psi|_{\alpha+1,\,\,\Omega}\quad\text{with $\alpha=\min(l,2)$};\]

and likewise:

\[\inf_{\phi_{h}\in\mathcal{P}_{h}}|\psi-\phi_{h}|_{1,\,\,\Omega}\leqslant C_{4 }h^{l}|\psi|_{l+1,\,\,\Omega},\]

\[\|o-P_{h}o\|_{0,\,\Omega}+h|o-P_{h}o|_{1,\,\,\Omega}\leqslant C_{5}h^{\beta}| o|_{\beta,\,\,\Omega}\]

with \(\beta=1\) when \(l=1\) and \(\beta=l-1\) when \(l\geqslant 2\). By substituting these bounds into (4.47) and applying Theorem 4.4 and Lemma 4.1 we easily derive (4.43). 

### Remarks on the "Stream Function-Gradient of Velocity Tensor" Scheme

With minor modifications, the approach of Section 4.3 can be applied to the "stream function-gradient of velocity tensor" method for the Navier-Stokes equations, at least when \(\Omega\) is a _plane_, _convex polygon_. Going back to Paragraph 4, Chapter III, recall the bilinear forms:

\[a_{h}(\sigma,\tau)=\int_{\Omega}\sigma_{ij}\tau_{ij}\,dx,\]

\[b_{h}(\tau,\phi)=-\sum\limits_{\kappa\in\mathcal{T}_{h}}\int_{\kappa}\tau_{ ij}(\partial^{2}\phi/\partial x_{i}\partial x_{j})\,dx+\int_{T_{h}}M_{n}(\tau)S( \partial\phi/\partial n)\,ds,\]

and the spaces

\[\widetilde{\Sigma}=\{\tau=(\tau_{ij})\in L^{2}(\Omega)^{4};\,\tau_{1 \,2}=\tau_{2\,1},\,\tau|_{\kappa}\in W^{1,\,r}(\kappa)^{4}\quad\forall\kappa \in\mathcal{T}_{h},\] \[\quad\quad M_{n}(\tau)\text{ is continuous on each segment of }\Gamma_{h}\},\] \[\widetilde{\mathcal{V}}=\{\phi\in\Phi_{s};\,\phi|_{\kappa}\in H^{2 }(\kappa)\quad\forall\kappa\in\mathcal{T}_{h}\},\]
