_where \(q\in H^{1}(\Omega)/\mathbb{R}\) is the only solution of (3.9) and \(\phi\in H^{1}(\Omega)^{3}\) satisfies \(\operatorname{\mathbf{curl}}\phi\in H\) and \(\operatorname{div}\phi=0\). In addition, if \(\Omega\) is simply-connected, we can choose for \(\phi\) the only solution of (3.29) in \(H(\operatorname{\mathbf{curl}};\Omega)\)._

**Corollary 3.5**.: _Every function \(\mathbf{v}\) of \(H^{1}_{0}(\Omega)^{3}\) has the orthogonal decomposition_:__

(3.33) \[\mathbf{v}=(-\Delta)^{-1}\operatorname{\mathbf{grad}}q\,+\,\operatorname{ \mathbf{curl}}\phi,\]

_where \(\phi\in H^{2}(\Omega)^{3}\) with \(\operatorname{div}\phi=0\) and \(\operatorname{\mathbf{curl}}\phi\in V\) is a solution of_

(3.34) \[(-\Delta\phi,\operatorname{\mathbf{curl}}\mathbf{w})=(\operatorname{\mathbf{ curl}}\mathbf{v},\operatorname{\mathbf{curl}}\mathbf{w})\quad\quad\forall \mathbf{w}\in V,\]

_and \(q\in L^{2}_{0}(\Omega)\) is uniquely determined by (3.33). Moreover, when \(\Omega\) is simply-connected, problem (3.34) has exactly one solution \(\phi\) in \(H\) with \(\operatorname{\mathbf{curl}}\phi\) in \(V\)._

### The Imbedding of \(H(\operatorname{div};\Omega)\cap H_{0}(\operatorname{\mathbf{curl}};\Omega)\) into \(H^{1}(\Omega)^{3}\)

Throughout this section, we assume that \(\Omega\) is _bounded_ and that _either \(\Gamma\) is \(\mathcal{C}^{1,\,1}\) or_ that \(\Omega\) is a _convex polyhedron_. Like in Section 3.2, we set:

\[W=H(\operatorname{div};\Omega)\cap H_{0}(\operatorname{\mathbf{curl}};\Omega), \quad\quad W_{0}=\{\mathbf{w}\in W;\,\operatorname{div}\mathbf{w}=0\}.\]

**Lemma 3.3**.: _The space \(W\) is continuously imbedded into \(H^{1}(\Omega)^{3}\) iff \(W_{0}\) is also continuously imbedded into \(H^{1}(\Omega)^{3}\)._

Proof.: Let \(\phi\in W\) and let \(q\in H^{1}(\Omega)\) be the solution of the Dirichlet problem

\[\Delta q=\operatorname{div}\phi\quad\text{in }\Omega,\quad\quad q=0\quad \text{on }\Gamma.\]

Then

\[\|\operatorname{\mathbf{grad}}q-\phi\|_{0,\Omega}\leqslant\|\phi\|_{0,\Omega}\]

and the assumptions on \(\Omega\) imply that \(q\in H^{2}(\Omega)\) with

\[\|q\|_{2,\Omega}\leqslant C_{1}\,\|\operatorname{div}\phi\|_{0,\Omega}.\]

Moreover, we have \((\operatorname{\mathbf{grad}}q)\times\mathbf{n}=\mathbf{0}\) on \(\Gamma\). Therefore the function

\[\psi=\phi-\operatorname{\mathbf{grad}}q\]

belongs to \(W_{0}\). Hence, if \(W_{0}\) is continuously imbedded in \(H^{1}(\Omega)^{3}\), then \(\phi\in H^{1}(\Omega)^{3}\) and

\[\|\phi\|_{1,\Omega} \leqslant\|\psi\|_{1,\Omega}+C_{1}\|\operatorname{div}\phi\|_{0,\Omega}\] \[\leqslant C_{2}(\|\psi\|_{0,\Omega}+\|\operatorname{\mathbf{curl} }\psi\|_{0,\Omega})+C_{1}\|\operatorname{div}\phi\|_{0,\Omega}\] \[\leqslant C_{2}(\|\phi\|_{0,\Omega}+\|\operatorname{\mathbf{curl} }\phi\|_{0,\Omega})+C_{1}\|\operatorname{div}\phi\|_{0,\Omega},\]

thus showing that the imbedding is also continuous. The converse is obvious.
