Conversely, suppose that (1.12) holds with a constant \(\beta^{*}>0\) independent of \(h\). Then for each \(v\) in \(X\) there exists a unique element \(\Pi_{h}v\) of \(V_{h}^{\perp}\) such that

\[b(\Pi_{h}v,\mu_{h})=b(v,\mu_{h})\quad\forall\mu_{h}\in M_{h}\]

and

\[\|\,\Pi_{h}v\|_{X}\leqslant\frac{1}{\beta^{*}}\,\|\,B_{h}v\|_{M_{h}}\leqslant \frac{\|\,b\,\|}{\beta^{*}}\,\|\,v\|_{X}.\]

Clearly \(\Pi_{h}\in\mathcal{L}(X;X_{h})\) and satisfies (1.20) with \(C=\|\,b\,\|/\beta^{*}\). 

In practice, the construction of \(\Pi_{h}\) is by no means easy. The reader will find in Section 1.4 how to establish the inf-sup condition in a number of cases without constructing \(\Pi_{h}\) explicitly.

_Remark 1.4_.: Another useful way of writing the inf-sup condition (1.12) is:

\[\begin{cases}\text{for each }\mu_{h}\in M_{h}\text{ there exists a }v_{h}\text{ in }X_{h}\text{ (unique in }V_{h}^{\perp})\text{ such that:}\\ \\ b(v_{h},\mu_{h})=\|\,\mu_{h}\|_{M}^{2},\quad\quad\|\,v_{h}\|_{X}\leqslant\frac{ 1}{\beta^{*}}\,\|\,\mu_{h}\|_{M}.\end{cases}\]

This result, which is also valid in the continuous case, uses explicitly the fact that \(\|\,\cdot\,\|_{M}\) is a Hilbert norm.

_Remark 1.5_.: In the particular case where the bilinear form \(a(.,.)\) coincides with the scalar product \(((.,.))_{X}\) associated with the Hilbert norm \(\|\,\cdot\,\|_{X}\), formula (1.17) simplifies to:

\[\|\,\lambda-\lambda_{h}\|_{M}\leqslant\frac{1}{\beta^{*}}\,\biggl{\{}\inf_{w_{ h}\in V_{h}(x)}\|\,u-w_{h}\|_{X}+(\beta^{*}+\|\,b\,\|)\inf_{\mu_{h}\in M_{h}}\|\, \lambda-\mu_{h}\|_{M}\biggr{\}}.\] (1.17)

Indeed, we have:

\[b(v_{h},\lambda_{h}-\mu_{h})=((u-w_{h},v_{h}))_{X}+b(v_{h}, \lambda-\mu_{h})\] \[\forall v_{h}\in V_{h}^{\perp},\quad\forall w_{h}\in V_{h}(\chi), \quad\forall\mu_{h}\in M_{h}\]

and the \(v_{h}\) (in \(V_{h}^{\perp}\)) of Remark 1.4 gives (1.17').

Theorem 1.1 readily yields the following general convergence results.

**Corollary 1.1**.: _Assume that the following hypotheses hold:_

\(1^{\circ})\) _the form \(a(.,.)\) satisfies (1.10) with a constant \(\alpha^{*}>0\) independent of \(h\)_;__

\(2^{\circ})\) _there exist a dense subvariety \(\mathscr{V}(\chi)\) of \(V(\chi)\), \(a\) dense subspace \(\mathscr{M}\) of \(M\) and two mappings \(r_{h}\): \(\mathscr{V}(\chi)\to V_{h}(\chi)\) and \(\rho_{h}\): \(\mathscr{M}\to M_{h}\) with:_

\[\lim_{h\to 0}\|\,r_{h}v-v\,\|_{X}=0\quad\quad\forall v\in\mathscr{V}( \chi),\] \[\lim_{h\to 0}\|\,\rho_{h}\mu-\mu\,\|_{M}=0\quad\quad\forall\mu\in \mathscr{M}.\]
