(4.24) \[K(\lambda)=\mathop{\rm Min}\limits_{\mu\in M}K(\mu).\]

Therefore, the second argument \(\lambda\) of the solution of Problem (Q) is characterized as the solution of the unconstrained optimization problem (4.24).

### Approximation by Regularization or Penalty

We want to introduce a perturbed form of Problem (Q) which may be easier to solve in practice. In addition to \(a(.,.)\) and \(b(.,.)\), we consider a third continuous bilinear form

\[c(.,.)\colon M\times M\to\mathbb{R},\]

with norm

\[\|c\|=\sup_{\lambda,\,\mu\in M,\,\lambda,\,\mu\neq 0}\frac{c(\lambda,\mu)}{ \|\lambda\|_{M}\|\mu\|_{M}}.\]

We assume that the form \(c(.,.)\) is \(M\)-elliptic in the sense that there exists a constant \(\gamma>0\) such that:

(4.25) \[c(\mu,\mu)\geqslant\gamma\,\|\,\mu\|_{M}^{2}\quad\quad\forall\mu\in M.\]

With the form \(c(.,.)\), we associate the operator \(C\in\mathcal{L}(M;M^{\prime})\) defined by

(4.26) \[\langle C\lambda,\mu\rangle=c(\lambda,\mu)\quad\quad\forall\lambda,\,\mu\in M.\]

Let \(\varepsilon>0\) be a parameter which will _tend to zero_. We consider the following problem, called _Problem_ (Q\({}^{\varepsilon}\)):

_Find a pair \((u^{\varepsilon},\lambda^{\varepsilon})\in X\times M\) such that_

(4.27) \[a(u^{\varepsilon},v)+b(v,\lambda^{\varepsilon})=\langle l,v\rangle \quad\quad\forall v\in X,\] (4.28) \[-\varepsilon c(\lambda^{\varepsilon},\mu)+b(u^{\varepsilon},\mu)= \langle\chi,\mu\rangle\quad\quad\forall\mu\in M.\]

Since the operator \(C\) is nonsingular, equation (4.28) is equivalent to

(4.29) \[\lambda^{\varepsilon}=(1/\varepsilon)C^{-1}(Bu^{\varepsilon}-\chi).\]

Hence, by replacing \(\lambda^{\varepsilon}\) by its value in (4.27), we obtain the following problem, called _Problem_ (P\({}^{\varepsilon}\)), which is obviously equivalent to Problem (Q\({}^{\varepsilon}\)):

_Find \(u^{\varepsilon}\in X\) such that_

(4.30) \[a(u^{\varepsilon},v)+(1/\varepsilon)\langle C^{-1}Bu^{\varepsilon},Bv\rangle =\langle l,v\rangle+(1/\varepsilon)\langle C^{-1}\chi,Bv\rangle\quad\quad \forall v\in X.\]

**Theorem 4.3**.: _Assume the hypotheses (4.9) and (4.25). Assume in addition that there exists a constant \(\alpha>0\) such that_

(4.31) \[a(v,v)+\langle C^{-1}Bv,Bv\rangle\geqslant\alpha\,\|\,v\|_{X}^{2}\quad\quad \forall v\in X.\]
