\[\pi Au=\pi l=g.\]

Hence, \(\pi A\) is a one-to-one linear continuous mapping from \(V\) onto \(V^{\prime}\) and therefore an isomorphism from \(V\) onto \(V^{\prime}\). 

_Remark 4.1_.: In the first part of the proof of Theorem 4.1, we have used the fact that Problem (P) has a unique solution as soon as \(\pi A\) is an isomorphism from \(V\) onto \(V^{\prime}\) and the affine manifold \(V(\chi)\) is non void. The inf-sup condition (4.9) implies indeed that \(V(\chi)\) is non void.

**Corollary 4.1**.: _Assume that the bilinear form \(a(.,.)\) is V-elliptic, i.e. there exists a constant \(\alpha>0\) such that_

(4.12) \[a(v,v)\geq\alpha\|v\|_{X}^{2}\ \ \ \ \ \forall v\in V.\]

_Then, Problem (Q) is well-posed if and only if the bilinear form \(b(.,.)\) satisfies the inf-sup condition (4.9)._

Proof.: Let \(l\) be in \(V^{\prime}\). Since \(a(.,.)\) is \(V\)-elliptic, we may apply the Lax & Milgram Theorem 1.7: there exists a unique \(u\in V\) such that

\[a(u,v)=\langle l,v\rangle\ \ \ \ \ \ \forall v\in V,\]

or equivalently

\[\pi Au=l.\]

Moreover, the mapping \(l\to u\) is continuous from \(V^{\prime}\) into \(V\). Hence, \(\pi A\) is an isomorphism from \(V\) onto \(V^{\prime}\) and the desired result follows from Theorem 4.1.



_Remark 4.2_.: The above analysis can be readily extended to the case where \(X\) and \(M\) are reflexive Banach spaces. The space \(V\) is unchanged but \(V^{\perp}\) is replaced by the quotient space \(X/V\). The results and proofs of this section carry over with very few modifications.

### A Saddle-Point Approach

Under adequate hypotheses, it is possible to formulate Problems (P) and (Q) in terms of optimization problems.

In addition to the notations of the previous section, we introduce two quadratic functionals \(J\colon X\to\mathbb{R}\) and \(\mathscr{L}\colon X\times M\to\mathbb{R}\) defined by

(4.13) \[J(v)=(1/2)a(v,v)-\langle l,v\rangle\]

and

(4.14) \[\mathscr{L}(v,\mu)=J(v)+b(v,\mu)-\langle\chi,\mu\rangle.\]
