_Remark 2.1_.: Let \(\mathbf{u}_{0}\) be a function of \(H^{1}(\Omega)^{N}\) such that

\[\operatorname{div}\mathbf{u}_{0}=0,\quad\left.\mathbf{u}_{0}\right|_{\Gamma}= \mathbf{g},\quad\left.v>\rho(\mathbf{u}_{0}).\right.\]

Then, we have for all solution \((\mathbf{u}=\mathbf{u}_{0}+\mathbf{w},\mathbf{p})\) of Problem (2.20)

\[\left.\left|\mathbf{w}\right|_{1,\Omega}\right.\leq\frac{\left\|\,l(\mathbf{f} ;\mathbf{u}_{0})\right\|_{V^{\prime}}}{v-\rho(\mathbf{u}_{0})}.\]

_Remark 2.2_.: Assuming the hypotheses of Theorem 2.4, we may apply the results of Remark 1.3 to Problem (2.21). Starting from an arbitrary \(\mathbf{w}^{0}\in V\), the iterative scheme

\[\tilde{a}(\mathbf{w}^{m};\mathbf{w}^{m+1},\mathbf{v})-(p^{m+1},\operatorname {div}\mathbf{v})=\langle\mathbf{f},\mathbf{v}\rangle-a(\mathbf{u}_{0};\mathbf{ u}_{0},\mathbf{v})\quad\quad\forall\mathbf{v}\in H^{1}_{0}(\Omega)^{N}\]

uniquely defines a sequence \((\mathbf{w}^{m},p^{m})\) in \(V\times L^{2}_{0}(\Omega)\) which converges towards the solution \((\mathbf{w},p)\) of Problem (2.21).

Equivalently, starting from an arbitrary function \(\mathbf{u}^{0}\in H^{1}(\Omega)^{N}\) such that \(\operatorname{div}\mathbf{u}^{0}=0\) and \(\mathbf{u}^{0}|_{\Gamma}=\mathbf{g}\), the iterative scheme

\[\left\{\begin{aligned} -\nu\lambda\mathbf{u}^{m+1}& +\,\sum\limits_{j=1}^{N}u_{j}^{m}(\partial\mathbf{u}^{m+1}/\partial x_{j})+ \mathbf{grad}\,p^{m+1}&=\mathbf{f}&\text{in }\Omega,\\ &\operatorname{div}\mathbf{u}^{m+1}&=0& \text{in }\Omega,\\ &\mathbf{u}^{m+1}&=\mathbf{g}&\text{on }\Gamma\end{aligned}\right.\] (2.25)

uniquely defines a sequence \((\mathbf{u}^{m},p^{m})\) in \(H^{1}(\Omega)^{N}\times L^{2}_{0}(\Omega)\) such that

\[\lim_{m\to\infty}\left\{\,\left\|\,\mathbf{u}^{m}-\mathbf{u}\right\|_{1, \Omega}+\,\left\|\,p^{m}-p\,\right\|_{0,\Omega}\right\}=0.\]

### The Stream Function Formulation of the Homogeneous Problem

For the sake of simplicity, we restrict the discussion exclusively to the homogeneous boundary condition:

\[\mathbf{u}=\mathbf{0}\quad\text{on }\Gamma.\] (2.2)

Let us first consider the _two-dimensional case_: \(N=2\). Since \(\mathbf{u}\in H^{1}_{0}(\Omega)^{2}\) is divergence-free, we know from Section I.3.1 that

\[\mathbf{u}=\mathbf{curl}\,\psi\]

for a unique stream function \(\psi\) in the space

\[\psi=\langle\,\chi\in H^{2}(\Omega);\,\chi|_{\Gamma_{0}}=0,\,\chi|_{\Gamma_{i}} \text{ is constant for }1\leq i\leq p,\,\partial\chi/\partial n|_{\Gamma}=0\rangle.\]

To express the nonlinear term \(a_{1}(\mathbf{u};\mathbf{u},\mathbf{v})\) in terms of stream functions, observe that
