where \(\tau_{1}\) is the unit direction vector of \(L_{1}\) and \(\mathbf{n}_{2}\) the unit normal vector to \(L_{2}\). Therefore, the difference \(X_{\kappa_{1}}-X_{\kappa_{2}}\) is \(O(h)\) if \(\tau_{1}\cdot\mathbf{n}_{2}\) is also \(O(h)\); in other words if \(L_{1}\) and \(L_{2}\) are nearly parallel. Thus with the notations of Figure 20, we make the following hypothesis:

_there exists a constant \(C>0\)_, _independent of_\(h\), _such that_

(3.30) \[|\tau_{1}\cdot\mathbf{n}_{2}|\leq Ch\]

_for all pairs of adjacent segments \(L_{1}\) and \(L_{2}\) of \(\mathcal{T}_{h}\)._

This hypothesis means that a mesh \(\mathcal{T}_{h}\) that satisfies (3.22) as well as (3.30) is obtained by slightly distorting two pencils of parallel lines. Of course it is a very stringent condition on the mesh and only few domains \(\Omega\) lend themselves readily to such a triangulation. Albeit so, with (3.30) we derive the result announced at the beginning of this section. First, we infer the next lemma from the above considerations.

**Lemma 3.9**.: _Let \(\Omega\) be a bounded polygon and let \(\mathcal{T}_{h}\) be a regular triangulation of \(\bar{\Omega}\) made of convex quadrilaterals satisfying (3.22) and (3.30). Then there exists a constant \(C>0,\) independent of \(h\), such that:_

(3.31) \[\begin{split}\left|\sum_{\kappa\in\mathcal{T}_{h}}\int_{\tilde{ \kappa}}X_{\kappa}[\partial(\hat{\phi}-\hat{T}\hat{\phi})/\partial\hat{x}_{i} ]\,[\partial\hat{\mu}/\partial\hat{x}_{j}]\,d\hat{x}\right|&\leq Ch ^{l}\|\,\phi\|_{l+2,\Omega}\|\,\mu_{h}\|_{0,\Omega}\\ i&\neq j,\quad\forall\phi\in H^{l+2}(\Omega),\quad \forall\mu_{h}\in\mathcal{O}_{h}.\end{split}\]

Then, using Lemmas 3.6 to 3.9 we can prove the following theorem.

**Theorem 3.4**.: _Let \(\Omega\) and \(\mathcal{T}_{h}\) be like in Lemma 3.9 and let \(I_{h}\) be the interpolation operator on \(\kappa\) corresponding to \(\hat{I}\)_:__

\[(I_{h}\phi)\circ F_{\kappa}=\hat{I}(\phi\circ F_{\kappa})\quad\text{on each $\kappa$},\]

_where \(\hat{I}\in\mathcal{C}(\mathcal{C}^{0}(\hat{\kappa});Q_{l})\) is the standard interpolation operator at the \((l+1)^{2}\) Gauss-Lobatto quadrature nodes. Then there exists a constant \(C>0,\) independent of \(h,\) such that the following bound holds for all \(\phi\) in \(H^{l+2}(\Omega)\)_:__

(3.32) \[\sup_{\mu_{h}\in\mathcal{O}_{h}}\frac{|(\mathbf{curl}(\phi-I_{h}\phi),\mathbf{ curl}\,\mu_{h})|}{\|\mu_{h}\|_{0,\Omega}}\leq Ch^{l}\|\,\phi\|_{l+2,\Omega}.\]

With the material of the preceding section, we immediately derive the following consequence of Theorem 3.4.

**Corollary 3.3**.: _Under the assumptions of Theorem 3.4, there exists a constant \(C>0,\) independent of \(h,\) such that:_

(3.33) \[\begin{split}\inf_{v_{h}\in V_{h}}\|v-v_{h}\|_{\tilde{\kappa}}& \leq Ch^{l}\|\,\phi\|_{l+2,\Omega}\\ &\forall v=(\mathbf{curl}\,\phi,\theta)\in V\quad\text{with $\phi\in H^{l+2}(\Omega)$}.\end{split}\]
