Now assume that the right-hand side \(\mathbf{f}\) of (2.1) belongs to \(L^{r}(\Omega)^{2}\) and consider the following _Problem_ (\(\widetilde{\mathcal{Q}}\)).

\(\mathit{Find}\) _\((\mathbf{u},\omega)\!\in\!\widetilde{X}\) and \((\lambda,p)\!\in\!\widetilde{M}\) such that_:

(2.13) \[\left\{\begin{aligned} & v(\omega,\theta)+(\mathbf{v}, \mathbf{curl}\,\lambda)-(\theta,\lambda)+(\mathbf{grad}\,p,\mathbf{v})=( \mathbf{f},\mathbf{v})\quad\quad\forall(\mathbf{v},\theta)\!\in\!\widetilde{X} ,\\ &(\mathbf{u},\mathbf{curl}\,\mu)-(\omega,\mu)+(\mathbf{grad}\,q, \mathbf{u})=0\quad\quad\forall(\mu,q)\!\in\!\widetilde{M}.\end{aligned}\right.\]

Before going any further, let us examine the space \(\widetilde{V}\) associated with Problem (\(\widetilde{\mathcal{Q}}\)):

(2.14) \[\widetilde{V}=\{(\mathbf{v},\theta)\!\in\!\widetilde{X};(\mathbf{v},\mathbf{ curl}\,\mu)-(\theta,\mu)+(\mathbf{grad}\,q,\mathbf{v})=0\quad\quad\forall(\mu,q )\!\in\!\widetilde{M}\}.\]

We introduce the following seminorm on \(\widetilde{X}\):

(2.15) \[|(\mathbf{v},\theta)|=\|\,\theta\|_{0,\Omega}\quad\quad\forall(\mathbf{v}, \theta)\!\in\!\widetilde{X}.\]

**Lemma 2.1**.: _The spaces \(V\) and \(\widetilde{V}\) coincide algebraically and topologically. Moreover the seminorm \(|.|\) is a norm equivalent to \(\|\,.\,\|_{\widetilde{X}}\) on \(V\)_:

\[|(\mathbf{v},\theta)|\cong\|(\mathbf{v},\theta)\|_{\widetilde{X}}\quad\quad \forall(\mathbf{v},\theta)\!\in\!V.\]

Proof.: Let \((\mathbf{v},\theta)\!\in\!\widetilde{V}\). Straightforward applications of Green's formulas (I.2.17) and (I.2.22) yield in succession:

\[\begin{aligned} &\mathrm{div}\,\mathbf{v}=0\quad\text{in }\Omega,\quad \mathbf{v}\!\cdot\!\mathbf{n}=0\quad\text{on }\Gamma;\\ &\theta=\mathrm{curl}\,\mathbf{v}\quad\text{in }\Omega,\quad \mathbf{v}\!\cdot\!\mathbf{\tau}=0\quad\text{on }\Gamma.\end{aligned}\]

Hence \(\mathbf{v}\!\in\!H_{0}(\mathrm{div};\Omega)\cap H_{0}(\mathrm{curl};\Omega)\) and Lemma I.2.5 implies that

\[\mathbf{v}\!\in\!H_{0}^{1}(\Omega)^{2}\]

with (cf. Remark I.2.7)

(2.16) \[|\mathbf{v}|_{1,\Omega}\leq C\|\,\theta\|_{0,\Omega}.\]

Therefore \(\widetilde{V}\subset V\) and the converse is obvious.

The equivalence of norms is an immediate consequence of the stronger result (2.16) and Sobolev's Imbedding Theorem I.1.3. 

Now we can prove that problems (\(\mathbf{Q}\)) and (\(\widehat{\mathcal{Q}}\)) are equivalent.

**Theorem 2.3**.: _Assume that the solution \((\mathbf{u},p)\) of the Stokes problem (2.1) satisfies_:__

(2.17) \[\mathrm{curl}\,\mathbf{u}\!\in\!W^{1,\,\mathbf{r}}(\Omega),\quad\quad p\!\in\!W ^{1,\,\mathbf{r}}(\Omega)\cap L_{0}^{2}(\Omega);\]

_then Problem (\(\widetilde{\mathcal{Q}}\)) has the unique solution: \(\mathbf{u}\), \(\omega=\mathrm{curl}\,\mathbf{u}\), \(\lambda=v\omega\), \(p\)._

Proof.: The proof is an easy application of Theorem 1.1 and Lemma 2.1.

The inclusions \(X\underset{d}{\subset}\widetilde{X}\) and \(\widetilde{M}\underset{d}{\subset}M\) follow from Theorem I.1.3 and Lemma
