Proof.: The argument of the proof is very similar to that of Theorem 4.3. We set:

\[w^{\varepsilon}=u^{\varepsilon}-u-\sum\limits_{n=1}^{N}\varepsilon^{n}u_{n}, \quad\rho^{\varepsilon}=\dot{\lambda}^{\varepsilon}-\dot{\lambda}-\sum\limits_{ n=1}^{N}\varepsilon^{n}u_{n}.\]

Using (4.1), (4.2), (4.27), (4.28) and (4.35), we get:

(4.37) \[\left\{\begin{aligned} a(w^{\varepsilon},v)+b(v,\rho^{\varepsilon} )=0\quad\quad\forall v\in X,\\ -\varepsilon c(\rho^{\varepsilon},\mu)+b(w^{\varepsilon},\mu)= \varepsilon^{N+1}c(\dot{\lambda}_{N},\mu)\quad\quad\forall\mu\in M.\end{aligned}\right.\]

The first equation (4.37) together with (4.9) yields

(4.38) \[\left\|\,\rho^{\varepsilon}\right\|_{M}\leqslant(\left\|\,a\left\|/\beta \right\|)\left\|\,w^{\varepsilon}\right\|_{X}.\]

Next, by taking \(v=w^{\varepsilon}\) and \(\mu=\rho^{\varepsilon}\) in (4.37), we obtain

\[a(w^{\varepsilon},w^{\varepsilon})=-\varepsilon c(\rho^{\varepsilon},\rho^{ \varepsilon})-\varepsilon^{N+1}c(\dot{\lambda}_{N},\rho^{\varepsilon}) \leqslant-\varepsilon^{N+1}c(\dot{\lambda}_{N},\rho^{\varepsilon})\]

so that

\[a(w^{\varepsilon},w^{\varepsilon})\leqslant\varepsilon^{N+1}(\left\|\,a \left\|\,\left\|\,c\left\|/\beta\right\|\,\dot{\lambda}_{N}\right\|_{M}\right\| w^{\varepsilon}\right\|_{X}.\]

On the other hand, the second equation (4.37) gives

\[Bw^{\varepsilon}=\varepsilon C(\rho^{\varepsilon}+\varepsilon^{N}\dot{ \lambda}_{N})\]

so that

\[\left\langle C^{-1}Bw^{\varepsilon},Bw^{\varepsilon}\right\rangle =\varepsilon^{2}c(\rho^{\varepsilon}+\varepsilon^{N}\dot{\lambda }_{N},\rho^{\varepsilon}+\varepsilon^{N}\dot{\lambda}_{N})\] \[\leqslant 2\varepsilon^{2}\left\|\,c\left\|\,(\left\|\,\rho^{ \varepsilon}\right\|_{M}^{2}+\varepsilon^{2N}\right\|\dot{\lambda}_{N}\right\| _{M}^{2})\]

and by (4.38)

\[\left\langle C^{-1}Bw^{\varepsilon},Bw^{\varepsilon}\right\rangle\leqslant 2 \varepsilon^{2}\left\|\,c\left\|\,(\left\|\,a\left\|/\beta\right\|^{2}\right\| w^{\varepsilon}\right\|_{X}^{2}+\varepsilon^{2N}\left\|\,\dot{\lambda}_{N}\right\|_{M}^{2}).\]

Therefore, using (4.31), we obtain an inequality of the form

\[\alpha\left\|\,w^{\varepsilon}\right\|_{X}^{2}\leqslant C_{1}\varepsilon^{2} \left\|\,w^{\varepsilon}\right\|_{X}^{2}+C_{2}\varepsilon^{N+1}\left\|\,\dot{ \lambda}_{N}\right\|_{M}\left\|\,w^{\varepsilon}\right\|_{X}+C_{3}\varepsilon ^{2N+2}\left\|\,\dot{\lambda}_{N}\right\|_{M}^{2}\]

which implies for \(\varepsilon\leqslant\varepsilon_{0}\) small enough

(4.39) \[\left\|\,w^{\varepsilon}\right\|_{X}\leqslant C_{4}\varepsilon^{N+1}\left\|\, \dot{\lambda}_{N}\right\|_{M}.\]

Now, it follows from (4.35) and Corollary 4.1 that

(4.40) \[\left\|\,\dot{\lambda}_{N}\right\|_{M}\leqslant C_{5}\left\|\,\dot{\lambda} \right\|_{M}\leqslant C_{6}(\left\|\,l\right\|_{X^{\prime}}+\left\|\,\dot{ \gamma}\right\|_{M^{\prime}}),\]

with constants \(C_{5}\) and \(C_{6}\) of the form \(C^{N}\). Thus the desired inequality (4.36) is a consequence of (4.38), (4.39) and (4.40). 

### Iterative Methods of Gradient Type

The purpose of this section is to derive convenient iterative methods to solve Problem (Q). To this end we propose a duality approach based on the optimization formulations (4.20) and (4.24). Assume for the moment that the bilinear form
