Owing to the regularity assumption (4.18), the Stokes operator \(T\) can be written in the form (4.17):

\[T\!\in\!\mathscr{L}(Y;X),\quad\quad T\mathbf{f}=(\mathbf{u},p,\mu=0)\quad\text{ solution of \eqref{eq:T_h}}.\]

The nonlinearity is embodied by the usual mapping \(G\):

\[G(\lambda,v)=\lambda\biggl{(}\sum_{j=1}^{2}v_{j}\partial\mathbf{v}/\partial x _{j}-\mathbf{f}\biggr{)},\quad\quad\lambda\!\in\!\mathbb{R}_{+},\quad\quad v= (\mathbf{v},q,\phi)\!\in\!X\]

which maps \(\mathbb{R}_{+}\times X\) into \(L^{r}(\Omega)^{2}\). With these notations, Problem (4.16) takes the standard form:

\[F(\lambda,u)=0\]

with \(\lambda=1/v\), \(u=(\mathbf{u},\lambda p,0)\) and \(F(\lambda,u)\equiv u+TG(\lambda,u)\).

_Remark 4.3_.: When the Stokes operator has the regularity (4.18), each solution \(u\) of Problem (4.16) with right-hand side \(\mathbf{f}\) in \(L^{r}(\Omega)^{2}\) has the regularity \(\mathbf{u}\!\in\!W^{2,r}(\Omega)^{2}\), \(p\!\in\!W^{1,r}(\Omega)\). This is valid for all real \(r\!\in\!(1,2]\).

_Remark 4.4_.: It is important to note that if the Stokes operator has the regularity (4.18) then every branch of nonsingular solutions of Problem (4.1) with right-hand side \(\mathbf{f}\) in \(L^{r}(\Omega)^{2}\) is also a branch of nonsingular solutions of Problem (4.16) and conversely.

Next, we set

\[W_{h}=X_{h}\times[\![Q_{h}/\mathbb{R}]\!]\times\Phi_{h}\subset X\]

and let \(T_{h}\!\in\!\mathscr{L}(Y;W_{h})\) be the discrete Stokes operator corresponding to (4.17):

\[T_{h}\mathbf{f}=(\mathbf{u}_{h},p_{h},\mu_{h})\quad\text{solution of:}\] (4.19) \[\left\{\begin{aligned} &(\mathbf{grad}\,\mathbf{u}_{h}, \mathbf{grad}\,\mathbf{v}_{h})+(\mathbf{grad}\,p_{h},\mathbf{v}_{h}-\mathbf{ grad}\,q_{h})=(\mathbf{f},\mathbf{v}_{h}-\mathbf{grad}\,q_{h})\\ &\qquad\qquad\qquad\qquad\qquad\qquad\qquad\qquad\qquad\qquad \qquad\qquad\qquad\qquad\qquad\qquad\qquad\qquad\forall(\mathbf{v}_{h},q_{h}) \!\in\!X_{h}\times\,\Phi_{h},\\ &(\mathbf{u}_{h}-\mathbf{grad}\,\mu_{h},\mathbf{grad}\,q_{h})=0 \quad\quad\forall q_{h}\!\in\!Q_{h}.\end{aligned}\right.\]

Therefore, Problem (4.15) has the equivalent formulation:

\[F_{h}(\lambda,u_{h}(\lambda))=0\]

with \(\lambda=1/v\), \(u_{h}(\lambda)=(\mathbf{u}_{h}(\lambda),\lambda p_{h}(\lambda),\mu_{h}(\lambda))\) and \(F_{h}(\lambda,u_{h})\equiv u_{h}+\,T_{h}G(\lambda,u_{h})\).

We are now in a position to apply Theorem 3.3. We take

\[Z=\,Y\]

and (3.36) holds automatically. As far as the approximation properties of the operator \(T_{h}\) are concerned, we can apply the material of Section II.4.3. In particular, it is established in Theorem II.4.6 that
