Now let us determine the degrees of freedom of the tensors of \(\Sigma_{h}\). First we consider the special case where \(\kappa\) is the reference triangle \(\hat{\kappa}\) (cf. Appendix A).

Lemma 4.1: Let \(\hat{\kappa}\) be the reference unit triangle. A symmetric tensor-valued function \(\tau\in P_{t-1}^{4}\) is uniquely determined on \(\hat{\kappa}\) by the following moments:

\[\left\{\begin{aligned} &\int_{\hat{\kappa}}M_{\hat{n}}(\tau)q\,d\hat{ \kappa}\quad\quad\forall q\in P_{t-1}(\hat{\kappa}^{\prime})\quad\text{for all sides $\hat{\kappa}^{\prime}$ of $\hat{\kappa}$},\\ &\left[\int_{\hat{\kappa}}\tau_{ij}q\,d\hat{\kappa}\quad\quad \forall q\in P_{t-2}(\hat{\kappa}),\quad\quad 1\leqslant i,j\leqslant 2,\quad\text{if $l \geqslant 2$}.\right.\end{aligned}\right.\] (4.23)

Proof: To begin with, we observe that (4.23) consists of

\[3l+(3/2)l(l-1)=(3/2)l(l+1)\]

degrees of freedom and that

\[\dim\{\tau\in P_{t-1}^{4};\,\tau_{1\,2}=\tau_{2\,1}\}=(3/2)l(l+1).\]

Thus it suffices to prove that the set of homogeneous equations:

\[\left\{\begin{aligned} &\int_{\hat{\kappa}^{\prime}}M_{\hat{n}}(\tau)q\,d \hat{\kappa}=0\quad\quad\forall q\in P_{t-1}(\hat{\kappa}^{\prime}),\quad \text{for all sides $\hat{\kappa}^{\prime}$ of $\hat{\kappa}$},\\ &\left[\int_{\hat{\kappa}}\tau_{ij}q\,d\hat{\kappa}=0\quad\quad \forall q\in P_{t-2}(\hat{\kappa}),\quad\quad 1\leqslant i,j\leqslant 2,\right.\end{aligned}\right.\] (4.24)

has the unique solution \(\tau=0\).

Now the first equation of (4.24) is equivalent to \(M_{\hat{n}}(\tau)=0\) on \(\partial\hat{\kappa}\). And, taking advantage of the position and shape of \(\hat{\kappa}\), this amounts to:

\[\tau_{1\,1} =0\quad\text{on $\hat{\kappa}_{1}=0$},\] \[\tau_{2\,2} =0\quad\text{on $\hat{\kappa}_{2}=0$},\] \[\tau_{1\,1}+2\tau_{1\,2}+\tau_{2\,2} =0\quad\text{on $\hat{\kappa}_{1}+\hat{\kappa}_{2}=1$}.\]

Next, by taking \(q=\partial\tau_{ij}/\partial\hat{\kappa}_{k}\) in the second equation of (4.24), we obtain:

\[\int_{\partial\hat{\kappa}}\tau_{ij}^{2}\hat{n}_{k}\,d\hat{\kappa}=0\quad \text{for $k=1,2$},\quad\quad 1\leqslant i,j\leqslant 2.\]

Combining with the three equations above, this yields first that \(\tau=0\) on \(\hat{\kappa}_{1}+\hat{\kappa}_{2}=1\) and then that \(\tau=0\) on \(\partial\hat{\kappa}\).

Then (4.24) immediately implies that \(\tau=0\) on the whole of \(\hat{\kappa}\). 

In order to extend Lemma 4.1 to an arbitrary triangle \(\kappa\), we must introduce a suitable transformation that maps a symmetric tensor on \(\hat{\kappa}\) into a symmetric tensor on \(\kappa\) while preserving in some sense \(M_{\bm{n}}(.)\) on \(\partial\hat{\kappa}\). To this end, we recall on the one hand that the normal \(\bm{n}\) to \(\kappa\) and the normal \(\bm{\hat{n}}\) to \(\hat{\kappa}\) are related by:

\[\bm{\hat{n}}=[(B_{\kappa}^{T}\bm{n})/\|\,B_{\kappa}^{T}\bm{n}\,\|\,]\circ F_{\kappa}\]
