_In addition, the pressure \(p\) is the unique solution of \(\colon\)_

\[\begin{split} Find\ p\in W^{1,\,r}(\Omega)\cap L^{2}_{0}(\Omega) \text{ such that }\\ (\mathbf{grad}\ p,\mathbf{grad}\ q)=(\mathbf{f}-v\,\mathbf{curl}\, \omega,\mathbf{grad}\,q)\quad\quad\forall q\in W^{1,\,s}(\Omega).\end{split}\] (2.21)

_Proof._ Equation (2.21) is obtained by taking \(\mathbf{v}=\mathbf{grad}\ q\) for all \(q\in W^{1,\,s}(\Omega)\) in (2.13) and using the fact that \(\lambda=\mathit{v}o\). 

The approximation discussed in the next sections is based essentially on the formulations (2.20) and (2.21). It is important to point out that (2.20) can be interpreted as two Dirichlet problems for the Laplace operator. Indeed, for the sake of simplicity, consider the case where \(\Omega\) is simply-connected (\(p=0\)). Let \(o_{0}\) denote the trace of \(\omega\) on \(\Gamma\); then Problem (2.20) has the following interpretation:

\[\begin{split}-v\Delta\omega&=\operatorname{curl} \mathbf{f}\quad\text{in }\Omega,\quad\quad-\Delta\psi=\omega\quad\text{in }\Omega,\\ \omega|_{\Gamma}&=\omega_{0}\qquad\qquad\qquad \psi|_{\Gamma}=0.\end{split}\]

Likewise, Problem (2.21) is a Neumann's problem for the Laplace operator.

Although the two problems of (2.20) are coupled (because \(\omega_{0}\) is unknown), problem (2.20) is entirely decoupled from (2.21) in the sense that one solves first (2.20) and afterward (2.21). Besides that, these two formulations are well-adapted for approximations with:

\(1^{\circ}\)) exactly divergence-free velocities;

\(2^{\circ}\)) continuous pressures.

### Mixed Approximation and Application to Finite Elements of Degree \(l\)

Throughout this section we retain the hypotheses of Theorem 2.3:

(2.22) \[\operatorname{curl}\mathbf{u}\in W^{1,\,r}(\Omega),\quad\quad p\in W^{1,\,r} (\Omega)\cap L^{2}_{0}(\Omega),\]

but to simplify the discussion, we shall postpone the approximation of the pressure and discretize for the time being the stream function and vorticity alone.

We propose to adapt to Problem (2.19) the general approximation developed in Section 1.2. The _Problem_ (Q) that we want to solve is Problem (2.9):

\[\begin{split} Find\ (u=(\mathbf{curl}\,\psi,\omega),\lambda)\in X \,\times\,M\text{ such that }\\ \left\{\begin{aligned} v(\omega,\theta)-(\Delta\phi +\theta,\lambda)&=(\mathbf{f},\mathbf{curl}\,\phi)\quad\quad \forall v=(\mathbf{curl}\,\phi,\theta)\in X,\\ (\Delta\psi+\omega,\mu)&=0\quad\quad\forall\mu\in M ,\end{aligned}\right.\end{split}\] (2.9)

with the spaces

\[X=\{v=(\mathbf{curl}\,\phi,\theta);\,\phi\in\Psi,\,\theta\in L^{2}(\Omega) \},\quad\quad M=L^{2}(\Omega).\]

Then Problem (2.19) is in fact a \(Problem\) (\(\bar{\mathbb{Q}}\)) associated with (2.9). Here the spaces are:
