\[g_{h}=\sum_{i=1}^{N_{h}}g_{i}\mu_{i}\quad\text{with $g_{i}=g_{h}(a_{i})$.}\]

With this notation, (4.65) is equivalent to:

\[\sum_{j=1}^{N_{h}}\rho_{j}a_{h}(\mu_{j},\mu_{i})=-(\mathbf{grad}\,\lambda_{h}^{0 }-\mathbf{u}_{h}^{0},\mathbf{grad}\,\mu_{i})\quad\quad 1\leq i\leq N_{h}.\]

In other words we have to solve the system of linear equations:

\[A_{h}\boldsymbol{\rho}=\boldsymbol{b}\] (4.66)

where

\[(A_{h})_{i,\,j} = a_{h}(\mu_{j},\mu_{i})=(\mathbf{grad}\,\lambda_{h}(\mu_{j})- \mathbf{u}_{h}(\mu_{j}),\mathbf{grad}\,\mu_{i}),\] \[b_{i} = -(\mathbf{grad}\,\lambda_{h}^{0}-\mathbf{u}_{h}^{0},\mathbf{grad }\,\mu_{i}).\]

To compute \(\boldsymbol{b}\), we have to solve the three Dirichlet problems (4.50) to find \(\mathbf{u}_{h}^{0}\) plus the first Dirichlet problem (4.62) to obtain \(\lambda_{h}^{0}\)--a total of four Dirichlet problems. To compute the \(j^{\text{th}}\) column of the matrix \(A_{h}\) we must solve the three Dirichlet problems (4.51) with \(g_{h}=\mu_{j}\) to find \(\mathbf{u}_{h}(\mu_{j})\) plus the second problem (4.62) to get \(\lambda_{h}(\mu_{j})\)--again a total of four Dirichlet problems.

From the above considerations, it follows that the matrix \(A_{h}\) is symmetric and semi-positive definite with zero as a simple eigenvalue. Furthermore, when the nodes of \(\mathcal{T}_{h}\) are properly numbered, it can be shown that \(\operatorname{Ker}(A_{h})\) is the constant vector and that the principal block \(\widetilde{A}_{h}=(a_{h}(\mu_{j},\mu_{i}))_{1\leq i,\,j\leq N_{h}-1}\) is positive definite. Therefore, setting \(\tilde{\rho}_{N_{h}}=0\), we can solve (4.66) by the Cholesky factorisation for the first \(N_{h}-1\) components of a representative \(\boldsymbol{\tilde{\rho}}\) of \(\boldsymbol{\rho}\). Then the solution \(\rho_{h}\) of (4.65) that satisfies \(\int_{\Gamma}\rho_{h}\,ds=0\) is given by:

\[\tilde{\rho}_{h}-(1/\text{meas}(\Gamma))\int_{\Gamma}\tilde{\rho}_{h}\,ds.\]

Once \(\rho_{h}\) is known, the pressure \(p_{h}(\rho_{h})\) and velocity \(\mathbf{u}_{h}(\rho_{h})\) are computed by solving the three Dirichlet problems (4.51).

The problem (4.65) can also be solved by the conjugate-gradient algorithm (cf. Glowinski _et al. loc. cit._).
