_Remark 5.4_.: In the above definition, it is necessary to suppose that \(\mathbf{u}\) has a little more regularity than \(H^{1}(\kappa)^{3}\) because \(M_{e}(\mathbf{u})\) makes no sense when \(\mathbf{u}\) is only in \(H^{1}(\kappa)^{3}\).

These definitions will enable us to construct conforming finite elements in \(H(\mathbf{curl};\Omega)\) provided that on the one hand, the above set of moments is unisolvent on \(R_{l}\) and on the other hand, the moments \(M_{e}\) and \(M_{f}\) determine entirely the tangential components of polynomials of \(R_{l}\). This is achieved in the next lemmas.

**Lemma 5.4**.: _The total number of moments in Definition 5.1 is equal to \(N_{l}\), the dimension of \(R_{l}\):_

\[N_{l}=(1/2)l(l+2)(l+3).\]

Proof.: In view of Definition 5.1, we have:

\[\operatorname{card}(M_{e}(\mathbf{u})) =6\dim(P_{l-1}\text{ in }\mathbb{R})=6l,\] \[\operatorname{card}(M_{f}(\mathbf{u})) =8\dim(P_{l-2}\text{ in }\mathbb{R}^{2})=4l(l-1),\] \[\operatorname{card}(M_{\kappa}(\mathbf{u})) =3\dim(P_{l-3}\text{ in }\mathbb{R}^{3})=(1/2)l(l-1)(l-2).\]

On summing these three quantities we obtain \((1/2)l(l+2)(l+3)\) moments.

On the other hand, observe that the product of an arbitrary polynomial of \(\widetilde{P}_{l}^{3}\) by \(\mathbf{x}\): \(\mathbf{p}(x)\cdot\mathbf{x}\) yields an arbitrary polynomial of \(\widetilde{P}_{l+1}\). Hence the identity \(\mathbf{p}(x)\cdot\mathbf{x}\equiv 0\) amounts to \(\dim(\widetilde{P}_{l+1})\) independent conditions. Therefore

\[\dim(R_{l}) =3\dim(P_{l}\text{ in }\mathbb{R}^{3})-\dim(\widetilde{P}_{l+1})\] \[=(1/2)(l+3)(l+2)(l+1)-(1/2)(l+3)(l+2)\] \[=(1/2)(l+3)(l+2)l.\qed\]

The equality in Lemma 5.4 means that the polynomials of \(R_{l}\) are uniquely determined by their three sets of moments if and only if the zero moments define only the zero polynomial. But this unisolvence is not easily established on an arbitrary tetrahedron \(\kappa\). Therefore, we shall first prove that the zero moments are preserved by an affine transformation and subsequently work on the reference tetrahedron \(\hat{\kappa}\) whenever it is convenient.

As usual, we denote by \(F_{\kappa}\) the affine invertible transformation from \(\hat{\kappa}\) onto \(\kappa\):

\[x=F_{\kappa}(\hat{x})=B_{\kappa}\hat{x}+\mathbf{b}_{\kappa}.\]

Scalar functions defined on \(\kappa\) are transformed by a composition with \(F_{\kappa}\):

(5.25) \[\hat{\phi}=\phi\circ F_{\kappa}\quad\quad\forall\phi\text{ defined on }\kappa,\]

while vector functions defined on \(\kappa\) are transformed like gradients:

(5.26) \[\hat{\mathbf{u}}=B_{\kappa}^{T}(\mathbf{u}\circ F_{\kappa})\quad\quad\forall \mathbf{u}\text{ defined on }\kappa.\]

Recall that the unit normal and unit tangent vectors are transformed respectively
