In addition, we have the identity:

\[(\mathbf{g},\mathbf{curl}(\psi-\psi_{h}))= (\mathbf{curl}(\lambda_{g}-\lambda_{h}),\mathbf{curl}(\psi-\psi_{h}) )+(\omega-\omega_{h},\lambda_{h}-\lambda_{g})\] \[+(\mathbf{curl}(\phi_{g}-\phi_{h}),\mathbf{curl}(\omega-\omega_{h}))\] \[\forall\lambda_{h}\!\in\!\mathcal{O}_{h},\hskip 14.226378pt \forall\phi_{h}\!\in\!\mathcal{O}_{h}.\]

On the one hand, we can choose \(\lambda_{h}=P_{h}\lambda_{g}\) in the first two terms:

\[(\mathbf{curl}(\lambda_{g}-P_{h}\lambda_{g}),\mathbf{curl}(\psi-\gamma_{h}))+ (\omega-\omega_{h},P_{h}\lambda_{g}-\lambda_{g})\hskip 14.226378pt\forall \gamma_{h}\!\in\!\mathcal{O}_{h}.\]

On the other hand, we can split the third term as follows:

\[(\mathbf{curl}(\phi_{g}-\phi_{h}),\mathbf{curl}(\omega-\omega_{h}))= (\mathbf{curl}(\phi_{g}-\phi_{h}),\mathbf{curl}(\omega-P_{h}\omega))\] \[+(\mathbf{curl}(\phi_{g}-\phi_{h}),\mathbf{curl}(P_{h}\omega- \omega_{h})).\]

But

\[(\mathbf{curl}\phi_{g},\mathbf{curl}(P_{h}\omega-\omega_{h}))=(\lambda_{g},P_ {h}\omega-\omega_{h})\]

and according to (2.33) and (2.32) we have:

\[(P_{h}\omega-\omega_{h},\theta_{h})=0\hskip 14.226378pt\forall( \mathbf{curl}\,\sigma_{h},\theta_{h})\!\in\!V_{h},\] \[(\mathbf{curl}(P_{h}\omega-\omega_{h}),\mathbf{curl}\,\phi_{h})= 0\hskip 14.226378pt\forall\phi_{h}\!\in\!\mathcal{O}_{h}.\]

Therefore, collecting these equalities we obtain:

\[(\mathbf{g},\mathbf{curl}(\psi-\psi_{h}))= (\mathbf{curl}(\lambda_{g}-P_{h}\lambda_{g}),\mathbf{curl}( \psi-\gamma_{h}))+(\omega-\omega_{h},P_{h}\lambda_{g}-\lambda_{g})\] \[+(\mathbf{curl}(\phi_{g}-\phi_{h}),\mathbf{curl}(\omega-P_{h} \omega))\] \[+(\lambda_{g}-\theta_{h},P_{h}\omega-\omega_{h})\] \[\forall\gamma_{h},\,\phi_{h}\!\in\!\mathcal{O}_{h},\hskip 14.226378pt \forall(\mathbf{curl}\,\sigma_{h},\theta_{h})\!\in\!V_{h}.\]

As \(\phi_{g}\) and \(\psi\) belong at least to \(H^{2}(\Omega)\) we take

\[\chi_{h}=I_{h}\psi,\hskip 14.226378pt\phi_{h}=I_{h}\phi_{g}.\]

Then

\[|(\mathbf{curl}(\lambda_{g}-P_{h}\lambda_{g}),\mathbf{curl}( \psi-I_{h}\psi))|\leqslant C_{2}h|\lambda_{g}|_{1,\,\Omega}|\psi|_{2,\,\Omega},\] \[|(\omega-\omega_{h},P_{h}\lambda_{g}-\lambda_{g})|\leqslant C_{3}h| \omega|_{1,\,\Omega}|\lambda_{g}|_{1,\,\Omega},\] \[|(\mathbf{curl}(\phi_{g}-I_{h}\phi_{g}),\mathbf{curl}(\omega-P_{h }\omega))|\leqslant C_{4}h|\phi_{g}|_{2,\,\Omega}|\omega|_{1,\,\Omega},\] \[\inf_{(\mathbf{curl}\,\sigma_{h},\theta_{h})\!\in\!V_{h}}\| \lambda_{g}-\theta_{h}\|_{0,\,\Omega}\leqslant C_{5}(\varepsilon)h^{1/2- \varepsilon}\|\phi_{g}\|_{3,\,\Omega}\]

according to Remark 3.2 and similarly Remark 3.3 gives:

\[\|P_{h}\omega-\omega_{h}\|_{0,\,\Omega}\leqslant C_{6}(\varepsilon)h^{1/2- \varepsilon}|\omega|_{1,\,\Omega}\hskip 14.226378pt\forall\varepsilon>0.\]

By substituting these estimates into (3.19) and applying (3.18) we find (3.17).
