(4.20) \[\left\{\begin{aligned} &|\mathbf{u}-\mathbf{u}_{h}|_{1,\,\Omega}\leqslant 2(1+ \sqrt{2}/\beta^{*})\inf_{\mathbf{v}_{h}\in X_{h}}|\mathbf{u}-\mathbf{v}_{h}|_{1, \,\Omega}+\sqrt{2}\,\|\,\bar{p}-P_{h}\bar{p}\,\|_{0,\,\Omega},\\ &|\mu_{h}|_{1,\,\Omega}\leqslant\|\mathbf{u}-\mathbf{u}_{h}\|_{0, \,\Omega},\\ &\|\,\bar{p}-\bar{p}_{h}\|_{0,\,\Omega}\leqslant(1+\sqrt{2}/ \beta^{*})\inf_{q_{h}\in Q_{h}}\|\,\bar{p}-q_{h}\|_{0,\,\Omega}+(1/\beta^{*})| \mathbf{u}-\mathbf{u}_{h}|_{1,\,\Omega},\end{aligned}\right.\]

where \(P_{h}\) denotes the \(H^{1}\)-projection on \(Q_{h}\cap L^{2}_{0}(\Omega)\) defined by (A.25), \(\bar{p}\) (resp. \(\bar{p}_{h}\)) denotes the representative of \(p\) (resp. \(p_{h}\)) in \(L^{2}_{0}(\Omega)\) and \(\beta^{*}\) is the constant of the inf-sup condition. Note that (4.20) requires only the mild assumption (II.4.17) and the regularity of the triangulation \(\mathcal{T}_{h}\). Thus (3.37) follows from (4.20) and a standard density argument.

Finally, (3.38) is a consequence of (4.20) and the regularity assumption (4.18) (which is valid when \(\Omega\) is convex). More precisely, if (4.18) holds then \(\mathbf{u}\) and \(p\) have the extra regularity:

\[\mathbf{u}\in\mathbf{w}^{2,\,r}(\Omega)^{2},\qquad p\in w^{1,\,r}(\Omega).\]

Then just like in Section III.3.1 we derive:

(4.21) \[\inf_{\mathbf{v}_{h}\in X_{h}}|\mathbf{u}-\mathbf{v}_{h}|_{1,\,\Omega} \leqslant C_{1}\,h^{2/s}|\mathbf{u}|_{2,\,r,\,\Omega}\]

and if in addition \(\Omega\) is convex and \(\mathcal{T}_{h}\) is uniformly regular, Lemma III.3.4 establishes that

(4.22) \[\|\,p-P_{h}p\|_{0,\,\Omega}\leqslant C_{2}\,h^{2/s}|\ln h|^{1-2/s}|p|_{1,\,r, \,\Omega}.\]

Collecting these inequalities we obtain:

(4.23) \[|\mathbf{u}-\mathbf{u}_{h}|_{1,\,\Omega}+|\mu_{h}|_{1,\,\Omega}+\|\,\bar{p}- \bar{p}_{h}\|_{0,\,\Omega}\leqslant C_{3}\,h^{2/s}|\ln h|^{1-2/s}\|\,\mathbf{ f}\|_{0,\,r,\,\Omega}\]

which proves (3.38).

Observe also that when \(\Omega\) is convex and \(\mathcal{T}_{h}\) is uniformly regular, (4.19) and Theorem A.2 imply that:

(4.24) \[|\mu_{h}|_{1,\,\alpha,\,\Omega}\leqslant C_{4}(\alpha)\,\|\,\mathrm{div}( \mathbf{u}-\mathbf{u}_{h})\|_{0,\,\Omega}\,\quad\quad\forall\text{real }\alpha\geqslant 2.\]

Indeed, we can consider that \(\mu_{h}\) is the \(H^{1}_{0}\)-projection, \(\dot{P}_{h}\mu\), of the solution \(\mu\) of the Dirichlet problem:

\[(\mathbf{grad}\,\mu,\mathbf{grad}\,q)=-(\mathrm{div}(\mathbf{u}-\mathbf{u}_{h} ),q)\,\quad\quad\forall q\in H^{1}_{0}(\Omega).\]

Consequently, the conclusion of Theorem 3.3 is valid; it is summarized in the following theorem.

**Theorem 4.3**.: _Let \(\Omega\) be a bounded, convex polygon and assume that \(\mathcal{T}_{h}\) is a uniformly regular triangulation of \(\,\bar{\Omega}\) that satisfies (II.4.17). For \(\mathbf{f}\in L^{r}(\Omega)^{2}\), \(r\in(1,2]\), let \(\{(\dot{\lambda},\,(\dot{\mu}(\dot{\lambda}),\dot{\nu}(\dot{\lambda}),0));\, \dot{\lambda}=1/v\in\Lambda\},\) with \(p(\dot{\lambda})\) chosen in \(L^{2}_{0}(\Omega)\), be a branch of nonsingular solutions of the Navier-Stokes Problem (4.16). Then for \(h\leqslant h_{0}\) sufficiently small, there exists a unique \(\mathcal{C}^{\infty}\) branch \(\{(\dot{\lambda},(\mathbf{u}_{h}(\dot{\lambda}),\dot{\nu}_{h}(\dot{\lambda}), \mu_{h}(\dot{\lambda})));\,\dot{\lambda}\in\Lambda\},\) with \(p_{h}(\dot{\lambda})\) chosen in \(L^{2}_{0}(\Omega)\), of solutions of Problem (4.15) such that:_
