each \(\mathbf{f}\) in \(Y\) determines a unique \(T_{h}\mathbf{f}\) in \(X_{h}\) and

\[\lim_{h\to 0}\left\{\left|\mathbf{v}_{h}-\mathbf{v}\right|_{1,\Omega}+\left\|q_{ h}-q\right\|_{0,\Omega}\right\}=0,\] (4.9)

i.e.

\[\lim_{h\to 0}\left\|(T_{h}-T)\mathbf{f}\right\|_{X}=0\quad\quad\forall \mathbf{f}\in Y.\]

Furthermore, when \((\mathbf{v},q)\) belongs to \(H^{m+1}(\Omega)^{N}\times H^{m}(\Omega)\) for some integer \(m\) in \([1,l]\), this same theorem asserts that:

\[\left|\mathbf{v}_{h}-\mathbf{v}\right|_{1,\Omega}+\left\|q_{h}-q \right\|_{0,\Omega}\leqslant Ch^{m}(\left\|\mathbf{v}\right\|_{m+1,\Omega}+ \left\|q\right\|_{m,\Omega}),\] (4.10) \[\left\|(T_{h}-T)\mathbf{f}\right\|_{X}\leqslant Ch^{m}\left\|\,T \mathbf{f}\right\|_{H^{m+1}(\Omega)^{N}\times H^{m}(\Omega)}.\]

As mentioned at the end of Remark 3.4, the compactness of the imbedding of \(Z\) into \(Y\) together with (4.9) imply that

\[\lim_{h\to 0}\left\|\,T_{h}-T\right\|_{\mathcal{L}(Z;X)}=0.\]

Thus (3.37) and (3.38) hold.

Finally, since

\[a(\mathbf{u}_{h};\mathbf{u}_{h},\mathbf{v}_{h})=v(\mathbf{grad}\,\mathbf{u}_{ h},\mathbf{grad}\,\mathbf{v}_{h})+\left(\sum\limits_{j=1}^{N}u_{hj}\partial \mathbf{u}_{h}/\partial x_{j},\mathbf{v}_{h}\right),\]

we can express Problem (4.2) as follows:

\[(\mathbf{grad}\,\mathbf{u}_{h},\mathbf{grad}\,\mathbf{v}_{h})-(1/v)(p_{h}, \operatorname{div}\mathbf{v}_{h})=(1/v)\left\langle\mathbf{f}-\sum\limits_{j =1}^{N}u_{hj}\partial\mathbf{u}_{h}/\partial x_{j},\mathbf{v}_{h}\right\rangle\] \[\forall\mathbf{v}_{h}\in W_{oh},\]

\[(q_{h},\operatorname{div}\mathbf{u}_{h})=0\quad\quad\forall q_{h}\in M_{h}.\]

In other words, \(u_{h}=(\mathbf{u}_{h},(1/v)p_{h})\) satisfies:

\[u_{h}=-T_{h}G(1/v,u_{h})\]

i.e.

\[F_{h}(\lambda,u_{h})\equiv u_{h}+T_{h}G(\lambda,u_{h})=0\quad\text{ with }\lambda=1/v.\]

Consequently, we can apply the conclusion of Theorem 3.3: for \(h\leqslant h_{0}\) sufficiently small there exists _a unique branch of nonsingular solutions of (4.2)_: \(\{(\lambda,u_{h}(\lambda)=(\mathbf{u}_{h}(\lambda),\lambda p_{h}(\lambda))); \lambda\in\Lambda\},\)

i.e.

\[u_{h}(\lambda)+T_{h}G(\lambda,u_{h}(\lambda))=0\quad\quad\forall\lambda\in \Lambda,\]

and a real number \(a>0\), independent of \(h\), such that:

\[\left\|u_{h}(\lambda)-u(\lambda)\right\|_{X}\leqslant a\quad\quad\forall \lambda\in\Lambda.\]

In addition, according to Remark 3.6, the mapping \(\lambda\to u_{h}(\lambda)\) is \(\mathcal{C}^{\infty}\) because the mapping \(G\) is also \(\mathcal{C}^{\infty}\) with bounded derivatives of all order on every bounded subsets of \(\Lambda\times X\).
