unit exterior normal to \(\Omega_{i}\) on \(S\). Assume that the vector field \(\mathbf{u}\) is no longer globally smooth in \(\Omega\) but that instead,

\[\mathbf{u}|_{\Omega_{k}}\!\in\!H^{1}(\Omega_{k})^{N},\quad\mathbf{u}|_{\Gamma} =\mathbf{0},\quad\mathbf{u}\!\in\!H(\mathrm{div};\Omega)\quad\text{and}\quad \mathrm{div}\,\mathbf{u}=0.\]

Then the product \(u_{j}u_{i}\) is no longer differentiable in \(\Omega\) but its distributional derivative has the form:

\[\begin{array}[]{ll}[\partial(u_{j}u_{i})/\partial x_{j}]=&\partial(u_{j}u_{i})/ \partial x_{j}|_{\Omega_{1}\cup\Omega_{2}}\\ &+\text{ a surface distribution corresponding to the jump of the field}\\ &\mathbf{u}\text{ across the interface }S,\text{ namely:}\\ &\mathbf{u}\cdot\mathbf{n}(u_{i}^{ext}-u_{i}^{int})\,ds\end{array}\]

where \(\mathbf{n}\) and the notions of exterior and interior refer to the same region. The upwinding relies on the following principle:

_the flow in \(\Omega_{k}\) depends exclusively upon the flux entering through \(S\)._

By virtue of this principle, we introduce the notation:

(5.1) \[\partial_{-}\Omega_{k}=\{x\!\in\!S;\mathbf{u}\!\cdot\!\mathbf{n}_{k}(x)<0\}\]

for the portion of the interface \(S\) where the fluid enters \(\Omega_{k}\) and we take as a _definition_ the following expression for the convection term:

(5.2) \[\begin{array}[]{ll}\int_{\Omega}u_{j}(\partial u_{i}/\partial x_{j})v_{i}\,dx \overset{\mathrm{def}}{=}\\ \sum\limits_{k=1}^{2}\int_{\Omega_{k}}u_{j}(\partial u_{i}/\partial x_{j})v_{i} \,dx\,+\sum\limits_{k=1}^{2}\int_{\partial_{-}\Omega_{k}}\mathbf{u}\!\cdot\! \mathbf{n}_{k}(u_{i}^{ext}-u_{i}^{int})v_{i}^{int}\,ds\end{array}\]

for all \(\mathbf{u}\) in \(H(\mathrm{div};\Omega)\) with \(\mathrm{div}\,\mathbf{u}=0\), \(\mathbf{u}|_{\Omega_{k}}\!\in\!H^{1}(\Omega_{k})^{N}\) and \(\mathbf{v}|_{\Omega_{k}}\!\in\!H^{1}(\Omega_{k})^{N}\). Clearly, when \(\mathbf{u}\) and \(\mathbf{v}\) belong to \(H^{1}(\Omega)^{N}\), the surface term vanishes and we recover the familiar expression for the convection. But when \(\mathbf{u}\) and \(\mathbf{v}\) are not globally in \(H^{1}\) we have to interpret (5.2) as a definition.

Figure 21:
