_Remark 2.3_.: The same analysis with analogous conclusions can be carried out with vector potentials in the space:

\[\Psi_{1}=\langle\phi\in L^{2}(\Omega)^{3};\,\mathrm{div}\,\phi\in H^{1}(\Omega), \,\mathbf{curl}\,\phi\in H^{1}_{0}(\Omega)^{3},\,\phi\cdot\mathbf{n}|_{\Gamma}= \mathbf{0}\rangle.\]

## SS3. Approximation of Branches of Nonsingular Solutions

As proved in the preceding paragraph, the Navier-Stokes equations have in general more than one solution, unless the data (namely, the viscosity and external forces) satisfy very stringent requirements. However, it can also be shown that in many practical examples these solutions are mostly isolated, i.e. there exists a neighborhood in which each solution is unique. Furthermore, it can be established that the solutions depend continuously on the viscosity. Thus, as the viscosity varies along an interval, each solution of the Navier-Stokes equations describes an isolated branch. In particular, this means that the bifurcation phenomenon is rare. This situation, very frequently encountered in practice, is expressed mathematically by the notion of branches of nonsingular solutions.

This paragraph proposes and analyzes several approximations of branches of nonsingular solutions pertaining to a wide class of nonlinear problems, including the Navier-Stokes problem. The analysis, based on a general form of the implicit function theorem, is a variant of a broader theory developed by Brezzi, Rappaz & Raviart [14]. The version that we present here is due to Crouzeix [22].

### An Abstract Framework

Let \(X\) and \(\mathcal{X}\) be two Banach spaces and \(\Lambda\) a compact interval of the real line \(\mathbb{R}\). We are given a \(\mathcal{C}^{p}\)-mapping (\(p\geqslant 1\))

\[F\colon(\dot{\lambda},u)\in\Lambda\,\times\,X\to F(\lambda,u)\in\mathcal{X}\]

and we want to solve the equation

(3.1) \[F(\dot{\lambda},u)=0,\]

i.e. we want to find pairs \((\dot{\lambda},u)\in\Lambda\,\times\,X\) solutions of (3.1).

Let \(\{(\dot{\lambda},u(\dot{\lambda}));\dot{\lambda}\in\Lambda\}\) be a branch of solutions of equation (3.1). This means that

(3.2) \[\dot{\lambda}\to u(\dot{\lambda})\text{ is a continuous function from }\Lambda\text{ into }X;\]

(3.3) \[F(\dot{\lambda},u(\dot{\lambda}))=0.\]

Moreover, we suppose that these solutions are _nonsingular_ in the sense that:

(3.4) \[D_{u}F(\dot{\lambda},u(\dot{\lambda}))\text{ is an isomorphism from }X\text{ onto }\mathcal{X}\text{ for all }\dot{\lambda}\in\Lambda.\]

As an immediate consequence of (3.4), it follows from the implicit function theorem that \(\dot{\lambda}\to u(\dot{\lambda})\) is a \(\mathcal{C}^{p}\)-function from \(\Lambda\) into \(X\).
