### Mixed Approximation and Application to Finite Elements of Degree \(l\)

The Technique of Mesh-Dependent Norms

Further Topics on the "Stream Function-Vorticity-Pressure" Scheme

Refinement of the Error Analysis

Super Convergence Using Quadrilateral Finite Elements of Degree \(l\)

A "Stream Function-Gradient of Velocity Tensor" Method in Two Dimensions

The Hellan-Herrmann-Johnson Formulation

Approximation with Triangular Finite Elements of Degree \(l\)

Additional Results for the Hellan-Herrmann-Johnson Scheme

Discontinuous Approximation of the Pressure

A "Vector Potential-Vorticity" Scheme in Three Dimensions

A Mixed Formulation of the Three-Dimensional Stokes Problem

Mixed Approximation in \(H(\mathbf{curl};\Omega)\)

A Family of Conforming Finite Elements in \(H(\mathbf{curl};\Omega)\)

A Error Analysis for Finite Elements of Degree \(l\)

Discontinuous Approximation of the Pressure

Theory and Approximation of the Navier-Stokes Problem

A Class of Nonlinear Problems

Theory of the Steady-State Navier-Stokes Equations

The Dirichlet Problem in the Velocity-Pressure Formulation

The Stream Function Formulation of the Homogeneous Problem

Approximation of Branches of Nonsingular Solutions

An Abstract Framework

Approximation of Branches of Nonsingular Solutions

Application to a Class of Nonlinear Problems

Non-Differentiable Approximation of Branches of Nonsingular Solutions

Non-Differentiable Approximation of Branches of Nonsingular Solutions

Numerical Analysis of Centered Finite Element Schemes

Numerical Analysis of Centered Finite Element Schemes

Formulation in Primitive Variables: Methods Using Discontinuous

Formulations

Formulations in Primitive Variables: the Case of Continuous

Formulations

Mixed Incompressible Methods: the "Stream Function-Vorticity"

Formulation

Remarks on the "Stream Function-Gradient of Velocity Tensor"

Scheme
