Table of Contents

* 1 Generalities on Some Elliptic Boundary Value Problems * 1.1 Basic Concepts on Sobolev Spaces * 1.2 Abstract Elliptic Theory * 1.3 Example 1: Dirichlet's Problem for the Laplace Operator * 1.4 Example 2: Neumann's Problem for the Laplace Operator * 1.5 Example 3: Dirichlet's Problem for the Biharmonic Operator
* 2 Function Spaces for the Stokes Problem * 2.1 Preliminary Results * 2.2 Some Properties of Spaces Related to the Divergence Operator * 2.3 Some Properties of Spaces Related to the Curl Operator
* 3 A Decomposition of Vector Fields * 3.1 Decomposition of Two-Dimensional Vector Fields * 3.2 Application to the Regularity of Functions of \(H(\operatorname{div};\Omega)\cap H(\operatorname{\textbf{curl}};\Omega)\) * 3.3 Decomposition of Three-Dimensional Vector Fields * 3.4 The Imbedding of \(H(\operatorname{div};\Omega)\cap H_{0}(\operatorname{\textbf{curl}};\Omega)\) into \(H^{1}(\Omega)^{3}\) * 3.5 The Imbedding of \(H_{0}(\operatorname{div};\Omega)\cap H(\operatorname{\textbf{curl}};\Omega)\) into \(H^{1}(\Omega)^{3}\)
* 4 Analysis of an Abstract Variational Problem * 4.1 A General Result * 4.2 A Saddle-Point Approach * 4.3 Approximation by Regularization or Penalty * 4.4 Iterative Methods of Gradient Type
* 5 The Stokes Equations * 5.1 The Dirichlet Problem in the Velocity-Pressure Formulation * 5.2 The Stream Function Formulation of the Dirichlet Problem in Two Dimensions * 5.3 The Three-Dimensional Case

## 1
