## Chapter IV. Theory and Approximation of the Navier-Stokes Problem

### 1. A Class of Nonlinear Problems

In this paragraph, we study a nonlinear generalization of the abstract variational problem analyzed in Paragraph I.4. This family of nonlinear problems contains in particular the Navier-Stokes problem.

We retain the notations of Paragraph I.4. Namely, we consider two (real) Hilbert spaces \(X\) and \(M\) normed by \(\|\,.\,\|_{X}\) and \(\|\,.\,\|_{M}\) respectively and a bilinear continuous form

\[b(.,.)\colon(v,\mu)\in X\,\times\,M\to b(v,\mu)\in\mathbb{R}.\]

The nonlinearity is introduced by means of a form

\[a(.;.,.)\colon(u,v,w)\in X\,\times\,X\,\times\,X\to a(w;u,v)\in\mathbb{R}\]

where, for \(w\in X\), the mapping \((u,v)\to a(w;u,v)\) is a bilinear continuous form on \(X\,\times\,X\).

Then, we consider the following problem, also called _Problem_ (Q):

_Given \(l\in X^{\prime}\), find a pair \((u,\lambda)\in X\,\times\,M\) satisfying_

(1.1) \[a(u;u,v)+b(v,\lambda) =\langle l,v\rangle\quad\quad\forall v\in X,\] (1.2) \[b(u,\mu) =0\quad\quad\forall\mu\in M.\]

Let us introduce the linear operators \(A(w)\in\mathcal{L}(X;X^{\prime})\) for \(w\) in \(X\), and \(B\in\mathcal{L}(X;\,M^{\prime})\) defined by:

\[\langle A(w)u,v\rangle =a(w;u,v)\quad\quad\forall u,\,v\in X,\] \[\langle Bv,\mu\rangle =b(v,\mu)\quad\quad\forall v\in X,\quad\quad\forall\mu\in M.\]

With these notations, Problem (Q) becomes:

_Find \((u,\lambda)\in X\,\times\,M\) such that_

(1.3) \[A(u)u+B^{\prime}\lambda =l\quad\text{in }X^{\prime},\] (1.4) \[Bu =0\quad\text{in }M^{\prime}.\]
