Likewise, it is easy to see that all polynomials of \(S_{2}\) must necessarily be of the form:

\[\mathbf{p}(x)=\sum_{i,j=1}^{3}\alpha_{ij}x_{j}\mathbf{p}_{i}(x)\quad\text{with the above }\mathbf{p}_{i}.\]

But the nine polynomials \(x_{j}\mathbf{p}_{i}(x)\) are not all linearly independent, for they are linked by one relation:

\[\sum_{i=1}^{3}x_{i}\mathbf{p}_{i}(x)=\mathbf{x}\times\mathbf{x}=\mathbf{0}.\]

Thus we can suppress one of these polynomials and it can be readily checked that the remaining eight are linearly independent. For example, we can take for \(S_{2}\) the following eight basis functions:

\[x_{1}\mathbf{p}_{1},\quad x_{2}\mathbf{p}_{1},\quad x_{3}\mathbf{p}_{1},\quad x _{1}\mathbf{p}_{2},\quad x_{2}\mathbf{p}_{2},\quad x_{3}\mathbf{p}_{2},\quad x _{1}\mathbf{p}_{3},\quad x_{2}\mathbf{p}_{3}.\]

The space \(R_{l}\) has the following attractive property.

**Lemma 5.3**.: _If the vector field \(\mathbf{u}\!\in\!R_{l}\) satisfies \(\mathbf{curl}\,\mathbf{u}=\mathbf{0}\) then_

\[\mathbf{u}=\mathbf{grap}\,p\quad\text{with }p\!\in\!P_{l}.\]

Proof.: First observe that each \(f\!\in\!\bar{P}_{l}\) satisfies

\[\mathit{lf}=\mathbf{grad}\,f\!\cdot\mathbf{x}.\]

Now, we know that \(\mathbf{u}=\mathbf{grad}\,p\) with \(p\!\in\!P_{l+1}\). Therefore, the term in \(\mathbf{grad}\,p\) that belongs to \(S_{l}\) vanishes according to the definition (5.24). Hence \(p\) has no term of degree \(l+1\). 

_Remark 5.3_.: The definition of \(R_{l}\) can obviously be extended to an arbitrary dimension \(N\). Then the statement of Lemma 5.3 is also valid for all dimensions. 

**Definition 5.1**.: Let \(\kappa\) be a tetrahedron in \(\mathbb{R}^{3}\) with edges denoted by \(e\) and faces by \(f\) and let \(\mathbf{u}\) be a function in \(W^{1,s}(\kappa)^{3}\) for some \(s>2\). We define the three sets of moments of \(\mathbf{u}\) on \(\kappa\):

\[M_{e}(\mathbf{u})=\biggl{\{}\int_{e}(\mathbf{u}\cdot\tau)q\,de\quad\forall q \!\in\!P_{l-1}(e)\,\text{for all edges }e\text{ of }\kappa\biggr{\}},\]

where \(\tau\) denotes the unit vector of \(e\);

\[M_{f}(\mathbf{u})=\biggl{\{}\int_{f}(\mathbf{u}\times\mathbf{n}) \cdot\mathbf{q}\,ds\quad\forall\mathbf{q}\!\in\!P_{l-2}^{2}(f)\,\text{for all faces }f\text{ of }\kappa\biggr{\}};\] \[M_{\kappa}(\mathbf{u})=\biggl{\{}\int_{\kappa}\mathbf{u}\cdot \mathbf{q}\,dx\quad\forall\mathbf{q}\!\in\!P_{l-3}^{3}(\kappa)\biggr{\}}.\]
