**Lemma 3.7**.: _If \(U\) is continuously imbedded into \(H^{1}(\Omega)^{3},\) then for each \(\psi\in H^{1}(\Omega)^{3}\) with \(\int_{\Gamma}\psi\cdot\mathbf{n}\,ds=0,\) the solution \(\chi\) of the non-homogeneous Neumann's problem:_

(3.39) \[\Delta\chi=0\quad\text{in }\Omega,\quad\ \ \partial\chi/\partial n=\psi\cdot \mathbf{n}\quad\text{on }\Gamma\]

_belongs to \(H^{2}(\Omega)/\mathbb{R}.\) Conversely, when \(\Omega\) is simply-connected, this condition is sufficient for the above imbedding._

Proof.: \(1^{\circ})\) Let \(\psi\in H^{1}(\Omega)^{3}\) with \(\int_{\Gamma}\psi\cdot\mathbf{n}\,ds=0;\) then (3.39) has a unique solution \(\chi\) in \(H^{1}(\Omega)/\mathbb{R}\) and

\[\phi=\psi-\mathbf{grad}\,\chi\]

belongs to \(U.\) Therefore, if \(\phi\) belongs to \(H^{1}(\Omega)^{3},\) then \(\chi\) is necessarily in \(H^{2}(\Omega)/\mathbb{R}.\)

\(2^{\circ})\) Conversely, we derive from the proof of Theorem 3.5 that, if \(\chi\in H^{2}(\Omega)/\mathbb{R},\) then each function of \(T\) has a unique vector potential in \(U_{0}\cap H^{1}(\Omega)^{3}.\) Hence Lemmas 3.5 and 3.6 imply that \(U\) is continuously imbedded in \(H^{1}(\Omega)^{3}.\) 

Now, when \(\Gamma\) is \(\mathscr{C}^{1,\,1},\) the solution of (3.39) belongs indeed to \(H^{2}(\Omega)/\mathbb{R}\) and therefore Lemma 3.7 guarantees that \(U\subsetneq H^{1}(\Omega)^{3},\) provided that \(\Omega\) is simply-connected. Furthermore, this last restriction can be removed by using the argument of Theorem 3.7,\(2^{\circ}).\) Thus, we have established the following result.

**Theorem 3.8**.: _If \(\Omega\) is bounded and has a \(\mathscr{C}^{1,\,1}\) boundary, then the space \(U\) is continuously imbedded in \(H^{1}(\Omega)^{3}.\)_

Unfortunately, when \(\Gamma\) is a polyhedron and \(\psi\) belongs to \(H^{1}(\Omega)^{3},\) its normal component \(\psi\cdot\mathbf{n}\) is not in \(H^{1/2}(\Gamma)\) and we have not been able to find in the literature any direct information about the regularity of the solution of (3.39). In this case, Lemma 3.7 seems to be of no help and we propose to establish the imbedding of \(U\) into \(H^{1}(\Omega)^{3}\) by means of a different argument due to Nedelec [60]. Briefly speaking, this author uses a particular equivalence of norms which, on a smooth and convex domain \(\Omega,\) holds with _constants independent_ of \(\Omega.\) Then, he extends this equivalence to convex polyhedrons by regularizing their boundaries. The starting point of this approach is the following technical lemma; the proof, which is too long to be included here, can be found in Grisvard [42].

**Lemma 3.8**.: _Let \(\Omega\) be a bounded open subset of \(\mathbb{R}^{3}\) with a \(\mathscr{C}^{2}\) boundary \(\Gamma.\) Every function \(\phi\) of \(H^{1}(\Omega)^{3}\) with \(\phi\cdot\mathbf{n}=0\) on \(\Gamma\) satisfies:_

(3.40) \[|\phi|_{1,\,\Omega}^{2}+\int_{\Gamma}(\mathscr{R}\phi,\phi)\,ds=\|\,\mathbf{ curl}\,\phi\|_{0,\,\Omega}^{2}+\|\,\mathrm{div}\,\phi\,\|_{0,\,\Omega}^{2},\]

_where \(\mathscr{R}\) denotes the curvature tensor on the tangent plane to \(\Gamma.\)_

Since the curvature tensor \(\mathscr{R}\) is positive definite when \(\Omega\) is convex, we derive immediately the equivalence of norms:
