\[\mathbf{u}_{h}=\mathbf{curl}\,r_{h}\phi,\]

i.e.

\[\mathbf{curl}(\phi-r_{h}\phi)=\mathbf{0}\quad\text{in }\Omega.\]

On the one hand, observe that \(\mathbf{curl}(\phi-r_{h}\phi)|_{\kappa}\!\in\!P_{l-1}^{3}(\kappa)\). On the other hand, we have

\[\int_{\kappa}\mathbf{curl}(\phi-r_{\kappa}\phi)\!\cdot\!\mathbf{ q}\,dx=0\quad\quad\forall\mathbf{q}\!\in\!P_{l-2}^{3}(\kappa),\] \[\mathbf{curl}(\phi-r_{\kappa}\phi)\!\cdot\!\mathbf{n}=0\quad \text{on each face }f\text{ of }\kappa.\]

Hence like in Lemma 5.8, we deduce:

\[\mathbf{curl}(\phi-r_{\kappa}\phi)=\mathbf{0}\quad\text{in each }\kappa\text{ of } \mathcal{T}_{h}\]

and since \(\phi-r_{h}\phi\) belongs to \(H(\mathbf{curl};\Omega)\), its \(\mathbf{curl}\) vanishes on the whole of \(\Omega\).

It remains to establish that when \(\mathbf{u}_{h}\!\cdot\!\mathbf{n}\) vanishes on \(\Gamma\) then \(\phi_{h}\) may be chosen such that \(\phi_{h}\times\mathbf{n}=\mathbf{0}\) on \(\Gamma\). The proof follows the lines of Theorem I.3.6. We take an open ball \(\mathscr{O}\) containing \(\Omega\); then, it is easy to construct a function \(q\) in \(H^{2}(\mathscr{O})\) such that

\[\mathbf{grad}\,q\times\mathbf{n}=\phi\times\mathbf{n}\quad\text{on }\Gamma.\]

Note that this requires no regularity on \(\Omega\) since \(\mathbf{grad}\,q\) need not be divergence-free. As \(q\) belongs to \(H^{2}(\Omega)\), \(r_{h}\,\mathbf{grad}\,q\) is well defined and therefore \(r_{h}(\phi-\mathbf{grad}\,q)\) is the desired potential vector of \(\mathbf{u}_{h}\) in \(\mathcal{P}_{h}\). 

**Remark 5.9**: _According to Corollary 5.1, for each divergence-free vector field \(\mathbf{u}_{h}\) in \(D_{0h}\) there exists a unique vector potential \(\phi_{h}\) in \(\mathcal{P}_{h0}\) such that:_

\[\mathbf{u}_{h}=\mathbf{curl}\,\phi_{h}.\]

_In addition, under the hypotheses of Proposition 5.1, we have:_

\[\|\phi_{h}\|_{H(\mathbf{curl};\Omega)}\leqslant C\|\mathbf{u}_{h}\|_{0, \Omega}.\]

_With this lemma and the statement of Problem (5.16), we can formulate the corresponding problem in \(\mathbf{u}_{h}\), \(\omega_{h}\), \(p_{h}\):_

_Find a pair \((\mathbf{u}_{h},\omega_{h})\) in \(D_{0h}\times M_{h}\) and a function \(p_{h}\) in \(Q_{h}\) such that:_

(5.55) \[\left\{\begin{aligned} v(\mathbf{curl}\,\omega_{h}, \mathbf{v}_{h})-(p_{h},\operatorname{div}\,\mathbf{v}_{h})&=( \mathbf{f},\mathbf{v}_{h})\quad\quad\forall\mathbf{v}_{h}\!\in\!D_{0h},\\ (\mathbf{u}_{h},\mathbf{curl}\,\mathbf{\mu}_{h})&=( \omega_{h},\mathbf{\mu}_{h})\quad\quad\forall\mathbf{\mu}_{h}\!\in\!M_{h},\\ \operatorname{div}\,\mathbf{u}_{h}&=0\quad\text{in } \Omega.\end{aligned}\right.\]

_The existence and uniqueness of \(p_{h}\) is a consequence of the following lemma which establishes the inf-sup condition relative to the space \(D_{0h}\times M_{h}\) and \(Q_{h}\). Then Lemma 5.11 implies the equivalence between this problem and (5.15) or (5.16). Therefore when \(\Omega\) is a bounded polyhedron, Problem (5.55) has a unique solution \((\mathbf{u}_{h},\omega_{h},p_{h})\)._
