we set

\[u_{i,\,j}=\,-\,h(\vec{V}_{1}\,q)_{i,\,j},\quad\,\,v_{i,\,j}=\,-\,h(\vec{V}_{2}\,q) _{i,\,j}\]

on all remaining nodes \((i,j)\) of \(\mathcal{C}_{\alpha,\,\beta}\) (i.e. \((\alpha\,\pm\,1,\beta),(\alpha,\beta\,\pm\,1)\)). We can easily see that

\[(\vec{V}_{k}\,q^{1})_{i,\,j}(\vec{V}_{k}\,q^{4})_{i,\,j}=0\quad\text{for $k=1,2$, on all such nodes $(i,j)$.}\]

Hence the resulting function \(\vec{v}\) belongs to \(\vec{V}_{h}\) and satisfies

\[\int_{\mathcal{C}_{\alpha,\,\beta}}q\,\mathrm{div}\,\vec{v}\,dx=h\sum_{i,\,j} \{|u_{i,\,j}|^{2}\,+\,|v_{i,\,j}|^{2}\}.\]

Then (3.35) follows from the inequality:

\[|\vec{v}_{h}|_{1,\,\mathcal{C}_{\alpha,\,\beta}}\leqslant C_{1}\biggl{(}\sum_ {i,\,j}\{|u_{i,\,j}|^{2}\,+\,|v_{i,\,j}|^{2}\}\biggr{)}^{1/2},\]

with a constant \(C_{1}\) independent of \(h,\,\alpha\) and \(\beta\), and

\[\sum_{i,\,j}\{|u_{i,\,j}|^{2}\,+\,|v_{i,\,j}|^{2}\}\geqslant 2\sum_{I,\,J}|q_{I, \,J}|^{2}\]

considering that \(\sum_{I,\,J}q_{I,\,J}=0\) since \(q\,\in L_{0}^{2}(\mathcal{C}_{\alpha,\,\beta})\). 

Lemmas 3.7, 3.8 and 3.9 yield immediately the next result.

**Theorem 3.4**.: _Assume that \(\Omega\) can be partitioned into groups \(\mathcal{C}_{\alpha,\,\beta}\) of four macroelements like in Figure 16. Then the pair \((\vec{V}_{h},\vec{M}_{h})\) defined by (3.33) and (3.32) satisfies a uniform inf-sup condition._

_Remark 3.1_.: The argument of Lemma 3.8 can be used directly to show that the pair \((X_{h},\vec{M}_{h})\) satisfies a uniform inf-sup condition but this does not imply that \((\vec{V}_{h},\vec{M}_{h})\) satisfies it as well.

_Remark 3.2_.: The above analysis does not apply directly to arbitrary quadrilaterals. Usually, the "checkerboard" spurious pressure disappears from \(M_{h}\) but the inf-sup condition is not satisfied (cf. Sani et al [70]). However, it is possible to derive similar results for special quadrilateral meshes (cf. Pitkaranta & Stenberg [65]).

### Error Estimates for the \(Q_{1}\)-\(P_{0}\) Element

The object of this section is to show that, although it does not satisfy the inf-sup condition, the pair of spaces \((X_{h},M_{h})\) can still be used to compute successfully the velocity \(\vec{u}\) and (with some precautions) the pressure \(p\). For this purpose, the statement of Theorem 3.4 will play a crucial role.

Let \((\vec{u}_{h},p_{h})\,\in\,X_{h}\,\times\,M_{h}\) be a solution of:
