\(a_{1}(.;.,.)\). When \(\mathbf{u}=\mathbf{curl}\,\psi\) with \(\psi\) in \(\mathcal{P}_{s}\cap H^{2}(\Omega)\), formula (2.26) yields:

\[(u_{j}\partial u_{i}/\partial x_{j},v_{i})=(\operatorname{curl}\,\mathbf{u}\, \mathbf{grad}\,\psi,\mathbf{v})\quad\quad\forall\mathbf{v}=\mathbf{curl}\, \phi,\quad\ \phi\in\mathcal{P}_{s}.\]

Hence

\[a_{1}(u,u,\mathbf{v})=(\omega\,\mathbf{grad}\,\psi,\mathbf{v})\]

provided \(\psi\) has the regularity \(H^{2}\). Of course, when \(u\) belongs only to \(X\) this equality does not hold but we can extend \(G\) to \(X\) by regularizing the function \(u\). Thus we define for all \(u\) in \(X\):

(5.36) \[\langle G(u),\mathbf{v}\rangle=a_{1}(u;Pu,\mathbf{v})-\langle\mathbf{f}, \mathbf{v}\rangle\quad\quad\forall\mathbf{v}\in L^{s}(\Omega)^{2}.\]

Since \(Pu=u\) for all \(u\) in \(V\), this definition coincides with (5.6) when \(u\in V\) and \(\mathbf{v}=\mathbf{curl}\,\phi,\phi\in\mathcal{P}_{s}\). Furthermore, it can be readily checked that (5.36) defines a \(\mathcal{C}^{\infty}\)-mapping \(G\): \(X\to Y\) whose derivative \(DG(u)\in\mathcal{L}(X;\,Y)\) is given by the expression:

(5.37) \[\langle DG(u)\cdot v,\mathbf{w}\rangle=a_{1}(u;Pu,\mathbf{w})+a_{1}(v;Pu, \mathbf{w})\quad\quad\forall\mathbf{w}\in L^{s}(\Omega)^{2}.\]

Finally, it can be proved that \(u\) is a nonsingular solution of (5.7) whenever \(u\) is also a nonsingular solution of the Navier-Stokes problem with \(G\) defined by (5.36), and conversely.

Let us check the assumptions of Theorem 3.8. It follows readily from (5.10) that

(5.38) \[\|\,T_{h}l\|_{X}\leqslant(1+C_{s})^{2}\,\|\,l\|_{h}\quad\quad\forall l\in Y_{ h},\]

where \(C_{s}\) denotes the constant of (5.20). Next, (3.60) has already been checked in Section 4.3: owing to the regularity condition (4.18) \(T_{h}\mathbf{f}=(\mathbf{curl}\,\psi_{h},\omega_{h})\) satisfies the error estimate

(5.39) \[|\psi-\psi_{h}|_{1,s,\Omega}+\|\,\omega-\omega_{h}\|_{0,\Omega}\leqslant Ch^{ \bullet}\|\,\mathbf{f}\|_{0,t,\Omega},\]

where \(r\leqslant t<2\), \(1/\gamma+1/t=1\), \(\alpha=1/\gamma\) when \(l=1\) and \(\alpha=2/\gamma\) when \(l\geqslant 2\).

Likewise, the approximation properties of the operator \(\pi_{h}\) have been derived in Section III.3.1. Indeed, for \(v=(\mathbf{curl}\,\phi,\theta)\in V\) we take

(5.40) \[\pi_{h}v=(\mathbf{curl}(\mathring{P}_{h}\phi),\theta_{h})\in V_{h},\]

i.e. \(\theta_{h}\) is determined by

\[(\theta_{h},\mu_{h})=(\mathbf{curl}(\mathring{P}_{h}\phi),\mathbf{curl}\,\mu_ {h})\quad\quad\forall\mu_{h}\in\Theta_{h}.\]

Then

\[\|\,\pi_{h}v-v\,\|_{X}\leqslant|\mathring{P}_{h}\phi-\phi|_{1,s, \Omega}+2\inf_{\mu_{h}\in\,\Theta_{h}}\|\,\mu_{h}-\theta\,\|_{0,\Omega}\] \[\qquad\qquad\qquad\qquad+\sup_{\mu_{h}\in\,\Theta_{h}}\frac{( \mathbf{curl}(\mathring{P}_{h}\phi-\phi),\mathbf{curl}\,\mu_{h})}{\|\,\mu_{h} \|_{0,\Omega}}.\]

Therefore Lemma III.3.2, Theorem A.2 and a standard density argument yield

\[\lim_{h\to 0}\|\pi_{h}v-v\,\|_{X}=0\quad\quad\forall v\in V.\]
