(5.27) \[\mathbf{n}\circ F_{\kappa} =[(B_{\kappa}^{-1})^{T}\cdot\hat{\mathbf{u}}]/\|(B_{\kappa}^{-1})^{T }\cdot\hat{\mathbf{u}}\|,\] (5.28) \[\tau\circ F_{\kappa} =[B_{\kappa}\cdot\hat{\tau}]/\|B_{\kappa}\cdot\hat{\tau}\|.\]

The main reason for adopting the transformation (5.26) is that it preserves the **curl** in a certain sense. Indeed, let us introduce the matrices

(5.29) \[C =(c_{ij})_{i,\,j}=(\partial u_{j}/\partial x_{i}-\partial u_{i}/ \partial x_{j})_{i,\,j},\] \[\hat{C} =(\hat{c}_{ij})_{i,\,j}=(\partial\hat{u}_{j}/\partial\hat{x}_{i}- \partial\hat{u}_{i}/\partial\hat{x}_{j})_{i,\,j}.\]

Then by expanding the formula (5.26) we easily derive that the matrices \(C\) and \(\hat{C}\) are related by:

(5.30) \[C\circ F_{\kappa}=(B_{\kappa}^{-1})^{T}\hat{C}(B_{\kappa}^{-1}).\]

As a consequence, \(\mathbf{curl}\,\mathbf{u}\) and \(\mathbf{curl}\,\hat{\mathbf{u}}\) vanish always simultaneously.

Besides that, the transformation (5.26) preserves the space \(R_{l}\).

**Lemma 5.5**.: _The space \(R_{l}\) is invariant under the transformation (5.26)._

Proof.: Clearly (5.26) preserves the space \(P_{k}^{3}\) for arbitrary \(k\); hence we need only consider \(\mathbf{u}\) in \(S_{l}\). Formula (5.26) reads:

\[\hat{\mathbf{u}}(\hat{x}) =B_{\kappa}^{T}\mathbf{u}(B_{\kappa}\hat{x}+\mathbf{b}_{\kappa})\] \[=B_{\kappa}^{T}\mathbf{u}(B_{\kappa}\hat{x})+\mathbf{p}(\hat{x})\]

where the degree of \(\mathbf{p}\) is strictly less than \(l\) and \(B_{\kappa}^{T}\mathbf{u}(B_{\kappa}\hat{x})\!\in\!\bar{P}_{l}^{3}\). Now,

\[B_{\kappa}^{T}\mathbf{u}(B_{\kappa}\hat{x})\!\cdot\!\hat{x}=\mathbf{u}(B_{ \kappa}\hat{x})\!\cdot\!(B_{\kappa}\hat{x})=0\]

since \(\mathbf{u}\!\in\!S_{l}\). Hence \(\hat{\mathbf{u}}\!\in\!R_{l}\) on \(\hat{\kappa}\). Conversely, the same argument shows that if \(\hat{\mathbf{u}}\!\in\!R_{l}\) on \(\hat{\kappa}\) then \(\mathbf{u}\!\in\!R_{l}\) on \(\kappa\). 

**Lemma 5.6**.: _The three sets of moments of a function \(\mathbf{u}\) given by Definition 5.1 vanish on \(\kappa\) iff the moments of \(\hat{\mathbf{u}}\) vanish on \(\hat{\kappa}\)._

Proof.: In view of (5.26) we have:

\[\int_{\kappa}\mathbf{u}\!\cdot\!\mathbf{q}\,dx=|\det(B_{\kappa})|\int_{\hat{ \kappa}}\hat{\mathbf{u}}\cdot(B_{\kappa}^{-1})(\mathbf{q}\circ F_{\kappa})\,d \hat{x}.\]

Hence

\[\int_{\kappa}\mathbf{u}\!\cdot\!\mathbf{q}\,dx=0\quad\quad\forall\mathbf{q}\! \in\!P_{l-3}^{3}(\kappa)\!\Leftrightarrow\int_{\hat{\kappa}}\hat{\mathbf{u}} \cdot\hat{\mathbf{q}}\,d\hat{x}=0\quad\quad\forall\hat{\mathbf{q}}\!\in\!P_{l- 3}^{3}(\hat{\kappa}).\]

Next, observe that every vector \(\mathbf{q}\) of \(\mathbb{R}^{3}\) satisfies

\[\mathbf{u}\times\mathbf{n}\!\cdot\!\mathbf{q}=-\mathbf{q}\times\mathbf{n}\! \cdot\!\mathbf{u}.\]

Furthermore, all tangent vectors \(\mathbf{q}\) to the affine variety \(f\) with normal \(\mathbf{n}\) (i.e. \(\mathbf{q}\) is characterized by \(\mathbf{q}\cdot\mathbf{n}=0\)) are of the form \(\mathbf{q}=\mathbf{p}\times\mathbf{n}\) for arbitrary \(\mathbf{p}\) of \(\mathbb{R}^{3}\). Hence
