This proposition has interesting consequences and calls for some comments.

_Remark 3.4_.: There exist polygonal domains \(\Omega\) with reentrant corners for which the solution \(q\) of (3.16) is not in \(H^{2}(\Omega)\) (cf. Grisvard [42]). Thus, it suffices to take \(\phi=0\) in (3.8) to obtain a function \(\mathbf{v}\) of \(U\) that does not belong to \(H^{1}(\Omega)^{2}\). Therefore, the condition on the angles of polygonal domains is in general both necessary and sufficient.

_Remark 3.5_.: Let \(\Omega\) be _simply-connected_ and like in Proposition 3.1. Then, since \(p=0\), we infer from (3.17) that the following equivalence holds in \(U\):

(3.19) \[\|\mathbf{v}\|_{1,\Omega}\cong\|\operatorname{div}\mathbf{v}\|_{0,\Omega}+\| \operatorname{curl}\mathbf{v}\|_{0,\Omega}.\]

In turn, this implies that \(H\cap\operatorname{Ker}(\operatorname{\mathbf{curl}})=\{\mathbf{0}\}\), as was previously mentioned in Remark 2.2.

On the other hand, if \(\Omega\) is not simply-connected the equivalence (3.19) is no longer true for there exist non zero functions in \(H\cap\operatorname{Ker}(\operatorname{\mathbf{curl}})\).

_Remark 3.6_.: Assume \(\Omega\) is like in Proposition 3.1. Let \(P\in\mathcal{L}(H^{1}(\Omega);H^{1}(\mathbb{R}^{2}))\) be the extension operator of Theorem 1.2, \(3^{\circ}\)). Then \(P\) applied to each component of functions of \(U\) (or \(W\)) is also an extension from \(U\) (or \(W\)) into \(H^{1}(\mathbb{R}^{2})^{2}\).

### Decomposition of Three-Dimensional Vector Fields

**Theorem 3.4**.: _A vector field \(\mathbf{v}\in L^{2}(\Omega)^{3}\) satisfies_

(3.1) \[\operatorname{div}\mathbf{v}=0,\quad\ \ \left\langle\mathbf{v}\operatorname{ \boldsymbol{\cdot}}\mathbf{n},1\right\rangle_{\Gamma_{i}}=0\quad\text{for }0\leqslant i\leqslant p\]

_if and only if there exists a vector potential \(\phi\) in \(H^{1}(\Omega)^{3}\) such that_

\[\mathbf{v}=\operatorname{\mathbf{curl}}\phi.\]

_Furthermore_,

\[\operatorname{div}\phi=0.\]

Proof.: The proof is quite similar to that of Theorem 3.1.

\(1^{\circ}\)) Let \(\phi\in H^{1}(\Omega)^{3}\) and \(\mathbf{v}=\operatorname{\mathbf{curl}}\phi\). Then \(\operatorname{div}\mathbf{v}=0\) and we must check that \(\left\langle\mathbf{v}\operatorname{\boldsymbol{\cdot}}\mathbf{n},1\right\rangle _{\Gamma_{i}}=0\). For \(0\leqslant i\leqslant p\), let \(\theta_{i}\) be a function of \(\mathcal{L}(\mathbb{R}^{3})\) satisfying:

\[0\leqslant\theta_{i}(x)\leqslant 1\quad\text{in }\mathbb{R}^{3}\quad\text{ and}\quad\theta_{i}(x)=\delta_{ij}\quad\text{in a neighborhood of }\Gamma_{j}.\]

We set \(\mathbf{w}_{i}=\operatorname{\mathbf{curl}}(\theta_{i}\phi)\). Obviously \(\mathbf{w}_{i}\in L^{2}(\Omega)^{3}\) and \(\operatorname{div}\mathbf{w}_{i}=0\). Moreover,

\[\mathbf{w}_{i}\operatorname{\boldsymbol{\cdot}}\mathbf{n}|_{\Gamma_{j}}=0 \quad\text{if }j\neq i,\quad\ \mathbf{w}_{i}\operatorname{\boldsymbol{\cdot}}\mathbf{n}|_{\Gamma_{i}}= \mathbf{v}\operatorname{\boldsymbol{\cdot}}\mathbf{n}|_{\Gamma_{i}}.\]

Hence

\[\left\langle\mathbf{v}\operatorname{\boldsymbol{\cdot}}\mathbf{n},1\right\rangle _{\Gamma_{i}}=\left\langle\mathbf{w}_{i}\operatorname{\boldsymbol{\cdot}} \mathbf{n},1\right\rangle_{\Gamma}=\int_{\Omega}\operatorname{div}\mathbf{w}_{ i}\,dx=0\quad\text{for }0\leqslant i\leqslant p.\]
