\(F\) are not defined on the same space, but it is not a fundamental tool in the fixed-point argument used below. The reader will find in Section 3.4 an example of a situation where \(F\) and \(F_{h}\) are not defined in the same space.

Now, we assume that \(D_{u}F_{h}(\lambda;\tilde{u}_{h})\) is an isomorphism from \(X\) onto \(\mathscr{X}\) and we introduce the following notations:

(3.17) \[\left[\begin{array}[]{c}\varepsilon_{h}(\lambda)=\|\,F_{h}(\lambda;\tilde{u}_{ h})\|_{\mathscr{X}},\\ \gamma_{h}(\lambda)=\|\,\{D_{u}F_{h}(\lambda;\tilde{u}_{h})\}^{-1}\|_{ \mathscr{L}(\mathscr{X};\mathscr{X})},\\ S(u;\alpha)=\{v\in X;\,\|v-u\|_{X}\leq\alpha\},\\ L_{h}(\lambda;\alpha)=\sup_{v\in S(\tilde{u}_{h};\alpha)}\|D_{u}F_{h}(\lambda ,\tilde{u}_{h})-D_{u}F_{h}(\lambda,v)\|_{\mathscr{L}(\mathscr{X};\mathscr{X})} .\end{array}\right.\]

Clearly, the function \(\alpha\to L_{h}(\lambda;\alpha)\): \(\mathbb{R}_{+}\to\mathbb{R}_{+}\) is monotonically increasing.

The next theorem solves Problem (3.12) and gives a fundamental error estimate. In addition, it shows that Problem (3.12) has no other solution in a suitable neighborhood of \(\tilde{u}_{h}\).

**Theorem 3.1**.: _Under the following assumptions_:__

(3.18) \[D_{u}F_{h}(\lambda;\tilde{u}_{h})\text{ is an isomorphism of }\,X\text{ onto }\mathscr{X},\] (3.19) \[2\gamma_{h}(\lambda)L_{h}(\lambda;2\gamma_{h}(\lambda)\varepsilon_{h }(\lambda))<1,\]

_then Problem (3.12) has a solution \((\lambda,u_{h})\) with_

(3.20) \[u_{h}\in S(\tilde{u}_{h};2\gamma_{h}(\lambda)\varepsilon_{h}(\lambda)),\]

\(D_{u}F_{h}(\lambda;u_{h})\) _is an isomorphism of \(X\) onto \(\mathscr{X}\) and_

(3.21) \[\|\,\{D_{u}F_{h}(\lambda,u_{h})\}^{-1}\,\|_{\mathscr{L}(\mathscr{X};\mathscr{ X})}\leq 2\gamma_{h}(\lambda).\]

_Furthermore_, _we have the following uniqueness result_: \(u_{h}\) is the only solution in every ball \(S(\tilde{u}_{h};\alpha)\) whose radius \(\alpha\) satisfies_:__

(3.22) \[\gamma_{h}(\lambda)L_{h}(\lambda;\alpha)<1\]

_and we have the estimate_:__

(3.23) \[\|u_{h}-v\|_{X}\leq[\gamma_{h}(\lambda)/(1-\gamma_{h}(\lambda)L_{h}(\lambda; \alpha))]\,\|\,F_{h}(\lambda,v)\,\|_{\mathscr{X}}\quad\quad\forall v\in S_{h} (u_{h};\alpha).\]

Proof.: Let us define the function

\[\varPhi_{h}(v)=v-[D_{u}F_{h}(\lambda,\tilde{u}_{h})]^{-1}\,F_{h}(\lambda,v) \quad\quad\forall v\in X.\]

Clearly, the pair \((\lambda,u_{h})\) is a solution of (3.12) if and only if \(u_{h}\) is a fixed point of \(\varPhi_{h}\). First, we are going to establish that \(\varPhi_{h}\) is a strict contraction of \(S=S(\tilde{u}_{h};\,2\gamma_{h}(\lambda)\varepsilon_{h}(\lambda))\) into itself.

\(1^{\circ})\) Let \(v\in S\); then
