\[v\Delta^{2}\psi=\operatorname{curl}\mathbf{f},\] \[\psi=\chi\quad\text{on }\Gamma_{0},\quad\psi=c_{i}+\chi\quad \text{on }\Gamma_{i},\quad 1\leqslant i\leqslant p,\] \[\partial\psi/\partial n=-\mathbf{g}\!\cdot\!\tau\quad\text{on }\Gamma,\] \[\int_{\Gamma_{i}}(v\partial(\Delta\psi)/\partial n-\mathbf{f}\! \cdot\!\tau)\,ds=0,\quad\ 1\leqslant i\leqslant p.\]

Note that this last condition makes sense if \(\mathbf{f}\!\in\!H(\operatorname{curl};\Omega)\).

### The Three-Dimensional Case

Now consider the case \(N=3\). To simplify the discussion, we first examine the case of a homogeneous boundary condition \(\mathbf{g}=\mathbf{0}\). We know from Section 3.3 that the velocity field \(\mathbf{u}\) can be expressed as:

\[\mathbf{u}=\operatorname{\mathbf{curl}}\psi\quad\text{with}\quad\operatorname {div}\psi=0\quad\text{in }\Omega.\]

When \(\Omega\) is simply-connected, the vector potential \(\psi\) is uniquely determined by either:

(5.38) \[\psi\!\cdot\!\mathbf{n}=0\quad\text{on }\Gamma\]

or

(5.39) \[\psi\times\mathbf{n}=\mathbf{0}\quad\text{on }\Gamma\quad\text{and}\quad\int_{ \Gamma_{i}}\psi\!\cdot\!\mathbf{n}\,ds=0\quad\ 0\leqslant i\leqslant p.\]

As \(\mathbf{u}\) vanishes on \(\Gamma\), we can add the boundary condition:

(5.40) \[\operatorname{\mathbf{curl}}\psi=\mathbf{0}\quad\text{on }\Gamma\]

but observe that this condition reduces to

(5.40') \[(\operatorname{\mathbf{curl}}\psi)\times\mathbf{n}=\mathbf{0}\quad\text{on }\Gamma\]

when \(\psi\) satisfies the first of (5.39) (cf. Remark 2.5). As far as the regularity of \(\psi\) is concerned, all we want is that \(\psi\) satisfy a biharmonic problem. Thus, it seems reasonable to ask that \(\Delta\psi\) belong to \(L^{2}(\Omega)^{3}\). In view of the identity

(5.41) \[-\Delta\mathbf{0}=\operatorname{\mathbf{curl}}\operatorname{\mathbf{curl}} \mathbf{0}-\operatorname{\mathbf{grad}}(\operatorname{div}\mathbf{0})\]

and the fact that \(\operatorname{\mathbf{curl}}\psi\!\in\!H^{1}(\Omega)^{3}\) we see that this amounts to ask that \(\operatorname{div}\psi\!\in\!H^{1}(\Omega)\). Of course, this is always the case when \(\psi\) is divergence-free, but in practice a divergence-free condition is unattractive and we are going to relax it entirely.

At this stage, it is important to point out that the vector potential \(\psi\) has no straightforward characterization on a multiply-connected domain \(\Omega\). For this reason, we shall only discuss briefly this last situation and restrict ourselves mainly to simply-connected regions.

Let us begin with vector potentials that satisfy (5.39). In the light of the above considerations, we introduce the space
