taking \(q_{h}=0\) in (4.59). Thus, by virtue of the inf-sup condition, we can apply (1.17):

\[\|p-\bar{p}_{h}\|_{0,\Omega}\leq(1+\sqrt{2}/\beta^{*})\inf_{q_{h}\in M_{h}}\|p-q_ {h}\|_{0,\Omega}+(v/\beta^{*})|\mathbf{u}-\mathbf{u}_{h}|_{1,\Omega}.\]

This yields (4.56); in turn a familiar argument gives (4.57).

Finally we establish an \(L^{2}\)-estimate for the velocity. The proof is an easy variant of that of Theorem 1.2. As \(\Omega\) is convex, there exists a unique pair \((\boldsymbol{\phi},\mu)\) in \([V\cap H^{2}(\Omega)^{2}]\times[H^{1}(\Omega)\cap L^{2}_{0}(\Omega)]\) such that

\[(\mathbf{g},\mathbf{u}-\mathbf{u}_{h})=v(\mathbf{grad}\,\boldsymbol{\phi}, \mathbf{grad}(\mathbf{u}-\mathbf{u}_{h}))+(\mathbf{grad}\,\mu,\mathbf{u}- \mathbf{u}_{h}),\] (4.61) \[\|\boldsymbol{\phi}\|_{2,\Omega}+|\mu|_{1,\Omega}\leq C\,\| \mathbf{g}\|_{0,\Omega}.\]

Combining this equality with (4.59) we readily derive:

\[(\mathbf{g},\mathbf{u}-\mathbf{u}_{h})=v(\mathbf{grad}(\boldsymbol {\phi}-\boldsymbol{\phi}_{h}),\mathbf{grad}(\mathbf{u}-\mathbf{u}_{h}))+(p-p_ {h},\operatorname{div}(\boldsymbol{\phi}_{h}-\boldsymbol{\phi}))\] \[\qquad\qquad-(\mu-q_{h},\operatorname{div}(\mathbf{u}-\mathbf{u} _{h}))+(\mathbf{grad}\,\lambda_{h},\mathbf{grad}(\mu-q_{h}))\] \[\qquad\qquad-(\mathbf{g},\mathbf{grad}\,\lambda_{h})\quad\quad \forall\boldsymbol{\phi}_{h}\in X_{h},\quad\forall q_{h}\in Q_{h}.\]

(Here we use the fact that \(\Delta\mu=\operatorname{div}\mathbf{g}\) in \(\Omega\)). Therefore choosing \(q_{h}=P_{h}\mu\) we obtain:

\[(\mathbf{g},\mathbf{u}-\mathbf{u}_{h}+\mathbf{grad}\,\lambda_{h} )=v(\mathbf{grad}(\boldsymbol{\phi}-\boldsymbol{\phi}_{h}),\mathbf{grad}( \mathbf{u}-\mathbf{u}_{h}))+(p-p_{h},\operatorname{div}(\boldsymbol{\phi}_{h} -\boldsymbol{\phi}))\\ -(\mu-P_{h}\mu,\operatorname{div}(\mathbf{u}-\mathbf{u}_{h})) \quad\quad\forall\boldsymbol{\phi}_{h}\in X_{h}.\]

In view of (4.56) and (4.61) this yields (4.58). 

_Remark 4.6_.: It does not appear possible to find an \(L^{2}\) bound like (4.58) for \(\mathbf{u}-\mathbf{u}_{h}\) alone. On the contrary, (4.60) implies that

\[\|\mathbf{u}-\mathbf{u}_{h}+\mathbf{grad}\,\lambda_{h}\|_{0,\Omega}^{2}=\| \mathbf{u}-\mathbf{u}_{h}\|_{0,\Omega}^{2}-|\lambda_{h}|_{1,\Omega}^{2}\]

so that neither \(\mathbf{u}-\mathbf{u}_{h}\) nor \(\lambda_{h}\) can be isolated from (4.58). But this is not surprising since \(\lambda_{h}\) acts as a correction on the velocity \(\mathbf{u}_{h}\).

The same analysis can be applied when \(X_{h}\) is defined by (4.30) (and \(M_{h}\) is unchanged). Because of (4.31), the statement of Theorem 4.6 holds _only with \(k=1\)_.

### Implementation of the Glowinski-Pironneau Scheme

It is not absolutely straightforward to compute the solution of (4.50) (4.51) (4.52) because the test function \(l_{h}\) does not appear explicitly in the left-hand side of (4.52). It is easier to split the computation by calculating the auxiliary function \(\lambda_{h}\), defined by (4.55), that compensates for the fact that \(\mathbf{u}_{h}\) does not satisfy the discrete divergence-free constraint.
