**Theorem 2.6**.: _Let \(\Omega\) and \(\mathcal{T}_{h}\) be like in Theorem 2.4 and let the solution \((\mathbf{u},p)\) of the Stokes Problem satisfy:_

\[\mathbf{u}\in[H^{k+1}(\Omega)\cap H^{1}_{0}(\Omega)]^{3},\quad\quad p\in H^{k}( \Omega)\cap L^{2}_{0}(\Omega)\]

_for some integer \(k\in[1,l]\). Then the solution \((\mathbf{u}_{h},p_{h})\) of (1.39) with the spaces \(X_{h}\) and \(M_{h}\) defined by (2.47) (2.48) satisfies the error bound:_

(2.51) \[|\mathbf{u}-\mathbf{u}_{h}|_{1,\,\Omega}+\|\,p-p_{h}\|_{0,\,\Omega}\leq C_{1}h ^{k}(|\mathbf{u}|_{k+1,\,\Omega}+|p|_{k,\,\Omega}).\]

_In addition, if the Stokes Problem (1.48) is regular, we have the \(L^{2}\)-estimate_

(2.52) \[\|\mathbf{u}-\mathbf{u}_{h}\|_{0,\,\Omega}\leq C_{2}h^{k+1}(|\mathbf{u}|_{k+1 ,\,\Omega}+|p|_{k,\,\Omega}).\]

_Remark 2.8_.: It is easy to show that the statement of Remark 2.6 concerning the convergence under weak regularity assumptions on \((\mathbf{u},p)\) is still valid in the three-dimensional case.

## 3 Quadrilateral Finite Element Methods Using Discontinuous Pressures

There are two reasons for treating separately quadrilateral finite elements. On the one hand, isoparametric finite element methods are less transparent than simplicial ones and must be handled with some more care. On the other hand, quadrilateral elements (more precisely, rectangular elements) provide excellent examples of schemes which do not satisfy the inf-sup condition and yet can be proved to converge with optimal accuracy. Some of these schemes, being particularly simple, are preferred by a number of users.

For the sake of conciseness, we have only treated the two-dimensional case. The three-dimensional case is a straightforward adaptation of this material and that of Section 2.3.

### A Quadrilateral Finite Element of Order One

The element discussed in this section is the analogue of the first-order element defined in Section 2.1. It has been introduced by Fortin [30].

Let \(\Omega\) be a _bounded_, _plane polygon_ and let \(\mathcal{T}_{h}\) be a "triangulation" of \(\bar{\Omega}\) made of **convex quadrilaterals** with diameters bounded by \(h\). Consider one of these quadrilaterals \(\kappa\) with vertices \(a_{1}\), \(a_{2}\), \(a_{3}\), \(a_{4}\) (also numbered \(a_{0}\)); we denote by \(f_{i}\) the segment \([a_{i-1},a_{i}]\) (cf. Figure 10) and by \(\mathbf{n}_{i}\) its unit outward normal. To draw the parallel with Section 2.1 we replace the barycentric coordinates by the reference variables

\[\hat{x}_{1},\hat{x}_{2},\hat{x}_{3}=1-\hat{x}_{1}\quad\text{and}\quad\hat{x}_ {4}=1-\hat{x}_{2}.\]
