## Chapter 2 Numerical Solution of the Stokes Problem in the Primitive Variables

### 2 General Approximation

The abstract problem discussed in Chapter 1, SS 4 lends itself readily to a straightforward approximation that converges under reasonable assumptions with an error proportional to the approximation error of the spaces involved. When applied to the Stokes problem, this approach yields a conforming approximation of the velocity and pressure, although the approximate velocity field is (in general) not exactly divergence-free. The wide range of finite element methods developped in the remainder of the chapter are all founded on the material of this paragraph. Non-conforming methods can also be put into this framework (cf. Zine [85]) but for the sake of conciseness we have skipped them entirely.

### 2 An Abstract Approximation Result

This section is devoted to the approximation of the abstract variational problem analyzed in SS 4 of Chapter 1. We keep here the same notation and we put the problem in exactly the same situation. Recall that our _Problem_ (Q) reads:

_Given \(l\) in \(X^{{}^{\prime}}\) and \(\chi\) in \(M^{{}^{\prime}}\), find a pair \((u,\lambda)\) in \(X\times M\) such that_

(1) \[a(u,v)+b(v,\lambda)=\langle l,v\rangle\quad\quad\forall v\in X,\] (2) \[b(u,\mu)=\langle\chi,\mu\rangle\quad\quad\forall\mu\in M.\]

Here, \(X\) and \(M\) are two real Hilbert spaces and \(a(.,.)\) and \(b(.,.)\) are two continuous bilinear forms defined respectively on \(X\times X\) and \(X\times M\). With the form \(b(.,.)\) we associate the linear operators \(B\) and \(B^{{}^{\prime}}\) defined by:

\[\langle Bv,\mu\rangle=\langle v,B^{{}^{\prime}}\mu\rangle=b(v,\mu)\quad\quad \forall v\in X,\quad\quad\forall\mu\in M\]

and we set

\[V(\chi)=\{v\in X;\,Bv=\chi\},\]

\[V=V(0)=\operatorname{Ker}(B).\]
