\(2^{\circ}\)) Conversely, let \(\mathbf{v}\in L^{2}(\Omega)^{3}\) satisfy (3.1). As in the two-dimensional case, we extend \(\mathbf{v}\) to the whole space so that the extended function \(\tilde{\mathbf{v}}\) belongs to \(L^{2}(\mathbb{R}^{3})^{3}\), is divergence-free and has a compact support. Again, the Fourier transform of \(\tilde{\mathbf{v}},\mathscr{F}\tilde{\mathbf{v}}\), is holomorphic in \(\mathbb{R}^{3}\) since the support of \(\tilde{\mathbf{v}}\) is compact. In terms of Fourier transforms, the conditions \(\operatorname{div}\tilde{\mathbf{v}}=0\) and \(\tilde{\mathbf{v}}=\operatorname{\mathbf{curl}}\phi\) become respectively:

(3.20) \[\sum_{i=1}^{3}\mu_{i}\mathscr{F}\tilde{v}_{i}=0,\]

and

(3.21) \[\mathscr{F}\tilde{\mathbf{v}}=2i\pi(\mu_{2}\mathscr{F}\phi_{3}-\mu_{3} \mathscr{F}\phi_{2},\mu_{3}\mathscr{F}\phi_{1}-\mu_{1}\mathscr{F}\phi_{3},\mu _{1}\mathscr{F}\phi_{2}-\mu_{2}\mathscr{F}\phi_{1}).\]

Observe that if (3.20) holds then (3.21) and the following condition:

(3.22) \[\sum_{i=1}^{3}\mu_{i}\mathscr{F}\phi_{i}=0\]

determine \(\mathscr{F}\phi\) uniquely. The unique solution of (3.20), (3.21) and (3.22) is:

\[\mathscr{F}\phi=\frac{1}{2i\pi\|\mu\|^{2}}(\mu_{3}\mathscr{F}\tilde{v}_{2}-\mu _{2}\mathscr{F}\tilde{v}_{3},\mu_{1}\mathscr{F}\tilde{v}_{3}-\mu_{3}\mathscr{F }\tilde{v}_{1},\mu_{2}\mathscr{F}\tilde{v}_{1}-\mu_{1}\mathscr{F}\tilde{v}_{2}).\]

Clearly, these equations imply that \(\mu_{j}\mathscr{F}\phi_{i}\in L^{2}(\mathbb{R}^{3})\) and that

\[|\mathscr{F}\phi_{i}|\leq(|\mathscr{F}\tilde{v}_{j}|+|\mathscr{F}\tilde{v}_{k }|)/(2\pi\|\mu\|).\]

Therefore, the inverse transform of \(\mathscr{F}\phi\) belongs to \(H^{1}(\Omega)^{3}\), provided that \(\mathscr{F}\phi\) is bounded at the origin. First, we observe that (3.20) implies that \(\mathscr{F}\tilde{\mathbf{v}}(0)=\mathbf{0}\). Hence, since \(\mathscr{F}\tilde{\mathbf{v}}\) is holomorphic, it follows that, in a neighborhood of zero:

\[\mathscr{F}\tilde{\mathbf{v}}(\mu)=\sum_{j=1}^{3}\mu_{j}(\partial\mathscr{F} \tilde{\mathbf{v}}(0)/\partial\mu_{j})+O(\|\mu\|^{2}).\]

Therefore \(\mathscr{F}\phi\) is bounded as \(\mu\) tends to zero.

By restricting to \(\Omega\) the inverse transform \(\phi\) of \(\mathscr{F}\phi\), we thus find a function \(\phi\) in \(H^{1}(\Omega)^{3}\) such that \(\mathbf{v}=\operatorname{\mathbf{curl}}\phi\) and moreover, \(\operatorname{div}\phi=0\). 

_Remark 3.7_.: The above construction shows that one can always choose a divergence-free potential vector. Of course, this is not the only possibility. For instance, we might have replaced (3.22) by:

(3.22') \[\mathscr{F}\phi_{3}=0.\]

Then (3.20), (3.21) and (3.22') have the only solution

\[\mathscr{F}\phi_{1}=\mathscr{F}\tilde{v}_{2}/(2i\pi\mu_{3}),\quad\mathscr{F} \phi_{2}=-\mathscr{F}\tilde{v}_{1}/(2i\pi\mu_{3}),\quad\mathscr{F}\phi_{3}=0.\]

The corresponding potential vector \(\phi\) of \(\mathbf{v}\) has the form \((\phi_{1},\phi_{2},0)\).

_Remark 3.8_.: Every divergence-free potential vector \(\phi\) of \(\mathbf{v}\) satisfies:

\[-\Delta\phi=\operatorname{\mathbf{curl}}\mathbf{v}\quad\text{in }H^{-1}(\Omega)^{3}.\]
