**Corollary 3.6**.: _Let \(\Omega\) be a bounded and convex open subset of \(\mathbb{R}^{3}\) with a \(\mathcal{C}^{2}\) boundary \(\Gamma\). The functions \(\phi\) of \(U\cap H^{1}(\Omega)^{3}\) satisfy the inequality:_

(3.41) \[|\phi|_{1,\,\Omega}^{2}\leqslant\|\operatorname{\mathbf{curl}}\phi\|_{0,\, \Omega}^{2}+\|\operatorname{div}\phi\|_{0,\,\Omega}^{2}.\]

**Theorem 3.9**.: _Let \(\Omega\) be a bounded and convex polyhedron. The space \(U\) is continuously imbedded in \(H^{1}(\Omega)^{3}\) and the functions of \(U\) satisfy (3.41)._

Proof.: It is possible to construct (cf. Grisvard [42]) an increasing sequence \((\Omega_{l})_{l\geqslant 1}\) of open convex sets, each with a \(\mathcal{C}^{2}\) boundary \(\Gamma_{l}\) and such that

\[\bar{\Omega_{l}}\subset\Omega\quad\quad\forall l\geqslant 1,\quad\quad\Omega= \bigcup_{l\geqslant 1}\Omega_{l}.\]

By virtue of Lemma 3.5, we can restrict our attention to \(U_{0}\). Thus, let \(\phi\in U_{0}\), let \(\chi_{l}\in H^{1}(\Omega_{l})/\mathbb{R}\) denote the solution of

(3.42) \[\Delta\chi_{l}=0\quad\text{in }\Omega_{l},\quad\quad\partial\chi_{l}/ \partial n=\phi\cdot\mathbf{n}\quad\text{on }\Gamma_{l},\]

and define \(\phi_{l}\) on \(\Omega_{l}\) by

\[\phi_{l}=\phi-\operatorname{\mathbf{grad}}\chi_{l}.\]

Note that the non-homogeneous Neumann's problem (3.42) has a unique solution \(\chi_{l}\), since \(\operatorname{div}\phi=0\) in \(\Omega\). Furthermore, owing to Corollary 2.10, \(\phi\in H^{1}(\Omega_{l})^{3}\forall l\); and since \(\Gamma_{l}\) is smooth this, in turn, implies that \(\phi\cdot\mathbf{n}\in H^{1/2}(\Gamma_{l})\). Hence \(\chi_{l}\in H^{2}(\Omega_{l})/\mathbb{R}\) and therefore \(\phi_{l}\in H^{1}(\Omega_{l})^{3}\) with \(\phi_{l}\cdot\mathbf{n}=0\) on \(\Gamma_{l}\). Thus we can apply Corollary 3.6 to \(\phi_{l}\):

(3.43) \[|\phi_{l}|_{1,\,\Omega_{l}}\leqslant\|\operatorname{\mathbf{curl}}\phi_{l}\| _{0,\,\Omega_{l}}\leqslant\|\operatorname{\mathbf{curl}}\phi\|_{0,\,\Omega} \quad\quad\forall l.\]

In addition, (3.42) is equivalent to

\[\int_{\Omega_{l}}\phi_{l}\cdot\operatorname{\mathbf{grad}}\mu\,dx=0\quad\quad \forall\mu\in H^{1}(\Omega_{l}).\]

Hence, we easily derive that

(3.44) \[\|\phi_{l}\|_{0,\,\Omega_{l}}\leqslant\|\phi\|_{0,\,\Omega},\] (3.45) \[\|\operatorname{\mathbf{grad}}\chi_{l}\|_{0,\,\Omega_{l}}\leqslant \|\phi\|_{0,\,\Omega},\] (3.46) \[\left|\int_{\Omega_{l}}\operatorname{\mathbf{grad}}\chi_{l}\cdot \operatorname{\mathbf{grad}}\mu\,dx\right|\leqslant\|\phi\|_{0,\,\Omega- \Omega_{l}}\|\operatorname{\mathbf{grad}}\mu\|_{0,\,\Omega-\Omega_{l}}\quad \quad\forall\mu\in H^{1}(\Omega).\]

Let us extend \(\operatorname{\mathbf{grad}}\chi_{l}\), \(\phi_{l}\) and \(\partial\phi_{l}/\partial x_{i}\) by zero outside \(\Omega_{l}\) and, as usual, let us denote the extended functions by a tilde. Then (3.45) implies that

\[\widehat{\operatorname{\mathbf{grad}}\chi_{l}}\to\mathbf{w}\quad\text{weakly in }L^{2}(\Omega)^{3}\quad\text{with }\operatorname{\mathbf{curl}}\mathbf{w}=\mathbf{0}.\]

Indeed, if \(\lambda\in\mathcal{D}(\Omega)^{3}\), there exists an integer \(k\) such that \(\lambda\in\mathcal{D}(\Omega_{l})^{3}\forall l\geqslant k\). Then
