it stands out clearly from the expression of \(\tilde{a}(.;.,.)\) that it requires a finer norm than the \(W^{1.s}\)-norm of the space \(\Phi\). To be specific, it is desirable to work with the seminorm

\[\left(\sum_{\kappa\in\mathcal{T}_{h}}|\phi|_{2,\kappa}^{2}\right)^{1/2}.\]

This is precisely the purpose of the space \(V_{h}\): it was shown in Chapter III that, under adequate conditions, the functions of \(V_{h}\) satisfy the uniform stability properties:

(5.20) \[|\phi_{h}|_{1,\,t,\Omega}\leq C_{t}\|\,\theta_{h}\|_{0,\,\Omega} \quad\text{ (cf.\,(III.2.41))}\quad\quad\forall v_{h}=(\mathbf{curl}\,\phi_{h},\theta_{h}) \!\in V_{h},\] (5.21) \[\left(\sum_{\kappa\in\mathcal{T}_{h}}|\phi_{h}|_{2,\kappa}^{2} \right)^{1/2}\leq C\|\,\theta_{h}\|_{0,\,\Omega}\quad\text{ (cf.\,(III.2.65))}\]

with constants independent of \(h\). In other words:

_the seminorm of \(X\colon|v_{h}|\equiv\|\,\theta_{h}\|_{0,\,\Omega}\) is a norm on \(V_{h}\) uniformly equivalent to both_

\[|\phi_{h}|_{1,\,t,\,\Omega}+\|\,\theta_{h}\|_{0,\,\Omega}\quad\text{and}\quad \left(\sum_{\kappa\in\mathcal{T}_{h}}|\phi_{h}|_{2,\kappa}^{2}\right)^{1/2}+\| \,\theta_{h}\|_{0,\,\Omega}\quad\text{for each $t\geqslant 2$}.\]

This suggests to adopt the following mesh-dependent norms:

(5.22) \[[\![\phi]\!]_{t}=\left(\sum_{\kappa\in\mathcal{T}_{h}}|\phi|_{2,\kappa}^{2} \right)^{1/2}+\,h^{-2/t}|\phi|_{1,\,t,\,\Omega}\quad\forall t\geqslant 2.\]

Next, since the functions of \(X\) have little regularity, it will sometimes be useful to work with the following smoothing operator:

\[P\!\in\!\mathcal{L}(X;\,\{\mathbf{curl}\,\phi;\,\phi\!\in\!H^{2}(\Omega)\cap H _{0}^{1}(\Omega)\}\,\times\,L^{2}(\Omega))\]

defined by

\[\text{for $u=(\mathbf{curl}\,\psi,\omega)\!\in\!X,Pu=(\mathbf{curl}\,\phi,\omega)$ is the solution of the Dirichlet problem}\] (5.23) \[-\,\mathcal{A}\phi=\omega\quad\text{in $\Omega$},\quad\ \phi=0\quad\text{on $\Gamma$}.\]

When \(\Omega\) is _convex_, this function \(\phi\) belongs indeed to \(H^{2}(\Omega)\) and

(5.24) \[\|\,\phi\!\|_{2,\,\Omega}\leq C\|\,\omega\|_{0,\,\Omega}.\]

Clearly, the operator \(P\) reduces to the identity mapping on \(V\). Moreover, when \(u_{h}=(\mathbf{curl}\,\psi_{h},\omega_{h})\) belongs to \(V_{h}\) the corresponding function \(\phi\) coincides with the function \(\phi(h)\) introduced in the proof of Lemma III.2.5. In other words, \(u_{h}=(\mathbf{curl}\,\psi_{h},\omega_{h})\!\in V_{h}\) and \(Pu_{h}=(\mathbf{curl}\,\phi,\omega_{h})\) are related by

\[\psi_{h}=\hat{P_{h}}\phi,\]

the \(H^{1}\)-projection on \(\mathcal{P}_{h}\) defined by (A.24):

(5.25) \[(\mathbf{curl}(\hat{P_{h}}\phi-\phi),\mathbf{curl}\,\mu_{h})=0\quad\quad \forall\mu_{h}\!\in\!\mathcal{P}_{h}.\]

The next lemma gives a useful estimate for \([\phi-\hat{P_{h}}\phi]_{t}\).
