\[\tau_{ij}=0\quad\text{if }i\neq j,\quad\tau_{ii}=\theta_{h}\quad\quad i=1, 2.\]

All such tensors satisfy

\[b_{h}(\tau_{h},\phi_{h})=(\operatorname{\mathbf{curl}}\theta_{h},\operatorname{ \mathbf{curl}}\phi_{h})\quad\quad\forall\phi_{h}\in\varPhi_{h}\]

and

\[\|\tau_{h}\|_{0,\,h}^{2}=2\,\|\,\theta_{h}\|_{0,\,\Omega}^{2}+h\,\|\,\theta_{h }\|_{0,\,\Gamma_{h}}^{2}.\]

Hence applying Lemma 2.12 we obtain the preliminary result:

\[\sup_{\tau_{h}\in\,\mathcal{Z}\cap\theta_{h}^{*}}\frac{b_{h}(\tau_{h},\phi_{h} )}{\|\tau_{h}\|_{0,\,h}}\geqslant(1/\sqrt{2})\beta^{*}\,\|\,\phi_{h}\|_{2,\,h }\quad\quad\forall\phi_{h}\in\varPhi_{h},\]

where \(\beta^{*}\) is the constant of Lemma 2.12, provided \(\Omega\) is convex and the triangulation is uniformly regular. By virtue of (4.31) and (4.32) this condition implies the inf-sup condition on the space \(\varSigma_{h}\).

**Lemma 4.4**.: _Let \(\Omega\) be a bounded, convex polygon and let \(\mathcal{T}_{h}\) be a uniformly regular triangulation of \(\widehat{\Omega}\). Then we have:_

\[\sup_{\tau_{h}\in\,\varSigma_{h}}\frac{b_{h}(\tau_{h},\phi_{h})}{\|\tau_{h}\| _{0,\,h}}\geqslant[1/(\sqrt{2}C_{1})]\beta^{*}\,\|\,\phi_{h}\|_{2,\,h}\quad \quad\forall\phi_{h}\in\varPhi_{h},\]

_where \(\beta^{*}\) and \(C_{1}\) are the constants of (2.63) and (4.32) respectively._

_Remark 4.2_.: Owing to Remark 2.8, we also have

\[\sup_{\tau_{h}\in\,\varSigma\cap\varPhi_{h}^{*}}\frac{b_{h}(\tau_{h},\phi_{h} )}{\|\tau_{h}\|_{0,\,h}}\geqslant(\gamma(s)/\sqrt{2})\,|\phi_{h}|_{1,\,s, \Omega}\quad\quad\forall\text{real }s\geqslant 2,\quad\quad\forall\phi_{h}\in \varPhi_{h}.\]

Thus, the assumptions of Lemma 4.4 imply the additional inf-sup condition:

\[\sup_{\tau_{h}\in\,\varSigma_{h}}\frac{b_{h}(\tau_{h},\phi_{h})}{\|\tau_{h}\| _{0,\,h}}\geqslant[1/(\sqrt{2}C_{1})]\gamma(s)\,|\phi_{h}|_{1,\,s,\Omega} \quad\quad\forall\text{real }s\geqslant 2,\quad\quad\forall\phi_{h}\in \varPhi_{h}.\]

_Remark 4.3_.: The construction of Lemma 4.4 can also be applied to prove that Problem (4.20) has a unique solution _without restriction on \(\Omega\) and \(\mathcal{T}_{h}\)_. Indeed, since we are working with finite-dimensional spaces, all we need to show is that the set \(\{\phi_{h}\in\varPhi_{h};b_{h}(\tau_{h},\phi_{h})=0\ \forall\tau_{h}\in\varSigma_{h}\}\) is reduced to the zero function. Now, by proceeding like above, we construct \(\tau\in\varSigma\cap\varPhi_{h}^{*}\) such that \(b_{h}(\tau,\phi_{h})=|\phi_{h}|_{1,\,\Omega}^{2}=b_{h}(\tau_{h}\tau,\phi_{h})=0\). Hence \(\phi_{h}=0\).

Finally when \(\mathcal{T}_{h}\) is uniformly regular we can show like in Lemma 2.7 that \(\|\,.\,\|_{0,\,h}\) and \(\|\,.\,\|_{0,\,\Omega}\) are _two uniformly equivalent norms on \(\varSigma_{h}\)_. The proof, which is left as an exercise, stems from the inequality:

\[\|M_{n}(\tau)\|_{0,\,\Gamma_{h}}^{2}\leqslant(C/h)\,\|\,\tau\|_{0,\,h}^{2} \quad\quad\forall\tau\in\varSigma_{h}.\]

We are now in a position to establish optimal error estimates for Problem (4.20).
