_Remark 4.4_.: Although it is less accurate than the preceding scheme while involving the same number of unknowns, this last method is often preferred because it leads to better conditioned linear systems.

### The "Glowinski-Pironneau" Finite Element Method

To begin with, let the dimension \(N\) be two or three. The numerical scheme discussed in this section, introduced by Glowinski & Pironneau [38], is based on a Poisson equation for the pressure. By taking the divergence of both sides of the equation:

\[-v\,\boldsymbol{u}+\boldsymbol{\mathrm{grad}}\,p=\boldsymbol{f}\]

and taking into account the condition \(\operatorname{div}\boldsymbol{u}=0\), we obtain:

\[\mathcal{A}p=\operatorname{div}\boldsymbol{f}\quad\text{in }\Omega.\]

Hence, if we know the trace \(\rho=p|_{\Gamma}\) of \(p\) on \(\Gamma\), the Stokes equations reduce to \(N+1\) Dirichlet problems for the Laplace operator:

(4.34) \[\mathcal{A}p=\operatorname{div}\boldsymbol{f}\quad\text{in } \Omega,\quad\ p=\rho\quad\text{on }\Gamma,\] (4.35) \[v\,\mathcal{A}\boldsymbol{u}=\boldsymbol{\mathrm{grad}}\,p- \boldsymbol{f}\quad\text{in }\Omega,\quad\boldsymbol{u}=\boldsymbol{0}\quad\text{on }\Gamma.\]

In fact, \(\rho\) is the major unknown of the problem. We shall show that \(\rho\) can be in turn determined by the constraint \(\operatorname{div}\boldsymbol{u}=0\).

More precisely, observe that \(\boldsymbol{u}\) and \(p\) can be split into two components:

(4.36) \[\boldsymbol{u}=\boldsymbol{u}^{0}+\boldsymbol{u}(\rho),\quad\ p=p^{0}+p(\rho),\]

where \(p^{0}\) and \(\boldsymbol{u}^{0}\) are the solutions of the Dirichlet problems:

(4.37a) \[\mathcal{A}p^{0}=\operatorname{div}\boldsymbol{f}\quad\text{in } \Omega,\quad\ p^{0}=0\quad\text{on }\Gamma,\] (4.37b) \[v\,\mathcal{A}\boldsymbol{u}^{0}=\boldsymbol{\mathrm{grad}}\,p^{0}- \boldsymbol{f}\quad\text{in }\Omega,\quad\boldsymbol{u}^{0}=\boldsymbol{0}\quad\text{on }\Gamma,\]

and, for each boundary value \(g\), \(p(g)\) and \(\boldsymbol{u}(g)\) are the solutions of:

(4.38a) \[\mathcal{A}p(g)=0\quad\text{in }\Omega,\quad\ p(g)=g\quad\text{on }\Gamma,\] (4.38b) \[v\,\mathcal{A}\boldsymbol{u}(g)=\boldsymbol{\mathrm{grad}}\,p(g) \quad\text{in }\Omega,\quad\boldsymbol{u}(g)=\boldsymbol{0}\quad\text{on }\Gamma.\]

The space \(G\) of the boundary functions \(g\) is chosen so that the mapping \(g\to p(g)\) defined by (4.38a) is an isomorphism from \(G\) onto the space

\[\{q\,\text{in}\,\text{$L^{2}(\Omega)$; $\mathcal{A}q=0$}\}.\]

Then, since the solution \(\boldsymbol{u}\) of (4.34) (4.35) must satisfy

\[\mathcal{A}(\operatorname{div}\boldsymbol{u})=0\quad\text{in }\Omega,\]

the constraint \(\operatorname{div}\boldsymbol{u}=0\) can be expressed by:
