then \(\mathbf{u}\in H^{1}(\Omega)^{N}\). However, their techniques do not apply when \(\Gamma\) has corners. It turns out that this property remains valid in this case, provided \(\Omega\) has no reentrant corners (at least in two dimensions) and in two dimensions, the results of Section 3.1 supply a very simple proof.

Recall that \(\Omega\) is a _connected_, _bounded_, open subset of \(\mathbb{R}^{2}\). We set

\[U=H_{0}(\operatorname{div};\Omega)\cap H(\operatorname{curl};\Omega),\quad\ W =H(\operatorname{div};\Omega)\cap H_{0}(\operatorname{curl};\Omega).\]

**Proposition 3.1**.: _If \(\Gamma\) is of class \(\mathcal{C}^{1.1}\) or if \(\Gamma\) is piecewise smooth with no reentrant corners, then \(U\) and \(W\) are both algebraically and topologically included in \(H^{1}(\Omega)^{2}\)._

Proof.: \(1^{\circ}\)) Let \(\mathbf{v}\in U\); according to Theorem 3.2 and Remarks 3.1, 3.2, \(\mathbf{v}\) can be split as follows:

(3.8) \[\mathbf{v}=\operatorname{\mathbf{grad}}q+\operatorname{\mathbf{curl}}\phi,\]

where \(q\) is the solution (unique up to an additive constant) of the homogeneous Neumann's problem:

(3.16) \[\left\{\begin{aligned} \Delta q&=\operatorname{div} \mathbf{v}\quad\text{in }\Omega,\\ \partial q/\partial n&=0\quad\text{on }\Gamma\end{aligned}\right.\]

and \(\phi\) is the solution of the non-homogeneous Dirichlet problem:

\[-\Delta\phi=\operatorname{curl}\mathbf{v}\quad\text{in }\Omega,\]

\[\phi|_{\Gamma_{0}}=0,\quad\phi|_{\Gamma_{i}}=\text{a constant }c_{i},\]

where the constants \(c_{i}\) are determined by (3.10). As \(\operatorname{div}\mathbf{v}\) and \(\operatorname{curl}\mathbf{v}\) are both in \(L^{2}(\Omega)\), and because of the hypotheses on \(\Gamma\), it follows from Theorems 1.8 and 1.10 that both \(q\) and \(\phi\) belong to \(H^{2}(\Omega)\) and furthermore:

(3.17) \[\left\{\begin{aligned} \|q\|_{2,\Omega}&\leqslant C_{1}\| \operatorname{div}\mathbf{v}\|_{0,\Omega},\\ \|\phi\|_{2,\Omega}&\leqslant C_{2}(\| \operatorname{curl}\mathbf{v}\|_{0,\Omega}+\|\gamma_{0}\phi\|_{3/2,\Gamma}). \end{aligned}\right.\]

Now observe that since \(\phi\) is constant on each \(\Gamma_{i}\) and vanishes on \(\Gamma_{0}\), we have:

\[\|\gamma_{0}\phi\|_{3/2,\Gamma}\leqslant C_{3}\|\phi\|_{1,\Omega}\leqslant C_ {4}|\phi|_{1,\Omega}.\]

In addition, by virtue of (3.10) and (3.9), we get

\[|\phi|_{1,\Omega}\leqslant\|\mathbf{v}-\operatorname{\mathbf{grad}}q\|_{0, \Omega}\leqslant\|\mathbf{v}\|_{0,\Omega}.\]

Hence, collecting these inequalities and substituting into (3.8), we infer that \(\mathbf{v}\in H^{1}(\Omega)^{2}\) and

(3.18) \[\|\mathbf{v}\|_{1,\Omega}\leqslant C_{5}(\|\mathbf{v}\|_{0,\Omega}+\| \operatorname{div}\mathbf{v}\|_{0,\Omega}+\|\operatorname{curl}\mathbf{v}\|_{ 0,\Omega}).\]

\(2^{\circ}\)) As far as the space \(W\) is concerned, we can use the simple trick of Remark 2.4: for \(\mathbf{u}\) in \(W\), the vector \(\mathbf{v}=(-u_{2},u_{1})\) belongs to \(U\), with \(\operatorname{div}\mathbf{v}=-\operatorname{curl}\mathbf{u}\), \(\operatorname{curl}\mathbf{v}=\operatorname{div}\mathbf{u}\) and \(\mathbf{v}\cdot\mathbf{n}=-\mathbf{u}\cdot\mathbf{\tau}\). Therefore, we infer from \(1^{\circ}\)) that \(\mathbf{v}\) belongs to \(H^{1}(\Omega)^{2}\) and satisfies the bound (3.18); and thus the same holds for \(\mathbf{u}\).
