### Approximation of Branches of Nonsingular Solutions

Let us go back to the general abstract problem (3.1) in order to introduce the method of approximation. For each value of a real parameter \(h>0\) which will tend to zero, we are given a \(\mathcal{C}^{p}\)-mapping \(F_{h}\), presumably an approximation of \(F\), defined on \(\Lambda\times X\) with values in \(\mathcal{X}\). The problem now is to find pairs \((\lambda,u_{h})\in\Lambda\times X\), solutions of

\[F_{h}(\lambda,u_{h})=0.\] (3.12)

Let us assume that \(\{(\lambda,u(\lambda));\lambda\in\Lambda\}\) is a branch of _nonsingular solutions of (3.1)_. We want to find sufficient conditions ensuring the existence and uniqueness of a branch \(\{(\lambda,u_{h}(\lambda));\lambda\in\Lambda\}\) of solutions of (3.12) in a suitable neighborhood of the branch of solutions of (3.1).

In a first stage, we fix \(\lambda\) in \(\Lambda\) and we propose to approximate the solution of (3.1) by the solution \(u_{h}(\lambda)\) of (3.12). Let \(\tilde{u}_{h}\) (\(=\tilde{u}_{h}(\lambda)\)) be an arbitrary element of \(X\) and let us investigate under what conditions the mapping \(D_{u}F_{h}(\lambda,\tilde{u}_{h})\) is invertible. To this end, we introduce the two quantities:

\[\gamma(\lambda) =\|\,\{D_{u}F(\lambda,u(\lambda))\}^{-1}\|_{\mathcal{L}( \mathcal{X};X)},\] (3.13) \[\mu_{h}(\lambda) =\|\,D_{u}F(\lambda,u(\lambda))-D_{u}F_{h}(\lambda,\tilde{u}_{h} )\|_{\mathcal{C}(X;\mathcal{X})}.\] (3.14)

**Lemma 3.3**.: _Under the condition_

\[\gamma(\lambda)\mu_{h}(\lambda)<1,\] (3.15)

_the mapping \(D_{u}F_{h}(\lambda,\tilde{u}_{h})\) is an isomorphism from \(X\) onto \(\mathcal{X}\)._

Proof.: We set

\[B=\{D_{u}F(\lambda,u(\lambda))\}^{-1}\{D_{u}F(\lambda,u(\lambda))-D_{u}F_{h}( \lambda,\tilde{u}_{h})\}.\]

Then

\[D_{u}F_{h}(\lambda,\tilde{u}_{h})=D_{u}F(\lambda,u(\lambda))\{I-B\}.\]

But in view of (3.15), we have

\[\|\,B\,\|_{\mathcal{L}(X;X)}\leqslant\gamma(\lambda)\mu_{h}(\lambda)<1;\]

therefore \(I-B\) is an isomorphism of \(X\) and

\[\|(I-B)^{-1}\,\|_{\mathcal{L}(X;X)}\leqslant 1/(1-\gamma(\lambda)\mu_{h}( \lambda)).\]

As a consequence \(D_{u}F_{h}(\lambda,\tilde{u}_{h})\) is also an isomorphism from \(X\) onto \(\mathcal{X}\) and

\[\|\,\{D_{u}F_{h}(\lambda,\tilde{u}_{h})\}^{-1}\,\|_{\mathcal{L}(\mathcal{X};X )}\leqslant\gamma(\lambda)/(1-\gamma(\lambda)\mu_{h}(\lambda)).\qed\] (3.16)

_Remark 3.1_.: The above lemma relies on the fact that both \(F\) and \(F_{h}\) map \(\Lambda\times X\) into \(\mathcal{X}\). This hypothesis makes the forthcoming theory simpler than when \(F_{h}\) and
