\(\mathcal{L}(W^{1,s}(\hat{\kappa})^{3};R_{l})\), Corollary A.1 yields:

\[\|\hat{\mathbf{u}}-r_{\hat{\kappa}}\hat{\mathbf{u}}\|_{0,\,\hat{\kappa}}\leq C_{ \gamma}|\hat{\mathbf{u}}|_{1,\,s,\,\hat{\kappa}}.\]

Hence

\[\|\mathbf{u}-r_{h}\mathbf{u}\|_{0,\,\kappa}\leq C_{8}(\mathrm{meas}(\kappa))^{1 /2-1/s}\|\,B_{\kappa}^{-1}\|\,\|B_{\kappa}\|^{2}|\mathbf{u}|_{1,\,s,\,\kappa}.\]

Then Holder's inequality and the regularity of \(\mathcal{T}_{h}\) imply that

\[\|\mathbf{u}-r_{h}\mathbf{u}\|_{0,\,\Omega}\leq C_{9}h(\mathrm{meas}(\Omega) )^{1/2-1/s}|\mathbf{u}|_{1,\,s,\,\Omega}.\]

Likewise, we have

\[\|\mathbf{curl}(\hat{\mathbf{u}}-r_{\hat{\kappa}}\hat{\mathbf{u}})\|_{0,\, \hat{\kappa}}\leq C_{10}|\hat{\mathbf{u}}|_{1,\,s,\,\hat{\kappa}}.\]

Therefore, we infer from the above inequalities that:

\[\|\,\mathbf{curl}(\mathbf{u}-r_{h}\mathbf{u})\|_{0,\,\Omega}\leq C_{11}( \mathrm{meas}(\Omega))^{1/2-1/s}|\mathbf{u}|_{1,\,s,\,\Omega}.\qed\]

### Error Analysis for Finite Elements of Degree \(l\)

The spaces \(M_{h}\) and \(\Phi_{h}\) have already been defined in (5.36) and it remains to define the space \(\Theta_{h}\). Here, we simply take the standard finite element space:

(5.43) \[\Theta_{h}=\{q_{h}\!\in\!\mathcal{C}^{0}(\bar{\Omega});\,q_{h}|_{\,\kappa}\! \in\!P_{l}\quad\forall\kappa\!\in\!\mathcal{T}_{h},\,q_{h}|_{\,\Gamma}=0\}.\]

Recall that the functions of \(\Phi_{h0}\) satisfy

(5.12) \[(\phi_{h},\mathbf{grad}\,q_{h})=0\quad\quad\forall q_{h}\!\in\!\Theta_{h}.\]

The next three results check the hypotheses (5.14) and (5.17). They will lead in particular to an interesting decomposition of our discrete finite element spaces. Before proving that the space \(\Phi_{h0}\) satisfies (5.14), let us show the following preliminary result.

**Lemma 5.10**.: _Let \(\mathbf{u}\) be a function of the form:_

\[\mathbf{u}=\mathbf{grad}\,p\quad\text{with }p\!\in\!H_{0}^{1}(\Omega)\]

_and assume that \(\mathbf{u}\) is such that \(r_{h}\mathbf{u}\) is well defined. Then there exists \(p_{h}\) in \(\Theta_{h}\) such that_

\[r_{h}\mathbf{u}=\mathbf{grad}\,p_{h}.\]

Proof.: As \(\mathbf{curl}\,\mathbf{u}=\mathbf{0}\), Remark 5.6 implies that

\[\mathbf{curl}\,r_{h}\mathbf{u}=\mathbf{0}\quad\text{in each }\kappa.\]

But since \(p\) is constant on \(\Gamma\), we also have \(\mathbf{u}\times\mathbf{n}=\mathbf{0}\) on \(\Gamma\). Therefore, it follows from Lemma 5.9 that \(r_{h}\mathbf{u}\!\in\!H_{0}(\mathbf{curl};\Omega)\); this means that

\[\mathbf{curl}\,r_{h}\mathbf{u}=\mathbf{0}\quad\text{in }\Omega,\quad\,r_{h} \mathbf{u}\times\mathbf{n}=\mathbf{0}\quad\text{on }\Gamma.\]

Hence
