and let

\[r_{h}\mathbf{v}|_{\kappa}=r_{\kappa}\mathbf{v}\ \ \ \ \ \forall\kappa\in\mathcal{T}_{h}.\]

It follows from Lemma 2.1 that

\[r_{h}\in\mathcal{L}(\mathcal{C}^{0}(\bar{\Omega})^{2};\,W_{h})\cap\mathcal{L}(( \mathcal{C}^{0}(\bar{\Omega})\cap H^{1}_{0}(\Omega))^{2};\,\bar{X}_{h}).\]

However, if we want to check the inf-sup condition--i.e. Hypothesis H3--it is convenient, in vew of Lemma 1.1, to work right away with the appropriate operator \(\pi_{h}\). At first sight, it appears that the above operator \(r_{h}\) would do the trick since

\[\int_{\kappa}\operatorname{div}(\mathbf{v}-r_{\kappa}\mathbf{v})\,dx=\sum_{i= 1}^{3}\int_{f_{i}}(\mathbf{v}-r_{\kappa}\mathbf{v})\cdot\mathbf{n}_{i}\,ds=0.\]

But strictly speaking, \(r_{h}\) does not satisfy H3 because it is defined on \(H^{2}(\Omega)^{2}\) instead of \(H^{1}(\Omega)^{2}\). Thus we must replace \(r_{h}\) by another operator which does not involve the values of \(\mathbf{v}\) at the vertices of \(\kappa\). The easiest way of turning the difficulty consists in replacing the values of \(\mathbf{v}\) by those of the projection \(P_{h}\mathbf{v}\) on \(X_{h}\). From a practical point of view, this global regularization is not satisfactory because the corresponding proof requires the uniform regularity of the triangulation (cf. Theorem A.2 and Girault & Raviart [32]). This additional requirement, which stems from the global regularization and not from the above approximation, can be released by using instead the local regularization operator in Section A.3.

Thus, following Bernardi & Raugel [10], with each \(\mathbf{v}\in H^{1}_{0}(\Omega)^{2}\) we associate the function \(\mathbf{w}_{h}=R_{h}\mathbf{v}\in\Phi_{h}^{2}\) where

\[\mathcal{O}_{h}=\{\phi\in\mathcal{C}^{0}(\bar{\Omega});\,\phi|_{\kappa}\in P_ {1}\ \ \ \forall\kappa\in\mathcal{T}_{h}\}\cap H^{1}_{0}(\Omega)\]

and \(R_{h}\) is defined by (A.53), (A.54). Then we define the operator \(\pi_{h}\in\mathcal{L}(H^{1}_{0}(\Omega)^{2};\,\bar{X}_{h})\) by:

\[\begin{cases}\pi_{h}\mathbf{v}(a)=R_{h}\mathbf{v}(a)\ \ \ \ \ \forall\text{node}\,a\text{ of }\mathcal{T}_{h},\\ \int_{f}(\pi_{h}\mathbf{v}-\mathbf{v})\cdot\mathbf{n}\,ds=0\ \ \ \ \ \forall\text{side}\,f\text{ of }\mathcal{T}_{h}.\end{cases}\] (2.7)

Now assume that the family of triangulations \(\mathcal{T}_{h}\) is regular in the sense of Definition A.2, i.e.

\[h_{\kappa}/\rho_{\kappa}\leq\sigma\ \ \ \ \ \forall\kappa\in\mathcal{T}_{h},\ \ \ \ \ \sigma\text{ independent of }h.\] (2.8)

The next lemma shows that \(\pi_{h}\) satisfies Hypothesis H1 with \(l=1\) as well as Hypothesis H3.

**Lemma 2.2**.: _If the triangulation \(\mathcal{T}_{h}\) is regular, then_

\[|\mathbf{v}-\pi_{h}\mathbf{v}|_{m,\Omega}\leq Ch^{k-m}|\mathbf{v}|_{k,\Omega} \ \ \ \ \ \forall\mathbf{v}\in H^{k}(\Omega)^{2}\] (2.9)

_for \(m=0\) or \(1\) and \(k=1\) or \(2\), with a positive constant \(C\) independent of \(h\) and \(\mathbf{v}\)._

_In addition, whatever the triangulation we have_
