arbitrary point of \(\Gamma_{0}\) (for instance!). Next, we choose a function \(\chi\) (in \(H^{3/2}(\Gamma)\)) which satisfies

(5.34) \[\partial\chi/\partial\tau=\mathbf{g}\cdot\mathbf{n}\quad\text{on }\Gamma, \quad\chi(x_{0})=0.\]

Since \(\partial\phi/\partial\tau=\mathbf{g}\cdot\mathbf{n}\) on \(\Gamma\), it follows that

\[\psi=\begin{cases}\chi&\text{on }\Gamma_{0},\\ \chi+c_{i}&\text{on }\Gamma_{i},\quad\ 1\leqslant i\leqslant p,\end{cases}\]

where the constants \(c_{i}\) are fixed but unknown.

**Theorem 5.5**.: _Let \(N=2\) and let the hypotheses of Theorem 5.1 be satisfied together with (5.33). Then, the associated stream function of \(\mathbf{u}\) may be characterized as the unique function \(\psi\in H^{2}(\Omega)\) solution of the equations_

(5.35) \[v(\Delta\psi,\Delta\phi)=\langle\mathbf{f},\mathbf{curl}\,\phi \rangle\quad\quad\forall\phi\in\Psi\quad(cf.\,\eqref{eq:v_1}),\] (5.36) \[\begin{cases}\psi=\chi&\text{on }\Gamma_{0},\quad\ \psi=\chi+c_{i}&\text{on }\Gamma_{i}, \quad\ 1\leqslant i\leqslant p,\\ &\partial\psi/\partial n=-\mathbf{g}\cdot\tau&\text{on }\Gamma,\end{cases}\]

_where \(\chi\) is chosen according to (5.34)._

Proof.: We have already shown that the velocity field \(\mathbf{u}\) is the unique solution of (5.17). Now, the function \(\mathbf{u}\) satisfies the conditions

\[\operatorname{div}\mathbf{u}=0\quad\text{in }\Omega,\quad\ \mathbf{u}=\mathbf{g}\quad\text{on }\Gamma\]

if and only if \(\mathbf{u}=\mathbf{curl}\,\psi\) where the stream function \(\psi\in H^{2}(\Omega)\) satisfies the boundary conditions (5.36). Besides that, according to Corollary 3.2, \(\mathbf{v}\in V\) if and only if \(\mathbf{v}=\mathbf{curl}\,\phi\) with \(\phi\in\Psi\). Thus, the theorem will be proved if we show that

(5.37) \[(\mathbf{grad}\,\mathbf{u},\mathbf{grad}\,\mathbf{v})=(\Delta\psi,\Delta\phi) \quad\quad\forall\mathbf{v}=\mathbf{curl}\,\phi,\quad\ \phi\in\Psi.\]

Here, we use the identities stated at the beginning of Section 2.3. First, we have

\[(\Delta\psi,\Delta\phi)=(\operatorname{curl}(\mathbf{curl}\,\psi), \operatorname{curl}(\mathbf{curl}\,\phi))=(\operatorname{curl}\,\mathbf{u}, \operatorname{curl}\,\mathbf{v}).\]

Next, we take \(\mathbf{v}\) in \(\mathcal{V}=\langle\mathbf{v}\in\mathcal{D}(\Omega)^{2};\operatorname{div} \mathbf{v}=0\rangle\) and recall that according to Corollary 2.5, \(\mathcal{V}\) is dense in \(V\). In the sense of distributions, we have:

\[(\operatorname{curl}\,\mathbf{u},\operatorname{curl}\,\mathbf{v}) =\langle\mathbf{curl}(\operatorname{curl}\,\mathbf{u}),\mathbf{v}\rangle\] \[=\langle-\Delta\mathbf{u},\mathbf{v}\rangle\quad\text{because} \quad\operatorname{div}\mathbf{u}=0,\] \[=(\mathbf{grad}\,\mathbf{u},\mathbf{grad}\,\mathbf{v}).\]

Thus the density of \(\mathcal{V}\) in \(V\) yields (5.37). 

It remains to interpret Problem (5.35) (5.36). By applying (formally) Green's formula, we can easily show that \(\psi\) is the only solution of the boundary value problem:
