### A General Result

Let \(X\) and \(M\) be two (real) Hilbert spaces with norms \(\|\,.\,\|_{X}\) and \(\|\,.\,\|_{M}\) respectively. Let \(X^{\prime}\) and \(M^{\prime}\) be their corresponding dual spaces and let \(\|\,\cdot\,\|_{X^{\prime}}\) and \(\|\,.\,\|_{M^{\prime}}\) denote their dual norms. As usual, we denote by \(\langle\,.\,,\,.\,\rangle\) the duality pairing between the spaces \(X\) and \(X^{\prime}\) or \(M\) and \(M^{\prime}\).

We introduce two bilinear continuous forms:

\[a(.\,,\,.)\colon X\times X\to\mathbb{R},\quad\,b(.\,,\,.)\colon X\times M\to \mathbb{R},\]

with norms

\[\|\,a\,\|=\sup_{u,\,v\,\in\,X,\,u,\,v\neq 0}\frac{a(u,v)}{\|\,u\,\|_{X}\,\|\,v\, \|_{X}},\quad\,\|\,b\,\|=\sup_{v\,\in\,X,\,\mu\,\in\,M,\,v\neq 0,\,\mu\neq 0} \frac{b(v,\mu)}{\|\,v\,\|_{X}\,\|\,\mu\,\|_{M}}.\]

Then, we consider the following variational problem, called _Problem_ (\(Q\)):

_Given \(l\!\in\!X^{\prime}\) and \(\chi\!\in\!M^{\prime}\), find a pair \((u,\lambda)\!\in\!X\times M\) such that_

\[a(u,v)+b(v,\lambda)=\langle l,v\rangle\quad\,\,\,\forall v\!\in\!X,\] (4.1) \[b(u,\mu)=\langle\,\chi,\mu\rangle\quad\,\,\,\forall\mu\!\in\!M.\] (4.2)

In order to study Problem (Q), we require some extra notations. With the bilinear forms \(a(.\,,\,.)\) and \(b(.\,,\,.)\), we associate two linear operators \(A\!\in\!\mathcal{L}(X;X^{\prime})\) and \(B\!\in\!\mathcal{L}(X,M^{\prime})\) defined by:

\[\langle Au,v\rangle=a(u,v)\quad\,\,\,\forall u,\,v\!\in\!X,\] (4.3) \[\langle Bv,\mu\rangle=b(v,\mu)\quad\,\,\,\forall v\!\in\!X,\quad \,\,\forall\mu\!\in\!M.\] (4.4)

Let \(B^{\prime}\!\in\!\mathcal{L}(M;X^{\prime})\) be the dual operator of \(B\), i.e.

\[\langle B^{\prime}\mu,v\rangle=\langle\,\mu,Bv\rangle=b(v,\mu)\quad\,\,\,\forall v \!\in\!X,\quad\,\,\forall\mu\!\in\!M.\] (4.5)

It can be readily verified that

\[\|\,A\,\|_{\mathcal{L}(X;X^{\prime})}=\|\,a\|,\quad\,\,\|\,B\,\|_{\mathcal{L} (X;M^{\prime})}=\|\,b\,\|.\] (4.6)

With these operators, Problem (Q) may be equivalently written in the form:

_Find \((u,\lambda)\!\in\!X\times M\) satisfying_

\[Au+B^{\prime}\lambda =l\quad\,\,\,in\,\,\,X^{\prime},\] \[Bu =\chi\quad\,\,\,in\,\,\,M^{\prime}.\]

Let us now introduce the linear operator \(\Phi\!\in\!\mathcal{L}(X\times M;X^{\prime}\times M^{\prime})\) defined by:

\[\Phi(v,\mu)=(Av+B^{\prime}\mu,Bv).\]

Then, we shall say that _Problem_ (Q) _is well-posed_ if \(\Phi\) is an isomorphism from \(X\times M\) onto \(X^{\prime}\times M^{\prime}\). Our purpose is to derive necessary and sufficient conditions for Problem (Q) to be well-posed.
