or

\[\mathbf{n}\circ F_{\kappa}=[(B_{\kappa}^{-1})^{T}\hat{\mathbf{n}}]/\|(B_{\kappa}^{ -1})^{T}\hat{\mathbf{n}}\|\]

where \(x=F_{\kappa}(\hat{x})=B_{\kappa}\hat{x}+b_{\kappa}\) and \(B_{\kappa}\) is a nonsingular matrix with constant coefficients. On the other hand, we remark that

\[M_{n}(\tau)(x)=((\tau(x)\mathbf{n}(x),\mathbf{n}(x)))\]

where \(((.,.))\) denotes the Euclidean scalar product of \(\mathbb{R}^{2}\) associated with \(\|.\|\). Thus, we can write

\[(M_{n}(\tau))\circ F_{\kappa}=\|(B_{\kappa}^{-1})^{T}\hat{\mathbf{n}}\|^{-2}(( B_{\kappa}^{-1}(\tau\circ F_{\kappa})(B_{\kappa}^{-1})^{T}\hat{\mathbf{n}}, \hat{\mathbf{n}})).\]

This suggests to establish (in each \(\kappa\)) the correspondence between tensor-valued functions:

\[\tau=B_{\kappa}(\hat{t}\circ F_{\kappa}^{-1})B_{\kappa}^{T}=\mathcal{G}_{ \kappa}(\hat{t}),\]

or equivalently

\[\hat{t}=B_{\kappa}^{-1}(\tau\circ F_{\kappa})(B_{\kappa}^{-1})^{T}=\mathcal{G }_{\kappa}^{-1}(\tau).\]

The first equation can be written explicitly as follows:

\[\tau_{ij}=\sum_{r,s=1}^{2}(\hat{t}_{rs}\circ F_{\kappa}^{-1})(\partial F_{i}/ \partial\hat{x}_{r})(\partial F_{j}/\partial\hat{x}_{s}).\]

Obviously, the transformation \(\mathcal{G}_{\kappa}\) preserves the symmetry and regularity of tensors and furthermore:

\[\widehat{M_{n}(\tau)}=\|(B_{\kappa}^{-1})^{T}\hat{\mathbf{n}}\|^{-2}M_{\hat{n }}(\hat{t}),\] (4.26)

or

\[\widehat{M_{n}(\tau)}=\|B_{\kappa}^{T}(\mathbf{n}\circ F_{\kappa})\|^{2}M_{ \hat{n}}(\hat{t}),\]

since

\[\|B_{\kappa}^{T}(\mathbf{n}\circ F_{\kappa})\|=\|(B_{\kappa}^{-1})^{T}\hat{ \mathbf{n}}\|^{-1}.\]

Hence it is easy to check that the statement of Lemma 4 carries over to an arbitrary triangle \(\kappa\) of \(\mathcal{T}_{h}\). As a consequence, we can take the following values as degrees of freedom for the tensors \(\tau\) of \(\Sigma_{h}\):

\[\int_{\kappa^{\prime}}M_{n}(\tau)q\,ds\quad\quad\forall q\in P_{l- 1}(\kappa^{\prime}),\quad\quad\forall\kappa^{\prime}\text{ of }\Gamma_{h},\] \[\int_{\kappa}\tau_{ij}q\,dx\quad\quad\forall q\in P_{l-2}(\kappa) ,\quad\quad 1\leqslant i,j\leqslant 2,\quad\quad\forall\kappa\in\mathcal{T}_{h}, \quad\text{if }l\geqslant 2.\]

_Remark 4.1_.: The simplest example of spaces \(\Sigma_{h}\) corresponds to \(l=1\):

\[\Sigma_{h}=\{\tau\in L^{2}(\Omega)^{4};\,\tau_{ij}=\tau_{ji},\,\tau_{ij}|_{ \kappa}=\text{a constant }c_{ij}\quad\forall\kappa\text{ of }\mathcal{T}_{h},\]

\[M_{n}(\tau)\text{ is continuous on each segment of }\Gamma_{h}\}.\]
