(4.57) \[|p-p_{h}|_{1,\,\Omega}\leqslant C_{2}h^{k-1}\{|\mathbf{u}|_{k+1,\, \Omega}+|p|_{k,\,\Omega}\},\] (4.58) \[\|\mathbf{u}-\mathbf{u}_{h}+\mathbf{grad}\,\lambda_{h}\|_{0,\, \Omega}\leqslant C_{3}h^{k+1}\{|\mathbf{u}|_{k+1,\,\Omega}+|p|_{k,\,\Omega}\},\]

_where \((\mathbf{u}_{h},p_{h})\) is the solution of (4.50)...(4.53), \(\lambda_{h}\) is given by (4.55) and \(\check{p}_{h}\) is the representative of \(p_{h}\) in \(L^{2}_{0}(\Omega)\)._

_Proof_. We have:

(4.59) \[\begin{cases}v(\mathbf{grad}(\mathbf{u}-\mathbf{u}_{h}),\mathbf{ grad}\,\mathbf{v}_{h})+(\mathbf{grad}(p-p_{h}),\mathbf{v}_{h}-\mathbf{grad}\,q_{h})=0\\ \qquad\qquad\qquad\qquad\qquad\qquad\qquad\qquad\qquad\qquad\qquad\qquad \qquad\qquad\qquad\qquad\qquad\qquad\qquad\qquad\qquad\qquad\qquad\qquad \qquad\qquad\qquad\qquad\qquad\qquad\qquad\forall(\mathbf{v}_{h},q_{h})\! \in\!X_{h}\times\,\varPhi_{h},\\ \qquad\qquad\qquad\qquad\qquad(\mathbf{u}_{h}-\mathbf{grad}\,\lambda_{h}, \mathbf{grad}\,q_{h})=0\qquad\forall q_{h}\!\in\!Q_{h}.\end{cases}\]

Let us restrict the pair \((\mathbf{v}_{h},q_{h})\) to the space:

\[B_{h}=\{(\mathbf{v}_{h},q_{h})\!\in\!X_{h}\times\,\varPhi_{h};( \mathbf{v}_{h}-\mathbf{grad}\,q_{h},\mathbf{grad}\,\mu_{h})=0\quad\forall\mu_{ h}\!\in\!Q_{h}\}.\]

Note that \((\mathbf{u}_{h},\lambda_{h})\!\in\!B_{h}\). Then (4.59) reads:

\[v(\mathbf{grad}(\mathbf{u}-\mathbf{u}_{h}),\mathbf{grad}\,\mathbf{ v}_{h})+(\mathbf{grad}(p-\mu_{h}),\mathbf{v}_{h}-\mathbf{grad}\,q_{h})=0\] \[\qquad\qquad\qquad\qquad\qquad\qquad\qquad\qquad\qquad\qquad \qquad\qquad\qquad\qquad\qquad\qquad\qquad\qquad\forall(\mathbf{v}_{h},q_{h}) \!\in\!B_{h},\quad\forall\mu_{h}\!\in\!Q_{h}.\]

To get rid of \(\mathbf{grad}\,q_{h}\), we choose \(\mu_{h}=P_{h}p\), the \(H^{1}\)-projection of \(p\) on \(M_{h}\) defined by (A.25). Hence

\[v(\mathbf{grad}(\mathbf{u}-\mathbf{u}_{h}),\mathbf{grad}\,\mathbf{ v}_{h})=(\operatorname{div}\mathbf{v}_{h},p-P_{h}p)\quad\quad\forall(\mathbf{v}_{h},q_{h}) \!\in\!B_{h}.\]

As \((\mathbf{u}_{h},\lambda_{h})\!\in\!B_{h}\), this equation readily implies:

\[|\mathbf{u}-\mathbf{u}_{h}|_{1,\,\Omega}\leqslant 2|\mathbf{u}-\mathbf{w}_{h }|_{1,\,\Omega}+(\sqrt{2}/v)\,\|\,p-P_{h}p\|_{0,\,\Omega}\quad\quad\forall( \mathbf{w}_{h},q_{h})\!\in\!B_{h}.\]

Clearly, we may choose here the pair \((\mathbf{w}_{h},0)\) with \(\mathbf{w}_{h}\) in \(V_{h}\) and since the spaces \((X_{h},M_{h})\) satisfy the inf-sup condition (4.9) we can apply (1.16):

\[\inf_{\mathbf{w}_{h}\in V_{h}}|\mathbf{u}-\mathbf{w}_{h}|_{1,\, \Omega}\leqslant(1+\sqrt{2}/\beta^{*})\inf_{\mathbf{v}_{h}\in X_{h}}|\mathbf{u }-\mathbf{v}_{h}|_{1,\,\Omega}.\]

As a consequence,

\[|\mathbf{u}-\mathbf{u}_{h}|_{1,\,\Omega}\leqslant 2(1+\sqrt{2}/\beta^{*}) \inf_{\mathbf{v}_{h}\in X_{h}}|\mathbf{u}-\mathbf{v}_{h}|_{1,\,\Omega}+(\sqrt{ 2}/v)\,\|\,p-P_{h}p\|_{0,\,\Omega},\]

and the velocity bound in (4.56) follows from (4.16) and (A.26). Notice that it is (A.26) alone which requires the convexity of \(\Omega\) and the uniform regularity of \(\mathcal{T}_{h}\).

The bound for \(\lambda_{h}\) is obtained from the above inequality and the fact that \(\operatorname{div}\mathbf{u}=0\):

(4.60) \[(\mathbf{grad}\,\lambda_{h},\mathbf{grad}\,q_{h})=-(\mathbf{u}- \mathbf{u}_{h},\mathbf{grad}\,q_{h})\quad\quad\forall q_{h}\!\in\!Q_{h}.\]

Therefore

\[|\lambda_{h}|_{1,\,\Omega}\leqslant\|\mathbf{u}-\mathbf{u}_{h}\|_{0,\,\Omega}.\]

As far as the pressure is concerned, we revert to the standard situation by
