_2\({}^{\circ}\)) Moreover_, _when the mapping \(\lambda\to(\psi(\lambda),p*(\lambda))\) is continuous from \(\Lambda\) into \([H^{m+2}(\Omega)\cap W^{m+3/2,\,\infty}(\Omega)]\times H^{m}(\Omega)\) for some real \(m\in[1,l-1/2]\) we have the error estimate for all \(\lambda\) in \(\Lambda\)_:

(4.38) \[|\psi_{h}(\lambda)-\psi(\lambda)|_{1,\,s,\Omega}+\|\,\omega_{h}(\lambda)- \omega(\lambda)\|_{0,\,\Omega}+\|\,p_{h}^{*}(\lambda)-p^{*}(\lambda)\|_{0,\, \Omega}\leq Kh^{m}.\]

Like in the linear case, it is possible to sharpen the above estimate for \(\psi_{h}-\psi\) in the \(H^{1}_{0}\) norm. However, the argument of Theorem 3.5 does not seem to apply here because it would have to bear on both \(\psi\) and \(\omega\) whereas the estimate on \(\omega\) is unlikely to be improved. Let us introduce instead a more direct duality argument. Since we are not concerned by the pressure, we take

\[X=\{\mbox{\bf curl}\,\phi;\,\phi\in\Phi_{s}\}\,\times\,L^{2}(\Omega),\ \ \ \ H=\{\mbox{\bf curl}\,\phi;\,\phi\in\Phi\}\,\times\,L^{2}(\Omega)\]

and we suppose that

\[\lambda\to u(\lambda)=(\mbox{\bf curl}\,\psi(\lambda),\omega(\lambda))\]

is a branch of nonsingular solutions of Problem (4.32a) with \(\mbox{\bf f}\in L^{2}(\Omega)^{2}\). Again we assume that (4.18) holds so that \(u(\lambda)\) belongs to \(H^{2}(\Omega)\times H^{1}(\Omega)\). To simplify we denote

\[D=D_{u}G(\lambda,u(\lambda)).\]

Recall that

\[D\cdot v=\lambda(\omega(\lambda)\,\mbox{\bf grad}\,\phi\,+\,\theta\,\mbox{ \bf grad}\,\psi(\lambda))\ \ \ \ \ \forall v=(\mbox{\bf curl}\,\phi,\theta)\in X.\]

Then we introduce the operator \(D*\in\mathcal{L}(H;X^{\prime})\) defined by:

(4.39) \[\langle D*z,v\rangle=(\mbox{\bf curl}\,\chi,D\cdot v)\ \ \ \ \ \forall z=(\mbox{\bf curl}\,\chi,\mu)\in H.\]

To relate \(D\) and \(D*\) recall that the space \(V\) associated with \(X\) is

\[V=\{v=(\mbox{\bf curl}\,\phi,\theta)\in X;\,\tilde{b}(v,\mu)=0\ \ \ \ \forall\mu\in W^{1,\,r}(\Omega)\},\]

where

\[\tilde{b}(v,\mu)=(\mbox{\bf curl}\,\phi,\mbox{\bf curl}\,\mu)-(\theta,\mu).\]

Recall also that \(V\) is a Hilbert space for the scalar product

\[\tilde{a}(u,v)=(\omega,\theta)\ \ \ \ \ \forall u=(\mbox{\bf curl}\,\psi, \omega),\ \ \ \ \ v=(\mbox{\bf curl}\,\phi,\theta)\in V\]

and that the definition of the Stokes operator can be extended to

\[T\in\mathcal{L}(X^{\prime};V),\ \ \ \ \ \tilde{a}(Tl,v)=\langle l,v\rangle\ \ \ \ \ \forall v\in V.\]

Thus it follows readily from (4.39) that

\[\tilde{a}(TD*z,v)=\tilde{a}(TDv,z)\ \ \ \ \ \forall z,\,v\in V.\]

In other words, \(TD*\)_is the adjoint of TD in \(V\)_ for the scalar product \(\tilde{a}(.,.)\). As a consequence, since by assumption \(I+TD\) is an isomorphism of \(V\), then \(I+TD*\)_is also an isomorphism of \(V\).
