We close this section with two useful applications of Green's formula.

**Lemma 1.4**.: _Let \(\Omega\) be a bounded open subset of \(\mathbb{R}^{N}\) with a Lipschitz-continuous boundary \(\Gamma.\)_

\(1^{\circ})\) _For \(u\) and \(v\) in \(H^{1}(\Omega)\) and for \(1\leqslant i\leqslant N,\) we have_:__

(1.19) \[\int_{\Omega}u(\partial v/\partial x_{i})\,dx=-\int_{\Omega}(\partial u/ \partial x_{i})v\,dx+\int_{\Gamma}\gamma_{0}(uv)n_{i}\,ds.\]

\(2^{\circ})\) _If in addition \(u\!\in\!H^{2}(\Omega)\) we have_:__

(1.20) \[\sum\limits_{i=1}^{N}\int_{\Omega}\frac{\partial u}{\partial x_{i}}\frac{ \partial v}{\partial x_{i}}\,dx=-\sum\limits_{i=1}^{N}\int_{\Omega}\frac{ \partial^{2}u}{\partial x_{i}^{2}}v\,dx+\sum\limits_{i=1}^{N}\int_{\Gamma} \gamma_{0}\biggl{(}\frac{\partial u}{\partial x_{i}}\,v\biggr{)}n_{i}\,ds.\]

Adopting the usual notations:

\[\Delta u=\sum\limits_{i=1}^{N}\frac{\partial^{2}u}{\partial x_{i}^{2}},\ \ \ \ \ \mathbf{ grad}\,u=(\partial u/\partial x_{1},\ldots,\partial u/\partial x_{N}),\]

(1.20) becomes:__

(1.21) \[(\mathbf{grad}\,u,\mathbf{grad}\,v)=-(\Delta u,v)+\int_{\Gamma}(\partial u/ \partial n)\gamma_{0}\,v\,ds.\]

### Abstract Elliptic Theory

This section gives a brief account of a fundamental tool used in studying linear partial differential equations of elliptic type.

Let \(V\) be a real Hilbert space with norm denoted by \(\|\,.\,\|_{V};\) let \(V^{\prime}\) be its dual space and let \(\langle.,.\,.\rangle\) denote the duality pairing between \(V^{\prime}\) and \(V.\) Let \((u,v)\!\to\!a(u,v)\) be a real bilinear form on \(V\times V,\)\(l\) an element of \(V^{\prime}\) and consider the following problem:

\[Find\ u\!\in\!V\ \text{such that}\] (P) \[a(u,v)=\langle l,v\rangle\ \ \ \ \ \forall v\!\in\!V.\]

The following theorem is due to Lax & Milgram [49].

**Theorem 1.7**.: _We assume that a is continuous and elliptic on \(V,\) i.e. there exist two constants \(M\) and \(\alpha>0\) such that_

(1.22) \[|a(u,v)|\leqslant M\|u\|_{V}\|v\|_{V}\ \ \ \ \ \forall u,\,v\!\in\!V\]

_and_

(1.23) \[a(v,v)\geqslant\alpha\|v\|_{V}^{2}\ \ \ \ \ \forall v\!\in\!V.\]

_Then Problem (P) has one and only one solution \(u\) in V. Moreover, the mapping \(l\to u\) is an isomorphism from \(V^{\prime}\) onto V._
