solve the homogeneous boundary value problem:

\[\left\{\begin{aligned} -(v\mathcal{A}+r\,\mathbf{grad}\,\mathrm{div}) \mathbf{z}^{m}&=\mathbf{grad}\,\omega^{m}\quad\text{in }\Omega,\\ \mathbf{z}^{m}&=\mathbf{0}\quad\text{on }\Gamma, \end{aligned}\right.\]

and compute \(\rho^{m}\!\in\!\mathbb{R}\) and the next pair \((\mathbf{u}^{m+1},p^{m+1})\!\in\!H^{1}(\Omega)^{N}\times L_{0}^{2}(\Omega)\) by:

\[\rho^{m} = -\frac{\|\,\mathrm{div}\,\mathbf{u}^{m}\|_{\,\Omega,\,\Omega}^{2 }}{(\mathrm{div}\,\mathbf{z}^{m},\mathrm{div}\,\mathbf{u}^{m})},\] \[p^{m+1} = p^{m}-\rho^{m}\omega^{m},\] \[\mathbf{u}^{m+1} = \mathbf{u}^{m}+\rho^{m}\mathbf{z}^{m}.\]

Here again, Corollary 4.6 guarantees that the conjugate-gradient algorithm is convergent.

We end this section with a theorem due to Cattabriga [18] concerning the existence and regularity of the solution of the Stokes problem (5.12) in more general Sobolev spaces when the boundary \(\Gamma\) is sufficiently smooth.

**Theorem 5.4**.: _In addition to the hypotheses of Theorem 5.1_, _suppose that the boundary \(\Gamma\) is of class \(\mathcal{C}^{\max(2,m+2)},\,\mathbf{f}\!\in\!W^{m,r}(\Omega)^{N}\) and \(\mathbf{g}\!\in\!W^{m+2-1/r,r}(\Gamma)^{N}\) for some integer \(m\geqslant-1\) and some real \(r\) with \(1<r<\infty\). Then, Problem (5.12) has a unique solution \((\mathbf{u},p)\!\in\!W^{m+2,r}(\Omega)^{N}\times W^{m+1,r}(\Omega)\) with \(\int_{\Omega}p\,dx=0\) and there exists a constant \(C\) independent of \(\mathbf{f}\) and \(\mathbf{g}\) such that_

(5.32) \[\|\,\mathbf{u}\|_{\,m+2,r,\,\Omega}+\|\,p\|_{\,m+1,r,\,\Omega}\leqslant C(\| \mathbf{f}\|_{\,m,r,\,\Omega}+\|\,\mathbf{g}\|_{\,m+2-1/r,r,\,r}).\]

_Remark 5.6_.: In the case of a polyhedral domain \(\Omega\), the regularity properties of the solution of Problem (5.12) are clearly weaker. In particular, when \(N=2\) and \(\Omega\) is a convex polygon, the conclusions of the theorem are still valid for \(m\leqslant 0\) and \(1<r\leqslant 2\) (cf. Grisvard [43]).

### The Stream Function Formulation of the Dirichlet Problem in Two Dimensions

Let us again denote by \(\Gamma_{i}\), \(0\leqslant i\leqslant p\), the components of the boundary \(\Gamma\) like in Figure 2. Now, instead of (5.11), we assume the stronger condition

(5.33) \[\int_{\Gamma_{i}}\mathbf{g}\!\cdot\!\mathbf{n}\,ds=0,\quad\ 0\leqslant i \leqslant p.\]

Then, according to Theorems 3.1 and 3.4, the velocity field \(\mathbf{u}\) given by Theorem 5.1 may be expressed as the **curl** of a stream function \(\psi\) (\(N=2\)) or a vector potential \(\psi\) (\(N=3\)). We are going to show that this stream function or this vector potential can be characterized as the solution of a biharmonic problem in \(\Omega\).

We begin with the case \(N=2\). Then, the stream function \(\psi\) is unique up to an additive constant. But, as \(\psi\!\in\!H^{2}(\Omega)\!\subset\!\mathcal{C}^{0}(\bar{\Omega})\!,\psi\) can be uniquely determined by fixing its value in one point of \(\Omega\). At first, we set \(\psi(x_{0})=0\), where \(x_{0}\) is an
