### Abstract Mixed Approximation

Throughout this section we assume that the hypotheses of Theorem 1.1 hold.

For each \(h\) let \(X_{h}\) and \(M_{h}\) be two _finite-dimensional_ subspaces of \(\tilde{X}\) and \(\tilde{M}\) respectively. We approximate Problem (\(\bar{\mathbb{Q}}\)) by _Problem_ (\(\mathrm{Q}_{h}\)):

_Find a pair \((u_{h},\lambda_{h})\!\in\!X_{h}\times M_{h}\) such that_

(16) \[\tilde{a}(u_{h},v_{h})+\tilde{b}(v_{h},\lambda_{h}) =\langle l,v_{h}\rangle\qquad\forall v_{h}\!\in\!X_{h},\] (17) \[\tilde{b}(u_{h},\mu_{h}) =\langle\chi,\mu_{h}\rangle\qquad\forall\mu_{h}\!\in\!M_{h}.\]

Again we define

(18) \[V_{h}(\chi)=\{v_{h}\!\in\!X_{h};\,\tilde{b}(v_{h},\mu_{h})= \langle\chi,\mu_{h}\rangle\quad\forall\mu_{h}\!\in\!M_{h}\},\] \[V_{h}=V_{h}(0).\]

Next we associate with Problem (\(\mathrm{Q}_{h}\)) the following _Problem_ (\(\mathrm{P}_{h}\)):

_Find \(u_{h}\!\in\!V_{h}(\chi)\) such that_

(19) \[\tilde{a}(u_{h},v_{h})=\langle l,v_{h}\rangle\qquad\forall v_{h}\!\in\!V_{h}.\]

Here also \(V_{h}\) is generally not included in \(\tilde{V}\) and therefore Problem (\(\mathrm{P}_{h}\)) is an external approximation of Problem (\(\bar{\mathbb{P}}\)).

In order to derive error estimates for \(u_{h}\) and \(\lambda_{h}\) we make the following assumptions, analogous to (14) and (15):

i) there exists a constant \(\alpha^{*}>0\) such that

(20) \[\tilde{a}(v_{h},v_{h})\geq\alpha^{*}\|v_{h}\|_{\tilde{X}}^{2}\qquad\forall v_ {h}\!\in\!V_{h};\]

ii) there exists a constant \(\beta^{*}>0\) such that

(21) \[\sup_{v_{h}\!\in\!X_{h}}\frac{\tilde{b}(v_{h},\mu_{h})}{\|v_{h}\|_{\tilde{X}} }\geq\beta^{*}\|\mu_{h}\|_{M}\quad\quad\forall\mu_{h}\!\in\!M_{h}.\]

The next theorem is a natural extension of Theorem II.1.1.

**Theorem 1.2**: \(1^{\circ}\)_Suppose \(V_{h}(\chi)\) is not empty and \(\tilde{a}(.,.)\) satisfies (20). Then Problem (\(\mathrm{P}_{h}\)) has a unique solution \(u_{h}\!\in\!V_{h}(\chi)\) and the following error bound holds:_

\[\|u-u_{h}\|_{\tilde{X}}\leq(1+\|\tilde{a}\|/\alpha^{*})\inf_{v_{h}\!\in\!V_{h} (\chi)}\|u-v_{h}\|_{\tilde{X}}+(1/\alpha^{*})\inf_{\mu_{h}\!\in\!M_{h}}\!\! \left[\sup_{v_{h}\!\in\!V_{h}}\frac{\tilde{b}(v_{h},\lambda-\mu_{h})}{\|v_{h} \|_{\tilde{X}}}\right]\!.\] (22)

\(2^{\circ}\)_Suppose moreover that \(\tilde{b}(.,.)\) satisfies (21). Then \(V_{h}(\chi)\) is not empty and Problem (\(\mathrm{Q}_{h}\)) has exactly one solution \((u_{h},\lambda_{h})\) where \(u_{h}\) is the solution of Problem (\(\mathrm{P}_{h}\)). Furthermore \(\lambda_{h}\) satisfies the error estimate_:

\[\|\,\lambda-\lambda_{h}\|_{M}\leq\!\!\left(\frac{\|\tilde{a}\|}{\beta^{*}} \right)\|u-u_{h}\|_{\tilde{X}}+\inf_{\mu_{h}\!\in\!M_{h}}\!\left\{\!\!\left( \frac{\|\tilde{b}\|}{\beta^{*}}\right)\|\lambda-\mu_{h}\|_{\tilde{M}}+\|\, \lambda-\mu_{h}\|_{M}\!\right\}\!.\] (23)
