\[\int_{\kappa}\operatorname{\mathbf{curl}}\phi\cdot\operatorname{\mathbf{curl}} \theta\,dx=-\int_{\kappa}\Delta\phi\theta\,dx+\int_{\partial\kappa}(\partial \phi/\partial n)\theta\,ds,\]

where \(\mathbf{n}\) denotes the exterior unit normal to \(\kappa\). In order to sum this identity over all elements \(\kappa\) of \(\mathcal{T}_{h}\), it is convenient to define the set:

\[\Gamma_{h}=\{\bigcup\kappa^{\prime};\,\text{for all sides $\kappa^{\prime}$ of $\kappa$ and all elements $\kappa$ of $\mathcal{T}_{h}$}\}\]

and the jump \(S(\partial\phi/\partial n)\) of \(\partial\phi/\partial n\) across the side \(\kappa^{\prime}\) of \(\kappa\). More precisely, if \(\kappa^{\prime}\) is a side shared by \(\kappa_{1}\) and \(\kappa_{2}\) and \(\mathbf{n}_{i}\) denotes the exterior normal to \(\kappa_{i}\) we set

\[S(\partial\phi/\partial n)|_{\kappa^{\prime}}=\partial\phi/\partial n_{1}+ \partial\phi/\partial n_{2}\]

and if \(\kappa^{\prime}\subset\Gamma\) we set

\[S(\partial\phi/\partial n)|_{\kappa^{\prime}}=\partial\phi/\partial n.\]

With these notations we have

(2.47) \[\begin{cases}(\operatorname{\mathbf{curl}}\phi,\operatorname{ \mathbf{curl}}\theta)=-\sum\limits_{\kappa\,\in\,\mathcal{T}_{h}}\int_{\kappa }\Delta\phi\theta\,dx+\int_{\Gamma_{h}}S(\partial\phi/\partial n)\theta\,ds \\ \forall\phi\in H^{1}(\Omega)\text{ with }\phi\in H^{2}(\kappa)\text{ on each $\kappa$ of $\mathcal{T}_{h}$}, \quad\forall\theta\in H^{1}(\Omega).\end{cases}\]

From now on, we are going to work with \(L^{2}\) and \(H^{m}\)-spaces. The identity (2.47) is the basis for another Problem (\(\mathbf{Q}\)) that is equivalent to Problem (2.20). Indeed, if the solution \(\mathbf{u}\) and right-hand side \(\mathbf{f}\) of the Stokes Problem (2.1) satisfy: \(\mathbf{f}\in L^{2}(\Omega)^{2}\), \(\omega=\operatorname{curl}\mathbf{u}\in H^{1}(\Omega)\) then an easy argument shows that the pair \((\psi,\omega)\) satisfying (2.20) is also the only solution of _Problem_ (\(\mathbf{Q}\)):

\[\begin{cases}-\,v\sum\limits_{\kappa\,\in\,\mathcal{T}_{h}}\int_{\kappa} \Delta\phi\omega\,dx+v\int_{\Gamma_{h}}S(\partial\phi/\partial n)\omega\,ds =(\mathbf{f},\operatorname{\mathbf{curl}}\phi),\\ (\omega,\mu)+\sum\limits_{\kappa\,\in\,\mathcal{T}_{h}}\int_{\kappa}\Delta \psi\mu\,dx-\int_{\Gamma_{h}}S(\partial\psi/\partial n)\mu\,ds=0,\\ \forall\mu\in H^{1}(\Omega),\quad\forall\phi\in\tilde{\mathcal{V}}\text{ with }\\ \tilde{\mathcal{V}}=\{\phi\in\Phi;\,\phi|_{\kappa}\in H^{2}(\kappa)\quad\forall \kappa\in\mathcal{T}_{h}\}.\end{cases}\]

As far as the approximation is concerned, we notice that the functions of \(\Phi_{h}\) (cf. (2.39)) belong to \(\Phi\) globally and to \(H^{2}(\kappa)\) (in particular) on each \(\kappa\). Thus the identity (2.47) is valid for \(\phi_{h}\) in \(\Phi_{h}\) and \(\theta_{h}\) in \(\Theta_{h}\) and consequently, Problem (2.29) is equivalent to the following _Problem_ (\(\operatorname{Q}_{h}\)):

\[\begin{cases}-\,v\sum\limits_{\kappa\,\in\,\mathcal{T}_{h}}\int_{\kappa}\mathcal{ A}\phi_{h}\omega_{h}\,dx+v\int_{\Gamma_{h}}S(\partial\phi_{h}/\partial n)\omega_{h}\,ds =(\mathbf{f},\operatorname{\mathbf{curl}}\phi_{h})\quad\forall\phi_{h}\in \Phi_{h},\\ (\omega_{h},\mu_{h})+\sum\limits_{\kappa\,\in\,\mathcal{T}_{h}}\int_{\kappa} \mathcal{A}\psi_{h}\mu_{h}\,dx-\int_{\Gamma_{h}}S(\partial\psi_{h}/\partial n )\mu_{h}\,ds=0\quad\forall\mu_{h}\in\Theta_{h}.\end{cases}\] (2.48)
