where \(x\) stands for \(\|u^{\epsilon}-u\|_{X}\). If \(\varepsilon\) is sufficiently small, this amounts to

\[\|u^{\epsilon}-u\|_{X}\leq\varepsilon C_{3}\|\lambda\|_{M}.\]

This, together with (4.34), proves the bound (4.32). 

_Remark 4.3_.: Problem (\(Q^{\epsilon}\)) has a unique solution even when the inf-sup condition (4.9) does not hold. Hence, in (4.28), \(-\varepsilon c(\lambda^{\varepsilon},\mu)\) plays the role of a regularizing term: Problem (\(Q^{\epsilon}\)) appears to be a regularized version of Problem (Q).

_Remark 4.4_.: When the bilinear forms \(a(.,.)\) and \(c(.,.)\) are symmetric, so is the bilinear form \(u\), \(v\to a(u,v)+(1/\varepsilon)\langle C^{-1}Bu,Bv\rangle\). In this case, setting

\[J_{\varepsilon}(v)=J(v)+\frac{1}{2\varepsilon}\langle C^{-1}(Bv-\gamma),Bv- \gamma\rangle\]

and using the ellipticity property (4.31) with \(\varepsilon\leq 1\), we obtain that Problem (P\({}^{\varepsilon}\)) amounts to find \(u^{\epsilon}\!\in\!X\) such that

\[J_{\varepsilon}(u^{\epsilon})=\inf_{v\in X}J_{\varepsilon}(v).\]

Hence, we have approximated the constrained optimization problem (4.20) for the energy functional \(J\) by an unconstrained one for the penalized functional \(J_{\varepsilon}\) where the expression \(\langle C^{-1}(Bv-\gamma),Bv-\gamma\rangle\)/(\(2\varepsilon\)) is a penalty term corresponding to the constraint \(Bv=\gamma\). Thus, Problem (P\({}^{\varepsilon}\)) is a penalized version of Problem (P).

In fact, we can derive a more precise result than Theorem 4.3, namely an asymptotic expansion of \((u^{\varepsilon},\lambda^{\varepsilon})\) in powers of \(\varepsilon\). We define by induction a sequence \((u_{n},\lambda_{n})\!\in\!X\times M\) in the following way. We set \(\lambda_{0}=\lambda\) and, for any integer \(n\geq 1\), the pair \((u_{n},\lambda_{n})\!\in\!X\times M\) is the solution of:

\[\begin{cases}a(u_{n},v)+b(v,\lambda_{n})=0&\quad\forall v\!\in\!X,\\ b(u_{n},\mu)=c(\lambda_{n-1},\mu)&\quad\forall\mu\!\in\!M.\end{cases}\] (4.35)

Knowing \(\lambda_{n-1}\), it follows from (4.9), (4.31) and Corollary 4.1, that the equations (4.35) define indeed a unique pair \((u_{n},\lambda_{n})\!\in\!X\times M\).

**Theorem 4.4**.: _Assume the hypotheses of Theorem 4.3. Then, we have for all integers \(N\geq 1\) and for \(\varepsilon\leq\varepsilon_{0}\) small enough_

\[\left\|u^{\epsilon}-u-\sum_{n=1}^{N}\varepsilon^{n}u_{n}\right\|_{X}+\left\| \lambda^{\varepsilon}-\lambda-\sum_{n=1}^{N}\varepsilon^{n}\lambda_{n} \right\|_{M}\leq K_{N}\varepsilon^{N+1}(\|l\|_{X^{\prime}}+\|\chi\|_{M^{ \prime}}),\] (4.36)

_where the constant \(K_{N}\) depends only upon \(N\), \(\alpha\), \(\beta\), \(\|a\|\), \(\|b\|\) and \(\|c\|\)._
