This scheme has the same order of convergence as (2.36) but the proof requires more regularity of the solution (cf. Girault & Raviart [33]).

_Remark 4.7_.: Of course, we can use here a continuous approximation of the pressure analogous to (2.36), but the error analysis of the corresponding scheme is more delicate.

## 5. A "Vector Potential-Vorticity" Scheme in Three Dimensions

It is not easy to adapt the schemes developed in the previous paragraphs to the three-dimensional Stokes problem. The obvious reason is that the conditions determining the vector potential are more intricate than those defining the two-dimensional stream function. Therefore we shall only attempt to extend to the homogeneous Stokes problem in a very simple region of \(\mathbb{R}^{3}\) the "stream function-vorticity" scheme of SS2.

Throughout this paragraph, we shall assume that \(\Omega\) is a _bounded_, _simply-connected open subset of \(\mathbb{R}^{3}\) with a polyhedral connected bounded \(\Gamma\)_. Leaving the approximation of the pressure to the last section, our first object is to relax the regularity of the function spaces related to the biharmonic problems of Section I.5.3. The reader will discover that it suffices to work with functions in \(H(\operatorname{\mathbf{curl}};\Omega)\). This approach will lead to the construction of finite-dimensional subspaces of conforming finite elements in \(H(\operatorname{\mathbf{curl}};\Omega)\), which are not subspaces of \(H^{1}(\Omega)^{3}\).

Finally, since discontinuous elements are used it is reasonable to use a discontinuous approximation of the pressure, very similar to that of Section 4.4.

### A Mixed Formulation of the Three-Dimensional Stokes Problem

Let \(\mathbf{f}\) be a given vector of \(L^{2}(\Omega)^{3}\) and consider the _homogeneous_ Stokes Problem:

_Find \((\mathbf{u},p)\) in \(H^{1}(\Omega)^{3}\times L^{2}_{0}(\Omega)\) satisfying_:

(5.1) \[\begin{cases}-\,v\,A\,\mathbf{u}\,+\,\operatorname{\mathbf{grad}}\,p=\mathbf{ f},\\ \quad\quad\quad\quad\quad\operatorname{div}\,\mathbf{u}=0\end{cases}\quad\text{ in }\Omega,\\ \mathbf{u}=\mathbf{0}\quad\text{ on }\Gamma.\]

We have seen in Section I.5.3 that this problem can be interpreted as a biharmonic problem for the vector potential \(\psi\) of \(\mathbf{u}\) (recall that \(\mathbf{u}=\operatorname{\mathbf{curl}}\psi\)) where \(\psi\) belongs to the space:

(5.2) \[\Psi=\{\phi\in L^{2}(\Omega)^{3};\,\operatorname{div}\phi\in H^{1}(\Omega), \,\operatorname{\mathbf{curl}}\phi\in H^{1}_{0}(\Omega)^{3},\,\phi\times\, \mathbf{n}|_{\Gamma}=\mathbf{0}\}.\]

In order to derive a mixed formulation of Problem (5.1), let us multiply both sides of (5.1) with \(\operatorname{\mathbf{curl}}\phi\) and determine exactly what properties we require of \(\phi\)
