\[|a_{2}(u_{h};v_{h}-z,\mathbf{w}_{h}-\mathbf{w})| \leqslant C_{5}h^{1/2}\,\|\mathbf{u}_{h}\|_{0,\,4,\,\Omega}[\phi_{h}- \alpha]_{4}[\chi_{h}-\chi]_{2}\] \[\leqslant C_{6}h^{1/2}\,\|\mathbf{u}_{h}\|_{0,\,4,\,\Omega}|w_{h}| [\phi_{h}-\alpha]_{4}.\]

By collecting these inequalities, we obtain (5.34). 

_Remark 5.1_.: It follows from Lemma 5.2 and the argument of Lemma 5.3 that the mapping \(G_{h}\) is Lipschitz-continuous on \(V_{h}\):

(5.35) \[\|G_{h}(u_{h})-G_{h}(u_{h}^{\star})\|_{\star}\leqslant C(|u_{h}|+|u_{h}^{\star }|)|u_{h}-u_{h}^{\star}|\ \ \ \ \ \forall u_{h},u_{h}^{\star}\!\in\!V_{h},\]

with a constant \(C\) independent of \(h\).

Now we are in a position to define the operator \(FG_{h}(u_{h})\), i.e. to approach as best as we can the "derivative" of the form \(\tilde{a}(\cdot;,\,.\,.)\). Clearly, the simplest guess is to linearize the dependence of \(\tilde{a}^{z_{h}}(\cdot;\,,\,.\,.)\) with respect to \(z_{h}\). Thus we set:

**Definition 5.1**.: For all \(u_{h}\!\in\!V_{h}\), the operator \(FG_{h}(u_{h})\!\in\!\mathcal{L}(V_{h};\,Y_{h})\) is defined by

\[\langle\!\nabla G_{h}(u_{h})\!\cdot\!v_{h},\mathbf{w}_{h}\rangle=\tilde{a}^{u _{h}}(u_{h};v_{h},\mathbf{w}_{h})+\tilde{a}^{u_{h}}(v_{h};u_{h},\mathbf{w}_{h })\ \ \ \ \ \forall\mathbf{w}_{h}=\mathbf{curl}\,\chi_{h},\,\chi_{h}\!\in\! \varPhi_{h}.\]

Obviously \(FG_{h}(u_{h})\) is a linear operator from \(V_{h}\) into \(Y_{h}\) and Lemma 5.2 implies that

\[\|FG_{h}(u_{h})\!\cdot\!v_{h}\|_{\star}\leqslant C|u_{h}|\,|v_{h}|\ \ \ \ \ \forall u_{h},v_{h}\!\in\!V_{h},\]

with a constant \(C\) independent of \(h\).

_Remark 5.2_.: Note that \(FG_{h}(u_{h})\) is "nearly Lipschitz-continuous" with respect to \(u_{h}\). Indeed,

\[|\langle\!(VG_{h}(u_{h})-VG_{h}(u_{h}^{\star}))\!\cdot\!v_{h}, \mathbf{w}_{h}\rangle| =|\tilde{a}^{u_{h}}(u_{h};v_{h},\mathbf{w}_{h})-\tilde{a}^{u_{h} ^{\star}}(u_{h}^{\star};v_{h},\mathbf{w}_{h})\] \[\quad+\tilde{a}^{u_{h}}(v_{h};u_{h},\mathbf{w}_{h})-\tilde{a}^{u_ {h}^{\star}}(v_{h};u_{h}^{\star},\mathbf{w}_{h})|\] \[\leqslant|\tilde{a}^{u_{h}}(u_{h}-u_{h}^{\star};v_{h},\mathbf{w}_ {h})|+|\tilde{a}^{u_{h}}(u_{h}^{\star};v_{h},\mathbf{w}_{h})\] \[\quad-\tilde{a}^{u_{h}^{\star}}(u_{h}^{\star};v_{h},\mathbf{w}_{h })|+|\tilde{a}^{u_{h}}(v_{h};u_{h}-u_{h}^{\star},\mathbf{w}_{h})|\] \[\quad+|\tilde{a}^{u_{h}}(v_{h};u_{h}^{\star},\mathbf{w}_{h})- \tilde{a}^{u_{h}^{\star}}(v_{h};u_{h}^{\star},\mathbf{w}_{h})|\] \[\leqslant C_{1}|v_{h}|\,|w_{h}|\,[|u_{h}-u_{h}^{\star}|\] \[\quad+h^{1/2}(\,\|\mathbf{u}_{h}-\mathbf{u}_{h}^{\star}\|_{0,\,4, \,\Omega}+|u_{h}^{\star}|)],\]

by applying Lemmas 5.3 and 5.4. Hence

\[\|FG_{h}(u_{h})-VG_{h}(u_{h}^{\star})\|_{\mathcal{L}(V_{h};V_{h})}\leqslant C_ {2}(|u_{h}-u_{h}^{\star}|+h^{1/2}|u_{h}^{\star}|).\]

Of course, we can derive a similar upper bound with the term \(h^{1/2}|u_{h}|\) in the right-hand side.

Finally in order to apply Theorem 3.8, it is necessary to relate the operator \(G\) defined by (5.6) with the operator that corresponds to the trilinear form
