\[\begin{split}\|\,p-p_{h}\|_{0,\Omega}\leq& C\left\{h^{2/\gamma}\inf_{q_{h}\in Q_{h}}|p-q_{h}|_{1,t,\Omega}+v\|_{0}-o_{h}\|_{0, \Omega}\right.\\ &+\left.v\inf_{\theta_{h}\in\,\Theta_{h}}(\|\omega-\theta_{h}\|_{ 0,\Omega}+h^{2/\gamma}|_{0}-\theta_{h}|_{1,t,\Omega})\right.\\ &+\left.h^{1/2}[\psi-\psi_{h}]_{4}(|\psi_{h}|_{1,\,4,\Omega}+| \psi|_{2,\Omega})\right\}\end{split}\] (5.53)

_where \(1/\gamma+1/t=1,\)\(u_{h}=(\mathbf{u}_{h}=\mathbf{curl}\,\psi_{h},o_{h})\) and \(u=(\mathbf{u}=\mathbf{curl}\,\psi,o)\) denote the solutions of (5.18) and (5.7) respectively._

It follows readily from (5.53) and (5.48) that the pressure \(p_{h}\) has the same order of convergence as the velocity:

**Theorem 5.3**.: _Under the assumptions of Theorem 5.1 the pressure \(p_{h}\) defined by Problem (5.51) converges to \(p\) with the same order of accuracy as the velocity. Namely, if \(\mathbf{f}\!\in\!L^{l}(\Omega)^{2}\) for \(t\!\in\![r,2)\) we have:_

\[\sup_{\lambda\in\,A}\|\,p(\lambda)-p_{h}(\lambda)\|_{0,\Omega}\leq C_{1}\,h^{ \alpha}\quad\quad\alpha=\begin{cases}1/\gamma&\text{if }l=1,\\ 2/\gamma&\text{if }l=2,\end{cases}\]

_where \(1/\gamma+1/t=1.\) When \(\psi\) belongs to \(W^{2,\,\infty}(\Omega)\) or when \(l\geq 2,\) this bound can be extended to \(t=2.\) When \(l=1\) and \(t=2\) we have:_

\[\sup_{\lambda\in\,A}\|\,p(\lambda)-p_{h}(\lambda)\|_{0,\Omega}\leq C_{2}( \varepsilon)h^{1-\varepsilon}.\]

_Finally when the mapping \(\lambda\to(\psi(\lambda),p(\lambda))\) is continuous from \(\Lambda\) into \([H^{m+2}(\Omega)\cap W^{m+3/2,\,\infty}(\Omega)]\times H^{m}(\Omega)\) for some real \(m\!\in\![1,l-1/2]\) we have_

\[\sup_{\lambda\in\,A}\|\,p(\lambda)-p_{h}(\lambda)\|_{0,\Omega}\leq C_{3}\,h^{m}.\]

## 6 Numerical Algorithms

Navier-Stokes equations are difficult to solve in practice because they are nonlinear. We present here a few simple converging algorithms that permit to handle the nonlinearity. Although they are intended to solve the discrete systems of (nonlinear) equations, it is simpler to introduce these algorithms in connection with the continuous problem. The reader will verify easily that the convergence theorems below are also valid for the approximate problems.

### General Methods of Descent and Application to Gradient Methods

Like every nonlinear problem, the Navier-Stokes equations can be put into the framework of an optimization problem. Therefore we shall consider first the
