(3.27) \[\lim_{h\to 0}\biggl{(}\sup_{\lambda\in\Lambda}e_{h}(\lambda)\biggr{)}=0.\]

_If, in addition,_

(3.56) \[\sup_{\lambda\in\Lambda}L_{h}(\lambda;\mu)=L_{h}(\mu)\ \ \ \ \ \forall h\leqslant h_{0},\]

_where the function \(L_{h}(\mu)\) is monotonically increasing with respect to \(\mu\) and \(h\)_, _continuous at \(\mu=0\)_, _and such that:_

(3.57) \[\lim_{h\to 0}L_{h}(0)=0\]

_then there exists two real constants \(\alpha>0\) and \(h_{1}>0\) and a function \(u_{h}\in\mathcal{C}^{0}(\Lambda;X_{h})\) such that for all \(h\leqslant h_{1}\)_:

\[\{(\lambda,u_{h}(\lambda));\,\lambda\in\Lambda\}\quad\text{is a branch of solutions of \eqref{eq:12}},\]

_for each \(\lambda\in\Lambda\), \(u_{h}(\lambda)\) is the only solution of (3.12) in \(S(\tilde{u}_{h}(\lambda);\alpha)\cap X_{h}\) and we have the estimate:_

(3.30') \[\|u_{h}(\lambda)-v_{h}\|_{X}\leqslant 2\gamma\|F_{h}(\lambda,v_{h})\|_{ \mathcal{X}}\ \ \ \ \ \forall v_{h}\in S(\tilde{u}_{h}(\lambda);\alpha)\cap X_{h}.\]

_Remark 3.8_.: The assumption that \(L_{h}(\mu)\) be monotonically increasing with respect to \(h\) is not necessary. It can be replaced by the condition that \(L_{h}(\mu)\) be uniformly continuous with respect to \(h\) at \(\mu=0\).

For the sake of simplicity, we are going to apply Theorem 3.7 to solve a narrower range of problems than (3.33), but the reader will easily extend the forthcoming analysis to the general case. More precisely, with the notations of Section 3.3 we propose to solve the problem:

(3.33') \[F(\lambda,u)\equiv u+\lambda TG(u)=0\]

where \(G\) is a \(\mathcal{C}^{1}\)-mapping from \(X\) into \(Y\), \(\lambda\in\Lambda\), a compact interval of \(\mathbb{R}\), and \(T\) is unchanged but we assume that \(T\in\mathcal{C}(Y;V)\) where \(V\) is a closed subspace of \(X\). This may amount to a regularity assumption on \(T\). Furthermore, we suppose that the problem

\[F(\lambda,u(\lambda))=0\]

has a branch of nonsingular solutions \(\lambda\to u(\lambda)\) from \(\Lambda\) into \(X\) with \(u\in\mathcal{C}^{0}(\Lambda;V)\).

In view of the approximation, we introduce a closed subspace \(V_{h}\) of \(X\), equipped with the norm of \(X\) and a space \(Y_{h}\) that _contains_\(Y\) with continuous imbedding. To avoid confusion, we denote the norm of \(Y_{h}\) by \(\|.\|_{h}\). The mapping \(G\) is approximated by a \(\mathcal{C}^{0}\)-mapping \(G_{h}\) from \(V_{h}\) into \(Y_{h}\) and \(T\) is approximated by an operator \(T_{h}\in\mathcal{L}(Y_{h};V_{h})\). Then we set

(3.58) \[F_{h}(\lambda,u_{h})=u_{h}+\lambda T_{h}G_{h}(u_{h})\]
