### A First Order Method: the "Mini" Finite Element

With minor modifications, the setting of the problem is that of Section 1.3. We take for \(\Omega\) a bounded, plane polygon and we assume that the Stokes system

(4.1) \[\begin{cases}\begin{aligned} \text{\rm$-$\,$\nu$}d\,\mathbf{u}+ \mathbf{grad}\,p&=\mathbf{f}\\ \text{div}\,\mathbf{u}&=0\end{aligned}\end{cases}\quad\text{in }\Omega,\] \[\mathbf{u}=\mathbf{0}\quad\text{on }\Gamma\]

is such that:

\[p\text{ belongs to }H^{1}(\Omega).\]

Following Arnold _et al_[2], we construct a triangulation \(\mathcal{T}_{h}\) of \(\bar{\Omega}\) and we approximate the velocity on each element \(\kappa\) by a polynomial of

(4.2) \[\mathcal{P}_{1}(\kappa)=[P_{1}\oplus\operatorname{span}\{\dot{\lambda}_{1} \dot{\lambda}_{2}\dot{\lambda}_{3}\}]^{2}\]

and the pressure by a polynomial of \(P_{1}\). Thus we choose the following finite element spaces:

(4.3) \[X_{h} =\{\mathbf{v}\!\in\!\mathcal{C}^{0}(\bar{\Omega})^{2};\,\mathbf{v }|_{\kappa}\!\in\!\mathcal{P}_{1}(\kappa)\quad\forall\kappa\!\in\!\mathcal{T} _{h},\,\mathbf{v}|_{\Gamma}=\mathbf{0}\},\] (4.4) \[Q_{h} =\{q\!\in\!\mathcal{C}^{0}(\bar{\Omega});\,q|_{\kappa}\!\in\!P_{ 1}\quad\forall\kappa\!\in\!\mathcal{T}_{h}\},\,M_{h}=Q_{h}\cap L_{0}^{2}( \Omega).\]

The degrees of freedom are the simplest ones, namely the values of the _velocity_ at the _vertices_ and _center_ of \(\kappa\) and the values of the _pressure_ at the _vertices_ of \(\kappa\). As usual, the space \(V_{h}\) is defined by:

\[V_{h}=\{\mathbf{v}_{h}\!\in\!X_{h};\,(\text{div}\,\mathbf{v}_{h},q_{h})=0 \quad\forall q_{h}\!\in\!Q_{h}\}\]

and the approximate problem, called _Problem_ (Q\({}_{h}\)) reads:

_Find a pair \((\mathbf{u}_{h},p_{h})\) in \(X_{h}\times\,M_{h}\) satisfying:_

(4.5) \[\begin{cases}a(\mathbf{u}_{h},\mathbf{v}_{h})-(p_{h},\text{div}\, \mathbf{v}_{h})&=\langle\mathbf{f},\mathbf{v}_{h}\rangle\quad\quad\forall \mathbf{v}_{h}\!\in\!X_{h},\\ (\text{div}\,\mathbf{u}_{h},q_{h})&=0\quad\quad\forall q_{h}\!\in\!Q_{h},\end{cases}\]

where the bilinear form \(a(.\,,\,.)\) is unchanged:

\[a(\mathbf{u},\mathbf{v})=2v\sum_{i,j}^{2}(D_{ij}(\mathbf{u}),D_{ij}(\mathbf{v }))\]

or

\[a(\mathbf{u},\mathbf{v})=v(\mathbf{grad}\,\mathbf{u},\mathbf{grad}\,\mathbf{v}).\]

Note that because the space \(Q_{h}\) is contained in \(H^{1}(\Omega)\), the bilinear form \(b(.\,,\,.)\) can be written equivalently as:

\[b(\mathbf{v}_{h},q_{h})=-(\text{div}\,\mathbf{v}_{h},q_{h})=(\mathbf{grad}\,q_ {h},\mathbf{v}_{h})\quad\quad\forall\mathbf{v}_{h}\!\in\!X_{h},\quad\quad \forall q_{h}\!\in\!Q_{h}.\]
