_Remark 2.7_.: Except for \(\{\mathfrak{f}_{F_{k}}\,\mathbf{p}\cdot\mathbf{n}_{i}\,ds\) all degrees of freedom enumerated by (2.39) are preserved by affine transformations. Note that the space \(\mathcal{P}_{2}(\kappa)\) itself is not invariant under affine transformations because of the normal vectors in the cubics \(\mathbf{p}_{i}\).

From the above considerations, we choose the following finite element spaces for velocity and pressure:

(2.40) \[\begin{cases}W_{h}=\{\mathbf{w}\!\in\!\mathcal{C}^{0}(\bar{\Omega})^{3};\, \mathbf{w}|_{\kappa}\!\in\!\mathcal{P}_{2}(\kappa)\quad\forall\kappa\!\in\! \mathcal{T}_{h}\},\\ \qquad\qquad X_{h}=\,W_{h}\cap H^{1}_{0}(\Omega)^{3},\end{cases}\] (2.41) \[\begin{cases}\quad Q_{h}=\{q\!\in\!L^{2}(\Omega);\,q|_{\kappa}\! \in\!P_{1}\quad\forall\kappa\!\in\!\mathcal{T}_{h}\},\\ \qquad\qquad M_{h}=Q_{h}\cap L^{2}_{0}(\Omega).\end{cases}\]

Lemma 2.9 provides an adequate interpolation operator \(r_{h}\) such that:

\[r_{h}\mathbf{v}|_{\kappa}=r_{\kappa}\mathbf{v}\quad\quad\forall\kappa\!\in \!\mathcal{T}_{h}\quad\quad\forall\mathbf{v}\!\in\!\mathcal{C}^{0}(\bar{ \Omega})^{3}\]

where \(r_{\kappa}\mathbf{v}\) is the unique polynomial of \(\mathcal{P}_{2}(\kappa)\) that has the same degrees of freedom (2.39) as \(\mathbf{v}\) on \(\kappa\). Clearly we have:

\[r_{h}\!\in\!\mathcal{L}(\mathcal{C}^{0}(\bar{\Omega})^{3};\,W_{h})\cap\mathcal{ L}([\mathcal{C}^{0}(\bar{\Omega})\cap H^{1}_{0}(\Omega)]^{3};\,X_{h})\]

and the following lemma checks Hypothesis H1.

**Lemma 2.10**.: _If \(\mathcal{T}_{h}\) is a regular triangulation of \(\bar{\Omega}\) then \(r_{h}\) satisfies the approximation property:_

(2.42) \[|\mathbf{v}-r_{h}\mathbf{v}|_{m,\Omega}\leqslant Ch^{k-m}|\mathbf{v}|_{k, \Omega}\quad\quad\forall\mathbf{v}\!\in\!H^{k}(\Omega)^{3},\]

\(m=0\)_, \(1\), \(k=2\) or \(3\), with a positive constant \(C\) independent of \(h\) and \(\mathbf{v}\)._

Proof.: If \(r_{\kappa}\) were preserved by affine transformation the proof would be trivial; nevertheless, the proof is quite short because only the moments on the faces are not invariant by affine transformation.

Let \(Iv\) denote the polynomial of \(P_{2}\oplus(\lambda_{1}\lambda_{2}\lambda_{3}\lambda_{4}P_{0})\) defined by:

\[Iv(a_{i})=v(a_{i})\quad\quad 1\leqslant i\leqslant 4,\]

\[Iv(a_{ij})=v(a_{ij})\quad\quad 1\leqslant i<j\leqslant 4,\quad\,Iv(a_{\kappa})=v( a_{\kappa}).\]

On the one hand this set of conditions determine \(Iv\) uniquely, and on the other hand the operator \(I\) is invariant under affine transformation. Moreover, as \(I\) preserves the polynomials of \(P_{2}\), the standard argument of Corollary A.2 shows that

(2.43) \[|v-Iv|_{m,\kappa}\leqslant C_{1}\|B_{\kappa}\|^{k}\|B_{\kappa}^{-1}\|^{m}|v|_{ k,\kappa}\quad\quad m=0\text{, }1,\quad\quad k=2\text{, }3.\]

Like in Remark 2.1 we find that \(r_{\kappa}\mathbf{v}\) can be expressed as:

\[r_{\kappa}\mathbf{v}=I\mathbf{v}+\sum\limits_{i=1}^{4}\alpha_{i}\mathbf{p}_{i} +\beta\lambda_{1}\lambda_{2}\lambda_{3}\lambda_{4}\]
