(4.48) \[\|\tilde{I}_{h}\psi-\psi_{h}\|_{2,\,h}\leqslant C_{2}\|\sigma_{h}-\sigma\|_{0,\, \Omega}.\]

Hence (4.44) follows from (4.48), (4.40) and Corollary 4.1.

To establish (4.41) and (4.42) we use a familiar duality argument. For \(\mathbf{g}\) in \(L^{2}(\Omega)^{2}\) we introduce the auxiliary Stokes Problem:

(4.49) \[\begin{cases}b_{h}(\mu_{g},\phi)=(\mathbf{g},\mathbf{curl}\,\phi)&\quad\forall \phi\in\bar{\mathcal{V}},\\ a_{h}(\mu_{g},\tau)+b_{h}(\tau,\lambda_{g})=0&\quad\forall\tau\in\Sigma.\end{cases}\]

Since \(\Omega\) is convex, the solution \((\mu_{g},\lambda_{g})\) belongs to \(H^{1}(\Omega)^{4}\times H^{3}(\Omega)\) with

(4.50) \[\|\mu_{g}\|_{1,\,\Omega}+\|\,\lambda_{g}\|_{3,\,\Omega}\leqslant C_{3}\,\| \,\mathbf{g}\|_{0,\,\Omega}.\]

Then a straightforward combination of (4.45), (4.49), (4.31) and Corollary 4.1 leads to:

\[(\mathbf{g},\mathbf{curl}(\psi-\psi_{h}))= b_{h}(\mu_{g}-\pi_{h}\mu_{g},\psi-\phi_{h})+a_{h}(\sigma-\sigma_{h}, \mu_{g}-\pi_{h}\mu_{g})\] \[+\,b_{h}(\sigma-\tau_{h},\lambda_{g}-\tilde{I}_{h}\lambda_{g}) \quad\forall\phi_{h}\in\varPhi_{h},\quad\quad\forall\tau_{h}\in\Sigma_{h}.\]

When \(l\geqslant 2\), Corollary 4.1, (4.33) and (4.50) yield:

(4.51) \[|\psi-\psi_{h}|_{1,\,\Omega}\leqslant C_{4}h\biggl{\{}\inf_{\phi_{h}\in \varPhi_{h}}\|\psi-\phi_{h}\|_{2,\,h}+\|\,\sigma-\sigma_{h}\|_{0,\,\Omega}+ \inf_{\tau_{h}\in\Sigma_{h}}\|\sigma-\tau_{h}\|_{0,\,h}\biggr{\}}.\]

When \(l=1\), we only have:

(4.52) \[|\psi-\psi_{h}|_{1,\,\Omega}\leqslant C_{5}h\biggl{\{}\inf_{\phi_{h}\in \varPhi_{h}}\|\psi-\phi_{h}\|_{2,\,h}+\|\,\sigma-\sigma_{h}\|_{0,\,\Omega} \biggr{\}}\]

In view of (4.40), Corollary 4.1 and (4.33), this implies (4.42) and (4.41). 

**Corollary 4.2**.: _We retain all the assumptions of Theorem 4.2. If \(\psi\) belongs to \(H^{k+2}(\Omega)\) for some real \(k\in\llbracket 1,l\rrbracket\) with \(l\geqslant 1\), we have:_

(4.53) \[|\psi-\psi_{h}|_{1,\,s,\,\Omega}\leqslant C(s)h^{k}|\psi|_{k+2,\,\Omega}\quad \text{for each $s\geqslant 2$}.\]

Proof.: Formula (4.47) and the inf-sup condition proved in Remark 4.2 give:

(4.54) \[|\tilde{I}_{h}\psi-\psi_{h}|_{1,\,s,\,\Omega}\leqslant C(s)\,\|\,\sigma- \sigma_{h}\|_{0,\,\Omega}.\]

Hence (4.53) follows from (4.40) and (A.23). 

_Remark 4.4_.: The above theorem calls for a number of comments. First of all, it is obvious that this approach yields very neatly optimal error estimates for polynomials of all degrees. In addition, the scheme considered is fairly inexpensive.

On the other hand, all results are stated for a right-hand side \(\mathbf{f}\) in \(L^{2}(\Omega)^{2}\) whereas one is often interested in solving the Stokes problem when the right-hand side is in \(L^{r}(\Omega)^{2}\) with \(r<2\). The next section extends the error analysis to this case.
