constant \(C>0\), independent of h, such that:_

(A.36) \[|v|_{m,r,\Omega}\leq Ch^{\operatorname{Min}(0,\,N/r-N/p)}|v|_{m,\,p,\Omega} \quad\quad\forall v\in\Theta_{h}.\]

Proof.: Clearly, (A.36) is obvious when \(r\leq p\). When \(r>p\), the proof is quite similar to that of (A.33) and is left to the reader. 

### Quadilateral Finite Elements

This section is devoted exclusively to plane polygonal domains. Unless otherwise specified, the notation is that of the preceding section. In addition, since several properties of triangular finite elements are still valid for quadrilateral finite elements, we shall focus our attention on those properties which are specific to quadrilaterals.

**Definition A.3**.: For each integer \(k\geq 0\), we denote by \(Q_{k}\) the space of all polynomials in the reference space \((\hat{x}_{1},\hat{x}_{2})\) of the form:

\[q(\hat{x})=\sum c_{ij}\hat{x}_{1}^{i}\hat{x}_{2}^{j},\]

where the sum ranges over all integers \(i\) and \(j\) such that \(0\leq i,j\leq k\).



Of course \(Q_{0}\) coincides with \(P_{0}\) but for all \(k\geq 1\) we have the strict inclusion

\[P_{k}\subset Q_{k}.\]

Let \(\hat{x}\) denote the reference unit square \([0,1]\times[0,1]\) in the \((\hat{x}_{1},\hat{x}_{2})\) reference space, with vertices denoted by \(\hat{a}_{j}\), \(1\leq j\leq 4\), like in Figure 5. With the notations of this figure, for each convex quadrilateral \(\kappa\) with vertices \(a_{j}\), there exists exactly one invertible mapping \(F_{\kappa}\in Q_{1}^{2}\) that maps \(\hat{x}\) onto \(\kappa\) and is such that

\[F_{\kappa}(\hat{a}_{j})=a_{j},\quad\ \ 1\leq j\leq 4.\]

Figure 5: Quadrilateral \(K\) and its reference unit square \(\hat{K}\)
