Therefore the convergence (4.60) implies that

\[\lim_{m^{+}\infty}\lambda^{m}=\lambda\quad\text{in }M\]

which in turn implies the convergence of \(u^{m}\) by taking limits in (4.56). 

_Remark 4.6_.: The convergence criterion (4.58) implies that the direction of descent \(\omega^{m}\) is never asymptotically orthogonal to the gradient \(g^{m}\).

As a first application, the _simple gradient algorithm with optimal parameter_ is obtained by a descent along the gradient:

(4.61) \[\omega^{m}=g^{m}.\]

Thus the general step of this algorithm is:

For \(m\geq 0\), knowing \((u^{m},\lambda^{m})\in X\times M\) determine \((z^{m},g^{m})\in X\times M,\ \rho^{m}\in\mathbb{R}\) and the pair \((u^{m+1},\lambda^{m+1})\in X\times M\) by:

(4.62) \[\left\{\begin{aligned} Cg^{m}&=\chi-Bu^{m},\\ A_{r}z^{m}&=B^{r}g^{m},\\ \rho^{m}&=c(g^{m},g^{m})/b(z^{m},g^{m}),\\ \lambda^{m+1}&=\lambda^{m}-\rho^{m}g^{m},\\ u^{m+1}&=u^{m}+\rho^{m}z^{m}.\end{aligned}\right.\]

Here the criterion (4.58) is obviously satisfied with \(\alpha=1\); thus we have:

**Corollary 4.4**.: _Let \(b(.,.)\), \(a_{r}(.,.)\) and \(c(.,.)\) satisfy the assumptions of Theorem 4.6. Then the simple gradient algorithm with optimal parameter (4.62) is convergent._

At this stage, it is interesting to point out that the simple gradient algorithm is still convergent provided the parameters \(\rho^{m}\) lie in an appropriate interval, even though these parameters are _not optimal_. Let us stress the fact that the convergence of the resulting scheme _does not require the symmetry of \(a(.,.)\)_. The method of proof is altogether different from that of Theorem 4.6.

**Theorem 4.7**.: _We retain the hypotheses of Corollary 4.4 but we do not necessarily assume that the form \(a(.,.)\) is symmetric. Then the algorithm:_

(4.54) \[\lambda^{m+1}=\lambda^{m}-\rho^{m}g^{m}\] (4.56) \[a_{r}(u^{m},v)=\langle l,v\rangle+rb(v,C^{-1}\chi)-b(v,\lambda^ {m})\quad\quad\forall v\in X\]

_is convergent for every initial value \(\lambda^{0}\in M\) and every choice of \(\rho^{m}\) satisfying:_

(4.63) \[0<\inf_{m}\rho^{m}\leq\sup_{m}\rho^{m}<2\gamma\tilde{x}_{r}\]
