Likewise, (A.17) and Jensen's inequality (A.34) yield:

\[|\phi-I_{h}\phi|_{1,\,s,\,\Omega}\leq C_{5}h^{2s}|\mathbf{v}|_{1,\,\Omega}.\]

Hence Hypothesis H2 holds for all \(s\geq 2\). 

From Theorems 2.6, 2.7 and these two lemmas we immediately derive the main result of this section.

**Theorem 2.8**.: _Let \(\Omega\) be an open, bounded convex polygon and let \(\mathcal{T}_{h}\) be a uniformly regular family of triangulations of \(\bar{\Omega}\). Let \((u=(\mathbf{curl}\,\psi,\omega=\,-\Delta\psi),p)\) be the solution of (2.20) and (2.21) and assume that_

(2.44) \[\psi\in W^{k+1,\,s}(\Omega),\quad\Delta\psi\in H^{k}(\Omega),\quad p\in H^{m}( \Omega)\cap L^{2}_{0}(\Omega),\quad m=\max(1,k-1)\]

_for some integer \(k\) such that \(1\leq k\leq l.\) Then we have the error bounds:_

(2.45) \[\|u-u_{h}\|_{\widetilde{X}} \leq C_{1}\big{[}h^{k-1}(|\psi|_{k+1,\,s,\,\Omega}+|\Delta\psi|_{ k,\,\Omega})+h^{k}\|\,\Delta\psi\|_{k,\,\Omega}\big{]},\] (2.46) \[\|p-p_{h}\|_{0,\,\Omega} \leq C_{2}\big{[}h^{k-1}(|p|_{m,\,\Omega}+|\psi|_{k+1,\,s,\,\Omega }+|\Delta\psi|_{k,\,\Omega})+h^{k}\|\,\Delta\psi\|_{k,\,\Omega}\big{]},\]

_with constants \(C_{1}>0\) and \(C_{2}>0\) independent of \(h,\psi\) and \(p\)._

_Remark 2.7_.: Theorem 2.8 uses the convexity of \(\Omega\) in three instances: to verify Hypotheses H1 and H2 and to evaluate \(\|\omega-P_{h}\omega\|_{0,\,\Omega}\). In many cases, Hypothesis H1 does not demand that \(\Omega\) be convex (cf. Remark 2.6). But the \(L^{2}\)-estimate for \(P_{h}\omega\), which stems from a duality argument, and Hypothesis H2 both require the convexity of \(\Omega\) (because \(\Gamma\) has corners). As far as (2.45) is concerned, we can always replace \(\|\omega-P_{h}\omega\|_{0,\,\Omega}\) by \(\inf_{\theta_{h}\in\,\theta_{h}}\|\omega-\theta_{h}\|_{1,\,r,\,\Omega}\) (cf. (1.27)) and, if \(\omega\) is sufficiently smooth, derive an estimate of the same order for \(\|u-u_{h}\|_{\widetilde{X}}\) without \(\Omega\) being convex.

But unfortunately, our proof of (2.46) does require the convexity of \(\Omega\) and we see no possibility of discarding this assumption.

Because of the factor \(K(h)\) the estimates of Theorem 2.8 are not optimal; in particular (2.45) and (2.46) do not imply convergence when \(l=1\) (i.e. when piecewise linear elements are used). As mentioned previously, Section 3.1 will take care of this difficulty.

### The Technique of Mesh-Dependent Norms

In this section we propose to improve to some extent the estimate (2.45) by the use of mesh-dependent norms, introduced by Babuska, Osborn & Pitkaranta [5], which are better adapted here than \(\|\,.\,\|_{\widetilde{X}}\). The underlying idea for introducing these norms is an integration by parts on each element \(\kappa\) of \(\mathcal{T}_{h}\). To be specific, let \(\phi\in H^{2}(\kappa)\) and \(\theta\in H^{1}(\kappa)\); Green's formula gives:
