Here \(q\) is the only solution (up to an additive constant) of the Neumann's problem:

\[\left\{\begin{aligned} \mathcal{A}q&=0\quad\text{in } \Omega,\\ \partial q/\partial n&=\mathbf{g}\cdot\mathbf{n} \quad\text{on }\Gamma.\end{aligned}\right.\]

And \(\phi\) is the unique solution of the biharmonic equation:

\[\mathcal{A}^{2}\phi=0\quad\text{in }\Omega,\]

\[\phi=0\quad\text{on }\Gamma,\quad\partial\phi/\partial n=\partial q/\partial \tau-\mathbf{g}\cdot\tau\quad\text{on }\Gamma.\]

The reader can easily check that \(\mathbf{u}\) satisfies the statement of the lemma. 

Now, we turn to the space \(V.\) According to Theorem 3.1, each function \(\mathbf{v}\in V\) has a stream function \(\phi\in H^{1}(\Omega),\) i.e.

\[\mathbf{v}=\mathbf{curl}\,\phi.\]

Again, \(\phi\) is uniquely determined if we fix \(\phi=0\) on \(\Gamma_{0}.\) In this case, it can be readily verified that \(\phi\) belongs to the space

\[\Psi=\{\chi\in H^{2}(\Omega);\,\chi|_{\Gamma_{0}}=0,\,\chi|_{\Gamma_{i}}\text{ is constant for }1\leq i\leq p,\,\partial\chi/\partial n=0\text{ on }\Gamma\}.\] (3.11)

Note that the seminorm \(\left\|\mathcal{A}\phi\right\|_{0,\,\Omega}\) is a norm on \(\Psi\) equivalent to \(\left\|\phi\right\|_{2,\,\Omega}.\) Indeed, since \(\mathbf{grad}\,\phi\in H^{1}_{0}(\Omega)^{2}\) when \(\phi\in\Psi,\) it can be easily shown like in Section 1.5 and by virtue of Lemma 3.1 that

(3.12) \[\left\|\mathcal{A}\phi\right\|_{0,\,\Omega}=\left|\phi\right|_{2,\,\Omega} \geq C_{1}|\phi|_{1,\,\Omega}\geq C_{2}\left\|\phi\right\|_{0,\,\Omega}.\]

With this space, we can formulate for \(V\) the analogues of Corollary 3.1 and Theorem 3.2.

**Corollary 3.2**.: _The space \(V\) verifies the identity:_

\[V=\{\mathbf{curl}\,\phi;\,\phi\in\Psi\}\]

_and the mapping \(\mathbf{curl}\) is an isomorphism from \(\Psi\) onto \(V.\) Moreover, the stream function \(\phi\) of \(\mathbf{v}\) can be characterized as the only solution of:_

(3.13) \[\phi\in\Psi,\quad(\mathcal{A}\phi,\mathcal{A}\chi)=-(\operatorname{curl}\, \mathbf{v},\mathcal{A}\chi)\quad\forall\chi\in\Psi.\]

_Remark 3.3_.: Problem (3.13) has the following interpretation:

(3.14) \[\left\{\begin{aligned} &\mathcal{A}^{2}\phi=-\mathcal{A}( \operatorname{curl}\,\mathbf{v})\quad\text{in }H^{-2}(\Omega),\\ &\phi|_{\Gamma_{0}}=0,\quad\,\phi|_{\Gamma_{i}}=\text{a constant }c_{i}\quad\text{for }1\leq i\leq p,\\ &\partial\phi/\partial n=0\quad\text{on }\Gamma,\\ &\int_{\Gamma_{i}}\partial(\mathcal{A}\phi+\operatorname{curl} \,\mathbf{v})/\partial n\,ds=0\quad\text{for }1\leq i\leq p.\end{aligned}\right.\]
