\[\sum\limits_{j=1}^{2}u_{j}\partial\mathbf{u}/\partial x_{j},\]

which is considered part of the right-hand side, belongs only to \(L^{2-\varepsilon}(\Omega)^{2}\) for any \(\varepsilon>0\) whenever \(\mathbf{u}\) belongs to \(H^{1}(\Omega)^{2}\) (cf. Corollary I.1.1 with \(N=2\)). This remark suggests to \(fix\) a real \(r\) in the interval \((1,2)\) and take \(W_{0}^{1,\,s}(\Omega)\) for space of potentials with \(1/s+1/r=1\). Then consider the problem:

\[For\,\mathbf{f}\!\in\!L^{r}(\Omega)^{2}\,\,\,find\,\,a\,\,triple\,(\mathbf{u}, p,\mu)\!\in\!H_{0}^{1}(\Omega)^{2}\,\times\,W^{1,\,r}(\Omega)\,\times\,W_{0}^{1,\,s}( \Omega)\,\,such\,\,that\] (4.16) \[\left\{\begin{aligned} v(\mathbf{grad}\,\mathbf{u}, \mathbf{grad}\,\mathbf{v})+\left(\sum\limits_{j=1}^{2}u_{j}\partial\mathbf{u}/ \partial x_{j},\mathbf{v}-\mathbf{grad}\,q\right)+(\mathbf{grad}\,p,\mathbf{v} -\mathbf{grad}\,q)\\ =(\mathbf{f},\mathbf{v}-\mathbf{grad}\,q)\,\,\,\,\,\,\,\,\,\,\, \forall(\mathbf{v},q)\!\in\!H_{0}^{1}(\Omega)^{2}\,\times\,W_{0}^{1,\,s}( \Omega)\\ (\mathbf{u}-\mathbf{grad}\,\mu,\mathbf{grad}\,q)=0\,\,\,\,\,\,\, \,\,\,\,\forall q\!\in\!W^{1,\,r}(\Omega).\end{aligned}\right.\]

It is a matter of routine to check that this problem is equivalent to the Navier-Stokes problem (4.1) in the following sense:

if \((\mathbf{u},p)\) is a solution of (4.1) _with \(p\) in \(W^{1,\,r}(\Omega)\)_ then the triple \((\mathbf{u},p,\mu=0)\) is a solution of (4.16). Conversely, each solution of (4.16) is of the form \((\mathbf{u},p,\mu=0)\) where the pair \((\mathbf{u},p)\) satisfies (4.1).

Obviously, the same conclusion applies to the Stokes problem with right-hand side \(\mathbf{f}\) in \(L^{r}(\Omega)^{2}\):

if the pressure solution \(p\) of the Stokes problem belongs to \(W^{1,\,r}(\Omega)\) then this problem is equivalent to:

\[Find\,\,(\mathbf{u},p,\mu)\!\in\!H_{0}^{1}(\Omega)^{2}\,\times\,W^{1,\,r}( \Omega)\,\times\,W_{0}^{1,\,s}(\Omega)\,\,such\,\,that\] (4.17) \[\left\{\begin{aligned} (\mathbf{grad}\,\mathbf{u}, \mathbf{grad}\,\mathbf{v})+(\mathbf{grad}\,p,\mathbf{v}-\mathbf{grad}\,q)& =(\mathbf{f},\mathbf{v}-\mathbf{grad}\,q)\\ \forall(\mathbf{v},q)\!\in\!H_{0}^{1}(\Omega)^{2}\,\times\,W_{0} ^{1,\,s}(\Omega),\\ (\mathbf{u}-\mathbf{grad}\,q)=0\,\,\,\,\,\,\,\,\,\,\,\forall q \!\in\!W^{1,\,r}(\Omega).\end{aligned}\right.\]

Therefore, in order to express the Stokes operator by (4.17) for every right-hand side in \(L^{r}(\Omega)^{2}\) we must assume that the Stokes problem is regular in a more general sense than (4.11):

(4.18) \[\left\{\begin{aligned} &\text{the mapping}\,(\phi,\mu)\to-\Delta\phi+\mathbf{grad}\,\mu \text{ is an isomorphism from}\,[W^{2,\,r}(\Omega)\cap V]^{2}\times[W^{1,\,r}(\Omega)/\mathbb{R}] \text{ onto }L^{r}(\Omega)^{2}\text{ for all }r\!\in\!(1,2].\end{aligned}\right.\]

_Remark 4.2_.: Here the pressure is taken in the quotient space \(W^{1,\,r}(\Omega)/\mathbb{R}\) instead of \(W^{1,\,r}(\Omega)\cap L_{0}^{2}(\Omega)\) because in the practical computation of (4.15), \(p_{n}\) is fixed by the condition \(\int_{T}p_{n}\,ds=0\) (cf. Lemma II.4.3).

Now, we can put Problem (4.16) into the setting of Section 3.3. We take:

\[Y=L^{r}(\Omega)^{2},\,\,\,\,\,\,\,\,\,X=H_{0}^{1}(\Omega)^{2}\,\times[L^{2}( \Omega)/\mathbb{R}]\times H_{0}^{1}(\Omega).\]
