Usually, \(J\) is called the energy functional associated with Problem (P) and \(\mathcal{L}\) the Lagrangean functional associated with Problem (Q).

Consider the following problem, called _Problem_ (L):

_Find a saddle-point \((u,\dot{\lambda})\!\in\!X\times M\) of the Lagrangean functional \(\mathcal{L}\) over \(X\times M\)_, _i.e. find a pair \((u,\dot{\lambda})\!\in\!X\times M\) such that_

(4.15) \[\mathcal{L}(u,\mu)\leq\mathcal{L}(u,\dot{\lambda})\leq\mathcal{L}(v,\dot{ \lambda})\ \ \ \ \ \forall v\!\in\!X,\ \ \ \ \ \forall\mu\!\in\!M.\]

**Theorem 4.2**.: _Assume the conditions_ (i) _and_ (ii) _of Theorem 4.1. Assume in addition that the bilinear form \(a(\cdot,\,.)\) is symmetric and semi-positive definite on \(X\)_, _i.e._

(4.16) \[a(v,v)\geqslant 0\ \ \ \ \ \forall v\!\in\!X.\]

_Then Problem (L) has a unique solution \((u,\dot{\lambda})\!\in\!X\times M\) which is precisely the solution of Problem (Q)._

Proof.: The first inequality in (4.15) can be written as follows:

\[b(u,\mu-\dot{\lambda})\leqslant\langle\chi,\mu-\dot{\lambda}\rangle\ \ \ \ \ \forall\mu\!\in\!M.\]

As \(\mu\) is any element of \(M\), this amounts to

\[b(u,\mu)=\langle\chi,\mu\rangle\ \ \ \ \ \forall\mu\!\in\!M.\]

Next, the second inequality in (4.15) is equivalent to

\[\mathcal{L}(u,\dot{\lambda})=\inf_{v\in\,X}\mathcal{L}(v,\dot{\lambda}).\]

Since, by hypothesis, \(a(\cdot,\,.)\) is symmetric, we have

\[D_{v}\mathcal{L}(u,\dot{\lambda})\!\cdot\!v=a(u,v)+b(v,\dot{\lambda})-\langle l ,v\rangle.\]

Furthermore, using (4.16), we have

\[D_{vv}^{2}\mathcal{L}(u,\dot{\lambda})\!\cdot\!(v,v)=a(v,v)\geqslant 0\ \ \ \ \ \forall v\!\in\!X.\]

Therefore \(v\to\mathcal{L}(v,\dot{\lambda})\) is a convex functional and its minimum \(u\) is characterized by the condition \(D_{v}\mathcal{L}(u,\dot{\lambda})\cdot v=0\), i.e.

\[a(u,v)+b(v,\dot{\lambda})=\langle l,v\rangle\ \ \ \ \ \forall v\!\in\!X.\]

Thus, \((u,\dot{\lambda})\) is a saddle-point of \(\mathcal{L}\) iff it is also a solution of Problem (Q). Hence the theorem is established. 

**Corollary 4.2**.: _Under the hypotheses of Theorem 4.2, the solution \((u,\dot{\lambda})\) of Problem (Q) is characterized by:_

(4.17) \[\underset{v\in\,X}{\text{Min}}\biggl{(}\sup_{\mu\in\,M}\mathcal{L}(v,\mu) \biggr{)}=\mathcal{L}(u,\dot{\lambda})=\underset{\mu\in\,M}{\text{Max}} \biggl{(}\inf_{v\in\,X}\mathcal{L}(v,\mu)\biggr{)},\]

_where Min instead of inf (resp. Max instead of sup) means that the extremum is taken._
