It stems from the above considerations that

\[\operatorname{Ker}(B^{\prime}_{n})=\operatorname{span}(\mu).\] (3.23)

Because of its alternate "plus and minus" pattern, the function \(\mu\) is called a checkerboard function. Its connection with \(\operatorname{Ker}(B^{\prime}_{n})\) was first reported by Fortin [28] and then by Sani et al. [70].

In view of (3.23), the pair of spaces \((X_{h},M_{h})\) has no chance of satisfying the inf-sup condition. To save the situation, the first step we can take is to replace \(M_{h}\) by \([\operatorname{Ker}(B^{\prime}_{h})]^{\perp}\). Let us characterize this space. Let \(I=2i+1\) and \(J=2j+1\) for \(-n\leqslant i,j\leqslant n-1\) and let the macro-element \(\Omega_{I,J}\) be the union of the four squares \(\kappa\) with common vertex \((I,J)\). Following Johnson & Pitkaranta [46], for each \((I,J)\) we introduce the four functions \((v_{k})_{I,\,J}\)\(1\leqslant k\leqslant 4\) which take the value \(\pm 1\) on the subsquares of \(\Omega_{I,\,J}\) according to the pattern of Figure 15.

Note that

\[\int_{\Omega_{I,J}}(v_{k})_{I,\,J}\,dx=0\quad\text{when $k\neq 1$}\] (3.24)

Figure 14:
