Now we turn to the dual problem of (4.43):

\[\mathop{\rm Max}\limits_{\mu\,\in\,M}\inf_{v\,\in\,X}\mathscr{L}_{r}(v,\mu).\]

Assuming that the bilinear form \(a_{r}(.,.)\) defined by:

\[a_{r}(u,v)=a(u,v)+r\langle C^{-1}Bu,Bv\rangle\]

is \(X\)-elliptic, i.e. assuming there exists \(\alpha_{r}>0\) such that

(4.46) \[a_{r}(v,v)\geqslant\alpha_{r}\|v\|_{X}^{2}\ \ \ \ \ \ \forall v\,\in X,\]

then it is clear that the optimization problem:

\[\mathscr{L}_{r}(u_{r}(\mu),\mu)=\inf_{v\,\in\,X}\mathscr{L}_{r}(v,\mu)\]

has a unique solution \(u_{r}(\mu)\,\in\,X\). Indeed, according to the above proof, this problem amounts to solve:

(4.47) \[a_{r}(u_{r}(\mu),v)=\langle l,v\rangle+rb(v,C^{-1}\chi)-b(v,\mu)\ \ \ \ \ \forall v\,\in X.\]

Here again, we have \(u_{r}(\lambda)=u\); hence

(4.48) \[\mathscr{L}_{r}(u_{r}(\lambda),\lambda)=\mathop{\rm Max}\limits_{\mu\,\in\,M} \mathscr{L}_{r}(u_{r}(\mu),\mu).\]

Like in Section 4.2 we easily derive the expression:

\[\mathscr{L}_{r}(u_{r}(\mu),\mu)=-(1/2)a_{r}(u_{r}(\mu),u_{r}(\mu))-\langle\chi ,\mu\rangle+(r/2)\langle C^{-1}\chi,\chi\rangle.\]

Thus, setting

(4.49) \[K_{r}(\mu)=(1/2)a_{r}(u_{r}(\mu),u_{r}(\mu))+\langle\chi,\mu\rangle,\]

we obtain

\[\mathscr{L}_{r}(u_{r}(\mu),\mu)=-K_{r}(\mu)+(r/2)\langle C^{-1}\chi,\chi\rangle.\]

From this equality and (4.48), it follows that \(\lambda\) satisfies:

(4.50) \[K_{r}(\lambda)=\mathop{\rm Min}\limits_{\mu\,\in\,M}K_{r}(\mu).\]

The following corollary summarizes this result.

**Corollary 4.3**.: _Under the hypotheses of Theorem 4.5 and the ellipticity condition (4.46), \(\lambda\,\in\,M\) is characterized as the unique solution of the unconstrained optimization problem (4.50)._

_Remark 4.5_.: The mapping \(\mu\to u_{r}(\mu)\) defined by (4.47) is affine from \(M\) into \(X\).

In order to adapt methods of descent to solve (4.50), we must compute the first two derivatives of the quadratic functional \(K_{r}\) with respect to \(\mu\). First of all, we observe from (4.47) that the derivative of \(u_{r}\):
