_Assume in addition that \(\Omega\) is convex and that the solution \(\mathbf{u}=\mathbf{curl}\,\psi\) of the Stokes problem (5.1) satisfies_:__

\[\psi\in H^{l+1}(\Omega)^{3},\quad\quad\omega=-\,\Delta\psi\in H^{l+1}(\Omega)^{3}\]

_for some integer \(l\geqslant 1\). Then, if \(\mathscr{T}_{h}\) is a uniformly regular family of triangulations of \(\bar{\Omega}\), \(u_{h}\) satisfies the error estimates_:__

(5.48) \[\begin{cases}\|\omega-\omega_{h}\|_{\,0,\Omega}\leq C_{1}(h^{l-1}|\psi|_{l+1, \Omega}+h^{l}\|\omega\|_{l+1,\Omega}),\\ \|\mathbf{curl}(\psi-\psi_{h})\|_{\,0,\Omega}\leq C_{2}\{(h^{l-1}+h^{l})|\psi|_ {l+1,\Omega}+h^{l}\|\omega\|_{l+1,\Omega}\},\end{cases}\]

_with positive constants \(C_{1}\) and \(C_{2}\) independent of \(h,\omega\) and \(\psi\)._

_Remark 5.8_.: Like in the two-dimensional case, we observe a loss of one power of \(h\) arising from the term (cf. Lemma 5.2):__

(5.49) \[\inf_{\phi_{h}\in\phi_{h0}}\sup_{\mathbf{h}_{h}\in M_{h}}\frac{|(\mathbf{curl }(\psi-\phi_{h}),\mathbf{curl}\,\mathbf{\mu}_{h})|}{\|\mathbf{\mu}_{h}\|_{\,0 ,\Omega}}.\]

If it were known that the projection \(\hat{P_{h}}\psi\) (for \(\psi\) in \(\mathcal{P}_{0}\)):__

\[\hat{P_{h}}\psi\in\mathcal{P}_{h0}\quad\quad(\mathbf{curl}(\hat{P_{h}}\psi- \psi),\mathbf{curl}\,\phi_{h})=0\quad\quad\forall\phi_{h}\in\mathcal{P}_{h0}\]

satisfied the \(L^{p}\)-estimate:__

(5.50) \[\|\hat{P_{h}}\psi-\psi\|_{\,0,\,p,\Omega}+h\|\mathbf{curl}(\hat{P_{h}}\psi- \psi)\|_{\,0,\,p,\Omega}\leq Ch^{s+1}\,\|\psi\|_{\,s+1,\,p,\Omega}\]

for all \(p\in[2,\,\infty]\) and \(s\in[1,l]\), then the argument of Section 3.1 could be applied to derive a sharper estimate than (5.48) and regain part of the missing power of \(h\). In particular this would enable us to obtain an acceptable rate of convergence when using first degree elements, which Theorem 5.5 fails to show.

Although (5.50) is still a conjecture, it does not sound unreasonable and it is hoped that this problem will be solved in a near future.

### Discontinuous Approximation of the Pressure

This section briefly describes and analyzes a finite element method that solves for the pressure term underlying Problems (5.15) and (5.16). Since the situation is fairly similar to that in Section 4.4 we shall state nearly all results without proof. The reader will easily fill in the blanks.

It is clear that here we must construct subspaces \(D_{h}\) of \(H(\operatorname{div};\Omega)\) such that, on the one hand, \(\mathbf{curl}\,\mathbf{\mu}_{h}\) belongs to \(D_{h}\) for \(\mathbf{\mu}_{h}\) in \(M_{h}\) and on the other hand, \(\operatorname{div}\mathbf{v}_{h}\) belongs to the discrete pressure space for \(\mathbf{v}_{h}\) in \(D_{h}\). The following definition generalizes the polynomial space \(D\) defined by (4.61a).

**Definition 5.3**.: \(1^{\circ}\)) For each integer \(l\geqslant 1\), let

\[D_{l}=P_{l-1}^{3}\oplus\{\,p(x)\mathbf{x};\,p\in\widetilde{P}_{l-1}\}.\]
