To stress the parallel with the continuous case, we set

\[a_{h}(g_{h},l_{h})=v(\mathbf{grad}\,\mathbf{u}_{h}(g_{h}),\mathbf{grad}\,\mathbf{ u}_{h}(l_{h}))\quad\quad\forall g_{h},\,l_{h}\in G_{h}.\]

Clearly, Problem (4.50) has a unique solution, and so does Problem (4.51) for a given \(g_{h}\). Moreover, it is easy to check that Problem (4.52) has also a unique solution \(\rho_{h}\). Indeed, if \(\mathbf{u}_{h}(\rho_{h})=\mathbf{0}\) then

\[(\mathbf{grad}\,p_{h}(\rho_{h}),\mathbf{v}_{h})=0\quad\quad\forall\mathbf{v}_{ h}\in X_{h}.\]

But the inf-sup condition established by Corollary 4.1 implies that

\[p_{h}(\rho_{h})=(1/\mathrm{meas}(\Omega))\int_{\Omega}p_{h}(\rho_{h})\,dx,\]

i.e. \(p_{h}\) is constant in \(\Omega\). As \(p_{h}(\rho_{h})\) also satisfies \(\int_{F}p_{h}(\rho_{h})\,ds=0\) we conclude that \(p_{h}(\rho_{h})=0\) and in particular, \(\rho_{h}=0\). Therefore we have the following result:

**Lemma 4.3**.: _Let the right-hand side \(\mathbf{f}\) belong to \(L^{2}(\Omega)^{2}\) where \(\Omega\) is a plane, bounded polygon and assume that the triangulation \(\mathcal{T}_{h}\) is like in (4.17). Then the Glowinski-Pironneau scheme (4.50) ...(4.53) determines a unique pair \((\mathbf{u}_{h},p_{h})\) with \(\mathbf{u}_{h}\) in \(X_{h}\) and \(p_{h}\) in \(Q_{h}\), \(\int_{F}p_{h}\,ds=0\)._

_Moreover, the pair \((\mathbf{u}_{h},p_{h})\) satisfies:_

(4.54) \[\begin{split} v(\mathbf{grad}\,\mathbf{u}_{h},\mathbf{grad}\, \mathbf{v}_{h})+(\mathbf{grad}\,p_{h},\mathbf{v}_{h}-\mathbf{grad}\,q_{h})\\ =(\mathbf{f},\mathbf{v}_{h}-\mathbf{grad}\,q_{h})\quad\quad \forall(\mathbf{v}_{h},q_{h})\in X_{h}\times\Phi_{h}.\end{split}\]

Note that (4.54) amounts to two independent equations: one for \(\mathbf{u}_{h}\) and one for \(p_{h}\). They are obtained by combining the last equations (resp. the first equations) of (4.50) and (4.51).

It is important to point out that, although the finite element spaces coincide with those of the Hood-Taylor method and (4.54) with \(q_{h}=0\) is satisfied in both cases, the above pair \((\mathbf{u}_{h},p_{h})\) is not, in general, the solution of the Hood-Taylor algorithm because it does not satisfy the discrete divergence-free constraint:

\[(\mathbf{u}_{h},\mathbf{grad}\,q_{h})=0\quad\quad\forall q_{h}\in Q_{h}.\]

Indeed, it follows from (4.51) that we have:

\[\begin{split}(\mathbf{grad}\,p_{h}(g_{h}),\mathbf{u}_{h})& =-v(\mathbf{grad}\,\mathbf{u}_{h}(g_{h}),\mathbf{grad}\,\mathbf{ u}_{h})\\ &=-v(\mathbf{grad}\,\mathbf{u}_{h}(g_{h}),\mathbf{grad}(\mathbf{ u}_{h}^{0}+\,\mathbf{u}_{h}(\rho_{h})))\\ &=-(\mathbf{u}_{h}^{0},\mathbf{grad}\,p_{h}(g_{h}))-v(\mathbf{ grad}\,\mathbf{u}_{h}(g_{h}),\mathbf{grad}\,\mathbf{u}_{h}^{0})\end{split}\]

by virtue of (4.52). Hence, another application of (4.51) shows that we have:

\[(\mathbf{grad}\,p_{h}(g_{h}),\mathbf{u}_{h})=0\quad\quad\forall g_{h}\in G_{h}.\]

Unlike the continuous case, this equality does not necessarily carry over to all \(q_{h}\) in \(Q_{h}\). In this sense, the _Glowinski-Pironneau algorithm relaxes the divergence-free constraint_. In fact, we must add something to \(\mathbf{u}_{h}\) in order to verify this
