Proof.: We apply the material of Paragraph 1 as follows. We set

\[X=H_{0}^{1}(\Omega)^{N}\quad\text{normed by }|.|_{1,\Omega},\quad\quad M=L_{0}^{2}( \Omega),\]

\[b(\mathbf{v},q)=-(q,\operatorname{div}\mathbf{v}),\quad\quad\langle l,\mathbf{v }\rangle=\langle\mathbf{f},\mathbf{v}\rangle.\]

Hence (2.8) is a particular case of Problem (Q). Thus, it remains to check the hypotheses of Theorems 1.2 and 1.4. First, using (2.5), we get for all \(\mathbf{v}\), \(\mathbf{w}\!\in\!V\)

\[a(\mathbf{w};\mathbf{v},\mathbf{v})=a_{0}(\mathbf{v},\mathbf{v})=v|\mathbf{v} |_{1,\Omega}^{2}.\]

Therefore, the form \(a(.;.,.)\) satisfies the property (1.13) (and thus (1.9)).

Next, let \(\mathbf{u}\) be a function of \(V\) and \((\mathbf{u}_{m})\) be a sequence in \(V\) such that

\[\mathbf{u}_{m}\to\mathbf{u}\quad\text{weakly in }V\text{ as }m\to\infty.\]

Then, the compactness of the imbedding of \(H_{0}^{1}(\Omega)\) into \(L^{2}(\Omega)\) (cf. Theorem I.1.3) implies that:

\[\mathbf{u}_{m}\to\mathbf{u}\quad\text{strongly in }L^{2}(\Omega)^{N}\text{ as }m\to\infty.\]

Now, let \(\mathbf{v}\) be in \(\mathcal{V}\) and let us take the limit of \(a(\mathbf{u}_{m};\mathbf{u}_{m},\mathbf{v})\). According to (2.4), we have

\[a_{1}(\mathbf{u}_{m};\mathbf{u}_{m},\mathbf{v}) =-a_{1}(\mathbf{u}_{m};\mathbf{v},\mathbf{u}_{m})\] \[=-\sum_{i,j=1}^{N}\int_{\Omega}u_{mi}u_{mj}(\partial v_{i}/ \partial x_{j})\,dx.\]

As \(\partial v_{i}/\partial x_{j}\!\in\!L^{\infty}(\Omega)\) and \(\lim_{m\to\infty}u_{mi}u_{mj}=u_{i}u_{j}\) in \(L^{1}(\Omega)\), it follows that

\[\lim_{m\to\infty}a_{1}(\mathbf{u}_{m};\mathbf{u}_{m},\mathbf{v}) =-\sum_{i,j=1}^{N}\int_{\Omega}u_{i}u_{j}(\partial v_{i}/\partial x _{j})\,dx\] \[=-a_{1}(\mathbf{u};\mathbf{v},\mathbf{u})=a_{1}(\mathbf{u}; \mathbf{u},\mathbf{v}).\]

Since it is clear that

\[\lim_{m\ \times\infty}a_{0}(\mathbf{u}_{m},\mathbf{v})=a_{0}(\mathbf{u}, \mathbf{v}),\]

we get

\[\lim_{m\to\infty}a(\mathbf{u}_{m};\mathbf{u}_{m},\mathbf{v})=a(\mathbf{u}; \mathbf{u},\mathbf{v})\]

for all \(\mathbf{v}\!\in\!\mathcal{V}\) and therefore for all \(\mathbf{v}\!\in\!V\) by virtue of the density of \(\mathcal{V}\) in \(V\) (cf. Corollary I.2.5) and the continuity of the mapping \(\mathbf{v}\to a(\mathbf{u};\mathbf{u},\mathbf{v})\).

Finally, we have already seen that the bilinear form \(b(.,.)\) satisfies the inf-sup condition of Theorem 1.4 (see inequality (I.5.14)).

Thus, the hypotheses of Theorems 1.2 and 1.4 are fulfilled. Hence, there exists at least one function \(\mathbf{u}\!\in\!\mathcal{V}\) such that

(2.9) \[a(\mathbf{u};\mathbf{u},\mathbf{v})=\langle\mathbf{f},\mathbf{v}\rangle\quad \quad\forall\mathbf{v}\!\in\!\mathcal{V}.\]
