\[\int_{\Omega}\mathbf{w}\cdot\mathbf{curl}\,\lambda\,dx=\lim_{l\to\infty}\int_{ \Omega}\mathbf{grad}\,\chi_{l}\cdot\mathbf{curl}\,\lambda\,dx\]

and the result follows from the fact that

\[\int_{\Omega_{1}}\mathbf{grad}\,\chi_{l}\cdot\mathbf{curl}\,\lambda\,dx=0\,\,\, \,\,\,\,\,\,\,\,\forall l\geqslant k.\]

Since \(\Omega\) is simply-connected, this means that there exists \(\chi\) in \(H^{1}(\Omega)\) such that

\[\mathbf{w}=\mathbf{grad}\,\chi.\]

In addition, (3.46) implies that \(\mathbf{grad}\,\chi=\mathbf{0}\). Hence, we see that

\[\tilde{\Phi}_{l}\to\boldsymbol{\phi}\,\,\,\,\,\,\,\text{weakly in $L^{2}( \Omega)^{3}$}.\]

Together with (3.43), this implies that

\[\partial\tilde{\Phi}_{l}/\partial x_{i}\to\partial\phi/\partial x_{i}\,\,\,\, \,\,\,\,\text{weakly in $L^{2}(\Omega)^{3}$},\,\,\,\,\,\,\,\,\,1\leqslant i \leqslant 3.\]

Thus \(\boldsymbol{\phi}\in H^{1}(\Omega)^{3}\) and we derive from (3.43) that

\[|\boldsymbol{\phi}|_{1,\Omega}\leqslant\|\mathbf{curl}\,\boldsymbol{\phi}\|_ {0,\Omega}.\qed\]

As an immediate consequence of this theorem and Lemma 3.7, we see on the one hand that if \(\Omega\) is a bounded and convex polyhedron, the solution \(\chi\) of problem (3.39) is automatically in \(H^{2}(\Omega)\). On the other hand, if \(\Omega\) is a non convex polyhedron, there are cases where the solution of (3.39) is not in \(H^{2}(\Omega)\) and hence \(U\) is not included in \(H^{1}(\Omega)^{3}\).

As an interesting consequence of Theorem 3.8, we have the following corollary established by Foias & Temam [27]:

**Corollary 3.7**.: _Let \(\Omega\) be a bounded, open region of \(\,\mathbb{R}^{3}\) with a \(\mathscr{C}^{m,\,1}\) boundary \(\Gamma\) (\(m\geqslant 1\)). We have:_

(3.47) \[H^{m}(\Omega)^{3} = \{\mathbf{v}\in L^{2}(\Omega)^{3};\,\mathrm{div}\,\mathbf{v}\in H ^{m-1}(\Omega),\mathbf{curl}\,\mathbf{v}\in H^{m-1}(\Omega)^{3},\] \[\mathbf{v}\cdot\mathbf{n}\in H^{m-1/2}(\Gamma)\},\] (3.48) \[\|\mathbf{v}\|_{m,\Omega}\leqslant C\{\|\mathbf{v}\|_{0,\Omega} +\|\mathrm{div}\,\mathbf{v}\|_{m-1,\Omega}+\|\mathbf{curl}\,\mathbf{v}\|_{m-1 ,\Omega}+\|\mathbf{v}\cdot\mathbf{n}\|_{m-1/2,\Gamma}\}.\]

## 4 Analysis of an Abstract Variational Problem

In this paragraph, we construct an abstract framework well adapted to the solution of a variety of linear boundary value problems with a constraint, like the Stokes problem. Several algorithms are proposed to deal with the constraint. Although they are introduced in connection with the continuous problem, they will prove to be useful mainly for solving the discretized problems.
