**Lemma A.3**.: _Let \(p\in\mathbb{R}\) with \(p>1;\) for each \(v\in W^{2,\,p}(\kappa),\) there exists exactly one polynomial \(\widetilde{I}_{\kappa}v\in P_{k}\) such that:_

(A.22) \[\left\{\begin{aligned} &\widetilde{I}_{\kappa}v(a_{i})=v(a_{i}) \quad\quad 1\leqslant i\leqslant 3,\\ &\text{if }k\geqslant 2\quad\quad\int_{\kappa^{\prime}}( \widetilde{I}_{\kappa}v-v)f\,ds=0\quad\quad\forall f\in P_{k-2}(\kappa^{\prime }),\quad\quad\forall\text{sides }\kappa^{\prime}\text{ of }\kappa,\\ &\text{if }k\geqslant 3\quad\quad\int_{\kappa}(\widetilde{I}_{\kappa}v-v)f \,dx=0\quad\quad\forall f\in P_{k-3}(\kappa).\end{aligned}\right.\]

Proof.: First, we remark that (A.22) consists of \((1/2)(k+1)(k+2)\) equations, which is precisely the dimension of \(P_{k}\). Hence (A.22) is a square system of linear equations and it suffices to prove that its solution is unique. Thus, we assume that \(p\in P_{k}\) satisfies:

(i) \[p(a_{i})=0\quad\quad 1\leqslant i\leqslant 3,\]

(ii) \[\int_{\kappa^{\prime}}p(s)f(s)\,ds=0\quad\quad\forall f\in P_{k-2}(\kappa^{ \prime}),\quad\forall\text{sides }\kappa^{\prime}\text{ of }\kappa,\]

(iii) \[\int_{\kappa}p(x)f(x)\,dx=0\quad\quad\forall f\in P_{k-3}(\kappa).\]

Suppose for the moment that \(k\geqslant 3\). Note that the restriction of \(p\) to each \(\kappa^{\prime}\) is a polynomial of degree \(k\) of the single variable \(s\). Then it follows from (i) and (ii) that:

\[0=\int_{\kappa^{\prime}}p(s)(d^{\,2}p(s)/ds^{2})\,ds=-\int_{\kappa^{\prime}}( dp(s)/ds)^{2}\,ds.\]

Hence \(p=0\) on \(\partial\kappa\) and \(p\) can be expressed in terms of barycentric coordinates as:

\[p=\lambda_{1}\lambda_{2}\lambda_{3}q,\quad\text{where }q\in P_{k-3}.\]

Then (iii) implies that

\[\int_{\kappa}\lambda_{1}\lambda_{2}\lambda_{3}q^{2}(x)\,dx=0,\]

i.e. \(q=0\) since the integrand is non negative. Hence \(p=0\) on \(\kappa\).

The case \(k\leqslant 2\) is trivial. 

It is a matter of routine to check that \(\widetilde{I}_{\kappa}\in\mathcal{L}(W^{2,\,p}(\kappa);P_{k})\), the value of \(\widetilde{I}_{\kappa}v\) on each side \(\kappa^{\prime}\) of \(\kappa\) depends only on the value of \(v\) on \(\kappa^{\prime}\) and of course

\[\widetilde{I}_{\kappa}p=p\quad\quad\forall p\in P_{k}.\]

Furthermore, the operator \(\widetilde{I}_{\kappa}\) satisfies the fundamental relation (A.13):

\[\widehat{\widetilde{I}_{\kappa}v}=\widetilde{I}_{\kappa}\delta.\]

By collecting these properties and using Corollary A.2 and Remark A.1 we derive:
