organized more efficiently. For the sake of simplicity, we set:

\[g^{m}=g_{r}(\lambda^{m}),\ \ \ \ z^{m}=A_{r}^{-1}B^{\prime}\omega^{m}.\]

From (4.52), (4.53) and (4.55), we easily derive:

\[\rho^{m}=c(g^{m},\omega^{m})/b(z^{m},\omega^{m}).\]

In addition, by subtracting two consecutive values of (4.56) and using (4.54) we get:

\[u^{m+1}-u^{m}=\rho^{m}z^{m}.\]

Hence our general descent algorithm has the following procedure:

\(1^{\circ})\) Given an initial guess \(\lambda^{0}\in M\) compute \(u^{0}\in X\) by:

\[A_{r}u^{0}=l+B^{\prime}(rC^{-1}\chi-\lambda^{0});\]

\(2^{\circ})\) For \(m\geq 0\), given \(\omega^{m}\in M\) and knowing \((u^{m},\lambda^{m})\in X\times M\), determine \((z^{m},g^{m})\in X\times M\), \(\rho^{m}\in\mathbb{R}\) and the pair \((u^{m+1},\lambda^{m+1})\in X\times M\) by:

\[\left\{\begin{array}[]{l}Cg^{m}=\chi-Bu^{m},\\ A_{r}z^{m}=B^{\prime}\omega^{m},\\ \rho^{m}=c(g^{m},\omega^{m})/b(z^{m},\omega^{m}),\\ \lambda^{m+1}=\lambda^{m}-\rho^{m}\omega^{m},\\ u^{m+1}=u^{m}+\rho^{m}z^{m}.\end{array}\right.\] (4.57)

At each iteration, we have to solve two linear problems: one with the operator \(C\) and one with the operator \(A_{r}\). In practice, the operator \(C\) is easily invertible--for instance, in the case of the Stokes problem, one usually chooses the \(L^{2}\)-inner product for \(c(.,.)\) so that \(C\) is the identity operator . Hence the major computational effort is concentrated on \(z^{m}\).

This method of descent has the following convergence result:

**Theorem 4.6**.: _Assume that the form \(b(.,.)\) satisfies the inf-sup condition (4.9) and that \(a_{r}(.,.)\) and \(c(.,.)\) are both symmetric and satisfy the ellipticity conditions (4.46) and (4.25) respectively. Then for every starting value \(\lambda^{0}\in M\) and every sequence \((\omega^{m})\subset M\), the iterative scheme (4.57) defines a unique sequence \((u^{m},\lambda^{m})\) in \(X\times M\). In addition, if the sequences \((g^{m})\) and \((\omega^{m})\) satisfy for all \(m\geq 0\):_

\[c(g^{m},\omega^{m})\geq\alpha\|\,g^{m}\|_{M}\|\omega^{m}\|_{M}\ \ \ \ \ \alpha>0\ \ \ \mbox{ independent of }m,\] (4.58)

_then the method of descent converges_:

\[\lim_{m\rightarrow\infty}\left\{\|\,u^{m}-u\|_{X}+\|\,\lambda^{m}-\lambda\|_ {M}\right\}=0.\]

_Proof_. Clearly the first two equations in (4.57) have a unique solution because of the ellipticity of \(a_{r}(.,.)\) and \(c(.,.)\). Furthermore, (4.52) yields:
