**Corollary 1.2**.: _When a is symmetric--i.e. \(a(u,v)=a(v,u)\,\forall u,\,v\in V\)--then the solution \(u\) of (P) is also the only element of \(V\) that minimizes the following quadratic functional (also called energy functional) on \(V\)_:__

\[J(v)=(1/2)a(v,v)-\langle l,v\rangle.\] (1.24)

### Example 1: Dirichlet's Problem for the Laplace Operator

In all the examples, we assume that \(\Omega\) is bounded and \(\Gamma\) Lipschitz-continuous. Consider the following non-homogeneous Dirichlet's problem:

\[\text{Given $f$ in $H^{-1}(\Omega)$ and $g$ in $H^{1/2}(\Gamma)$, find a function $u$ such that}\] (D) \[\left\{\begin{aligned} (\ref{eqn:D1})&-Au=f& \text{in $\Omega$,}\\ (\ref{eqn:D2})&u=g&\text{on $\Gamma$.}\end{aligned}\right.\]

Let us formulate this problem in terms of Problem (P). We set \(V=H^{1}_{0}(\Omega)\) and

\[a(u,v)=(\mathbf{grad}\,u,\mathbf{grad}\,v).\]

It is clear that \(a\) is continuous in \(H^{1}_{0}(\Omega)^{2}\), and owing to Theorem 1.1,

\[a(v,v)=\|\mathbf{grad}\,v\|_{0,\Omega}^{2}=|v|_{1,\Omega}^{2}\geqslant C\,\|v \|_{1,\Omega}^{2}.\]

Besides that, since \(H^{1/2}(\Gamma)\) is the range space of \(\gamma_{0}\) in \(H^{1}(\Omega)\), let \(u_{0}\) in \(H^{1}(\Omega)\) satisfy \(u_{0}=g\) on \(\Gamma\), and examine the following problem:

\[\text{Find $u$ in $H^{1}(\Omega)$ such that}\] (D') \[\left\{\begin{aligned} (\ref{eqn:D1})&u-u_{0}\in H^{1}_{0}( \Omega),\\ (\ref{eqn:D2})&a(u-u_{0},v)=\langle f,v\rangle-a(u_{0},v )&\forall v\in H^{1}_{0}(\Omega).\end{aligned}\right.\]

Since \(a\) is continuous, the mapping \(v\to\langle f,v\rangle-a(u_{0},v)\) belongs to \(H^{-1}(\Omega)\). Therefore, thanks to the Lax & Milgram's Theorem, Problem (D') has one and only one solution \(u\) in \(H^{1}(\Omega)\).

It remains only to prove that \(u\) may be characterized as the unique solution of Problem (D). Taking \(v\in\mathcal{D}(\Omega)\) in (1.28) gives:

\[a(u,v)=-\langle\Delta u,v\rangle=\langle f,v\rangle\quad\quad\forall v\in \mathcal{D}(\Omega).\]

Hence \(u\) satisfies

\[\text{(D}_{1})\quad\left\{\begin{aligned} (\ref{eqn:D1})&u-u_{0}\in H^{1}_{0}( \Omega),\\ (\ref{eqn:D1})&-\Delta u=f&\text{in $H^{-1}( \Omega)$.}\end{aligned}\right.\]

Conversely, every solution of (D\({}_{1}\)) is a solution of (D') by the density of \(\mathcal{D}(\Omega)\) in \(H^{1}_{0}(\Omega)\). But

\[u-u_{0}\in H^{1}_{0}(\Omega)\quad\text{iff $u=g$}\quad\text{on $\Gamma$,}\]

therefore Problems (D\({}_{1}\)) and (D) are the same.
