(3.68) \[\varepsilon_{h}(\lambda) \leqslant\|\,\tilde{u}_{h}(\lambda)-u(\lambda)\|_{X}+|\lambda|\,\|\,T _{h}\{G_{h}(\tilde{u}_{h}(\lambda))-G(u(\lambda))\}\,\|_{X}\] \[\qquad+|\lambda|\,\|(T_{h}-\,T)G(u(\lambda))\|_{X}.\]

But on the one hand, (3.61) and Ascoli's Lemma imply that

\[\limsup_{h\to 0}\sup_{\lambda\in\,\Lambda}\|\,\tilde{u}_{h}(\lambda)-u(\lambda) \|_{X}=0.\]

On the other hand, (3.59) and (3.62) yield:

\[\limsup_{h\to 0}\sup_{\lambda\in\,\Lambda}\|\,T_{h}\{G_{h}(\tilde{u}_{h}( \lambda))-G(u(\lambda))\}\,\|_{X}=0.\]

In addition, it stems from the continuity of the mapping \(G\) and (3.60) that

\[\limsup_{h\to 0}\sup_{\lambda\in\,\Lambda}\|(T_{h}-\,T)G(u(\lambda))\|_{X}=0.\]

These three limits give immediately (3.27').

Now, we turn to (3.26'). For each \(u_{h}\!\in\!V_{h}\), it is natural to define \(F_{u}F_{h}(\lambda,u_{h})\!\in\!\mathscr{L}(V_{h};V_{h})\) by:

(3.69) \[F_{u}F_{h}(\lambda,u_{h})=I+\lambda T_{h}VG_{h}(u_{h}).\]

Then we can write:

(3.70) \[F_{u}F_{h}(\lambda,\tilde{u}_{h}(\lambda))=\lambda T_{h}\{FG_{h}(\tilde{u}_{h }(\lambda))-DG(u(\lambda))\}+I+\lambda T_{h}DG(u(\lambda)).\]

But observe that the operator \(I+\lambda T_{h}DG(u(\lambda))\) belongs to \(\mathscr{L}(X;X)\cap\mathscr{L}(V_{h};V_{h})\). Furthermore,

\[I+\lambda T_{h}DG(u(\lambda))-D_{u}F(\lambda,u(\lambda))=\lambda(T_{h}-\,T)DG (u(\lambda))\]

and owing to (3.60) and the differentiability of \(G\), we have

\[\limsup_{h\to 0}\sup_{\lambda\in\,\Lambda}\|(T_{h}-\,T)DG(u(\lambda))\|_{ \mathscr{L}(X;X)}=0.\]

Hence, applying Lemma 3.3 we find that there exists a real \(h_{0}>0\) such that for all \(h\leqslant h_{0}\) and all \(\lambda\!\in\!\Lambda\), \(I+\lambda T_{h}DG(u(\lambda))\) is an isomorphism of \(X\) as well as an isomorphism of \(V_{h}\). Besides that, we have the bound:

(3.71) \[\|(I+\lambda T_{h}DG(u(\lambda)))^{-1}\,\|_{\mathscr{L}(V_{h};V_ {h})} \leqslant\|(I+\lambda T_{h}DG(u(\lambda)))^{-1}\,\|_{\mathscr{L}(X;X)}\] \[\leqslant 2\gamma(\lambda)\quad\forall h\leqslant h_{0}\quad\text{ and }\quad\forall\lambda\!\in\!\Lambda,\]

where \(\gamma(\lambda)\) is defined by (3.13). Likewise, it follows from (3.59) and (3.63) that

\[\limsup_{h\to 0}\sup_{\lambda\in\,\Lambda}\|\,T_{h}\{F_{h}G_{h}(\tilde{u}_{h}( \lambda))-DG(u(\lambda))\}\|_{\mathscr{L}(V_{h};V_{h})}=0.\]

Therefore, applying again Lemma 3.3 and using (3.70) and (3.71), we see that there exists another \(h_{1}\), with \(0<h_{1}\leqslant h_{0}\), such that for all \(h\leqslant h_{1}\) and all \(\lambda\!\in\!\Lambda\), \(F_{u}F_{h}(\lambda,\tilde{u}_{h}(\lambda))\) is an isomorphism of \(V_{h}\) and

\[\|[F_{u}F_{h}(\lambda,\tilde{u}_{h}(\lambda))]^{-1}\,\|_{\mathscr{L}(V_{h};V_{h })}\leqslant 4\gamma(\lambda)\quad\forall h\leqslant h_{1},\quad\forall \lambda\!\in\!\Lambda.\]

As \(\gamma(\lambda)\) is bounded above, this establishes (3.26').
