\(2^{\circ}\)) Conversely, let \(\mathbf{v}\) satisfy (3.1). The idea is to extend \(\mathbf{v}\) to the whole plane so that it remains divergence-free. Then, it will be easy to construct its stream function by means of the Fourier transform.

a) We propose to use an extension that has the same normal component as \(\mathbf{v}\) on \(\Gamma\).

Let \(\mathcal{O}\) be any bounded, smooth, simply-connected open set with \(\bar{\mathcal{O}}\subset\mathcal{O}\). Then, for \(p\geqslant 1\), the set \(\mathcal{O}-\bar{\mathcal{O}}\) is not connected and we denote by \(\Omega_{i}\) that component which is bounded by \(\Gamma_{i}\), for \(1\leqslant i\leqslant p\), and \(\Omega_{0}\) that component bounded by \(\Gamma_{0}\) and \(\partial\mathcal{O}\) (cf. Figure 2). Consider the following problem:

\[\begin{array}[]{c}\mbox{\it Find $w$ defined in $\mathcal{O}-\bar{\mathcal{O}}$ such that}\\ \left\{\begin{array}[]{c}\Delta w=0\quad\mbox{in $\mathcal{O}-\bar{\mathcal{O}}$}, \\ \bar{\partial}w/\partial n=\mathbf{v}\cdot\mathbf{n}\quad\mbox{on $\Gamma_{i}$}\quad \mbox{for $0\leqslant i\leqslant p$},\\ \partial w/\partial n=0\quad\mbox{on $\partial\mathcal{O}$},\end{array}\right.\end{array}\]

where \(\mathbf{n}\) denotes the unit normal to \(\Gamma_{i}\) pointing outside \(\Omega_{i}\), \(0\leqslant i\leqslant p\). Problem (N) consists of \(p+1\) non-homogeneous Neumann's problems, each defined in \(\Omega_{i}\) for \(0\leqslant i\leqslant p\), like the one we analyzed in Section 1.4 since they include the compatibility conditions

\[\langle\mathbf{v}\cdot\mathbf{n},1\rangle_{\Gamma_{i}}=0\quad\mbox{for $0 \leqslant i\leqslant p$}.\]

Therefore, there exists a function \(w\!\in\!H^{1}(\mathcal{O}-\bar{\mathcal{O}})\) satisfying (N), determined uniquely up to an additive constant in each \(\Omega_{i}\). We set

\[\mathbf{0}=\mathbf{grad}\ w.\]

Then \(\mathbf{0}\!\in\!H(\operatorname{div};\mathcal{O}-\bar{\mathcal{O}})\) with

(3.3) \[\left\{\begin{array}[]{c}\operatorname{div}\mathbf{0}=\Delta w=0\quad\mbox{in $ \mathcal{O}-\Omega$},\\ \mathbf{0}\cdot\mathbf{n}=\delta w/\delta n=\mathbf{v}\cdot\mathbf{n}\quad \mbox{on $\Gamma_{i}$}\quad\mbox{for $0\leqslant i\leqslant p$},\\ \mathbf{0}\cdot\mathbf{n}=0\quad\mbox{on $\partial\mathcal{O}$}.\end{array}\right.\]

b) Now we can extend \(\mathbf{v}\) as follows:

\[\mathbf{\tilde{v}}=\begin{cases}\mathbf{v}&\mbox{in $\Omega$},\\ \mathbf{0}&\mbox{in $\mathcal{O}-\Omega$},\\ \mathbf{0}&\mbox{elsewhere}.\end{cases}\]

Clearly, \(\mathbf{\tilde{v}}\!\in\!L^{2}(\mathbb{R}^{2})^{2}\). Let us calculate its divergence; as a distribution, \(\operatorname{div}\mathbf{\tilde{v}}\) satisfies:

\[\langle\operatorname{div}\mathbf{\tilde{v}},\phi\rangle=-\!\int_{\mathbb{R}^{2 }}\mathbf{\tilde{v}}\cdot\mathbf{grad}\,\phi\,dx\quad\quad\forall\phi\!\in\! \mathcal{D}(\mathbb{R}^{2}),\]

that is

\[\langle\operatorname{div}\mathbf{\tilde{v}},\phi\rangle=-\!\int_{\Omega} \mathbf{v}\cdot\mathbf{grad}\,\phi\,dx-\sum\limits_{i=0}^{p}\int_{\Omega_{i}} \mathbf{0}\cdot\mathbf{grad}\,\phi\,dx.\]

As \(\mathbf{v}\) and \(\mathbf{0}\) are both divergence-free, Green's formula (2.17) and (3.3) yield:
