Next, we note that for all \(v=(\mathbf{v},q)\in X\)

\[D_{u}G(\lambda,u)\cdot v=\bigg{(}\,\lambda\sum_{j=1}^{N}\,(u_{j}\partial\mathbf{ v}/\partial x_{j}+v_{j}\partial\mathbf{u}/\partial x_{j}),\mathbf{0}\bigg{)}.\]

Hence in our example, \(u=(\mathbf{u},p/v)\) is a nonsingular solution of (3.1), or equivalently \(D_{u}F(1/v,u)\) is an isomorphism of \(X\) if and only if, for each \(w=(\mathbf{w},\sigma)\in X\) there exists a unique \(v=(\mathbf{v},q)\) in \(X\) such that

\[\begin{split}-\Delta\mathbf{v}+\mathbf{grad}\,q+(1/v)\sum_{j=1}^{ N}\,(u_{j}\partial\mathbf{v}/\partial x_{j}+v_{j}\partial\mathbf{u}/\partial x _{j})=\,-\Delta\mathbf{w}+\mathbf{grad}\,\sigma\quad\text{in }\Omega,\\ \operatorname{div}\mathbf{v}=\operatorname{div}\mathbf{w}\\ \mathbf{v}=\mathbf{w}\quad\text{on }\Gamma.\end{split}\]

Now, this problem can be simplified because on the one hand, an obvious extension of Theorem I.5.4, proved in Cattabriga [18], guarantees that for every \(\mathbf{f}\in H^{-1}(\Omega)^{N}\), \(\mu\in L^{2}(\Omega)\) and \(\mathbf{g}\in H^{1/2}(\Gamma)^{N}\) fulfilling the compatibility condition

\[\int_{\Omega}\mu\,dx=\int_{\Gamma}\mathbf{g}\cdot\mathbf{n}\,ds\]

there exists a unique \(w=(\mathbf{w},\sigma)\) in \(X\) solution of

\[\begin{split}-\Delta\mathbf{w}+\mathbf{grad}\,\sigma& =\mathbf{f}\\ \operatorname{div}\mathbf{w}&=\mu\end{split} \quad\text{in }\Omega,\] \[\mathbf{w} =\mathbf{g}\quad\text{on }\Gamma.\]

On the other hand, when \(\mu\) and \(\mathbf{g}\) satisfy the above conditions an extension of Lemma I.2.2 shows that there exists \(\mathbf{v}_{0}\) in \(H^{1}(\Omega)^{N}\) such that

\[\operatorname{div}\mathbf{v}_{0}=\mu,\quad\,\mathbf{v}_{0}\,|_{\Gamma}= \mathbf{g}.\]

Therefore, applying these two results we can prove that \(u=(\mathbf{u},p/v)\) is a nonsingular solution of (3.1) if and only if the homogeneous linearized problem

(3.10) \[\begin{split}-v\Delta\mathbf{v}+\sum_{j=1}^{N}\,(u_{j}\partial \mathbf{v}/\partial x_{j}+v_{j}\partial\mathbf{u}/\partial x_{j})+\mathbf{ grad}\,q&=\mathbf{f}_{\star}\\ \operatorname{div}\mathbf{v}&=0\end{split} \quad\text{in }\Omega,\] \[\mathbf{v} =\mathbf{0}\quad\text{on }\Gamma\]

has a unique solution \(v=(\mathbf{v},q)\in X\) for each \(\mathbf{f}_{\star}\in H^{-1}(\Omega)^{N}\), the mapping \(\mathbf{f}_{\star}\to v\) being continuous from \(H^{-1}(\Omega)^{N}\) into \(X\).

Although we do not want to give here a precise statement, it can be proved that the solutions of the Dirichlet problem for the Navier-Stokes equations are "in general" nonsingular. We shall only derive the following simple result.
