and we define the corresponding subspace

\[V_{h}=\{(\vec{\mathbf{curl}}\,\phi_{h},\theta_{h})\in X_{h};(\vec{\mathbf{curl}}\, \phi_{h},\vec{\mathbf{curl}}\,\mu_{h})=(\theta_{h},\mu_{h})\quad\forall\mu_{h} \in\mathcal{O}_{h}\}.\] (5.9)

The discrete Stokes operator can be defined on a wider space than \(Y\), namely:

\[Y_{h}=\text{the dual space of }\{\boldsymbol{\mathbf{curl}}\,\phi_{h};\,\phi_{h} \in\mathcal{O}_{h}\}\]

equipped with the norm

\[\|l\|_{\star}=\sup_{\phi_{h}\in\mathcal{O}_{h}}\frac{\langle l,\vec{\mathbf{ curl}}\,\phi_{h}\rangle}{|\phi_{h}|_{1,\,s,\Omega}}.\]

By setting

\[\langle l,v_{h}\rangle=\langle l,\vec{\mathbf{curl}}\,\phi_{h}\rangle\quad \quad\forall v_{h}=(\vec{\mathbf{curl}}\,\phi_{h},\theta_{h})\in V_{h},\]

the space \(Y_{h}\) can also be identified with a subspace of \(V_{h}^{{}^{\prime}}\), the dual space of \(V_{h}\); thus we have the following continuous imbeddings:

\[Y\subsetneq Y_{h}\subsetneq V_{h}^{{}^{\prime}}.\]

It will be useful further on to provide \(Y_{h}\) with the norm of \(V_{h}^{{}^{\prime}}\), i.e. we put

\[\|l\|_{h}=\sup_{v_{h}\in\mathcal{V}_{h}}\frac{\langle l,v_{h}\rangle}{\|v_{h} \|_{X}}\quad\quad\forall l\in Y_{h};\]

clearly we have:

\[\|l\|_{h}\leq\|l\|_{\star}\quad\quad\forall l\in Y_{h}.\]

Then we define the approximate Stokes operator \(T_{h}\in\mathcal{C}(Y_{h};X_{h})\) by:

\[\begin{split}&\text{\it For }l\in Y_{h},\text{\it find }T_{h}l=(\vec{\mathbf{curl}}\,\psi_{h},\omega_{h})\in X_{h}\text{\it solution of}\\ &\begin{cases}(\vec{\mathbf{curl}}\,\omega_{h},\vec{\mathbf{curl}}\, \phi_{h})=\langle l,\vec{\mathbf{curl}}\,\phi_{h}\rangle\quad\quad\forall \phi_{h}\in\mathcal{O}_{h},\\ (\vec{\mathbf{curl}}\,\psi_{h},\vec{\mathbf{curl}}\,\mu_{h})=(\omega_{h},\mu_ {h})\quad\quad\forall\mu_{h}\in\mathcal{O}_{h}.\end{cases}\end{split}\] (5.10)

Obviously the range of the operator \(T_{h}\) is the space \(V_{h}\).

Now we turn to the upwind discretization of the convection term. Considering that \(\Omega\) is the union of all the triangles \(\kappa\) of \(\mathcal{T}_{h}\), formula (5.2) can be generalized to yield the following definition:

\[\begin{split}\int_{\Omega}u_{j}(\partial u_{i}/\partial x_{j})v_ {i}\,dx\stackrel{{\mathrm{def}}}{{=}}\\ \sum_{\kappa\in\mathcal{T}_{h}}\biggl{\{}\int_{\kappa}u_{j}( \partial u_{i}/\partial x_{j})v_{i}\,dx+\int_{\partial-\kappa}\vec{\mathbf{u} }\cdot\vec{\mathbf{n}}(u_{i}^{ext}-u_{i}^{int})v_{i}^{int}\,ds\biggr{\}}.\end{split}\] (5.11)

This induces us to split the convection term and replace the single trilinear form by two forms: one for the volume integrals and one for the line integrals. Thus for all \(u=(\vec{\mathbf{curl}}\,\psi,\omega)\) and \(v=(\vec{\mathbf{curl}}\,\phi,\theta)\) in \(X_{h}\) and all \(\vec{\mathbf{w}}\) of the form \(w_{i}=\partial\chi/\partial x_{j}\) with \(\chi\) in \(\mathcal{O}_{h}\) we set:
