Proof.: Since the functions \(\mathbf{p}_{i}\) vanish on all vertices of \(\kappa\), we can write

(3.4) \[\mathbf{p}=I_{\kappa}\mathbf{p}+\sum_{i=1}^{4}\alpha_{i}\mathbf{p}_{i},\ \ \ \ \ \alpha_{i}\in\mathbb{R},\]

where \(I_{\kappa}\) denotes the standard interpolation operator on \(Q_{1}(\kappa)^{2}\). Furthermore,

(3.5) \[(\mathbf{p}-I_{\kappa}\mathbf{p})\cdot\mathbf{n}_{i}|_{f_{i}}=\alpha_{i}(\hat {q}_{i}\circ F_{\kappa}^{-1})|_{f_{i}}.\]

From these two expressions we can easily derive that zero moments yield only the zero polynomial. 

Thus, we choose the following velocity and pressure spaces:

(3.6) \[\begin{cases}W_{h}=\langle\mathbf{w}\in\mathcal{C}^{0}(\bar{\Omega})^{2}; \mathbf{w}|_{\kappa}\in\mathcal{Q}_{1}(\kappa)\ \ \ \forall\kappa\in\mathcal{T}_{h}\rangle,\\ \bar{X}_{h}=W_{h}\cap H_{0}^{1}(\Omega)^{2},\end{cases}\]

(3.7) \[\begin{cases}Q_{h}=\{q\in L^{2}(\Omega);\,q|_{\kappa}\in P_{0}\ \ \ \forall\kappa\in\mathcal{T}_{h}\},\\ \bar{M}_{h}=Q_{h}\cap L_{0}^{2}(\Omega).\end{cases}\]

Lemma 3.1 suggests the interpolation operator \(r_{\kappa}\) on \(\mathcal{Q}_{1}(\kappa)\) defined by:

\[r_{\kappa}\mathbf{v}(a_{i})=\mathbf{v}(a_{i}),\ \ \ \ \ \int_{f_{j}}(r_{\kappa} \mathbf{v}-\mathbf{v})\cdot\mathbf{n}_{j}\,ds=0,\ \ \ \ \ 1\leqslant i<j\leqslant 4.\]

But once again, this operator does not satisfy Hypothesis H3 because it is not defined on \(H^{1}(\Omega)^{2}\). Therefore, like in the simplicial case we replace the above values of \(\mathbf{v}\) by those of the local regularization operator \(R_{h}\), similar to that of Section A.3:

\[R_{h}\in\mathcal{C}(H_{0}^{1}(\Omega);\,\Phi_{h})\]

with

\[\Phi_{h}=\{\phi\in\mathcal{C}^{0}(\bar{\Omega});\,\phi|_{\kappa}\in Q_{1}( \kappa)\ \ \ \forall\kappa\in\mathcal{T}_{h}\}\cap H_{0}^{1}(\Omega).\]

Then we define the operator \(\pi_{h}\in\mathcal{C}(H_{0}^{1}(\Omega)^{2};\,\bar{X}_{h})\) by:

(3.8) \[\begin{cases}\pi_{h}\mathbf{v}(a)=R_{h}\mathbf{v}(a)\ \ \ \ \ \forall\text{node $a$ of $\mathcal{T}_{h}$},\\ \int_{f}(\pi_{h}\mathbf{v}-\mathbf{v})\cdot\mathbf{n}\,ds=0\ \ \ \ \ \forall\text{side $f$ of $\mathcal{T}_{h}$}.\end{cases}\]

In order to establish the approximating properties of \(\pi_{h}\) we must assume that the triangulation \(\mathcal{T}_{h}\) is regular in the sense of Definition A.2 with the parameters:

\[h_{\kappa}=\text{diameter of $\kappa$},\ \ \ \ \ \rho_{\kappa}=2\mathop{\mathrm{Min}}_{1 \leqslant i\leqslant 4}\{\text{diameter of circle inscribed in $S_{i}$}\}\]

where \(S_{i}\) denotes the triangle with vertices \(a_{i-1}\), \(a_{i}\), \(a_{i+1}\).

**Lemma 3.2**.: _The operator \(\pi_{h}\) defined by (3.8) satisfies:_

\[\int_{\Omega}\operatorname{div}(\mathbf{v}-\pi_{h}\mathbf{v})q\,dx=0\ \ \ \ \ \forall q\in\bar{Q}_{h}.\]
