According to Theorem 1.6, if \(\Gamma\) is \(\mathcal{C}^{1,\,1}\), there exists a function \(u_{0}\) in \(H^{2}(\Omega)\) such that

(1.45) \[u_{0}=g_{1}\quad\text{on }\Gamma,\quad\partial u_{0}/\partial n=g_{2}\quad \text{on }\Gamma.\]

Thus we turn to the following problem:

* \[\left\{\begin{aligned} &\text{Find }u\text{ in }H^{2}(\Omega)\text{ such that}\\ &\text{\eqref{eq:H2}}&\quad\text{ }u-u_{0}\in H^{2}_{0}(\Omega),\\ &\text{\eqref{eq:H2}}&\quad a(u-u_{0},v)=\langle f,v \rangle-a(u_{0},v)\quad\quad\forall v\in H^{2}_{0}(\Omega).\end{aligned}\right.\]

By the Lax & Milgram's Theorem 1.7, Problem (B') has exactly one solution \(u\) in \(H^{2}(\Omega)\). Owing to (1.45) and (1.46), \(u\) satisfies the boundary conditions:

\[u=g_{1}\quad\text{on }\Gamma,\quad\partial u/\partial n=g_{2}\quad\text{on }\Gamma.\]

Besides that, by restricting the test functions of (1.47) to \(\mathcal{D}(\Omega)\), we find

\[\Delta^{2}u=f\quad\text{in }H^{-2}(\Omega).\]

Therefore, \(u\) is a solution of (B).

Conversely, as in the case of the Laplace operator, we can show that Problem (B) has at most one solution in \(H^{2}(\Omega)\).

From (1.47) and the equivalence of norms, we derive the bound

\[\left\|u\right\|_{2,\,\Omega}\leqslant C_{1}(\left\|f\right\|_{-2,\,\Omega}+ \left\|u_{0}\right\|_{2,\,\Omega})\quad\quad\forall u_{0}\text{ satisfying }\eqref{eq:H2},\]

i.e.

\[\left\|u\right\|_{2,\,\Omega}\leqslant C_{2}(\left\|f\right\|_{-2,\,\Omega}+ \left\|g_{1}\right\|_{3/2,\,\Gamma}+\left\|g_{2}\right\|_{1/2,\,\Gamma}).\]

These results are summed up in the proposition below:

**Proposition 1.3**.: _If \(\Gamma\) is \(\mathcal{C}^{1,\,1}\), Problem (B) has exactly one solution \(u\) in \(H^{2}(\Omega)\), bounded as follows:_

(1.48) \[\left\|u\right\|_{2,\,\Omega}\leqslant C(\left\|f\right\|_{-2,\,\Omega}+ \left\|g_{1}\right\|_{3/2,\,\Gamma}+\left\|g_{2}\right\|_{1/2,\,\Gamma}).\]

The above analysis does not allow for corners since it assumes that \(\Gamma\) is \(\mathcal{C}^{1,\,1}\). This hypothesis plays a crucial part in the lifting operator: \((g_{1},g_{2})\to u_{0}\). Of course, if these non-homogeneous data are given directly in the form of a function \(u_{0}\) in \(H^{2}(\Omega)\) such that

\[u=u_{0}\quad\text{on }\Gamma\quad\text{and}\quad\partial u/\partial n=\partial u _{0}/\partial n\quad\text{on }\Gamma\]

then Proposition 1.3 applies to a Lipschitz-continuous domain with \(u_{0}\) instead of \(g_{1}\) and \(g_{2}\). Otherwise, we must alter a little the statement of Problem (B). Suppose that \(\Omega\) is a two-dimensional bounded polygon. In view of Remark 1.1, let \(\Gamma_{j}\) and \(S_{j}\) for \(1\leqslant j\leqslant J\) denote respectively the sides and vertices of \(\Gamma\). Let us take \(J\) functions:
