\[r_{h}\mathbf{u}=\mathbf{grad}\,q\quad\text{for some $q$ in $H_{0}^{1}(\Omega)$.}\]

On the other hand, Lemma 5.3 implies that

\[q|_{\kappa}\in P_{t}\quad\text{for each $\kappa$.}\]

Therefore \(q\in\Theta_{h}\). 

_Remark 5.7_.: Lemma 5.10 shows that for each function \(\phi_{h}\) in \(\Phi_{h}\) that satisfies \(\mathbf{curl}\,\phi_{h}=\mathbf{0}\) in \(\Omega\) there exists a (unique) element \(p_{h}\) of \(\Theta_{h}\) such that

\[\phi_{h}=\mathbf{grad}\,p_{h}.\]

Thus

\[\{\mathbf{grad}\,p_{h};\,p_{h}\in\Theta_{h}\}=\{\phi_{h}\in\Phi_{h};\,\mathbf{ curl}\,\phi_{h}=\mathbf{0}\}.\]

It follows from this last remark that \(\Phi_{h0}\) satisfies (5.14). But if we want to check that (5.14) holds _uniformly_, we shall require below a uniformly regular triangulation, i.e. a regular triangulation \(\mathcal{T}_{h}\) that also satisfies for some \(\tau>0\) independent of \(h\):

\[\tau h\leq h_{\kappa}\leq\sigma\rho_{\kappa}\quad\quad\forall\kappa\in \mathcal{T}_{h}.\]

**Proposition 5.1**.: _Let \(\Omega\) be an open, bounded and convex region of \(\mathbb{R}^{3}\) with a polyhedral boundary \(\Gamma\). If \(\mathcal{T}_{h}\) is a uniformly regular triangulation of \(\Omega\), there exists a constant \(C^{\star}\), independent of \(h\), such that:_

(5.14) \[\|\phi_{h}\|_{0,\Omega}\leq C^{\star}\|\,\mathbf{curl}\,\phi_{h}\|_{0,\Omega} \quad\quad\forall\phi_{h}\in\Phi_{h0}.\]

Proof.: The idea is to write \(\phi_{h}\) as the sum of a gradient and a divergence-free function \(\mathbf{w}\), smooth enough to satisfy an inequality similar to (5.14). First, let \(p\in H_{0}^{1}(\Omega)\) be the unique solution of the problem:

\[(\mathbf{grad}\,p,\mathbf{grad}\,q)=(\phi_{h},\mathbf{grad}\,q)\quad\quad \forall q\in H_{0}^{1}(\Omega).\]

Clearly the difference

\[\mathbf{w}=\phi_{h}-\mathbf{grad}\,p\]

satisfies \[\mathbf{curl}\,\mathbf{w}=\mathbf{curl}\,\phi_{h},\quad\,\mathrm{div}\, \mathbf{w}=0,\quad\,\mathbf{w}\,\times\,\mathbf{n}|_{\Gamma}=\mathbf{0}.\]

In addition, \(\mathbf{curl}\,\phi_{h}\) belongs to \(L^{\gamma}(\Omega)^{3}\) for all \(\gamma\). Therefore, since \(\Omega\) is convex, it follows from Remark I.3.14 that there exists a real \(s>2\) such that:

\[\mathbf{w}\in W^{1,s}(\Omega)^{3}\]

and

(5.14) \[\|\,\mathbf{w}\,\|_{1,\alpha,\Omega}\leq C_{1}(\alpha)\,\|\,\mathbf{curl}\, \mathbf{w}\,\|_{0,\alpha,\Omega}\quad\text{for all $\alpha$ with $2\leq\alpha\leq s$.}\]

Hence, the interpolate \(r_{h}\mathbf{w}\) is well defined. As \(\phi_{h}\) belongs to \(\Phi_{h}\), this in turn implies that \(r_{h}(\mathbf{grad}\,p)\) is also well defined and owing to Lemma 5.10, there exists \(p_{h}\) in \(\Theta_{h}\) such that

\[r_{h}(\mathbf{grad}\,p)=\mathbf{grad}\,p_{h}.\]
