Moreover, for each solution \(\mathbf{u}\) of (2.9), there exists a unique \(p\!\in\!L^{2}_{0}(\Omega)\) such that \((\mathbf{u},p)\) is a solution of Problem (2.8). 

Now, we turn to the uniqueness of the solution \((\mathbf{u},p)\) of Problem (2.8). For this, we introduce the norm of the trilinear form \(a_{1}(.;.,.)\) in \(V^{3}\):

\[\mathcal{N}=\sup_{\mathbf{u},\,\mathbf{v},\,\mathbf{w}\in V}\frac{a_{1}( \mathbf{w};\mathbf{u},\mathbf{v})}{|\mathbf{u}|_{1,\,\Omega}|\mathbf{v}|_{1, \,\Omega}|\mathbf{w}|_{1,\,\Omega}}.\] (2.10)

We also set:

\[\|\mathbf{f}\|_{V^{\prime}}=\sup_{\mathbf{v}\in V}\frac{\langle\mathbf{f}, \mathbf{v}\rangle}{|\mathbf{v}|_{1,\,\Omega}}.\] (2.11)

**Theorem 2.2**.: _Under the hypotheses of Theorem 2.1 and if in addition_

\[(\mathcal{N}/v^{2})\,\|\mathbf{f}\|_{V^{\prime}}<1,\] (2.12)

_then Problem (2.8) has a unique solution \((\mathbf{u},p)\) in \(V\times L^{2}_{0}(\Omega)\)._

Proof.: Here, we make use of Theorem 1.3. We have already proved the property (1.13) with \(\alpha=v\) and it suffices to establish (1.14). Let \(\mathbf{u},\mathbf{v},\,\mathbf{w}_{1}\) and \(\mathbf{w}_{2}\) be in \(V\); we have:

\[|a(\mathbf{w}_{1};\mathbf{u},\mathbf{v})-a(\mathbf{w}_{2};\mathbf{ u},\mathbf{v})| =|a(\mathbf{w}_{1}-\mathbf{w}_{2};\mathbf{u},\mathbf{v})|\] \[\leqslant\mathcal{N}|\mathbf{u}|_{1,\,\Omega}|\mathbf{v}|_{1,\, \Omega}|\mathbf{w}_{1}-\mathbf{w}_{2}|_{1,\,\Omega}.\]

Therefore, the form \(a(.;.,.)\) satisfies the hypothesis (1.14) with \(L(\mu)=\mathcal{N}\) for all \(\mu\). Then, the condition (2.12) coincides precisely with (1.15). Hence, the conclusion of Theorem 1.3 is valid. 

Let us next consider the general case of a _nonhomogeneous Dirichlet boundary condition_

\[\mathbf{u}=\mathbf{g}\quad\text{on }\Gamma.\] (2.13)

Denote again by \(\Gamma_{i},0\leqslant i\leqslant p\), the connected components of the boundary \(\Gamma\) like in Figure 2. We shall assume in all the sequel that

\[\int_{\Gamma_{i}}\mathbf{g}\!\cdot\!\mathbf{n}\,ds=0,\quad\ 0\leqslant i \leqslant p.\] (2.14)

Now, we need the following important technical result due to Hopf [45].

**Lemma 2.3**.: _Suppose \(N\leqslant 3\) and \(\Omega\) is like in Theorem 2.1. Then, given a function \(\mathbf{g}\!\in\!H^{1/2}(\Gamma)^{N}\) satisfying the conditions (2.14), there exists for any \(\varepsilon>0\) a function \(\mathbf{u}_{0}=\mathbf{u}_{0}(\varepsilon)\!\in\!H^{1}(\Omega)^{N}\) such that_
