(5.12) \[a_{1}(u;v,\mathbf{w})=\sum_{\kappa\in\mathcal{S}_{h}}\int_{\kappa}u_{j}(\partial v _{i}/\partial x_{j})w_{i}\,dx\]

where \(\mathbf{u}=\mathbf{curl}\,\psi\) and \(\mathbf{v}=\mathbf{curl}\,\phi\); likewise for \(z=(\mathbf{curl}\,v,\mu)\) in \(X_{h}\) we take:

(5.13) \[a_{2}^{z}(u;v,\mathbf{w})=\sum_{\kappa\in\mathcal{S}_{h}}\int_{\partial_{-} \kappa(z)}\mathbf{u}\,\boldsymbol{\cdot}\,\mathbf{n}(v_{i}^{\text{ext}}-v_{i} ^{\text{int}})w_{i}^{\text{int}}\,ds,\]

where \(\mathbf{n}\) denotes always the unit exterior normal to \(\kappa\), the superscript \(ext\) (resp. \(int\)) denotes the external (resp. internal) trace of the function on the boundary of \(\kappa\) and

(5.14) \[\partial_{-}\kappa(z)=\{x\in\partial\kappa;(\mathbf{z}\cdot\mathbf{n})(x)<0\} ,\quad\mathbf{z}=\mathbf{curl}\,v,\]

i.e. \(\partial_{-}\kappa(z)\) is the portion of the boundary of \(\kappa\) where the fluid with velocity \(\mathbf{z}\) enters \(\kappa\). Finally, we introduce the form

(5.15) \[\tilde{a}^{z}(u;v,\mathbf{w})=a_{1}(u;v,\mathbf{w})+a_{2}^{z}(u;v,\mathbf{w})\]

and we define the mapping \(G_{h}\): \(v\in X_{h}\to G_{h}(v)\in Y_{h}\) by

(5.16) \[\langle G_{h}(v),\mathbf{curl}\,\chi\rangle=\tilde{a}^{v}(v;v,\mathbf{curl}\, \chi)-(\mathbf{f},\mathbf{curl}\,\chi)\quad\quad\forall\chi\in\Phi_{h}.\]

The continuity of \(G_{h}\) will be established subsequently, but right away we observe that owing to the dependence of \(a_{2}^{v}(v;v,\mathbf{w})\) on \(\partial_{-}\kappa(v)\) the mapping \(G_{h}\) is not differentiable. Note that when \(\mathbf{w}\in H^{1}(\Omega)^{2}\) the form \(a\) satisfies the crucial property justifying definition (5.11):

(5.17) \[\tilde{a}^{z}(u;v,\mathbf{w})=-\int_{\Omega}u_{j}(\partial w_{i}/\partial x_{ j})v_{i}\,dx,\]

whatever the function \(z\), provided of course \(\operatorname{div}\mathbf{u}=0\) in \(\Omega\) and \(\mathbf{u}\cdot\mathbf{n}=0\) on \(\Gamma\).

Then the Navier-Stokes Problem (5.7) has the following upwind discretization:

_Find \(\psi_{h}\in\Phi_{h}\) and \(\omega_{h}\in\Theta_{h}\) solution of_

(5.18) \[\begin{cases}v(\mathbf{curl}\,\omega_{h},\mathbf{curl}\,\phi_{h})+\tilde{a}^{ u_{h}}(u_{h};u_{h},\mathbf{curl}\,\phi_{h})=(\mathbf{f},\mathbf{curl}\,\phi_{h}) \quad\quad\forall\phi_{h}\in\Phi_{h},\\ (\mathbf{curl}\,\psi_{h},\mathbf{curl}\,\mu_{h})=(\omega_{h},\mu_{h})\quad \quad\forall\mu_{h}\in\Theta_{h},\end{cases}\]

with \(\tilde{a}\) defined by (5.12) (5.15). Keeping in mind the above notations, this problem takes the form of (3.58):

(5.19) \[F_{h}(\lambda,u_{h})\equiv u_{h}+\lambda T_{h}G_{h}(u_{h})=0,\]

where \(u_{h}=(\mathbf{curl}\,\psi_{h},\omega_{h})\) and \(\lambda=1/v\). Note that \(F_{h}\) maps \(\lambda\times X_{h}\) into \(V_{h}\).

### Error Analysis of the Upwind Scheme

Before applying the material of Section 3.4 to establish the convergence of (5.18), let us prove some important properties of the form \(\tilde{a}(.;\,.\,,.)\). The reader will find that this form is not as hard to manipulate as it would seem at first sight. First,
