Now, in order to apply Theorem 4.3, we need here to check the assumption (4.31), namely:

(5.30) \[\left\{\begin{aligned} & 2v\sum\limits_{i,j=1}^{N}\|D_{ij}( \mathbf{v})\|_{0,\,\Omega}^{2}+\,\|\operatorname{div}\mathbf{v}\|_{0,\,\Omega} ^{2}\\ &\geq\alpha_{0}|\mathbf{v}|_{1,\,\Omega}^{2}\quad\quad\forall \mathbf{v}\in H_{0}^{1}(\Omega)^{N},\quad\quad\alpha_{0}>0.\end{aligned}\right.\]

But Remark 5.1 establishes that

\[\sum\limits_{i,j=1}^{N}\left(D_{ij}(\mathbf{u}),D_{ij}(\phi)\right) =-(1/2)\{\langle\measuredangle A\mathbf{u},\phi\rangle+\langle\mathbf{ grad}(\operatorname{div}\mathbf{u}),\phi\rangle\}\] \[=(1/2)\{\langle\mathbf{grad}\mathbf{u},\mathbf{grad}\phi\rangle+( \operatorname{div}\mathbf{u},\operatorname{div}\phi)\rangle\]

for all \(\mathbf{u}\in H^{1}(\Omega)^{N}\), for all \(\phi\in\mathcal{D}(\Omega)^{N}\). Hence

(5.31) \[2v\sum\limits_{i,j=1}^{N}\|D_{ij}(\mathbf{v})\|_{0,\,\Omega}^{2}=v(|\mathbf{ v}|_{1,\,\Omega}^{2}+\|\operatorname{div}\mathbf{v}\|_{0,\,\Omega}^{2}).\]

Therefore the analogue of Theorem 5.3 holds in that case.

_Remark 5.5_.: The inequality (5.31) is also related to the classical _Korn's Inequality_:

(5.31') \[\sum\limits_{i,j=1}^{N}\|D_{ij}(\mathbf{v})\|_{0,\,\Omega}^{2}+\,\|\mathbf{v} \|_{0,\,\Omega}^{2}\geq\alpha_{1}\|\mathbf{v}\|_{1,\,\Omega}^{2}\quad\quad \forall\mathbf{v}\in H^{1}(\Omega)^{N},\quad\,x_{1}>0.\]

For the sake of completeness, here is a concise proof of (5.31') given by Duvaut & Lions [26] in the case of a bounded, Lipschitz-continuous open subset of \(\mathbb{R}^{N}\).

Observe that formally the following identity holds:

\[\frac{\partial^{2}v_{i}}{\partial x_{j}\partial x_{k}}=\frac{\partial(D_{ik}( \mathbf{v}))}{\partial x_{j}}+\frac{\partial(D_{ij}(\mathbf{v}))}{\partial x _{k}}-\frac{\partial(D_{jk}(\mathbf{v}))}{\partial x_{i}},\quad\,1\leq i,j,\, k\leq N.\]

Hence for \(\mathbf{v}\) in \(H^{1}(\Omega)^{N}\) we have

\[\|\mathbf{grad}(\partial v_{i}/\partial x_{j})\|_{-1,\,\Omega} \leq C_{1}\sum\limits_{i,j=1}^{N}\|\mathbf{grad}(D_{ij}(\mathbf{v}) )\|_{-1,\,\Omega}\] \[\leq C_{2}\sum\limits_{i,j=1}^{N}\|D_{ij}(\mathbf{v})\|_{0,\, \Omega}.\]

Therefore, applying Theorem 2.2 to \(\mathbf{grad}\,v_{i}\) yields immediately (5.31).

Now, let us turn to the gradient methods to solve Problem (5.12). Again, we take

\[c(p,q)=(p,q),\]

so that

\[a_{r}(\mathbf{u},\mathbf{v})=v(\mathbf{grad}\,\mathbf{u},\mathbf{grad}\, \mathbf{v})+r(\operatorname{div}\mathbf{u},\operatorname{div}\mathbf{v})\]

which is clearly elliptic on \(H_{0}^{1}(\Omega)^{N}\). Thus, defining \(\mathbf{u}_{r}(q)\) by:
