Finally, if \(v\) is an arbitrary element of \(S(\tilde{u}_{h};\alpha)\), we can write

\[v-u_{h} =[D_{u}F_{h}(\lambda,\tilde{u}_{h})]^{-1}[D_{u}F_{h}(\lambda,\tilde{u }_{h})\cdot(v-u_{h})\] (3.24) \[\quad-(F_{h}(\lambda,v)-F_{h}(\lambda,u_{h}))+F_{h}(\lambda,v)]\] \[=[D_{u}F_{h}(\lambda,\tilde{u}_{h})]^{-1}\Bigg{[}\int_{0}^{1} \left\{D_{u}F_{h}(\lambda,\tilde{u}_{h})\right.\] \[\quad-\left.D_{u}F_{h}(\lambda,u_{h}+\left.\theta(v-u_{h})\right) \cdot(v-u_{h})\,d\theta+F_{h}(\lambda,v)\right]\!\!.\]

Hence

\[\left\|\,v-u_{h}\,\right\|_{X}\leqslant\gamma_{h}(\lambda)\{L_{h}(\lambda; \alpha)\left\|\,v-u_{h}\,\right\|_{X}+\left.\left\|\,F_{h}(\lambda,v)\right\| _{\mathcal{X}}\},\]

thus proving (3.23). 

Now we allow \(\lambda\) to vary in the compact interval \(\Lambda\). We replace the fixed element \(\tilde{u}_{h}\) by a \(\mathcal{C}^{0}\)-mapping \(\lambda\to\tilde{u}_{h}(\lambda)\): \(\Lambda\to X\). The following lemma generalizes Lemma 3.3.

**Lemma 3.4**.: _Under the condition_:__

(3.25) \[\lim_{h\to 0}\sup_{\lambda\in\Lambda}\mu_{h}(\lambda)=0,\]

_there exists a real \(h_{0}>0\) such that for all \(\lambda\in\Lambda\) and all \(h\leqslant h_{0}\), \(D_{u}F_{h}(\lambda,\tilde{u}_{h}(\lambda))\) is an isomorphism of \(X\) onto \(\mathcal{X}\) and we have the bound:_

(3.26) \[\gamma_{h}(\lambda)=\left\|\,[D_{u}F_{h}(\lambda,\tilde{u}_{h}(\lambda))]^{-1 }\,\right\|_{\mathcal{L}(\mathcal{X};\lambda)}\leqslant 2\gamma(\lambda).\]

Proof.: Since \(\Lambda\) is compact, the function \(\gamma(\lambda)\) is bounded above on \(\Lambda\). Therefore (3.25) implies that for some \(h_{0}>0\), we have

\[\sup_{\lambda\in\Lambda}\left\{\gamma(\lambda)\mu_{h}(\lambda)\right\} \leqslant 1/2\,\,\,\,\,\,\,\,\,\,\,\forall h\leqslant h_{0}.\]

Hence Lemma 3.3 asserts that \(D_{u}F_{h}(\lambda,\tilde{u}_{h}(\lambda))\) is an isomorphism of \(X\) onto \(\mathcal{X}\) for all \(\lambda\in\Lambda\) and all \(h\leqslant h_{0}\). Moreover the bound (3.16) yields directly (3.26). 

Combined with Theorem 3.1, this lemma shows that Problem (3.12) has a unique branch of nonsingular solutions in a neighborhood of \(\tilde{u}_{h}\).

**Theorem 3.2**.: _Let \(\{(\lambda,u(\lambda));\lambda\in\Lambda\}\) be a branch of nonsingular solutions of (3.1) and let \(\lambda\to\tilde{u}_{h}(\lambda)\) be a given function in \(\mathcal{C}^{0}(\Lambda;X)\) that satisfies_

\[\limsup_{h\to 0}\sup_{\lambda\in\Lambda}\mu_{h}(\lambda)=0.\]

_If, besides that,_
