Let us put \(\rho=\inf_{m}\rho^{m}\); according to (4.63), \(\rho>0\). Therefore,

(4.65) \[c(v^{m})\leqslant\theta^{m}c(v^{0}),\ \ \ \ \ 0\leqslant\theta=1-(\alpha_{r}/ \tilde{\alpha}_{r})(\rho\delta\beta^{2})/(\|\,c\,\|\,\|\,a_{r}\|^{2})<1.\]

Hence the sequence \((c(v^{m}))\) converges to zero and

\[\lim_{m^{-\infty}}\|\,\lambda^{m}-\lambda\|_{M}=0.\]

In turn, this implies the convergence of \((u^{m})\). 

_Remark 4.7_.: We infer from (4.65) that each iteration reduces the norm of the error: \((c(v^{m}))^{1/2}\) by a factor which is at least \(\theta^{1/2}<1\). Therefore, the convergence of the iterative method (4.54') (4.56) is linear.

_Remark 4.8_.: The simple gradient algorithm with constant parameter \(\rho\) instead of \(\rho^{m}\) is also widely used. Of course, fixing \(\rho\) once and for all reduces the volume of computation, but this also reduces the rate of convergence of the method. Both theoretical and practical arguments lead us to choose \(r\) and \(\rho\) according to the following criteria:

i) take \(r\) as large as possible, for the conditioning of \(A\), increases with \(r\);

ii) take

\[\rho=(r\gamma^{2})/\|\,c\,\|^{2}.\]

Indeed, we have

\[\langle C^{-1}\chi,\chi\rangle\geqslant(\gamma/\|\,c\,\|^{2})\|\,\chi\|_{M}^{ 2};\]

when \(a(.,.)\) is semi-positive definite on \(X\) (cf. (4.16)), this implies:

\[a_{r}(v,v)\geqslant r\langle C^{-1}Bv,Bv\rangle\geqslant(\gamma r/\|\,c\,\|^{2 })\|\,Bv\,\|_{M}^{2},\]

whence

\[\tilde{\alpha}_{r}\geqslant\gamma r/\|\,c\,\|^{2}.\]

Therefore the above \(\rho\) satisfies (4.63).

More specifically, when \(M=M\)' and \(C=\mathrm{Id}\), we can take \(\rho=r\).

Now, we turn to the _conjugate-gradient method_. Instead of updating \(\lambda^{m}\) along the direction of the gradient (i.e. along the direction of steepest descent) like in (4.61), we propose the conjugate direction to that of the preceding descent with respect to the hypersurface \(K_{r}=\mathrm{constant}\). This amounts to take:

(4.66) \[\omega^{m}=g^{m}+\sigma^{m}\omega^{m-1},\]

where the real parameter \(\sigma^{m}\) is chosen so that

\[D^{2}K_{r}\cdot(\omega^{m},\omega^{m-1})=0\]
