(3.8) \[\mathbf{v}=\mathbf{grad}\,q\,+\,\mathbf{curl}\,\phi,\]

_where \(q\in H^{1}(\Omega)/\mathbb{R}\) is the only solution of_

(3.9) \[(\mathbf{grad}\,q,\mathbf{grad}\,\mu)=(\mathbf{v},\mathbf{grad}\,\mu)\quad\quad \forall\mu\in H^{1}(\Omega),\]

_and \(\phi\in\Phi\) is the only solution of_

(3.10) \[(\mathbf{curl}\,\phi,\mathbf{curl}\,\chi)=(\mathbf{v}-\mathbf{grad}\,q, \mathbf{curl}\,\chi)\quad\quad\forall\chi\in\Phi.\]

Proof.: For \(\mathbf{v}\in L^{2}(\Omega)^{2}\), the Neumann's problem (3.9) has a unique solution \(q\in H^{1}(\Omega)/\mathbb{R}\). This solution \(q\) satisfies

\[\Delta q=\operatorname{div}\mathbf{v}\quad\text{in }H^{-1}(\Omega).\]

Hence \(\mathbf{v}-\mathbf{grad}\,q\) is a divergence-free vector of \(H(\operatorname{div};\Omega)\). Moreover, Green's formula (2.17) applied to (3.9) yields

\[0=(\mathbf{v}-\mathbf{grad}\,q,\mathbf{grad}\,\mu)=\zeta(\mathbf{v}-\mathbf{ grad}\,q)\cdot\mathbf{n},\mu)_{\Gamma}\quad\quad\forall\mu\in H^{1}(\Omega),\]

implying that \((\mathbf{v}-\mathbf{grad}\,q)\cdot\mathbf{n}=0\) in \(H^{-1/2}(\Gamma)\). In other words, \(\mathbf{v}-\mathbf{grad}\,q\in H\). Thus, we infer from Corollary 3.1 that there exists a unique function \(\phi\in\Phi\) verifying (3.8) and (3.10). 

_Remark 3.2_.: When \(\mathbf{v}\in H(\operatorname{div};\Omega)\), problem (3.9) has the following interpretation:

\[\begin{cases}\quad\Delta q=\operatorname{div}\mathbf{v}&\text{in }\Omega,\\ \partial q/\partial n=\mathbf{v}\cdot\mathbf{n}&\text{on }\Gamma.\end{cases}\]

If \(\mathbf{v}\) belongs only to \(L^{2}(\Omega)^{2}\), the last equality is formal.

The techniques of this section provide a straightforward extension of Lemma 2.2 to smoother functions.

**Lemma 3.2**.: _Let \(\Omega\) be a bounded and connected domain of \(\mathbb{R}^{2}\), with a boundary \(\Gamma\) of class \(\mathcal{C}^{m,\,1}\)\((m\geqslant 2)\), and let \(\mathbf{g}\) be given in \(H^{m-1/2}(\Gamma)^{2}\) with_

\[\int_{\Gamma}\mathbf{g}\cdot\mathbf{n}\,ds=0.\]

_Then, there exists \(\mathbf{u}=f(\mathbf{g})\) in \(H^{m}(\Omega)^{2}\) such that_

\[\operatorname{div}\mathbf{u}=0\quad\text{in }\Omega,\quad \mathbf{u}=\mathbf{g}\quad\text{on }\Gamma,\] \[\|\mathbf{u}\|_{m,\Omega}\leqslant C\,\|\mathbf{g}\|_{m-1/2,\, \Gamma}.\]

Proof.: Let us sketch the proof. The condition \(\mathbf{u}=\mathbf{g}\) on \(\Gamma\) can be split into \(\mathbf{u}\cdot\mathbf{n}=\mathbf{g}\cdot\mathbf{n}\) and \(\mathbf{u}\cdot\tau=\mathbf{g}\cdot\tau\) on \(\Gamma\): As it is simpler to prescribe each condition separately, we propose a function \(\mathbf{u}\) of the form

\[\mathbf{u}=\mathbf{grad}\,q\,+\,\mathbf{curl}\,\phi.\]
