Proof.: As mentioned above, Lemma 3.5 implies that

\[\int_{\hat{\kappa}}[\partial(\hat{\phi}-\hat{I}\hat{\phi})/\partial \hat{x}_{i}][\partial\hat{\mu}/\partial\hat{x}_{i}]\,d\hat{x}\] \[\quad=[1/(l+1)!]\!\left[\int_{\hat{\kappa}}\partial^{l+1}\hat{ \phi}/\partial\hat{x}_{i}^{l+1}\,d\hat{x}\right]\!\left[\int_{\hat{\kappa}}( \partial\omega_{i}/\partial\hat{x}_{i})(\partial\hat{\mu}/\partial\hat{x}_{i} )\,d\hat{x}\right]+\,E_{i}\]

where the remainder term \(E_{i}\) is bounded by

\[|E_{i}| \leqslant C_{1}|\hat{\phi}|_{l+2,\,\hat{\kappa}}|\hat{\mu}|_{1,\, \hat{\kappa}}\leqslant C_{2}|\hat{\phi}|_{l+2,\,\hat{\kappa}}\,\|\hat{\mu}\|_{ 0,\,\hat{\kappa}}\] \[\leqslant C_{3}\sigma_{\kappa}^{2}h_{\kappa}^{l}\,\|\phi\|_{l+2, \,\kappa}\,\|\,\mu_{\hbar}\|_{0,\,\kappa}\]

by virtue of (3.23) and (A.45).

Now, a simple integration by parts shows that

\[\int_{\hat{\kappa}}(\partial\omega_{i}/\partial\hat{x}_{i})(\partial\hat{\mu }/\partial\hat{x}_{i})\,d\hat{x}=0\]

because \(\omega_{i}\hat{n}_{i}\) vanishes on the boundary of \(\hat{\kappa}\) (\(\hat{n}_{i}\) is the \(i^{\text{th}}\)-component of the normal \(\hat{\mathbf{n}}\) to \(\hat{\kappa}\)) and the integrand \(\omega_{i}\partial^{2}\hat{\mu}/\partial\hat{x}_{i}^{2}\) is a polynomial of \(Q_{2l-1}\) which vanishes on the set \(\{\alpha_{\kappa}\}\). This proves (3.26). 

This lemma takes care of the first two terms in (3.25). But the third and fourth terms which involve

\[[\partial(\hat{\phi}-\hat{I}\hat{\phi})/\partial\hat{x}_{i}][\partial\hat{\mu }/\partial\hat{x}_{j}]\]

with \(i\neq j\) are not so amenable, as can be seen by inspecting \(R(\hat{\phi})\). Indeed, the argument of Lemma 3.8 leads to the integral of polynomials of \(Q_{2l}\), whereas the Gauss-Lobatto formula is only exact for polynomials of degree \(2l-1\). So the particular choice of points \(\{\alpha_{\kappa}\}\) is of no avail here.

Let us examine closely \(\hat{\jmath}_{\hat{\kappa}}[\partial(\hat{\phi}-\hat{I}\hat{\phi})/\partial \hat{x}_{i}][\partial\hat{\mu}/\partial\hat{x}_{j}]\,d\hat{x}\). To get rid of the derivative of \(\hat{\mu}\) we integrate by parts with respect to \(\hat{x}_{j}\). Applying again Lemma 3.5 and using the fact that

\[\partial^{2}\,R(\hat{\phi})/\partial\hat{x}_{i}\partial\hat{x}_{j}=0\quad \text{for $i\neq j$}\]

we obtain:

\[\int_{\hat{\kappa}}[\partial(\hat{\phi}-\hat{I}\hat{\phi})/\partial\hat{x}_{i} ][\partial\hat{\mu}/\partial\hat{x}_{j}]\,d\hat{x}=\int_{\partial\hat{\kappa}} [\partial(\hat{\phi}-\hat{I}\hat{\phi})/\partial\hat{x}_{i}]\,\hat{n}_{j}\hat{ \mu}\,d\hat{s}+\,E_{j}\]

where

(3.27) \[|E_{j}|\leqslant C_{1}\sigma_{\kappa}^{2}h_{\kappa}^{l}\,\|\,\phi\|_{l+2,\, \kappa}\,\|\,\mu_{\hbar}\|_{0,\,\kappa}.\]

But for \(i\neq j\), the inverse image on \(\kappa\) of \([\partial(\hat{\phi}-\hat{I}\hat{\phi})/\partial\hat{x}_{i}]\,\hat{n}_{j}\hat{\mu}\) is continuous (but with opposite signs) across interelement boundaries and vanishes on \(\Gamma\). In addition, Theorem A.3 and Lemma A.9 give only:
