### Higher-Order Approximation on Triangular Elements

The finite element spaces discussed in this section were introduced by Crouzeix & Raviart [23] and Mansfield [56]. They are a direct generalization of the space \(\mathcal{P}_{1}(\kappa)\). The reader will perhaps find them easy to grasp, but originally their analysis was far from trivial on account of the inf-sup condition. Fortunately, the material of Section 1.4 has considerably reduced this difficulty.

In this section, we assume that \(\Omega\) is a _bounded_, _plane polygon_. Let us fix an integer \(l\geqslant 2\). Let \(\mathcal{T}_{h}\) be a triangulation of \(\overline{\Omega}\) and let \(\kappa\) be any triangle of \(\mathcal{T}_{h}\). Here again, we want to construct velocities with components that are polynomials of degree \(l+1\) and tangential components of degree \(l\) on each side of \(\kappa\). But now, the higher degree of polynomials provide a simple answer to this problem for it suffices that all terms of degree \(l+1\) vanish on the sides of \(\kappa\); in other words they must have the common factor \(\lambda_{1}\lambda_{2}\lambda_{3}\). More precisely, let us denote by \(\bar{P}_{k}\) the space of homogeneous polynomials of degree \(k\):

\[\bar{P}_{k}=\operatorname{span}\{x_{1}^{i}x_{2}^{k-i};\,0\leqslant i\leqslant k\}.\]

Then we take the velocities \(\mathbf{w}\) in the polynomial subspace of \(P_{l+1}^{2}\):

\[\mathcal{P}_{l}(\kappa)=[P_{l}\oplus\{\lambda_{1}\lambda_{2}\lambda_{3}\bar{P }_{l-2}\}]^{2}\] (2.16)

and the pressures \(q\) in \(P_{l-1}\). This leads to the following choice of spaces:

\[\begin{cases}W_{h}=\{\mathbf{w}\!\in\!\mathcal{C}^{0}(\bar{\Omega})^{2};\, \mathbf{w}|_{\kappa}\!\in\!\mathcal{P}_{l}(\kappa)\quad\forall\kappa\!\in\! \mathcal{T}_{h}\},\\ \qquad\qquad X_{h}=W_{h}\cap H_{0}^{1}(\Omega)^{2},\end{cases}\] (2.17) \[\begin{cases}Q_{h}=\{q\!\in\!L^{2}(\Omega);\,q|_{\kappa}\!\in\!P_{ l-1}\quad\forall\kappa\!\in\!\mathcal{T}_{h}\},\\ \qquad\qquad M_{h}=Q_{h}\cap L_{0}^{2}(\Omega).\end{cases}\] (2.18)

The choice of degrees of freedom for the velocities \(\mathbf{w}\) is no longer dictated by the fulfillment of the inf-sup condition. Therefore we can simply take the values of \(\mathbf{w}\) associated with \(P_{l}\) on the sides of \(\kappa\) and the derivatives corresponding to \(P_{l-2}\) at the center of \(\kappa\), i.e.:

\[\begin{cases}\text{(a)}\,\,\mathbf{w}(a)\text{ on all points $a$ of $\Sigma_{\kappa}\!\cap f_{i}$, $1\leqslant i\leqslant 3$, where $\Sigma_{\kappa}$ denotes the principal lattice of order $l$ (cf. (\ref{eq:w})),}\\ \text{(b)}\,\,\partial^{k}\mathbf{w}(a_{\kappa})/\partial x_{1}^{i}\partial x _{2}^{k-i}\text{ on the center $a_{\kappa}$ of $\kappa$, $0\leqslant i\leqslant k$, $0\leqslant k \leqslant l-2$.}\end{cases}\] (2.19)

From a theoretical point of view, derivatives are seldom an attractive choice because they require a lot of regularity; they can be replaced by the interior moments:

\[\int_{\kappa}\mathbf{w}\!\cdot\!\mathbf{q}\,dx\quad\quad\forall\mathbf{q}\! \in\!P_{l-2}^{2}.\] (2.19)

In particular, when \(l=2\), (2.19a) (2.19b) or (2.19c) become:
