(4.25) \[\left\{\begin{aligned} &\sup_{\lambda\in A}\left\{|\mathbf{u}_{h}( \lambda)-\mathbf{u}(\lambda)|_{1,\,\alpha}+\,\|\,p_{h}(\lambda)-p(\lambda)\|_{0, \,\alpha}\right\}\leqslant Ch^{2/s}|\ln h|^{1-2/s}\\ &\sup_{\lambda\in A}|\mu_{h}(\lambda)|_{1,\,\alpha,\,\Omega} \leqslant C(\alpha)h^{2/s}|\ln h|^{1-2/s}\ \ \ \ \ \forall\alpha\geqslant 2,\end{aligned}\right.\]

\(1/r+1/s=1\), with constants independent of \(h\) and \(\lambda\).

Besides that, if the mapping \(\lambda\to(\mathbf{u}(\lambda),p(\lambda))\) is continuous from \(\Lambda\) into \(H^{m+1}(\Omega)^{2}\times H^{m}(\Omega)\) for \(m=1\) or \(2\), we have the estimate:

(4.26) \[|\mathbf{u}_{h}(\lambda)-\mathbf{u}(\lambda)|_{1,\,\Omega}+\,\|p_{h}(\lambda) -p(\lambda)\|_{0,\,\Omega}+|\mu_{h}(\lambda)|_{1,\,\alpha,\,\Omega}\leqslant Kh ^{m}\]

for all \(\lambda\in\Lambda\).

Remark 4.5: It is not yet known whether or not a more accurate \(L^{2}\)-estimate can be obtained for \(\mathbf{u}-\mathbf{u}_{h}+\mathbf{grad}\,\mu_{h}\), as it is done in Theorem II.4.6 for the Stokes problem. The delicate point is that the proof of Theorem II.4.6 uses explicitly the equality:

\[\Delta p=\operatorname{div}\mathbf{f}\]

which is valid for every Stokes system but is obviously not true for Navier-Stokes equations.

### Mixed Incompressible Methods: the "Stream Function-Vorticity" Formulation

In this section, we investigate exclusively the two-dimensional case. (As mentioned at the beginning of this paragraph, the corresponding analysis of mixed incompressible schemes in three dimensions is still an open problem). We propose to extend to the Navier-Stokes equations the mixed formulation introduced in Section III.2.1. To begin with, recall the stream function-vorticity formulation of the Stokes operator.

Let us _fix_ a real \(s\geqslant 4\) and let \(r\) be its dual exponent:

\[1/r+1/s=1.\]

Define the space of stream functions:

\[\Phi=\{\chi\in H^{1}(\Omega);\,\chi|_{\Gamma_{0}}=0,\,\chi|_{\Gamma_{i}}= \text{a constant }c_{i},\,1\leqslant i\leqslant p\}\]

where as usual \(\Gamma_{0}\), ..., \(\Gamma_{p}\) denote the connected components of the boundary \(\Gamma\) with exterior component \(\Gamma_{0}\) (cf. Figure 2). We know that the operator **curl** is an isomorphism from

(4.27) \[\Phi_{s}=\Phi\cap W^{1,s}(\Omega)\]

onto

\[H\cap L^{s}(\Omega)^{2}=\{\mathbf{v}\in L^{s}(\Omega)^{2};\,\operatorname{div }\mathbf{v}=0,\,\mathbf{v}\boldsymbol{\cdot}\,\mathbf{n}|_{\Gamma}=\mathbf{0}\}.\]
