Thus in both cases the form \(a(.,.)\) is \(X\)-elliptic. Therefore Theorem 1.1 implies that Problem (1.39) has a unique solution \((\textbf{u}_{h},p_{h})\!\in\!X_{h}\times M_{h}\), where \(\textbf{u}_{h}\) is the unique solution of Problem (1.40), and we have:

(1.47) \[|\textbf{u}-\textbf{u}_{h}|_{1,\,\Omega}+\|\,p-p_{h}\|_{0,\,\Omega}\leq C_{1} \left\{\inf_{\textbf{v}_{h}\in\,X_{h}}|\textbf{u}-\textbf{v}_{h}|_{1,\,\Omega} +\inf_{q_{h}\in\,M_{h}}\|\,p-q_{h}\|_{0,\,\Omega}\right\}\]

with a constant \(C_{1}\) independent of \(h\).

Now, observe that if \(s_{h}\) does not map \(L^{2}_{0}(\Omega)\) onto \(M_{h}\) we can replace it by:

\[\overline{s_{h}}q=s_{h}q-\frac{1}{\text{meas}(\Omega)}\!\int_{\Omega}s_{h}q\, dx;\]

then \(\overline{s}_{h}\!\in\!\mathcal{L}(L^{2}(\Omega);M_{h})\) and \(\|\,\overline{s}_{h}q-q\,\|_{0,\,\Omega}\leqslant\|\,s_{h}q-q\,\|_{0,\,\Omega }\)\(\forall q\!\in\!L^{2}_{0}(\Omega)\). Thus if \(p\!\in\!H^{m}(\Omega)\cap L^{2}_{0}(\Omega)\), Hypothesis H2 gives:

\[\inf_{q_{h}\in\,M_{h}}\|\,p-q_{h}\|_{0,\,\Omega}\leqslant\|\,p-s_{h}p\|_{0,\, \Omega}\leqslant C_{2}h^{m}\|\,p\,\|_{m,\,\Omega}.\]

Likewise, if \(\textbf{u}\!\in\!H^{m+1}(\Omega)^{N}\cap V\), Hypothesis H1 yields:

\[\inf_{\textbf{v}_{h}\in\,X_{h}}|\textbf{u}-\textbf{v}_{h}|_{1,\,\Omega} \leqslant|\textbf{u}-r_{h}\textbf{u}|_{1,\,\Omega}\leqslant C_{3}h^{m}\| \,\textbf{u}\|_{m+1,\,\Omega}.\]

These inequalities and (1.47) imply (1.46).

It remains to establish the limit (1.45). For this we make use of Corollary 1.2 and the above considerations. We know that \(H^{2}(\Omega)\cap H^{1}_{0}(\Omega)\) is dense in \(H^{1}_{0}(\Omega)\) and that \(H^{1}(\Omega)\cap L^{2}_{0}(\Omega)\) is dense in \(L^{2}_{0}(\Omega)\). Hence it suffices to work with the above operators \(r_{h}\) and \(s_{h}\) to obtain (1.45). 

Of course, (1.46) implies that \(\|\,\textbf{u}-\textbf{u}_{h}\|_{0,\,\Omega}=O(h^{m})\), but it is possible to refine this estimate by making use of Theorem 1.2. Here we take

\[H=L^{2}(\Omega)^{N}.\]

Then Problem (1.21) is the homogeneous Stokes Problem:

(1.48) \[\left\{\begin{aligned} &\text{Find a pair $(\varphi,\xi)$ in $H^{1}_{0}(\Omega)^{N}\times L^{2}_{0}(\Omega)$ such that}:\\ &-\nu A\varphi\,+\,\textbf{grad}\,\xi=\textbf{g}\\ &\text{div}\,\varphi=0\end{aligned}\right\}\quad\text{ in $\Omega$, where $\textbf{g}\!\in\!L^{2}(\Omega)^{N}$.}\]

We shall require below the following concept of regularity for this problem.

**Definition 1.1**.: We say that Problem (1.48) is _regular_ if the mapping

\[(\varphi,\xi)\mapsto-\nu A\varphi\,+\,\textbf{grad}\,\xi\]

is an _isomorphism_ from \([H^{2}(\Omega)^{N}\cap V]\times[H^{1}(\Omega)\cap L^{2}_{0}(\Omega)]\) onto \(L^{2}(\Omega)^{N}\).

This definition means that \(\varphi\) belongs to \(H^{2}(\Omega)^{N}\) and \(\xi\) to \(H^{1}(\Omega)\) whenever the right-hand side **g** belongs to \(L^{2}(\Omega)^{N}\) and

(1.49) \[\|\varphi\|_{2,\,\Omega}+\|\,\xi\|_{1,\,\Omega}\leqslant C\,\|\,\textbf{g}\|_ {0,\,\Omega}.\]
