(4.13) \[\begin{split}&\begin{split}& v\sum\limits_{\kappa\in\, \mathcal{T}_{n}}\int\limits_{\kappa}\sigma_{ij}\partial^{2}\phi/\partial x_{i} \partial x_{j}\,dx-v\int_{\Gamma_{h}}M_{n}(\sigma)S(\partial\phi/\partial n)\, ds\\ &\quad=\int_{\Omega}\mathbf{f}\cdot\mathbf{curl}\,\phi\,dx\quad \quad\forall\phi\in\widetilde{\mathcal{V}},\\ &\begin{split}&\int_{\Omega}\sigma_{ij}\tau_{ij}\,dx- \biggl{\{}\sum\limits_{\kappa\in\,\mathcal{T}_{n}}\biggl{[}\tau_{ij}\partial^ {2}\psi/\partial x_{i}\partial x_{j}\,dx-\int_{\Gamma_{h}}M_{n}(\tau)S( \partial\psi/\partial n)\,ds\biggr{\}}\\ &\quad=0\quad\quad\forall\tau\in\mathcal{L}.\end{split}\end{split}\]

Here again, it is possible to express (4.13) by means of two bilinear forms \(a_{h}(.,.)\) and \(b_{h}(.,.)\):

(4.14) \[a_{h}(\sigma,\tau)=\int_{\Omega}\sigma_{ij}\tau_{ij}\,dx\quad\quad\text{\rm{tensors $\sigma$ and $\tau$ in $L^{2}(\Omega)^{4}$}},\]

(4.15) \[b_{h}(\tau,\phi)=-\sum\limits_{\kappa\in\,\mathcal{T}_{h}}\biggl{[}\tau_{ij} \partial^{2}\phi/\partial x_{i}\partial x_{j}\,dx+\int_{\Gamma_{h}}M_{n}(\tau)S (\partial\phi/\partial n)\,ds\]

\[\forall\tau\in\mathcal{L},\quad\quad\forall\phi\in H^{1}(\Omega)\quad\text{\rm{ with $\phi|_{\kappa}\in H^{2}(\kappa)$}}.\]

Then Problem (4.13) reads:

_Find a pair \((\sigma,\psi)\in\mathcal{L}\,\times\,\widetilde{\mathcal{V}}\) such that_:

(4.13') \[\begin{split}&\begin{cases}b_{h}(\sigma,\phi)=-(1/v)(\mathbf{f}, \mathbf{curl}\,\phi)\quad\quad\forall\phi\in\widetilde{\mathcal{V}},\\ & a_{h}(\sigma,\tau)+b_{h}(\tau,\psi)=0\quad\quad\forall\tau\in \mathcal{L}.\end{cases}\end{split}\]

Note the analogy with Problems (2.48) and (2.48') of Section 2.3. Observe also that when \(\tau\) belongs to \(\mathcal{L}\cap H^{1}(\Omega)^{4}\) and \(\phi\) belongs to \(\widetilde{\mathcal{V}},b_{h}(\tau,\phi)\) reduces to:

(4.16) \[b_{h}(\tau,\phi)=\int_{\Omega}(\partial\tau_{ij}/\partial x_{j})(\partial\phi /\partial x_{i})\,dx,\]

a property which is similar to (2.51a).

The following theorem summarizes the results of this section.

**Theorem 4.1**.: _Let \(\Omega\) be a bounded plane polygon and \(\mathcal{T}_{h}\) a triangulation of \(\bar{\Omega}\). Suppose that the solution \((\mathbf{u}=\mathbf{curl}\,\psi,p)\) of the Stokes problem (2.1) has the regularity:_

\[\mathbf{u}\in(H^{2}(\Omega)\cap H^{1}_{0}(\Omega))^{2},\quad\quad p\in H^{1}( \Omega)\cap L^{2}_{0}(\Omega).\]

_Then_

\(1^{\circ})\) _the triple \((\mathbf{u},(\lambda_{ij}=\partial u_{i}/\partial x_{j}),p)\) is the unique solution of Problem (4.8);_

\(2^{\circ})\) _the pair \(((\sigma_{ij}=\partial^{2}\psi/\partial x_{i}\partial x_{j}),\psi)\) is the unique solution of Problem (4.13)._

In the next section, we shall assume that:

(4.17) \[\mathbf{u}\in H^{2}(\Omega)^{2},\quad\quad p\in H^{1}(\Omega),\]

in order to be able to work with either Problem (4.8) or Problem (4.13).
