As far as the regularity of \(u\) is concerned, we know from the Lax & Milgram's Theorem that the mapping \(l\to u-u_{0}\) is an isomorphism from \(H^{-1}(\Omega)\) onto \(H^{1}_{0}(\Omega)\). Therefore,

\[\|u-u_{0}\|_{1,\Omega}\leqslant C_{2}\|l\|_{-1,\Omega}.\]

Clearly,

\[\|l\|_{-1,\Omega}\leqslant\|f\|_{-1,\Omega}+\|u_{0}\|_{1,\Omega}.\]

Hence

\[\|u\|_{1,\Omega}\leqslant C_{3}\{\,\|f\|_{-1,\Omega}+\|u_{0}\|_{1,\Omega}\} \hskip 14.226378pt\forall u_{0}\in H^{1}(\Omega)\hskip 14.226378pt\text{such that}\hskip 14.226378ptu_{0}=g \hskip 14.226378pt\text{on $\Gamma$}.\]

From definition (1.16) this implies that

\[\|u\|_{1,\Omega}\leqslant C_{3}\{\,\|f\|_{-1,\Omega}+\|g\|_{1/2,\Gamma}\}.\]

Thus, we have proved the following proposition:

**Proposition 1.1**.: _Problem_ (D) _has one and only one solution \(u\) in \(H^{1}(\Omega)\) and there exists a constant \(C=C(\Omega)\) such that_

(1.29) \[\|u\|_{1,\Omega}\leqslant C\{\,\|f\|_{-1,\Omega}+\|g\|_{1/2,\Gamma}\},\]

_i.e. \(u\) depends continuously upon the data of_ (D)_._

When \(f\) and \(g\) are more regular, it is natural to expect that the solution \(u\) of Problem (D) is also smoother. The next theorem states the precise regularity of \(u\). Its proof, which is far outside the scope of this book, can be found for example in Grisvard [42].

**Theorem 1.8**.: \(1^{\circ}\)_) Let \(\Omega\) be a bounded open subset of \(\mathbb{R}^{N}\) with a \(\mathcal{C}^{k+1,\,1}\) boundary \(\Gamma\) for some integer \(k\geqslant 0\). Suppose that the data \(f\) and \(g\) of Problem (1.25) (1.26) satisfy_

\[f\in W^{k,\,p}(\Omega),\hskip 14.226378ptg\in W^{k+2-1/p,\,p}(\Gamma)\]

_for some real \(p\) with \(1<p<\infty\). Then \(u\in W^{k+2,\,p}(\Omega)\) and there exists a constant \(C=C(k,p,\Omega)\) such that_

(1.30) \[\|u\|_{k+2,\,p,\Omega}\leqslant C\{\,\|f\|_{k,\,p,\,\Omega}+\|g\|_{k+2-1/p,\,p ,\,\Gamma}\}.\]

_\(2^{\circ}\)_) When \(\Omega\) is a two-dimensional bounded polygon with no reentrant corner, there exists a real \(p_{\Omega}>2\) depending on the greatest inner angle of \(\Gamma\) such that_

\[u\in W^{2,\,p}(\Omega),\hskip 14.226378pt1<p<p_{\Omega},\]

_whenever \(f\in L^{p}(\Omega)\) and \((g|_{\,\Gamma_{j}};\ 1\leqslant j\leqslant J)\in\prod_{j=1}^{J}W^{2-1/p,\,p}( \Gamma_{j})\) satisfies the matching conditions of Remark 1.1._

\(3^{\circ}\)_) If \(\Omega\) is a bounded, convex polyhedron in three dimensions, the conclusion of \(2^{\circ}\)) is still valid for the homogeneous Dirichlet problem_ (\(g=0\)).
