**Hypothesis H2**.: _Every vector field \(\mathbf{v}\in H^{1}_{0}(\Omega)^{2}\) has the following decomposition:_

\[\mathbf{v}=\mathbf{grad}\,q\,+\,\mathbf{curl}\,\phi\quad\text{with}\,\,\phi\in \varPhi_{s},\quad\,q\in W^{1,\,s}(\Omega)\cap L^{2}_{0}(\Omega)\]

_and_

(2.37) \[|P_{h}q-q|_{{}_{1,\,\beta,\,\Omega}}+\inf_{\phi_{h}\,\in\,\varPhi_{h}}|\phi_{h} -\phi|_{{}_{1,\,\beta,\,\Omega}}\leqslant Ch^{2/\beta}|\mathbf{v}|_{{}_{1,\, \beta}}\quad\,\,\,\,\forall\beta\in[2,s],\]

_with a constant \(C\) independent of \(h,\,\phi,\,q\) and \(\mathbf{v}\)._

**Theorem 2.7**.: _Let \(p\) and \(p_{h}\) denote the solutions of Problems_ (2.21) _and_ (2.36) _respectively. In addition to the assumptions of Theorem 2.6, suppose that Hypothesis H2 holds and \(p\in W^{1,\,a}(\Omega),\,\omega\in W^{1,\,a}(\Omega)\) for some \(real\,\alpha\in[r,2]\). Then the error on \(p\) is bounded as follows:_

(2.38) \[\begin{split}&\|\,p-p_{h}\|_{{}_{0,\,\Omega}}\leqslant C\, \biggl{\{}h^{2/\beta}\inf_{q_{h}\,\in\,\varPhi_{h}}|p-q_{h}|_{{}_{1,\,\alpha, \,\Omega}}+v\|\omega-\omega_{h}\|_{{}_{0,\,\Omega}}\\ &\quad\quad+\,v\inf_{\theta_{h}\,\in\,\varTheta_{h}}\,[hK_{2}(h) \,\|\,\omega_{h}-\theta_{h}\|_{{}_{0,\,\Omega}}+h^{2/\beta}|\theta_{h}-\omega| _{{}_{1,\,\alpha,\,\Omega}}]\biggr{\}},\end{split}\]

_with \(1/\alpha+1/\beta=1\)._

Proof.: As \(p-p_{h}\in L^{2}_{0}(\Omega)\), there exists \(\mathbf{v}\in H^{1}_{0}(\Omega)^{2}\) with

\[\operatorname{div}\mathbf{v}=p-p_{h},\quad\,|\mathbf{v}|_{{}_{1,\,\Omega}} \leqslant C\,\|\,p-p_{h}\|_{{}_{0,\,\Omega}}.\]

Hence by virtue of Hypothesis H2 we have:

\[\mathbf{v}=\mathbf{grad}\,q\,+\,\mathbf{curl}\,\phi,\]

\[\|\,p-p_{h}\|_{{}_{0,\,\Omega}}^{2}=-(\mathbf{grad}(p-p_{h}),\mathbf{v})=( \mathbf{grad}(p_{h}-p),\mathbf{grad}\,q).\]

Introducing \(P_{h}q\) we can write:

\[\|\,p-p_{h}\|_{{}_{0,\,\Omega}}^{2}=(\mathbf{grad}(q_{h}-p),\mathbf{grad}(q-P_ {h}q))+(\mathbf{grad}(p_{h}-p),\mathbf{grad}(P_{h}q))\]

\[\forall q_{h}\in Q_{h}.\]

Now (2.21) and (2.36) yield:

\[(\mathbf{grad}(p-p_{h}),\mathbf{grad}(P_{h}q))=\,v(\mathbf{curl}(\omega_{h}- \omega),\mathbf{grad}(P_{h}q)).\]

Thus taking any \(\phi_{h}\) in \(\varPhi_{h}\) and setting

\[\mathbf{v}_{h}=\mathbf{grad}(P_{h}q)+\mathbf{curl}\,\phi_{h},\]

we obtain in view of (2.20) and (2.29):

\[\begin{split}(\mathbf{grad}(p-p_{h}),\mathbf{grad}(P_{h}q))& =\,v(\mathbf{curl}(o_{h}-\omega),\mathbf{v}_{h}-\mathbf{curl}\, \phi_{h})\\ &=\,v(\mathbf{curl}(o_{h}-\omega),\mathbf{v}_{h}-\mathbf{v})+\,v( o_{h}-\omega,\operatorname{curl}\mathbf{v})\\ &=\,v(\mathbf{curl}(o_{h}-\theta_{h}),\mathbf{v}_{h}-\mathbf{v}) +\,v(\mathbf{curl}(\theta_{h}-\omega),\mathbf{v}_{h}-\mathbf{v})\\ &\quad\,+\,v(o_{h}-\omega,\operatorname{curl}\mathbf{v})\quad \quad\forall\theta_{h}\in\varPhi_{h},\quad\,\phi_{h}\in\varPhi_{h}.\end{split}\]
