As our fundamental example, let us show that the Dirichlet problem for the Navier-Stokes equations in the velocity-pressure formulation (2.20) fits into the above framework. We first set:

(3.5) \[X=\mathcal{X}=H^{1}(\Omega)^{N}\times L_{0}^{2}(\Omega),\]

and we introduce the intermediate space

(3.6) \[Y=H^{-1}(\Omega)^{N}\times\bigg{\{}\mathbf{g}\in H^{1/2}(\Gamma)^{N};\,\,\int_{ \Gamma_{i}}\mathbf{g}\cdot\mathbf{n}\,ds=0,\,0\leqslant i\leqslant p\bigg{\}}.\]

Next we define a linear operator \(T\) as follows: given \((\mathbf{f}_{\star},\mathbf{g}_{\star})\in Y,\) we denote by \((\mathbf{u}_{\star},p_{\star})=T(\mathbf{f}_{\star},\mathbf{g}_{\star})\in X\) the solution of the Dirichlet problem for the Stokes equations:

(3.7) \[\begin{Bmatrix}-\Delta\mathbf{u}_{\star}+\mathbf{grad}\,p_{\star}&=\mathbf{f}_ {\star}\\ \mathrm{div}\,\mathbf{u}_{\star}&=0\end{Bmatrix}\quad\text{in }\Omega,\]

Finally, with the data \((\mathbf{f},\mathbf{g})\in Y\) we associate a \(\mathcal{C}^{\infty}\)-mapping \(G\) from \(\mathbb{R}_{+}\times X\) into \(Y\) defined by

(3.8) \[G\colon(\lambda,v=(\mathbf{v},q))\to G(\lambda,v)=\bigg{(}\lambda\bigg{(} \sum\limits_{j=1}^{N}v_{j}\delta\mathbf{v}/\partial x_{j}-\mathbf{f}\bigg{)}, \,-\mathbf{g}\bigg{)}\]

and we set

(3.9) \[F(\lambda,v)=v\,+\,TG(\lambda,v).\]

Now we may state:

**Lemma 3.1**.: _The pair \((\mathbf{u},p)\in H^{1}(\Omega)^{N}\times L_{0}^{2}(\Omega)\) is a solution of Problem (2.1) (2.13) if and only if \(u=(\mathbf{u},p/v)\) is a solution of (3.1) where \(\lambda=1/v,\) the spaces \(X\) and \(\mathcal{X}\) are defined by (3.5) and the compound mapping \(F\) is defined by (3.9)._

Proof.: We observe that the equations (2.1) may be equivalently written in the form

\[-\Delta\mathbf{u}+\mathbf{grad}(p/v) =(1/v)\bigg{(}\mathbf{f}-\sum\limits_{j=1}^{N}u_{j}\partial \mathbf{u}/\partial x_{j}\bigg{)}\quad\text{in }\Omega,\] \[\mathrm{div}\,\mathbf{u}=0\quad\text{in }\Omega,\] \[\mathbf{u}=\mathbf{g}\quad\text{on }\Gamma;\]

or by (3.7)

\[(\mathbf{u},p/v)=T\bigg{[}(1/v)\bigg{(}\mathbf{f}-\sum\limits_{j=1}^{N}u_{j} \partial\mathbf{u}/\partial x_{j}\bigg{)},\mathbf{g}\bigg{]}.\]

Hence the lemma is established using (3.8) and (3.9).
