_for all \(v\in W^{k+1,\,p}(\kappa)\):_

\[|v-\pi v|_{m,\,q,\kappa}\leq C\sigma_{\kappa}^{m}(\mathrm{meas}(\kappa))^{1/q-1/p }h_{\kappa}^{k+1-m}|v|_{k+1,\,p,\kappa}.\] (144)

We shall assume henceforth that the _dimension \(N\) equals two_, although some results will be stated in the \(N\)-dimensional case. In addition, to simplify the discussion we shall assume that \(\Omega\) is a bounded domain with a _polygonal_ boundary \(\Gamma\). The technical difficulties inherent to curved boundaries can be conveniently handled with the general elements introduced by Bernardi [9], but there is no space to discuss them here.

For each \(h>0\), let \(\mathcal{T}_{h}\) be a _triangulation of \(\bar{\Omega}\)_ made of _closed_ triangles \(\kappa\) with diameters bounded by \(h\). In other words,

\[\bar{\Omega}=\bigcup_{\kappa\in\mathcal{T}_{h}}\kappa,\ \ \ \ \ h_{\kappa} \leq h,\]

where any two triangles are either disjoint or share exactly either one side or one vertex.

**Definitions A.2**.: \(1^{\circ}\)) A family \(\mathcal{T}_{h}\) of triangulations of \(\bar{\Omega}\) is said to be regular as \(h\) tends to zero if there exists a number \(\sigma>0\), independent of \(h\) and \(\kappa\), such that

\[\sigma_{\kappa}\leq\sigma\ \ \ \ \ \forall\kappa\in\mathcal{T}_{h}.\] (145)

\(2^{\circ}\)) In addition, \(\mathcal{T}_{h}\) is said to be uniformly regular (or quasi-uniform) as \(h\) tends to zero if there exists another constant \(\tau>0\) such that

\[\tau h\leq h_{\kappa}\leq\sigma\rho_{\kappa}\ \ \ \ \ \forall\kappa\in \mathcal{T}_{h}.\] (146)

_Remark A.1_.: When \(\mathcal{T}_{h}\) is regular, the error estimate (144) simplifies to:

\[|v-\pi v|_{m,\,q,\kappa}\leq Ch_{\kappa}^{k+1-m+N(1/q-1/p)}|v|_{k+1,\,p,\kappa} \ \ \ \ \ \forall v\in W^{k+1,\,p}(\kappa),\] (147)

where the constant \(C\) is independent of \(v\), \(h\) and \(\kappa\). Because of the inclusion

\[W^{k+1,\,p}(\hat{\kappa})\subset W^{m,\,q}(\hat{\kappa}),\]

we have:

\[k+1-m+N(1/q-1/p)\geq 0\]

and therefore the above factor \(h_{\kappa}\) can be bounded by \(h\).

Now, we fix the integer \(k\geq 1\) and we introduce the standard finite element spaces:

\[\Theta_{h}=\{\theta_{h}\in\mathcal{C}^{0}(\Omega);\,\theta_{h}|_{\kappa}\in P _{k}\ \ \ \forall\kappa\in\mathcal{T}_{h}\},\] (148)

\[\Phi_{h}=\Theta_{h}\cap H_{0}^{1}(\Omega).\]

Note that they are both finite-dimensional subspaces of \(W^{1,\,\infty}(\Omega)\); but their
