degrees of freedom. On the other hand, each component \(p\) of \(\mathcal{P}_{l}(\kappa)\) belongs to a space of dimension:

\[\dim(P_{l})+\dim(\vec{P}_{l-2})+\dim(\vec{P}_{l-3}),\quad\text{all in } \mathbb{R}^{3}\] \[=(1/6)(l+1)(l+2)(l+3)+(1/2)(l-1)l+(1/2)(l-2)(l-1)\] \[=(1/6)\{(l^{2}-1)(l+12)+24\}.\]

Recalling the argument of Lemma 2.3, it is an easy matter to prove that these degrees of freedom are \(\mathcal{P}_{l}(\kappa)\)-unisolvent.

**Lemma 2.12**.: _Each component \(p\) of a polynomial of \(\mathcal{P}_{l}(\kappa)\) is uniquely determined by the degrees of freedom (2.49a) (2.49b) or (2.49a) (2.49c). Moreover, on a given face of \(\kappa\), \(p\) depends exclusively upon the degrees of freedom defined on that face._

This lemma yields the following interpolation operator:

\[r_{h}\mathbf{v}|_{\kappa}=r_{\kappa}\mathbf{v}\quad\quad\forall\kappa\in \mathcal{T}_{h}\quad\quad\forall\mathbf{v}\in\mathcal{C}^{0}(\bar{\Omega})^{3},\]

where \(r_{\kappa}\mathbf{v}\) is the only polynomial of \(\mathcal{P}_{l}(\kappa)\) that has the same degrees of freedom (2.49a) (2.49c) as the function \(\mathbf{v}\). Obviously, the operator \(r_{\kappa}\) is invariant under affine transformations and as a consequence we have the following result:

**Lemma 2.13**.: _The operator \(r_{h}\) belongs to \(\mathcal{L}(\mathcal{C}^{0}(\bar{\Omega})^{3};W_{h})\cap\mathcal{L}([\mathcal{ C}^{0}(\Omega)\cap H^{1}_{0}(\Omega)]^{3};\)\(X_{h})\). In addition, if the triangulation \(\mathcal{T}_{h}\) is regular, \(r_{h}\) has the following interpolation error_:__

(2.50) \[|\mathbf{v}-r_{h}\mathbf{v}|_{m,\Omega}\leqslant Ch^{k+1-m}|\mathbf{v}|_{k+1 ,\Omega}\quad\quad\forall\mathbf{v}\in H^{k+1}(\Omega)^{3},\quad\quad m=0\quad or \quad 1,\]

\(1\leqslant k\leqslant l\)_, with a positive constant \(C\) independent of \(h\) and \(\mathbf{v}\)._

Like for the second-order scheme, the proof of the inf-sup condition here is trivially similar to that of Theorem 2.2. The local spaces involved are

\[X_{h}(\kappa)=\{\mathbf{v}\in\mathcal{P}_{l}(\kappa);\,\mathbf{v}|_{\partial \kappa}=\mathbf{0}\},\]

\[M_{h}(\kappa)=P_{l-1}\cap L^{2}_{0}(\Omega)\]

and the salient property that links them is:

\[\lambda_{1}\lambda_{2}\lambda_{3}\lambda_{4}\operatorname{\mathbf{grad}}q\in X _{h}(\kappa)\quad\quad\forall q\in M_{h}(\kappa).\]

Hence the statement of Lemma 2.11 carries over to the pair \((X_{h},M_{h})\) defined by (2.47) (2.48).

Again Hypothesis H2 follows from the approximation property of the \(L^{2}\)-projection operator \(\rho_{h}\) onto \(Q_{h}\):

\[\|q-\rho_{h}q\|_{0,\Omega}\leqslant Ch^{k}|q|_{k,\Omega}\quad\quad\forall q \in H^{k}(\Omega),\quad\quad 1\leqslant k\leqslant l.\]

Collecting these results, we obtain the desired estimate for this last scheme.
