Proof.: \(1^{\circ}\)) The idea of the proof is very similar to that of Theorem II.1.1. The existence and uniqueness of the solution \(u_{h}\) of Problem (P\({}_{h}\)) follow from (1.20) and Lax & Milgram's Theorem I.1.7, provided \(V_{h}(\gamma)\) is not empty.

Now, let \(w_{h}\) be any element of \(V_{h}(\chi)\) and let \(v_{h}=u_{h}-w_{h}\in V_{h}\). Then formula (II.1.15) holds:

\[\tilde{a}(v_{h},v_{h})=\tilde{a}(u-w_{h},v_{h})+\tilde{b}(v_{h},\lambda-\mu_{h} )\quad\quad\forall\mu_{h}\in M_{h},\quad\quad\forall w_{h}\in V_{h}(\chi).\]

Thus (1.20) implies:

\[\alpha^{*}\|v_{h}\|_{\tilde{\chi}}\leq\|\tilde{a}\|\,\|u-w_{h}\|_{\tilde{\chi} }+\sup_{v_{h}\in V_{h}}\biggl{\{}\frac{\tilde{b}(v_{h},\lambda-\mu_{h})}{\|v_{ h}\|_{\tilde{\chi}}}\biggr{\}}\quad\quad\forall\mu_{h}\in M_{h},\quad\quad \forall w_{h}\in V_{h}(\chi)\]

and this gives immediately (1.22).

\(2^{\circ}\)) Since the dimension of \(M_{h}\) is finite, the condition (1.21) implies the classical inf-sup condition on \(M_{h}\), eventually with a constant that depends upon \(h\). Therefore \(V_{h}(\chi)\) is not empty and Problem (Q\({}_{h}\)) has exactly one solution \((u_{h},\lambda_{h})\) where \(u_{h}\) satisfies Problem (P\({}_{h}\)). Moreover, the following equality holds for any \(v_{h}\) in \(X_{h}\) and \(\mu_{h}\) in \(M_{h}\):

\[\tilde{b}(v_{h},\lambda_{h}-\mu_{h})=\tilde{a}(u-u_{h},v_{h})+\tilde{b}(v_{h} ,\lambda-\mu_{h}).\]

Then it stems from (1.21) that:

\[\beta^{*}\|\lambda_{h}-\mu_{h}\|_{M}\leq\|\tilde{a}\|\,\|u-u_{h}\|_{\tilde{ \chi}}+\|\tilde{b}\|\,\|\lambda-\mu_{h}\|_{\tilde{\Lambda}}\]

and (1.23) is established. 

Note that the estimate (1.23) is not optimal inasmuch as it gives an upper bound for \(\|\lambda-\lambda_{h}\|_{M}\) in terms of \(\|\lambda-\mu_{h}\|_{\tilde{\Lambda}}\) while the two norms are usually not meant to be equivalent. The examples of SS 3 will show how to overcome this defect.

Observe also that it is often difficult to evaluate directly an expression like

\[\inf_{v_{h}\in V_{h}(\chi)}\|u-v_{h}\|_{\tilde{\chi}}.\]

Like in Chapter II, it is possible to reduce this term to the approximation error in \(X_{h}\) although here the process is not always optimal. As \(M_{h}\) is finite-dimensional, there exists a constant \(K(h)>0\) such that

\[\|\mu\|_{\tilde{\Lambda}}\leq K(h)\|\,\mu\|_{M}\quad\quad\forall\mu\in M_{h}.\]

With this we readily prove the following result.

**Corollary 1.1**.: _With the assumptions_ (1.20) _and_ (1.21) _each \(v\) in \(V(\chi)\) satisfies:_

\[\inf_{v_{h}\in V_{h}(\chi)}\|v-v_{h}\|_{\tilde{\chi}}\leq[1+K(h)(\|\,\tilde{b} \|/\beta^{*})]\inf_{v_{h}\in X_{h}}\|v-v_{h}\|_{\tilde{\chi}}.\]

_Furthermore_, _there exists a constant \(C>0\)_, _depending solely upon \(\alpha^{*}\)_, \(\beta^{*}\)_, \(\|\tilde{a}\|\) and \(\|\tilde{b}\|\) such that_:
