Therefore, \(\phi_{h}\) has the following decomposition:

\[\phi_{h}=r_{h}\mathbf{w}+\mathbf{grad}\,p_{h}.\]

Then, applying (5.12) with \(q_{h}=p_{h}\) we easily derive

\[\left\|\phi_{h}\right\|_{0,\Omega}\leq\left\|r_{h}\mathbf{w}\right\|_{0,\Omega}.\]

Thus, (5.14) will be established if we show that

(5.45) \[\left\|r_{h}\mathbf{w}\right\|_{0,\Omega}\leq C^{\star}\left\|\mathbf{curl} \,\phi_{h}\right\|_{0,\Omega}.\]

Now (5.39) and (5.44) yield:

\[\left\|\mathbf{w}-r_{h}\mathbf{w}\right\|_{0,\Omega}\leq C_{2}h\left\|\mathbf{ curl}\,\phi_{h}\right\|_{0,s,\Omega}.\]

But since \(\mathcal{T}_{h}\) is uniformly regular and \(\phi_{h}\) is a polynomial on each \(\kappa\), we easily obtain from (5.30) and (A.34):

\[\left\|\mathbf{curl}\,\phi_{h}\right\|_{0,s,\Omega}\leq C_{3}h^{3(1/s-1/2}) \left\|\mathbf{curl}\,\phi_{h}\right\|_{0,\Omega}.\]

Therefore

\[\left\|\mathbf{w}-r_{h}\mathbf{w}\right\|_{0,\Omega}\leq C_{4}h^{\star} \left\|\mathbf{curl}\,\phi_{h}\right\|_{0,\Omega}\]

with a non negative exponent \(\alpha\) as long as \(2<s\leq 6\). This proves (5.45). 

**Corollary 5.1**.: _Let \(\Omega\) be an open, bounded polyhedron of \(\mathbb{R}^{3}\). For each function \(\mathbf{w}_{h}\) of \(\Phi_{h}\) there exists a unique function \(\mathbf{v}_{h}\) in \(\Phi_{h0}\) and \(p_{h}\) in \(\Theta_{h}\) such that:_

(5.46) \[\begin{split}\mathbf{w}_{h}=\mathbf{v}_{h}+\mathbf{grad}\,p_{h} ,\\ |p_{h}|_{1,\Omega}\leq\left\|\mathbf{w}_{h}\right\|_{0,\Omega}. \end{split}\]

_Moreover, under the assumptions of Proposition 5.1_, \(\mathbf{v}_{h}\) is bounded as follows:_

(5.47) \[\left\|\mathbf{v}_{h}\right\|_{H(\mathbf{curl},\Omega)}\leq(1+C^{\star}{}^{2 })^{1/2}\left\|\mathbf{curl}\,\mathbf{w}_{h}\right\|_{0,\Omega}.\]

Proof.: Let us take for \(p_{h}\) the unique solution in \(\Theta_{h}\) of

\[(\mathbf{grad}\,p_{h},\mathbf{grad}\,q_{h})=(\mathbf{w}_{h},\mathbf{grad}\,q_ {h})\quad\quad\forall q_{h}\!\in\!\Theta_{h}.\]

Then the difference

\[\mathbf{v}_{h}=\mathbf{w}_{h}-\mathbf{grad}\,p_{h}\]

belongs to \(\Phi_{h0}\) and (5.47) follows immediately from Proposition 5.1. 

Observe that the first part of this corollary establishes (5.17).

From Lemmas 5.1 and 5.2, Theorems 5.1, 5.2 and 5.4, Proposition 5.1 and Corollary 5.1, we derive the major result of this section.

**Theorem 5.5**.: _Let \(\Omega\) be a bounded polyhedron in \(\mathbb{R}^{3}\). Then Problems (5.15) and (5.16) associated with the choice of finite element spaces (5.36) and (5.43) are equivalent and have a unique solution \(u_{h}=(\mathbf{curl}\,\psi_{h},\omega_{h})\)._
