**Lemma 3.2**.: _Assume the hypotheses of Theorem 2.4. Then, if \((\mathbf{u},p)\) is the unique solution of Problem (2.20), \(u=(\mathbf{u},p/v)\) is a nonsingular solution of (3.1)._

Proof.: First, using the notations of Paragraph 2.1, we note that a variational form of Problem (3.10) consists in finding a pair \((\mathbf{v},q)\!\in\!H^{1}(\Omega)^{N}\times L_{0}^{2}(\Omega)\) solution of

(3.11) \[\left\{\begin{aligned} a(\mathbf{u};\mathbf{v},\mathbf{z})+a_{1}( \mathbf{v};\mathbf{u},\mathbf{z})-(q,\operatorname{div}\mathbf{z})& =\langle\mathbf{f}_{\star},\mathbf{z}\rangle\quad\quad\forall \mathbf{z}\!\in\!H_{0}^{1}(\Omega)^{N},\\ \operatorname{div}\mathbf{v}=0&\quad\text{in }\Omega,\\ \mathbf{v}=\mathbf{g}_{\star}&\quad\text{on }\Gamma.\end{aligned}\right.\]

In order to check that the equations (3.11) have a unique solution, it is sufficient to prove that the bilinear form

\[(\mathbf{v},\mathbf{z})\to c(\mathbf{v},\mathbf{z})=a(\mathbf{u}; \mathbf{v},\mathbf{z})+a_{1}(\mathbf{v};\mathbf{u},\mathbf{z})\]

is \(V\)-elliptic. But it follows from (2.5) that

\[c(\mathbf{v},\mathbf{v})=v|\mathbf{v}|_{1,\Omega}^{2}+a_{1}(\mathbf{v}; \mathbf{u},\mathbf{v})\quad\quad\forall\mathbf{v}\!\in\!V.\]

Now, assume that \(v\!>\!v_{0}\) where \(v_{0}\) is defined by (2.24). Then, there exists a function \(\mathbf{u}_{0}\!\in\!H^{1}(\Omega)^{N}\) such that

\[\operatorname{div}\mathbf{u}_{0}=0,\quad\quad\mathbf{u}_{0}|_{ \Gamma}=\mathbf{g},\] \[v>\rho(\mathbf{u}_{0})+(\mathcal{N}\|l(\mathbf{f};\mathbf{u}_{0 })\|_{\mathcal{V}})^{1/2}.\]

Next, setting \(\mathbf{u}=\mathbf{u}_{0}+\mathbf{w}\), we have by (2.10) and (2.22)

\[|a_{1}(\mathbf{v};\mathbf{u},\mathbf{v})| \leqslant|a_{1}(\mathbf{v};\mathbf{u}_{0},\mathbf{v})|+|a_{1}( \mathbf{v};\mathbf{w},\mathbf{v})|\] \[\leqslant(\rho(\mathbf{u}_{0})+\mathcal{N}|\mathbf{w}|_{1,\Omega })|\mathbf{v}|_{1,\Omega}^{2}.\]

Since (cf. Remark 2.1)

\[|\mathbf{w}|_{1,\Omega}\leqslant\frac{\|l(\mathbf{f};\mathbf{u}_{0})\|_{ \mathcal{V}}}{v-\rho(\mathbf{u}_{0})},\]

we obtain

\[c(\mathbf{v},\mathbf{v}) \geqslant\bigg{(}v-\rho(\mathbf{u}_{0})-\frac{\mathcal{N}\|l( \mathbf{f};\mathbf{u}_{0})\|_{\mathcal{V}}}{v-\rho(\mathbf{u}_{0})}\bigg{)}| \mathbf{v}|_{1,\Omega}^{2}\] \[=(v-\rho(\mathbf{u}_{0}))\bigg{(}1-\frac{\mathcal{N}\|l(\mathbf{ f};\mathbf{u}_{0})\|_{\mathcal{V}}}{(v-\rho(\mathbf{u}_{0}))^{2}}\bigg{)}| \mathbf{v}|_{1,\Omega}^{2},\]

so that the ellipticity property holds. 

In the subsequent paragraphs, we shall be essentially concerned with the approximation of branches of nonsingular solutions \(\{(\lambda,u(\lambda)=(\mathbf{u}(\lambda),\lambda p(\lambda)));\lambda\!\in \!\Lambda\}\) of the Dirichlet problem for the Navier-Stokes equations where the parameter \(\lambda=1/v\) plays the role of the Reynolds number.
