constraint (5.12) on the test functions \(\phi_{h}\). Therefore we shall use instead the following approximation of Problem (\(\widetilde{Q}\)) which works with the entire space \(\Phi_{h}\):

_Find a pair \((\psi_{h},\omega_{h})\!\in\!\Phi_{h0}\,\times\,M_{h}\) satisfying:_

(5.16) \[\begin{cases}v(\operatorname{\mathbf{curl}}\omega_{h},\operatorname{\mathbf{ curl}}\phi_{h})=(\mathbf{f},\operatorname{\mathbf{curl}}\phi_{h})&\quad\forall \phi_{h}\!\in\!\Phi_{h},\\ (\operatorname{\mathbf{curl}}\psi_{h},\operatorname{\mathbf{curl}}\psi_{h})=( \omega_{h},\mu_{h})&\quad\forall\mu_{h}\!\in\!M_{h}.\end{cases}\]

Obviously, it is desirable that these two problems be equivalent; but this requires an additional hypothesis:

_for each function \(\phi_{h}\) of \(\Phi_{h}\) there exists a function \(\phi_{h0}\) of \(\Phi_{h0}\) with_

(5.17) \[\operatorname{\mathbf{curl}}\phi_{h}=\operatorname{\mathbf{curl}}\phi_{h0}.\]

Clearly, (5.17) implies the equivalence between Problems (5.15) and (5.16).

As far as the solution of these problems is concerned, uniqueness implies existence, for (5.15) is a square system of linear equations. Like in the continuous case, we readily infer this existence from (5.14) and the inclusion \(\Phi_{h}\subset M_{h}\). Hence we have the following result.

**Lemma 5.1**.: _Let the spaces \(\Phi_{h}\), \(M_{h}\) and \(\Theta_{h}\) satisfy (5.11) with \(\Phi_{h}\subset M_{h}\) and let \(\Phi_{h0}\) be defined by (5.13). Under the hypothesis (5.14), Problem (\(Q_{h}\)) has a unique solution \((\psi_{h},\omega_{h})\) in \(\Phi_{h0}\,\times\,M_{h}\). If, in addition the hypothesis (5.17) holds, then Problem (5.16) is equivalent to Problem (\(Q_{h}\))._

It is possible to derive directly an error bound for the solution of (\(Q_{h}\)), but it is easier and more satisfactory to place this problem into the setting of Section 1.2 and use Theorem 1.2. Here, there is a slight difficulty because the natural discretization of \(\widetilde{X}\colon(\operatorname{\mathbf{curl}}\Phi_{h0})\,\times\,M_{h}\) is not contained in \(\widetilde{X}\). However we can make use of Remark 5.2 and observe that the crucial spaces of Problem (5.8) are in fact \(H_{0}(\operatorname{\mathbf{curl}};\Omega)\,\times\,L^{2}(\Omega)^{3}\) and \(\widetilde{V}\). Thus, we take

(5.18) \[X_{h}=\langle\operatorname{\mathbf{curl}}\phi_{h};\phi_{h}\! \in\!\Phi_{h0}\rangle\,\times\,M_{h}\subset\langle\operatorname{\mathbf{curl}} \phi;\phi\!\in\!H_{0}(\operatorname{\mathbf{curl}};\Omega)\rangle\,\times\,L ^{2}(\Omega)^{3},\] (5.19) \[V_{h}=\{(\operatorname{\mathbf{curl}}\phi_{h},\theta_{h})\!\in\! X_{h};(\operatorname{\mathbf{curl}}\phi_{h},\operatorname{\mathbf{curl}}\mu_{h})=( \theta_{h},\mu_{h})\quad\forall\mu_{h}\!\in\!M_{h}\}.\]

Of course, \(V_{h}\) is generally not included in \(\widetilde{V}\) but if \(\Phi_{h}\subset M_{h}\) and if (5.14) holds then we have the analogue of (5.10):

(5.20) \[\|\operatorname{\mathbf{curl}}\phi_{h}\|_{0,\,\Omega}\,\leqslant\,C^{\star}\| \,\theta_{h}\|_{0,\,\Omega}\quad\quad\forall v_{h}=(\operatorname{\mathbf{ curl}}\phi_{h},\theta_{h})\!\in\!V_{h},\]

which means that the mapping \(v_{h}=(\operatorname{\mathbf{curl}}\phi_{h},\theta_{h})\to\|\,\theta_{h}\|_{0, \,\Omega}=|v_{h}|\) is an equivalent norm on \(V_{h}\).

With this notation, _Problem_ (\(Q_{h}\)) becomes:

_Find a pair \((u_{h},\lambda_{h})\!\in\!X_{h}\times\,M_{h}\) such that_

\[\tilde{a}(u_{h},v_{h})+\tilde{b}(v_{h},\lambda_{h})=\langle l,v_{h}\rangle \quad\quad\forall v_{h}\!\in\!X_{h},\] \[\tilde{b}(u_{h},\mu_{h})=0\quad\quad\forall\mu_{h}\!\in\!M_{h}.\]

Then we can easily apply the argument of Theorem 1.2 and derive the next result.
