eral finite elements whereas in general Lemma A.7 holds here only when \(m\leqslant 1\). Nevertheless these two values of \(m\) are sufficient for subsequent applications.

_Remark A.5_.: It is sometimes very useful to construct triangulations which contain triangles as well as quadrilaterals. All the results which are valid for _both triangles and quadrilaterals_ can be applied to these triangulations.

### Interpolation of Discontinuous Functions

The interpolation of \(L^{1}\) functions was first analyzed by Clement [21] who proposed a local regularization operator. This technique was later generalized by Bernardi [9] who introduced more general finite elements in order to interpolate essentially functions that were either discontinuous or that were defined on domains with curved boundaries. We have no space here to describe "curved" finite elements but we shall discuss briefly the interpolation of functions that are not supposed to be continuous. For the sake of simplicity, _we shall restrict ourselves to the finite element space \(\Theta_{h}\) defined by (A.18) on triangular finite elements_. The forthcoming results are valid for higher dimensions and quadrilateral finite elements and also for spaces with other boundary conditions, like for example \(\Theta_{h}\cap H^{1}_{0}(\Omega)\).

Let \(\mathcal{T}_{h}\) be the triangulation of \(\Omega\) corresponding to \(\Theta_{h}\) and let

\[\Sigma_{h}=\bigcup_{\kappa\in\mathcal{T}_{h}}\Sigma_{\kappa}=\{a_{i};\,1 \leqslant i\leqslant N_{h}\},\]

all the points \(a_{i}\) being distinct. For each integer \(i\), \(1\leqslant i\leqslant N_{h}\), there exists exactly one function \(\theta_{i}\!\in\!\Theta_{h}\) such that

\[\theta_{i}(a_{j})=\delta_{ij},\quad\ 1\leqslant j\leqslant N_{h}.\]

The set \(\{\theta_{i};\,1\leqslant i\leqslant N_{h}\}\) is a basis of \(\Theta_{h}\). Now, for each \(i\), let

(A.52) \[\begin{cases}\mathcal{A}_{i}=\bigcup\,\{\kappa\!\in\!\mathcal{T}_{h};\,\text {supp}(\theta_{i})\cap\kappa\neq\phi\},\\ \quad=\bigcup\,\{\kappa\!\in\!\mathcal{T}_{h};\,a_{i}\!\in\!\kappa\}.\end{cases}\]

If the triangulation \(\mathcal{T}_{h}\) is regular, it can be shown that on the one hand, the number of triangles \(\kappa\) in \(\mathcal{A}_{i}\) is bounded by a constant, say \(M\), independent of \(h\) and \(i\); on the other hand, the number of macro-elements \(\mathcal{A}_{i}\) containing a given triangle \(\kappa\) is also bounded by a constant independent of \(\kappa\) and \(h\). In addition, for any pair of triangles \(\kappa\) and \(\kappa^{\prime}\) in the same macro-element \(\mathcal{A}_{i}\) we have:

\[h_{\kappa}\leqslant Ch_{\kappa}.\quad\text{with a constant $C$ independent of $h$ and $i$.}\]

Thus, the macro-elements \(\mathcal{A}_{i}\) can only assume a _finite number of different configurations_. To each configuration, there corresponds a reference region \(\hat{\mathcal{A}}_{i}\), contained in the unit \(\operatorname{disc}\{\hat{x};\,\|\,\hat{x}\|\leqslant 1\}\), and composed of at most \(M\) equal triangles with a common vertex at \(\hat{x}=0\) (see the example of Figure 6). Further
