following Green's formula for all \(p\in L(\lambda;\Omega)\):

\[(\lambda p,\mu)=(p,\lambda\mu)-\int_{\Gamma}(\gamma p)\partial\mu/\partial n\,ds \quad\quad\forall\mu\in H^{2}(\Omega)\cap H^{1}_{0}(\Omega).\]

Collecting these results, we find that Problems (4.38a) and (4.40) are equivalent, have a unique solution \(p(g)\) for each \(g\) in \(G\) and

(4.42) \[[1/(\sqrt{N}\,C_{1})]\,\|\,g\,\|_{-1/2,\,\Gamma}\leq\|\,p(g)\|_{0,\,\Omega} \leq C_{3}\|\,g\,\|_{-1/2,\,\Gamma}\quad\quad\forall g\in G.\]

Next, we write Problem (4.38b) in variational form:

(4.43) \[v(\mathbf{grad}\,\mathbf{u}(g),\mathbf{grad}\,\mathbf{v})=(p(g),\mathrm{div} \,\mathbf{v})\quad\quad\forall\nu\in H^{1}_{0}(\Omega)^{N}.\]

From this and Corollary I.2.4 we derive immediately that

(4.44) \[(C_{1}/v)\,\|\,p(g)\|_{L^{2}(\Omega)/\mathbb{R}}\leq|\mathbf{u}(g)|_{1,\, \Omega}\leq(\sqrt{N}/v)\,\|\,p(g)\|_{L^{2}(\Omega)/\mathbb{R}}.\]

Thus, combining (4.42) and (4.44) and using the fact that

\[p(g+c)=p(g)+c\]

we obtain

(4.45) \[\frac{C_{4}}{v\sqrt{N}\,C_{1}}\inf_{c\,\in\,\mathbb{R}}\|\,g+c\,\|_{-1/2,\, \Gamma}\leq|\mathbf{u}(g)|_{1,\,\Omega}\leq(\sqrt{N}/v)C_{3}\inf_{c\,\in\, \mathbb{R}}\|\,g+c\,\|_{-1/2,\,\Gamma}\]

Finally, by substituting (4.43) into (4.39) we derive:

\[v(\mathbf{grad}\,\mathbf{u}(\rho),\mathbf{grad}\,\mathbf{u}(l))=-(\mathrm{div }\,\mathbf{u}^{0},p(l))\quad\quad\forall l\in G.\]

In other words, with the notation

(4.46) \[a(\rho,l)=v(\mathbf{grad}\,\mathbf{u}(\rho),\mathbf{grad}\,\mathbf{u}(l)),\]

Problem (4.39) reads:

_Find \(\rho\) in \(G/\mathbb{R}\) such that_:

(4.47) \[a(\rho,l)=-(\mathrm{div}\,\mathbf{u}^{0},p(l))\quad\quad\forall l\in G/ \mathbb{R}.\]

Clearly, in view of (4.44) and (4.45) this problem has a unique solution. Note also that the bilinear form \(a(.,.)\) is symmetric.

The above results are summarized in the following theorem.

**Theorem 4.5**.: _Let \(N=2\) or \(3\). Assume that \(\Omega\) is bounded with either a \(\mathcal{C}^{1,\,1}\) boundary or a polygonal boundary with no reentrant corners. For \(\mathbf{f}\) given in \(L^{2}(\Omega)^{N},\) the solution \((\mathbf{u},p)\) of the Stokes system (4.1) can be split into_:__

\[\mathbf{u}=\mathbf{u}^{0}+\mathbf{u}(\rho),\quad\quad p=p^{0}+p(\rho),\]

_where \(\rho\) is the unique solution of Problem (4.47) and the pairs \((\mathbf{u}^{0},p^{0}),\)\((\mathbf{u}(\rho),p(\rho))\) are the only solutions of (4.37) and (4.38) respectively._
